tobymao/18xx

assets/js/view/auction_round.rb, lib/engine/round/auction.rb, spec/lib/engine/round/auction_spec.rb
Right now, you can bid on the cheapest private rather than buy it outright. The existing bid action is already designed to let you purchase the private in that situation, so this change is really just changing the way the action gets rendered.
=> Allow for purchasing the cheapest private if it has no bids

assets/js/view/buy_trains.rb, assets/js/view/company.rb, assets/js/view/corporation.rb, assets/js/view/player.rb, assets/js/view/sell_shares.rb, lib/engine/game/base.rb, lib/engine/game/g_1889.rb, lib/engine/round/auction.rb, lib/engine/round/base.rb, lib/engine/round/operating.rb, lib/engine/share_pool.rb, spec/lib/engine/share_pool_spec.rb
Currency values are now printed as `$<val>` by default but can be customized per title (e.g., `¥<val>` for 1889).
=> Format currency based on game title

assets/js/view/tile_selector.rb
Makes the tiles being chosen hover a little over the background map, making it more clear that they're temporary.
=> Add drop shadow to tile selector

lib/engine/game/base.rb
This addresses half of #19. The other half (to come) is to call out who has priority deal on the player cards.
=> At end of auction/stock round, log priority deal

assets/js/view/player.rb
The active player card gets a black border and a green shade. As usual, I won't be offended if this is replaced by a different design, but I do think it's important to call out the active player clearly in some way.
=> Call out active player

assets/js/view/game.rb
I also got rid of the line that just said "Players" since it mostly acted as clutter and nothing else (corporations, stock market) is labeled anyway.
=> Add vertical space between elements on game screen

api.rb, assets/js/app.rb, assets/js/lib/hex.rb, assets/js/view/all_tiles.rb, assets/js/view/hex.rb, assets/js/view/part/city.rb, assets/js/view/tile.rb, assets/js/view/tiles.rb, assets/js/view/triangular_grid.rb, lib/engine/company.rb, lib/engine/tile.rb
* Cities with 2 or 3 slots have boxes now (per https://github.com/tobymao/18xx/issues/2#issuecomment-614425795)
* the 3-slot solution is lazily scaling down the full-size hexagon
* cities with 4+ slots still don't have a box, but 1889 doesn't use those
* add new route/page at `/all_tiles`, to show all defined tiles
* also shows all custom starting hexes defined for 1889 (including corporations and company blockers)
* company blocker is now rendered on map even before it is bought during the private auction
=> City boxes, "all tiles" page, show company blocker on tile even before it is bought in the private auction

assets/js/view/pass_button.rb, lib/engine/round/auction.rb, lib/engine/round/base.rb, lib/engine/round/operating.rb, lib/engine/round/stock.rb
Pass has a specific game meaning in the initial stock round and in stock rounds.
Passing when in the operating round moves to the next step.
Use 'Pass' when this has the specific in game meaning
"Don't" when the user wishes to skip to the next action
"Done" when the user has taking an action in this step (Done Buying Trains)
Resolves #63
=> Make Pass be more descriptive (Pass for real passes, Don't or Done otherwise)

lib/engine/round/operating.rb
Log messages of the form `<president> operates <corporation>` at the beginning of each corporation's turn during the OR, making the gameflow in the log easier to follow.
=> Log when corporation operates, including president

assets/app/view/stock_market.rb
Single tokens are centered horizontally. Multiple tokens are placed so that the left and right margins are equal. Everything is calculated instead of using magic numbers, so the code is less brittle for any future changes.
There are a lot of constants here and some of them could be folded into others. My experience with this sort of code has been that the most important thing is the clarity of the intermediate calculations, so I like to leave everything in, but we can do whatever fits the project's style best.
=> Improve stock market token spacing

assets/app/view/part/town_rect.rb
The calculation of normalized edges need to grab the min, then make
sure our diff is valid, and then swap them again to make sure a < b.
Prior to this change edges 4 and 0 would result in normalized edges
of 0 and 10 throwing off the type calculation.
Fixes #58
=> fix: Fix track type calcation

assets/app/view/corporation.rb
- IPO/market count/price display is condensed and put into a table
- Ownership by players is displayed, including presidency
- Value of privates has been removed, since it's irrelevant once owned by a corporation
=> New corp card design, including shareholders

assets/app/view/part/track.rb, assets/app/view/route_selector.rb
Give more information about the route while the user is selecting it
Also makes the route colours colourblind safe
Valid route example
Invalid route example
fixes #98
=> Add per train route information while selecting routes

assets/app/view/player.rb
New format, from top to bottom:
- Just player name in top stripe (like corporation cards) and turn order
- Stats (cash, value, certs) on left, shares on right (if no shares owned, just stats, centered)
- Privates, if any
Another new feature is that the cert display is in red if the player's over the limit.
Goals of this design:
- Remove clutter (both stats and field names) from header, so the eye is immediately drawn to the player name
- Avoid tons of blank space once the privates have been bought in
- Don't need to truncate private names
The one thing I'm still not totally happy with is the 1st, 2nd, 3rd denoting turn order, which is easily misinterpretable as "1st place", "2nd place", etc. If "Priority Deal" or "Priority" is not too confusing to newer players, I'd prefer to just label a …
=> New player card design

lib/engine/round/auction.rb
The awkward structure (`@log` on the outside) and indentation are because rubocop complained when I wrote the code more naturally.
The last two cases could be folded into common code as they stand but I'm not sure those two messages will always want to remain almost identical.
=> Differentiate ways of winning an auction in log (fixes #327)

lib/engine/share_pool.rb
Remove redundant presidency announcement. Previously the log would look like
```
dfan pars TR at ¥65 and becomes the president
dfan buys a 20% share of TR from the IPO for ¥130
dfan becomes the president of TR
```
=> Don't log presidency when setting par

assets/app/view/corporation.rb
They used to be right-aligned; this looks much nicer (I claim).
=> Center fields in corporation card header

lib/engine/round/auction.rb
The code for #337 (in an upcoming PR) wants `@last_to_act` on a round with players (auction, stock) to reliably refer to the player who most recently effectively passed the priority deal card to their left by taking a non-pass action. The auction code overloaded this instance variable in order to handle turn order both during top-level bidding and when coming out of set of limited auctions.
The state necessary to handle auction turn order has now been broken out into `@last_to_act` (which now has the desired meaning defined above) and `@auction_triggerer` (the player who triggered a set of limited auctions by buying the lowest company outright).
In passing I also fixed a bug where the "Company goes up for auction" message could get logged multiple times if there were more than two players …
=> Separate @auction_triggerer and @last_to_act

assets/app/view/corporation.rb
Players who have sold shares of that corporation this round have their share count in red. If they have no shares left, they're still included with a share count of 0.
We could do the same thing on player cards but I think this is sufficient. I'm happy to try it out, though.
The formatting is a little awkward to appease rubocop (overly long line means it wants the block to be multiline, which means it wants it to use do/end, which means it doesn't like chaining it). This was the best compromise I could negotiate between me and rubocop, but rewriting suggestions are welcome.
=> On corp card, call out players who have sold shares (implements #292)

assets/app/lib/tile_selector.rb
fixes #41 
tested the fix on Edge, Chrome and Firefox
=> Edge doesn't seem to support x & y, but left and top are aliases for it

lib/engine/game/base.rb, spec/lib/engine/games/g_1889_spec.rb
The check for finishes was before undo processing.
fixes #374
fixes #372
=> Move finished check after undo and ignore for messages

assets/app/view/create_game.rb, lib/engine.rb, lib/engine/game/base.rb, lib/engine/game/g_1889.rb
I thought separating this out from the rest of the opal pinning would be sensible.
It adds the following messages to the top of the log
For dev purposes if you do http://localhost:9292/new_game?all you can see all the games not just those marked alpha and above, 1889 is the only game visible at the moment.
=> Add warnings about alpha and beta quality games on initialization

lib/engine/round/stock.rb
```
sparr buys a 10% share of UR from the IPO for ¥90
sparr sells 4 shares UR and receives ¥440
UR's share price changes from ¥110 to ¥80
sparr passes buying shares
```
This came up in a game recently and sounded wrong. I have changed the logic so that it says you are passing buying if you could still buy, passing selling if you have bought.
=> Change logic for share pass wording

lib/engine/config/game/g_1889.rb
Going through the 1889 tutorial, I'm pretty sure I found a typo.
This PR changes
"outside of the operating rounds of a company **controller** by another player"
to
"outside of the operating rounds of a company **controlled** by another player"
=> Fix typo in Mitsubishi Ferry description

assets/app/view/create_game.rb
Fixes tobymao/18xx#71
After I prevented strict duplicates, I realized it was still possible to add names that would appear identical such as `<space>Player<space>1` and `Player<space><space>1`. So I added a second commit to trim whitespace out of the name. That took the longest because I couldn't figure out why `.gsub(/[[:space:]]+/, " ")` wasn't working. Turns out it's not supported by Opel! 😢 
I haven't added any tests yet. I couldn't find anything existing in the `/spec` folder that mentioned the Hotseat feature or the CreateGame class. Let me know if that's a merge blocker.
=> Prevent duplicate Hotseat player names

lib/engine/config/game/g_18_chesapeake.rb, lib/engine/game/base.rb
- Removed P1's text saying that P1-P5 can be bought in, put text on P6 saying that it can't be bought in (this had immediately caused confusion in the multiplayer game I just started)
- Fixed some spacing and typos
- Made the use of "company" and "corporation" consistent with the rest of the site
- Made the random corporation text a little more clear
=> Improve Chesapeake private text

spec/assets_spec.rb
This is currently failing due to 18Chesapeake's company "blockers" being broken and not appearing on the map. Once that is fixed, these new/improved tests will pass and will be more useful.
=> Update /map render tests to check for every string that should be rendered on the map

lib/engine/hex.rb, lib/engine/part/city.rb, spec/lib/engine/hex_spec.rb
* fix how tokens and reservations are moved from cities on one tile to the upgrade tile
* add corporation name to `place_token` error
* rewrite existing OO specs such that additional specs can be added by adding hashes with the same structure to the list
* add spec exactly matching the scenario in #464 
* add spec for upgrading Baltimore from brown to gray
* add spec like #464, only with B&O only holding the reservation there, not having placed its token
=> Fix tokens in OO upgrades [Fixes #464]

lib/engine/config/game/g_1817.rb, lib/engine/config/game/g_1830.rb, lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_1889.rb, lib/engine/config/game/g_18_chesapeake.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1830.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1889.rb, lib/engine/game/g_18_chesapeake.rb
This uses the colors names from 18xx-maker in the game definition, which WILL pass through if not defined. This means if we don't define colors the svg will just use `red` or `green` and the like. However now you can call `register_colors` to define the colors for this game in the game file. I did it for 1889 and 18Chesapeake.
For 1889 and 18Chesapeake I used the colors currently used.
For 1846 and 1830 I used the GMT color scheme from 18xx-maker.
For 1817 I used every Rails on Board token color (one for each of the 20), we will probably change this if you want to use AAG's colors of course.
At least now changing that is just on your side 👍
=> feat: ability to define colors for a game

assets/app/view/game_card.rb
fixes #474
Please let me know if there's a more idiomatic way of doing this. I tried post-processing it, but this resulted in an extra space between the name and the succeeding comma:
`p_elm = p_elm.zip((',' * (p_elm.size - 1)).chars).flatten.compact`
=> [issue_474] game_card: comma-separate player names

DEVELOPMENT.md, assets/app/view/part/location_name.rb, assets/app/view/tile_manifest.rb, assets/app/view/tiles.rb, assets/app/view/tiles_page.rb
Also allow the `/tiles` routes that render one or more `+`-separated tiles to take URL params `r` and `n` to specify rotation and location name. `r` can be `all` or `+`-separated integers, and `n` will be applied to all tiles that do not already have a location name (e.g., `/tiles/1889/I4` will always render "Kotohira")
437 with rotation 3 still isn't ideal, but better than the current situation.
[Fixes #383]
[Fixes #404]
[Fixes #480]
=> Add special case for rendering location name with one town on tile, fixes tile 437 and 58

assets/app/view/tiles.rb
Was originally added with https://github.com/tobymao/18xx/commit/3af74892f41beed7cccec7c9894c7be80692dbdb, then accidentally (I presume) undone with https://github.com/tobymao/18xx/commit/f034cc3c3d07384ada590fb0dabc064d5fc9ab56.
=> Restore # prefix to tile IDs

DEVELOPMENT.md, assets/app/view/game.rb, assets/app/view/hex.rb, assets/app/view/part/base.rb, assets/app/view/part/blocker.rb, assets/app/view/part/city.rb, assets/app/view/part/label.rb, assets/app/view/part/location_name.rb, assets/app/view/part/revenue.rb, assets/app/view/part/single_revenue.rb, assets/app/view/part/town_rect.rb, assets/app/view/part/towns.rb, assets/app/view/part/track.rb, assets/app/view/part/upgrade.rb, assets/app/view/tile.rb, assets/app/view/tiles.rb, assets/app/view/tiles_page.rb, lib/engine/config/game/g_1817.rb, lib/engine/part/revenue_center.rb, lib/engine/round/auction.rb, lib/engine/route.rb, lib/engine/share_bundle.rb, lib/engine/tile.rb, spec/assets_spec.rb, spec/lib/engine/tile_spec.rb
This started as fix for town names getting in the way on the 1889 port tile and
other town tiles, especially double dit tiles in 18Chesapeake. The revenue was
the most troublesome tile part for rendering, and it wasn't long before I
decided to address the town problem by going after a revenue rendering idea I've
had for a while but hadn't acted on--render the revenue in a position relative
to the city/town, and do so for each city/town on OO/double-dits.
This imgur album has some screenshots showing the OO/double-dit work and the new
/tiles page - https://imgur.com/a/p46E9iJ
OO and Double Dits:
- all cities and towns render revenue circles right next to them; OO and double
dits now render two revenue circles on the tile
- create a Part::SingleRevenue class; View::Tile still uses …
=> Render revenue for each stop on OO/double-dits, various other changes

assets/app/view/hex.rb, lib/engine/config/game/g_18_chesapeake.rb, lib/engine/config/tile.rb, lib/engine/tile.rb
Necessary for 1846, useful for 18Chesapeake--render impassable water hexes instead of having an apparent gap in the map.
Probably necessary for the offboard port hex in 1882 (conceivably it could be a normal red offboard with some other indicator that it's a special port thing, but that would be suboptimal).
For 1846 and 18Chesapeake, routes should not be allowed to point to blue hexes, but they will have to in 1882.
What I've pushed here only draws the blue hex, it doesn't prevent track from being pointed to it, or prevent the hex from being clicked on during the track laying step (and doing so completely breaks the game)
=> Support for blue hexes

lib/engine/config/game/g_1882.rb
This information is required and must have been omitted by accident.
=> 1882: Add number of operating rounds to phases

lib/engine/config/game/g_1846.rb
1. Big 4 starting treasury is $40 not $60
2. Mention debt that must be paid off when purchasing.
=> Fix descriptions for Independent Railroads.

assets/app/game_manager.rb, assets/app/index.rb, assets/app/view/game_card.rb
This switches the `enter` button to use a Link class with an `href` attribute which can then be used to right-click and open the game in a new window/tab.
=> Switch enter button to link to allow opening in a new tab, closes #156

assets/app/view/game_log.rb
This PR enhances the game chat text box slightly to give it a bit more focus and fixes the input width :)
When I started a game, I did not realize that I could type in the box! See image:
[https://postimg.cc/K15Q4YLB](https://postimg.cc/K15Q4YLB)
=> Add spacing + user identification to game log/chat

assets/app/view/spreadsheet.rb, lib/engine/round/base.rb
So this is part of #291 where we first implement an operating order column for the spreadsheet tab. Companies that have already operated are marked with an `*`. Unfloated companies do not have an order and neither do companies in a stock/auction round.
See screenshots:
[https://postimg.cc/SYz8Lhrf](https://postimg.cc/SYz8Lhrf)
[https://postimg.cc/BLzH16xv](https://postimg.cc/BLzH16xv)
In the next iteration we could tackle sorting on the UI :)
=> Add company operating order to spreadsheet

assets/app/view/log.rb
Log is used in both chat and gameplay logs. The existing code
implemented scroll-to-bottom through CSS, which caused
problems with keyboard scrolling and copy-paste.
This commit removes the scroll-specific CSS, and replaces it
with a scroll_to_bottom lambda that is called in the postpatch
hook.
I'm new to Opal, so I have no idea if this is a reasonable solution!
Fixes #298 
Fixes #346
=> View::Log scrolls to bottom via JavaScript

assets/app/view/axis.rb, assets/app/view/map.rb, lib/engine/config/game/g_1846.rb, lib/engine/game/base.rb, lib/engine/hex.rb
screenshot album - https://imgur.com/a/zG4xN6B
by default, for pointy maps letters are rows and for flat maps letters are
columns; this can be overriden by defining AXES in the game class; for example,
this is what was used to generate the wonky 1889 screenshot:
```
AXES = { x: :number, y: :letter }.freeze
```
* update 1846 config (TODO: contribute back to 18xx-maker)
- no aliases, this allows the blue hexes to be blue
- rotate track appropriately
=> Map axes: allow letters to be rows or columns

lib/engine/corporation.rb, lib/engine/round/operating.rb
This fix adds a default operating information for any company that is operating.
The default is to withhold with a revenue of 0. This allows one to identify if a company has operated its turn or not. This is especially relevant for the spreadsheet view.
=> add default operating info, closes #618

assets/app/view/spreadsheet.rb
This PR allows sorting columns in the spreadsheet view. At the moment the following 3 columns are supported:
- Operating Order
- Cash
- Market price
The default is to sort by company symbol in ascending order (current view). The sort preferences are locally stored so they should be maintained over sessions :).
See screencast: [https://streamable.com/oobcg6](https://streamable.com/oobcg6)
=> Add sortable columns to spreadsheet view, closes #291

spec/lib/engine/tile_spec.rb
These specs were originally written as one test per upgrade to ensure the rspec
output would be useful, but the number of tests that created is not so useful.
Using aggregate_failures to group upgrades_to? tests by game gets the number of
tests to something more reasonable.
Using expected/actual strings instead of just the return value of
`upgrades_to?` (`true`/`false`) keeps the rspec output useful.
For these tests, `A < B` means "A upgrades to B" and `A !< B` means "A does not
upgrade to B"
=> change upgrades_to? specs to one test per game title

assets/app/view/form.rb
+ placeholder:
+ label_props
+ for on label
+ id on input
for + id connect label and input => click on label results in focus on input
dedicated placeholder to separate label/placeholder
render_input() is used in reset.rb, create_game.rb, forgot.rb and user.rb. I haven’t added placeholders there.
Without iOS device hard to test, but missing ids might have been the reason color inputs displayed standard color (black) on iOS. So this commit might fix this issue. Reports in regards to my [test-page](https://yzemaze.de/temp/18xx_profile_test.html) were positive.
=> forms: placeholder, label_props, for/id

assets/app/lib/tile_selector.rb, assets/app/view/game/actionable.rb, assets/app/view/game/company.rb, assets/app/view/game/hex.rb, assets/app/view/game/map.rb, assets/app/view/game/tile_confirmation.rb, assets/app/view/game/tile_selector.rb
fixes #28 
fixes #517 
fixes #679
also fixes the ☑' and ⌫ not lining up
and make the radial selector align a bit nicer (and get rid of the magic numbers)
=> Fix issue of tile selector stuck onscreen, improve tile selector code

assets/app/view/game/part/towns.rb
blue and green were mixed up (=> blue towns on green routes and vice versa). Likely better to have only one constant anyway.
=> fix route colors on towns

assets/app/app.rb, assets/app/lib/color.rb, assets/app/view/chat.rb, assets/app/view/create_game.rb, assets/app/view/game/corporation.rb, assets/app/view/game/player.rb, assets/app/view/game/stock_market.rb, assets/app/view/game_page.rb, assets/app/view/log.rb, assets/app/view/user.rb, assets/app/view/welcome.rb, models/user.rb, public/assets/main.css
colors are in effect for
- chat/gamelogs
- game navigation
- company holdings
- player card titles
- stock market
=> main part of #666 is done
additional changes:
+ button bg slightly darker when ```prefers-color-scheme: dark``` is set
+ welcome message bg color
+ create_game: json textarea and max players smaller
in app.rb color_for intentionally not used (wouldn’t work with pcs:dark)
=> settings: alternative colors

assets/app/view/game/part/city.rb, lib/engine/tile.rb
This changes tiles with multiple cities but no paths from rendering all cities in the middle
to
=> Fix OO tiles without paths on 1836jr/1882

lib/engine/part/city.rb, spec/lib/engine/part/city_spec.rb
This covers the last two parts of CN for 1882
* It is allowed for a company to place a neutral station marker in a city where that company already has a station.
* There may only be one neutral station marker in a hex
=> 1882 Allow neutral and corp lays on same tile

assets/app/view/create_game.rb, assets/app/view/form.rb, public/assets/main.css
fixes #698 
+ min/max player numbers taken from config file / cert_limit
+ inputs for names get created/removed on change of player number
+ +/- player buttons removed
+ player number changes to max allowed if illegal (< min || > max) on title switch
+ player number doesn’t change when changing modes
Caveat: [Safari doesn’t respect min/max of input=number](https://caniuse.com/#feat=input-number) (yet?).
=> enforce player numbers on game creation

assets/app/view/game/part/base.rb, assets/app/view/game/part/cities.rb, assets/app/view/game/part/city.rb, assets/app/view/game/part/label.rb, assets/app/view/game/part/revenue.rb, assets/app/view/game/part/town_rect.rb, assets/app/view/game/tile.rb
Fixes rendering of tile #62 to
This also improves the rendering of multi-city multi-slot tiles generally
Town revenues are now not rotated by 30 degrees
=> Fix render of tile #62, fix town revenue on pointy

assets/app/view/game/part/blocker.rb, assets/app/view/game/tile.rb
Also fix rotation of blockers for pointy orientation (ie 1846)
[Fixes #493]
[Fixes #575]
orientation before:
orientation after:
18Chesapeake after C-P was bought in:
1889 before buying in both TR and ER:
1889 after buying in both (ER has tile lay ability, TR does not)
=> If blocker company also has tile laying ability, when it is bought in, remove barbell but keep sym

assets/app/view/game/part/town_dot.rb, assets/app/view/game/tile.rb, assets/app/view/tiles_page.rb, lib/engine/config/game/g_18_carolinas.rb, lib/engine/round/base.rb, lib/engine/tile.rb, spec/lib/engine/tile_spec.rb
- replace all occurrences of (0..5) with a constant
- fix config for 18Carolinas' G19 -- assign corp homes to specific cities, add
missing revenue
town before:
town after:
Wilmington before:
Wilmington after (still needs name position tweaking, will fix later):
=> Fix dot-town revenues and double-city tiles where only one has paths

lib/engine/ability/token.rb, lib/engine/config/game/g_1846.rb, lib/engine/round/g_1846/operating.rb
- Sets the price of the token ability in the config.
- Adds token ability for IC
- Uses teleport_price on the ability to determine if corp needs a route first to use power. This is needed for IC.
- Overrides skip_token? since the base class one relies on graph.skip_token? that doesn't hook into 1846 special logic for connected_hexes and connected_nodes.
#748 #755
=> Fix 1846 token powers

lib/engine/token.rb
It was checking corporation tokens which could be empty.
#789
=> Check tokenable? on bonus token when buying 1846 minor.

assets/app/app.rb, assets/app/view/game/buy_companies.rb, assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, assets/app/view/game/game_log.rb, assets/app/view/game/map.rb, assets/app/view/game/player.rb, assets/app/view/game/round/operating.rb, assets/app/view/game_card.rb, assets/app/view/game_page.rb, assets/app/view/log.rb, assets/app/view/logo.rb, assets/app/view/navigation.rb, public/assets/main.css
rem => vmin for most margins/paddings between/of boxes/divs
companies: (at least) 3 inline below most maps
company cards share props with corps, players and game cards
cards stretch on mobile (<= 420px) to fill the width (95vw leaves some padding)
player card header fixed (bg stretches to fill width)
bottom border to game menu to diff from log content
looks good on Safari/iOS 13 on browserstack, too – but again: please check locally on hardware
=> margins/paddings revised (header/home/content/game/companies)

assets/app/view/game/exchange.rb, assets/app/view/game/round/stock.rb, lib/engine/ability/exchange.rb, lib/engine/config/game/g_1836_jr30.rb, lib/engine/config/game/g_1889.rb, lib/engine/round/special.rb, lib/engine/share_pool.rb
Fixes:
1836Jr Allow GCB to trade for pool share issue
Fixes a problem where an error would occur if you used the special at the start of a stock round.
=> Allow exchange abilities to come from market

lib/engine/config/game/g_1836_jr30.rb, lib/engine/game/g_1836_jr30.rb
A train that includes one of these three locations at one end of its run increases the total of its run by F20 per station
token (not City) on the route in the green phase, and F30 per station token (not City) in the brown phase. As with
Off-Map Locations, only one Paris/Port Location may be scored (either at the beginning or the end of the run). Such
a run must include at least two other scoring locations (e.g., a run from Lille to Paris is not legal) and thus requires at
least a 3 train. A train may include both an Off-Map Location and a Paris/Port Location in its run, one at each end.
=> 1836jr: Implement ports

assets/app/view/game/part/city_slot.rb, assets/app/view/map_page.rb, lib/engine/abilities.rb, lib/engine/ability/base.rb, lib/engine/ability/reservation.rb, lib/engine/company.rb, lib/engine/config/game/g_1846.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/hex.rb, lib/engine/part/city.rb, lib/engine/phase.rb, lib/engine/tile.rb, spec/lib/engine/hex_spec.rb, spec/lib/engine/part/city_spec.rb
1846
- Give relevant corporations and C&WI the reservation ability.
- Add Erie's token ability.
- Close private companies that are removed from the game before deleti
them. This keeps O&I and MC from blocking tiles if they're not in play.
Abilities
- Add teardown method to token abilities; called when the ability is being
removed.
- Add `remove` key to abilities to indicate the phase in which that ability
is removed; check for these at every phase change.
- When a company is closed, remove all of its abilities.
Reservations
- Reservations are the actual corp/company now rather than their short name.
- Reservation ability has tile and city properties that can be updated in order
to handle tile upgrades.
- If a slot is reserved by a company, it also counts as being reserved by the
owning …
=> Add reservation ability for token reservations.

assets/app/view/game/corporation.rb
As mentioned on slack the float percentage overflows into the tokens, this removes the trains and cash until the corp has floated
=> Fix the float percentage overflowing into the tokens

assets/app/view/game/corporation.rb
When token is placed all tokens will show the
hex name instead of showing token cost for
non-home tokens.
This is the request as given in issue #688 
Pros:
- Easy to see where a token is placed
Cons:
- What did I pay for it? This you have to check the log for.
Might also cause problems in 18xx where a token can be returned, but I believe this problem is similar if showing cost.
This is my first contribution to this open source project so I am interested to know if I have missed anything?
Also, was not able to locate any unit test for this.
=> Show position for layed token (#688)

assets/app/view/game/issue_shares.rb, assets/app/view/game/route_selector.rb, public/assets/main.css
- prevent map wrapping due to changes of routes, error msg etc.
- #left = fixed width => breakpoint on Chesapeake and 1889 ~1360px, 1846 ~1480px
- error message outsourced to separate tr
- prevent width changes of train "buttons"
- paddings, margins. nowrap etc.
Temporary fix for #921. It’s (still) not ideal for widths between 420 and ~1360px (with most maps).
Screenshots:
prod
PR
=> route selection styling: prevent map wrapping

lib/engine/ability/tile_discount.rb, lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_1889.rb, lib/engine/tile.rb
fixes #894 
Refactors `ignore_terrain` into a generic `tile_discount` ability
I'm not 100% sure if this properly implements a discount for "mountain edges" in 1846 tiles, since I don't have a good grasp of [the code that determines that](https://github.com/tobymao/18xx/blob/master/lib/engine/round/base.rb#L274)
=> [1846] implement tunnel blasting

assets/app/view/game/companies.rb, assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, assets/app/view/game/player.rb, assets/app/view/game/round/operating.rb, lib/engine/config/game/g_1889.rb, public/assets/main.css
- companies included on corp/player cards
- player owned companies with abilities during OR (e. g. Mitsubishi Ferry) are still rendered below active corp (alternative: render player card)
- toggle description by click/tap on company name
- click/tap to toggle selection (selected = light blue bg)
- prevent selection of not usable or not purchasable companies (should prevent using other corp’s companies from companies tab etc.)
- cursor: pointer only when selectable
- active corp/player highlighted with border and name underline instead of bg color
- (needs: display in part for later)
- still two selects needed when ability allows laying two tiles
I’m not convinced `@table` is the best method to choose which render method to use for corp/player. (… and results in annoying white-space …
=> Companies on cards

lib/engine/game/g_1846.rb, spec/lib/engine/games/game_spec.rb
tested with the game data shared in #918 at action 342
test game 2987 has final values change a little, but does not break, implying
that the illegal bonus revenue in that game did not lead to an extra share or
train purchase
[Fixes #918]
Screenshot showing new log output:
=> implement event for removal of MPC/SBC tokens in 1846

assets/app/view/game/stock_market.rb, lib/engine/config/game/g_1846.rb, lib/engine/share_price.rb
* consistent wording in stock market legend: "Company" -> "Corporation"
[Fixes #945]
=> change the $0 space in 1846 to black, update legend

assets/app/view/game/buy_trains.rb
Vary text depending if there is available trains in the
discard and/or allowed to buy from other corporations.
=> Improve must-buy-train wording (#650)

lib/engine/ability/tile_income.rb, lib/engine/config/game/g_1882.rb, lib/engine/game/base.rb, lib/engine/game/g_1882.rb, lib/engine/round/base.rb, lib/engine/round/g_1882/operating.rb, lib/engine/tile.rb
Covers the following of the 1882 list
* P4 pays revenue each time a bridge (river hexsides preprinted on the map) is crossed, $10 to its owner.
* If you lay in a NWR hex, you get $20 for each lay (must pay any extra costs before getting the $20). (possibly this can be a negative payment, the opposite of tile action payment in 1846)
* (alpha) A route gets a bonus $100 for running [A9 or B2] to L2. (probably can already implement this as using the new group function on tiles)
=> Add NWR tile laying incentive and Tresle company, add revenue calculation for Hudson Bay

lib/engine/config/game/g_18_chesapeake.rb, lib/engine/game/base.rb
I don't want to trod on @scottredracecar , but wanted to propose some changes to the description of 18Ches privates
Specifically I wanted to surface the name of the company attached to the Vanderbilt (it felt a bit buried in the bottom of the description)
As well as trim out references to "game setup" that didn't seem relevant for this online implementation
=> [18Ches] Proposed private description changes 

assets/app/lib/color.rb, assets/app/view/game/corporation.rb, assets/app/view/game/spreadsheet.rb
fixes #942
I don’t see a need for opacity on the bg colors. They aren’t as harsh as [expected](https://github.com/tobymao/18xx/issues/942#issuecomment-653387231) on black bg and hex-colors are easier to deal with anyway.
=> Contrasting colors

assets/app/view/game_card.rb
redundant info and obsolete chars removed, name length limited
even without word-break most game cards shouldn’t need more vertical space than before
=> minor stylistic changes on game cards, especially finished games

lib/engine/game/g_1846.rb
* fix removal of reservations
* prevent buying trains from closed corporations
* remove share price token
* close companies owned by the corporation, and log it; duplicate the array
since `company.close!` removes it from its owner's `companies`, i.e., `dup` is
needed to avoid modifying the array that is being iterated over
[Fixes #958]
This game is on PRR's turn at the train buying step, after ERIE closed at action 65 - [958_example.json.txt](https://github.com/tobymao/18xx/files/4874174/958_example.json.txt)
=> 1846 - corporation closure fixes

assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, assets/app/view/game/hex.rb, assets/app/view/game/round/operating.rb, lib/engine/assignable.rb, lib/engine/round/base.rb, lib/engine/round/operating.rb, lib/engine/round/special.rb
How to use: Click Steamboat Company then click the corporation. 
- Removes previous assignment when clicked again
- Removes previous assignment when purchased
Fixes #851
=> Assign steamboats before the private company is bought in

api.rb, assets/app/index.rb, assets/app/view/game/part/borders.rb, assets/app/view/game/part/location_name.rb, assets/app/view/game/part/multi_revenue.rb, assets/app/view/game/part/single_revenue.rb, assets/app/view/game/part/upgrade.rb, assets/app/view/game_page.rb, assets/app/view/logo.rb, public/assets/main.css
Except for the logo margins (around .) and bold on game menu hover Lato worked out of the box for text, too.
Logo: Keep old one / use Lato, too?
=> change font to Lato; improve legibility of numbers on map

assets/app/view/logo.rb, public/assets/main.css
1.15 (18.4px) => 1.25 (20px). It should make reading paragraphs and logs easier. I don’t think that increased letter- and word-spacing are really necessary (ymmv).
=> increase line height

assets/app/view/about.rb, assets/app/view/form.rb, public/assets/main.css
Right now all forms are on dedicated pages => form legend == content header. At least as long as that’s the case legend should contain h2, because of page semantics and consistent styling.
=> Consistent header styling / form headers

lib/engine/config/game/g_1817.rb
Adds a rough draft of privates for 1817.  No abilities yet, and the descriptions need cleaned up.
Fixes for trains so that the game will start properly.  The "on" condition of phase "2+" is wrong: it should trigger on the export of a 2T, which also zeroes the inventory of 2T's  but doesn't rust/obsolete them.
Fixed spelling of "Pittsburgh" in Corp names.
Added contrasting text_color to corps as needed.
=> 1817 privates

public/assets/main.css
usual recommendation would be 75 – 90 % of line-height, but this looks good to me. ymmv
=> front page texts take less vertical space
=> p margins reduced

lib/engine/config/game/g_1836_jr30.rb
Changed from yellow to green revenue as a 3T needed to use revenue
boxes.
=> Adjust Paris and Channel Ports revenue boxes (#980)

assets/app/view/game/part/upgrade.rb, lib/engine/round/base.rb, lib/engine/round/g_1846/operating.rb, lib/engine/tile.rb
[Fixes #1001]
[Closes #877]
Example mentioned in #877:
From the game data provided in #1001:
color mountains in middle of hex to match color of mountains on borders:
=> Apply company discount to border terrain, log terrain discounts

lib/engine/config/game/g_18_al.rb, lib/engine/config/tile.rb, lib/engine/game/g_18_al.rb, lib/engine/round/g_18_al/operating.rb, lib/engine/tile.rb, public/icons/18_al/coal.svg, public/icons/18_al/tree.svg
- Split 444a into two tiles with different labels (444b for Birmingham
with label B, and 444m for Montgomery with label M)
- Block tile laying of tile 445 as can only be placed via company BLC
- Put icon of tile 445
- to be able to use attribute for tile block
- to separate it form normal gentle tile with town
- Add sticky coal icon for Warrior Coal token locations (5 hexes)
- When tile is placed in Montgomery ensure label is set to M to
allow for a yellow tile to be put there and further tiles to be
put there needing the label M.
=> Correct tiles in 18AL (#961)

assets/app/view/welcome.rb
Now that there is a permanent invite link we can add this to the main page
=> Add slack invite link to homepage

lib/engine/config/game/g_18_al.rb
- Add "on" attribute to denote on which train phase change occur (Table I)
- Add gray tiles available on 4D train buy (Table I)
- 4T are now obsoleted on 7T buy, not rusted (Rule 4.5.2.1)
=> 18AL: Minor fixes related to phases

lib/engine/game/company_price_50_to_150_percent.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_ga.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/g_18_ms.rb, lib/engine/game/g_18_tn.rb
Update so that allowed purchase interval for companies is between
50% and 150% (inclusive) of face value.
This has been changed in the following games:
- 18AL
- 18GA
- 18MEX
- 18MS
- 18TN
=> Set allowed purchase interval for companies in Mark Derrick games (#961)

lib/engine/round/stock.rb
- add new `sold_out?` method so that other games can easily override it (e.g.,
1817 where more than 100% is also sold out, 18Chesapeake 2p where shares can
be removed from the game but a corporation can still be sold out)
- use `move_down` instead of `move_left` for decreasing the price; 2D market
games that drop prices for share in the market move down (e.g., 1849), and
`move_down` will be correctly translated to `move_left` for 1D games like 1846
- count the number of shares instead of adding up their values and dividing by
10--same result for 10-share corporations but with less computation, and for
smaller corporations (e.g., 2-share and 5-share in 1817), the adjustment is
based on number of shares in the pool rather than percentage
- adjust prices in descending corporation order for …
=> fix stock price adjustments at end of stock round

assets/app/view/game/part/city_slot.rb, assets/app/view/tiles.rb, assets/app/view/tiles_page.rb, lib/engine/hex.rb
* on /tiles/ pages, use real hex coordinates instead of A1 where applicable;
without this, all reservations are grey except when the corporation's home
happens to be A1
[Fixes #1071]
=> render non-home reservations as grey instead of black

assets/app/view/game/corporation.rb
Fixes the NOOP that is happening when trying to assign Steamboats to B&O.
=> Fix process_action not found when trying to assign_corporation

assets/app/view/game/game_info.rb, assets/app/view/game/spreadsheet.rb
fixes #1099 (… at least on Mojave/10.14 on browserstack – and prevents up/down arrow emoji there, too.)
Glyphs from the 2B block aren’t widely supported. Standard arrows work with many more fonts. [cf. http://www.alanwood.net/unicode/miscellaneous_symbols_and_arrows.html vs. http://www.alanwood.net/unicode/arrows.html]
=> change arrows to wider supported glyphs

lib/engine/game/company_price_50_to_150_percent.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_ga.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/g_18_ms.rb, lib/engine/game/g_18_tn.rb
18MEX/18AL is broke right now on master; they stop after SR1. 
Also the "50-150%" change did not work with further additions to setup of the games.
This change is prioritized among the PRs for 18AL.
=> Fix Mark Derrick games

lib/engine/game/g_18_al.rb, lib/engine/game/g_18_ga.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/g_18_tn.rb, lib/engine/step/g_1836jr30/train.rb, lib/engine/step/single_depot_train_buy_before_phase4.rb
This applies to the following 18xx:
- 18AL
- 18GA
- 18MEX
- 18TN
When buying train from depot in phase 2 and phase 3
only one train can be bought.
=> 18AL/18GA/18MEX/18TN: Limit depot train buy to one before phase 4 (#961)

lib/engine/config/game/g_18_al.rb, lib/engine/game/g_18_al.rb
4D now double off-board and cities.
6T and 7T now change phases.
All trains count towns for revenue, but
does not count them for distance.
=> 18AL: Fix revenue calculation for trains

assets/app/view/game/part/track.rb
=>
Only TrackCurvilinearPath, because the few other occassions don’t really matter (and would hurt performance more than they’d do good). [as of now & afaik]
=> render routes after (on top of) black track

assets/app/view/create_game.rb
On mobile backspace didn’t function as expected. (Workaround by selecting number and then changing is a pita.)
Allowing the fields to be temporary empty prevents this, but necessitates "validation" on mode switch.
Empty max_players gets catched for multiplayer games (according to my tests) and doesn’t matter for hotseat, because player inputs don’t get wiped. `required` had no effect apart from highlighting the field if empty on Firefox.
=> ease number input on mobile

assets/app/view/game/corporation.rb, lib/engine/ability/base.rb, lib/engine/config/game/g_18_al.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/revenue_4d.rb, lib/engine/game/terminus_check.rb, lib/engine/step/g_18_al/token.rb, lib/engine/step/g_18_al/track.rb
Introduce an ability Destination that can be used to specify
a destination hex. This ability can be used in e.g. 1822,
1844, 1856, 18AL.
Configure historical objective hex for all corporations in 18AL
using the destination ability. When a corporation places its
token in its destination hex, it receives $100 to treasury as
it has reached its historical objective.
=> 18AL: Add support for historical objective (#961)

lib/engine/ability/tile_lay.rb, lib/engine/config/game/g_18_al.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/round/special.rb, lib/engine/step/tracker.rb, lib/engine/tile.rb
Add the posibility to configure skip of feature check when
laying tile.
Add ability for Brown & Sons Lumber Co to lay tile 445
as a one of ability, for free.
Tile 445 does now ignore town count in the hex it is placed.
This tile will only be placed via the Brown & Sons Lumber
Co special ability.
A similar ability exists in 18MEX, but that will be implemented
later.
=> 18AL: Implement company Brown & Sons Lumber Co

lib/engine/game/base.rb, lib/engine/game/g_1882.rb, lib/engine/step/g_1882/waterfall_auction.rb, lib/engine/step/waterfall_auction.rb
Fixes #1092
Also implements 1882
The first available company reduces by $5, not just the first.
=> Add 1882 Initial auction rules, fix 18Chesapeake train export during initial auction

assets/app/view/game/corporation.rb
fixes #1133 
The gist is in the 2nd commit. `scrollLeft = width` not implemented, because it’s just not that necessary now and even counter-productive early in games. (Maybe later when we actually have games with 6+ tokens.)
=> Corps token scroll

assets/app/view/game/round/operating.rb, assets/app/view/game/round/stock.rb
_Afaik_ this is only relevant for Grand Central Belge (1836jr) and Dougo Railway (1889). Both tested and working fine.
https://18xxgames.slack.com/archives/CV3R3HPUZ/p1595464749116900 +
As long as there’s no way to act between corporations in ORs use of these abilities is limited to owner being the active player.
=> exchange of companies (GCB, Dougo) during OR

assets/app/view/game/buy_companies.rb, assets/app/view/game/company.rb
pls. test on iOS (3 buyable companies should be rendered per row below 1889 map)
=> eliminate wiggle

assets/app/view/game/par.rb, assets/app/view/game/round/stock.rb
before
after
< 5 buttons
5+ buttons
reduced padding and 0.5rem horizontal margin between buttons works for me on mobile, but might be a problem for fat fingers. Revert to previous values is no problem, just adds a row in most cases.
=> par price buttons: cleaner look

assets/app/lib/settings.rb, assets/app/view/game/part/town_dot.rb, assets/app/view/game/part/town_rect.rb, assets/app/view/game/part/towns.rb, assets/app/view/game/part/track.rb, assets/app/view/game/part/track_curvilinear_half_path.rb, assets/app/view/game/part/track_curvilinear_path.rb, assets/app/view/game/part/track_lawson_path.rb, assets/app/view/game/part/track_offboard.rb, assets/app/view/game/route_selector.rb, assets/app/view/user.rb, models/user.rb, public/assets/main.css
I’m no fan of dasharray, but if we’re serious about making the site friendlier to people with visual impairments color and width very likely won’t suffice.
width.to_i because user-settings from inputs are saved as string afaik. I don’t know where/how exactly I could change this for specific inputs.
`4.times` in models/user.rb is ugly – couldn’t figure out how to access Lib::Settings::ROUTE_COLORS there.
no hash with route settings because of problems with settings-array in models/user.rb and accessing values with color_for/settings_for. I wouldn’t mind rewriting these parts, but would likely need a lot of help.
=> settings: route colors, width & dash

assets/app/view/game/corporation.rb, assets/app/view/welcome.rb, lib/engine/game/g_1836_jr30.rb, lib/engine/game/g_1882.rb, lib/engine/graph.rb
Two minor bugs
* The operating order change caused it to crash as soon as you used NWR
* Make sure to clear the state of the graph after the NWR destroys tiles.
Update the status.
=> Minor bugs, 1882 -> alpha, 1836jr30 -> production

lib/engine/config/game/g_1882.rb, lib/engine/game/base.rb, lib/engine/game/g_1882.rb, lib/engine/phase.rb, lib/engine/step/g_1882/special_nwr.rb, lib/engine/step/g_1882/track.rb, lib/engine/step/tokener.rb, lib/engine/step/tracker.rb, spec/fixtures/1882/4932.json, spec/lib/engine/games/game_spec.rb
Critical 1882 bugs:
fixes #1198 Wrong price for tokens
fixes #1192 Neutral token gets replaced with another home token from the NWR owning corp
fixes #1189 Corp using NWR power should be able to pay for terrain costs
fixes #1188 Skipping token lays when can't afford it
short term workaround for #1199
=> 1882 critical bugs

lib/engine/game/g_18_al.rb, lib/engine/game/g_18_mex.rb, lib/engine/step/special_track.rb, lib/engine/tile.rb
For special tile tile, restrict available tiles to
the ones that are allowed to lay during current phase.
Add special lay to 18AL and 18MEX so that they can lay
Copper Canyon and Lumber Terminal again.
Put check for honoring existing track before short cut
for special lay, so existing track is also honored by
special lay.
(This was a potential bug with the special lay short cut.
It should have no change of existing functionality for
non special lays as this was an existing check that
has just been moved. The remaining checks are still
skipped by special lay.)
=> Ensure special tile lay follows phase colors (#1130)

lib/engine/step/dividend.rb
I bet this is going to break some games where players ran a train again after it should have rusted.
=> Rust obsolete trains even if they don't run [Fixes #1147]

assets/app/view/game/part/city.rb
fixes #1181 
Moves the city further back making the track obvious
=> 1882: Make track clearer when there's a border

assets/app/view/game/buy_trains.rb, lib/engine/depot.rb, lib/engine/step/g_1846/train.rb, lib/engine/step/train.rb
[Fixes #1235]
This will break any games like 5112; IC could afford a 6 but bought 7/8 with a little help from the president - https://www.18xx.games/game/5112?action=520
=> 1846 - disallow expensive train variant if corp can only afford cheaper

lib/engine/action/buy_train.rb, lib/engine/step/train.rb
[Fixes #1233]
`variant` in `args_to_h` was checking `train`'s *current* `name` and `variants,` instead
of using whatever `variant` was passed in when the action was created
Also it seems better to modify the train object in `process_buy_train`, rather
than when creating the action
=> Fix initialization of BuyTrain actions to prevent history from being changed

assets/app/view/game/route_selector.rb, lib/engine/ability/hex_bonus.rb, lib/engine/config/game/g_18_al.rb, lib/engine/game/base.rb, lib/engine/game/g_18_al.rb, lib/engine/step/g_18_al/assign.rb, lib/engine/step/g_18_al/buy_company.rb, lib/engine/step/g_18_al/buy_sell_par_shares.rb, lib/engine/step/minor_half_pay.rb
Added route_bonus ability that can be used to give revenue
bonus if a route include the specified hexes.
Although generic, the use of ability implemented in 18AL only.
Configure ability for company Memphis & Charleston RR.
=> 18AL: Implement M&C RR and S&NA companies

assets/app/view/game/buy_trains.rb, lib/engine/ability/train_discount.rb, lib/engine/config/game/g_18_al.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/game/base.rb, lib/engine/game/g_1836_jr30.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1882.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_chesapeake.rb, lib/engine/game/g_18_eu.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/buy_train.rb, lib/engine/step/dividend.rb, lib/engine/step/g_1836jr30/buy_train.rb, lib/engine/step/g_1846/buy_train.rb, lib/engine/step/single_depot_train_buy_before_phase4.rb, lib/engine/step/special_buy_train.rb, lib/engine/step/train.rb, migrate_game.rb
Configurable attribute 'train_discount' added. When this is set
for a corporation, the trains that has been configured in the
attribute, will appear as extra lines in the BuyTrains view,
shown with the discounted price.
When train bought for a discounted price the company should close.
This attribute has been configured for:
- 18AL: New Decatur Yards (50% discount for 3, 4, 5 trains)
- 18MS: Mobile & Ohio Railway (100$ discount for 3+, 4+ trains)
This commit is for peer review. The close of companies when
used does not seem to work as it should.
=> 18AL/18MS: Implement company that gives discount for some trains

assets/app/view/welcome.rb, lib/engine/game/g_18_al.rb, lib/engine/step/g_18_al/assign.rb, lib/engine/step/special_buy_train.rb, spec/assets_spec.rb, spec/fixtures/18_al/4711.json, spec/fixtures/18_al/4712.json, spec/lib/engine/games/game_spec.rb
Contains 18AL related stuff:
- Put in alpha
- Fix bug and add log text for closing company in special_buy_train
- Improve log text when assigning Warrior Coal Field token
- Add fixtures  (2 bank broke games, one with full set and one that ends in OR 8.1)
fixes #961 961
=> Make 18AL alpha

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/game_related_issue.md, .github/ISSUE_TEMPLATE/general_issue.md
"about" could need some differentiation.
Maybe labels "game" and "general" ("issue"?), with "game" to be changed into "18..." by mod and "bug" applied once confirmed. (Afaik there’s no way for issue creators to add a label.)
Wording might be off in some places, please check.
PS: There’s always an option to open an issue without using a template.
=> Issue templates

lib/engine/step/waterfall_auction.rb
Seems the pieces for this fix were already in place. Maybe something got clobbered at some point?
Got a long-line error from the linter, so I changed the if modifier form to a block if statement. Let me know if I've done something un-idiomatic.
=> waterfall_auction: prevent bids above available funds

assets/app/view/game/game_info.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1836_jr30.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1882.rb, lib/engine/game/g_1889.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_chesapeake.rb
If the GAME_INFO_URL is set, do show that as a link under
Game Info part of the Info page. Do not show any other Game
Info parts.
=> Show wiki page as game info link if such exists (#1251)

assets/app/view/log.rb, public/assets/main.css
Similar to #1265 this is to very simply, for now, make it harder to miss the important automated log messages and make the overall log a bit easier to parse when looking through history. Admittedly a brittle solution, but simple enough for now and will work across games in history.
=> Added styling to important log messages

assets/app/view/game/corporation.rb, assets/app/view/game/par.rb, assets/app/view/game/round/stock.rb, lib/engine/game/base.rb
The participants in the issue discussion concluded that it would be good to show the available par prices on the corporation card so they are visible without having to click on them. I did implement that, but to be honest I am somewhat ambivalent towards this choice. On the one hand, it is good to be able to see the par options at a glance. On the other hand, it's kind of the same information repeated in several places (unless there is some example of an 18xx game where available pars vary between corporations).
Fixes #671
=> Hide unaffordable par prices. 

assets/app/view/game/round/stock.rb
fixes #430
Since we now have the abilities menu, this is no longer needed
=> Remove the button, players can exchange via the abilities menu out of turn

lib/engine/ability/tile_lay.rb, lib/engine/config/game/g_1846.rb, lib/engine/step/special_track.rb
By default, special tile lay abilities skip the check for matching labels and matching number of cities/towns. One consequence of this is that the LSL private ability in 1846 allows upgrading Cleveland to a non-Z city or Toledo to a Z-city. This PR introduces a parameter to the ability configuration which will restore the full set of checks. Setting this parameter for LSL prevents the illegal upgrade.
Fixes #1285
=> allow complete set of upgradeable checks for special tile lay abilities

lib/engine/config/game/g_1846.rb, lib/engine/step/assign.rb, spec/lib/engine/round/operating_spec.rb
While this allows the company to be reassigned more than the rules permit (I have opened #1359 to address this), it is better than the current situation which prevents the company from being reassigned once by the owning corporation.
[Fixes #1313]
The added unit test fails if either the 1846 config or added logic in `Step::Assign` is reverted.
Screenshots from a continuation of [the game data shared](https://gist.github.com/wcraigtrader/cb9b22291a2ee33fa61fabcb433aab75) on #1313:
=> 1846 steamboat - allow "unlimited" hex assigning, unassign old hex

TILES.md, assets/app/view/game/part/revenue.rb, assets/app/view/game/part/track_lawson_path.rb, lib/engine/config/game/g_18_al.rb, lib/engine/part/path.rb, lib/engine/tile.rb
Fixes #1290 
Adjusted multi_revenue placement when in tow or bottom row.
Added support for "terminal:1" parameter to path in tile definition. Will create tapered track to city.
=> Adjust multi_revenue placement; Add support for terminal paths for off-board cities fixes #1290

lib/engine/round/operating.rb
[Fixes #1352]
Also fix order of log messages for corp in receivership to say
> Sharepool operates NYC
> NYC skips issue or redeem shares
> NYC skips place a token or lay track
instead of
> NYC skips issue or redeem shares
> NYC skips place a token or lay track
> Sharepool operates NYC
=> Operating round - don't move to next entity on messages

assets/app/view/game/entity_order.rb
ul not just because of semantics, it will come in handy when a vertical (space-saving) order is needed.
btw: I didn’t miss the borders on dark bg until now. Do we need them?
=> entity order: divs => ul/li, pruning

lib/engine/corporation.rb, lib/engine/share_bundle.rb, lib/engine/share_holder.rb, lib/engine/share_pool.rb
The new code outside of Engine::Corporation#initialize should work for any size
of share corporations (e.g., 5 share corporations in 1817, 4 share corporations
in 18CZ), regardless of how many shares a president certificate is.
[Fixes #1376]
=> fix dumping presidency when presidency is 30% instead of 20%

assets/app/view/game/abilities.rb
- fixes #1201 – if "show/hide others" + title are sufficient
- limit width of company desc to ~ map width
- prevent button & margin wiggling
=> abilities styling

assets/app/view/game/game_info.rb, lib/engine/config/game/g_1836_jr30.rb, lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_1882.rb, lib/engine/config/game/g_1889.rb, lib/engine/config/game/g_18_al.rb, lib/engine/config/game/g_18_carolinas.rb, lib/engine/config/game/g_18_chesapeake.rb, lib/engine/config/game/g_18_ga.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/config/game/g_18_tn.rb, lib/engine/game/base.rb, lib/engine/game/g_18_al.rb, lib/engine/game/g_18_ga.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/g_18_tn.rb, lib/engine/phase.rb, lib/engine/step/buy_company.rb, lib/engine/step/g_18_al/assign.rb, lib/engine/step/single_depot_train_buy_before_phase4.rb
Applied bold text to Game over message, and one Note! in 18AL.
Made it possible to show phase status, like e.g. Limited Train Buy in 18AL. See picture.
=> Add two bold texts, and improve phase status

TILES.md, assets/app/view/game/part/revenue.rb
1. Swap transformation on revenue for pointy maps to allow revenue to be properly horizontally centered on tiles
2. Add correct multi_revenue preferred_render_location for pointy maps
3. Update TILES.md for border options and minor formatting issue with last edit
With old revenue position (on 18TN):
With this change:
=> Fix revenue position on pointy maps

lib/engine/config/game/g_1817.rb
* Add location name to New York
* Change Chicago and Atlanta revenue to 30/50/60/80
* Add impassable border northeast of Cleveland
* Fix track on yellow New York tile
=> Correct 1817 map

assets/app/view/game/buy_company_from_other_player.rb, assets/app/view/game/round/stock.rb, lib/engine/config/game/g_18_al.rb, lib/engine/game/base.rb, lib/engine/game/g_18_al.rb, lib/engine/step/buy_sell_par_shares.rb, spec/fixtures/18_al/4714.json
This feature makes it possible for a player to buy a private company from another player during the stock round.
This should maybe be a draft instead?
There are two things remaining:
- The layout did not look good if a player buys the first company of two. So need help to get that correct.
- Need to fit this buy together with other so a player cannot buy more than one thing during an SR
=> 18AL: Add support for buying companies between players

lib/engine/config/game/g_18_tn.rb, lib/engine/game/g_18_tn.rb
Privates do not block their home hex.
Also did a minor refactoring to improve maintanability of upgrades_to?
=> 18TN: Privates should not block assigned hexes. (#1419)

assets/app/view/game/corporation.rb
Another part of #1416 
No zebra-style because it’s a minute detail not worth the time and code it would take because of user-defined colors, several possible combinations of abilities & company table plus maybe others in the long run.
Color on user-defined bg like in the screenshot is also not the best idea. Given we use bold in the holdings section and other places I’ll keep it here, too:
=> order/last run bg = holdings_bg

assets/app/lib/color.rb, assets/app/view/game/spreadsheet.rb, public/assets/main.css
(resolves a part of  #1416)
@justinkwaugh ’s proposal:
To me that many borders just reduce my parse speed hence I added only a few. Withhold and half-pay conflict a bit with gray bg, but I’d just wait and see what people think.
FF dark
Chrome light
=> zebra-style

lib/engine/game/base.rb, lib/engine/step/train.rb, spec/fixtures/18_al/1446.json, spec/lib/engine/games/game_spec.rb
If the last train is bought the game does not try to use
the cheapest train in the depot.
And if no trains are in the depot then a corporation is not
forced to buy trains.
Included a test case for an 18AL game where all 9 permanent
trains are bought, and the trains distributed among the 6
corporations so that one corporation is left without. Game
runs to completion with L&N trainless.
=> Handle empty depot smothly (fixes #1446)

lib/engine/config/game/g_18_ga.rb, lib/engine/game/g_18_ga.rb
Updated companies - but special ones are not yet implemented.
Make trains ignore towns for distance, ie the normal way in Mark Derrick's games.
Add More Info link. Have created a first wiki page.
=> 18GA: Minor corrections

lib/engine/ability/README.md, lib/engine/ability/token.rb, lib/engine/config/game/g_1846.rb, lib/engine/step/special_token.rb, lib/engine/step/tokener.rb, lib/engine/step/tracker.rb
Also includes a little fix-up for the token log messages for cases where the hex has no location name.
Fixes #1228
Fixes #1461
=> Enforce hex and city restrictions for token abilities

lib/engine/game/g_18_al.rb
Removed green upgrades for Lumber Terminal tile.
Show green M tile for possible upgrades to yellow cities
in tile manifest.
=> 18AL: Correct tile view in time manifest (fixes #1426)

lib/engine/game/g_18_ga.rb
During testing I experienced a crash sometimes that indicated
that owner was not always set. This might be the cause, so
just in case I added bank as owner to the neutral tokens.
=> 18GA: Let Bank own the neutral tokens

lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb
Update tile manifest to make it correct and complete.
Handle the special upgrades in Mobile City, Montgomery and Birmingham, using the same code pattern as is used in other Mark Derrick games.
=> 18MS: Tiles

lib/engine/config/game/g_18_ms.rb
Corrected off board revenue for New Orleans.
Make a three hex off board group, with correct revenue, in Atlanta.
Make a real town hex that is connected to New Orleans. Put this
in I3 to work around that you cannot have town and city in the
same hex. Name it Port Sulphur after a real port south east of
New Orleans. (Or should it use another name? Did not see any
on the 18MS map.)
=> 18MS: Fix map to make it playable with all hexes available. (#1385)

lib/engine/ability/token.rb, lib/engine/company.rb, lib/engine/config/game/g_18_ga.rb, lib/engine/game/g_18_ga.rb
Had to change special token handling a bit to make the token placement
being performed by the company's owner, and use one of the tokens from
the owner.
(Did this by adding a from_owner atribute to the token ability.)
TODO: This works, almost... When the token is placed using the ability the corporation can still lay a token (have to Skip Token if not wanting to), but this is incorrect.
I tried to use a round state and store company.owner there, and then add a check in tokens_available? that the entity had not put out any token, but it did break an 1846 game where IC had been used to lay a token. Looking into that one it looked OK (id 150 for hs_cbxfbqwe_5779 it complained about).
So am I missing something obvious to get it to skip token automatically when having used company token …
=> 18GA: Implement Waycross & Southern RR (fixes #1496)

lib/engine/game/g_18_ms.rb
Every corporation can lay 2 yellow (or one upgrade) in its first OR.
Remaining ORs it is 1 yellow or one upgrade.
=> 18MS: Allow extra yellow tile lay first OR

lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_company.rb
Make it possible for companies to buy P1/P2 during OR1.
AGS (P1) and BS (P2) can be bought by companies during OR1, but
only at face value. Otherwise buy of companies is as usual, can
be done for 50%-150% of face value during green phase. In 18MS
brown phase are triggered when 1st 6 train is bought.
Only private companies owned by the president may be bought
=> 18MS: Update private companies handling

lib/engine/ability/token.rb, lib/engine/company.rb, lib/engine/config/game/g_18_ga.rb, lib/engine/game/g_18_ga.rb
This reverts commit 071273e19d664ebecc56e81df80e862cfdc0bc2a.
Reverted due to bug in tokening.
=> Revert "18GA: Implement Waycross & Southern RR (fixes #1496) (#1498)"

lib/engine/config/game/g_18_ms.rb
Correct track for tile X31 and 446
Bank cash increased to 10 000. There is no bank limit - 10 000
should be more than enough (rule book recommend 6 000).
=> 18MS: Bug fixes

lib/engine/game/g_18_al.rb
As it is now you will get an option to upgrade tile 445 but it should not be allowed.
If anyone have upgrades Lumber Terminal to green this will break the game. But it cannot be saved.
=> 18AL: Lumber Terminal (Tile 445) cannot be upgraded

lib/engine/config/game/g_18_ga.rb, lib/engine/game/g_18_ga.rb, lib/engine/step/g_18_ga/buy_company.rb
The free train received when buying private Ocilla Souther RR
did not have the correct index. Changed so that the free train
is created as all other 2 trains, and then bought by neutral
corporation and set to buyable false. When Ocilla Southern RR
is bought the owning corporation makes a free buy of the free
2 train. The 2 train is set to not buyable otherwise so that
the owning corporation cannot sell it later.
=> 18GA: Correct handling of free train (Fixes #1536)

lib/engine/config/game/g_18_mex.rb, lib/engine/game/g_18_mex.rb, lib/engine/step/g_18_mex/dividend.rb
Init owner for each minor after completed SR1.
Set corresponding companies as non-buyable and closing at phase 3½.
Use 50%-50% dividend for minors.
=> 18MEX: Changes to make Minors operatable

lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_company.rb, lib/engine/step/special_buy_train.rb
Implements Mississippi Central Railway. This works as a free extra 2+ train. Cannot be bought after 2+ has been rusted or if train locked.
Also fixed a bug with Mobile and Ohio Railway caused by 18MS not using train buy limit.
=> 18MS: Implement Mississippi Central Railway private

assets/app/view/game/spreadsheet.rb
fixes #1119 
Safari doesn’t support text-decoration shorthand (=> -webkit-prefix or split into -line and -style)
=> halfpay fix for Safari

lib/engine/config/game/g_18_mex.rb
Updating four tiles on map to include both town and city. Two tiles have them connected.
Result:
Also fixed tile 470:
=> 18MEX: Add towns to Mexico City et.al.

assets/app/view/game/buy_trains.rb, lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_train.rb
If a corporation owns trains but cannot afford to buy an available
permanent train (but has at least 50% of its price) the president
can assist in the purchase buy spending the difference (and an
extra $50 "fee").
Have added a president_assisted_buy in the base class that can
be overridden if the game support this feature.
=> 18MS: Assisted permanent train buy

lib/engine/connection.rb, lib/engine/graph.rb, lib/engine/part/node.rb, lib/engine/part/path.rb, lib/engine/step/tracker.rb
Now supports routing for tiles with a single intra-tile path (i.e. 18TN, 18MEX).
A fully robust fix will require more substantial changes (and will likely break existing games without taking special action).
=> Intra-tile path routing support

lib/engine/depot.rb, lib/engine/phase.rb
Since this fix just adds another condition for rusting, it does generate a log message of the form `-- Event: 3/5 trains rust --`, even though the only 3/5 trains that have rusted are the ones in the pool. If this is too confusing I can break it out into separate check that doesn't trigger that event notice (or triggers a different one).
=> Don't allow obsolete trains in pool (fixes #1438)

DEVELOPMENT.md
Pretty simple update -- add information for working in Windows using Windows Subsystem for Linux, Docker for Desktop and Visual Studio Code
=> Add basic instructions for using Windows for development

lib/engine/game/g_18_ms.rb
After map change New Orleans hex can now appear twice in a route
(city + town).
=> 18MS: Fix route bonus calculation for New Orleans (fixes #1600)

lib/engine/game/g_1882.rb
This commit updates the 1882 rules URL. It previously linked to the old pre-release rules but Scott Petersen uploaded a newer version a couple of weeks ago.
=> Update 1882 rules URL

assets/app/view/game/emergency_money.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_train.rb, lib/engine/step/train.rb
Fix bug #1553.
If player is missing resources during emergency buy, the player must borrow the needed money.
=> 18MS: Handle emergency buy

lib/engine/phase.rb
Log now displays:
```
-- Phase 6 (Operating Rounds: 3, Train Limit: 2, Available Tiles: Yellow, Green, Brown ) --
-- Event: 3 trains rust (The Depot x2, N&W x2, C&A x2) --
PRR buys a 6 train for $630 from The Depot
PRR skips buy companies
Player 2 operates B&O
```
=> Display owned trains that were rusted in log (fixes #1575)

assets/app/view/game/part/blocker.rb, assets/app/view/game/part/city.rb, assets/app/view/game/part/icons.rb, assets/app/view/game/part/label.rb, assets/app/view/game/part/location_name.rb, assets/app/view/game/part/revenue.rb, assets/app/view/game/part/small_item.rb, assets/app/view/game/part/upgrade.rb
Fixes  #1622 
Fixes #1417 
Minor preferred_render_locations tweaks for pointy maps: location_name, icons, blockers, cities (revenue), labels, upgrades...
Old:
New:
=> Pointy map rendering tweaks

lib/engine/config/game/g_18_al.rb
Removed the visual error. This was just done in config and does not affect game play.
=> Removed a visual error with limited train buying in 18AL (fixes #1625) 

lib/engine/ability/README.md, lib/engine/ability/tile_lay.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/special_track.rb, lib/engine/step/special_track.rb, lib/engine/step/tracker.rb
This PR implements private P1 and P2 in 18MS, which are privates that can lay extra yellow tiles during tile lay.
This require the possibility to specify empty hexes and tiles for the ability, so supporting this in the general code has been added.
=> 18MS: Implement private P1 and P2 + general tile lay anywhere

lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb
Use the track restriction instead of specific code, to stop
multiple visits to Atlanta in a run.
Before:
After:
And here is how parts of it looks like on the physical map:
=> 18MS: Modify Atlanta off-board hexes

assets/app/view/game/emergency_money.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_train.rb
In 18MS a player that is president for a corporation doing an
emergency buy cannot declare bankrupcy. Instead the player
must buy the cheapest train in the depot and borrow the amount
missing (+ $50 interest).
Debt is represented by negative cash (which is an existing
"feature). This stops the debtee to spend any cash (except
further loans)
If player has negative cash at the end of another loan is added
to the debt, which means that the debt is increased by 50% of
the remaining debt.
The final score in the game is share value plus cash, so this
means that any remaining debt after OR5.2 is automatically
deducted from the final score.
The display of the "Declare Bankruptcy" button during emergency
buy has been changed. If the active step(s) does not support
the 'bankrupt' action the button …
=> 18MS: Handle emergency buy with insufficient resources

lib/engine/game/base.rb, lib/engine/step/bankrupt.rb, lib/engine/step/g_1846/bankrupt.rb, lib/engine/step/route.rb
- add help text for running routes when corporation is in receivership
- when `@round.active_entities.map(&:player)` is empty (e.g., active corporation
is in receivership), mark all players as active so that they are alerted about
whatever action needs to be taken
- make bankruptcy and receivership "events" in the logs so they are not as
easily overlooked
[Fixes #1380]
[Fixes #1408]
=> 1846 - Small receivership/bankruptcy enhancements

lib/engine/config/game/g_18_ms.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/g_18_ms/buy_company.rb, lib/engine/step/g_18_ms/buy_train.rb
- Emergency buy corrections (No requirement to buy cheapest train, Do not allow presidency change)
- Train rusted during ORx.2 should be possible to buy/sell during ORx.1
- Improved rusting message (Make similar to common code)
- Correct salvage calculation (fixed bug, free 2 train should give salvage)
- Correct private P4: Mississippi Central Railway (Description text, close during exchange)
- Correct revenue for private P1
=> 18MS: Fix some problems discovered during pre-alpha test

lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb, lib/engine/step/emergency_money.rb, lib/engine/step/g_18_ms/buy_train.rb, lib/engine/step/train.rb
Introduce a possibility to sell more shares than needed during emergency buy.
Only title that supports this at the moment are 18MS.
Refactor emergency buy so that check for sellable bundles can be
used by sub classes of train buy.
Bug fix: Do not enforce purchase of cheapest train if game title
(1846, 18MS) allows buy of more expensive train during emergency buy.
Bug fix 18MS: Do not allow player loans to purchase train if there
still are shares to sell. This stops the bugs there game made it possible to
take loans to buy a non-emergency train via president assist.
Sort of bug fix: Avoid doing emergency buy in case there is an affordable cheaper train.
=> Improvements for trains buy

TILES.md, lib/engine/config/game/g_18_mex.rb, lib/engine/tile.rb
1. Change Mexico City upgrade tiles to use double track
2. Minor change to allow town_rect rendering on Puebla tile without specifying a location for the town
=> 18MEX tile update to use double track

lib/engine/step/g_1846/assign.rb
This is a bug from my steamboat work. When the player-owned steamboat is done
assigning, then the first corporation should `start_operating`. The effect here
was that when the Meat Packing Company was done assigning, `start_operating` was
called again, setting all of its trains to having not operated.
[Fixes #1682]
Unfortunately this will break games wherever a corporation bought in the Big 4, then bought in and assigned the Steamboat or Meat Packing Company, then ran its routes.
=> Only start operating if the assigning entity is the player-owned steamboat

lib/engine/game/g_18_tn.rb
If not all trains in a corporation is routed, the non-active trains
are used as the Civil War candidate trains.
=> 18TN: Use non-routed trains for Civil War resolution (fixes #1683)

assets/app/view/game/tools.rb, lib/engine/step/end_game.rb
still use `current_entity` in hotseat mode
[Fixes #1614]
This probably will need to be changed on #1330
=> acting entity for EndGame is the player corresponding to logged in user

assets/app/view/game/stock_market.rb
Firefox has an issue where borders are not scaled exactly when a page is not viewed at the 100% zoom level. This means that the calculation designed to make blank areas in the stock market exactly match the size of market cells fails, with the following effect:
This code makes blank cells match the size of real cells exactly, by giving them the same width, height, and border sizes, but with a border alpha of 0.
=> Make empty space in stock market more robust

assets/app/view/game/game_info.rb, assets/app/view/game_page.rb, lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb, spec/assets_spec.rb
The game now shows OR 1 (of 10) etc instead of OR 1.1 (of 2).
The OR numbering is local to 18MS, so the change of OR presentation
is only done in 18MS, but it is possible to override the
round_name method in game base class if a title want to
modify this.
18MS also add information in the log, and game page, about the next
upcoming time based event. So e.g.
In the log:
-- Operating Round 6 (of 10) - 3+ trains rust after OR 6 --
In the game page:
18MS: Operating Round 6 (of 10) - 3+ trains rust after OR 6 - Lay Track
Or
18MS: Operating Round 1 (of 10) - Change to Phase 3 after OR 1 -
2+ trains rust after OR 4 - Buy Trains
This is done by extracting the description to the round_description
method in game base class, and overriding it in 18MS.
Stock round description has not been changed. …
=> 18MS: Improve display of OR description, and add special info

lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/step/tokener.rb, lib/engine/step/tracker.rb, lib/engine/step/train.rb
Stops skipping ahead and allows users to buy track/trains or tokens
=> 1817: Players can take loans to be able to buy trains, tokens and track

assets/app/view/game/part/track_node_path.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/part/path.rb, lib/engine/tile.rb
Update 18MEX tileset.
Refactored code in Path and track_node_path to use per exit (actually "endpoint" - a or b) lane width and index attributes.
Updated Path#walk to only follow paths across tiles if they have compatible lane attributes.
New MC/P tiles for 18MEX:
=> Change lane attributes to be per exit rather than per path

assets/app/view/game/round/merger.rb, lib/engine/round/g_1817/acquisition.rb, lib/engine/round/g_1817/merger.rb, lib/engine/step/g_1817/acquire.rb
Corporations in acquisition cannot be merge/converted.
Fixes the order of corporations in acquisition
Players can offer companies up correctly
Correct initial bid prices
Improve the logging
Company -> Corporation
=> 1817: Improvements to auction side for liquidation, acquisition and offering

lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/step/route.rb
It's not awesome that there is now a `revenue_str` method that parallels `revenue_for`. However, refactoring the code so that the logic all happens in one place (building up the descriptive string while calculating the revenue) is not trivial and would also lead to some wasted computation (since `revenue_for` is called many times when the correct stops have to be chosen).
=> More verbose route descriptions in log (fixes #1063)

lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb
@round.round_num is not updated for new round before description
uses it in the log. Now the new round number is passed for this
case which solves the issue.
The game page is correct, as the round is created, and round
number incremented before it is shown.
=> Correct round description in log (fixes #1711)

assets/app/view/game/part/assignments.rb, assets/app/view/game/part/icons.rb, assets/app/view/game/part/small_item.rb
Allow assignments to be flexibly placed for pointy maps. Essentially repeating code changes already made for icons.
Fixes #1699 
Examples with fix:
=> Fix assignment placement for pointy map tiles

lib/engine/game/base.rb, lib/engine/step/g_1846/dividend.rb, spec/fixtures/1846/3099.json
also fix a buying_power bug, it should include the total price of the whole
issuable bundle
=> when skipping Step::Dividend, also pass Step::IssueShares

lib/engine/game/g_18_mex.rb, lib/engine/step/g_18_mex/track.rb
Los Mochos need special handling to upgrade to green.
Mexico City is in the game a two hex tile. So this is implemented in a way that when the Mexico City hex is upgraded, the Puebla hex is automatically upgraded with the corresponding tile.
=> Los Mochos and Puebla tile fixes

assets/app/view/game/part/track_node_path.rb, lib/engine/config/tile.rb, lib/engine/part/path.rb, lib/engine/tile.rb
Fixes #513 
Also fixed boolean calls in path.rb and one random tile.
New rendering:
=> Add crossover rendering

lib/engine/ability/README.md, lib/engine/ability/train_limit.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/game/g_18_ms.rb, lib/engine/phase.rb, lib/engine/step/discard_train.rb, lib/engine/step/g_1846/buy_company.rb, lib/engine/step/g_18_ga/buy_company.rb, lib/engine/step/train.rb
Add a train_limit ability, with attribute increase, that can be added
to a corporation to set a permanent increase in the train limit.
=> Make it possible to introduce a different train limit for a corporation

lib/engine/config/game/g_18_mex.rb
That hex is a very crowded one.
=> 18MEX: Remove Toluca from Mexico City location name

lib/engine/tile.rb
Current code in compute_crossover is fragile. It is dependent on the order of the paths in the tile definition. For instance, if the tile definition for tile 19 is changed from:
`path=a:0,b:3;path=a:2,b:4`
to
`path=a:2,b:4;path=a:0,b:3`
we get:
With this change, this becomes:
I realize this was changed for performance reasons, so I added an early bail-out for tiles with less than two paths, which can never have a crossover.
=> Fix crossover rendering

assets/app/view/game/buy_trains.rb, lib/engine/ability/README.md, lib/engine/ability/train_buy.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/step/train.rb
Supported attribute is face_value. If true, inter corporation
buy of trains must be at exactly face value.
=> Add a train_buy ability to allow for restricting train buys

assets/app/view/game/hex.rb, assets/app/view/game/map.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/game/base.rb, lib/engine/hex.rb
18MS has no hexes in column 14, now we can add an "empty" hex like B14 to fix axes rendering. Seemed like this would be simpler than trying to identify and fill gaps in letters or numbers.
Before:
After:
=> allow "empty" hexes in game conf definition, fix axes for 18MS column 14

lib/engine/part/path.rb, lib/engine/tile.rb
Refactored crossover methods to allow a node rendered next to an edge (i.e. not in center) to act like the path connected to it from a different edge is connected to that edge (only for the purposes of crossover detection).
Fixes #1753 
This gets us here:
=> More robust handling of crossovers with cities/towns

lib/engine/game/g_18_ga.rb, lib/engine/step/g_18_ga/only_one_token_per_round.rb, lib/engine/step/g_18_ga/special_token.rb, lib/engine/step/g_18_ga/token.rb, lib/engine/step/special_token.rb
There were several problems with W&S RR special ability tokening. Now the special tokening and normal tokening act better together and this should be OK. Might break some games where special tokening is not used, as an extra Pass is now required in case it were not possible to token before. Also ensure tokening can only be done in the tokening phase of the OR.
Finally, track laying ability did appear in SR. By removing all other steps (besides buy and sell shares) it should now not appear at all in the SR.
=> Correct abilities of 18GA 

lib/engine/connection.rb, lib/engine/part/base.rb, lib/engine/part/edge.rb, lib/engine/part/junction.rb, lib/engine/part/node.rb, lib/engine/part/path.rb, lib/engine/step/tracker.rb, lib/engine/tile.rb
Fixes #1756 
1. Recoded Path "<=" method to comprehend junctions (via new jwalk method). This was needed to allow upgrades to Lawson tiles.
2. Junction class no longer is a subclass of Node, but of Base directly
3. Modified Path "walk" method to comprehend junctions
4. Added Path "match?" method that is identical to old "<=" method
5. Modified Connection "branch!" method to deal with junctions
6. Removed branches array from Path and Tile
=> Add support for Lawson tiles: upgrades and routes

assets/app/view/game/player.rb, assets/app/view/game/round/stock.rb, assets/app/view/game/spreadsheet.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/player.rb, lib/engine/share.rb, lib/engine/share_holder.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/share_buying.rb, spec/lib/engine/player_spec.rb
Do not count 5% shares for cert limit
5% are sold one at a time, in separate bundles.
When selling a 5% share it does not affect share price.
TODO: What remains to implement is two things:
- If owning 2 5% it looks as if it is 1 share
- The rules have a special case where you can sell 5%
if you own 10% or more, and there is a 5% in the open market.
Maybe this should be an exchange action? As we are
not allowed to sell 10% and then buy 5%.
=> 18MEX: Special handling of NdM 5% shares

lib/engine/config/game/g_1817.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/round/g_1817/acquisition.rb, lib/engine/round/g_1817/stock.rb, lib/engine/round/operating.rb
M&A didn't happen in the second OR.
Add end game due to train export
=> 1817: Fix M&A in OR 2, add end game after the 8 train is bought/exported

lib/engine/step/tracker.rb
Quick edit to check_track_restrictions!
By inspection, I saw that properly detecting a revenue increase is dependent on the order the paths on the new tile are inspected. I made changed_city parallel how used_new_track works.
=> Make check_track_restrictions! more robust

assets/app/view/game/dividend.rb
A frequently requested feature is the ability to see the route of a company on the map. There are numerous suggestions of ways of doing this, but I think the easiest one to implement is to show the route during the dividend step.
This should (at least partially) address issues: #1611, #1250 ant #563
=> Show route during dividend step

lib/engine/step/g_18_mex/special_track.rb
The label sometimes did cover the revenue circle. So removing
this solves that. And the tile cannot be upgraded so it should
not be a problem.
=> 18MEX: Remove CC label when placing Copper Canyon tile

lib/engine/config/game/g_18_mex.rb
If need be, NdM tokens will be added as part of the NdM merge in phase 5.
=> 18MEX: Do not show exchange tokens in NdM charter

assets/app/view/game/corporation.rb, assets/app/view/game/round/merger.rb, assets/app/view/game_page.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/part/city.rb, lib/engine/step/g_18_mex/assign.rb, lib/engine/step/g_18_mex/merge.rb, lib/engine/step/g_18_mex/single_depot_train_buy.rb
When first 5 train is bought the NdM merge event is triggered
if NdM has floated.
The merge process if that player in order, left of the player
that has bought the 5 train, is asked if their corporation wants
to merge. (Excluding "American" corporations, and corporations
controlled by NdM president.) If there is no floated corporation
that accepts, NdM will merge with any non floated, if there is
any eligible one.
The president of the merged corporation receives a 10% reserved
NdM share in exchange for their presidency. Remaining shares
in merged corporation is force sold for half amrket price.
Treasury and trains are transfered to NdM.
NdM also exchanges up to two tokens, one should at least be
the home token if any.
There are a new step: merge, which is located in module 18MEX.
This is …
=> 18MEX: Support NdM merge

lib/engine/route.rb
Fixes #1125 
Modify behavior of Route.touch_node to filter out connections that use paths already in the partially completed route being built. Unlike the last time I tried this - I specifically do _not_ filter out the paths in the most recently added connection so that clicking on the last node in the connection list will correctly switch between alternatives (but now, only legal alternatives).
For example, when selecting this route, the existing code initially creates an illegal route:
Before:
After:
=> Filter out illegal paths during run_routes

lib/engine/game/g_1817.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1817/selection_auction.rb
Fix initial auction player order on >3 players
Correct PAR value
Allow players to PAR when cash doesn't cover all of the money
Don't show bid if players cannot afford it
Allow subsidiries to cover exactly the price of a corporation (fixes #1833)
=> 1817 Bug Sweep:

lib/engine/config/game/g_18_mex.rb, lib/engine/config/game/g_18_ms.rb
It seems some players do forget to use this feature so adding it
should hopefully work as a reminder.
=> 18MS: Add line to P1/P2 description about OR 1 buy-in.

lib/engine/game/base.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/route.rb
only trains in the same overlap group are not allowed to reuse track; this
allows for 18 Los Angeles's Freight and Passenger trains to work correctly
=> 18 Los Angeles - allow Freight and Passenger trains to use the same track

assets/app/view/game/map.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/hex.rb
- a9 and G14 really only exist so that upgrades for A8 and F13 are less
restricted; on the actual map they aren't drawn as a full hex
- use small letters for "negative" letters, i.e., row a is above row A, row b is
above row a, and so on; #1849 will use this for an "a12" hex
- add hex attr `ignore_for_axes` to keep the axes rendering from taking a hex
into account--in the case of 18 Los Angeles, don't render labels for rows "a"
or "G"
=> 18 Los Angeles - offboards to nowhere, "negative" lettered axes

assets/app/view/game/part/track.rb, assets/app/view/game/part/track_node_path.rb, assets/app/view/game/part/track_offboard.rb, assets/app/view/game/part/track_stub.rb, assets/app/view/game/tile.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/game/base.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/part/base.rb, lib/engine/part/path_stub.rb, lib/engine/part/stub.rb, lib/engine/step/tracker.rb, lib/engine/tile.rb
"Stubs" around Long Beach in 18 Los Angeles that count as track which must be respected when laying a tile:
Offboard/Terminal Cities Before:
Offboard/Terminal Cities After:
=> 18 Los Angeles path stubs, fix rendering for offboards and terminal cities

lib/engine/step/g_1817/dividend.rb, lib/engine/step/half_pay.rb
Half-paying as 2-share companies in 1817 is off as reported in [issue 1888](https://github.com/tobymao/18xx/issues/1888). This PR updates dividend logic to support this case.
I can think of 2 sensible approaches:
- extend 1817 dividend logic to accommodate half-paying as 2-share companies.
- update half-paying logic to work for 2-share companies in 1817.
While private companies and minor companies are common in 18xx games, I cannot think of another title, 18USA excluded, with 2-share companies. The key questions for choosing between the above options are:
- how likely are we to add another title with variable number of shares?
- when that day comes, are we happier refactoring 1817 logic for the new title (downside of first approach) or branching out 2 different logic for 2 different …
=> Issue 1888 Half-pay dividend for 2-share companies.

lib/engine/config/game/g_18_tn.rb, public/icons/18_tn/etwcr.svg, public/icons/18_tn/mcr.svg, public/icons/18_tn/owr.svg, public/icons/18_tn/tcc.svg
Resolves #1879 
Handle bars are typically used for blocked hexes. This implementation mirrors how 1846 handles denoting tile lay placements for private company hexes that are not blocked.
=> Add company indicators to 18TN ( Issue 1879 )

assets/app/view/game/part/city.rb, assets/app/view/game/part/city_slot.rb, assets/app/view/game/part/label.rb, assets/app/view/game/part/town_dot.rb, assets/app/view/game/part/town_rect.rb, lib/engine/config/game/g_1860.rb, lib/engine/part/base.rb, lib/engine/part/halt.rb, lib/engine/part/town.rb, lib/engine/tile.rb
Created new tile part: Halt, which is a subclass of Town.
Changed 1860 tile definition to use Halts.
Changed rendering to handle Halts.
Also made other rendering tweaks/fixes so 1860 tiles display correctly.
New:
=> Adding Halts. Other 1860 tile rendering fixes.

lib/engine/config/game/g_18_ga.rb
Closes #1895 
I checked the Info page locally and this fixed the issue, but I'm not sure if there are any other implications of this change.
=> No grey tiles exist in 18GA

assets/app/view/game/dividend.rb, lib/engine/game/g_18_co.rb, lib/engine/step/dividend.rb, lib/engine/step/g_18_co/dividend.rb
**Dividends**: Adjust​ ​the​ ​Stock​ ​Token​ ​one​ ​space​ ​right.​ ​If​ ​the​ ​revenue​ ​was​ ​at​ ​least​ ​twice​ ​the​ ​original​ ​Stock​ ​Market​ ​Value​ ​this round,​​ ​move​ ​the​ ​token​ ​one​ ​space​ ​up.
-----
The current code only allows for one direction of movement, as well as only right and left.
My solution is to allow an array to be specified for both share_direction and share_times. This is supported by the changes to **lib/engine/step/dividend.rb** . I have chosen to make this change to the base dividend.rb (rather than 18CO specific) so any future game could take advantage of the capability. I chose to add support for _down_ for completeness. Current integer format still works the same way. Here is a working example of the …
=> Generic support for Multi-directional Dividend Movement ( 18CO rule )

lib/engine/step/tracker.rb
in 18 Los Angeles, Beverly Hills Company can lay track pointing towards
Hollywood and completing the bridge; even though it doesn't have to pay for
this cost, the border needs to be removed
[Fixes #1906]
=> [18 Los Angeles] fix terrain border not disappearing when completed by a company

assets/app/view/game/corporation.rb, lib/engine/corporation.rb, lib/engine/game/g_18_mex.rb
If there are reserved shares, do deduct them from IPO nunber shown
and show them on a line of their own (without price).
In case the corporation uses fractional shares (e.g. NdM uses
5% shares that appear as 0.5) then show one digit fraction even
if the share number to show has fraction .0. This will make for
better reading of the share number.
=> 18MEX: Improve presentation of fractional/reserved shares (fixes #1848)

lib/engine/step/g_18_ga/token.rb, lib/engine/step/g_18_ms/token.rb, lib/engine/step/tokener.rb
Should only be able to give the free token in the originally reserved city, not another city even if the owning corporation is connected.
Reported as an 18 Los Angeles problem, but unsurprisingly also applies to 1846
[Fixes #1897]
=> [1846, 18 Los Angeles] fix C&WI (and PMC) giving free token in connected other city

assets/app/view/game/corporation.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/game/g_18_mex.rb
Fixed spelling error for Copper Canyon private.
Fix three reported bugs:
- #1916 Show treasury for unfloated corporation if it is non-zero
- #1917 Fix invalid method call during NdM merge
- #1918 Place NdM in home city for merged even if merged haven't operated yet
- #1919 Fix invalid exchange token swap during NdM merge
=> 18MEX: Fix 4 errors reported

lib/engine/game/g_18_mex.rb
By deleting the train when minor close it will not appear in
the rusting message.
=> 18MEX: Remove train from closing minor (fixes #1926)

lib/engine/config/game/g_18_mex.rb
Visual update of hex F5 to make it indicate that this hex is special.
This might be improved in the future.
=> 18MEX: Add mining icon in the Copper Canyon hex (fixes #1923)

lib/engine/config/game/g_1817.rb, lib/engine/corporation.rb, lib/engine/game/g_1817.rb, lib/engine/round/g_1817/merger.rb, lib/engine/round/g_1817/operating.rb, lib/engine/step/g_1817/conversion.rb, lib/engine/step/g_1817/post_conversion.rb
Turn order in merger (fixes #1884)
2+ train should obsolete (fixes #1871)
Only treasury shares can be bought in merger (fixes #1857)
Mail contracts should payout (fixes #1881)
Merger round skipped if first entity cannot be merged (fixes #1876)
=> 1817 Bug Fixes

lib/engine/step/issue_shares.rb
In IssueShares, a call to blocking? results in a call to actions, generating an infinite loop if actions isn't empty and the step is set to block. Not seen in any current games due to 1846 being the only current game using IssueShares and being set to non-blocking.
=> Switch blocking? call to blocks? call to prevent infinite loop

assets/app/view/game/stock_market.rb, lib/engine/config/game/g_1860.rb, lib/engine/game/g_1860.rb, lib/engine/share_price.rb, lib/engine/stock_market.rb
Adding support for a new market type: Zig-zag. It's basically a variation of a 1D market:
I also added two new share-price types: "repar" and "ignore_one_sale". I added it to the base SharePrice as opposed to a game-specific class because I needed a corresponding change in the UI StockMarket view.  I suspect all of this (price types) should be eventually refactored to be completely game defined and make the UI as generic as possible.
=> Add ZigZag market for 1860

lib/engine/game/g_18_mex.rb
Resolves https://github.com/tobymao/18xx/issues/1948
Mail contract needs to use the base revenue for the location, not the train multiplier modified value.
=> Fix 18Mex doubling of mail contract

assets/app/view/game/actionable.rb, lib/engine/action/base.rb, lib/engine/game/base.rb, routes/game.rb
Resolves #509 
This is a normal action
```
{
"type": "bid",
"entity": "Vanish",
"entity_type": "player",
"id": 2,
"company": "O&I",
"price": 40
},
```
This an action when taken with master mode and it isn't your turn
```
{
"type": "bid",
"entity": "Garramon",
"entity_type": "player",
"id": 3,
"master_user": "Vanish",
"company": "C&WI",
"price": 60
},
```
_Note: Currently, the value of master_user is the user['name'] following the pattern set by entity. It could be the user['id'], with the name fetched at display time. That might be a better implementation for the future. Thoughts?_
Sample of log output
**lib/engine/action/base.rb** - I don't love the code here. I feel like there is probably a cleaner way to implement within the other methods of the action class. However, subclasses …
=> Add master mode to log ( Issue 509 )

lib/engine/game/g_18_mex.rb, lib/engine/step/tracker.rb
Adding "city_permissive" - allows any tile with a city to be laid, but restrictive o.w.
Fixes #1945 
Fixes #1947
=> Add new TRACK_RESTRICTION type for 18MEX

lib/engine/game/g_18_co.rb
Denver and Colorado Springs can only be laid with orientation pointing north.
=> [18CO] Denver and Colorado Springs fixed tile rotations

lib/engine/g_18_co/stock_market.rb, lib/engine/game/g_18_co.rb
... If​ ​the​ ​token​ ​is​ ​at​ ​the​ ​top​ ​edge​ ​upon​ ​an​ ​upwards​ ​movement,​ ​instead​ ​move​ ​it​ ​one​ ​space​ ​right.
None of this code is mindblowingly new.
The `share_price(r - 1, c)` check is not explicitly necessary considering we know the shape of the 18CO market and there are no blanks possible if the row is greater than or equal to zero, but I would rather not make that assumption.
The elsif prevents an infinite loop of move_right calling move_up and vice versa.
=> [18CO] Game specific stock market to allow for right movement at top

assets/app/view/game/buy_sell_shares.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/share_pool.rb
Remove button to short when unable to short a corp (fixes #1964)
Remove market limit on shares for 1817
Fix error in use of max (fixes #1963)
=> 1817 Bug Fixes:

lib/engine/game/g_1817.rb, lib/engine/share.rb, lib/engine/share_pool.rb, lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1817/conversion.rb, lib/engine/step/g_1817/post_conversion.rb
5 share merger resulted in incorrect results (fixes #1878)
Avoid cross-short president-less merges (fixes #1969)
Shorts are limited to corp size (fixes #1970)
Shorts should cancel when bought in post-conversion (finishes #686)
Short dividend should be payable in acquisitions
Correct share percentage calculations
=> 1817: Implement 5 share merges and finish 1817 implementation

assets/app/view/game/round/stock.rb, lib/engine/game/base.rb
For 1817 the amount of corporations gets confusing
Sort those that have been IPOed by their running order
Then others leave in symbol order
Done in base class to game so that other games (18CO and 1849 etc) can override.
This does have the slight impact to the UI that the position can change dynamically,
but this makes it clearer the change in stock price.
fixes #1838
=> Sort corporations in stock rounds.

lib/engine/game/g_18_mex.rb
=> 18MEX: Minors are only allowed to lay one yellow, and no upgrades.

lib/engine/share.rb, lib/engine/share_bundle.rb, lib/engine/share_holder.rb, lib/engine/step/dividend.rb
share.rb and share_bundle.rb gave 0 as price for share counts
not evenly divisable by 10. This caused the 5% of NdM in 18MEX
to be excluded from the value (on the server side).
When paying out revenue, use float for num_shares to handle
the NdM case.
In both cases ceil is used to round up.
This might fix several problems that has been reported, although it is hard to verify.
But I think the following might be solved:
- Fixes #1978 
- Fixes #1939 
- Fixes #1955 
- Fixes #2006 
If this PR is approved I intend to close the issues.
=> Correct price for 5% shares (on the server side)

lib/engine/corporation.rb, lib/engine/game/g_18_mex.rb
Added move of shares in bank pool to IPO. Failure to do this
caused games with 50% in bank pool of shares from merged corporation
to fail as it was still regarded as floated.
=> 18MEX: Corrections of Close handling of corporation during merge

lib/engine/game/base.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/company_pending_par.rb
From the discussion originally started here: https://18xxgames.slack.com/archives/C012K0CNY5C/p1603228267463700
**Background**
18CO is incremental capitalization. It has two privates built with the Shares ability. As the ability is currently written, the corporation does not receive treasury cash for those shares when the par is set. https://github.com/tobymao/18xx/issues/1836
I wanted opinions on whether I should:
1.) Implement this at the 18CO game level
2.) Add a new optional attribute to the Shares Ability ( par_cash: boolean ? )
3.) Make this the default for Shares abilities with incremental cap
Further discussion suggested option 3 as the appropriate path:
Chris Rericha  4:15 PM
Option 3 makes sense to me. To my knowledge, **that is the standard for how incremental cap games work** …
=> The treasury should receive money for shares from abilities in incremental cap games

lib/engine/route.rb
When a train ignores a revenue center type, such as the 4Ds in 18CO visiting but not paying towns, the block above is never run and thus revenue is never defined. This results in an error being thrown on return stops if revenue.positive?
Fix is to ensure revenue is defined with a default of 0
=> Fix Revenue Nil for positive?

lib/engine/game/g_18_mex.rb, lib/engine/train.rb
8a: Allow corporations (not minors) to lay a 3rd yellow tile (or 1
upgrade) during its first OR. For its second OR and later it is 2
yellow or 1 upgrade.
8d: Use normal (hard rust) 4 trains
Optional rule 8b and 8c are not yet implemented.
=> 18MEX: Implement support for optional rule 8a and 8d

lib/engine/route.rb
Current code doesn't check to see if a route passes through a city that has "terminal" paths.
This fixes that by checking to see if a route has a terminal flag on any path that is not at the very beginning or end of the route.
Only games known to be impacted: 18AL and 18MEX.
Fixes #1967
=> Check for terminal path in middle of route

lib/engine/game/base.rb, lib/engine/step/tracker.rb
Game 13797 created a tile 8-10, and then created another.
This caused a second 8-10 tile to be created corrupting the game.
=> 1817: Allow more than 10 tiles

assets/app/view/game/part/blocker.rb
[Fixes #2025]
Screenshots taken immediately after a corp buys in the C&OC...
Before:
After:
=> fix C&OC still being rendered on tile after it is bought in

lib/engine/corporation.rb
In case a corporation is merged, it loses its share prace (it
becomes nil) but then the merged corporation can move to last place
in the list as it will not do anything during the operation round.
(And the next OR/SR it will not appear.)
=> 18MEX: Fix nil problem in corporation order sort

lib/engine/tile.rb
Special case for Tile::paths_are_subset_of? => if a Lawson tile to a Lawson tile, just look at exits.
If we ever have a tile with a junction that has anything other than exits on it, this will break (but probably so will a lot of other code).
Fixes #2016
=> Fix for upgrading Lawson tiles to Lawson tiles.

assets/app/view/game/spreadsheet.rb
The numbers need to be strings - IPO column corrected.
Share numbers should not be rounded, use fractions if such exists.
(Needed for 18MEX 5% shares)
=> Fix bug with share count presentation in spreadsheet

assets/app/view/game/part/track.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/step/g_18_los_angeles/route.rb
- add help text in route step to tell user the routes can overlap
- render both routes, making the bottom one much thicker so it is visible
=> 18 Los Angeles - better handling of passenger/freight route overlap

assets/app/mail/turn.rb, assets/app/view/game_page.rb, lib/engine/game/base.rb, lib/engine/player.rb, routes/game.rb
Step 1 for #1135
Engine now takes a hash of players id's to names. This is currently ignored but lays the foundation for future fixes.
This can go in now, and more changes can come later.
Next steps
1. Clean up parts of the UI that use id rather than name. (I've seen a few)
2. Write migration script
3. Modify user settings to use id rather than name
4. Add UI to change player names
One thing I've spotted is that player names are used in the game results, my solution to this is to rerun unpinned games with that player in and store the new result.
=> Modify engine to use playerid->username hash for future modifications to allow players to rename themselves.

assets/app/view/game/part/city_slot.rb, assets/app/view/welcome.rb, lib/engine/ability/token.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/hex.rb, lib/engine/part/city.rb, lib/engine/step/g_18_los_angeles/special_token.rb, lib/engine/step/tokener.rb
- 18 Los Angeles's private company "Dewey, Cheatham, and Howe": place a token in
city with no available slots (and provide the name for this token argument)
- 1846 2p Variant setup: removed corporations place a second token in slot 1
instead of slot 0; this is functionally equivalent to current behavior (token
is placed when green tile is laid, has no real effect before then) but way
more obvious what is happening, and takes advantage of the digital platform
[Closes #1806]
=> "cheater" tokens for 18LA DC&H, 1846 2p Variant setup

assets/app/view/game/part/upgrade.rb, lib/engine/config/game/g_1817.rb, lib/engine/step/g_1817/special_track.rb, public/icons/lake.svg
Players owning mines were getting a free discount on 'mineable' tiles irrespective of using the special (fixes #2066)
Add 'lake' terrain type and update non-discounted $20 tiles to use the lake terrain (fixes #2069)
=> 1817: Mine discount and add lakes

assets/app/view/game_card.rb
Only show the "private game" string if the game is new, as requested by Toby
Don't show the Description if it's empty
=> Only show the "private game" string if the game is new #2067

assets/app/view/create_game.rb, assets/app/view/welcome.rb, lib/engine/game/base.rb, lib/engine/game/g_18_los_angeles.rb, routes/game.rb
- fix including optional rules when importing games with JSON [Fixes #2053]
- fix server side creation of games to include the optional rules [Fixes #2062]
- don't show optional rules that aren't valid for the given player count
=> optional rule fixes, plus 18 Los Angeles beta

lib/engine/game/g_1817.rb, lib/engine/round/g_1817/acquisition.rb
Keep a track of corps share price before the merger round and filter out those
which just entered acquisition (fixes #2061)
=> 1817: Corps entering acquisition in merger round should skip acqusition round.

routes/game.rb
I want to automatically create all the games for the 1846 tournament and send the links to the players.
Using the API directly I can create all of them and then leave. But after I leave I cannot start the game (nor could any of the players).
=> Allow the "owner" of the game to act even if they are not in the game

assets/app/view/game/par.rb
Displays the number of shares the player could buy with cash in each par price button. Adjusts the button padding so the number is on its own line.
This is a feature that the old DOS 1830 game has that makes it easy to see at which par prices you can float a company on your own.
This does not take into consideration the per corporation share limit, so games with low par prices (e.g. 1846) will show an unobtainable amount of shares.
=> When selecting par value, display number of purchasable shares.

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb, lib/engine/part/town.rb, lib/engine/step/g_18_co/track.rb, lib/engine/tile.rb
Add a new option that allows a town tile to upgrade to a city tile. Used in 18CO, 18NEB, 1825, 1829, 1856, etc ( Section 5.4 http://www.fwtwr.com/18xx/rules_difference_list/single_list.htm#5 )
The non-18CO specific changes are adding the `to_city` option and changing the definition of `<=` for Town. It would be reasonable to debate the name of the attribute `to_city`, its just what was in my head at the time.
In `<=` I choose to make it explicit that the only time we don't use the `super` definition is when both `to_city && other.city?` are true. There could be an argument made to use the shorthand `return to_city if other.city?` but that would change the logic of how `<=` works for a town tile that doesn't use the new feature and I wanted …
=> Option flag to allow town to upgrade to city

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/dividend.rb, lib/engine/step/g_18_co/track.rb
_This change only impacts 18CO files._
- Placing a tile on a location with a mine places the mine token onto the corporation's charter.
- Mines award $10 per mine directly to the treasury after the dividend step as long as a train was run
- Idarado Mining Company: Money gained from mines is doubled for the owning Corporation. Closes phase 5 if owned by a player. Closes phase 6 if owned by a corporation.
- Mines are removed from the board in phase 6
Mines show up as a corporation ability
Log is written to when a corporation picks up a mine as well as when mine money is awarded
Rather than define new Ability classes I am working with the Base class. I don't know any other games that use tokens like this. One downside is the need to build a …
=> [18CO] Specific Mine Implementation

assets/app/view/chat.rb, assets/app/view/log.rb, public/assets/main.css
Improves the styling of the homepage chat.
- Bolded username
- Smaller timestamp
- Timestamp only shows date for messages older than one day
- Slight indentation of word wrapped messages (also applied to the in-game log)
- Slightly increased spacing between messages
=> Improved chat style

lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/train.rb
Need to update variant as well when setting obsolete_on, rusts_on.
Update description text for optional rules.
Also remove unnecessary parantheses in the general presentation
of optional rules.
Before:
-- Phase 2 (Operating Rounds: 1, Train Limit: 3, Available Tiles: Yellow ) --
Optional rules used in this game:
* Hard rust: (8d: Hard rust for 4 trains)
After change:
-- Phase 2 (Operating Rounds: 1, Train Limit: 3, Available Tiles: Yellow ) --
Optional rules used in this game:
* Hard rust: 4 trains rust when 6' train is bought
=> 18MEX: Correct bug with hard rust 4 train (fixes #2049)

lib/engine/step/g_1817/special_track.rb
Mines can only be placed next to existing track
Mines must be connected to a revenue location
or could potentially be upgraded to be connected
fixes #2082
=> 1817 Mines restrictions

lib/engine/step/g_1817/buy_sell_par_shares.rb
Improve wording of log on player pass when acting for corps (fixes #2111)
Cannot purchase shares of corps in acquisition (fixes #2107)
SR order should be Sell, Short then Buy (fixes #2108)
=> 1817: Various fixes for stock rounds

lib/engine/config/game/g_18_mex.rb
Green tiles 474 and 619 should be 2 according to the rules, but was 1.
=> 18MEX: Correct tile count (fixes #2118)

lib/engine/config/game/g_18_mex.rb, lib/engine/game/g_18_mex.rb
In 18MEX, add a playertip (to FCP/PAC and TM) that the corporation
cannot be merged into NdM. Remove this playertip when phase 5 starts.
=> 18MEX: Add playertip to FCP/PAC and TM (fixes #2133)

assets/app/view/game/buy_trains.rb, lib/engine/step/train.rb
In case buying trains from/to a corporation that has the train_buy
ability (that restricts to only sell/buy trains at face value) those
trains should not appear as buyable in case they cost more than the
buying corporation has in cash.
=> 18MEX: NdM trains should not be buyable unless enough cash (fixes #2044)

assets/app/view/game/buy_sell_shares.rb
This is currently only for 18MEX but it is general code that will
be used as soon as there are different percentage shares in the
share pool.
In case there is just one type of shares the behavior will not be changed.
In case there are more the one type of percentage in the share pool
the percentage of the market share will be shown on the Buy button.
This is also presented even if only one of the types are buyable.
So, using 18MEX as an example:
* If 5% and 10% are in market pool, and player can buy both
Show: "Buy 5% Market Share" "Buy 10% Market Share"
* If 5% and 10% are in market pool, but player can only buy 5%
Show: "Buy 5% Market Share"
* If just 5% or 10% shares are in market pool
Show "Buy Market Share"
* And this means - if not 18MEX
Show "Buy Market Share"
This fixes #2097
=> In case different percentages is in market, separate buy buttons

assets/app/lib/publisher.rb, assets/app/view/game/game_info.rb, assets/app/view/welcome.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1860.rb, lib/engine/game/g_1882.rb, lib/engine/game/g_1889.rb, lib/engine/game/g_18_chesapeake.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/game/g_18_mex.rb, lib/engine/game/g_18_ms.rb, lib/engine/game/g_18_new_england.rb, lib/engine/game/g_18_tn.rb, lib/engine/publisher.rb
* a game's `GAME_PUBLISHER` is now just the symbol (or array of symbols)
* on the welcome page, automatically display the publishers of all alpha-and-up
games, sorted alphabetically--no more manually updating this list when a new
publisher is added
* fix `<p>` tag for publishers section on welcome page
* support for displaying multiple publishers on game info pages
* add Golden Spike Games as a second publisher of 1846
* add Sea Horse Laser & Design as a second publisher of 18 Los Angeles
* add missing publisher info for some games:
* 18MEX (All-Aboard Games)
* 18TN (Golden Spike Games)
* fix spelling ("All Aboard" -> "All-Aboard")
* alphabetize publishers in `lib/engine/publisher.rb`
* add Golden Spike Games to `lib/engine/publisher.rb`
=> Various publisher improvements

lib/engine/depot.rb, lib/engine/game/g_18_al.rb, lib/engine/hex.rb, lib/engine/operator.rb, lib/engine/train.rb
Optional rule 7a means that the first OR for any corporation, it
may lay 2 yellow tiles instead of 1 yellow or 1 upgrade.
Optional rule 7b means that the home location for L&N corporation
is moved to Decatur. This also means that hex A3 is turned into
an off board hex.
Optional rule 7c means that the number of 4D trains are unlimited.
This will change the number of 4D from 5 to 8. Theoretically
each of the 6 corporations may own 2 trains each, and there are
4 other permanent trains, so 8 4D is the max number of trains
that can be owned by corporations.
Optional rule 7d means that the 4T trains now are rusted by 7T
instead of phased out.
=> 18AL: Implement optional rules (fixes #2036)

assets/app/view/game/game_info.rb, lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb
Support the two optional rules of 18MS:
- An extra OR (11th) just after OR 10
- Possibility to buy (rusting) trains
Have made TIMELINE a method in base class instead so that
18MS can override it, and change game end info.
=> 18MS: Support optional rules (fixes #2042)

assets/app/view/game/spreadsheet.rb, lib/engine/game/base.rb, lib/engine/game/g_18_ms.rb
Create a general method for printing turn and OR in spreedsheet. Override this for 18MS.
=> 18MS: Fix OR history description (fixes #2141)

lib/engine/config/game/g_18_mex.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/step/g_18_mex/buy_company.rb
Optional rule 8b is to make it allowed to by KCM&O private
from any player, for up to face value.
Optional rule 8c is to delay close of minors until next SR.
=> 18MEX: Support optional rule 8b and 8c (fixes #2038)

lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/issues_shares.rb, lib/engine/step/g_18_co/redeem_shares.rb
Ref: https://github.com/tobymao/18xx/issues/1836
Issue and Redeem occur during completely different parts of the OR in 18CO, therefore the existing Step could not be reused.
- The​ ​active​ ​Corporation​ ​may​ ​purchase (redeem) its own​ ​stock​ ​certificates​ ​from​ ​the​ ​Market.
- Shares are issued one at a time. For each share issued, the share price drops.
=> [18CO] Issue and Redeem Shares

lib/engine/config/game/g_18_co.rb, lib/engine/hex.rb
Without the _any?_ check, the first city will always match regardless of which city index is specified in the config. We should instead assume the city has the same index. In the case where that city's index is no longer available on the tile, use index 0, which is the same as the original code would have returned.
Ref: https://github.com/tobymao/18xx/issues/1836
DSL, DRG, DPAC and CM have fixed home token locations on tiles that have multiple stations.
---
DSL is assigned the top left position correctly.
**Before the fix**, the token would jump to the bottom right because no exits is a subset of exits 0+5, even though the city index is set to 1 in the config file.
**After the fix**, the token is in the correct position.
Green Tile upgrade is also grouped correctly ( Different game shown …
=> Fix city assignment on upgrade and set 18CO Token Cities

lib/engine/step/g_1817/buy_sell_par_shares.rb
A player should only be able to bid the values of the companies combined.
(fixes #2117)
=> 1817: Disallow bids that aren't valid combinations of companies

assets/app/view/game/par.rb
Enhances the par share count button helper text by limiting the amount of shares shown to be purchasable to the corporation ownership limit. Appends an "L" flag in this case.
=> Don't imply shares can be over limit in par step

assets/app/view/game/buy_trains.rb, lib/engine/step/buy_train.rb, lib/engine/step/train.rb, validate.rb
* if shares have been sold to help buy a train, that cash must be used if buying
from another corporation
* also fix max spend; if the game allows EMR when cross-buying a train, allow
president to contribute cash even before shares have been sold
* don't allow cashless corporations to ebuy from others when EBUY_OTHER_VALUE is false
* update `validate_all()` in `validate.rb` to take a list of titles
[Fixes #968]
[Fixes #2230]
examples of behavior that this PR fixes: https://www.18xx.games/game/3063?action=442 and https://www.18xx.games/game/13894?action=376
=> Enforce minimum spend when emergency buying train from a corporation, enforce EBUY_OTHER_VALUE for cashless corporations

assets/app/mail/turn.rb, assets/app/view/create_game.rb, assets/app/view/game_card.rb, assets/app/view/game_page.rb, routes/game.rb, spec/fixtures/18_ms/14375.json, validate.rb
Migration script I used locally to fix game settings for this change:
```
require_relative 'validate'
where_args = {
Sequel.pg_jsonb_op(:settings).has_key?('optional_rules_selected') => true,
}
Game.where(**where_args).each do |game|
game.settings['optional_rules'] =
if game.settings.has_key?('pin')
game.settings['optional_rules_selected'] || []
else
game.settings.delete('optional_rules_selected') || []
end
game.save
end
```
=> refactor: drop "selected" from `optional_rules_selected`

assets/app/view/game/corporation.rb, assets/app/view/game/sell_shares.rb, lib/engine/share_pool.rb
Here is how the charter looks like with the Trade-in line removed. As well as how the sell button looks like for 5% shares.
And here is how the log looks like after the change:
=> Fix 5% share presentation in charter, logs and sell button

lib/engine/game/g_18_mex.rb
Then the minor is merged, the connected private company need to
be closed as well. This will correct the certificate count and
the minor do longer appear in the spread sheet as owned company.
=> 18MEX: Remove minor connect company at minor close (fixes #2172)

lib/engine/game/g_18_mex.rb, lib/engine/step/g_18_mex/merge.rb
Does improve the log message for showing merge candidates.
This addresses issue #2171 although it does not solve it.
This is a slight improvement that address part of issue #2171 
Here is how it looks in the logs after this change:
Note: If a player controls several corporations these will not be grouped.
So it is
CHI (Player A), MEX (Player A), SPM (Player B)
'automatic' is shown on the last corporation, if it is non-floated. This is as this will be automatically merged, if all corporations before that decline.
The president of NdM appear on the non-floated corporations, except the last one. This is because the NdM president does choose if there are multiple non-floated corporations that are merge candidates. (In case there are non-IPOed corporations, any IPOed but non-floated cannot be …
=> Improve log message Fix/18 mex/merge candidates log

lib/engine/game/base.rb
Treat towns rendered near edge of tile like an edge for the purposes of detecting track re-use.
Specifically, this will detect the following illegal route using the Copper Canyon tile in 18MEX:
Fixes #2149 
This also fixes a latent bug in the check_overlap method in game/base where game_error was not being called correctly.
=> Detect illegal routes to towns not in center of tile

lib/engine/step/g_1817/track.rb
'When upgrading normal cities to brown, players must
use tiles with as many exits as will fit.'
fixes #2245
=> 1817: Enforce tile upgrade rule on brown

lib/engine/step/g_18_mex/track.rb
If minor corporation does not have enough cash to lay a yellow in
its home hex, the track lay is skipped.
In case home hex has a yellow/green tile then normal track laying
check is done. This might mean that minor gets to manually pass
as there are no allowed track lays it can afford.
But that last is an exceptional case.
Fixes #1944
=> 18MEX: Skip minor track lay if it cannot afford to lay in home hex

assets/app/view/game/bank.rb, assets/app/view/game/corporation.rb, assets/app/view/game/entities.rb, assets/app/view/game/stock_market.rb, lib/engine/game/g_1817.rb, spec/assets_spec.rb
Change stock market tab to use the card form (fixes #2192)
Add detail showing how loans go up and down (also #2192)
Add colour for acquisition and liquidation (fixes #2186)
Highlight red when corp cannot pay its loans (also #2186)
Add buying power for games where loans are present (also #2186)
=> 1817: Improve display of loan info, add buying power

lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1817/conversion.rb, lib/engine/step/g_1817/post_conversion.rb, lib/engine/step/g_1817/share_buying_with_shorts.rb, migrate_game.rb, spec/fixtures/1817/13707.json, spec/lib/engine/games/game_spec.rb
Bid should pay off loans before being distributed to shareholders (fixes #2228)
Disallow buying shares after loans are taken if players can now afford them (fixes #2227)
Disallow buying of shares in acquisition from MA (fixes #2226)
Don't skip corps incorrectly in Acquisitions (fixes #2225)
Restore spec
=> 1817: Acquire bugs

lib/engine/game/g_1860.rb, lib/engine/part/halt.rb, lib/engine/step/g_1860/buy_sell_par_shares.rb, lib/engine/step/g_1860/home_track.rb, lib/engine/step/g_1860/track.rb, lib/engine/step/g_1860/tracker.rb
- Home track tile lay when corp is floated if no tile on home hex
- Yellow tile placement rules (2x, unless one is a city)
- Upgrade rules (must be able to reach with a single train corporation owns)
- Constrained rotation for (some) N, M and R tiles
- Fixed Halt to allow upgrade to Town.
=> 1860 tile placement and upgrades

lib/engine/game/g_18_mex.rb
=> 18MEX: Fix crash for optional rule (fixes #2202)

assets/app/view/game/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb
Don't show buying power on unfloated corps (fixes #2255)
Show "2 shares to start" rather than %age (fixes #1834)
=> 1817 corp card fixes

assets/app/view/game/company.rb, lib/engine/abilities.rb, lib/engine/ability/README.md, lib/engine/ability/base.rb, lib/engine/config/game/g_1817.rb, lib/engine/game/g_1817.rb, lib/engine/step/g_1817/acquire.rb
Repay loan is off by one (fixes #2263)
Add count of coal mine and bridges (fixes #2204)
Correct order of bid msg if players autopass (fixes #2189)
=> 1817: UI fixes and improvements

lib/engine/share_pool.rb
Fixes #2276; I can't say whether everything about the bankruptcy or acquisition of the current corporation is handled correctly, but this at least keeps the game from crashing at that point.
=> fix rendering when bankruptcy caused by acquisition cash crisis in 1817

lib/engine/game/g_18_ms.rb
[Fixes #2183]
AAG rules, section 11.3:
A major company can do the following on its turn. ...
1. If this is the major company’s first operating turn of the game, place a
station token in its home city or off-board location, as indicated by the
company logo. (Required)
=> Fix 18MS home token timing

lib/engine/game/g_1817.rb
The owner of a corporation in the market was cleared between stock rounds.
This caused a problem when the corp went up for auction next round
Retain the owner permamently (fixes #2281)
=> 1817: Fix crash where corp entered liquidating in MA

assets/app/view/game/entity_list.rb, assets/app/view/game/entity_order.rb, assets/app/view/game/round/merger.rb, lib/engine/round/g_1817/acquisition.rb, lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/conversion.rb, lib/engine/step/g_18_mex/merge.rb
fixes #2147
Both are valid information to display
18MEX: Override entity order during merger (fixes #2171)
18MEX: Don't hide other player corps
=> 1817: Show two entity bars during acquisitions (corps and players)

assets/app/view/game/corporation.rb, assets/app/view/game/dividend.rb, assets/app/view/game/spreadsheet.rb, lib/engine/abilities.rb, lib/engine/game/g_1817.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1817/cash_crisis.rb, lib/engine/stock_market.rb
1817 Correct rounding so that 5 displays properly on interest (fixes #2300)
1817 Show 0/n when all token actions are used up (fixes #2298)
1817 Improve phrasing on valid bids error (fixes #2223)
1817 Add log message on cash crisis (fixes #2205)
1817 Include buying power in interest highlight (fixes #2254)
1817 Change interest warning to yellow
1817 Show liquidation/acquisition on dividend screen (fixes #2209)
18MS Remove 'undefined' from spreadsheet (fixes #2297)
=> 1817 minor fixes

lib/engine/game/g_18_mex.rb
This crashed for the rare case of having a corporation with
trains but no tracks in home location (and therefor no possible
income). So a brief case use case for SPM...
=> 18MEX: Fix crash for mail handling (fixes #2304)

assets/app/view/game/spreadsheet.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/minor.rb
General code but only affects 18MEX at the moment.
To enable code in other titles, override all_corporations
from game base class to include minors.
For example how the result looks, see #2286.
=> 18MEX: Show minors in spreadsheet (fixes #2286)

lib/engine/game/g_18_tn.rb
There was a bug if the triggering company's only train was the
one triggering the Civil War. In which case trains was still
empty when checking for Civil War token.
Have now included the trigger in the event even if it has no
other trains.
Also added a log line per corporation describing if it gets
Civil War token or not, to make it more visible.
=> 18TN: Civil War should affect triggering company (fixes #1873)

lib/engine/round/operating.rb, spec/fixtures/1846/hs_ymymwsiv_16134.json, spec/lib/engine/games/game_spec.rb
This problem was first encountered in game 16134; this commit also adds a
fixture game that is based on 16134, but includes the B&O route, and then is
ended early.
The B&O running its route and withholding drops its stock price, but when the
actual game was played, the bug skipped the B&O and didn't change its stock
price. With the route added in after the fact, the game breaks due to different
operating order.
-----
[Fixes #2315]
I used the db backup that was created earlier today to run a local validation, and 16134 was the only broken game, and it will need to be pinned.
=> Fix consecutively operating receivership corporations

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/sell_shares.rb
Previous commit introduced possibility to show non-standard
percentage in 18MEX, but it introduced problems in other
titles. So this commit improves the solution and solves
a couple of issues.
Disregard president shares for pool shares if there are other
shares that can be bought. This means it will not be possible
to buy president's share directly from the market unless it
is the last one. (And the title need to handle that case.)
Do not let Treasury or Short share presence affect GUI
presentation. Before this fix, the "Buy a 10% Market share"
appeared when Treasury share was present, instead of just
"Buy Market Share".
Also, do not use 10% as the standard share size. Instead use
the share_percent of the corporation in question. This solves
the problem of 20% appearing for 5 share …
=> Fix problems with Buy and Sell button changes

assets/app/view/game/spreadsheet.rb
Fixes a logic issue (Ruby apparently treats numeric zero as "True")
This caused a "Loans" column to show up, even if games didn't have a loan mechanic
Tested locally, seems to work as expected for '46 and '17
=> Don't show loans in spreadsheet view for games without loan mechanics

lib/engine/config/game/g_1856.rb, lib/engine/game/g_1856.rb
Change the colors of companies in 1856 so that they are both more distinct than before and more closely match the colors on the charters in the physical copy
=> 1856 look and feel tweaks

lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/bankrupt.rb
Only allow the first player be the active entity in bankrupcy (fixes #2353)
Handle action after bankrupcy being finishing acquisitions (fixes #2367)
=> 1817: More bankrupcy fixes

lib/engine/minor.rb
If trying to sort the player columns, the minors throw an exception.
So I have added dummy implementations of num_shares_of and share_percent
for minors so that they can be sorted as well. They will end up at
top or bottom when sorted on shares for a player.
Fixes #2368 and #2370
=> 18MEX: Fix sorting problem with minors in spreadsheet

assets/app/view/game/hex.rb, assets/app/view/game/map.rb, assets/app/view/game/map_controls.rb, assets/app/view/game/tile.rb
* use localStorage to persist the last show/hide click
* workaround location names overlapping with important info by making it easy to
hide (partially addresses #2113)
* default location names to the localStorage value iff there is a value there;
this preserves the current behavior for users (showing the names) until they
click on something to hide them, and keeps the tests passing which expect city
names to be there
* show the "starting" map by re-using `init_hexes`; it's not exactly the
starting map depending on how some starting tokens/ability icons are handled,
but should be close enough for those that want it (I don't see a GitHub issue
for this, but it's a request that's come up a few times in chat)
[Fixes #322]
=> Add Show/Hide buttons for location names, hex coordinates, and "starting" map

lib/engine/config/game/g_18_tn.rb, lib/engine/game/g_1889.rb, lib/engine/game/g_18_tn.rb, lib/engine/step/buy_company.rb, lib/engine/step/g_1889/special_track.rb, lib/engine/step/g_18_tn/buy_company.rb, lib/engine/step/g_18_tn/track.rb, spec/fixtures/18_tn/7818.json
Buy remembering all buys during a round, it is possible to do
a correct check for private buys during OR 1.
Reuse the company_seller round attribute, but change it to a
list instead of a nil/player attribute. This ment refactoring
its use in 1889 a bit. Renamed it to company_sellers to reflect
its changed use.
I do believe it can just contain one value in 1889 so the effect
should be the same.
=> 18TN: Fix "company buy during OR1" bug (fixes #1887)

lib/engine/config/game/g_18_mex.rb, lib/engine/step/g_18_mex/special_track.rb, spec/fixtures/18_mex/13315.json, spec/lib/engine/games/game_spec.rb
This is an official errata to 18MEX that was published in
May 2020; it has been an error in the rules for MANY years
although the components in some version has the correct
rule.
Have updated the description to KCMO to reflect this.
Also remove CC label to avoid it cluttering up the hex.
(Actually this was as intended in the implementation but
action.hex.tile.name were not the expected value...)
This removes some income to the owning corporation which might affect
some games. For e.g the fixture that was checked in for 18MEX.
The extra $20 that now disappear means that the forced
train purchase deduct $20 from one of the players which also
meant that TM is not sold out, meaning there is a shift in
operating order... And the final scores are adjusted, affecting
the final ranks...
So, I …
=> 18MEX: Close KCMO private when its ability is used

assets/app/view/game/round/auction.rb, lib/engine/game/base.rb, lib/engine/game/g_18_chesapeake.rb, lib/engine/step/auctioner.rb, lib/engine/step/waterfall_auction.rb
* raise error if a company purchase over-commits the player
* don't render any action if it would over-commit the player
* add new config constant and special case for 18Chesapeake, where only highest
bid counts as committed
[Fixes #2302]
=> waterfall auction: prevent over-committing

lib/engine/game/g_18_mex.rb, lib/engine/step/g_18_mex/waterfall_auction.rb
According to the rules any bought minors should run during the OR
(as all privates should give revenue in this situation) but it
would require quite an effort to do this.
So instead a compromise has been reached that almost give the same
effect - any bought/floated will give a $30 (50-50) payout, which
would have been the same as it would have payed out during its
first two ORs, probably.
Although not perfect, it will have more or less the same effect
as according to the rules, and will get players to avoid passing...
Also improved handling of minor floating, which is now connected
to the actual buy of connected company in ISR.
Wiki page will be updated as well.
=> 18MEX: Minors pays revenue when pre-pass during ISR (fixes #2331)

lib/engine/config/game/g_1817.rb, lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/cash_crisis.rb, lib/engine/step/g_1817/post_conversion.rb, migrate_game.rb, spec/fixtures/1817/13707.json, spec/fixtures/1817/15528.json
Allow sell of shares after merger if players cannot buy (fixes #2398)
Up train limits of 2 and 8 trains (fixes #2395)
Disable selling of corps in acquisition/liquidation in cash crisis (fixes #2392)
Don't show potential acquiring corps in take loans step (fixes #2391)
Needs a migration for #2398, and pinning one game cheating for #2392.
=> 1817 Fixes

assets/app/view/game/round/auction.rb, lib/engine/game/base.rb, lib/engine/game/g_18_chesapeake.rb, lib/engine/step/auctioner.rb, lib/engine/step/base.rb, lib/engine/step/waterfall_auction.rb
use the existing `max_bid` method instead of trying to write a new
`available_cash` method
[Fixes #2302]
=> Fix waterfall auction over-committing (again)

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/sell_shares.rb, lib/engine/action/buy_shares.rb, lib/engine/action/sell_shares.rb, lib/engine/g_18_chesapeake/share_pool.rb, lib/engine/g_18_tn/share_pool.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/share_pool.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/buy_train.rb, lib/engine/step/g_18_mex/buy_sell_par_shares.rb, lib/engine/step/g_18_mex/single_depot_train_buy.rb, lib/engine/step/g_18_mex/swap_buy_sell.rb, lib/engine/step/share_buying.rb
In 18MEX it is possible to swap a 5% share as part of a sell/buy.
If selling shares and there is a 5% share in the market, player
can choose to get the 5% as part of the deal, reducing the money
received for the sell. Note: Selling 30%, with a 5% swap, just
decreases stock market price as if 20% had been sold.
If buying shares and the player owns one 5% share, the player
can choose to use the 5% as a partial payment, reducing the
money needed by the value of the 5% share. This is counted
as a buy for all purposes.
Have introduced swap_sell and swap_share methods, which if
implemented will enable the swap buttons to appear in the GUI.
So far only 18MEX has these implemented.
Note! Swap button is Sell/Buy buttons, which do show info
about 5% share as part of deal.
A bunch of smaller bug …
=> 18MEX: Introduce swap functionality (fixes #1921)

lib/engine/game/g_18_co.rb
**_This change only affects 18CO_**
Recent changes removing Acquisition from the base game definition caused it to be missing from the Market. Additionally, the colors were backwards.
Additionally, add some helpful text to the market zone definitions, as implementing separate par zones as currently not supported.
=> [18CO] Fix missing market text and color definitions

lib/engine/game/g_18_co.rb
In 18CO, unlimited towns are paid but towns on route ends are counted against city limit. It is legal for a 2 train to run "C t t t t" for example, but not "t C t t t". Similarly, a 4 train can run "t C C t" or "C t C C t" but not "t C C C t".
=> [18CO] Towns on route ends are counted against city limit.

assets/app/view/game/game_info.rb, assets/app/view/game/round/stock.rb, lib/engine/config/game/g_1867.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1867.rb, lib/engine/game/interest_on_loans.rb, lib/engine/phase.rb, lib/engine/round/g_1867/stock.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1867/buy_sell_par_shares.rb, lib/engine/step/g_1867/dividend.rb
Allow 1867 corps to have different limits
Add events relating to corporations
Allow majors to be floated in the major only region
Limit when majors can be started
Implement 1867 stock price movement and OR order
Skip merger rounds before phase 3
=> 1867: More changes for corporation types

lib/engine/config/game/g_1889.rb, lib/engine/step/g_1828/special_track.rb, lib/engine/step/g_1828/track.rb, lib/engine/step/g_1889/special_track.rb, lib/engine/step/tile_lay_when_company_sold.rb, lib/engine/step/track_lay_when_company_sold.rb
- E&K has a mandatory track lay when sold
- E&K has another track lay ability that can be used to place an additional yellow tile (e.g. no upgrades)
=> 1828: Implement E&K private

assets/app/view/game/button/buy_share.rb, assets/app/view/game/buy_sell_shares.rb, lib/engine/config/game/g_18_co.rb
This started as a simple task to add the unusual "shares" distribution for DSNG. That was a one liner, but in the process I discovered that the view file did not respect different sizes of shares in the treasury, only the market. I found doing so following the current pattern would create a lot of duplicated code for creating the buttons as well determining percentages and text. This also gave me the chance to write a lot of the code using fail first methodology as well as map functions.
The changes will also reduce the complexity needed for creating the buy buttons in https://github.com/tobymao/18xx/pull/2431 as the same Button view file can be reused, passing a different action.
A change I've made is to always show shares in descending …
=> Refactor BuySellShares view and add [18CO] DSNG Share Distribution

lib/engine/game/g_18_mex.rb
If the game uses the optional rule of delayed close of minors
the minor close in the Stock Round following the OR set where
the 5th 3 train was bought.
But the bug was that it was attempted to do the delayed minor
close in the Stock Round after that. So the delayed minor close
just had to be reset.
=> 18MEX: Fix bug with delayed minor close (fixes #2457)

lib/engine/ability/README.md, lib/engine/ability/tile_lay.rb, lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_18_chesapeake.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/spender.rb, lib/engine/step/special_track.rb, lib/engine/step/track_lay_when_company_sold.rb, spec/assets_spec.rb, spec/fixtures/1846/12666.json
New lay_tile param called "must_lay_together". The special_track step will block, after the first tile lay, if must_lay_together is true.
*** May need current games to be pinned. Recommend testing against the production db to verify ***
=> Fix abilities with multiple track lays that need to be laid at the same time

lib/engine/game/base.rb, lib/engine/game/g_1828.rb
- Add function to clear cache of the specified type
- Use to clear share_prices cache when new par prices become unlocked.
=> 1828: Allow the game class's cache to be cleared

lib/engine/ability/README.md, lib/engine/ability/tile_discount.rb, lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/step/g_1860/tracker.rb, lib/engine/step/g_18_mex/track.rb, lib/engine/step/tracker.rb
If hexes field is specified for tile_discount ability, only
the specified hexes will give the discount.
=> Add possibility to restrict tile discount to specific hexes

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/corporation.rb, assets/app/view/game/exchange.rb, assets/app/view/game/spreadsheet.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1867.rb, lib/engine/game/g_18_co.rb, lib/engine/game/g_18_mex.rb, lib/engine/minor.rb, lib/engine/share_pool.rb, lib/engine/step/g_1860/buy_cert.rb, lib/engine/transfer.rb
18MEX: Correct bank -> @bank in game class
corporation.rb: Make capitilization modifiable. This is for 1856
(and 18SJ) so that they can change capitilization for corporation
due to phase change.
corporation.rb, minor.rb: Extract the transfer part to a module
that can be shared. Today only corporations can transfer things
(because of merge) but there are titles that have minors that
can own things  which can be merged, so this is a preparation for that.
=> Minor fixes/refactoring

lib/engine/game/g_18_mex.rb
If KCM&O uses its ability, the private is closed, and it loses
its owner attribute. Need to add a nil guard to avoid crash.
=> 18MEX: Fix problem with KCM&O private (fixes #2480)

assets/app/view/game/game_info.rb
When having a specific optional rule in 18MEX the minors' trains
become (sort-of) non-rustable. For some reason this affects the
two train info for rusting.
By using @depot.upcoming instead the problem does not appear.
=> Use upcoming trains in Info (fixes #2508)

lib/engine/config/game/g_1817_wo.rb, lib/engine/game/g_1817_wo.rb
Marc Voyer sent me the 18xx-maker JSON for 1817WO so I put together the base for it as a pre-alpha title. 
The rule for Nieuw Zeeland is not implemented here and would need to be implemented before it can be taken alpha.
=> Add 1817WO; Nieuw Zeeland rule is not implemented

lib/engine/game/g_1817.rb, lib/engine/round/g_1817/stock.rb, lib/engine/round/g_1867/operating.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1817/cash_crisis.rb, lib/engine/step/g_1817/special_track.rb, lib/engine/step/g_1817/track.rb
1817: Remove corporations that have no benefit (fixes #2459)
1817: Only make the first cash crisis player the active player (fixes #2388)
(Also add 1867 operating that i forgot to add)
=> 1817: Remove corporations that have no benefit

assets/app/view/game/part/city.rb, assets/app/view/game/part/city_slot.rb
I think this only affects Pile o' Bones in 1882, but looks nicer
=> Use city as centre for TokenSelector, instead of the centre of the tile

assets/app/view/game/game_info.rb
This fix caused problems in other titles. So we need to
try another solution.
This reverts commit 27b88f52f7d1d9714815b389934f32ae743c4b1a.
=> Revert "Use upcoming trains in Info" (fixes #2513)

api.rb, assets/app/app.rb, assets/app/view/market_page.rb
I found it useful to have a view directly into the stock market while building 18CO. This allows a user to view the market for a specific game without bring in the game. (eg: /market/18AL )
http://0.0.0.0:9292/market/1846
http://0.0.0.0:9292/market/18CO
=> Stock Market View Page

lib/engine/game/g_1856.rb
Add 1856's dynamic certificate limit; the certificate limit is static until nationalization but after nationalization it changes whenever corporations close.
I put in some stubs to implement later once Nationalization is implemented
=> 1856 Dynamic Certificate Limit

lib/engine/game/g_1817_na.rb
Before this fix, the # of loans to raise interest rate was correct except
for when the # of loans was a multiple of 4, in which case it showed
5 loans to increase interest, instead of the correct 1
=> 1817NA: Fix bank text for # of loans to raise interest rate

lib/engine/game/base.rb, lib/engine/game/g_18_mex.rb, lib/engine/phase.rb
Have added a rust? method in base class that 18MEX overrides
and use it to skip rusting of minor's two train in case the
optional rule is used.
=> 18MEX: Fix info when using optional rule (fixes #2508)

lib/engine/ability/README.md, lib/engine/ability/token.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/step/g_18_ga/token.rb, lib/engine/step/g_18_ms/token.rb, lib/engine/step/tokener.rb
Add `special_only` attribute to token abilities; if `true`, prevents Tokener
from using the ability implicitly.
[Fixes #2512]
=> Bug fix: make abilities of 18LA optional companies only activate if explicitly chosen

assets/app/view/game/corporate_buy_shares.rb, assets/app/view/game/corporation.rb, assets/app/view/game/round/operating.rb, lib/engine/action/corporate_buy_shares.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_18_co.rb, lib/engine/share_pool.rb, lib/engine/step/corporate_buy_shares.rb
18CO allows corporations to buy shares from two possible places:
- The market
- The corporation's president
Once a purchase of a corporation is made, only purchases of that specific corporation can be made in that round, though from either source.
I chose to implement this as a generic ( non-18CO ) specific class as I believe there will be other games that allow cross-corp share purchasing.
A new action had to be created to allow the correct actions / display to work, though it implements no specific code of its own.
The displays have a decent amount of repeated code which I am not a fan of, but the code was also just different enough to seem difficult to refactor.
Flag: **CORPORATE_BUY_SHARE_SINGLE_CORP_ONLY** - Without this flag, a …
=> [18CO] Corporate Buy Shares

lib/engine/step/auctioner.rb
Dutch Auctions allow for reducing bids. In the view, the Auction is checked for if a bid can be reduced, but this check is missing for other auction types.
=> Fix: Missing Base May_Reduce

lib/engine/game/g_18_co.rb
We recompute to Mine Ability information when the IMC is purchased. However, If a corporation purchased the IMC before it collected any mines, the Mine Ability was added showing a $0 payout. Better to not add the ability until it actually has mines.
=> Fix 18CO IMC Ability and Mine Display

lib/engine/share_pool.rb
In case player bought share from IPO, and paid with a 5% NdM,
then the swap is between player and Market. So the percentage
transfers need to be handled separately.
=> 18MEX: Fix swap bug (fixes #2553)

assets/app/lib/hex.rb, assets/app/view/game/hex.rb, assets/app/view/game/part/borders.rb, assets/app/view/game/tile.rb, lib/engine/config/game/g_1817_na.rb, lib/engine/config/game/g_1828.rb, lib/engine/config/game/g_1867.rb, lib/engine/config/game/g_1882.rb, lib/engine/config/game/g_18_mex.rb, lib/engine/config/game/g_18_ms.rb
When a hex/tile has a border with no defined type, don't render a border element on top of it; instead, remove the "stroke" from the hex `<polygon>` and draw a partial outline with `<path>` elements. Drastically improves rendering of 18MEX's Mexico City double-tile, and somewhat improves rendering of paired offboards when opacity is low.
It's not perfect, there seems to still be either a slight seam or overlap that is visible, depending on the orientation of the two tiles being rendered. For instance, see the two different offboard pairs in the 1846 "after" screenshot; the lower one has a visible line that isn't present on the higher one
=> Enhancement: "Nil" border rendering

lib/engine/config/game/g_1867.rb
The third Montreal city gets placed in the center, will take some more effort to get that placed next to edge 5, but the track is connecting the correct cities at least.
I haven't read the 1867 rules, is it green on the board because it cannot be tokened before a green phase? Nobody can get connected to it until a green M tile is placed, so I was wondering if we could just leave that city off for now, but if there's some teleport-style token ability that would enable a token placement there that option is a no-go.
/cc @jenf
=> fix starting tile definitions for 1867's Toronto and Montreal hexes

assets/app/view/game/buy_trains.rb, lib/engine/game/base.rb, lib/engine/game/g_18_co.rb
Trains in the Market ( from discards ) are purchased at 50% face value.
Normal price of the 3 was 180. With discount its 90.
Since the final price is calculated in the view itself, I couldn't figure out a good way to make this 18CO specific. The calculation seemed straightforward enough to roll into the base, though.
=> 18CO Add Discarded Train Discount

lib/engine/game/company_price_up_to_face.rb, lib/engine/game/g_1846.rb
Similar to the [module to set private prices to between 0.5 face to 1.5x face](https://github.com/benjaminxscott/18xx/blob/master/lib/engine/game/company_price_50_to_150_percent.rb), also generalize a module that allows games to set legal private prices to between 1 to face value (such as 1848)
Updated the 1846 game engine, which also covers 18LA
=> Generalize private company prices that are up to face value

assets/app/view/game/corporation.rb, assets/app/view/game/route_selector.rb, lib/engine/game/base.rb, lib/engine/game/g_1860.rb, lib/engine/round/g_1860/operating.rb, lib/engine/route.rb, lib/engine/step/g_1860/buy_train.rb, lib/engine/step/g_1860/dividend.rb, lib/engine/step/g_1860/route.rb, lib/engine/step/g_1860/token.rb, lib/engine/step/g_1860/tracker.rb
Implements all the insolvency rules
Implements train buy restrictions
- Added ability for show status line for corporations (Game/Base, UI:Corporation)
- Game-specific train owner (Game/Base, Engine/Route)
- Game-specific trains list (Game/Base, UI:Route_Selector)
=> 1860 Insolvency and train buying rules

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/special_track.rb, lib/engine/step/g_18_co/track.rb, lib/engine/step/g_18_co/tracker.rb
**GJGR**: An owning Corporation may upgrade a yellow town to a green city in additional to its normal tile lay. Action closes the company or closes on purchase of “5” train.
**LNPW**: An owning Corporation may lay an extra tile at no cost in addition to its normal tile lay. Action closes the company or closes on purchase of “5” train.
I moved some shared code between the Normal Track Step and Special Track Step into a shared Tracker module.
I don't love having to modify the tiles in the json. However, I can't see a way to fake it at runtime. The explicit code in upgrades_to? allows it to work, though. No need to detect if the hex has a town since the ability definition restricts the upgrade to town hexes.
GJGR only activates on towns, and only shows green cities on yellow towns
LNPW can …
=> 18CO Special Tile Lays

assets/app/view/game/abilities.rb, assets/app/view/game/round/auction.rb, lib/engine/action/move_bid.rb, lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/moving_bid_auction.rb
18CO does not use a waterfall style auction. All privates are available for bids starting at face value.
A bid on a Private Company may be moved to a different Private Company as long as the bid value is increased by 5, in increments of 5. A player may have multiple bids on the same Private Company (via moving a bid between privates), but when "Place Bid" happens on a company with multiple bids already, it always adds to the player's highest bid. All bids are considered committed cash.
The auction ends when all players pass consecutively.
The `&& company.owner` addition fixes the problem of private abilities showing during the SR and will probably fix https://github.com/tobymao/18xx/issues/2122 as you shouldn't be able to activate an …
=> 18CO Moving Bid Auction

lib/engine/step/g_18_co/track.rb
I changed the function signature and forgot to update. Stupid. At least we're not live.
=> 18CO Fix Normal Track Lay

lib/engine/config/game/g_1882.rb, lib/engine/game/g_1882.rb, public/icons/1882/fish.svg
* Rename "Pile o' Bones & Lumsden" to "Regina" in brown; AAG's R tiles don't
have city names, but this matches prototype copies of the game that kept city
names on the tiles - https://boardgamegeek.com/image/5069960/1882-assiniboia
* Add fish icon from 18xx-maker for the fishing exit on B6
=> Enhancement, 1882: fish icon and "Regina"

assets/app/view/game/buy_trains.rb, lib/engine/depot.rb, lib/engine/step/train.rb
Now variants is added to discountable trains, if the base version
has a discount for the a train. The discount will be the same for
the variants as for the base version.
=> Variants should also be considered for discount (fixes #2492)

lib/engine/config/game/g_1828.rb, lib/engine/game/base.rb, lib/engine/game/g_1828.rb, lib/engine/route.rb, lib/engine/step/g_1828/buy_company.rb, lib/engine/step/g_1828/route.rb, lib/engine/step/g_1828/special_token.rb, lib/engine/step/g_1828/token.rb, lib/engine/step/g_1828/token_tracker.rb, lib/engine/step/g_1828/track.rb, public/logos/1828/blocking.svg, spec/lib/engine/games/g_1828_spec.rb
Implemented the following abilities for C&P:
- Pays $15 in revenue until the end of the auction
- Train doesn't rust
- Must run the tile it laid
- Run does not need to include its station
- Does not run if no tile laid
- Buying company has the option to replace C&P home token with one of its tokens for free, provided it has a token and has not laid a token this round.
- If the buying company cannot or does not replace the C&P token, a blocking token is placed instead
Cleaned-up the blocking token logic.
=> 1828: Implement C&P company

assets/app/view/game/spreadsheet.rb
This reverts commit f995a3df989439483f3fb43389f821af6a5105e8.
This was a bad idea. It is annoying during a game of 1817 to have an unnecessary column full of zeroes, but in games that end in bankruptcy it makes no sense to hide this column.
Since 883dddc407af50689a88f2ce5666daf5bf8b19bf, this column always contains information. Even in games that don't end with a bankruptcy. So I don't think this makes sense anymore in either type of game.
=> Revert "Hide bankrupt players from spreadsheet"

lib/engine/game/g_1846.rb, lib/engine/step/g_1846/buy_train.rb, lib/engine/step/g_1846/track_and_token.rb, spec/assets_spec.rb, spec/fixtures/1846/11181.json, spec/fixtures/1846/3099.json
* because the minors come with a train, the entity's current trains must be
taken into account
* when considering train buying power for an entity, if they have 0
trains (i.e., if they must buy a train), the minor's potential cash should
*not* be considered, as this prevents the president from contributing cash for
EMR
[Fixes #2566]
-----
The migration is very straightforward, just inserting pass actions when necessary. I ran it locally for all "active" games and then all "finished" games; active took around 4 minutes while finished took around 40, so when released I'll do the same.
=> Bug fix, 1846: add potential cash from minor to entity's buying power

lib/engine/ability/README.md, lib/engine/ability/return_token.rb, lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb, lib/engine/step/return_token.rb
Denver,​ ​Northwestern and​ ​Pacific​ ​Railroad
New Ability: An owning Corporation may return a station token to its charter to regain the token cost. The token is always placed on the most expensive open token slot and reimburses that cost. Corporation must always have at least one token on the board.
DPAC used DNPR to remove the token in Denver. The token was returned, $40 reimbursed and the reservation in Denver removed.
=> 18CO Return Token Ability

lib/engine/game/g_1817_wo.rb, lib/engine/round/g_1817_wo/operating.rb, lib/engine/step/g_1817_wo/buy_sell_par_shares.rb
This resolves 4 of the rules in https://github.com/tobymao/18xx/issues/2592
Namely: 
* A corporation with a token in Nieuw Zeeland gets $20 at the end of the OR if it has no loans
* A corporation with a token in Nieuw Zeeland gets to ignore one loan's worth of interest if it has loans
* Nieuw Zeeland cannot be chosen for IPO before Phase 3
* Nieuw Zeeland cannot be started as a 2 share corporation
=> 1817wo nieuwzeeland

assets/app/view/game/buy_company_from_other_player.rb, lib/engine/game/g_18_co.rb, lib/engine/step/buy_company.rb, lib/engine/step/g_18_co/buy_sell_par_shares.rb, lib/engine/step/g_18_co/moving_bid_auction.rb
A​ ​Private​ ​Company​ ​in​ ​the​ ​Market​ ​is​ ​purchased​ ​at​ ​50%​ ​of​ ​the​ ​Private​ ​Company’s​ ​face​ ​value.
Private companies wind up in the market if they are not purchased during auction. They can only be bought by corporations, not players.
Changes to the generic **buy_company.rb**
- Don't run the companies.delete call if the owner is nil, because it will throw an error
- Pay to bank if owner is nil ( the market )
- Add text to show "the market" if owner is nil
Changes to the generic **buy_company.rb** were not strictly necessary for 18CO as a player cannot buy from market but rather done for consistency and to prevent errors if a game allowed it in the future.
- Add text to show "the market" if owner is nil
Corporations can …
=> 18CO Corporations can buy Un-auctioned Companies

lib/engine/config/game/g_1867.rb, lib/engine/game/g_1867.rb, lib/engine/step/g_1867/single_item_auction.rb, lib/engine/step/g_1867/track.rb, public/logos/1867/CN.svg, public/logos/1867/neutral.svg
Lock tiles with green neutral tokens until phase 3
Lock tile with a fake '3' company
Add the canadian token at the start of the game
(The Canada logo is just until we get the final logos)
O upgrades via Y until grey
G15, K13, L10 must connect to the major city on it's first upgrade
Improve text for privates
Route bonuses for privates and for Timmins
=> 1867: Phase 3 events

assets/app/view/game/corporation.rb, assets/app/view/game/token.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1860.rb, lib/engine/round/stock.rb, lib/engine/step/g_1860/buy_train.rb, lib/engine/step/g_1860/route.rb, lib/engine/token.rb
Last of the big corporate status implementations: Corporate Bankruptcy
Unlike closing a corporation, a bankrupt corporation keeps it's assets and can be re-parred with a wider range of prices than before it was bankrupt. Any outstanding stock shares are moved from players/pool back to IPO. A new priority deal is assigned and if the bankruptcy occurs in the middle of a stock round, the stock round is restarted. It also implements the concept of "flipped" tokens for bankrupted corps that block track laying and tokening, but not running trains:
- UI: Corporation: handle showing assets for bankrupt corps, shrink font for really long train strings (1860 is bad in this regard)
- UI: Token: render flipped tokens
- Engine::Token: new status instance var
- Engine::Corporation: …
=> 1860 Corporate Bankruptcy

assets/app/view/game/part/city_slot.rb, lib/engine/game/g_18_co.rb, lib/engine/operator.rb, lib/engine/step/g_18_co/takeover.rb
If,​ ​at​ ​any​ ​time,​ ​a​ ​Corporation​ ​owns​ ​the​ ​President’s​ ​Certificate​ ​of​ ​another​ ​Corporation,​ ​the​ ​owning​ ​Corporation​ ​must​ ​take​ ​over​ ​the owned​ ​Corporation​ ​as​ ​follows:
TBD
Most of the Takeover is automated. The only player choice is which of up to 2 tokens to swap to the new corporation.
Showing the DPAC Denver redundant token was removed, and the remaining DPAC token hex is highlighted.
The DPAC token was replaced with a DSNG token. Since no further DPAC tokens remained on the board, the Takeover step ended.
DSNG has 5 trains, legal with the +1 ability from the takeover. The ability is also shown on the card.
=> 18CO Takeovers

assets/app/view/game/corporate_sell_shares.rb, assets/app/view/game/round/operating.rb, assets/app/view/game/sell_shares.rb, lib/engine/action/corporate_sell_shares.rb, lib/engine/game/g_18_co.rb, lib/engine/share_pool.rb, lib/engine/step/corporate_buy_shares.rb, lib/engine/step/corporate_sell_shares.rb
Shares (of other corporations)​ ​owned​ ​by​ ​a​ ​Corporation​ ​can​ ​be​ ​sold​ ​if​ ​the​ ​operating​ ​Corporation​ ​did​ ​not​ ​purchase​ ​any​ ​shares​ ​in​ ​the​ ​target Corporation​ ​earlier in​ ​the​ ​same​ ​operating round.
Changes to _operating.rb_ were required to add the new view
Changes to _sell_shares.rb_ allow for the corporate sell action which is necessary to allow for the corporate view.
Changes to _share_pool.rb_ correct the assumption that if a corporation is selling shares, its an issue. That's only true if the corporation is the same as the bundle.
Changes to _corporate_buy_shares.rb_ allow for distinguishing between which corporation bought which other corporations
Here we see DPAC owns both CM and KPAC. DPAC can sell …
=> 18CO Corporate Share Sales

lib/engine/round/operating.rb
Closed corporation has no share price. So need to be ignored during
recalculation of order.
=> 18MEX: Closed corporation caused exception (fixes #2623)

lib/engine/step/buy_company.rb
There was a missing space in the output logline
=> fix typo when buying privates

lib/engine/step/buy_sell_par_shares.rb
Fix https://github.com/tobymao/18xx/issues/2477
Using the word decline instead of pass more clearly indicates that an action was still taken that will affect priority deal rather than passing your action.
=> Issue 2477 Clarify Passing your action vs Ending your action

lib/engine/step/dividend.rb
From https://github.com/tobymao/18xx/issues/2609
Seems fairly self-explanatory. Corporate shareholders should be paid dividends. Before this change, the code only looks at players.
Here we see CM was paid $3 after the change.
=> Fix Corporate Shares not paying dividends

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb
From: https://github.com/tobymao/18xx/issues/2609
When the Experimental train is purchased, corporations can only lay one tile per turn for the remainder of the game.
Remove the "Companies can buy from other players" as that is not in the RAW.
=> 18CO Phase 7 - Reduced Tile Lay, Remove buying companies from other players

assets/app/view/game/buy_trains.rb, lib/engine/game/g_18_co.rb, lib/engine/step/emergency_money.rb, lib/engine/step/g_1846/buy_train.rb, lib/engine/step/g_18_co/buy_train.rb, lib/engine/step/train.rb
From https://github.com/tobymao/18xx/issues/2609
Each commit is specific to a change.
**Refactor Emergency Selling Minimum Shares**
This is a readability refactor
**EMR Refactor Presidency Swap Check …**
Change player to seller, as if it is a share issue, the bundle owner will be the corporation, not a player. No need to check if Presidency changes since issuing shares to the market cannot trigger a presidency change.
**Fix train available_cash double counting …**
If the corp is issuing shares, this prevents double counting the corporation cash, which would prevent the corporation from ever being able to buy a train if there are issuable shares.
**Fix train can_sell? preventing issuing …**
An issue share is a share sale by the current entity (the corporation) and should not be prevented …
=> Fix base Emergency Buy + Issue Shares, add 18CO Implementation

assets/app/view/game/choose.rb, assets/app/view/game/round/merger.rb, assets/app/view/game/round/operating.rb, lib/engine/config/game/g_1867.rb, lib/engine/corporation.rb, lib/engine/game/g_1867.rb, lib/engine/round/g_1867/operating.rb, lib/engine/step/g_1867/buy_sell_par_shares.rb, lib/engine/step/g_1867/buy_train.rb, lib/engine/step/g_1867/dividend.rb, lib/engine/step/g_1867/major_trainless.rb
Add support for 1867 trains (towns can count optionally)
Add support for 1867 Majors only being able to start in non-connected cities
Add support for 1867 rust events causing minors to nationalize and majors to optionally nationalize
Fix some minor bugs
=> 1867 Trains:

lib/engine/step/g_18_co/tracker.rb
A plain track tile with a junction cannot be placed unless the corporation can already trace a route to the path that contains the new junction. When multiple new paths are present, only one new path's junctions must be reachable.
This one is a bit of a doozy. I think it will be easiest to represent in pictures. There may be optimizations to this code. It was hard enough for me to put the rule into words.
`return if new_tile.color == :green && new_tile.exits.size == 4 # no new junctions, cheap short circuit`
All the green tiles with 4 exits have paths that don't connect. The only reason you couldn't place these would be handled by the default track restriction of "Must use new track"
Here we can see CM was able to place one of these tiles …
=> 18CO Restrictive Track Lay

lib/engine/game/base.rb
This adds a flag to define whether private companies count against cert limit (this is used by 1880, 1848)
Is a no-op for current games / engines
=> add a flag for whether privates count against cert limit

assets/app/view/game/player.rb, assets/app/view/game/spreadsheet.rb, lib/engine/config/game/g_1860.rb, lib/engine/g_1860/bank.rb, lib/engine/game/base.rb, lib/engine/game/g_1860.rb, lib/engine/player_info.rb, lib/engine/round/g_1860/operating.rb, lib/engine/step/g_1860/buy_sell_par_shares.rb, lib/engine/step/g_1860/buy_train.rb, lib/engine/step/g_1860/dividend.rb, lib/engine/step/g_1860/token.rb, lib/engine/step/g_1860/track.rb
Last set of changes to make 1860 feature complete:
Game now ends on
- Bank breaking
- Corp reaching rightmost stock price
- Nationalization
Implements 8+4 event
Implements 9+5 event - triggering Southern formation
Implements Nationalization
Moves player value calculation into Game::base
- UI::Player - now calls @game.player_value(player)
- UI::Spreadsheet - now calls @game.player_value(player)
- Game::Base - implements player_value(player), modified call to PlayerInfo
- Engine::PlayerInfo - takes player value directly from calling parameters
Fixes #2451
=> 1860 endgame - feature complete for 1860

lib/engine/game/base.rb
When laying a yellow OO tile, the code was incorrectly allowing single-city tiles as an option
So far 1848 is the only case that doesn't have pre-printed yellow tiles, but this covers other games with similar "lay a yellow OO tile" cases (e.g. 18CZ)
=> fix bug when building yellow OO tile

lib/engine/round/g_1817/stock.rb, lib/engine/step/g_1817/acquire.rb, lib/engine/step/g_1817/reduce_tokens.rb, migrate_game.rb
Sold out should disregard shorts (fixes #2606, but mass pinnning needed)
Bankrupt player shouldn't take part in acquisitions (fixes #2605, migrateable)
=> 1817 Bugs:

lib/engine/config/game/g_1860.rb, lib/engine/game/g_1860.rb, lib/engine/step/g_1860/buy_cert.rb
Tweaks to halt interface during Nationalization
Increase number of 9+5 trains to maximum possible
Simplify "stops" value during leasing
Validate bidding amount
=> 1860 UI tweaks, increase 9+5 count

assets/app/view/game/buy_sell_shares.rb, lib/engine/config/game/g_18_co.rb, lib/engine/corporation.rb, lib/engine/game/g_18_co.rb, lib/engine/round/g_18_co/presidents_choice.rb, lib/engine/share_pool.rb, lib/engine/step/g_18_co/buy_sell_par_shares.rb, lib/engine/step/g_18_co/presidents_choice.rb
**President's Choice Round**
This​ ​special​ ​stock​ ​round​ ​will​ ​occur​ ​once​ ​before​ ​the​ ​Stock​ ​Round​ ​following​ ​the​ ​first​ ​purchase​ ​of​ ​a​ ​5D​ ​or​ ​E​ ​train. Starting​ ​with​ ​the​ ​Priority​ ​Deal​ ​and​ ​moving​ ​clockwise,​ ​each​ ​player​ ​may​ ​purchase​ ​one​ ​Certificate​ ​from​ ​the​ ​Treasury​ ​of​ ​a Corporation​ ​for​ ​which​ ​they​ ​are​ ​President. Once​ ​a​ ​player​ ​passes,​ ​they​ ​may​ ​no​ ​longer​ ​purchase​ ​Certificates​ ​during​ ​this​ ​special​ ​stock​ ​round. Once​ ​all​ ​players​ ​pass,​ ​proceed​ ​to​ ​the​ ​normal​ ​Stock​ ​Round.​ ​All​ ​Certificates​ ​in​ ​the​ ​Treasuries​ ​of​ ​Corporations​ ​are​ ​now available​ ​for​ ​all​ ​players​ ​to​ ​purchase​ ​for​ ​the​ ​remainder​ ​of​ ​the​ …
=> 18CO President's Choice Round

lib/engine/step/emergency_money.rb, lib/engine/step/train.rb, spec/fixtures/18_ms/17510.json
See original https://github.com/tobymao/18xx/pull/2634 for a complete list of refactor/change explanations.
I've pulled out just the fixes/refactor to this PR, saving game specific changes and view improvements for later.
The problem with my first PR was emergency_money > can_sell? finished with an "unless" statement, thus the passing case returned nil instead of true. I've refactored that function this time so as to not have a trailing true. This only affected 18MS as that's the only game with @game.class::EBUY_SELL_MORE_THAN_NEEDED, so I have included a new fixture that addresses that path.
Relevant to https://github.com/tobymao/18xx/issues/2609
=> Fix/Refactor Emergency Money + Issuable Shares

lib/engine/step/g_18_tn/buy_company.rb
Fortunately it appears no one bought 2 companies in the games in the database, so no pins needed.
From the rulebook, section 4.2.6, page 8:
During the first operating round of the game only, each major company may purchase a single private company from a player for exactly the face value of the private company (maximum of one private company total per player on the first operating round). Any major company that chooses not to use this option at this time must wait until phase 3 to purchase private companies from players.
=> Bug Fix - 18TN: prevent corporations from buying multiple companies in OR1

lib/engine/share_price.rb
Fixes 2680
https://github.com/tobymao/18xx/issues/2680
Before
After
=> Repar values are not highlighted in 1860

assets/app/view/game/buy_trains.rb
The text "DPAC can issue shares to raise..." was showing regardless of whether there were shares to issue.
After the change the paragraph no longer renders since it is irrelevant
Note: I think the underlying code could be refactored to be better by rolling into a single step-based emergency_issuable_cash function, but I'd prefer to tackle that refactor in the future.
=> EBuy - Don't show issue message if no shares to issue ( one liner )

lib/engine/game/g_1860.rb, lib/engine/round/g_1860/operating.rb, lib/engine/step/g_1860/route.rb
Throw error when submitting an empty route when corp has train and a valid route
Fix bug with Nationalization not treating withheld runs as zero revenue
This will cause at least one completed game to fail. There is only a very small window where a running game would be impacted.
Fixes #2697 
Fixes #2696
=> 1860: Fix errors on empty routes, nationalization

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb, lib/engine/part/city.rb, lib/engine/step/g_18_co/home_token.rb, lib/engine/step/g_18_co/special_track.rb, lib/engine/step/g_18_co/track.rb, lib/engine/step/g_18_co/tracker.rb, lib/engine/tile.rb
From phase 5 onward, cities are no longer reserved.
If a corporation can never place its home token, it is removed from the game.
Once a corporation is parred, its reservation is returned to the hex.
A hex might be a single city, but the corporation may upgrade it to place its home token.
**Implementation Notes**
Tile label for Colorado Springs changed from **CS** to **C** to avoid confusion over the Corporation CS if it needs re-reservation.
I feel like once again I have a side effect inside a ? function, similar to the takeover. I don't know how to avoid that and still get the nice automation this provides. Its the same kind of reason: its the Home Token placement step, and if it can find a suitable automatic placement (in this case when …
=> 18CO Remove City Reservations, Close Corp w/o Homes, Re-reserve Newly Parred Corps

assets/app/view/game/round/merger.rb, lib/engine/game/g_18_co.rb, lib/engine/round/g_18_co/acquisition.rb, lib/engine/step/g_18_co/acquisition_auction.rb, lib/engine/step/g_18_co/acquisition_takeover.rb, lib/engine/step/g_18_co/takeover.rb
The **Final Feature** From: https://github.com/tobymao/18xx/issues/1836
At​ ​the​ ​beginning​ ​of​ ​every​ ​Stock​ ​Round​ ​starting​ ​with​ ​the​ ​second​ ​Stock​ ​Round,​ ​do the following with​ ​all​ ​Corporations​ ​with​ ​Stock​ ​Tokens​ ​in​ ​the​ ​red zone​ ​near​ ​the​ ​bottom​ ​of​ ​the​ ​Stock​ ​Market​ ​in​ ​Operating​ ​order.
- In​ ​Operating​ ​order,​ ​each​ ​Corporation​ ​that​ ​is​ ​not​ ​up​ ​for​ ​acquisition​ ​and​ ​does​ ​not​ ​have​ ​the​ ​same​ ​President​ ​as​ ​the Corporation​ ​currently​ ​being​ ​liquidated​ ​may​ ​either​ ​place​ ​a​ ​single​ ​bid​ ​of​ ​at​ ​least​ ​$1​ ​or​ ​pass.
- The​ ​Corporation​ ​with​ ​the​ ​highest​ ​bid​ ​wins​ ​the​ ​auction,​ ​and​ ​pays​ ​their​ ​bid​ ​money​ ​from​ ​their​ ​Treasury​ ​to​ ​the​ ​Bank.
- The​ ​winning​ ​Corporation​ …
=> 18CO Acquisition Round

lib/engine/step/g_18_co/takeover.rb
There is no rule in 18CO that a train transferred during a takeover cannot run again. It would be very unusual and probably not in a player's interest to takeover a higher value corporation.
=> 18CO - Transferred trains should reset

lib/engine/game/g_1860.rb, lib/engine/step/g_1860/buy_sell_par_shares.rb, lib/engine/step/g_1860/exchange.rb, lib/engine/step/g_1860/home_track.rb
Fixes #2709 
Fixes #2712 
Fixes #2718 
This also fixes an issue I thought of: home token and home tile lays are no longer allowed after the SR after the Southern forms. This may cause a problem when it happens, but it should be extremely rare and given how hard it is to construct a case where it happens, I'm just going to cross that bridge when someone tries to cross it.
=> 1860 home tile placement and priority deal fixes

assets/app/view/game/corporate_buy_shares.rb, lib/engine/step/corporate_buy_shares.rb, lib/engine/step/corporate_sell_shares.rb
Update Corp Share Buy to use Function - This was changed during dev but never updated.
---
Corporate Share Sales - Fix Duplicate corps if multiple owned shares.
Before:
---
If the President Share was the same percentage as the next share ( ie both 20% ) the President would be first and render an Undefined.
Before:
After:
=> Corporate Share Fixes

assets/app/view/game/issue_shares.rb, spec/assets_spec.rb
Fixes https://github.com/tobymao/18xx/issues/1813
Before
After
After (normal issue)
=> Display Emergency Issue instead of Issue when emergency issuing shares

lib/engine/ability/README.md, lib/engine/ability/tile_discount.rb, lib/engine/config/game/g_18_co.rb, lib/engine/game/base.rb, lib/engine/step/tracker.rb
**Saguache​ ​&​ ​San​ ​Juan Toll​ ​Road​ ​Company**
An​ ​owning​ ​Corporation​ ​receives​ ​a​ ​$20​ ​discount​ ​on​ ​the​ ​cost​ ​of​ ​tile​ ​lays.​ ​Closes​ ​on purchase​ ​of​ ​"5"​ ​train.
https://18xxgames.slack.com/archives/C012K0CNY5C/p1608399860033700
---
Base - add overall discount when terrain nil
tile_discount - set default terrain nil
Tracker - require terrain for ability to apply to a border
Update Readme
18CO config - remove terrain
=> Allow for generic tile cost discount and use in 18CO

lib/engine/step/g_1860/home_track.rb, lib/engine/step/g_1860/tracker.rb
Now uses a version of Tracker::upgradeable_tiles that has fewer side-effects when called repeatedly
Fixes #2734
=> 1860 Fix for #2734

assets/app/view/game/spreadsheet.rb
Adds a button to the bottom of the spreadsheet that toggles a difference mode of the player value history table.
=> Add delta value mode for player history

lib/engine/game/g_18_co.rb
Corp closing worked fine on red tiles but not in places like Denver as the check is based on the tile being laid, not the hex it is laid in. Not sure how this made it through final checks before.
Tweaking the variable/function names to be more accurate.
---
After
=> 18CO - Fix detection of city having max stations

lib/engine/game/g_1860.rb
Previously the rules link was to BGG, which requires login to view the PDF
This is on my personal dropbox as a shared file, can change to something else if we want
=> [1860] add direct link to rules pdf

public/logos/1856/GT.svg, public/logos/1856/GW.svg, public/logos/1856/TGB.svg
GT, GW, TGB logos were black text on color background when the text should've been white. This is fixed and now matches the corporation charter colors
Before:
After
=> Fix text color for GW, GT, TGB icons in 1856

assets/app/view/game/route_selector.rb, lib/engine/game/g_18_al.rb, lib/engine/route.rb, lib/engine/step/g_18_al/buy_company.rb, lib/engine/step/g_18_al/buy_sell_par_shares.rb, lib/engine/step/route.rb
Fixes: https://github.com/tobymao/18xx/issues/1302
---
There are a series of titles that award bonuses for stops at certain hexes or hitting specific routes. We may be able to make some generic functionality for this. In the meantime, I am tackling the titles missing this data in the route selector and logs.
---
=> 18AL Bonus Revenue Display and Logging

lib/engine/step/g_1867/merge.rb, lib/engine/step/g_1867/post_merger_shares.rb
Allow for buying presidency share at the share stage
Allow for second round of buying single shares
Correct order of merging so the initiator should end up with presidency
Error when the merge fails
=> 1867: Finish merger

lib/engine/step/buy_sell_par_shares.rb
This conversation will disappear eventually: https://18xxgames.slack.com/archives/C012K0CNY5C/p1608369677011200
Essentially, if the player took both buy and sell actions, it is superfluous and almost inaccurate to log that they did not continue to do those actions.
Sample Before:
```
tkspielt sells a 10% share of G&F and receives $50
G&F's share price changes from $50 to $45
tkspielt buys a 10% share of SAL from the IPO for $110
tkspielt sells a 10% share of G&F and receives $45
G&F's share price changes from $45 to $40
tkspielt declines to sell shares
cane buys a 10% share of W&A from the IPO for $110
cane declines to sell shares
```
After:
```
tkspielt sells a 10% share of G&F and receives $50
G&F's share price changes from $50 to $45
tkspielt buys a 10% share of SAL from the IPO for …
```
=> No need to log when the player has taken both actions

lib/engine/game/g_1856.rb
Noticed this when preparing a hotseat game to work on nationalization
=> [1856] Fix THB not being parrable

assets/app/view/game/axis.rb, assets/app/view/game/hex.rb, assets/app/view/game/map.rb, lib/engine/config/game/g_1860.rb, lib/engine/game/base.rb, lib/engine/game/g_1860.rb, lib/engine/step/g_1860/route.rb
Add two options to 1860: 2-3 player map, and original (first edition) insolvency rules
When testing 2-3 player map, rendering of map was broken due to the lack of hexes in column "A". There was some code in UI:Map that tries to deal with axes not starting with "A" or "0", but it wasn't complete. I modified UI::Map, Hex and Axis to allow shifting the display of hexes.
New 2-3 player map and rendering:
=> 1860 add first two options, fix map UI to allow missing row/column

assets/app/view/game/abilities.rb, lib/engine/game/base.rb, lib/engine/game/g_18_co.rb
I want to prevent players from using abilities they shouldn't be able to use. There are no companies in 18CO with an ability that can be used by other corporations, so I never want the option to show. Other games might have specific companies that can be used by third parties (this is a fact of some game on the site, I just don't remember which), and this function allows for that to be implemented.
Defaulting to true in game base so as to not break any production games. In the future, I'd propose adding a flag on the ability that toggles whether it can be used cross-corp, but that can be iterated on top of this base.
Before
After
=> Game based allow/disallow cross corp abilities

assets/app/view/game/game_info.rb, lib/engine/config/game/g_18_co.rb, lib/engine/phase.rb
18CO phase 6 starts when a "6" train is bought. This opens up purchase of both "5D" and "E".
Buying a "5D" moves to phase 6b.
Buying a "E" moves to phase 7, which rusts the "5" trains and reduces tile lay.
This update allows the phase to move straight from phase 6 to phase 7, skipping 6b, when an E is purchased. Without this change, the phase stays at "6" when an "E" is bought, because `next_on` is only looking for a "5D"
While this works for all implemented titles as well as 18CO, I have a concern that some day in the future someone will use a similar scheme and be confused when the skipped train's rust/events don't happen.
For Reference:
=> Allow for Phase Jumping

assets/app/view/game/route_selector.rb
Fixes #2762 
Add logic to route_selector to clear stored route when switching between corps/rounds with the same run_routes action.
=> Fix for route_selector when switching entities, but not steps

assets/app/view/game/abilities.rb, lib/engine/game/base.rb, lib/engine/game/g_18_co.rb
I should have slept on the previous PR because I literally woke up inspired this morning with this addition!
---
This update allows for filtering not only companies owned by other players, but also those owned by your other corporations.
Some games allow using the ability of a company another of your corporations own. 18CO only allows you to utilize your own owned companies.
Both those options could probably wind up within the ability config and implemented in the game/base function here.
=> Allow for increased control over who can use a company

assets/app/view/game/bank.rb, assets/app/view/game/corporation.rb, assets/app/view/game/entities.rb, assets/app/view/game/game_info.rb, assets/app/view/game/spreadsheet.rb, lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1867.rb, public/assets/main.css
Add the simplified train roster to entity and spreadsheet (fixes #2541)
Hide non-started corporations in 1817/1867 since they don't really matter (also #2541)
Always show loan amounts on 17 & 67 (also #2541)
Remove corporation size (also #2541)
Hide discount and available fields if they are unused (fixes #1792)
=> Various UI tweaks:

assets/app/view/game/choose.rb, assets/app/view/game/round/stock.rb, lib/engine/step/g_1817/buy_sell_par_shares.rb, lib/engine/step/g_1867/major_trainless.rb
Make it possible to control from a step if choose should appear
in the view. It is useful in case there are several choose.
The main usage for this is in 18SJ where it is possible for a player
to trigger priority deal "stealing" due to an ability.
This commit contains the general code update needed to accomplish this.
Should not affect 1867 or 1817 which are the titles using choose so far.
=> Add player choose to stock view

lib/engine/config/game/g_1849.rb, lib/engine/game/g_1849.rb, lib/engine/share.rb
Most of the physical copies of this game do not assign colors to the revenues. I tried e.g. `gray_10|gray_30|gray_90` but it only renders the last one.
=> Gray revenues update on second train of color

lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_1849.rb, lib/engine/step/g_1860/tracker.rb, lib/engine/step/g_18_mex/track.rb, lib/engine/step/tracker.rb
FIxes https://github.com/tobymao/18xx/issues/2781
https://18xx.games/game/19885
Log incorrectly stated -$20. CS did not gain money ( correct )
---
Showing correct log on an upgrade and a no-cost hex.
And correctly logging with one upgrade and one border.
=> Fix Issue 2781 - Negative Discount Logged

lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/track.rb
Fixes https://github.com/tobymao/18xx/issues/2779
Corporation can place an upgrade either first or second, as long as the upgrade on the second tile placement is the not tile they just placed with their first tile lay.
=> Fix 2779 - 18CO Upgrade Timing

lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb
While not what the user asked for, this is the real fix https://github.com/tobymao/18xx/issues/2811 as combined with showing the par groups on the stock market ( done earlier this week ), this correlates which corporations can be parred in which group. Also item 3 on https://github.com/tobymao/18xx/issues/2671
The text is removed when a corporation is parred.
Unintentionally threw in the fix https://github.com/tobymao/18xx/issues/2810 but its just config so whatever
Put in a simple implementation of DSNG special shares from https://github.com/tobymao/18xx/issues/2671
=> 18CO - Par Group on Corp Card

lib/engine/game/g_1860.rb, lib/engine/step/g_1860/track.rb, lib/engine/step/g_1860/tracker.rb
This is the last of all the functionality I was planning on adding to 1860.
Adding two options: one to use the first edition routing rules that won't allow skipping of towns, the second to essentially use all the options to revert the game's behavior to the first edition rules.
=> 1860 implement last options - no skipping of towns on runs

lib/engine/corporation.rb, lib/engine/g_18_co/share_pool.rb, lib/engine/game/g_18_co.rb, lib/engine/share_bundle.rb, lib/engine/share_pool.rb, lib/engine/step/g_18_co/takeover.rb
Fixes https://github.com/tobymao/18xx/issues/2812 
Fixes https://github.com/tobymao/18xx/issues/2780
Fixes https://github.com/tobymao/18xx/issues/2817 
Looking for a better name for the `corporate_player_share_holders` function if ya got one. It is the set of the corporate share holders and player share holders. For all other current games, it results in the same set as `player_share_holders`
Could also use a better name for `totaling_num`. This function creates an array of shares that have a total percentage matching the number of shares needed to do the swap. This is needed to allow for 20% shares being owned. The default assumes all shares have the same percentage, and thus doesn't even need to consider the share's percentage. The 18CO override finds a bundle totaling the number of …
=> 18CO Corporation can actually take President's Share

lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/buy_sell_par_shares.rb
Fixes https://github.com/tobymao/18xx/issues/2787
Changes to 18CO `sell_shares_and_change_price` - This prevents a swap sale from dropping the share price an extra space
Changes to 18CO `all_bundles_for_corporation` - This allows for all possible share combos, not just those involving the first share
Case 1: Player only has a 20% share, and no shares in the market for a swap
---
Case 2: Player only has a 20% share, and there is a 10% share in the market for a swap
---
Case 3: Player has (2) 20% shares, and there is only a 20% share in the market ( no swap possible )
---
Case 4: Player has 20%P, 20%, 10% shares and can sell any number to market cap
---
Case 5: Player has 20%P, 20%, 10% shares and can sell any number to market cap with a swap
=> 18CO Ability to swap sell DSNG's 20% shares

TILES.md, assets/app/lib/hex.rb, assets/app/view/game/hex.rb, lib/engine/part/base.rb, lib/engine/part/frame.rb, lib/engine/tile.rb
Adds an Option to the tile code to add an colored frame to a tile, which is needed for 18CZ.
You can add the code `frame=color:purple` to get a ourple frame.
It looks like that:
=> Feat(Tile): Added frame option

lib/engine/game/g_1867.rb, lib/engine/step/g_1867/merge.rb, spec/lib/engine/games/game_spec.rb
Add missing Y tile for O (fixes #2838)
Close corporations after moving assets (fixes #2836)
Post-merger share price is sum of min and max not average (fixes #2835)
Minors are skipped after a merge (fixes #2834)
CN shouldn't show up on merges (fixes #2831)
=> 1867: Bug fixes

lib/engine/step/tracker.rb
[Fixes #2818]
Implicitly using tile lay abilities from companies allows the benefit of the ability to be applied without `use!`-ing the ability. With this change, in order for a company's tile laying ability to be used during a corporation's OR turn, the ability button must be pressed.
=> skip implicit use of tile-laying abilities

lib/engine/ability/README.md, lib/engine/ability/tile_lay.rb, lib/engine/config/game/g_1828.rb, lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_1889.rb, lib/engine/config/game/g_18_chesapeake.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/config/game/g_18_ms.rb, lib/engine/step/special_track.rb
* fix docs and default for `blocks` attr
* add attr `must_lay_all` for abilities that must lay all of their tiles
together and cannot be interrupted by other actions (i.e., prevent C-P from
illegally interrupting B&S at https://18xx.games/game/1273?action=165)
=> Minor tile_lay ability tweaks

lib/engine/game/g_18_co.rb
Fixes https://github.com/tobymao/18xx/issues/2852
This ensures that when selling, bundles with 10% shares are preferred, then 20% shares, then the presidency.
Otherwise you wind up with something weird like:
=> 🐞 Fix 2852 - 18CO Sell Order of Certs

lib/engine/step/g_1860/track.rb
I biffed refactoring available_hex when I refactored path_distances, node_distances and hex_distances to support the first edition town routing rules.
Fixes #2858
=> 1860 fix for upgrading plain track

lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/part/city.rb, spec/fixtures/1846/19962.json, spec/fixtures/1846_2p_variant/11098.json, spec/game_state_spec.rb, spec/lib/engine/games/game_spec.rb
Game 19962 is broken by the cert limit change, so for the fixture, instead of
allowing actions that violate the cert limit, add an `end_game` action and
remove the rest of the game's actions
[Fixes #2799]
[Fixes #2800]
This will require a small handful of games to be pinned; like the one reported in issues #2799 and #2800, they are 1846 games involving a bankruptcy and then corporation closure resulting in incorrect cert limit.
=> Properly remove reservations when a token is placed, fix cert limit in 1846 games

lib/engine/ability/README.md, lib/engine/ability/train_limit.rb, lib/engine/phase.rb
Is typically used for minors that have a set train limit of one
or two all through the game.
=> Add train_limit ability for constant train limit

lib/engine/game/g_18_co.rb
Fix: https://github.com/tobymao/18xx/issues/2860
It was possible for a corporation to be IPO'd then the Event Triggered before the corporation ever laid its home station. This allowed a different corp to block its home token, which isn't legal.
=> Fix 2860 - 18CO Reservation Removal

lib/engine/phase.rb
Fixes: https://github.com/tobymao/18xx/issues/2872
18CO grants a +1 limit for each takeover and thus a corporation can have multiple limit abilities.
After (with train limit 2):
=> Allow for the Train Limit Ability to Stack

lib/engine/config/game/g_1867.rb, lib/engine/game/g_1867.rb, lib/engine/step/g_1867/buy_sell_par_shares.rb, lib/engine/step/g_1867/merge.rb
Maybe a few too many fixes :)
Share price should always be market price (fixes #2890)
Bidding for minors has no max price (fixes #2886)
5+5E train isn't doubled (fixes #2880)
Don't lay green tokens (fixes #2879)
Minor conversion shouldn't close minor (fixes #2874)
X5 and X7 are incorrect (fixes #2861)
Correct share drop behavior (fixes #2894)
Run nationalization code at export (fixes #2899)
Fix liquidity calculation (fixes #2889)
Fix selecting 5+5E paths when number of stops < 5 (fixes #2882)
Fix doubling of Timmons on multiplier 2 trains (fixes #2881)
=> 1867 bug sweep

lib/engine/step/g_1817/special_track.rb
See Issue for details, essentially this is a fix to allow laying coal on track heading into a town (klondike) which is likely marked as such for visual purposes.
=> Fix for 1817 coal mine on track lay connecting to a town, closes #2846

lib/engine/game/base.rb
* moves 18 Los Angeles to where "18LosAngeles" would fit
* ignore case, so 18Chesapeake is before 18CO
=> game title sorting tweaks

lib/engine/connection.rb, lib/engine/game/base.rb, lib/engine/hex.rb, spec/lib/engine/connection_spec.rb
Change connections calculation to on-demand rather than when connected.
When a tile is layed, it walks the paths invalidating the cache of connected tiles
When route requests the connections at that point it calculates them if the cache is not already calculated.
This also simplifies the downgrade case as it invalidates it anyway
Stackprof goes from 138.76 seconds for 100 runs to 103.32 on 15528 (25% reduction)
The connect! goes from 33.92% of CPU to 16% (3.117% disconnect + 12.848% connect)
Loading unoptimized goes from 16.47 seconds to 14.23 seconds (15% reduction)
improves #2533, I'm sure we can do extra improvements
=> Connections performance improvement

lib/engine/step/g_18_co/takeover.rb
Fixes https://github.com/tobymao/18xx/issues/2903 and will definitely break that game.
Remove any owned Station Tokens in hexes containing the owning Corporation’s Station tokens.
The original code was only examining the city, not the hex.
=> 18CO Takeover - Remove Redundant Tokens from Hex not City

lib/engine/step/g_1817/special_track.rb
This allows this
https://github.com/tobymao/18xx/pull/2904 fixed this but the fix got lost unfortunately
=> Allow coal to connect to gray towns; this allows coal to Klondike in 1817NA

lib/engine/game/base.rb
* if a param is given (like actions), no need to hit the db
* don't allow users to pass in arbitrary title, names, or id, it doesn't make
any sense to load a game while changing those params
=> make Engine::Game.load gentler on the db and more selective about kwargs

assets/app/view/game/sell_shares.rb
Fix https://github.com/tobymao/18xx/issues/2940
The return was added in the PR for 1828 but only looked at sell_shares action.
Also removed the duplicate step line as it is the first thing defined in the function.
CC: @crericha
=> Fix 2940 Corporate Share Sales undefined

assets/app/lib/hex.rb, lib/engine/config/game/g_1856.rb
The offboards in 1856 change on the D, not the 6 so I added a new color to distinguish this
=> Make 1856 Diesel black so that offboards can change on D, not 6 and add black hex color

lib/engine/config/game/g_1867.rb, lib/engine/game/g_1867.rb, lib/engine/round/g_1867/operating.rb, lib/engine/step/g_1867/buy_sell_par_shares.rb, lib/engine/step/g_1867/track.rb, migrate_game.rb, spec/fixtures/1867/hs_ahjzadkh_19792.json
Skip nationalized corporations (fixes #2893)
Add blocking buy private step before interest payment (fixes #2888)
Nationalizing privates should pay owner (fixes #2905)
Increase number of 2+2 and 5+5E trains (fixes #2915)
Don't place CN tokens when nationalizing if they already are on the hex (fixes #2891)
Limit market price of minor to $135 (fixes #2953)
Player after Minor auction is to the right of the winner (fixes #2950)
CN token should be placed on 639 (fixes #2917)
Correct max share price for minors (fixes #2954)
=> 1867 Bug fixes

lib/engine/company.rb
In 18CZ the values of companies is changing from round to round, so I have to change it during the game. 
Thus, it needs to be writable. 
Usage can be seen here:
https://github.com/Zwergenpunk/18xx/blob/c42b57cbc42c3cbd436d1637f3e69915cda67bf7/lib/engine/game/g_18_cz.rb#L91
=> [18CZ] Feat(Company): Value is changeing from round to round

lib/engine/config/game/g_1817_wo.rb, lib/engine/game/g_1817_wo.rb, public/logos/1817/nz.svg, spec/fixtures/1817NA/20584.json, spec/fixtures/1817WO/19926.json
The thought behind this is that since 1867 has city slots that are not IPOable until green that the same visual style should be used in 1817WO for Nieuw Zeeland because that hex is unIPOable until green (phase 3)
=> Make Nieuw Zeeland green in 1817WO until it is parrable

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/corporate_sell_shares.rb, assets/app/view/game/corporation.rb, assets/app/view/game/emergency_money.rb, assets/app/view/game/round/merger.rb, assets/app/view/game/round/stock.rb, assets/app/view/game/sell_shares.rb
Closes https://github.com/tobymao/18xx/issues/2672
The active player has no buy/sell/choose actions for the corps with a light gray background.
We could do more with this like disable selectable and turn the cursor hand to pointer, but I didn't want to make assumptions about why someone might need to select a corp..
=> 2672 - Stock Round - Denote corps with no actions

api.rb, assets/app/app.rb, assets/app/game_manager.rb, public/fixtures
When a fixture fails, no more copy-pasting the JSON into the "import hotseat" field to see how it looks in the browser, just go to `/fixture/<title>/<id>`
=> add route for accessing fixtures in the web browser

assets/app/view/game/game_info.rb
Adds an `target=_blank` to the rule hrefs so they open in new tabs by default
[Made a poll in slack](https://18xxgames.slack.com/archives/CV3R3HPUZ/p1609720327372700)
=> make rule links open in a new tab

lib/engine/game/g_1856.rb, lib/engine/round/g_1856/stock.rb
Fixed / Added a few 1856 things
Vesting was broken; If you bought a share of a different corp, the "unvested" corporation would switch but the "unvested" state wouldn't reset until the next SR. This fixes that
I added code to turn the presidency into a 1-share presidency but the code to force the player to buy back up in the SR still needs to happen in the future.
This also distributes national shares to the market, which I overlooked before
I also noticed that escrow funds count against the bank. The rules state that the escrow is held "by the bank" so that the escrow money shouldn't be "real" money and shouldn't count against that. That will complicate share buying when that gets fixed. Also the escrow money of nationalized corporations disappears from the game, but since the escrow …
=> 1856 nationalization market shares

lib/engine/game/g_1856.rb, lib/engine/round/base.rb, lib/engine/round/g_1856/operating.rb, lib/engine/step/g_1856/bankrupt.rb
This implements bankruptcy in 1856, including how a player can go bankrupt from interest *before* the corporation can fall back for not paying interest
=> 1856 bankruptcy

lib/engine/config/game/g_1846.rb
Some ocd changes to make the corp card colors match the token colors
Also make corp names consistently two words (e.g. "Erie Railroad" instead of "Erie")
=> [1846] slight changes to corp colors / names

lib/engine/corporation.rb, lib/engine/game/g_1849.rb
If the heir to the presidency holds only the double cert,
the president cannot sell down to 10% because the heir lacks a 10% cert
to exchange with the president.
Also, render token fee instead of % to float.
Here's the odd case:
Player 3 could get a 10% cert from Player 1, but not Player 2. Since Player 2 is to the immediate left of Player 3 and would become president, Player 3 must sell down to nothing in order to lose the presidency. The double cert ends up in the market:
Bonus token fee render:
=> Presidency swap for double cert

lib/engine/step/train.rb
In case there is a variant of a purchasable train we need to look
among the variants to allow it.
Before the change, when attempting to exchange for the variant train, it was not among the buyable_train_variants as the base variant was checked against.
=> Fix to make it possible to exchange for variant

assets/app/view/game/entities.rb, lib/engine/g_1849/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1849.rb, lib/engine/step/g_1849/token.rb, lib/engine/step/g_1849/track.rb
Sort unopened corps on the entites tab in the order in which they'll be
opened. Also handle when AFG can't open.
When there are no free token slots in any of the hexes in which AFG can start, it is removed from the ordering and cannot be opened until a spot becomes free, which can occur either when a different corporation closes or when a relevant city is upgraded.
=> Corporation ordering

lib/engine/round/g_18_co/presidents_choice.rb, spec/fixtures/18CO/21298.json
Fix: https://github.com/tobymao/18xx/issues/3073
Fix: https://github.com/tobymao/18xx/issues/3094
Can this really be this simple? I feel like I saw :pass used elsewhere, but running the original sample game as a spec ( which has gone poof on 18xx.games ), the President's choice round never ended as the `@entities.delete(action.entity)` was never triggered because nothing matched :pass. Switching to a string worked in both ruby and browser.
=> 18CO - Fix detection of the end of the President's Choice round on Ruby

lib/engine/step/g_18_sj/choose_priority.rb
Got errors for missing methods can_sell? and ipo_type from ChoosePriority
in 18SJ so have added these giving default values.
=> Add missing methods (fixes #3098)

lib/engine/step/g_1860/tracker.rb, lib/engine/step/tracker.rb
This adds the `location_name` in parentheses when appropriate
closes #3052
=> add location name when laying tiles

lib/engine/game/g_1856.rb, lib/engine/step/g_18_sj/special_buy.rb
The tunnel & bridge rights get transferred to the national during nationalization; duplicates get popped to the bank pool where other corporations may purchase them
=> 1856 rights nationalization

lib/engine/game/g_18_sj.rb, spec/fixtures/18SJ/shambolica_19.json
Error was introduced when icons b and m lower case was renamed.
Has now been corrected.
Correct spec file which was affected because of this bug.
=> 18SJ: Fix bonus errors for lower case destination (fixes #3106)

lib/engine/game/g_18_sj.rb
This shortcut made E train pass through blocked cities.
=> 18SJ: Remove incorrect short cut (fixes #3126)

lib/engine/game/base.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/emergency_money.rb
Previously timing restrictions were not respected during emergency
fundraising. This will likely break a bunch of games.
=> Enforce sale timing restrictions during ebuy

lib/engine/game/base.rb, lib/engine/game/g_1817.rb, lib/engine/round/g_1817/stock.rb
Fixes short squeeze to only jump a second time if player ownership
exceeds 100%. Also changes corp share sale timing restriction to be
not-in-stock-round-floated rather than after-operation.
Fixes #3012
=> Two bug fixes for 1817

lib/engine/config/game/g_1824.rb, lib/engine/game/g_1824.rb, lib/engine/step/g_1824/buy_train.rb
G-trains:
- Mine must be in route
- An Xg train will visit X+1 cities/off-board hexes, as the mine is
always part of route
- g-trains must visit exactly one mine
- Coal railway may only own g-trains
Non G-trains:
- Non g-trains may not visit any mines
All trains:
- Discount for previous version added
Remains:
- Mine revenue should go to corporation treasury
- Test in action
=> 1824: Update trains

assets/app/app.rb, assets/app/view/confirm.rb, assets/app/view/game/actionable.rb, assets/app/view/game/buy_companies.rb, assets/app/view/game/buy_companies_at_face_value.rb, assets/app/view/game/buy_company_from_other_player.rb, assets/app/view/game/buy_trains.rb, assets/app/view/game/round/merger.rb
This covers trains, privates and mergers
fixes #1619
Flash_opts had a bug which meant that errors wouldn't flash when buying privates, so i've had to effectively clone the flash code
=> Require permission checks to buy trains

assets/app/view/game/tile_manifest.rb, assets/app/view/tiles.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/dividend.rb, lib/engine/step/g_18_mag/track.rb, lib/engine/step/tracker.rb, lib/engine/tile.rb
- Double-sided tiles, which is basically pairing up certain tiles. When one is used the other is put on a separate list.
- Support for laying plain yellow track on K-hexes.
UI::tile_manifest, UI::tiles - support for double-sided manifest
Game::base - DOUBLE_SIDED_TILE flag
Step::tracker - broke tile list updates out to allow overriding
Engine::tile - added "opposite" method and instance var
=> 18Mag: double-sided tiles, K-tiles

lib/engine/step/train.rb
If the cheapest train in the depot:
- Had a more expensive variant
- Cheapest was required
the game allowed the more expensive variant to be forced buy.
Now it ensures that the name of the chosen variant is actually
the name of the cheapest variant of the cheapest train.
This fixes #3135 but it is a general fix.
=> Fix cheapest-buy during emergency buy when cheapest has variant

assets/app/view/game/map.rb, assets/app/view/game/map_controls.rb
Neither line breaks between label and select nor between zoom buttons.
Buttons always visible, only map scrolls horizontally.
ante:
post:
ante:
post:
=> map controls: prevent premature line breaks & horizontal scrolling

lib/engine/config/game/g_18_sj.rb, lib/engine/game/g_18_sj.rb, lib/engine/step/g_18_sj/choose_priority.rb, lib/engine/step/g_18_sj/waterfall_auction.rb
The PDC is handled as a company, with value 0, which is not part
of the initial auction, but instead given to the purchaser of Nils
Ericsson. It is handled as a no-buy company that is not counted
towards certificate limit, which only closes when the priority
deal choice ability is used.
This means that the "company" will appear in the player charter
and stay their for the rest of the game (until it is used) as
a reminder to the player.
=> 18SJ: Handle priority deal chooser ability as a company (fixes #3144)

assets/app/view/game/round/auction.rb, lib/engine/step/auctioner.rb, lib/engine/step/g_18_co/moving_bid_auction.rb
Fixes https://github.com/tobymao/18xx/issues/2815
This update fixes the problem where the user cannot move their bid because they cannot afford to place a brand new bid, even though they have enough to move the bid. It also removes the place bid button from the UI when the user cannot afford a Place Bid while still showing the move bid options if they can move a bid. Lastly, it removes Move Bid buttons where the user cannot add enough cash to make a valid move bid.
**Implementation Notes**
I originally tried this with an optional parameter on the max_bid / min_bid and I found it way less readable.
Can afford everything
Can only afford ONE move bid, not all.
Can only afford to MOVE bids
Can only afford to place a bid
Can't afford any bids.
=> Allow moving bids up to available cash

lib/engine/step/tracker.rb, validate.rb
This fixes the invalid lays that were occuring with 1867 X* tiles
fixes #3123
=> Enforce that every old city corresponds to exactly one new city

lib/engine/game/g_1849.rb, lib/engine/share_pool.rb, lib/engine/step/g_1849/buy_sell_par_shares.rb, lib/engine/step/g_1849/buy_train.rb, lib/engine/step/g_1849/dividend.rb
Fixes #3177
Fixes #3178
Fixes #3181
The bugs were:
- Using a string instead of a symbol to access a hash.
- Calling a private method.
- Bad timing for `old_operating_order` stuff.
The new idea in this is that the operating order needs to be updated right before the two times that shares can be sold - `buy_trains` and `buy_sell_par_shares`. "Right before" in this case means "right after the previous step", which are in this case `dividend` and `buy_sell_par_shares`, respectively.
This also fixes an unreported bug which reordered a corporation that had just operated after other shares were sold during an ebuy.
=> Refactor reorder_corps, make distance not private

lib/engine/config/game/g_18_sj.rb
Incorrect configuration caused private Nils Ericsson Första Tjing
to close when phase 5 started (if still around).
=> 18SJ: Fix premature close (fixes #3172)

lib/engine/game/g_18_sj.rb, lib/engine/step/g_18_sj/track.rb, spec/fixtures/18SJ/19.json
Simplified main line checks, which should also speed up the game.
By using the icons in the tile hex the information if a hex is
a main line hex can be utilized to make a quicker decision.
For a main line hex, if tile lay/upgrade is a real improvement
we can now remove the icon, meaning the hex wont be checked
for main line improvement in the future.
And by just keeping track of number of improvements in each
main line we will know when a main line is completed.
By using process_tile_lay instead of process_action the code
was much simplified. The 18SJ track step now keeps most of
the knowledge of the tile lays' state.
This will probably break some alpha games as they might include incorrect tile lays. I suppose these games can be deleted as they have illegal actions, but pinned is OK as …
=> 18SJ: Redesign main line tile lay/upgrade checks (fixes #3143)

lib/engine/game/g_1849.rb, lib/engine/round/g_1849/stock.rb
Fixes #3175 
Auction rounds aren't well equipped to handle token placement so this is a little hack to delay it until the beginning of the stock round.
=> Let RSA+AFG place home token

lib/engine/config/game/g_1846.rb, lib/engine/config/game/g_18_los_angeles.rb, lib/engine/game/base.rb, lib/engine/game/g_1846.rb, lib/engine/game/g_18_los_angeles.rb, lib/engine/round/base.rb, lib/engine/step/g_1846/assign.rb
* prevent abilities from being used on other corporations' turns or during stock rounds
* at attr `at_start` for rounds to tell when no actions have been processed; my
first inclination was to have an array of the actions which have been
performed in this round, checking if empty; that sounds theoretically useful
but also overkill for this case
* 1846 needs an override for `ability_time_is_or_start?` since it should still
be at the "or_start" after one of the possible assign actions has been
taken (player-owned Steamboat can assign to hex and to a corporation/minor)
* change 18LA to not use 46's Assign step; LA Steamship cannot be assigned while
owned by a player, so it is a little different from Steamboat Company and can
use the basic Assign step
* update 1846 phase text to use "marker" …
=> 1846, 18 Los Angeles: fix ability timing

assets/app/view/game/part/assignments.rb, assets/app/view/game/tile.rb, spec/assets_spec.rb, spec/fixtures/1846/22071.json
* not sure what change broke this, but this spec fails on master and passes with
the code changes, and seems to fit the description given in #3212
* while in the neighborhood, replace some `any?` calls with `!empty?` in Tile view
[Fixes #3212]
=> fix assignments being called on nil

lib/engine/step/g_18_co/moving_bid_auction.rb, spec/fixtures/18CO/21422.json
Fix captainobi trying to bid on DPTC in https://www.18xx.games/game/21422
The previous code works in javascript but not in ruby. As soon as there were multiple bids on one private, the error 
```
Failure/Error: puts "#{company_bids&.select { |b| b.entity == player }.max.price}\n\n"
NoMethodError:
undefined method `price' for nil:NilClass
```
occurs. This code works in both ruby and javascript.
=> Fix 18CO highest_player_bid

lib/engine/step/g_18_ms/buy_train.rb
18MS handles train buys in its own way due to an earlier problem
(#1553) so a refresh of depot trains is needed.
=> 18MS: Fix phase change problem for upcoming trains (fixes #3192)

assets/app/view/game/button/buy_share.rb, assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/corporation_pending_par.rb, assets/app/view/game/exchange.rb, assets/app/view/game/round/operating.rb, assets/app/view/game/round/stock.rb, assets/app/view/game_page.rb, lib/engine/game/base.rb, lib/engine/game/g_1828.rb, lib/engine/step/g_1828/buy_sell_par_shares.rb, lib/engine/step/g_1828/exchange.rb
- Exchange for one share of the presidency (cash for the other after parring)
- Add logic to trigger parring of the corporation after the exchange
- If exchange causes corporation to float, it operates in the next operating in which no corporations have yet operated (could be the current OR)
=> 1828 - M&H presidency exchanges

assets/app/view/game/dividend.rb, lib/engine/action/dividend.rb, lib/engine/config/game/g_18_mag.rb, lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/buy_train.rb, lib/engine/step/g_18_mag/discard_train.rb, lib/engine/step/g_18_mag/dividend.rb, lib/engine/step/g_18_mag/route.rb, lib/engine/step/g_18_mag/token.rb, lib/engine/step/g_18_mag/track.rb, lib/engine/step/tokener.rb, lib/engine/step/tracker.rb
- Add optional 2nd tile lay
- Add payment to corps for 2nd tile lay, terrain costs, tokens
- Add "variable" dividend type and UI for corps
- Allow any train from depot.upcoming to be used
- Add "scrap" train step (really just discard trains) with train going back to depot.upcoming
- Switch name and logo for former KSB corp - now SKEV
- Skip tile lay, route, buy_train for corps
- Add "amount" parameter to Action::dividend
- Add support for "variable" dividend type to UI::dividend
- Break out tile and token payments from vanilla Step::track and Step::token
New "variable" dividend UI:
=> 18Mag: Add most of OR steps for minors and majors

lib/engine/step/g_1860/buy_cert.rb
Pinning may be needed for games where people accidentally passed after winning an auction.
Fixes #3248
=> 1860: remove pass as option after winning auction

lib/engine/config/game/g_18_sj.rb, lib/engine/step/g_18_sj/buy_train.rb, lib/engine/step/g_18_sj/buy_train_action.rb, lib/engine/step/g_18_sj/buy_train_before_run_route.rb
Fixed Motala Verkstad:
- Using ability does not close the private
- Can buy any number of trains before running route
(But still, cannot buy after route if used)
- Prematurely bought trains can operate (cmf KHJ buy-in)
- Updated description
This might break some 18SJ games as the blocking premature
buy now will appear in each OR as long as Motala Verkstad
owned by the corporation operating.
It should be possible to migrate these games and add a
pass action if needed. Alternative is to just delete the games.
=> 18SJ: Fix Motala Verkstad (fixes #3267)

lib/engine/step/g_18_co/moving_bid_auction.rb
Fix https://github.com/tobymao/18xx/issues/3242
Ruby (not JavaScript) was returning the first player bid, not the highest.
Clarified variable name player_bids as @bids is also defined.
Fix move_bid min/max detection.
=> 18CO Fix Finding Highest Player Bid

lib/engine/step/corporate_buy_shares.rb
Fix https://github.com/tobymao/18xx/issues/3262
A corporation should not be able to buy the free share provided by one of the privates unless that share has had its par price set.
=> Fix 18CO private share buyable before being parred

assets/app/view/game/game_info.rb, lib/engine/config/game/g_18_mag.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mag.rb, lib/engine/phase.rb
18Mag changes phases on the purchase of a new train type - independent of which type that is.
- Engine::Phase - make @next_on accessible, add method to get next phase
- UI::GameInfo - game-specific formatting of phase triggering trains
- Game::Base - game-specific formatting of phase triggering trains
Game Info:
=> 18Mag: phase changes

assets/app/view/game/bank.rb, assets/app/view/game/round/auction.rb, lib/engine/config/game/g_1828.rb, lib/engine/game/g_1828.rb, lib/engine/share_price.rb, lib/engine/step/g_1828/buy_company.rb, lib/engine/step/g_1828/exchange.rb, lib/engine/step/g_1828/waterfall_auction.rb
- Resolve "undefined" in view when bank in nil by returning an empty div
- Implement tiered auction in the view. This is an auction when the first private cannot be bought unless other privates on its row have been bid on. The engine code was already there. This was only to add the view side.
- Use par groups for the stock market and misc stock mark visual cleanup
- Resolve an ability timing bug
=> 1828 visual updates

lib/engine/game/g_1849.rb, lib/engine/step/g_1849/bankrupt.rb, lib/engine/step/g_1849/buy_sell_par_shares.rb, lib/engine/step/g_1849/buy_train.rb
Fixes #3279 
Also fixes an unreported bug: Unsold corps should remain ahead of sold corps on same spot during reordering.
=> Fix corp reservation on restart

lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1828.rb, lib/engine/game/g_1870.rb, lib/engine/step/buy_sell_par_shares.rb
holding_ok? was used by the buy code, so the old way didn't enforce the cert limit when buying.
=> Reimplement logic to allow holding certs above the limit.

assets/app/view/game/round/merger.rb
Add active player information on mergers allowing
for more context of if the player wants to merge/convert
fixes #3301
=> 1867 & other mergers - Add player info in mergers

lib/engine/game/base.rb
The check was implemented for18Chesapeake's B&S company, where both tiles are required to be laid at the same time. It was not intended for all tile_lay abilities. Update the logic to only trigger for tile_lay abilities that also use 'must_lay_all'. Implemented in conjunction with @michaeljb. 
This is a required fix before 1828 goes to alpha.
I ran it against my db snapshot and all looked good. Please run against the latest DB also before deploying. @michaeljb may be able to do some additional validation tonight if need be.
=> Ability timing fix for companies with two tile_lay abilities.

lib/engine/g_1828/system.rb, lib/engine/game/g_1828.rb, lib/engine/step/dividend.rb, lib/engine/step/g_1828/buy_sell_par_shares.rb, lib/engine/step/g_1828/buy_train.rb, lib/engine/step/g_1828/dividend.rb, lib/engine/step/g_1828/exchange.rb, lib/engine/step/g_1828/merger.rb
Bugs fixed:
- Discard train did not remove the train from the shell
- Merger did not work on server (Ruby vs JS)
- System owner could not contribute cash if one of the shells were empty
- Game required a train in both shells
- Systems paid a one share dividend to *every* entity
- Couldn't exchange for a share when at the share limit
=> 1828: Fixes for major bugs found in pre-alpha multiplayer playthrough of full game

assets/app/view/game/route_selector.rb, lib/engine/config/game/g_18_mag.rb, lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/dividend.rb, lib/engine/step/g_18_mag/route.rb
Use SpecialBuy to allow minor to pay for RABA, G&C and SNW "railcar" powers
G&C, RABA, and SNW powers are available via button above route selector:
Common file change:
- UI::route_selector - generalize case of showing subsidies (since mines generate those)
G&C power - convert to N+N train:
RABA power - offboard bonus:
SNW power - allow use of mines:
=> 18Mag: add RABA, G&C and SNW power purchase

lib/engine/game/base.rb
This covers cases where companies have 4 or 5 shares (etc) without them needing additional logic
Ran the test fixtures, passed
=> generically capitalize based on number of shares

lib/engine/step/g_18_co/tracker.rb
Fix https://github.com/tobymao/18xx/issues/3297
In lay_tile, before check_track_restrictions! is called, the new tile is laid and the graph updated. This meant the original timing for calling prior_connected_paths was after the graph was updated, and thus we were examining newly connected paths as well. If the corporation could trace a loop back to the old segment of track, it would be returned as connected.
The new logic sets the prior_connected_paths before the graph is updated, so we are working with the true set of prior_connected_paths.
**Example**
Here CS should NOT have been able to upgrade the tile to connect between Pueblo and Trinidad (as happened in https://18xx.games/game/22553?action=451 ). The old logic failed because of the loop between Colorado Springs and Pueblo.
=> Fix 18CO Prior Connected Paths Timing

lib/engine/game/g_1849.rb
Fixes #3337 
Removing the corp from the operating order messes with `entity_index`.
=> Fix AFG quake again

assets/app/view/game/special_buy.rb, lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/track.rb, lib/engine/step/tracker.rb
Use SpecialBuy (again) to implement terrain "tokens"
- UI::SpecialBuy - allow @step to override default button text
- Step::Tracker - pull tile lay logging message into pay_tile_cost method (to allow redefinition)
=> 18Mag: implement terrain tokens

routes/user.rb
not a valid mail address => 'Invalid email address'
valid mail address, but unknown => 'Could not find user'
triggered by #3319
=> login: not an email address => error msg

routes/user.rb
Reverts tobymao/18xx#3359
Some users don’t have a valid e-mail-address in the DB. The (reverted) change would prevent them from logging in.
=> Revert "login: not an email address => error msg"

lib/engine/game/g_1828.rb
This should also cover the 1817 variants, since they inherit from this class
fixes #3366
fixes #3369 
Checked the verbiage on the permissive track lays, for confirmation
```
After placing or upgrading a track tile the placing share
company must be able to trace a continuous line of track
from one of its station markers to a line of track on the
placed track tile without:
– Passing through a city with all of station-marker
spaces filled with other companies’ station or blocking station markers.
– Passing through the Virginia Coalfields (K11) if the
public company doesn’t already own a coal token.
– Crossing any hexagon-edge twice.
```
=> [1828] various fixes

lib/engine/game/g_1849.rb, lib/engine/step/g_1849/bankrupt.rb, lib/engine/step/g_1849/buy_sell_par_shares.rb, lib/engine/step/g_1849/buy_train.rb
If two corps are sold and one is ledged, the unledged one should remain
in front on that space.
=> Share movement fix

lib/engine/config/game/g_1824.rb, lib/engine/game/g_1824.rb
Sarajevo is an offboard city, that use three hexes, with 6 termini.
Did not work with current implementation so am trying a different
approach. Now this uses 5 hexes instead of 3 so lanes is probably
a better solution, but this should be good enough as be playable.
Further improvements can be done in the future.
Before change:
After change:
=> 1824: Make Sarajevo offboard hex work functionally

assets/app/view/game/par.rb
The previous soultion did not work as expected
With 10 Shares and 60% max_ownership:
60/10 = 6 - > works
with 4 shares and 75% max ownership:
75/4 => 18,75 -> meeh
the new soultion should work for all values
With 10 Shares and 60% max_ownership:
(60/100) * 10 = 6
with 4 shares and 75% max ownership:
(75/100) * 4 = 3
=> Fixed purchasable share count

lib/engine/config/game/g_1867.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1867.rb, lib/engine/game/g_18_chesapeake.rb, lib/engine/game/g_18_cz.rb
Adds a `timeline` to 18Ches (also covers 18ChesOTR), 1817, 18CZ (since exports happen through the entire game)
Adds a `status` for 1867 (since exports only happen in specific phases)
Someone may want to double-check this, since I haven't played 1817 or 1867 (wrote it up based on a quick rules read-through)
closes #2863
=> add descriptions of exporting

assets/app/view/game/route_selector.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mag.rb, lib/engine/route.rb, lib/engine/step/g_18_mag/route.rb, lib/engine/step/g_18_mag/token.rb, lib/engine/step/tracker.rb
Most minor changes:
- Fixed orientation for BudaPest
- Move left by one on block sales
- Set must_buy_train false
- Permissive tile lays
- Corp token placement and bonus
- UI::route_select - clear route caches when refreshing
- Game::base - support for :down_block and :left_block
- Step::tracker - add log message when home token needs to be placed on upgrade
- Engine::route - calculate connection_data before clearing cache
=> 18Mag: functionality additions

assets/app/view/game/corporation.rb, lib/engine/game/g_18_co.rb
From: https://github.com/tobymao/18xx/issues/2671
Make corporate shares more distinguishable on the card ( show a symbol next to corps )
In revenue string, don't show the ignored towns.
=> 18CO QoL upgrades

assets/app/view/chat.rb, assets/app/view/game/game_log.rb
should fix #3247
[kaoskody confirmed](https://18xxgames.slack.com/archives/CV3R3HPUZ/p1610999489181200?thread_ts=1610907937.149900&cid=CV3R3HPUZ) it’s the same issue in the main chat and I could finally reproduce this on browserstack (OnePlus 6T, Chrome), too.
Just weird that nobody stumbled upon this earlier. Main chat input was a textarea [since June](https://github.com/tobymao/18xx/commit/a0290589ef18c354cd8761b1f71d972d40c78e2b) so I didn’t anticipate any problems.
=> fix mobile chat input

lib/engine/game/g_1867.rb, lib/engine/step/train.rb
Correct nationalization of corp to skip to next entity (fixes #3372)
Take loans before trains have rusted (fixes #3380)
=> 1867 bug fixes:

lib/engine/config/game/g_18_mag.rb, lib/engine/game/base.rb, lib/engine/game/g_18_mag.rb, lib/engine/minor.rb, lib/engine/step/g_18_mag/route.rb, lib/engine/step/g_18_mag/track.rb
- Use 1870-pioneered river partition for F9
- Implement end game
- Add descriptions of corporate powers to corp cards
- Fix references to tile color (need to by symbols, not strings)
- Fix attaching abilities to minors
- Game::Base - convert ability strings to symbols for minors, add support for new end condition: final phase
- Engine::Minor - deal with abilities converted to symbols
Fixes #3381
=> 18Mag: Partition, End game and Server-mod fixes

assets/app/view/game_card.rb, public/assets/main.css
Same width for all game related buttons (join, leave, start, delete, confirm, invite and review). Placement rtl ttb. If we’d ever need more buttons they’d follow suit. If longer captions were needed (minor) changes would become necessary.
Same height on all headers would be possible but would waste space on short titles (basically all but 18Chessie:OtR) with <= 2 buttons when the games are running.
ante:
post:
=> game cards: fix placement/alignment of buttons

assets/app/view/game/bid.rb, lib/engine/step/auctioner.rb, lib/engine/step/passable_auction.rb
Log in bidding when auto-passed due to cannot afford (fixes #2628)
Make it clear that the user hasn't passed if cannot afford to raise (fixes #2627)
Make min bid actually min bid (fixes #2349)
=> 1817: Various ui and log tweaks

assets/app/view/game/buy_companies.rb
Limit the max price to corporation cash if it is less than the company max price.
This prevents a player from submitting too high a price and getting back an error.
I started to worry about buying power, but that is irrelevant - one still would have to actually issue the share, and thus get the money in the treasury, to pay more for the company.
From: https://github.com/tobymao/18xx/issues/2671 but useful for all games.
Showing max price when corporation has more than max
Showing treasury amount when corporation cannot afford max
=> For Buy Company, set Max to max company price or treasury, whichever is lower.

lib/engine/config/game/g_18_mag.rb
Budapest's revenue should be 80 in gray phase. Fixes #3426.
=> 18Mag: fix L37 revenue

lib/engine/game/g_18_mag.rb
Fixes #3421 
Will break any game that advances to the Brown phase in the first OR of a set.
=> 18Mag: fix phase change effect on next round

lib/engine/game/g_18_sj.rb, lib/engine/round/g_18_sj/operating.rb, lib/engine/step/g_18_sj/buy_train_action.rb, lib/engine/step/g_18_sj/dividend.rb
The SJ tokens is now made passable (neutral) when
route step is setup (if current entity owns E train)
and made impassible when dividend has been paid.
This might break some existing games that has broken
the rules of the game.
As this happens late in the games I think they can be
pinned if not completed, and archived if completed.
=> 18SJ: Correct E train token handling (fixes #3173)

assets/app/view/welcome.rb, lib/engine/config/game/g_18_co.rb, lib/engine/game/g_18_co.rb
Move 18CO to beta as there haven't been any bug reports for 5 days and no breaking changes are expected to be introduced.
Fix https://github.com/tobymao/18xx/issues/2814
Fix https://github.com/tobymao/18xx/issues/2986
It is still a teeny bit difficult to see the two exits, but the revenue now shows and the circles are actually within the tile.
Before
After
=> 18CO Beta and Denver Tile Tweak

lib/engine/game/base.rb, lib/engine/game/g_18_co.rb
Use standard bundle calculations for standard corps ( DSNG is the only one with multiple 20% shares )
Use percent instead of price for share sorting, same results without calculations
=> 18CO - Performance Updates

lib/engine/step/g_1817/special_track.rb, lib/engine/step/g_1856/track.rb, lib/engine/step/g_1860/home_track.rb, lib/engine/step/g_1860/track.rb, lib/engine/step/g_1860/tracker.rb, lib/engine/step/g_18_cz/home_track.rb, lib/engine/step/special_track.rb, lib/engine/step/track.rb, lib/engine/step/tracker.rb
as a second action
fixes #3256
also tidies up some 1860 code since it was fixing a similar bug
=> Show track restrictions on the UI for games which cannot upgrade

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/exchange.rb, lib/engine/ability/README.md, lib/engine/ability/exchange.rb, lib/engine/config/game/g_1824.rb, lib/engine/config/game/g_1828.rb, lib/engine/config/game/g_1835.rb, lib/engine/config/game/g_1836_jr30.rb, lib/engine/config/game/g_1860.rb, lib/engine/config/game/g_1882.rb, lib/engine/config/game/g_1889.rb, lib/engine/game/base.rb, lib/engine/game/g_1882.rb, lib/engine/step/exchange.rb, lib/engine/step/g_1860/exchange.rb
Added an attribute 'corporations' that takes an array of corporation names.
If 'corporation' attribute is not specified, the 'corporations' is used instead.
This is a replacement for part of #3393.
=> Add possibility to specify a selection of corporations for exchange

lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/track.rb, lib/engine/tile.rb
- Clearing 'K' label on outgoing yellow tile required new method in Engine::Tile
- Fixed error introduced with new end-game rule where triggering OR wasn't followed by an SR correctly
Common file changes: Engine::Tile add clear_label! method
Fixes #3462 
Fixes #3482 
This is likely to require pins.
=> 18Mag: K-tile bug fix; end-game bug fix

lib/engine/game/base.rb, lib/engine/game/g_18_co.rb, lib/engine/step/g_18_co/corporate_buy_shares.rb, lib/engine/step/g_18_co/moving_bid_auction.rb
Fix https://github.com/tobymao/18xx/issues/3461
Pass Order Priority: Priority order is determined by the order in which players pass. ( see 1828 )
Pay-Per-Trash: Selling multiple shares before a corporation's first OR returns the amount from each movement down on the market, starting at the initial price
Major Investors: Corporate share purchase cannot trigger Presidency exchange to another player.
Pay-Per-Trash
=> 18CO optional rules

lib/engine/step/g_18_mag/discard_train.rb
[20:09]Vanish operates LdStEG
[20:10]LdStEG passes place a token
**[20:10]LdStEG skips scrap trains**
[20:11]LdStEG pays out 110 Ft
[20:11]LdStEG pays out 110 Ft = 11 Ft (55 Ft to Vanish, 44 Ft to NightFlyer, 11 Ft to DelmarSon)
[20:11]LdStEG's share price changes from 75 Ft to 90 Ft
Majors can never scrap, so no point in logging it.
=> 18Mag - Skip logging scrap train for majors

assets/app/view/game/discard_trains.rb, assets/app/view/game/dividend.rb, assets/app/view/game/round/auction.rb, lib/engine/config/game/g_18_mag.rb, lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/dividend.rb, lib/engine/step/g_18_mag/route.rb
- Add map display to draft rounds with minors on offer (generic)
- Add map display to discard_train steps during operating rounds (generic)
- Add price movement chart for 18Mag dividends
- Add specific RABA benefit to special_buy button
- Make bank large enough to avoid bank breaking
- Add minors to spreadsheet view
- UI::DiscardTrains - show map if in OR
- UI::Dividend - show movement chart for variable dividends
- UI::Round::Auction - show map if minors are available
Fixes #3419 
Fixes #3450 
Fixes #3481
=> 18Mag: UI improvements

lib/engine/g_1849/share_pool.rb, lib/engine/g_1860/share_pool.rb, lib/engine/game/g_1817.rb, lib/engine/game/g_1849.rb, lib/engine/share_pool.rb, lib/engine/step/g_1849/swap_choice.rb
Fixes #3502
The outgoing president can choose to let the incoming president retain
the double cert (if that player has two single certs). This is probably
a bad idea.
=> Outgoing pres swap option fix

assets/app/view/game/corporation.rb, lib/engine/g_1828/system.rb, lib/engine/game/g_1828.rb
Augmented the corporation card by including the logo for each shell and a separate line for the trains in each shell. Below are a few examples. @yzemaze, can you please review?
Portrait orientation
Landscape orientation
=> 1828: Augmented the corporation card for systems

lib/engine/game/g_1861.rb, lib/engine/game/g_1867.rb, lib/engine/round/g_1861/operating.rb, lib/engine/step/g_1861/buy_company.rb, lib/engine/step/g_1861/buy_train.rb, lib/engine/step/g_1861/dividend.rb, lib/engine/step/g_1861/skip_for_national.rb, lib/engine/step/g_1861/token.rb, lib/engine/step/g_1861/track.rb, lib/engine/step/g_1867/track.rb
Also rename CN in 1867 generally as 'national' as 1861 refers to it as 'Russian State'
=> 1861: Implement operating round for the national corp

assets/app/view/game/round/stock.rb, lib/engine/company.rb, lib/engine/config/game/g_1824.rb, lib/engine/game/g_1824.rb, lib/engine/round/g_1824/first_stock.rb, lib/engine/round/g_1824/stock.rb, lib/engine/step/g_1824/buy_sell_par_shares_first_sr.rb, lib/engine/step/g_1824/dividend.rb
The first attempt was to make Coal Railways corporations but they function
in all ways as a minor so this commits makes them minors.
The main reason for having them as corporations was that these had
5 different purchase prices (120G - 200G) so using the parring worked.
But it turned out to cause problems down the line so I now go back
to having them as minors.
Now, it still needs to support buying for different prices. And I have
now added support for having multiple prices by adding an interval
attribute to companies. In case this is set (default nil) the stock
view will render buy buttons similar to par buttons, when buying
private from bank.
In case interval is not specified as attribute this change has no
effect.
This is how the Stock view looks like in interval attribute specified …
=> 1824 mainly: Make Coal Railways minors

lib/engine/game/base.rb, lib/engine/game/g_18_mag.rb
Fixes #3531 
Changes Game::Base::check_distance as well.
**Old behavior:**
**New behavior:**
=> Fix check_distance for base and 18Mag to handle N+M trains correctly

lib/engine/step/g_1846/track_and_token.rb
[Sample game](https://gist.github.com/benjaminxscott/aa25da23db6e496a0d2e99a104f27993)
This clears the `lsl` icon from a given hex after it has been upgraded to green
This is rules-accurate since LSL can be used for a free upgrade (specifically from yellow to green), and LSL goes poof in brown phase (so it can never upgrade from green to brown)
Note that it's safe to clear this icon since LSL doesn't block hexes
Before:
After:
=> remove LSL icon appropriately after relevant tiles are upgraded

assets/app/view/game/dividend.rb, lib/engine/game/g_1860.rb, lib/engine/step/g_1860/dividend.rb
- Fix share movement description on dividend step to match expectations (despite zig-zag market). I.e. "move 2 right" becomes "move 1 right"
- Add hint to leased trains showing maximum possible revenue
- Sort companies in entities tab by layer
Common file change:
- UI::DIvidend - use step method (if implemented) to generate text for share price movement in table
Fixes #3214 
Fixes #3215 
Fixes #3205
**Old**
**New**
=> 1860: ui improvements

lib/engine/g_1849/share_pool.rb, lib/engine/share_pool.rb
Fixes #3546
Some duplicated mode moved into a function and then overridden for 1849
to avoid giving the outgoing president the double cert from the market.
=> Refactor handle_partial

lib/engine/config/game/g_1849_boot.rb, lib/engine/game/g_1849_boot.rb
Update terrain per starchitect suggestions here (ratchets up terrain costs)
https://boardgamegeek.com/thread/2582803/article/36837090#36837090
There is a new gray hex C7
Upon Phase 12, C7 this downgrades to a 10 value stub.
The A hex/tile sequence is updated to facilitate building to Rome via the Avezzano shortcut and afterwards.
Scott did the terrain, @tysen did the earthquake
I tested the earthquake.
=> Update 1849K2S per starchitect terrain suggestions, add earthquake

assets/app/view/game/game_info.rb, assets/app/view/game/game_meta.rb
Split from https://github.com/tobymao/18xx/pull/3162
This was a large function of if statements, which I find very difficult to read. This refactor seemed large enough to split out by itself. 
I plan to use this information on the Game Title page, so creating its own module appeared to be a good idea. An argument could be made that not all functions should return arrays, but I liked how clean this made the render function, with no need to run a .compact at the end. Open to debate.
@michaeljb Mentioned the discrepancy between calling this "Game Meta" when the header is "Game Info". There is already a game_info.rb module, so I wasn't sure if it would be more or less confusing to change either.
=> Refactor: View - Game Info

lib/engine/game/g_18_co.rb
Taking advantage of the work done in https://github.com/tobymao/18xx/pull/3445
In 18CO, a private does not need to be purchased in the initial auction. It remains in the bank and can be purchased at a later time by a corporation. Prior, there was no way to see which privates had not been purchased except for the log.
=> 18CO - Show bank-owned companies (for later purchase)

lib/engine/route.rb, lib/engine/step/g_1860/tracker.rb, lib/engine/step/tracker.rb
- Refactored Step::G1860::Tracker to use more of base class
- Step::Tracker - added "save_old" method to allow above
- Engine::Route - clear route.halts on touch_node. This allows calculate_stops logic to optimize revenue and halts when building a route
Fixes #3208
=> 1860: refactor step/tracker to use common code; optimize halt usage

lib/engine/hex.rb
Modify the logic in Hex.lay(tile) to map cities without exits more robustly.
Fixes: #3550 
The current logic fails when mapping a two-city tile with one city having track and the other not, to an upgraded tile:
=> Fix Hex.lay to map cities more robustly

lib/engine/game/g_1860.rb
Previous change to halts meant that selecting a route that had enough towns to fill the train allowance prevented ever selecting non-zero halts.
With this change, route.halts will always be written if there are halts are visited on the route, except for loaner trains and when the southern forms (after sr).
Fixes #3581
No pins should be required because it just affects route selection via UI.
=> 1860: update route.halts even if no halts are desired

assets/app/view/game/dividend.rb, assets/app/view/game/route_selector.rb, lib/engine/step/g_1860/route.rb
Add a chart to UI::route_selector to give a player the same info they'd see playing a F2F game by looking at the game board:
Also, tweaked dividend table for 18Mag in UI::dividend.
Fixes #3213
=> 1860: add share price movement chart to route_selector

lib/engine/game/g_1867.rb
This change makes it more explicit that the `nationalize_companies` event only concerns privates. Minors, majors, and privates are all exclusively referred to as "companies" in the rules.
=> 1867: clarify private company nationalization event

lib/engine/game/g_1849.rb
closes https://github.com/tobymao/18xx/issues/3603
=> [1849] Shares are in "Treasury" , not "IPO"

lib/engine/game/g_1877.rb
Override the default 1817 descriptions of "end on the first 8 train" since we end on the first 4 train
=> [1877] update game end description

lib/engine/config/game/g_1861.rb, lib/engine/game/g_1861.rb, lib/engine/game/g_1867.rb, lib/engine/round/g_1861/operating.rb, lib/engine/step/g_1861/buy_sell_par_shares.rb, lib/engine/step/g_1861/route.rb, public/logos/1861/M-K.svg, public/logos/1861/MKu.svg
Generalize the Timmins bonus
Remove neutral tokens for 1861
Change the RSR token behavior for 1861
=> Add 1861 map

assets/app/view/game/spreadsheet.rb, lib/engine/game/base.rb, lib/engine/game/g_1882.rb
For part of [issue #2506](https://github.com/tobymao/18xx/issues/2506). After this change, all columns in the Corporation section of the spreadsheet should be sortable (the loans column mentioned in the issue is already sortable). Worked on with @erperreault 🌈 🚋
=> Add sort for trains, tokens, and companies columns in Spreadsheet tab

assets/app/view/game/actionable.rb, assets/app/view/game/history_controls.rb, assets/app/view/game_card.rb, public/assets/main.css
No more jumping buttons when clicking through history.
Screenshots at 320px / 20 rem width.
ante:
post:
… and crap like this shouldn’t happen anymore:
Buttons extend a bit on bigger screens.
As a nice side effect we get a rudimentary loading indicator due to buttons being :active until the triggered action completes:
(ymmv, browsers …)
=> history: fixed button positions, button style

lib/engine/game/g_18_chesapeake.rb, lib/engine/game/g_18_tn.rb
For 18TN:
--
For 18Ches two-player:
Note that C&A is the "Cornelius" company in this test game, so its presidency is 20%
closes #3600
=> show non-standard president share percentage when relevant

lib/engine/step/g_1867/buy_train.rb
In game 23040 NYC was nationalized since it didn't buy a train,
this causes it to skip to the new corps turn GWR but the unpass occurs before
the pass, move the nationalization to after the pass. (fixes #3625)
=> 1867: Previous corp nationalizes causes skip of train buy

assets/app/view/game/part/city_slot.rb
=> Fix null ring for corps not owned by a player

DEVELOPMENT.md, routes/user.rb
This enables logging while in development, but keeps the secure cookie flag on production
=> Only require ssl encryption of cookies on production

assets/app/view/game/round/stock.rb, lib/engine/config/game/g_1824.rb, lib/engine/game/g_1824.rb, lib/engine/round/g_1824/first_stock.rb, lib/engine/step/g_1824/buy_sell_par_exchange_shares.rb, lib/engine/step/g_1824/buy_sell_par_shares_first_sr.rb
Mountain Railways is exchanged during SR in phase 3 by selecting
a regional, and click on Exchange. This exchange is for a 10% share.
Coal Railway is done as a Special Buy during SR in phase 3 or 4.
This exchange is for a 20% presidency share.
(The reason for separate ways is that the presidency share is set
to No Buy, and implementing support for doing normal exchange is
complicated. Think this way is good enough.)
When phase 5 is started the exchange of any remaining Coal Railways
is triggered.
Only change in general code is to show Special Buy during stock
round if any step responds to special_buy action.
Some minor changes of details (e.g. names) discovered during
play testing.
=> 1824: Support exchange Mountain and Coal Railways

lib/engine/config/game/g_18_zoo.rb, lib/engine/game/g_18_zoo.rb, lib/engine/step/buy_company.rb, lib/engine/step/g_18_zoo/buy_company.rb, lib/engine/step/g_18_zoo/buy_sell_par_shares.rb
Addition to 18ZOO:
- add ZOOTickets on game creation
- companies can be bought from players
- companies (only OR or ZOOTicket from owner player) can be bought by corporation
- ZOOTicket can be sold by corporation (price to player, difference to corporation)
- ZOOTickets value changes every round
- Player orders is higher cash + current order (but not on Draft)
=> 18zoo add tickets

assets/app/game_manager.rb, assets/app/view/invite_game.rb
Previously the invitation page did not refresh automatically, which was confusing to a lot of users. I took the chance and created a channel to listen to general game metadata changes to make the home page update automatically and avoid the need to refresh.
I've increased the refresh timeout, since it's less important now. It is still there because the new channel does not publish when an action is submitted. I think that would require a more targeted approach to avoid flooding all the online users.
PS: I'm sorry for lashing out the other day. My life has been rough, but that's no excuse for my reaction. I really appreciate Toby's selfless work (as everyone else's)
=> Fix invite page var name and auto refresh

lib/engine/game/g_18_mag.rb, lib/engine/step/g_18_mag/track.rb, lib/engine/step/tracker.rb
Minor tokens should always be placed on city index 0 when laying a yellow OO according to Lonny.
Before this change, the player had to select a city via HomeToken.
This change will require pinning most 18Mag games due to now superfluous place_token actions at the start of games.
Fixes #3650
=> 18Mag: Auto-lay token on yellow OO tiles

lib/engine/config/game/g_1822.rb, lib/engine/game/g_1822.rb, lib/engine/round/g_1822/stock.rb, lib/engine/step/g_1822/buy_sell_par_shares.rb, lib/engine/step/g_1822/buy_train.rb, lib/engine/step/g_1822/first_turn_housekeeping.rb
* End of stock round, remove trains if no bids on minors.
* Minors bidding par price, startorder and treasury.
* First turn housekeeping, minors can buy a L train if one still in the depot as first action in its first operation round it floated.
* Some minor code cleanup.
=> [1822] End of stock round

assets/app/view/game_page.rb, lib/engine/config/game/g_1824.rb, lib/engine/game/g_1824.rb, lib/engine/step/g_1824/forced_mountain_railway_exchange.rb, lib/engine/step/g_18_mex/merge.rb
In 1824 when the first 4 train is bought any remaining Mountain
Railways' companies need to be exchanged for shares in one of
the regionals. (Often multiple corporations possible to choose from.)
This is handled by having a stock view with only Exchange possible
during the OR.
This also means that game_page.rb was changed to allow for stock
market rendering during an OR (in case buy_shares is available).
This is the view in the OR when two mountain railways remained. This is shown after Discard Trains step.
=> 1824: Add an interrupt stock exchange step when 4 trains bought

assets/app/view/game_page.rb
The Stock view appeared by mistake in titles that had a redeem
possibility for a corporation. By restricting the view to
active players only it should just get the player options.
=> Restore stockview in OR (for 1824) but corrected

lib/engine/game/g_1860.rb, lib/engine/step/g_1860/dividend.rb
Move bankrupt corporation check from after_action to after the two places where a stock price can drop: dividends and selling shares.
This makes handling a bankruptcy that is not at the end of an OR more robust.
Fixes #3685 
A very small percentage of games may require pins.
=> 1860: relocate bankruptcy check

assets/app/view/game/part/city_slot.rb, lib/engine/config/game/g_1861.rb, lib/engine/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1867.rb, public/logos/1861/KP.svg, public/logos/1861/MB.svg
making it obvious which minors are which
fixes #3645
Also correct the name of MB's logo
=> 1861: Allow 'Green' phase minors token reservations to be green,

assets/app/view/game/buy_companies.rb, assets/app/view/game/buy_value_input.rb
Fix https://github.com/tobymao/18xx/issues/3696
Recent changes caused:
1.) Bank owned privates to move under the "Other Player" toggle which
2.) Now requires consent, failing due to the owner not having a name.
Before:
=> Fix 3696 - Bank owned companies javascript error (check_consent player.name)

lib/engine/game/g_1856.rb, lib/engine/graph.rb, lib/engine/step/g_1856/track.rb
This PR will have 1856 check after every tile lay if any escrow corporations have destinated.
This is used to find which hexes are reachable from the home hex for a corporation. 
Later PRs will:
* Make this process use auto actions and not happen when @loading
* Use the results to determine if a corporation has destinated and if so release escrow
=> 1856 does destination checks

lib/engine/corporation.rb, lib/engine/game/g_1860.rb
Corps now require 50% of shares to be owned by players in order to float (instead of 50% of IPO sold).
Added new option to Engine::Corporation - "float_excludes_market" for use in calculating when flotation occurs.
Fixes #3705 
There is a very small chance, but not zero, that this will requires pins
=> 1860: updated flotation rules

assets/app/view/game/par.rb, lib/engine/config/game/g_1822.rb, lib/engine/game/g_1822.rb, lib/engine/step/g_1822/buy_sell_par_shares.rb, lib/engine/step/g_1822/dividend.rb, lib/engine/step/g_1822/first_turn_housekeeping.rb
* In phase 2 in the stockround you can convert a concession into the president of the major company.
* After trying quite a few solutions i settle with the 1882 solution of showing the par values and automatic convert the concession.
* Did a very small modification to the base files, the par view. Checked after a method "available_par_cash", this is for the number of shares are correct on the buttons.
* Some minor bug fixes
=> [1822] Convert concession into a major company.

assets/app/view/game/corporation.rb, public/assets/main.css
- structure and css simplified
- slightly bigger gaps between elements in holdings
- trains + cash keys moved to title (=> visible on hover/tap)
- titles added to sym + tokens
- available tokens are shown first (should solve most cases of #2604)
- use of small font size only sparingly
- prefer scrollbar for tokens over x-small font size
- status and float strings at bottom centered
There’s still room to improve by revamping the token display (e.g. aggregation + popup).
"None" could be replaced by an icon (crossed out train/loco?).
Examples:
=> corporation card review

lib/engine/game/g_18_fl.rb, lib/engine/step/g_18_fl/convert.rb
This knocks off 4 of the 11 remaining rules for 18FL
A corporation must have operated before to voluntarily convert to a 10 share
Any pool / depot trains can be emergency bought
Presidencies of other corporations may be changed during emergency train buying
Cannot sell shares in corporations that have not operated yet
This one needs a separate PR
Trainless corps may force buy trains from other companies up to face value - IF they have 0 cash, but shares may not be sold
=> 18 fl misc

assets/app/view/game_page.rb
Difference between scrollHeight and scrollTop is offsetHeight. Exact match would lead to problems, adding 20 (line-height) seems to work fine.
Log still does not scroll to the bottom when taking an action (== pre #3719 behavior).
=> store log position only when scrolled up at least one line

lib/engine/config/game/g_1893.rb, lib/engine/game/g_1893.rb, lib/engine/minor.rb, lib/engine/step/g_1893/buy_sell_par_shares_first_sr.rb, lib/engine/step/g_1893/buy_train.rb, lib/engine/step/g_1893/dividend.rb
General change: Added optional type attribute on minor class.
Needed to allow for train limit for minors.
Used in 1824 and 1893.
Can buy privates during SR1. When all but one private is sold
shares in non-mergable corporations can be bought as normal.
Minors can operate, pay dividend, buy trains.
Remains:
- Special handling of SR 2 in case any of the privates
remain unsold. (Need to be sold first in SR 2.) Special
handling if everyone passes before all is sold. (Price decrease
plus forced buy at certain price.)
- Bank should not receive revenue for unsold privates
if everyone passes.
- Bonds (10 in total, cost 100M to buy, get 100M when sold,
give 10M revenue each OR, can be bought/sold during SR
according to share rules
=> 1893: First part of Start package

lib/engine/action/program_buy_shares.rb, lib/engine/action/program_disable.rb, lib/engine/action/program_enable.rb, lib/engine/game/base.rb, lib/engine/round/base.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/program.rb, lib/engine/step/programmer.rb
Relates to #209
This is the initial version.
Next steps would be:
* Separate the logging to be per player
* Deactivate programmed moves at end of round (in a way that also works for 1817)
* Add the UI
=> Initial programmed actions framework which progresses buys until floats

assets/app/view/game/part/label.rb, assets/app/view/game/part/reservation.rb, assets/app/view/game/part/upgrade.rb, assets/app/view/game/tile.rb, lib/engine/config/game/g_1861.rb, lib/engine/tile.rb
Add Y in Ottawa/Kharkiv (fixes #2885)
Fix tile 635 overlapping terrain (fixes #3636)
This slightly moves the label allowing it to be contained entirely inside two regions
Because of this i've removed the inheritance of Reservation because the text is bigger
=> 1861: Fix various tile rendering issues

lib/engine/config/game/g_1830.rb
- Add periods to ends of descriptions
- Gender-neutral language
- Make wording consistent with other titles
=> 1830 privates wording

lib/engine/game/g_18_cz.rb, lib/engine/step/g_18_cz/buy_company.rb
Small corps can only buy in small privates
Med corps can buy in small/medium
Large corps can buy in any size
[Test case](https://gist.github.com/benjaminxscott/cebe98b021cf8d3c9f70ac2f31626581)
Size is denoted by `sym`, which I don't love but I also didn't want to add something like `type` to the generic private definition since this is just for CZ
=> [18CZ] Limit private buy-ins by corp size

public/logos/1830/NYNH.alt.svg
=> [1830] fit the NYNH text in the simple logo better

assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, lib/engine/config/game/g_1822.rb, lib/engine/game/g_1822.rb, lib/engine/round/g_1822/stock.rb, lib/engine/step/g_1822/minor_acquisition.rb, lib/engine/step/g_1822/tracker.rb
* Major can now acquire minors as a step. Phase 2-7 majors can acquire player owned minors. Phase 5-7 they can also acquire one of the minors from the bidboxes. They still need to have a legal route to both options.
* Majors now have exchange tokens, did this as an ability wich already had a count on it. Did some logic for moving and removing them.
* Minors can only upgrade to green tiles even in brown and gray phase. In the green phase they still gets the option of upgrade to brown with text "Later phase". Might fix this later, it doesnt affect gameplay, since minors cant choose a brown tile when game have progressed into it.
* Phase change to phase 5 closes all concessions and changes float percent to 50. Now all majors can par as normal incremental companies.
* Did a very small change …
=> [1822] Minor acquisition

assets/app/lib/radial_selector.rb, assets/app/view/game/map.rb, assets/app/view/game/tile_manifest.rb, assets/app/view/game/tile_selector.rb, assets/app/view/tiles.rb, public/assets/main.css
- tile manifest with reduced margins => mobile and 2nd window friendly
- edges/corners of maps/tile manifest: arcs/fans of tiles instead of full circles moved towards center
- tiles are rendered with less distance to clicked hex
- map: tiles cover seams instead of hexes (in most cases)
- darker drop-shadow => better differentiation from background
Mobile edge cases (360px, 320px) …
… and map examples:
=> full size tile manifest & tile selector improvements

lib/engine/game/g_1860.rb, lib/engine/step/g_1860/buy_sell_par_shares.rb, lib/engine/step/g_1860/tracker.rb
Fixes #3802 
Fixes #3804 
A small number of games may require pinning.
=> 1860: fix sell in blocks; fix insolvent tile laying

lib/engine/config/game/g_1849.rb, lib/engine/game/base.rb, lib/engine/game/g_1849.rb
Unfortunately this requires pinning of active 1849 games because of the change in randomization. It would be possible to avoid this at the cost of much uglier code; read on if interested.
Previously, the order of operations was
- `init_corporations` (title-specific) just created `@corporations`.
- `init_company_abilities` (generic) associated RSA with a random corp because it has `random_president` ability.
- `setup` (title-specific) shuffled the corps and then called `setup_companies`, which moved RSA's corp to the front of the list.
The new order is
- `init_corporations` shuffles the corps, and moves IFT out of the first three if the option is selected.
- `init_company_abilities` associates RSA with the first corp because it has the (new) `first_president` abilitiy.
- `setup` doesn't …
=> 1849 option to delay IFT

assets/app/view/game/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1860.rb
fixes #3805
This adds possibility to tag specific status strings with css-class(es) for rendering. In case of 1860 insolvent, bankrupt etc. are bold. Font size of layer + par were chosen by @roseundy.
I got rid of bold and xsmall_font on other status_strs for better legibility (and a cleaner look) as well. Afaik these changes were implemented solely because of the longer 1860 strings anyway. 18Mag and 18Chessie (2p) look fine this way and 1824 etc. should be ok, too. Status strings needing more than 1 line would wrap nicely.
I wouldn’t mind merging status_str into status_array – if that’s desirable. (=> a few lines less, but more `[ ]` of course.)
ante
post
=> status_array: option to highlight specific status strings (1860: insolvent, bankrupt etc.)

lib/engine/config/game/g_1893.rb, lib/engine/g_18_chesapeake/share_pool.rb, lib/engine/g_18_tn/share_pool.rb, lib/engine/game/g_1893.rb, lib/engine/round/g_1893/stock.rb, lib/engine/share_pool.rb, lib/engine/step/g_1893/buy_sell_par_shares_first_sr.rb, lib/engine/step/g_1893/buy_sell_par_shares_following_sr.rb, lib/engine/step/g_1893/par_and_buy_actions.rb, lib/engine/step/share_buying.rb, public/logos/1893/AdSK.svg
Handle bonds (AdSK) as a president less corporation that does not
change price if sold (out). Gives 10M per 10% each OR.
Parring a normal corporation moves non-reserved shares to share pool.
AdSK starts with 100% in share pool.
AGV and HGK moves 50% to share pool when they can be bought.
AdSK, and corporations with reserved presidency share, does not change
presidency if bought/sold.
Two changes in general code, both in share_pool.rb:
- Added allow_president_change parameter to buy_shares, default true
- Do not call float_corporation when share bought, in case corporation
is not floatable (default wise all corporations are floatable)
These two changes are needed by 1824 and 1893 but should not affect
any other title as default behavior is as before.
=> 1893: Add more functionality related to shares, and 2nd stock round

assets/app/view/chat.rb, assets/app/view/form.rb, assets/app/view/game/actionable.rb, assets/app/view/game/game_log.rb, assets/app/view/game/history_controls.rb, assets/app/view/game/map_zoom.rb, assets/app/view/game_page.rb, public/assets/main.css
resolves #495
- Implemented on game_page for tab change, chat-activation/-leave and map zoom only – for now. If this turns out ok, more shortcuts/hotkeys and even systemwide ones (h = home, p = profile, n = next game to act …) shouldn’t be a big deal.
- Shortcuts function only if `div#game` or `body` is focussed. There should be no interference with the chat/input. Downside: on some browsers one click is necessary to focus (almost? anywhere but button, inputs, chat and top menu bar) before shortcuts work as intended. `div#game` is set to `autofocus`, but this is a hack and doesn’t work reliably on all browsers. (While testing Chrome did fine, FF didn’t. ymmv)
- Titles of anchors and buttons do work as tooltips, although a dedicated tooltip-lib might be better suited for this in the …
=> hotkeys / keyboard shortcuts

lib/engine/action/program_buy_shares.rb, lib/engine/action/program_enable.rb, lib/engine/game/base.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/program.rb
* Move to a player_log for things that should only be seen by a player (not yet filtered to the player)
* Automatically remove programmed actions on round change
=> Programmed actions: Automatically disable and log when used

assets/app/view/game/company.rb, lib/engine/game/g_1873.rb, lib/engine/step/g_1873/draft.rb, lib/engine/step/g_1873/premium.rb
Add initial premium auction
Add start auction (draft) of mines and starting concessions
Tweak to map
Load "extended" minor and company data (to avoid new classes)
Created "dummy" private companies based on mine (minors) and RR corps
Floating RRs add all home tokens and sell IPO shares to market
Common code change:
UI::Company - allow overriding "PRIVATE COMPANY" label
=> 1873: start auctions

lib/engine/config/game/g_18_eu.rb, lib/engine/game/g_18_eu.rb, spec/fixtures/18EU/hs_uflpdrek_1613000790.json
By adding the additional "pay" to the trains and "visit_cost": 0 to the hexes we can tack on the ports for free as endpoints.
=> 18EU - Ports, Status Text, Event Typo Fix, Optional Trains Verified

lib/engine/config/game/g_1849_boot.rb, lib/engine/game/g_1849_boot.rb
Also removes the "delay IFT" option from 1849-K2S.
=> Fix 1849-K2S RSA (#3903)

DEVELOPMENT.md, Makefile, docker-compose.dev.yml, docker-compose.yml, scripts/data_dir.sh
This pull request makes some changes to allow the development environment to run on Fedora.
- Docker doesn’t yet support Control Group v2 so doesn’t run out of the box on Fedora.  Allow Podman to be used instead.
- By default, Podman runs as the user rather than as root, and maps UIDs within the container to different UIDs outside the container.  Apply this mapping when creating the db/data/ directory.
- Fedora use SELinux by default, which means we need to relabel some volumes to allow them to be accessed from within the containers.
This was sufficient for me to be able to run `make` and access http://localhost:9292/.  I haven’t tried running any of this on a non-Fedora system, so it’s probably worth doing that before merging.
=> Developing on Fedora

assets/app/view/game/buy_sell_shares.rb, lib/engine/config/game/g_18_eu.rb, lib/engine/game/g_18_eu.rb, lib/engine/step/g_18_eu/buy_sell_par_shares.rb, lib/engine/step/g_18_eu/home_token.rb, lib/engine/step/g_18_eu/minor_exchange.rb, lib/engine/step/home_token.rb, lib/engine/step/share_buying.rb, spec/fixtures/18EU/hs_uflpdrek_1613000790.json
If it is before Phase 5, president also needs to trade a minor for one share of the new company and take the minor’s home for the corp home. If it is after phase 5, this is not required (the minors will be gone), but the corp must choose any open city circle on the board.
During the SR a company forms, a player may choose to exchange a _connected_ minor or a 10% share instead of a buy action. It is a straight swap, give assets to corp (_bank if pool share_). _Corp may accept or reject token._
Note: This does not implement the "connected" or "bank if pool share" or "accept or reject tokens" portions of the rules.
**buy_sell_shares.rb**
Adds minors to the list of entities that can have the exchange ability. Most of the changes are simply the …
=> 18EU - Minor Merge on Par and Minor Exchange for Share

lib/engine/step/g_1870/buy_sell_par_shares.rb
If a player owns more than 60% of a corp and they want to sell shares, they need to sell enough to comply with the 60% limit
=> 1870: Fix share selling when above 60%

lib/engine/game/base.rb
fixes #3883
Game boxes affected:
(ones using `:most_cash` sorting)
18CZ: This change reflects the correct implementation 
```
Resolve any ties so that the player who was earlier in the old order is also earlier in the new order.
```
1822: This change reflects the correct implementation
```
If two players have equal cash, their stock turn order relative to each other stays unchanged from the previous stock round. 
```
=> Maintain relative order when sorting players by most cash

assets/app/view/game/corporation.rb, assets/app/view/game/stock_market.rb
cleanup
+ opacity 0.4 if operated
+ title for all tokens (order could be included if !operated, but I didn’t see much value)
closes #3958
also helps in some cases of #1122 (which is still not solved perfectly)
=> spreadsheet tokens cleanup, opacity if operated, title added

assets/app/view/user.rb, public/assets/main.css
finally fixes #2975
Please test on Apple hardware. Browserstack is fine with it:
It’s a bit uglier on Chrome, but I guess that’s a small price to pay if it works on Apple devices.
ante:
post:
=> fix iOS & macOS color inputs

spec/game_state_spec.rb, spec/lib/engine/connection_spec.rb, spec/lib/engine/corporation_spec.rb, spec/lib/engine/games/config_spec.rb, spec/lib/engine/games/g_1828_spec.rb, spec/lib/engine/games/g_1889_spec.rb, spec/lib/engine/games/g_18_zoo_spec.rb, spec/lib/engine/games/game_spec.rb, spec/lib/engine/hex_spec.rb, spec/lib/engine/part/city_spec.rb, spec/lib/engine/part/revenue_center_spec.rb, spec/lib/engine/player_spec.rb, spec/lib/engine/round/auction_spec.rb, spec/lib/engine/round/operating_spec.rb, spec/lib/engine/round/stock_spec.rb, spec/lib/engine/share_pool_spec.rb, spec/lib/engine/stock_market_spec.rb, spec/lib/engine/tile_spec.rb, spec/lib/engine_spec.rb, spec/spec_helper.rb
This leads to fewer ~import~ require statements need in spec files, and fixes test behavior when loading a single spec file. For example, on the current master, this fails:
```
docker-compose exec rack rspec spec/lib/engine/stock_market_spec.rb
```
...while this passes:
```
docker-compose exec rack rspec
```
Having `spec_helper` load the whole `engine` allows more tests to pass with fewer `require` LOCs.
=> import 'engine' in spec_helper, 🪓 a bunch of require statements

assets/app/view/game/acquire_companies.rb, assets/app/view/game/round/operating.rb, lib/engine/action/acquire_company.rb, lib/engine/config/game/g_1822.rb, lib/engine/game/g_1822.rb, lib/engine/round/g_1822/stock.rb, lib/engine/step/acquire_company.rb, lib/engine/step/g_1822/buy_train.rb, lib/engine/step/g_1822/dividend.rb, lib/engine/step/g_1822/minor_acquisition.rb, lib/engine/step/g_1822/token.rb, lib/engine/step/g_1822/tracker.rb
* Made a new action and a new ui page, Aquire Company. I started with the buy_company view, but i had to modify it with multiple respond_to?, after i while choose to make the new view instead of clutter down the buy company code to much. I assume all other 22 variants need this as well.
* With the private 2P you gain a train in the corporation. They dont count towards the trainlimit or as a train in the mandatory train check. With this train you can also choose a different dividend then the other train, meaning you can ie withhold with the 2P and payout with the others. You can have any combination of the (payout, pay half and withhold)
* Destination bonus, if a train runs a route with both home token and destination token. You get the destination tokens city value one more time. Only one …
=> [1822] Dividend and private companies

lib/engine/game/g_1828/game.rb, lib/engine/game/g_1828/step/buy_sell_par_shares.rb, lib/engine/game/g_1828/step/company_pending_par.rb, lib/engine/game/g_1828/step/exchange.rb, lib/engine/game/g_1828/stock_market.rb, lib/engine/game/g_1849/game.rb, lib/engine/game/g_1849/step/buy_sell_par_shares.rb, lib/engine/game/g_1849/step/company_pending_par.rb, lib/engine/game/g_1849/stock_market.rb, spec/lib/engine/games/g_1828_spec.rb
This PR refactors the phased par value logic shared by 1828.Games and 1849, to instead use par groups. Par groups functionality was added after these games were implemented, but has has recently been added to both to display the phased par prices as different colors in the stock market.
Additional rationale for the refactoring is 1) data classes (stock_market) shouldn't contain logic and 2) unifies par price behavior with how other games handle variable par prices.
Tested 1828.Games and 1849 in hot seat games, up through the green phase, to verify the par price logic.
=> Convert 1828.Games and 1849 to use par groups for phased par values

assets/app/view/user.rb, public/assets/main.css
Without submit color inputs on Safari (iOS/macOS) aren’t updated. After merge changes of main bg and font color will be visible instantly.
=> ios macos color inputs (again)

assets/app/view/game/abilities.rb, lib/engine/game/g_1846/game.rb, lib/engine/game/g_1846/step/special_track.rb, lib/engine/step/track_and_token.rb, lib/engine/step/tracker.rb
- Clear the selected tile when toggling an ability
- Verify a matching ability was found when a company lays a tile
- Remove LSL icons after using its ability
- Show available hexes to token after both tiles have been laid
- Minor performance improvement
@Zwergenpunk, this may also fix CZ.
**Please validate against all games before deploying in case their is an edge case I missed where its valid to not have an ability**
=> [1846] Fix LSL invalid tile lay

lib/engine/game/g_1860/step/track.rb
Fixes #4029 
I was too conservative in calculating what hexes could be upgraded.
This should a very safe change, since it only affects the UI. If anything, more hexes than needed will be un-greyed for the lay tile action. The validation of the tile being laid, however, has not been changed at all.
**Examples (BHI&R has a 3+2 train)**
Before (Ryde is greyed out)
After (Ryde is available for an upgrade)
Showing that an upgrade is now possible:
=> 1860: fix available_hex for upgrades

lib/engine/game/g_18_sj.rb
GKB gave 50 bonus every time it was used, instead of decreasing.
So too much money was received.
If games are broken by this, it cannot be fixed. So delete, pin or
archive them.
=> 18SJ: Correct GKB revenue (fixes #3822)

lib/engine/game/g_18_sj.rb
The main line connection did only check edges, not paths.
If games break by this they cannot be fixed as that means an illegal tile lay has been made. So pin, delete or archive those games.
=> 18SJ: Improve main line connection check (fixes #3869)

lib/engine/game/g_18_sj.rb, lib/engine/step/g_18_sj/special_buy_train.rb
18SJ needed its own special train buy to add the needed checks.
If this break any game delete, pin or archive as usual. Cannot fix via migration as the bug means a corporation might gets to act even though it should have been closed.
Fixes #3437
=> 18SJ: Fix bug that caused nationalization to be dealyed (fixes #3437)

assets/app/view/game/spreadsheet.rb, public/assets/main.css
- table split into corporations and player details, to easily render bank & upcoming trains cards next to player details which better utilizes screen space (closes #2804)
- subtle row highlighting
- toggle visibility of not floated corporations
- zebra styling simplified
- slimmer player columns, no wiggling on delta/total toggle
Visibility toggling of not floated corporations also hides merged ones (cf. [18Mex](https://18xx.games/game/20831), [1828](https://18xx.games/game/27831)). I’m not sure if "floated"/"all" is precise (enough). Additionally the link might be better placed above SYM.
ante
post
all corps
not floated hidden, PW row highlighted
=> spreadsheet usability/cleanup

assets/app/view/game_page.rb
Stop-gap. Perfect solution would be to save scroll position for each tab, which might be especially useful on mobile.
=> scroll to top when anchor changes

assets/app/view/game/route_selector.rb, lib/engine/game/base.rb, lib/engine/game/g_1849/game.rb, lib/engine/route.rb
Some notes:
- I changed the header "Stops" to "Used" to make it more generic across titles. Some titles (none implemented yet) have both hex trains and number-of-stops trains so I didn't want to assume all trains had the same sort of resource consumption.
- I'm not familiar with all the implemented titles, so I only changed the display for 1849. It seems to be the only game with hex trains. Other games will continue to generically display number of stops, which is not a regression. Games with weird trains (e.g., ones that care about halts) may want to write their own `route_cost_str`.
- Hex distance is displayed with an H suffix (e.g., `3H`) so you can glance at it and be sure that hexes are being counted. This would probably become more important if/when we implement titles with multiple …
=> In route selection, display hexes used for hex trains (#3523)

lib/engine/config/game/g_18_cz.rb
closes https://github.com/tobymao/18xx/issues/4071
`float_excludes_market` isn't included on small corps, since you have to buy the 50% share first anyway
Using the [testcase](https://gist.github.com/Maxwell-Frank/684d8cc94f1a68fc88c2099e4cda3ae0) in that issue, the `BY` is no longer floated (which is what we expect)
=> [18CZ] float when 50% in player hands

assets/app/view/game/game_info.rb
=> Nicer layout of trains-remaining table

lib/engine/player_info.rb
fixes #4059
Due to https://github.com/tobymao/18xx/blob/87568900957bc4e4cda677be11629d53e58f3f1d/assets/app/view/game/spreadsheet.rb#L104 rounds are only rendered if values changed from last round. Therefore some rounds are gone in the 2nd screenshot each.
Caveat: I don’t know if any other games are affected as well.
[1817NA](https://18xx.games/game/22282)
ante
post
[1867](https://18xx.games/game/23010#spreadsheet)
ante
post
=> add round_no to AR and MR

assets/app/view/game_page.rb
fixes #4068
`+` on qwerty == `Shift + =`
=> fix + hotkey on qwerty

assets/app/view/game/part/track_offboard.rb, lib/engine/config/game/g_1822.rb, lib/engine/game/g_1822.rb, lib/engine/step/g_1822/minor_acquisition.rb, lib/engine/step/g_1822/pending_token.rb, lib/engine/step/g_1822/token.rb, lib/engine/step/g_1822/track.rb, lib/engine/step/g_1822/tracker.rb, lib/engine/step/tokener.rb
- Only one of the 2 tracks connecting Merthyr Tydfil and Pontypool can be used each OR.
- Lay a yellow tile on London counts as an upgrade. In the real game, this is a wooden token you flip.
- A corporation now can have more than one token in London.
- English channel, must have connection to France to be able to run train to english channel. France doesnt count as a stop.
- When upgrading english channel to brown, there are 2 lanes to france. Upgrade the france tile to a tile with 2 lanes as well.
- Fixed off board graphics to handle lanes.
- Exposed the parameter from city.place_token "check_tokenable: true" in the tokener.place_token method. I need to bypass the check if a corporation already have a token on a tile. In London you can have multiple tokens.
- Minor 14, this minor shares …
=> [1822] English channel and Minor 14

assets/app/view/game/part/track_offboard.rb
If you have lanes in an offboard the all clumped together in center of the edge. This fix changes them to allign with the rest of the lane code.
=> Fix so lanes shows correctly on offboards

lib/engine/corporation.rb, lib/engine/game/g_18_cz.rb, lib/engine/stock_market.rb
Adds the original par value to the corporation (Maybe some other games need the property as well)
closes #4073
=> [18CZ] Add original par price to corporation model, use when floating companies

assets/app/view/game_page.rb, assets/vendor/polyfill.js
Only downside to this minHeight-hack is the ever-present vertical scroll bar on desktops. A small price to pay for a consistent game menu position.
=> scroll to top & game_menu into view on game load / tab change

lib/engine/graph.rb, lib/engine/part/node.rb
1873 has special requirements for the Graph:
* RR corps have to ignore normal-gauge track when laying tiles and tokens
* private mines need to ignore tokens when laying lines and calculating connectivity to the state railroad track (normal-gauge)
* private mines need to trace track starting from their home hex even though they have no tokens
Engine::Graph now supports three new options: home_as_token, no_blocking, and skip_track to support this
Engine::Part::Node now has a skip_track option to support this
=> Add options to graph and node for 1873

assets/app/view/game_page.rb
This adds autofocus for all (regular) browsers on game page load, after tab change and button click (or other actions triggering postpatch). After merge hotkeys should function from the get-go and even when a clicked button disappears (history start/end e.g., which autofocussed `body` until now).
If the active element is an input, hotkeys are still ignored. [chatbar, price input for train etc.]
fixes #4109
=> autofocus game content

assets/app/view/game/bank.rb, assets/app/view/game/game_info.rb, assets/app/view/game/spreadsheet.rb, public/assets/main.css
Triggered by [18CZ’s upcoming trains card](https://github.com/tobymao/18xx/commit/ef4ea392f8778ab2b04947637783a993c068476d#r47411082) (incl. discussion with dfannius about these changes).
The usual: margins, alignments, some vestiges removed, some minor code changes etc.
[1817NA](https://18xx.games/game/26939)
ante
post
[18CZ](https://18xx.games/game/29230)
ante
post
I also added row highlighting on hover to these cards which might be useful in some cases:
game info
ante
post
=> bank / upcoming trains / game info cleanup

assets/app/view/game/spreadsheet.rb
Due to `else` (L158) of `if hist[x]` checking `hist.empty?` beforehand seems obsolete. Additionally it looks nicer if all cells of a row have a background-color.
ante
post
=> or_history rendering empty history

assets/app/view/game_page.rb
I modified game_page for 1873 to display Round::Merger if there is a "merge" action during a SR. This breaks 1828. Reverting this change.
Fixes #4119
=> Back out of stock round merger change

assets/app/view/game/round/auction.rb, lib/engine/game/g_1828/step/waterfall_auction.rb, lib/engine/step/g_18_cz/draft.rb, spec/fixtures/18CZ/hs_gwurdqhs_1613616655.json
We now use the tiered auctions of 1828, but I refactored to now have a boolean flag but the grouped companies as function
=> 18CZ Improved Draft Experience

assets/app/view/game/game_info.rb
6H is included in 16H and include works for both string and array.
Also removed a leftover put
=> Fixed game_info for 1849

lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_18_cz.rb, lib/engine/game/g_18_mag/game.rb, lib/engine/operator.rb, lib/engine/phase.rb, lib/engine/step/train.rb
Fixes issue when the same corporation that buys the 12H and is closed by the Messina Earthquake.
Ran against the 2/21 db without any failures.
=> Reorder train purchase operations, so that the train is purchased before events are triggered
