tobymao/18xx

lib/engine/game/g_18_mex/game.rb
lib/engine/game/g_18_mex/step/special_track.rb

I have a local migration for this that fixes 55/60 of the broken cases. The last 5 can't be fixed by that migration and are all finished anyway; they'll need more fixing anyway for the changes I have in progress for the [rest of the issues I'm working on](https://github.com/tobymao/18xx/issues?q=is%3Aopen+is%3Aissue+assignee%3Amichaeljb+label%3A%22ability+timing%22).

18MEX remove P2's ability if Copper Canyon is laid [Fixes #2855]

---

lib/engine/game/g_1860/round/operating.rb
lib/engine/game/g_1860/step/dividend.rb

Move bankruptcy check out of the process_dividend method and into the Round::after_operating method.
This avoids issues with "auto" dividends that causes bankruptcies.
Fixes #4136

1860: move bankruptcy check out of dividend step

---

assets/app/view/game/stock_market.rb

Bank and legend stay in place while grid is scrollable horizontally:
Legend inline and ordered by appearance in market (left to right & top to bottom, reversed if not 1d). This should work better than before for most titles.
ante
post

stock market: scroll grid only, horizontal and ordered legend

---

assets/app/view/game/stock_market.rb

Thanks for the `compact!`, but because types in `types_in_market` should always be a subset of types in `type_text` we can just get rid of the `unless`. If there’s no text available [=> text = nil] the color box/key and an empty div will be rendered. I’d consider this QA ;-)

remove unless & compact

---

assets/app/view/game/part/reservation.rb

closes #4152 
CZ: ATE in E9 before
after
--
1882: QLL in J10 before
after
1830's erie still looks fine

Fit reservation text into OO tiles

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/special_choose.rb
lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1822/step/track.rb
lib/engine/game/g_1822/step/tracker.rb
lib/engine/step/acquire_company.rb

- I move the override track code into a tracker.rb where i override the gerneric track code. This to make a special_track which uses this as well.
- P2 Remove Small Station. You can lay a plain yellow tile on a white town, or you can upgrade to a plain tile of the next color to remove the town. I had to work around all the track checks here. User have to verify this him/her self to make sure the track lay is correct.
- P8 Mountain/Hill Discount. I had to make a special_choose step. After you acquired this private you have to choose which of the 2 abilities you want to have. Either a one time use of a free track lay on a mountain, hill or swamp. Or you choose to have a passive tile discount of hills and mountains
- P10 River/Estuary Discount. Here the corporation have two uses of a free …

[1822] Track lay privates

---

lib/engine/game/g_1861/game.rb
public/logos/1861/MK.svg
public/logos/1861/MKV.svg

matches the colors of MK and MKV in published editions of the game.
https://github.com/tobymao/18xx/issues/4169
original edition: https://boardgamegeek.com/image/167006/1861-railways-russian-empire
1861/1867 edition: https://boardgamegeek.com/image/5033873/18611867

1861: Changes colors of MK and MKV companies 

---

assets/app/view/game/round/stock.rb
lib/engine/action/destination_connection.rb
lib/engine/game/base.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/destinate.rb
lib/engine/game/g_1873/step/form.rb
lib/engine/game/g_1873/step/track.rb
lib/engine/step/tracker.rb

* UI::Round::Stock - allow minors as parameter to Action::Merge
* Action::DestinationConnection - allow minors as parameters
* Step::Tracker - call game method for graph to check and clear
* Game::Base - use init_graph method instead of calling Graph.new directly; implement method for above
1873 implementation:
* fix public mine formation via SR view
* independent mines can lay one tile if not connected
* check for independent mine connection after every tile lay (mine or RR)
* concession route tile lays for concession company
* reserving tiles when other company lays on concession route
* reimburse owner when laying on other company's concession route (and back charge concession company when they complete the concession route)
* limit concession route tile lays to …

1873: tile laying rules

---

Rakefile

Migrating down to 0 is quite annoying due to wiping the DB in the process. This allows migrating down to any previous version to test migration scripts e.g.
[no or bogus argument => version = 0 == previous behavior]

allow rake dev_down to specific version

---

assets/app/view/game_page.rb

fixes #4180 
enabled:
[ymmv, unicode yadda yadda]
disabled: visualization by omission ;-)

game menu: show status of programmed actions

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/issue_shares.rb

- Do not include issuable shares in the corporations buying power. You cant isse shares during an emergency train buy
- Fix a bug when taking a loan during emergency train buy
- Dont log skipped issue shares step on minor corporations

[1822] Buying power and loans

---

lib/engine/game/g_1822/game.rb

- On the Info page i now use the timeline to show all the companies in a condensed form split on minors, concessions and privates.
fixes #4197

[1822] Better display of decks

---

lib/engine/game/g_18_cz/game.rb

Use "SR.OR" instead of "13 ORs"
Generic to variants

[18CZ] use standard round notation for endgame trigger

---

lib/engine/game/g_18_cz/game.rb

[testcase - full game](https://gist.github.com/benjaminxscott/67d6827b148d7439576e2296d8d5d220)
The production game doesn't have a yellow value, since it's impossible to lay the tiles in yellow
after this change:

[18CZ] remove unused yellow value from large offboards

---

lib/engine/game/g_1822/game.rb

- If you select the towns and city in a specific order you could go around the check i had for the L-train to only use one city token once. Modified it a bit to stop all different cases.
This shouldnt break any games, since the check is when you select the route not under process_run_routes.

[1822] Local trains can only use same token once

---

lib/engine/game/g_1822/game.rb

- Uses the status_str on the corporation to see the market value of the minors. As joey pointed out its a little hard to se under all the stacks of minor token in the stock market where one specific minors value is. This is actually true for the physical game as well, its always hard to se in in which stack of minors the one you looking for.
fixes #4217

[1822] Minors market value

---

lib/engine/game/g_1822/game.rb

- When simple logos was turned on, you didnt see which tokens where the destination tokens.
fixes #4235

[1822] Destination Tokens when Simple Logos is turned on

---

assets/app/view/game/part/location_name.rb
assets/app/view/game/part/revenue.rb
assets/app/view/game/part/small_item.rb

- Add bottom-left corner as another location for wide small items on pointy maps
- Nudge multi-revenue up on top and down on bottom a bit on pointy maps
- Add down 24 as a location name option and fix weighting to be better representative of where the text actually goes
I compared my local version vs 18xx.games base maps for 1817, 1822, 1830, 1846, 1860, 1861, 1867, 1889, 18AL, 18Chesapeake, 18CZ, 18CO, and 18MEX and all looked the same to me (18MEX actually a bit better).

1828: Fix tile rendering for Altoona and Virginia Coalfields.

---

lib/engine/game/g_1882/game.rb

Remove the word "currently" from log stating which is the NWR train.

[1882] Fix minor typo in logging in init_train_handler.

---

lib/engine/game/g_1822/game.rb

- No need to show the corporations in the stock round in phase 1.
- Improved the button text on the tax haven private to show the price of the share as well.
fixes #4196

[1822] Dont show corporations in phase 1

---

assets/app/view/game/game_info.rb
lib/engine/game/g_1877/game.rb
lib/engine/game/g_18_chesapeake/game.rb
lib/engine/phase.rb

- prevent line breaks in sub-strings of event, train limit, train upgrade and status => line breaks after `,`
- remove empty events/status columns
- event legend ordered
- `=>` replaced by `:` or `→` [The arrow breaks up the gray quite nicely in some places.]
ante
post
ante
post

game info cleanup

---

lib/engine/game/g_1822/game.rb

- Move where the icons where placed to init_hexes so when the user presses the "Show Starting Map" the destination icons will also be showed.
fixes #4233

[1822] Starting map doesnt show destination icons

---

assets/app/view/game/round/choices.rb
assets/app/view/game_page.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/choices.rb
lib/engine/game/g_1822/step/choose.rb
lib/engine/round/choices.rb

- I first did the private M&GNR as an ability you can choose during the stockround. This is a choice you should have between stock round and operation round, but before player order is determined. You must be able to use this power if you won the bid for it during the current stock round.
- View::Game::Round::Choices. Made a very simple round view which only shows the Choose component.
- View::GamePage. Added the round view above to the case where its selected what view to show.
- Engine::Round::Choices. Added a base round for the choices view.
- Added a Choices round and a Choose step to have the player choose if he want to double his cash before the turn order is determined.
fixes #4241
fixes #4242
This will break all games where the M&GNR …

[1822] Timing was wrong on M&GNR

---

lib/engine/game/g_1817_wo/game.rb
lib/engine/game/g_1817_wo/step/buy_sell_par_shares.rb
lib/engine/game/g_1817_wo/step/home_token.rb

The problem was that in the case when there is no choice for the size of the IPOed corporation nor any contest for the bid the home token (NZ) gets laid AFTER attempting to purchase tokens. The fix here is to add a hook to the HomeToken step in the stock round so that the second token can be laid then
Fixes #4189

Fixes #4189

---

assets/app/view/game/alternate_corporations.rb
assets/app/view/game/buy_trains.rb
assets/app/view/game/round/operating.rb
lib/engine/action/buy_train.rb
lib/engine/action/scrap_train.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/concession_auction.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1873/step/form.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_1873/step/track.rb

* UI::BuyTrain - changes to support scrapping trains, buying trains for subsidiary mines, and paying maintenance upon purchase
* UI::Operating - small change to support scrapping trains via new action
* Action:: BuyTrain - new parameters for "slots" and "extra_due" (first for subsidiary mines, second for when seller pays maintenance costs)
* Action::ScrapTrain - new action to support scrapping trains during the buy_trains step
Changes to 1873 code:
* Various bug fixes
* Calculation of mine revenue (indie and public)
* Calculation of maintenance costs for all
* Dividend step to take maintenance costs and mine revenue into account
* Implement MHE operation
* Major change to buy_train to implement all the various and sundry 1873 train purchase rules, including:
* …

1873: production, dividends, buying trains

---

assets/app/view/game/buy_trains.rb

I changed the method name at one point, but missed a call.

fix wrong method for slots in UI:buy_train

---

assets/app/view/game/spreadsheet.rb

sorting by best train (#4113) was just a stop-gap, this fixes #4112 completely

spreadsheet: sort by all trains

---

assets/app/view/game/part/city.rb
assets/app/view/game/part/city_slot.rb

Adds a shadow around the extra token so that it's possible to distinguish it

Make the "extra token" visually distinct from a normal token

---

lib/engine/game/g_18_co/game.rb
lib/engine/game/g_18_co/step/special_track.rb

- removes villages from hexes array for GJGR company
- removed connected check as in the rules it states the small village does not need to be connected
fixes #4208 
Here's json for a game to test: https://gist.github.com/underhilllabs/a1e430bf314cd6fbdeb8cb2e1c2673ff

[18CO] removes villages from hexes array for GJGR company #4208

---

assets/app/view/game/alternate_corporations.rb
assets/app/view/game/buy_corporation.rb
assets/app/view/game/buy_value_input.rb
lib/engine/action/buy_corporation.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_mine.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/convert.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_18_cz/step/buy_corporation.rb

* Add voluntary closing of indie mines
* Add 10 share conversion for RRs and 5 and 10 share conversions for public mines
* Add mine purchasing for public mines
* Deal with president changes upon purchase of compulsory train for concessions (RRs)
Common files:
* modified UI::buy_corporation and UI::BuyValueInput (used by 18CZ) to make it general enough to buy minors (mines)
* modified 18CZ::Step::BuyCorporation to add the methods needed for above
* modified Action::BuyCorporation to allow purchase of minors

1873: share conversion, buying and closing mines

---

assets/app/view/game/part/assignments.rb
assets/app/view/game/part/city.rb
assets/app/view/game/part/small_item.rb
lib/engine/game/base.rb
lib/engine/game/g_1870/game.rb
lib/engine/operator.rb

Trying to split the connection run PR. The rest (using auto actions) will come when this one is merged.
This is a bit complicated because some tiles are really busy and I had to create new was for assignments to be rendered:

1870: Show destinations on map

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/meta.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/route.rb
lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1822/step/tracker.rb

- 6 new minors, not much change except the corporations and company array
- P19 Avonside Engine Company. Added a permanent L train, ive prepered for this so just needed to add some code for english channel which it cant run. And you cant attach a pullman to it.
- P20 Canterbury & Whitstable Railway. Same as P15 but with phase x 5. Refactored the player to hold the cash into a hash instead to hold both privates cash.
- P21 Humber Suspension Bridge Company. 2 free tile lay on the Hull / Grimby hexes. You can lay both tiles even if its a minor. And one of the tile lay may be an upgrade.
- Added a few more constants to help with setup. This is also preperation to have the 1822MRS/NRS easily override the base 1822 class.
- 1822+ categorized the privates into 3 stacks and each stack is …

[1822] 1822+ expansion

---

assets/app/view/game/spreadsheet.rb
public/assets/main.css

part 6 of #4317
Fixed width of 5rem for all player columns would be simpler, but would also waste space – a lot if player names are short and companies per player are few.

spreadsheet: align column widths

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/special_track.rb

[1822] P2 - Middleton Railway
- Saw in slack that 1856 did tile lay where you remove a town. Had a looked and took some code from there to get the P2 to work as intended with path checks.
This have no effect on current games since the check is only when you rotate the tile in the ui and not in process_lay_tile.

[1822] P2 - Middleton Railway

---

lib/engine/game/g_1822/step/destination_token.rb
lib/engine/game/g_1822/step/token.rb

- Added a check when you press skip to see if we have a connection to the destination. If we do you cant skip this step. The check is wrapped around a game.loading block.
- Removed the check in the token step where you check if you try to token the destination hex.
fixes #4318
This have no effect on current games since the check is in a game.loading block. Only affects new actions.

[1822] Destination token

---

lib/engine/game/g_1817/round/operating.rb
lib/engine/game/g_1817_wo/round/operating.rb
lib/engine/game/g_1856/round/operating.rb
lib/engine/game/g_1856/step/loan.rb
lib/engine/game/g_18_fl/step/special_token.rb
lib/engine/round/base.rb

I created this method for #4301 because otherwise the line would be too big. Then I realised it's also used in a bunch of other places, so I thought it would be nice to have them all together.
I'm not sure the name of the method is very auto-explanatory. If someone has a better suggestion...

Add step_passed method to Round, to replace a line that's used often

---

lib/engine/game/g_1822/step/buy_sell_par_shares.rb

Bids weren't being tracks meaning that the auto-pass wouldn't disengage.

1822 bids should stop auto actions

---

assets/app/view/game/round/operating.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/price_protection.rb

When there's an ebuy, if shares are sold, the president can also protect
them. Had to add the step to the OR and that required changing some
assumptions.

1870: Add the PriceProtection step to the OR

---

assets/app/view/game/part/revenue.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb

- View::Game::Part::Revenue. Jen suggested to do an exception for six city tiles to move the revenue into the center of the tile. Since as it is now you cant see the revenue value of the tile. This is a very specific code for the specific tile London in 1822. If this not ok, i will remove the code.
- Added Railway to L&R's name
- Added PXX- to all private company names. This should now be a comprimise to all suggestions :)
- Fixed so you see the correct number of removed L trains after a stock round.
fixes #4198
fixes #4317
This have no effect on current games.

[1822] Small issues

---

assets/app/view/game/part/track_node_path.rb
lib/engine/game/g_1822/game.rb

- View::Game::Part::TrackNodePath. Made the terminal arrow a little bit narrower and decreased the height a little bit. Many offboard cities have 2 slots, the arrows was under the cities and it looked like it had a normal connection. Ive looked att a few other games with an offboard city and terminal arrow. And it looks good with only one city as well.
- Change a little bit on the map around Mid Wales
fixes #4327
This have no effect on current games.

[1822] Mid Wales

---

assets/app/view/game/round/operating.rb
assets/app/view/game/switch_trains.rb
lib/engine/action/switch_trains.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/convert.rb
lib/engine/game/g_1873/step/reassign_switcher.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_1873/step/token.rb
lib/engine/game/g_1873/step/track.rb
lib/engine/graph.rb

* New step, action and UI for a public mine to move switchers around prior to production (per the rules)
* Add crazy 1873 tokening rules:
** tokens not used in running a route get flipped to the inactive side (except for those on its concession route)
** RR can replace an inactive token from another RR with it's own for half-price
** Running routes and tokening treat inactive tokens normally
** Laying tiles ignore inactive tokens from the corp laying the tile (yes, a new graph, thanks for asking)
** Can't token out a "village" on a concession route before the RR with the concession runs the first time
* new parameter to graph to restrict tokens for a company
* new action and UI: switch_trains

1873 Reassign switchers, Tokening

---

assets/app/view/user.rb

No need for multiple methods …
Order of red_logo and simple_logos changed, because general options should be rendered before game related ones.

profile: dedicated methods => render_checkbox

---

assets/app/view/game/dividend.rb
lib/engine/game/g_1836_jr30/game.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_sj/game.rb

In 18CZ and 1836jr is a unneeded line break
Before:
After:

Added &nbsp; to currency formats with space

---

assets/app/view/game/spreadsheet.rb

#4322 didn’t account for 5-digit currency strings with nbsp;s …

spreadsheet: fix column width / alignment on mobile

---

assets/app/lib/storage.rb
assets/app/view/game/map_controls.rb
assets/app/view/game/part/city_slot.rb

This allows overriding show_player_colors per title. For now in parallel to the general option, so it’s still just one click to show/hide player colors for all titles – unless one had configured many titles beforehand.
I wouldn’t mind getting rid of the general option completely, because most people (on Slack back then) said they only use it on select titles anyway.
[Addition to lib/storage and & due to specs failing otherwise.]
PS: The same MO would work for #4278

show player colors per title

---

lib/engine/game/g_1817/step/buy_sell_par_shares.rb
lib/engine/game/g_1828/game.rb
lib/engine/game/g_1828/step/buy_sell_par_shares.rb
lib/engine/game/g_1828/step/exchange.rb
lib/engine/game/g_1828/step/route.rb
lib/engine/game/g_1828/step/special_track.rb
lib/engine/game/g_1828/step/swap_train.rb
lib/engine/game/g_1828/step/track.rb
lib/engine/game/g_1849/step/buy_sell_par_shares.rb
lib/engine/game/g_1860/step/buy_sell_par_shares.rb
lib/engine/game/g_1870/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1877/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/par_and_buy_actions.rb
lib/engine/round/base.rb
lib/engine/step/buy_sell_par_shares.rb

- Move buy_sell_par_share step's @current_actions array to round, so it can be used by other steps.
- Refactor 1828 steps to leverage current_actions and track round variables
- Small refactoring to buy_sell_par_share::can_buy_shares? for a 5% performance improvement
- Don't log skipping the swap train step for non-systems
Games 29466, 28559, and 27021 are expected failures due to illegal tile lays.

1828: Refactorings to use round variables

---

lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb
lib/engine/game/g_1893/step/starting_package_initial_auction.rb

- Passers during SR1 and/or initial draft, cannot act again
during SR1 and/or initial draft
- If all players have passed during initial draft, the draft
is completed.
- First passer during SR1 and/or initial draft will be priority
dealer during SR2
- ADSK sell does now give money and set correct sell status
- Use correct logo for open cities
- Minor corrections of texts

1893: Corrections of errors discovered during test

---

assets/app/lib/settings.rb
assets/app/view/game/corporation.rb
assets/app/view/game/entity_list.rb
assets/app/view/game/hex.rb
assets/app/view/game/map_controls.rb
assets/app/view/game/part/city_slot.rb
assets/app/view/game/player.rb
assets/app/view/game/stock_market.rb
assets/app/view/game/tile.rb
assets/app/view/game/token.rb
assets/app/view/game/token_selector.rb
assets/app/view/user.rb
models/user.rb
spec/assets/app/view/game/part/slot_spec.rb

In addition to adding a simple_logos button to map controls (closes #4278) this also allows saving options for location names and hex coords _per title_. (Mainly because it’s more code efficient that way, but I guess some people might appreciate it.)
Option for simple_logos in profile is gone.
Default settings are the same as before. All affected buttons are designed to toggle the status of both the per-title option _and_ the corresponding default option. This way it’s possible to toggle all options in any game and save title specific settings in any game of that title.

save map options per title

---

lib/engine/game/g_18_neb/game.rb

Adds custom stock_round method to 18Neb with Engine::Step::HomeToken so that Local Railroad Corporations can set home token when they float in phase 5.

[18Neb] adds HomeToken step to Stock Round in 18Neb

---

assets/app/view/game/game_info.rb
lib/engine/game/g_18_ms/game.rb

Adds Progress bar for 18 MS
The train icons are in 18CZ for export, but I think it works for 18MS as well for the rusting. 
With OR 11 optional rule there is one more OR in the progress bar
closes #4392

Show Progressbar for 18MS

---

lib/engine/game/g_1822/game.rb

[1822] E-trains
- Changed the distance of the train to just have a number instead of a array with nodes. Doesnt use the normal revenue calculation so no need for the array.
fixes #4383
This have no effect on current games.

[1822] E-trains

---

lib/engine/game/g_1822/game.rb

- Missed Q30's city name.
- Some more information on minor 14 and its home token cost.
- Removed the dubble company id when you start 1822+.
On #4376 it solves 2.

[1822] Minor changes

---

lib/engine/game/g_1822/game.rb

-  Company should not be allowed to cross-buy using director's contribution during EMR.
fixes #4333

[1822] E-buy train

---

public/assets/main.css

… and any other svgs. fixes #4430
It might affect other browsers, too, hence the browser prefixes.

mobile browsers: prevent copy popup on route selection

---

lib/engine/corporation.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb

- Engine::Corporation. Moved reservation_color from attr_reader to attr_accessor. Reason for this it to be able to set the reservation color of the minors which is in the bid box. This so you easly can see them on the map.
- When we refill the bank minors, also set the reservation color of them so you can see them on the map.
fixes #4328
On #4376 it solves 1.
This change doesnt affect any of the current inprogress games.

[1822] Reservation color

---

lib/engine/game/g_1822/game.rb

- If its a market share tax haven buys the money should go to the bank.
fixes #4443
This change might affect games that bought a market share and then spent the money the corporation got.

[1822] Tax haven market share

---

lib/engine/part/node.rb
lib/engine/part/path.rb
spec/fixtures/18MEX/README.md

This also adds the README.md that was supposed to be added with the hotseat game fixture in 18MEX but didn't get added succesfully

use .dup on visited_edges to prevent sideeffects from branchs

---

lib/engine/game/g_1822/game.rb

fixes #4437
This change doesnt affect any of the current inprogress games.

[1822] Incorrect revenue for cardiff brown tile

---

lib/engine/graph.rb
lib/engine/part/node.rb
lib/engine/part/path.rb

- Engine::Part::Node. Added a new method graph_walk. I opted to make a new method just for the walk called from the graph. Reason for this is in the first step i didnt want to mess with the walk which is called from different games in example 1856 and 1860.
- Engine::Part::Path. Added a new method graph_walk. Reason for the new method is the same as above. The orginal walk is aslo called when you lay a tile with the chain parameter. I didnt want to touch theese in the first round of refactor.
- Engine::Graph. Calling the new graph_walk method. path_node is a mutable hash to pass down if we are starting from multiple token nodes. No need to traverse paths we already is done with.
- No changes here.
fixes #4346
fixes #4354
This have no effect on …

[1822] Refactor graph walk

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/stock_market.rb

- At the end of the stock round, if 100% of any company is in players hands the stock market token for each such company rises one space vertically on the stock market, if possible. If the token is already at the top of the chart, it moves diagonally one space down to the right.
fixes #4343
This change might affect games that bought a share with the wrong price.

[1822] Sold-out companies

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/route.rb

[1822] Pullman Trains
- You shouldnt be able to attach a pullman to a e-train.
fixes #4453
This change might affect games if someone attached a pullman to an e-train.

[1822] Pullman Trains

---

assets/app/view/game/company.rb
assets/app/view/game/round/auction.rb
assets/app/view/game/round/stock.rb
assets/app/view/game_page.rb

closes #4385
Table instead of string. Bidding players are highlighted as follows:
map: player colors ✅ / on
=> colors configured in profile are used
map: player colors ❌ / off (default) && user participating in game
=> currently winning bid = green, bidding = yellow

highlight bidding players

---

assets/app/view/game/buy_trains.rb
assets/app/view/game/route_selector.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_1873/step/token.rb
lib/engine/game/g_1873/step/track.rb
lib/engine/graph.rb
lib/engine/train.rb

This is one of the big ones for 1873.
* RRs own "supertrains", each of which has 1-n "subtrains". This is transparent to the player.
* Numerous 1873-specific routing rules, some of which use the subtrain/supertrain distinction
* 1873-specific revenue calculation (revenue centers/mines/factories only count once, no matter how many trains hit them)
* Unlimited subtrain diesels per supertrain diesel. These subtrains are doled out automatically and added tot he route_selector as needed.
* Different routing rules for diesels.
* Diesels can reuse track used by non-diesels
* Only 1 Diesel per RR. Can't be scrapped.
* Diesels only become available starting with the first full set of ORs after a 5T/5M is bought
* Engine::Graph - minor change to allow multiple graphs to use …

1873: Routes

---

assets/app/view/game/spreadsheet.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_18_cz/game.rb

- corporation size added (only shown when there are different sizes of corps available) – fixes #2152 (body text mentions corp size)
- include minors/president-status when sorting player column – fixes #3799
- shares == 0 => hidden
- operating order == 0 => hidden
- operated => grayed out instead of *; alignment changed to right
- shorts sorted between longs and 0
- sort order toggles only when currently sorted column is sorted again – instead of when changing sort column
- sort order indicator (arrow) moved to left of column header, because it gets hidden too often due to width limit of player columns
- or_history right aligned & a tad more padding
tl;dr

spreadsheet sort enhancements

---

assets/app/view/game/player.rb
lib/engine/game/base.rb

@crericha I fixed the issue that the priority for next SR is shown in the current SR. The passing order is only acknowledged for first_pass.
I checked for 1828 and 18CZ and both work as expected.

Fixed Next SR Position for not Pass 

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/step/buy_train.rb

Adjusted the buy_train presidency_contribution to show the correct infos for 18cz.
Added a global constant to allow selling shares, which will then hide all the selling shares information.
Also needed to add a overload for the cheapest price since in 18CZ the cheapest variant of a type is needed.
closes #4100

[18CZ] Optimized EMR Info

---

assets/app/view/game/button/buy_share.rb
assets/app/view/game/buy_sell_shares.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_mine.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/concession_auction.rb
lib/engine/game/g_1873/step/convert.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1873/step/draft.rb
lib/engine/game/g_1873/step/form.rb
lib/engine/game/g_1873/step/premium.rb
lib/engine/game/g_1873/step/reassign_switcher.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_1873/step/token.rb
lib/engine/game/g_1873/step/track.rb

I apologize for the number of files in this - in addition to adding the insolvency and end of game rules, a playthrough to test these things found a fair number of  bugs that needed to be fixed.
- UI: buy_sell_shares and UI::Button:buy_share - added ability to buy a bundle instead of a single share. This is needed because even though the presidency in a 10-share corp is only 10%, you are required to buy at least two when taking a corp out of receivership.
This PR represents full functionality for 1873. I believe the game is completely playable (latent bugs notwithstanding), but it needs a few usability tweaks before it is ready for the masses.

1873: insolvency and end game

---

lib/engine/game/g_1822/step/pending_token.rb

- 14 should only be able to place its token in london.
fixes #4478
This change might affect games if someone placed 14 somewhere else.

[1822] 14 not restricted to London

---

lib/engine/game/g_1846/step/assign.rb

With the old code, if 1) the steamboat company is owned by the player that owns the corporation
that owns the meat packing company (MPC), and 2) that corporation is operating first,
and 3) the player passes on assigning the steamboat company at the beginning of
the round, then that corporation will not be able to assign the meat packing
company, as the Assign step is already marked as passed, and is not unpassed
until `next_entity!` is called
[Fixes #3996]

[1846, bug fix] don't set passed to true in `G1846::Step::Assign#pass!`

---

lib/engine.rb

fixes `/map/18cz` going to 1817
also get rid of a duplicate `.uniq`

make fuzzy matching on /tiles and /map case insensitive

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/dividend.rb

- Clear all cash from a corporation when it floats in phase 6. Then it will get the full cap.
- Make sure that its only ipo shares which payes money to the corporation.
fixes #4476
fixes #4506
This change might affect games if they used the money the corporation got extra from incorrect floating or revenue.

[1822] Phase 6 floated companies

---

lib/engine/step/tracker.rb

The OO tile can have SC, this causes two tokens
to be present on the tile in the token choice condition which must be selected which token goes where.
fixes #4379

1882: Fix NWR private and OO tile if it already has a token on it

---

lib/engine/game/g_1822/game.rb

- Renamed IPO to Treasury
fixes #4536
This change does not affect any of the currect games.

[1822] Treasury

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_mrs.rb
lib/engine/game/g_1822_mrs/game.rb
lib/engine/game/g_1822_mrs/meta.rb

This is the 1822 Medium Regional Scenario
- Inherited the 1822 base class.
- Changes cert limit, starting cash, map, tile and train constants.
- Changes the cost for upgrade L -> 2, first one to do it costs £80. After we entered phase 2 it costs £70.
- Advanced variant where you play with P1-12 and start with M14 in bid box 1.

[1822MRS] 1822 Medium Regional Scenario

---

assets/app/view/game/auto.rb
lib/engine/action/program_merger_pass.rb
lib/engine/game/g_1817/step/acquire.rb
lib/engine/game/g_1817/step/conversion.rb
lib/engine/game/g_1867/step/merge.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/programmer_merger_pass.rb
spec/fixtures/1817NA/25363.json
spec/fixtures/1822/hs_lxemeslq_30797.json
spec/lib/engine/games/game_spec.rb

Can now specify differently for AR and MR.
Add option to fail-safe if other people start merging
fixes #4164
Fix the unit tests for auto-actions which actually didn't check
and fix specs and other breakages
(Will cause existing merger passes to stop, but will do so without issue)

Improve granulality of auto actions for mergers

---

lib/engine.rb
spec/lib/engine_spec.rb

- add individual words of the main title to the list of things to match (so
"Harzbahn" and "1873" both get compared instead of just "Harzbahn 1873")
- only sub `/^G?18/` on the class name (so "G1873" gets transformed to
both "1873" and "73" instead of just "73")
- add unit tests for closest_title() to cover weird cases like "Harzbahn 1873",
"18LA", and subclasses where the title is the base title plus more, like
"18Chesapeake: Off the Rails"
[Fixes #4583]

fix fuzzy matching so "1873" goes to "Harzbahn 1873" instead of "1870"

---

lib/engine/game/g_1822/game.rb

- When using a tilelay private, make sure to check discount as well.
fixes #4533
This change might affect the currect games.

[1822] P10 doesnt reduce track laying cost

---

lib/engine/game/g_1822/round/stock.rb

- Dont export a train when there is a bid on the last minor.
fixes #4569
This change might affect the currect games.

[1822] Train removed when bid on last minor

---

assets/app/view/game/part/icons.rb
assets/app/view/game/part/large_icons.rb
assets/app/view/game/tile.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_mine.rb
lib/engine/game/g_1873/step/draft.rb
lib/engine/part/icon.rb
lib/engine/tile.rb

Added a "large" flag to Engine::Part::Icon and support for it in Engine::Tile.
Added a new UI element: LargeIcons and modified UI::Part::Icons and UI::Tile to support it.
Large icons are ownable and the LargeIcons UI uses that to show player ownership ala Tokens.
Modified 1873 to use large icons for mines and factories.
**With player colors.**

1873: add and use large icons

---

assets/app/view/game/round/auction.rb
lib/engine/game/g_1873/step/draft.rb

Like 18Mag, it's very useful to show the map during the initial draft. Unlike 18Mag, minors aren't directly on offer so the UI::Round::Auction will call step.show_map if it exists.

1873: show map on starting draft

---

lib/engine.rb
lib/engine/game/g_1817_wo/meta.rb
spec/lib/engine_spec.rb

- match against `full_title` and `SUPERTITLE` (in addition to `title` and
`SUBTITLE`)
- once list of candidates is compiled, also use individual words from each
candidate (e.g., put "Wight" in the list for 1860)
- create `fuzzy_candidates` hash just once
- in `closest_title()`, don't upcase the given title if it matches a real
title (avoids doing unnecessary checks for "18Chesapeake" for example; old
code was converting it to "18CHESAPEAKE" then failing to find a match in the
initialized `fuzzy_titles`, so then it had to calculate the distance against
all candidate strings from all games)
- remove unnecessary period from end of 1817WO's location
- add a couple `closet_title()` specs for individual subtitle words

improve fuzzy matching

---

assets/app/view/game/part/location_name.rb
assets/app/view/game/part/town_dot.rb

- improve rendering of copper canyon on rotation 4
Generic change: If a location name is of length 12 (including whitespace), wrap it
addresses https://github.com/tobymao/18xx/issues/2442 (doesn't close)
Rotation 0 is still messed up, I tried tweaking [location weights](https://github.com/tobymao/18xx/blob/master/assets/app/view/game/part/location_name.rb#L21) but it didn't seem to help

[18MEX] improve copper canyon rendering

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/price_protection.rb

Price protection is supposed to happen kind of between presidency
change, so put the potentially-former president as the actor for price
protection to disallow it when there's a presidency change.
Fixes #4598

1870: Keep track of potentially-former president.

---

lib/engine/game/g_1822/step/buy_sell_par_shares.rb
lib/engine/game/g_1828/step/buy_sell_par_shares.rb
lib/engine/game/g_1830/game.rb
lib/engine/game/g_1830/meta.rb
lib/engine/game/g_1830/step/buy_sell_par_shares.rb
lib/engine/game/g_1849/step/buy_sell_par_shares.rb
lib/engine/game/g_1860/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1882/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares.rb
spec/fixtures/1830/26855.json

Added an option to use the other interpretation of the original Avalon Hill wording.
One of the fixtures actually depended on the old behavior so I enabled that option for it.

1830: No multiple brown buys from IPO by default (fixes #4456)

---

lib/engine/part/node.rb

This was requiring an N+1 train to find a route with N stops
Fixes #4645

Fix off-by-one bug on max_nodes of node.walk

---

lib/engine/game/g_1846/game.rb

Clarifies when corp token reservations go away, adds log msg
addresses #2021 somewhat
edit: initial PR also changed corp ability text, but I pulled that out

[1846] [18LA] clarify when token reservations go away

---

lib/engine/game/g_1824/game.rb
lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/round/merger.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/merger.rb
lib/engine/game/g_1893/step/potential_discard_trains_after_merge.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb

Added Merge step for AGV and HGK. This will either do an auto
merge if late phase, and/or give the possibility to vote if merge
should take place or not.
If merge - minors + private (in case of HGK) are merged into
AGV/HGK which floats. Resources moved to AGV/HGK. Reserved
shares are exchanged.
Added a discard trains step which is used as the director of
the floated merged corporation may discard any train.
Potential Merger round takes place betwee Stock Round and Operating
Round as well as between first OR and second OR in each turn.

1893: Complete merge actions

---

assets/app/lib/hex.rb
assets/app/view/game/hex.rb
assets/app/view/game/map.rb
assets/app/view/game/map_controls.rb
lib/engine/game/g_1817/step/special_track.rb
lib/engine/game/g_1822/step/dividend.rb
lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1824/step/dividend.rb
lib/engine/game/g_1856/step/dividend.rb
lib/engine/game/g_1860/step/dividend.rb
lib/engine/game/g_1870/step/special_track.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1882/step/special_nwr.rb
lib/engine/game/g_1889/step/special_track.rb
lib/engine/game/g_18_co/step/special_track.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb
lib/engine/game/g_18_mag/step/dividend.rb
lib/engine/operating_info.rb
lib/engine/round/operating.rb
lib/engine/step/dividend.rb
lib/engine/step/special_track.rb
lib/engine/step/track_lay_when_company_sold.rb
lib/engine/step/tracker.rb

Highlights tiles laid this turn. Also highlights last tiles laid for other corporations via the  the "Show Last Route and Track For" drop-down.
For tiles with a border, uses contrast instead of black for the highlight.

Highlight laid tiles

---

assets/app/app.rb

allows for descriptively named game json fixtures to be accessed
at `/fixture/<title>/<fixture_name>`
This is useful on #4588 where there are fixtures named to describe whether certain powers work or not

app routing: match game IDs to any string

---

assets/app/view/game/stock_market.rb

noticable on 2d-markets like 18SJ:
ante
post

market: fix width of cells with right border

---

assets/app/view/chat.rb
assets/app/view/game/game_log.rb

fixes #4656 – [fingers crossed](https://caniuse.com/input-autocomplete-onoff) …

prevent Safari from autocompleting chatbars

---

lib/engine/game/g_1860/game.rb

The Brading Harbour Company description had 'public' misspelt as
'pubilc'.

1860: Fix typo in private company description

---

lib/engine/game/g_1873/step/token.rb
lib/engine/game/g_1873/step/track.rb

Changed a method name a while back but missed one call.
Fixes #4662

1873: fix obsolete method name

---

lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/buy_train.rb
lib/engine/game/g_1893/step/dividend.rb

Some minor fixes in 1893:
1. Trains owned by minors cannot be bought by corporations
2. Shares in market does not bring dividend to corporation
3. 1893 is restrictive when it comes to tile lay/upgrade
4. Can at most buy one discounted train per turn
5. AGV/HGK should not be parrable - IPOed via merge
6. Leverkusen hex uses special tiles

1893: Various minor fixes

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_18_los_angeles/game.rb

More consistent terminology, distinguishing corporations' station tokens and private companies' revenue markers https://boardgamegeek.com/thread/2565191/article/36594885#36594885
Validated against all 1846/1846 2p/18LA games in the database.

1846: "tokens" to "markers" for event descriptions

---

lib/engine/game/g_1822/game.rb

Based on [rulebook](https://boardgamegeek.com/filepage/219065/1822-railways-great-britain-rules)
This minor does not seem to be present in the MRS/NRS variants, so no changes to those configs

[1822] capitalize minor name

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/route.rb
lib/engine/game/g_1873/step/track.rb

Fixes #4697 
Fixes #4700 
Also modified buy_train step to disable the "Pass" button for a compulsory train if and only if there is an affordable train from the bank (depot).

1873: fix maintenance when no trains; fix repayment of reimbursed track costs

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/route.rb

1873: use dup when scrapping trains; fix buy_train validation for switchers

---

lib/engine/game/g_1822/game.rb

- After a major company have floated, make sure its capitalization is switch back to incremental if was full for a little while during phase 6+.
fixes #4686
This shouldnt break any of the current games.

[1822] Purchase of redeemed treasury share in phase 6+

---

lib/engine/game/g_1870/step/track.rb

Fort Wort was not on the list, so I removed the list to avoid duplicating information.
This requires archiving games.

1870: Improve/simplify upgrade of P Hexes

---

lib/engine/game/g_1893/game.rb
lib/engine/game/stubs_are_restricted.rb

Hex L5/S6 has a 0 cost border that blocks building track
to that edge during yellow phase. The border does not affect
building to that edge from adjacent hex, nor does it affect
builds in later phases.
Have also added some water icons to show where Rhine floats.

1893: Hex L5/S6 cannot pass Rhine in Yellow phase

---

lib/engine/game/g_18_fl/step/buy_train.rb

Do not let a president contribute cash to cross-train buys if the corp had cash to begin with

Fix 18FL cross-corp train ebuy

---

assets/app/view/game/game_info.rb
lib/engine/depot.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_1882/game.rb
lib/engine/train.rb
spec/assets_spec.rb

fixes #3563
1822 - Hide trains that are on privates (Pullmans etc)
1882 - Hide the SC trains until they are used
1861/67 - Forget the trains existed for 2 player games

Show previous trains to make it easier to value corps in 1817

---

lib/engine/game/g_1817/step/selection_auction.rb

Occurs only if the initial bid causes all other players to be skipped
fixes #4750

1817: Skips incorrectly if auction is automatically resolved

---

lib/engine/game/g_1870/step/check_connection.rb
lib/engine/graph.rb
lib/engine/part/node.rb

max_nodes wasn't behaving as I expected and I can't figure out why. This version loses a slight performance improvement, but I think it's cleaner and more robust.

1870: Fix check_connections (reverts max_nodes)

---

assets/app/view/game/game_data.rb
assets/app/view/game/notepad.rb
assets/app/view/game/rename_hotseat.rb
assets/app/view/game/tools.rb
spec/assets_spec.rb

- notepad & hotseat rename autosave (save buttons removed)
- master mode button with icons (same as map controls)
- end game: cancel + confirm buttons switched => accidental double-clicks don’t end the game
- game data buttons shortened, no wiggle
- headers

tools cleanup

---

lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb

only applies to owning corporation's first OR turn
[Fixes #4815]

[18CZ] allow company terrain discounts after first lay

---

assets/app/game_manager.rb

Ultimately prevents redirection of `/hotseat/hs_yqfgmjqg_1595751670` to `/game/hs_yqfgmjqg_1595751670` which leads to "Page not found".

open hotseat in new tab (without error)

---

assets/app/view/game/stock_market.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/stock_market.rb

1860 and 1862 markets are unaffected by this change.
Before:
After:
Physical Board:

allow zigzag markets to be flipped; match 18CZ's market to physical board

---

lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/step/home_token.rb

closes #4851
The issue here is that in 18CZ the corporation can get new tokens before the home token is permanent.
When upgrading the home track of ATE to green a new token is placed, but the price of that token is now 100.
I also tried to not increase the price for tokens that cost 0, but if a corporation has  a  token also in B9, and then ATE buys that corporation, one token has to be removed, and that token needs to cost 100 and not 0 even if that was the home token.

[18CZ] Fixed Laying of ATE token

---

assets/app/view/game/companies.rb
assets/app/view/game/company.rb
lib/engine/game/g_18_cz/entities.rb
lib/engine/game/g_18_cz/game.rb

closes #3867
player/corp cards: company display revised
- company size included
- company name truncated if necessary
- company_status_str not truncated!
- title added
(Magnus is fine with the layout changes to 1822’s cards.)

company display on cards incl. company size

---

lib/engine/game/g_1828/game.rb

Use forget_train, so the depot train counts are correct.

[1828.Games] Don't show C&P train and removed 6 train in the depot train roster

---

assets/app/view/game_card.rb

closes #4671
- display delete button only when hotseat [if we need the delete button there for multi games, I’d add a check for `owner == @user`]
- layout fixes: display like other cards
- grid changed slightly, so longer titles have more space and don’t linebreak if not necessary
ante
post

game_card: fix rendering error game card

---

assets/app/lib/settings.rb

now that we have 16 colors by default it’s cruft
can be reintroduced if there’ll ever be a game with 17+ players … 🤦

revert calculated colors for 9+ players

---

lib/engine/game/g_1822_nrs/game.rb

- Fixed when try to aquire minor 16 it will look for the right city in the london hex.
fixes #4835
This doesnt affect any of the current games since its a UI check.

[1822NRS] Connectivity to minor 16

---

lib/engine/game/g_1822/game.rb

- If you dont have any exchange tokens. You shouldnt have the option to move an exchange token to available with the P5 ability.
fixes #4893
This shouldnt break any of the current games.

[1822] P5-LC&DR

---

lib/engine/game/g_1870/step/check_connection.rb

If a node is blocked, it never get added to `visited` because we used to
only care about paths. Now we check where the path is leading us next.

1870: Yet another check_connections fix

---

assets/app/view/game/buy_sell_shares.rb
assets/app/view/game/corporation.rb
assets/app/view/game/stock_market.rb
lib/engine/corporation.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/step/buy_tokens.rb
lib/engine/game/g_1862/step/charter_auction.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/buy_sell_par_shares.rb
lib/engine/share.rb
lib/engine/share_pool.rb
lib/engine/share_price.rb
lib/engine/step/buy_sell_par_shares.rb

SR is now mostly complete
This required changing the following common elements:
- Engine::Corporation - allow the bank to own IPO shares. Needed because a chartered company in 1862 can have shares both in IPO and in the treasury.
- Engine::Share - distinguish between IPO and treasury purchase prices
- Engine::SharePool - distinguish between IPO and treasury purchases
- Step::BuySellParShares - use ipo_shares rather than shares for parring (consequence of the above)
- UI::Corporation - show shares in treasury in addition to IPO
- UI::BuySellShares - allow buying shares from treasury in addition to IPO
1870 needed to be tweaked because it made assumptions about corporation.capitialization that was specific to 1870 for reissuing shares. I created a game method for 1870 for this.
A word about …

1862: Stock Round

---

lib/engine/game/g_1846/game.rb

this doesn't explain how a whole corporation got skipped in #4941, but it does
fix the issue
[Fixes #4941]
----
This breaks a few 1846 games - `[11362, 23182, 35294]`

[1846] don't skip MC/O&I second tile lay on Message

---

assets/app/lib/settings.rb
lib/engine/game/g_1873/game.rb

Fixes #4936 
Fixes #4952 
Fixes #4955 
Common file change: UI:Lib:Settings - unlimited routes by cycling through colors

1873: 17+ routes, tokening checks reserved tile, player value

---

lib/engine/game/g_1822/entities.rb

s.b. "London and North Western Railway" 
Using [this image for reference](https://cf.geekdo-images.com/-_bF1QrqIJnqo_meIjInvw__imagepage/img/_VicQtx5IEa4rmxqle9DhnXcA-M=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4787413.jpg)
closes #4929

[1822] fix LNWR corp name 

---

lib/engine/game/g_1870/step/buy_sell_par_shares.rb

I thought it always rounded down, but it turns out that it rounds to the closest value

1870: Fix rounding of reissue par price

---

assets/app/view/game/buy_trains.rb
lib/engine/game/g_1817/step/buy_train.rb

Being at train limit causes the turn to skip. Get confirmation if buying a train
will cause themselves to go into liquidation.
fixes #2600

1817: Warn about liquidation on the train step and ask for confirmation.

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/discard_train.rb
lib/engine/game/g_1822_mrs/game.rb
lib/engine/game/g_1822_nrs/game.rb

- Set value of the 5P to 500. If its discarded other can buy it for the same amount as a normal 5.
- If you discard a 2P or LP they are removed from the game.
- If you acquire a minor with LP or 2P, and the major already have a LP or a 2P you must discard one of them.
- Before discarding a train, remove all variants except the selected when the train was bought.
fixes #4789
fixes #4812
fixes #4985
This will break a few games.

[1822] Discard Train

---

assets/app/view/game/tile_manifest.rb
assets/app/view/tiles.rb
assets/app/view/tiles_page.rb

- tile name toggleable on tiles tab and /tiles (partly closes #4868)
- tile name + count rendering revised
- fixed rendering of double sided tiles (18Mag) on /tiles
- refactoring of double sided tiles rendering
ante
post

tiles tab/page: toggle tile name

---

lib/engine/game/g_1817/step/track.rb

PSM seems to have no closed properly since the ability refactor
fixes #4974

1817: PSM should close if tile cannot be laid

---

lib/engine/game/g_1822/step/buy_train.rb

- A corporation should only be able to buy one E train.
fixes #5020
This can break games if there is a corporation that have bought 2 E, this should be a very edge case.

[1822] Multiple E-Trains

---

lib/engine/game/g_18_ireland/game.rb
lib/engine/part/node.rb

The effect of narrow gauge track is to add the value of town stations that
are exclusively on narrow gauge track to the first broad gauge station
they are connected to at the end (or both ends) of the narrow
gauge line. Thus, the companies in the game benefit from the construction
of narrow gauge track even though they do not operate it
directly. It is possible to string together multiple towns on a single
narrow gauge line or network.

18Ireland bonus payouts for narrow gauge routes

---

lib/engine/game/g_18_ga/meta.rb

This presumes that the 18xx.net link is somewhat canonical
http://www.18xx.net/18GA/18GAr.txt
closes #5002

[18GA] update stale rules link

---

assets/app/view/game/part/town_dot.rb
assets/app/view/game/part/town_location.rb
assets/app/view/game/part/town_rect.rb
assets/app/view/game/part/towns.rb
assets/app/view/game/tile.rb
assets/app/view/game/tile_manifest.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/map.rb
lib/engine/tile.rb

- Add "hidden" attribute to tiles and hide those tiles on the manifest
- Treat tiles that have only one town like multi-town tiles if there are other paths on the tile (i.e. don't center them in the track)
- When a tile has over two towns all with the same revenue, only render a single revenue
This is all pretty much common code changes except for the 1862 tiles.
Old tile rendering for 1862:
New tile rendering:

1862: tile rendering fixes, hidden tiles

---

lib/engine/game/g_18_sj/game.rb

closes #5062 
[testcase](https://gist.github.com/benjaminxscott/2ef85450ff127c7775145679c9bded49)
Adds `groups` for each revenue location on `G10`, similar to Chicago in 1846
This PR implements the correct behavior:

[18SJ] stockholm can only be used once in a given route

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/token.rb

Implement 1862 trains and route rules.
- Routes must intersect, one route must included home token (same as 1860)
- Track can be reused between routes, but not within a route
- Revenue locations only count once across all routes (same as 1873).
- Split assignment of revenues and bonuses across trains.
- Freight trains: hex trains. Much complexity due to the rule that multiple non-permanent freight trains have to be linked end-to-end and then treated as a single, long train. Permanent trains may or may not be linked. Had to build "sets" of these trains and detect violations of this as well as weird branching cases.
- Local and Express trains: fairly normal, except the M/N trains are much harder to optimize in 1862 due to the fact revenue centers only count once across all trains. I had to …

1862: implement routes and trains

---

assets/app/view/game/hex.rb
assets/app/view/game/runnable.rb
lib/engine/route.rb

I added these nifty red hexes with lines through them and two offboards to make the 1862 map look correct.
The problem is that the existing code can't deal with multiple offboards on one hex for the purpose of selecting a route. This is because it doesn't know which node to use for the touch_node method in route.
This PR fixes that by creating a "disambiguation" front end to touch_node for hexes with two offboards.
Hopefully, more than just 1862 can make use of it.
Example:

1862: disambiguate multiple offboards on one hex

---

lib/engine/game/base.rb
lib/engine/game/g_1828/game.rb
lib/engine/game/g_1870/game.rb
lib/engine/step/buy_sell_par_shares.rb

also rename `can_hold_above_limit?` for clarity; there the "limit" is the
percentage of a corporation that one player is allowed to hold, not the "cert
limit"
[Fixes #5019]
----
I validated against all titles, just a few 1870 games broke and need pinning/archiving.

[1870] fix can_sell? to check for cert limit before corp % limit

---

assets/app/view/game/dividend.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/dividend.rb
lib/engine/game/g_1862/step/route.rb

Implement 1862 dividends. Mostly borrowed from 1860 (due to subsidies), but also added new dividend type: the George Hudson Manouevre. This is a way to boost share price by stealing corporate money to increase revenue.
I had to change the common UI:Dividend file for two reasons:
- It was written assuming the dividend choices are fixed for the entire game. Not true here since the Hudson Manouevre requires certain conditions to be true
- I wanted to be able to control the text on the button.
Example of the GHM:

1862: Dividends

---

lib/engine/game/g_1817_wo/game.rb

1817 code checks that the share isn't in liquidation
and is otherwise identical (except some is_a? vs instance_of?)
fixes #5053

1817WO: Shouldn't be able to redeem shares in liquidation

---

lib/engine/game/g_18_cz/game.rb

Adds reservation color when a corporation becomes available
closes #3905

[18CZ] Added reservation_color to available corp like 1822

---

lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/corporate_sell_shares.rb
lib/engine/step/emergency_money.rb

Still don't know how it was possible to submit the action that issued shares in
1882, but this change now raises an error if that happens. The game in
question ([37905](https://18xx.games/game/37905?action=120)) was [undone to before the issuing action](https://18xx.games/game/37905?action=140), and no other games
were found where this was done (I validated against the full DB), so nothing
needs to be pinned.
[Fixes #5107]

Require bundle ownership in order to sell shares

---

assets/app/view/game/actionable.rb

Clarify that the player is confirming that they *already have* consent to buy another player's stuff (not just confirming that they need consent).

Clarify confirmation to purchase from other player

---

assets/app/view/game/buy_trains.rb
assets/app/view/game/game_info.rb
lib/engine/action/buy_train.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/dividend.rb

Implement most of the buy_trains step for 1862, except for the emergency train buying rules.
- separate limits for each train type (freight/local/express) until phase G
- trains are now lettered A-H with the actual trains being options
- trains bought across companies are fixed price
- add train warranties that can be bought with new trains from depot
- warranties are kept track of by appending a number of *s to the name, every OR one * is removed
- implement deferred rusting due to warranties
This PR has several common file changes:
- UI::GameInfo, Engine::Game::Base - I needed to add control over how the train types and prices were displayed
- UI::BuyTrains - above, plus UI element for warranty purchases, fixed prices for used trains
- Action::BuyTrains - warranties
Old game info:
New …

1862: buy trains

---

lib/engine/game/g_18_cz/entities.rb
lib/engine/game/g_18_cz/game.rb

update the route distance string so that if more than N towns are hit, count the
excess toward the number on the left side of the +
[Fixes #5140]

fix 18CZ N+N trains hitting more than N towns

---

lib/engine/game/base.rb
lib/engine/game/g_1882/game.rb
lib/engine/game/g_18_mex/game.rb

* better baja private wording [Fixes #5099]
* if owning corp has no tokens left on charter, ability tokens with `from_owner`
should cause `ability_usable?` to return `false` [Fixes #5044]
* exception: in 1882, the NWR ability moves a token on the map so it still
works if the owning corp has none left

18MEX Baja variant fixes

---

lib/engine/game/base.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/step/train.rb
lib/engine/stock_market.rb

Correct the rusting timing
Make selling of shares possible if EMR happens in the first round
Also, remove private from stock_market as 18ireland merger requires finding a stock price
by row and column

18ireland: Implement EMR rules

---

lib/engine/game/g_1822/game.rb

Companies P15-HR and P20-C&WR close at beginning of phase 7 if player-owned (in `def event_phase_revenue!`).
Rather than generic statement, report to log the balance and owner of each closing company.
See issue https://github.com/tobymao/18xx/issues/5168 .

[1822] Better logging when phase revenue companies close

---

assets/app/view/game/game_info.rb

18ireland has a lot of trains in the discard, simplify it
to
fixes #5154

Simplify discard trains

---

lib/engine/game/base.rb
lib/engine/game/g_18_ireland/step/narrow_track.rb
lib/engine/hex.rb
lib/engine/step/tracker.rb

Irish Mail turns an impassible Red into and connected tile, update
the neighbors of the adjacent tiles so it is now connected.
1867 tile rule was impacting 18ireland DD tile, until a better solution
can be find specialise the 18Ireland version without that check

18Ireland: Fix Irish Mail and DD tile lays

---

assets/app/view/game/part/upgrade.rb
assets/app/view/game/part/upgrades.rb
lib/engine/part/upgrade.rb
lib/engine/tile.rb

make cow skulls bigger in 1868WY
#5011
before on the left, after on the right:

allow upgrade icons to be resized in tile def

---

assets/app/view/game/game_info.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1828/game.rb
lib/engine/game/g_1846/game.rb
lib/engine/game/g_1849/game.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ms/game.rb
lib/engine/game/g_18_zoo/game.rb
spec/lib/engine/games/g_1828_spec.rb

Show the end game conditions on the info page.
Remove custom code for one vs last but one bankrupcy.
Remove custom code for last phase.
fixes #3974
1849 could do with some improvement as i'm not sure it supports bankrupcy at all, and it'd be good to refactor the rounds based approach of 18MS and 18ZOO

Show end game conditions in UI, and simplify code

---

assets/app/view/game/part/city_slot.rb
assets/app/view/game/part/town_dot.rb
lib/engine/part/city.rb
lib/engine/part/town.rb
lib/engine/tile.rb

[1868WY] render boomtowns and boom cities

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/map.rb
lib/engine/game/g_1868_wy/trains.rb

* fix IPO name
* can buy companies from phase 3 for $1 to face
* various constant-based rules
* unlimited tiles except for C, L, G, and gray tiles
* hide ghost town (GT) tiles from manifest
* remove the plain ghost town tile, can just destroy the town instead
* remove the wind river canyon tile (and WRC label from the map hex), can just
use a plain yellow tile and turn it gray after its laid
[Issue #5011]

[1868WY] basic configuration changes

---

lib/engine/game/g_18_co/step/moving_bid_auction.rb

Fixes #5190. Ensures a player is inserted into the pass order when being skipped in case they have not ever passed.

Update pass order when skipping

---

assets/app/view/game/part/town_dot.rb

sample partial tile manifest from 1868WY:

make town dots on track more noticeable with a white outline

---

lib/engine/game/base.rb
lib/engine/game/g_1868_wy/game.rb

General changes (easier to see with the ignore whitespace option selected):
* change the capitalization condition in `after_par` before the shares check to
an if block instead of a guard statement so that the final `place_home_token`
call will be reached with any capitalization (ie in 1868WY's phase 5)
1868WY:
* change `HOME_TOKEN_TIMING` to `:par`
* fixes UP's token being placed when it's parred/floated in the ISR
* combined with change in `Game::Base`, fixes home token placement in phase
5 and later, when float/capitalization is changed to 60%/full
[Issue #5011]

fix "par" home token timing for corporations with full cap

---

lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1822/step/tracker.rb
lib/engine/game/g_1862/step/track.rb
lib/engine/game/g_18_cz/step/home_track.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/track.rb
lib/engine/step/tracker.rb

- Permissive tile lays
- Yellow towns can upgrade to yellow cities once green tiles are available
- Some cities start off as normal city tiles and later become special city tiles
- Some NYC tiles have a required rotation
- Refactor tile upgrades, so that yellow -> yellow is an upgrade
Ran against 5/2 DB and all games passed.

[18NY] Tile lays

---

lib/engine/game/g_1870/game.rb

closes #5151 
References:
> "P3 (SCC) token may be placed in any city west of the Mississippi. Cities located in the same hex as any portion of the Mississippi river are not allowed."
Rules: http://www.hexagonia.com/rules/MFG_1870.pdf
Map: https://18xx.games/map/1870

[1870] fix valid hexes for P3 (SCC)

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/track.rb

* Each railroad gets 6 track points
* 2 points to lay new tile, 3 points for upgrades
* P7 General Jack adds a track point to the owning railroad, so if 1 point
remains and P7 could be bought in, the game should remain on the track step
* Set track points to 0 at end of each OR; when LNP or OSL are started, and
their home tile doesn't have the green tile yet, it must be laid immediately
for their home token to be placed, and this must count against their used
track points. Therefore the track points cannot be set to 0 at the start of
the OR (the automatic LNP/OSL green lay has not yet been implemented)
[Issue #5011]

[1868WY] track points

---

lib/engine/game/base.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/tile.rb

A few small changes that touch a smidge of common code
General Changes:
* make a tile's `color` a writable attr
* make `Game::Base#add_extra_tile` return the new tile so that the method can be
overridden in subclasses and the new tile may be further modified if needed
1868WY:
* turn Wind River Canyon (WRC) gray after the yellow tile is laid; in the
physical game, there is a special gray tile with just a gentle curve that is
the only tile which may be placed there; it is layable in yellow and
equivalent to a normal gentle yellow
* fix new tiles from "unlimited" stack having rectangular towns
* fix company buy-in price
* add train export
[Issue #5011]

[1868WY] WRC tile, fix rectangular towns, company buy-in price, train export

---

lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1822/step/track.rb
lib/engine/game/g_1822/step/tracker.rb

- Removed the restriction of yellow london counted as an upgrade.
fixes #5090
This shouldnt break any games.

[1822] Dont count yellow london as upgrade

---

assets/app/view/game/round/operating.rb
lib/engine/corporation.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/acquire.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/dividend.rb
lib/engine/game/g_1862/step/merge.rb
lib/engine/game/g_1862/step/option_share.rb
lib/engine/game/g_1862/step/redeem_share.rb
lib/engine/game/g_1862/step/remove_tokens.rb
lib/engine/game/g_1862/step/route.rb
lib/engine/game/g_1862/step/token.rb
lib/engine/game/g_1862/step/track.rb

Add support for complicated merger and acquisition process. Also implements refinancing. Also implements corporation bankruptcy.
- Engine::Corporation - make always_market_price an attr_accessor
- UI::Round::Operating - allow display of a second corporation (helps with merge)

1862: implement mergers and acquisitions

---

lib/engine/game/g_1828/step/merger.rb

`exchange_source` should only verify the player has enough shares of the `merger`. The check for total shares has already been done. Leads to erroneous exchanges.

1828.Games: Fix merger bug

---

lib/engine/game/g_1870/step/price_protection.rb
lib/engine/game/g_1870/stock_market.rb

Preserve order when hitting the soft ledge (don't go down to come back up)
When hitting the ceiling, move right and down instead

1870: Fix stock movements (fixes #5067)

---

lib/engine/game/g_1870/step/check_connection.rb
lib/engine/step/buy_sell_par_shares.rb

The pass! on PriceProtection may be called during the Stock Round
while on the turn closed corporation and it inherits BuySellParShares
force_next_entity! tries to pass! every step, but we still want to run
through the CheckConnection

1870: Fix error on closing corporation (fixes #4987)

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/buy_train.rb

During EMR force selling down to 60% if holding above 60% and selling
some share. Now to consider "the minimum" a player must sell, we can't
only look and the money. We may also need allow selling more than 10%
when the player holds more than 60%.

1870: Enforce "must sell down to 60%" rule during EMR (fixes #4566)

---

assets/app/view/game/entity_list.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/meta.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/dividend.rb
lib/engine/game/g_1862/step/merge.rb
lib/engine/game/g_1862/step/redeem_share.rb
lib/engine/game/g_1862/step/route.rb
lib/engine/game/g_1862/step/token.rb
lib/engine/game/g_1862/step/track.rb
lib/engine/round/operating.rb

Adds game end conditions and completes receivership rules
Fixes a problem with train owners not being adjusted after a merge
Fixes a problem with shares not moved from originator to survivor after a merge
- Game::Base
- Round::Operating
- UI::EntityList
All of the above were changed to add and use an "acting_for_entity" method used to show which player is operating on behalf of a corporation/minor. This was needed because the 1862 rules specify that the majority shareholder makes the decisions of a receivership corp (instead of "The Market").

1862: end game and receivership

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/price_protection.rb

Moved sell_queue from round to game, because it now is checked at all times (and was already available almost anywhere anyway)

1870: Fix bug that broke game rendering at the end of the auction.

---

assets/app/view/game/part/city_slot.rb
lib/engine/game/base.rb
lib/engine/game/g_1860/game.rb

Both 1860 and 1862 have the requirement that at least one route must contain the home token. It is helpful to highlight this token on the map.
Fixes #4946 
Examples:

1860, 1862: highlight home token

---

lib/engine/game/g_1822/step/route.rb

- If a minor only have an E-train, skip the run routes step.
fixes #5079
This will probably break a game or two if there was a minor who owned a E-Train.

[1822] Minors shouldnt be able to run E trains

---

assets/app/view/game/buy_trains.rb
assets/app/view/game/game_info.rb
lib/engine/game/base.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/buy_sell_par_shares.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/step/train.rb

Global Changes: 
- game/base: Adds a constant  `ALLOW_TRAIN_BUY_FROM_OTHERS = true ` which is needed for a text snippet (and is now also used in the available_trains method)
This should not affect any game since no game has that variable set to false (except 1840 of course)
- game_info: Extracts active train setting to a function, so that multiple arrows are possible:
Game specific:
- Adds Train Configuration
- Adds EBuy
- Adds Player Debt

[1840] Added Train Config and train buying

---

lib/engine/game/g_18_ireland/step/merge.rb
validate.rb

fixes #5275 
18Ireland trys to move tokens to the new corporation twice causing stray ones to appear.

18Ireland: Unused token after 2 corp merger should be £50 rather than £0

---

assets/app/view/game/spreadsheet.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/map.rb
lib/engine/game/g_1862/step/acquire.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/charter_auction.rb
lib/engine/game/g_1862/step/dividend.rb
lib/engine/game/g_1862/step/merge.rb

This adds an optional column to the spreadsheet view. This is needed to show treasury shares separately from IPO shares (which are indeed separate in 1862). So obviously this touches UI::Spreadsheet as well as Game::Base
There are also a number of fixes for bugs found in a playthrough:
* Sort bank entities by start phase
* Offboard values are not indexed by tile color in 1862. Fixes that.
* Bug with sometimes ignoring a bid of 0
* Use "Additional Warranties" if trains come with a warranty
* I missed a dup when "delayed" rusting trains owned by a player
* Add home hex markers back when restarting a corp
* Fix player value and liquidity
* Mergers had superfluous "major" in some of the descriptions and log messages.
This should be the last PR prior to going alpha.
New column:

1862: spreadsheet and bug fixes

---

lib/engine/game/base.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/special_token.rb
lib/engine/game/g_1840/step/track_and_token.rb
lib/engine/step/route.rb
lib/engine/step/tokener.rb

Adds a new graph for city corporations and adds replacing of city tokens.
Changes some references of `@graph` in base game or `@game.graph` to `graph_for_entity`.  I think we should use in general functions always `graph_for_entity` which is more flexible than just accessing the default graph.
Also extracted the `check_connected` method since I need that code in another place again

[1840] Replace city token

---

assets/app/view/game/buy_companies.rb
assets/app/view/game/dividend.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/round/line_operating.rb
lib/engine/game/g_1840/step/buy_company.rb
lib/engine/game/g_1840/step/dividend.rb
lib/engine/game/g_1840/step/route.rb
lib/engine/game/g_1840/step/track_and_token.rb
lib/engine/game/g_18_mag/step/dividend.rb

This adds the dividend handling for major corporations, track handling for city trains (can run through tokened cities, but does not pay), and private companies (can be bought by owning major corporation and give bonus to all lines of major corporation)
This build up on the variable dividend from 18Mag, but a litle bit different. That's why I added some step methods to the view to make some parameters variable.
@roseundy can you look at the changes for 18Mag. I tested it and everything behaves as before, but a second look might not hurt.

[1840]  Added dividend for major corporations, track value for city and company bonus

---

lib/engine/game/g_1828/step/merger.rb

Ruling from JC. If you have an odd number of shares to trade, you can retain a share that will become a system share, even if you don't have enough other soon-to-be system shares. The player can get the other system share from another source.
Situation
GT merging into PR
P1: 2 PRR, 3 GT
Before:
P1 was forced to hold on to the GT share because the 2 PRRs are needed in the 2:1 exchange as they will become system shares
After:
P1 can keep 1 PRR share as the odd share. The first system share comes from combining a PRR and a GT. The second system share comes from a trade of a GT share for a PRR share from another source. The original PRR share is retained for the single share exchange step.

1828: Allow player to retain soon-to-be system share and trade for a system share from another

---

lib/engine/game/g_1862/game.rb

* Remove tokens from map on bankruptcy
* Fix problem with stock purchases being blocked after LNER formation
* Re-sort shares after merger/bankruptcy
* Start with all companies IPO stock in bank
* Remove unstartable corps after LNER formation
* Keep chartered flag when merging two chartered corps (only needed for solo rules)

1862: more play-though fixes

---

lib/engine/game/g_18_zoo/entities.rb
lib/engine/game/g_18_zoo/game.rb

Update text to use 18xx terms
Add description for yellow par on market
Add tie breaking on results based on turn order
Avoid application of "patch" when company already owns 3 companies
Assign "patch" to corporation when owner is player
Change ZOOTickets sym to avoid strange number inside "spreadsheet"

[18ZOO] - Update multiple small details

---

assets/app/view/game/buy_trains.rb
assets/app/view/game/round/operating.rb
assets/app/view/game/scrap_trains.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_1840/step/route.rb

In 1840 it is theoretically always possible to scrap a train. That is not so easy to implement, so I asked Lonny whats the minimum viable option. For now we can scrap trains when buying trains and in the route selection. That should probably be enough.
This PR extracts the scrap_train view to be an own component and can be shown independend of buy_train.
I tested with 1873 and looking at the logic in operating.rb it should behave nearly the same as before.

[1840] Made scrapping view more generic and added to route step

---

lib/engine/game/g_18_ireland/step/merger_common.rb

See https://github.com/tobymao/18xx/issues/5386
Prior code required votes_against to be greater than votes_needed, and so mis-reported a 4-6 result as a tie.

[18Ireland] Fix voting result message

---

lib/engine/game/g_1862/entities.rb
lib/engine/game/g_1862/game.rb

Fixes #5392 
Also fixed typo in name of "Waveney Valley Railway"

1862: full fix for clearing train operated flag on merge

---

assets/app/view/game/part/large_icons.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb

Corp markers (large icons) on map now indicate the type of permit and whether they are available to start.

1862: differentiate between permits types on markers on map

---

lib/engine/ability/README.md
lib/engine/game/base.rb
lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/par_and_buy_actions.rb

1. Add a 'when' attribute for using private in SR
2. Update description on 3 events
3. Par 120 not allowed via stockmarket
4. Prepare FdsD-RAG exchange (not complete yet)

Misc corrections for 1893

---

lib/engine/game/g_1862/game.rb
public/logos/1862/ECR.alt.svg
public/logos/1862/EH.alt.svg
public/logos/1862/ENR.alt.svg
public/logos/1862/ESR.alt.svg
public/logos/1862/EUR.alt.svg
public/logos/1862/FDR.alt.svg
public/logos/1862/IB.alt.svg
public/logos/1862/LD.alt.svg
public/logos/1862/LE.alt.svg
public/logos/1862/LH.alt.svg
public/logos/1862/NB.alt.svg
public/logos/1862/NE.alt.svg
public/logos/1862/NGC.alt.svg
public/logos/1862/NS.alt.svg
public/logos/1862/SVR.alt.svg
public/logos/1862/WF.alt.svg
public/logos/1862/WNR.alt.svg
public/logos/1862/WSTI.alt.svg
public/logos/1862/WVR.alt.svg
public/logos/1862/YN.alt.svg

Fixes #5379 
After some debate, simplified Freight route hex-distance bonus calculation:

1862: change freight route distance calc; add alt logos

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/dividend.rb

Fixes #5418 
Fixes #5419 
Any game that used the Hudson Manoeuvre will likely need to be archived.

1862: Fix Hudson manoeuvre; Obligations should not impact share limit

---

lib/engine/game/g_1862/game.rb

Fixes #5426 
Shouldn't need archiving since track restrictions are not checked when loading.

1862: make track semi-restrictive

---

lib/engine/game/g_18_al/meta.rb

The previous link do no longer load. Use an A5 booklet version instead
from BGG.

18AL: Change rule link (fixes #3536)

---

lib/engine/game/g_1862/map.rb

G14 and F15 had different values for Holland offboard.
See https://github.com/tobymao/18xx/issues/5432

[1862] Correct value of Holland offboard.

---

assets/app/view/game/convert.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb

Fixes #5449 
Fixes #5453 
Modified UI::Convert to allow specifying text on button
Unlikely this will require archiving games. If it invalidates a lot of games, then something is wrong.

1862: add refinance as an option; add missing stock value

---

assets/app/view/game/part/city.rb
lib/engine/game/base.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/map.rb
lib/engine/game/g_1868_wy/step/boom_track.rb
lib/engine/game/g_1868_wy/step/track.rb
lib/engine/step/tracker.rb

General changes:
* move `Engine::Step::Tracker#update_tile_lists()` logic into a method on the
`Game` class so it can be called from the `Game`, not just from the `Step`
1868 Wyoming-specific changes:
* add some locs to double Boomtown preprinted tiles to control which one becomes
the Boom City
* when a hex's DTC (development token count) hits 3, 4, or 5, it Booms
* 3: one Boomtown -> Boom City (tile replacement, or update preprinted tile)
* 4: revenue increases by 10
* 5: in brown Boom City -> Double Boom City (tile replacement; two slots);
affects future upgrades for green tiles with one Boomtown and one Boom
City
* when a Booming tile needs a replacement, it can't be done automatically if
are multiple Boomtowns/Boom Cities on it, or if there are insufficient Gray
tiles (other colors …

[1868WY] DTC Boomtown/Boom City effects and bonuses

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/step/token.rb

FIxes #5481 
Fixes #5484 
Games where someone tokened London illegally will need to be archived.

1862: fix chartered corp treasury buys; check london connection for links

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_18_los_angeles/game.rb

Remove the `@checked_little_miami_graph_before ||=` in
`check_little_miami_graph_before!`; that caused an issue if one Little Miami
action was done and then the user refreshed, or if both actions were done and
then one was undone; due to the `loading`, check, this caused the
`check_little_miami_graph_before!` logic to be skipped on the first Little Miami
action and then executed on the first.
Move that check so that `check_little_miami_graph_before!` is only called before
any Little Miami actions have been made; also move the initialization of
`@little_miami_hexes_laid` from the `after!` check so it can also be used for
this
[Fixes #5490]

[1846] fix Little Miami Undo bug

---

lib/engine/game/g_1846/entities.rb

* partial fix for #5476; the same change is not applied to IC's ability, as
making that change has an unexpected side effect: Currently if IC has
insufficient cash for a track tile or token, their `TrackAndToken` step is not
skipped, even if all of the hexes where they are allowed a free yellow tile
already have tiles placed. When their ability is changed from `free` to
`discount`, their `TrackAndToken` step *does* get skipped if they lack the
funds for another action (I think this would be preferred behavior, but also
requires a migration)
https://boardgamegeek.com/thread/2665904/article/37786321#37786321

[1846] change Little Miami's tile lay ability from "free" to "discount: 20"

---

lib/engine/game/g_1862/map.rb

Fixes #5522 
This shouldn't require archiving games (since illegal rotations with the new leg aren't checked when loading actions).

1862: fix tile 61y

---

lib/engine/game/g_1860/game.rb
lib/engine/game/g_1860/step/buy_sell_par_shares.rb

Fixes #4999 
Fixes #5505 
This will require some games to be pinned.

1860: no out-of-turn exchanges; allow some exchanges after parring

---

lib/engine/game/base.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1846/entities.rb
lib/engine/step/track_and_token.rb

Also change `Step::TrackAndToken#can_lay_tile?` so that if a discount is at
least as high as the tile's normal base cost, it counts as free
This fixes the edge case where IC still needs to pay for the bridge between J4
and J6; the implementation before this commit makes it completely free.
[Fixes #5476]
See also #5501
----
Validated against all 1846-family games in my local DB copy, it checks out

1846: IC tile lay from free to discount

---

lib/engine/game/g_1846/step/bankrupt.rb
lib/engine/step/train.rb

1846: Reset "last share sold" stuff on bankruptcy to fix train restrictions

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/map.rb
lib/engine/game/g_1868_wy/trains.rb
lib/engine/hex.rb

General Changes:
* when laying a tile, check that a new city actually exists before updating its
reservations and groups
1868 Wyoming:
* add events for removing Coal Development Tokens 2 phases after they are placed
* remove "GT" labels from ghost town tiles, not needed for digital
implementation
* fix tile 5b (remove extra path)
* when a Boomcity has busted below DTC of 3, its revenue is reduced to $10; in
the next BUST Round, the tile is downgraded to a Boomtown or Ghost Town (plain
track tile)
* add constant `GHOST_TOWN_TILE` to identify which tile replaces a tile that has
busted to a ghost town
* cities in hexes with no tiles that bust to DTC of 0 do not become Ghost Towns
* override `next_round!` so that at the end of each OR a Bust Round happens, and
after the second OR in a set a …

[1868WY] Bust when DTC drops, add BUST rounds

---

lib/engine/game/g_1873/step/track.rb

1873: allow other corps to place reserved tile on target hex

---

lib/engine/game/g_18_cz/entities.rb

"Wolframs-Teltsch" missing and an extra "Martinitz-Rochlitz", relative to the printed rulebook.
Edit puts in W-T as S4 (replacing S-B-B), and moves S-B-B to S5 (replacing M-R), matching order in rulebook.

[18CZ] "Martinitz-Rochlitz" local RR duplicated

---

lib/engine/game/g_1856/game.rb

Fix 'x%' to float appearing in phase 6 in 1856 instead of 'y%' to operate

---

lib/engine/game/g_1856/game.rb

1856: Waterloo cannot be used outside of a corporation's OR now

---

lib/engine/game/g_1856/step/bankrupt.rb

The privates broke in the last deploy; the bankruptcy fix broke the ability to use privates in the UI. This fixes it
Fixes #5648

Fix privates not working in **56

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_mrs/game.rb
lib/engine/game/g_1822_mrs/meta.rb

Adds the 2 player variant to 1822MRS.  Variant is automatically activated when 2-players are selected.  Checkbox for Advanced still overrides Box 1 Minor placement (M14 instead of M24)

[1822MRS] Added 2-player Variant

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_1846/step/special_track.rb
lib/engine/game/g_18_los_angeles/game.rb
spec/lib/engine/hex_spec.rb

Several changes related to icon cleanup
1 When a private company is removed (during setup or private closure), also remove its icons
e.g. The "hog" icon for Boomtown private will be removed from H12 if Boomtown is removed during setup
Note that this also fixes a bug in "first edition" variants where the Boomtown and Little Miami private icons were still present even after being removed at setup-time
This also applies to 18LA, for the equivalent Citrus and Port companies
Examples where privates are removed:
2 When the IC corporation is removed in a two-player variant context, remove its icon on related hexes 
Example when IC is removed in a 2P game
3 In 18LA, remove the label for `SBL` private after it is used (this is equivalent to LSL in 1846)
before:
after:
--
Note that the hex test …

[1846, 18LA] remove icons when appropriate

---

lib/engine/game/base.rb
lib/engine/step/tracker.rb

This is needed for 1893, when upgrading Leverkusen hex, from
yellow to green.
Yellow Leverkusen hex has two towns, each on a separate track.
The green Leverkusen hex hex have track at same edges, but the
track makes an X with a city in the middle. It does remove the
towns.

Make it possible to override orientation check

---

lib/engine/game/base.rb

In some titles there are companies owned by bank when OR is
entered. These should not trigger log texts about bank receiving
payouts from the bank...

Do not give revenue to bank for privates owned by bank

---

assets/app/view/game/round/auction.rb

Some games (e.g. 1893) has the possibility to draft a minor for
its "face value". Have added a may_draft?(minor) method that if
this return true, then a "Buy for XX" button appear during auction/draft.
The XX is the amount that is returned by min_bid(minor).
Buying the minor will result in a bid action with minor set,
and price the min_bid.
Default is that no such button appear. The step need to implement
may_draft?(minor) and have it return true for it to appear.

Make it possible to draft minors for a min_bid

---

lib/engine/game/g_18_cz/game.rb

Override the base class constant so we have a better description of the endgame condition
before:
after:

[18CZ] make CZ's end condition more clear

---

lib/engine/game/g_1856/game.rb

Duplicate tokens in home bases don't kill off home bases in 1856

---

assets/app/view/game/round/stock.rb
lib/engine/game/g_1893/step/buy_minor.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb
lib/engine/game/g_1893/step/starting_package_initial_auction.rb

General: Show any buyable minors in stock round, and add a Buy button if
this can be bought.
1893: Implement buy_corporation for minors during buy_sell_par_shares step.

Add support to buy minor in SR (fixes #5725)

---

lib/engine/game/g_1856/game.rb

I'm not sure why `can_par?` was implemented this way when this new way is far simpler. Maybe it was used for something else earlier in 18xx.games but I couldn't find a reason for it not to simply be that you cannot par the national

Fix issue that stalled game/44700

---

lib/engine/game/g_1856/game.rb

1856: fix borrowed trains being marked as having operated

---

lib/engine/game/g_1893/game.rb

AGV and HGK have a 20% certificate each, besides the 20% president share.
This is now shown with a 'd', similar to 1849.

[1893] Show double cert (fixed #5756)

---

lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb

Was a bug where the first pass status was lost when going from
drafting to stock round during turn 1.

[1893] Improve to check for SR1 pass (fixes #5762)

---

lib/engine/auto_router.rb

This specifically handles the case in '46 where a minor company's train cannot operate twice in the same OR
e.g. if the minor is bought into a major in the same OR that the minor's train has operated, that train cannot operate again
Possibly this fixes autoroute bugs in other games, if they have similar concepts of "runnable" trains
closes #5694

[autoroute] trains must be 'runnable' to be routed

---

lib/engine/game/g_1856/step/buy_sell_par_shares.rb
spec/fixtures/1856/README.md

This is the last and most edge-casey of the rules to implement for 1856. There isn't any pre-existing structure for players to go bankrupt in a stockround and since this scenario so so unlikely to happen (At this point in a game a player can usually scrounge up enough capital to buy a single share) that instead of implementing a proper bankruptcy button like in the Buy Trains step the Buy Sell shares step for 1856 forces the player to keep on selling shares until they are either able to buy the share they are obligated to buy or if they are out of share to sell it ends the game

1856: Game ends when a player is forced to buy a national share but is unable to

---

assets/app/view/game/round/auction.rb
assets/app/view/game/round/stock.rb
lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_minor.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb
lib/engine/game/g_1893/step/starting_package_initial_auction.rb

- Restore companies for the 5 minors and act upon them instead
- Remove some minor related code that was used when not having
proxy privates
Note: Have some TODOs that is needed to support existing games.
Should be removed but will break the games. So wait with that.

[1893] Use privates as proxies for minors (fixes #5760)

---

assets/app/view/game/part/label.rb

When upgraded to green/brown/gray, the Chicago tile has its CHI label pushed to the lower left corner, making it overlap other parts of the tile
1846 uses "pointy" tiles, and the Chi tile specifically wants to use `POINTY_MULTI_CITY_LOCATIONS`
This patch changes this type of tile to prefer other parts of the tile above the lower left corner
Checked 18CZ which is another title with pointy tiles and multi-cities, and its OOs and Prague were unchanged with this patch
before: 
after:

[1846] fix chi label position when upgraded

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb

Fixes #5788 
Fixes #5799 
While debugging, I also noticed and fixed errors related to empty train routes when doing the M/N auto-optimize.

1862: Fix rounding issue on mergers; fix zombie buy_train messages

---

lib/engine/game/g_1856/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/share_buying.rb

The issue was caused by the buy_shares auto action only issuing a single share, not a bundle, to `can_buy?`. With this change all base calls to `can_buy?` use a bundle now

Fixes #5825

---

lib/engine/game/g_18_fl/step/buy_train.rb

I don't think this will break any games because it won't make EMR any easier for anyone and EMR isn't auto-skipped if there is no choice of which train to buy

8.4.1 in the 18FL rules states that a player is not forced to buy the cheapest train from the pool/depot when EMR

---

lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/map.rb

Added empty hex D2, which does appear on the published map. Also added Wien name to hex I11, as it's on the published board. Fixes bug #5818

[1840] Update map.rb to add missing hex

---

lib/engine/game/g_1893/game.rb

The bug was when upgrading Köln from brown to gray - which caused a
"must use new track", but gray Köln has no new track. The rules
are not explicit if it is allowed to upgrade a city tile where new
track is not reachable but my interpretation is that this should
be allowed.

1893: Allow city upgrade even if no new track is usable (fixes #5836)

---

lib/engine/game/g_1824/step/buy_train.rb
lib/engine/game/g_1893/step/buy_train.rb
lib/engine/step/buy_train.rb
lib/engine/step/train.rb

By making the check in a method it is easy for titles to override
method if they want to allow a minor to be able to buy trains.
If instead an override of actions' method it might cause a bug
if code is forgotten - which is what happended in 1893 (and 1824).
A quick scan through of existing titles did not find any other
title where minors can buy trains so I have not updated any
other title.

Change minor check in buy trains actions (fixes #5843)

---

lib/engine/game/g_1840/map.rb

Hex was incorrectly implemented before. 
This fixes bug #5859

Fix hex G11

---

lib/engine/game/g_18_va/game.rb

I learned about `check_distance` last night looking into how 1862 handled the london token check. Using this gets around the issue I encountered with throwing GameError in revenue_for so I moved a lot of "is the route valid" logic out of `revenue_for` into the new `check_distance`

Fix the ports in 18VA

---

assets/app/view/game/round/operating.rb
assets/app/view/game/route_selector.rb
assets/app/view/game/track_conversion.rb
lib/engine/game/base.rb
lib/engine/game/g_1860/step/route.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/map.rb
lib/engine/game/g_18_carolinas/step/track.rb
lib/engine/route.rb
lib/engine/step/route.rb

Implement all track rules, including track conversion operation.
Make all "Southern" track dual gauge instead of narrow gauge (so Graph will work correctly for mixed segments).
Finish implementing dual-sided tiles
UI::Round::Operating - add optional "mode" button, alternate route selector view
UI::TrackConversion - new view
Engine::Route - moved token check to game
Engine::Game::Base - move an Engine::Route check method here
Engine::Step::Route - added default alternate_selector? method
Mode Button:
Track Conversion Mode:

18Carolinas: track rules

---

lib/engine/game/g_1856/game.rb
public/icons/1856/bridge.svg
public/icons/1856/tunnel.svg

This also makes the tokens on the map the canonical source of truth as to how many tokens are left for purchase (like 1828.games)

Display bonus tokens on map in 1856

---

assets/app/view/game/route_selector.rb
lib/engine/game/base.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/step/dividend.rb
lib/engine/game/g_18_carolinas/step/route.rb

Implement running trains and dividends.
Adds concept of "variable" train lists for a corp. User controls train mix being run subject to constraint of current "train power" (which is hard-coded for the time being).
UI::RouteSelector - add UI elements to add and delete trains, and to change the size of the currently selected train.
Engine::Game::Base - default methods for the above.
Example:

18Carolinas: routes and dividends

---

lib/engine/game/g_1856/game.rb

Fixes #5885 (bank relies on `interest_rate`, corporations `@total_loans`)
Fixes #5886 by using `concat` and not `+=` (I verified this with puts, the loans are put back)

Remove loans from 1856 UI after nationalization

---

lib/engine/game/g_1889/game.rb
lib/engine/game/g_1889/meta.rb

For the additional tiles, I would've preferred to add tiles but it looks like the canonical way to use `optional_tiles` is to add the optional tiles to the roster and remove them in the method.
Side effect of having the beginner tiles in the manifest the way they are: upgrades are slightly more complicated:

1889 Beginner Game rules

---

lib/engine/auto_router.rb

closes #5863 
for 18cz this fixes the issue with taking a not runnable train into account.
since the default implementation is entity.runnable_trains it should not change  most of the games and only improve the behaviour

Fixes Trains selection for autorouting

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/dividend.rb
lib/engine/game/g_18_ka/game.rb
spec/fixtures/1836jr56/README.md
spec/fixtures/1836jr56/hotseat004.json

Fixes #5906 
It also displays the dividends for 20 share corps as fractional since the per-share dividends are friendly to the player anyways

Fix rounding of 5% dividends in 1856

---

lib/engine/game/g_1846/game.rb

closes #1869 
This adds loglines for which private companies and corps are currently in the game

[1846] emit list of privates in the game

---

lib/engine/game/g_1856/game.rb

I missed this reverting this %f back to %d when I was trying to make currency say "$32" or "$9.5"
Fixes #5921

1856: Restore %d to 1856's default currency format

---

lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares.rb

As shares in 1893 are moved from IPO to market when parred,
we need to change the check in general code that checks if auto
order was for market or IPO. "Buy until float" has IPO as source.
So the check is extracted to a method, which 1893 can override,
so that "auto buy until float" always buys from market.

[1893] Support auto buy until float (fixes #5794)

---

lib/engine/game/g_18_va/meta.rb

The DTG link seems to be stale (in fact their whole site is non-responsive)

[18VA] update stale rules link

---

assets/app/view/game/buy_power.rb
assets/app/view/game/corporation.rb
assets/app/view/game/game_info.rb
assets/app/view/game/round/operating.rb
lib/engine/action/buy_power.rb
lib/engine/game/base.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/step/buy_power.rb

Replace buy_trains step/action/view with buy_power step/action/view
Add train power and power progress support to game_info and corporation cards
UI::Round::Operating - support for buy_power
UI::GameInfo - support for power progress, more generic phase info
UI::Corporation - support for train power
Engine::Game::Base - default methods to support above UI changes
Spreadsheet tab still needs more work.

18Carolinas: buy_power step/view; phases; support for power in UI

---

lib/engine/game/g_1828/round/stock.rb

So we don't miss out on a price movement, we first check whether the stock is in the "gray zone" - and then move it if so, before we attempt other movements for "sold out" and "80% owned by one player"
Given the example in the bug report, the companies now move three rows up as expected
```
MC's share price changes from $58 to $71
OSH's share price changes from $58 to $71
NW's share price changes from $55 to $68
```
fixes #5957

[1828] check that stock is in gray before trying to move up

---

assets/app/view/game/player.rb

This adds a ` d` after the company symbol, if the player owns a double share of that company
Note the space between company symbol and the `d`, to separate it from the company symbol
If a player owns 30% or more of a company, it will still show that part of their ownership is a double share
(similar to how presidencies work)
This can stack with presidency, if a game allows that
closes #5809

show double share in player holdings

---

lib/engine/game/g_18_va/meta.rb

This reverts commit e389475cb27b51c1896867d16f1588a87dac6a97.
Looks like DTG site is back up

[18VA] Revert "update stale rules link"

---

lib/engine/game/base.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/track.rb
lib/engine/step/tracker.rb
spec/fixtures/1856/README.md
spec/fixtures/1856/hotseat007.json

A check was recently added to `tracker.rb` that makes sures that towns aren't removed during tile upgrades which of course prevents us from replacing town tiles with plain track tiles. Instead of altering the base code with flags I just copied it over into 1856's Track and removed the check
Fixes #5959

Fix 1856 not allowing dits to downgrade

---

lib/engine/game/g_1846/game.rb

I accidentally put the output in the 'corp removal' loop, which fires twice in 2P
closes #5977

[1846] only output list of privates once

---

routes/game.rb

We want to use this to have the same setup for everyone in the 18Zoo tournament

Allow setting the seed manually when creating a game (api only)

---

assets/app/view/game/abilities.rb
assets/app/view/game/company.rb

1 - add size to the company name on card
2 - add brackets around first initial of size (shown on player card and ability usage)
Totally open for input
1 --
2 --
@Zwergenpunk 
closes #5984

[18CZ, others] add priv. company size to name

---

lib/engine/game/g_1893/buy_company.rb
lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_minor.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/step/buy_company.rb

This commit makes it possible for the active player to purchase
the EVA company (for any amount - upto cash limit) at two times:
- During the stock round (is not counted as an action)
- During train purchase step
The purchaser is the active player, not the minor/corporation.
The purchaser pay.
Note! The rules does allow for buy/sell at any time, and this
would also be regarded as an action, for determination of first
player, but this implementation is a simplication that should
be good enough to at least give the players an option to buy EVA.

[1893] Add possibility to purchase EVA from other player

---

lib/engine/game/g_1822/game.rb

closes #5986
Modified info screen to add `Minors receive...` at the relevant phases
Relevant rules: (at bottom)
closes #1822

[1822] emit info about minor capital

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb

closes #5953
Works with sample game at issue
May archive / break games
Main bugfix is [player paying the bank before the bank pays to start the minor](https://github.com/tobymao/18xx/pull/6002/files#diff-6f471d381e596c4a0bbf760e2a864407e25b795b3b92366d07243f764397547dR116) which incorrectly breaks the bank as 1K+ gets paid out of the bank often in games
Minor bugfix is [player buying the presidency and then paying the difference later](https://github.com/tobymao/18xx/pull/6002/files#diff-6f471d381e596c4a0bbf760e2a864407e25b795b3b92366d07243f764397547dL98) instead of giving the player a temp loan, which could incorrectly break the bank theoretically

[1822] pay to bank before floating company

---

assets/app/view/game/part/city_slot.rb

Since #5940 was logged, making the extra tokens more easily differentiated is important. I looked at some of the other filters available and none of them looked like they would be great (although the inverse filter could be potentially useful at some point) 
Instead I'm opting for putting a dashed border around the token to differentiate it from other tokens that live inside the "normal" slots of the city
Tokens that DO occupy slots look the same as usual

Add dashed border for extra tokens to more clearly differentiate them

---

lib/engine/game/g_1882/game.rb
lib/engine/game/g_1882/step/special_nwr.rb

If the NWR owner places a token on a NWR tile, the token they used
would cost zero, and then they wouldn't be able to use the NWR ability
fixes #5879

1882: Fix behaviour if NWR owner places token on NWR tile

---

lib/engine/game/g_1856/step/escrow.rb

This provides a description for Escrow which notifies the user to undo. This is somewhat possible in 1856
because the game takes somewhat long (~2 seconds by the end of the game) to replay for an undo so a race
condition with the server is possible.
FIxes #6035 
This adds a description to a step so it will not need pins or archiving games.

In timing issues w/ 1856, if an incorrect pass gets given to Track, escrow does not get passed.

---

lib/engine/game/g_18_cz/game.rb

This should help prevent the trap of people buying a `4e` when they want a `3E` ;)

18CZ: Highlight trains a corp cannot run

---

assets/app/view/game/buy_trains.rb

I like this suggestion from @dfannius
related to #5966

[1862, others] make inoperable trains gray while buying

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/buy_sell_par_shares.rb

First 3 certificates sold of KKK must be 20% each.
KKK gets 6 times par price in treasury when floated.
Set Double mark on the correct KKK certificates.

[18Rhl] Corrected KKK handling

---

lib/engine/game/g_18_ka/game.rb
lib/engine/game/g_18_ka/step/special_token.rb

May as well put in some work on 18KA
This implements the 3 tile locking privates. 9 more to go.
It doesn't implement the rule that 
```
If this private is closed in Phase 5 while owned by a player, the player immediately places the tile in
one of the Equatorial hexes. If multiple Equatorial privates are in player’s hands when they are closed
at the start of phase 5, this is resolved in clockwise order starting with the player that bought the 5 train
```
for each of the tile locking privates, but that's a stupid rule (the game setup is to randomly remove some of the privates at the start..) so I'll have to update the rules instead

18ka tile locks

---

lib/engine/game/g_1840/map.rb

I presume F8 and F10 need updated, instead of F7/F9 as noted in the issue (the latter are not on the map)
closes #6059

[1840] fix dit values on F8,F10

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/assign.rb
lib/engine/game/g_18_usa/step/dividend.rb
lib/engine/game/g_18_usa/step/special_track.rb
lib/engine/game/g_18_usa/step/track.rb

This batch is the bridge, oil, coal, and iron privates in 18USA
I made some special tiles for coal, oil, and iron in the game because the `tile_lay` ability was more natural to work with than `assign` when dealing with how the iron token "can be flipped with a tile upgrade action" in green phase and tiles with oil tokens can be upgraded and automatically update their revenue.

18 usa privates batch2

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/dividend.rb

1. Avoid repeated home location tokening for CCE
2. Disallows 8 train routes if not RGE terminus or use non-RGE offboard
3. Requires at least price revenue for increase stock price

[18Rhl] Three minor fixes

---

lib/engine/game/g_18_rhl/game.rb

This reverts commit 260556f140f8aefd0d9fd47fdf384bba1d3f247f.
New attempt will be done for this, due to review comments,
and also that it contained a bug.

Revert "[18Rhl] Forbid route to same Rhine Metropolis city"

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/step/bankrupt.rb

Fixes #6062 
Also fixes a bankrupt player holding onto cash if they didn't have a corporation to hand off to another player

18VA: Don't scrap trains on bankruptcy

---

lib/engine/game/g_1836_jr56/game.rb

I noticed this while working on autoactions in 1856. This will require pinning some games most likely? It's also possible that nobody's really playing 1836jr56

1836jr56 uses 1856 SR rules

---

lib/engine/game/g_1856/step/buy_sell_par_shares.rb

This will require some games to be pinned as this will cause the buy-until-float autoaction to end quicker
Fixes #5525

1856/1836jr56: Stop buy-until-float autoaction on floatable?

---

lib/engine/game/cities_plus_towns_route_distance_str.rb
lib/engine/game/g_1828/game.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_18_al/game.rb
lib/engine/game/g_18_co/game.rb
lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_ga/game.rb
lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_mex/game.rb
lib/engine/game/g_18_ms/game.rb

Omits the "+N" if there are no towns
Fixes #2170

Added module for M+N display of route length for games with friendly dits

---

lib/engine/game/g_1822/entities.rb

Based on the suggestions in the linked issue I added short descriptions to the names of the 1822 privates. It looks like this will not require pinning anything
Fixes #4947

Add short descriptions to the name of 1822 privates

---

lib/engine/game/base.rb
lib/engine/game/g_18_cz/game.rb

closes #6078 
Issue caused with bugfix in 
https://github.com/tobymao/18xx/commit/a4b1a5f35f736f9640011a79a2377f53828a083c#diff-c424fe765fa42b21004cdcbd52a9601b7ff9351f061d04cacec49f40973a2bb1R42
Also add this function to base (throws NotImplemented) , so games with similar mechanics will throw an instructive error at lint-time

[18CZ] fix EMR by implementing `company_sale_price` func

---

lib/engine/game/g_1817/step/track.rb

Rules as written privates never close in 1817. This fixes #6087 (the other companies close upon use, which implies they aren't owned by a player)

Don't kill the pittsburgh private in 1817 if it's owned by a player

---

assets/app/view/game/part/borders.rb
lib/engine/game/g_1836_jr30/game.rb
lib/engine/game/g_1836_jr56/game.rb
lib/engine/part/border.rb
lib/engine/tile.rb
spec/lib/engine/games/config_spec.rb

I also made impassable borders slightly thicker to make them look different from passable borders. We may want to emphasize the difference a little more in a future PR
Fixes #3269 
(I think I have different colors set up on my local v 18xx.games hence the difference in shades of blue)
before
after

Allow for colored borders; use it in 1836jr to make impassable borders blue

---

assets/app/lib/hex.rb
assets/app/view/game/hex.rb
lib/engine/part/base.rb
lib/engine/part/stripes.rb
lib/engine/tile.rb

This does not do any rules enforcement as to what they mean however. Tagging @volker18xxdev as they were working on 1829 and filed a bug for visibility and functionality of these tiles

Allow rendering of striped tiles by adding a Stripes part

---

lib/engine/game/g_1893/step/buy_sell_par_shares.rb

This probably only applies when trying to buy an AdSK bond late
in the game.
This might break games as it was previously possible to buy
AdSK bonds to exceed cert limit (although those had to be sold
to be allowed to pass in SR), so any games this break can be
pinned (or archived if finished).
I intend to set 1893 to beta when this PR is deployed.

[1893] Do not allow buy of company when cert limit reached

---

lib/engine/game/g_18_mag/game.rb

closes #6095 
This removes the `CitiesPlusTownsRouteDistanceStr` function from the game script, which doesn't seem to break anything
This function was breaking games since it [causes the train distance string to be used as part of a math operation here](https://github.com/tobymao/18xx/blob/master/lib/engine/game/cities_plus_towns_route_distance_str.rb#L10)

[18Mag] fix issue with string operations

---

assets/app/view/game/buy_power.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/step/buy_power.rb
lib/engine/tile.rb

Updated buy_power step to implement correct rules for EMR.
Fixed an issue with update_route_trains not saving trains correctly
Fixed an issue with setting ignore_gauge_* in Tile where I forgot to clear path caches in Node and Junction.
Fixed an issue with reusing trains where I forgot to clear the "operated" flag when shuffling trains around.

18Carolinas: updated EMR code; bug fixes

---

lib/engine/config/tile.rb
lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/special_track.rb

1. Orange need to be put into COLORS so that sort of tiles work.
(So far only 18Rhl uses orange for any tile, but it is general.)
2. Fix private No 3 (Seilzuganlage) so that only allowed tiles can
be used in the selected hex.

Fix two bugs related to 18Rhl

---

lib/engine/game/base.rb
lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_sj/meta.rb
lib/engine/game/g_18_sj/round/auction.rb
lib/engine/game/g_18_sj/round/requisitions.rb
lib/engine/game/g_18_sj/round/stock.rb
lib/engine/game/g_18_sj/step/buy_company.rb
lib/engine/game/g_18_sj/step/buy_train.rb
lib/engine/game/g_18_sj/step/dividend.rb
lib/engine/game/g_18_sj/step/requisition.rb
lib/engine/game/g_18_sj/step/token.rb
lib/engine/game/g_18_usa/round/stock.rb
lib/engine/round/stock.rb

This 2 player variant adds a 3rd player, a bot, that is
partly automatic, and partly handled by the players, via
master mode. The bot is excluded from the value/result.
More details in the 18SJ rule book.

[18SJ] Add special 2 player variant

---

lib/engine/game/g_18_carolinas/game.rb

Fixes #6124 
Also allow increasing train size even if total of trains is over corporate power
No archiving required.

18Carolinas: relax southern track restrictions post phase 5

---

assets/app/view/game/part/label.rb

closes #6129
This does result in some other labeled cities changing, see examples below
before:
after:
before:
after:
Note that IMO this better / more consistent, since Toledo's LSL `icon` is similarly under the city slot already
before:
after:

allow labels to be on right side

---

lib/engine/game/g_18_sj/game.rb

Oscarian Era variant uses 1830 style IPO prices.
Standard 18SJ uses incremental capitalization at the start, and uses
market price.

[18SJ] Correct IPO price in Oscarian Era variant

---

lib/engine/game/g_18_rhl/game.rb

The partitioning in the three Rhine Metropolis hexes is more a cosmetic
detail. It has no play effect, as the partitioning is removed when the
hexes are upgraded to green, which is when the hex can be passed from
one side of the Rhine to the other.

[18Rhl] Make Rhine appear as blue partitioning

---

lib/engine/game/g_18_carolinas/game.rb

Rule change for 5P and 6P games: instead of presidencies, 5th player gets PD and 6th player gets to follow PD.
Existing 5P/6P games (if any) will need to be archived.

18Carolinas: rule change for private distribution

---

lib/engine/game/g_18_sj/game.rb

Corrected so that only Brown and Orange shares can be redeemed in
multiple shares.
Corrected redeem price for yellow and orange shares.

[18SJ] Correct redeem (fixes #6150)

---

assets/app/view/game/round/stock.rb
lib/engine/company.rb
lib/engine/game/base.rb
lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_minor.rb
lib/engine/game/g_1893/step/buy_sell_par_shares.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb
lib/engine/game/g_1893/step/starting_package_initial_auction.rb

Show only one bank owned bond in stock view.
Make name of bank owned bonds dynamic to show the number of
bonds bank own. The name of non-bank owned bonds always have
the same name.
Name of minor connected companies changed to make it less
confusing compared to bonds.
Some minor cleanups, including descriptions of minor connected
companies.
Small refactoring of general code:
1. make it possible for 1893 to override which companies to show
in the stock view.
2. change name attribute of company to an accessor to make it
possible for 1893 to use dynamic name of companies

[1893] Improve presentation of bonds

---

lib/engine/game/g_18_co/game.rb

Fix https://github.com/tobymao/18xx/issues/4817
If the corporation's starting city has been removed as it was merged into a greater city ( see: Denver ) then get_slot would return nil. We need to check if that city still exists, and if not, use the 0 city.

Fix 4817 - 18CO Starting Slot Late Game

---

lib/engine/game/g_18_co/game.rb

Fix https://github.com/tobymao/18xx/issues/5909
This changes limits the EMR bundles to only one option - the bundle that will allow buying the cheapest train. Before: Bundles worth more would trigger a "Cannot Sell Bundle" error, and thus were useless to show in the display. Smaller bundles were useless because the player would just have to keep issuing anyway.
Why Pins? - Games where a player issued one share multiple times will fail as that bundle no longer exists. I don't know how often if ever that occurred but its a distinct possibility.
Before:
After:

Fix 5905 - 18CO EMR Bundles

---

lib/engine/game/base.rb
lib/engine/game/g_18_texas/game.rb

Games with intra-tile paths can allow the autorouter to select routes with duplicate paths.

Add intra-tile paths to check_overlap

---

lib/engine/game/g_18_co/game.rb

This logic is incomplete. There are times when a player should be able to issue fewer shares than is required to buy a train, example when they can't issue enough to afford the cheapest train. Will need to rethink this.

Revert 18CO EMR change

---

lib/engine/auto_router.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1873/game.rb
lib/engine/part/revenue_center.rb
lib/engine/route.rb

Modified autorouter to handle intra-tile paths correctly (1860, 18Mex, 18Texas, 18MS).
Modified 1860, 1862 and 1873 to deal with the autorouter path pruning algorithm (i.e. skip them if route.routes is empty).
Modified Part::RevenuCenter to bail gracefully (needed for 1862 offboards with the autorouter).
Modifed Route to display more useful error information when checking chains.
Fixes #6100

Autorouter fixes for 1860, 1862, 1873, 1849, plus probably more

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/round/stock.rb
lib/engine/game/g_18_va/step/buy_sell_par_shares.rb
spec/fixtures/18VA/49936.json

Rename the "medium" and "large" company types to "5 and 10 share" companies
This primarily affects the `Info` tab

[18VA] medium, large => 5share,10share

---

lib/engine/game/g_18_va/game.rb

Clarifies that train buying is limited to "one per type per OR" up to phase 6

[18VA] add text for limited train buys

---

lib/engine/game/g_18_co/game.rb

Fix https://github.com/tobymao/18xx/issues/5909
The return is "all bundles that do not allow buying any train, plus the one bundle that allows buying the cheapest train, if it exists."
I ran tests on this to ensure I did not wind up with unexpected nils.

Fix 5909 - remove 18CO EMR extra options

---

lib/engine/game/g_18_eu/game.rb

A corporation must be connected to the minor in order for it to be eligible for exchange.
Map:
Before:
After (active player owns 13 but not 15):

18EU - Only exchange connected minor

---

lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/map.rb
lib/engine/game/g_18_carolinas/step/convert_track.rb
lib/engine/game/g_18_carolinas/step/track.rb

Changes from the designer (Scott):
* Phase 3 is only Yellow tiles, and only 1 OR
* Phase 5 is only Yellow and Green tiles, and only 2 ORs
* Track conversion now begins at the start of Phase 6, and now involves a "voting" mechanism where the number of pure Southern track tiles and pure Standard (Northern) track tiles are compared. The majority becomes the dominant track gauge for the remainder of the game
* All tiles are now double-sided, with Standard track on one side and Southern on the other.
This is a substantial change which will invalidate most games in progress.

18Carolinas: modify phases, add "voting" for final track

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/lay_tile_checks.rb
lib/engine/game/g_18_rhl/step/special_track.rb

Tile 935 requires special handling. It has only one possible rotation
and is orange.
Do not allow upgrade to Osterath in phase 5 or later
Remove ability (if not used) when phase 5 starts.
Also correcting spelling of Osterath.

[18Rhl] Make it possible to lay Osterath tile

---

lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/map.rb
lib/engine/game/g_18_carolinas/step/buy_power.rb
lib/engine/game/g_18_carolinas/step/track.rb

Fixes #6216 
Also removes "voting" (and double-sided brown and gray tiles).
Also checks to make sure extending track is done in existing gauge.
Most existing games will need to be archived.

18Carolinas: more rule changes

---

lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/step/buy_minor.rb
lib/engine/game/g_1893/step/starting_package_forced_auction.rb
lib/engine/game/g_1893/step/starting_package_initial_auction.rb
spec/fixtures/1893/46448.json

Also some clean up of drafted company.
This commit most likely break all 1893 games, so I suggest pinning
unfinished games, and archiving finished games.

[1893] Improve player order after drafting (fixes #6204)

---

assets/app/view/game/corporation.rb
assets/app/view/game/player.rb

In e.g. 18Rhl there are two double certificates in corporation KKK.
With this commit if both certificates are in the same location
'dd' is shown. 'd' is used for single double certificate as before.
Here is how it looks like in 18Rhl - only KKK has double shares.

Make it possible to show multiple double certificates

---

assets/app/view/game/spreadsheet.rb

56 has a concept where the company is not "floated" but is able to operate in the next round:
This changes the "show floated companies" view to include those "will operate" companies as well
No change for other games, such as 46:

[1856] genericize spreadsheet view 'floated' => 'will operate'

---

assets/app/view/game/spreadsheet.rb

This makes the links that toggle "hide/show unfloated companies" a bit more obvious since they use an action verb instead of `all`
Default view:
After toggling:

Make spreadsheet visibility options a bit more clear

---

lib/engine/game/g_18_texas/game.rb

18Texas - Define buying power to be equal to treasury (not including treasury shares)

---

assets/app/view/game/player.rb
lib/engine/game/base.rb
lib/engine/game/g_18_rhl/game.rb

Priority Deal is now shown continuously (in the SR) for the player
that has the most cash. (If two or more share this, the PD is shown
for the player after last to act.)

[18Rhl] Update Priority Deal handling

---

assets/app/view/chat.rb

Attempts to fix #4656 again after recent occurrences.
Adds a form tag around the chat input on the home page. This appears to prevent Safari from detecting the input as part of a login form when certain keywords are in the chat log.
Steps to replicate:
- Use MacOS Safari to create an account, electing to save your password. (Thanks BrowserStack)
- Logout
- Login using the saved password.
- Enter a chat message with the string "username"
- Refresh the page
- Click on the chat input and observe the option to fill in the form with your username.

Prevent Safari treating chat input as username field

---

assets/app/view/game/tools.rb

For #5297
I thought for a while about the other suggestions but not sure they'd be better - default text in the input box wouldn't be needed after one or two appearances, and the button would create two disconnected ways to do the same thing.

player notification info sentence in tools tab

---

assets/app/view/game/game_log.rb

Fixes #4656 in the game chat in the same manner as #6252 
In this case the form tag interfered with the width of the input field, thus the need for the `display: contents` style.
Note that the game chat seems less prone to triggering the autocomplete depending on what other text is present, but it is still possible:

Prevent Safari using game chat as login form

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/track.rb

From https://github.com/tobymao/18xx/issues/792
In 18EU, 120 cost mountains turn into 60 cost rough after a tile is laid on them. In the physical game, there are double sided tokens to represent this.
Note: I can't help but feel like I might be missing the easier/cleaner way to implement this.
Before Tile Lay, the hex SE of Basil is 120 cost:
Ater Tile Lay, the hex SE of Basil is 60 cost:

18EU Mountain Upgrade

---

lib/engine/distance_graph.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1825/round/operating.rb
lib/engine/game/g_1825/step/buy_train.rb
lib/engine/game/g_1825/step/dividend.rb
lib/engine/game/g_1825/step/route.rb
lib/engine/game/g_1825/step/track_and_token.rb

Add all of the receivership rules, except for dealing with the "imaginary 9th share" when buying the president's cert.
Implemented halt functionality
Common files:
* Engine::DistanceGraph - will now ignore nodes that have a 0 visit_cost.

1825: receivership and halts

---

lib/engine/game/g_18_texas/entities.rb
lib/engine/game/g_18_texas/game.rb
lib/engine/game/g_18_texas/step/special_track.rb

- Limit tile lays to phases 3-4
- Allow NOPR private to upgrade directly to green 511 tile (this counts as an upgrade)

18Texas - Revise private company powers

---

assets/app/view/game/auto.rb
lib/engine/action/program_independent_mines.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/convert.rb
lib/engine/game/g_1873/step/track.rb
lib/engine/step/program.rb

This adds an auto program for Harzbahn 1873 to automate independent mines, which currently are a big drag on game speed due to their large number and mostly trivial actions.
The first commit contains the program, the second commit extends the UI to allow disabling each of the three actions a mine can perform separately.
Code passed rake, but I'm a total beginner at ruby and github, so there's probably room for improvement still.

Auto independent mines

---

assets/app/lib/hex.rb
assets/app/view/game/part/town_location.rb
lib/engine/config/tile.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb
lib/engine/tile.rb

* Implement "Sepia" tiles to distinguish pre-printed non-upgradable track from gray tiles. A nice side-effect of this is that I no longer need stubs on the gray borders in order to lay track against them.
* Fix rendering of "Halt" tile 11
* Minor tile tweaks
* Implement final kits K1, K6 and D1

1825: rendering fixes; K1, K6 and D1

---

lib/engine/game/g_18_cz/step/draft.rb

Output log now includes private size after purchase

[18CZ] emit private size after purchase

---

assets/app/view/game/spreadsheet.rb

This shows obsoleted trains on the spreadsheet in parens, same way they are shown on the corp cards
)

show obsoleted trains on spreadsheet tab

---

assets/app/view/game/spreadsheet.rb

closes #6405
this should also fix sorting in 1822 etc.
No idea how to solve that without regex and no `corporation.id.to_i.to_s == corporation.id`

Fixed sorting for numbers

---

lib/engine/round/base.rb

Tested companies in 1846 and 1817.
Tested auto actions in 1822, 1867, and 1870

Enhance active_step to work when a corporation or player entity passed in.

---

lib/engine/game/g_1893/game.rb

checked the rules and market on BGG which seems to indicate that the green box is meant to be AGV par price
closes #6500

[1893] fix par value names

---

lib/engine/part/city.rb

closes #6530 
Tested with cases:
1 - IC attempts to token Terra Haute, which it can't afford
https://gist.github.com/benjaminxscott/4526e3d9603ea5d9df8218f254e5c2c5
2 - NYC attempts to token Erie, where it already has a token
https://gist.github.com/benjaminxscott/d94992f37484341daa179eb9c262112d
3 - GT attempts to token Erie, which has a reserved slot so it has no open slots
https://gist.github.com/benjaminxscott/14743b143adca8253140b918607a37d6

add error messages if unable to token

---

assets/app/view/game/part/city_slot.rb

Same technique as used for issue_shares for 1846. This will be used for 18NY, provided it doesn't cause any major issues with other games; however, it's hard to test as it's a view code change. It shouldn't affect games as they shouldn't have non-blocking steps, prior to the current blocking step, with the 'place_token" or 'remove_token' action as they wouldn't have been possible to use before this change. I did test with 1817 since it has a token selection at the corporation auction, a regular token placement, and remove tokens if over the limit after acquisition and they all worked as expected.
In general, I don't know why all view logic doesn't act like this. It would create a lot more flexibility for non-blocking steps, but one step at a time.
I've kept the PR as only this change, so …

Make place_token and remove_token actions possible for non-blocking steps

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/meta.rb
lib/engine/train.rb

Fix route distance for diesels, show which stops the 5DE scores in the route str, 5DE only needs to run one of its stations, not score it, and add optional rule for 5DE to only run stations and offboards.
Now also includes the fix for the linked bug and a symbol vs string fix.

[18NY] 5DE train

---

assets/app/view/game/pass.rb
assets/app/view/game/pass_auto_button.rb

The button enables the auto pass in stock round program, same as the auto tab, but more accessible. The motivation is half to encourage more use of auto pass and half to make it less annoying when auto pass keeps getting cancelled over and over because someone sells and buys and sells and buys...
Only displayed for the active player, only in stock around, and does not show up in hotseat games.

Add "Auto pass" button in stock rounds.

---

lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_18_cz/step/buy_train.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/meta.rb
lib/engine/game/g_18_ny/step/buy_train.rb
lib/engine/game/g_18_ny/step/track.rb
lib/engine/step/train.rb

- Player is not restricted to buying the cheapest train when emergency issuing; however, they become restricted the moment they contribute player cash or take loans.
- Offboard logic wasn't working for offboard areas that were cities, so use color instead
- Springfield's 2 hexes should act like one when calculating train distance
- Minor clean-up
I removed a check that didn't make sense. Whether the entity has more money than the cheapest train or not is irrelevant to is it the cheapest train. It broke 18NY, where a loan can put you over the cost, but is still considered emergency fund raising.

[18NY] Bug fixes from designer feedback

---

lib/engine/step/buy_sell_par_shares.rb

Example of internal action is winning a bid in 1817.
https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1817/step/buy_sell_par_shares.rb#L364
```
action = Action::Par.new(entity, corporation: corporation, share_price: share_price)
process_par(action)
```
This action never passes through game/base process_action, so it never gets an id assigned. It does get tracked by track_action, however, so the shenanigans code needs to be able to process it.

Handle internal actions with no action id in shenanigans check.

---

lib/engine/step/buy_sell_par_shares.rb

Example:
```
-- Disabled programmed action due to 'NYSW took a loan'
```
Fixes #5861

Add proper shenanigans message for taking loans.

---

assets/app/view/game_row_filters.rb
lib/engine.rb

Include variant titles (e.g. 1822NRS) in game title filter options.

---

assets/app/view/game/auto.rb
lib/engine/action/base.rb
lib/engine/action/program_buy_shares.rb
lib/engine/step/buy_sell_par_shares.rb

The switch only happens if the auto-buy program completes successfully, not if it gets interrupted by shenanigans or inability to buy the specified shares.
Fixes #6483

Add option to automatically switch auto-buy to auto-pass when done.

---

assets/app/view/game/auto.rb
lib/engine/action/base.rb
lib/engine/action/program_buy_shares.rb
lib/engine/action/program_independent_mines.rb
lib/engine/action/program_merger_pass.rb
lib/engine/action/program_share_pass.rb
lib/engine/game/base.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/program.rb

NB: The first two commits are from #6608
Implementation-wise, removes the unused description method and replaces the print_name method with a standard to_s returning detailed descriptions of the action. Also modifes the game log to include this description every time the program is enabled and disabled.
Example messages:
Enabled programmed action 'Buy SAL from IPO until floated'
Enabled programmed action 'Buy SAL from IPO until 3 shares'
Programmed action 'Buy SAL from IPO until 3 shares' removed due to round change
Enabled programmed action 'Pass in Stock Round'
Disabled programmed action 'Pass in Stock Round' due to 'Shares were sold'
Enabled programmed action 'Pass in AR (PW, R) and MR (PW, R)'
Fixes #4891

Add detailed descriptions of auto actions in game log

---

lib/engine/action/program_merger_pass.rb

Original impl always displayed values for AR and MR, but some titles use merger pass with a different phase set. E.g. in 1861 there's only the MR and no AR.
Makes the description use the phases recorded in @corporations_by_round instead of hardcoding AR/MR.
1861 example:
-- Programmed action 'Pass on mergers in MR (KK, MV)' removed due to round change
#4891

Make merger pass to_s dynamic based on phases recorded.

---

assets/app/view/game/auto.rb
lib/engine/action/program_share_pass.rb
lib/engine/step/buy_sell_par_shares.rb

Add an option to make SR auto-pass unconditional. The option bypasses the entire should_stop_applying_program call tree in buy_sell_par_shares, which also stops calling into game-specific overrides of that method and/or action_is_shenanigan?.
Add an option to make SR auto-pass indefinite. This intended mainly for use where the game drags on beyond SR relevance, e.g. late 18CZ. Can also be used together with the unconditional option to essentially drop out of a game.

Add support for unconditional and/or indefinite auto pass

---

lib/engine/step/special_token.rb

This line was translated incorrectly in PR #4932. Following the call chain, the line determines if the place_token action is returned for the company and thus if it is shown in the UI or not. The bug would manifest as the company not being selectable in the UI when all the corporation's tokens are used, even if from_owner is false and would show in the UI when the corporation has no tokens, but extra_action is true.
Note: Tokener is correct, as long as the ability showed up in the UI, it would behave correctly.

Extra tokens are tied to !from_owner, not extra_action

---

lib/engine/game/g_18_ireland/game.rb

All bids (both in the private auction and when starting 5-share companies) must be multiple of £5 as per the rules: https://boardgamegeek.com/filepage/219076/18ireland-rules-mass-production-version.

18Ireland - bids must be multiples of 5

---

public/assets/main.css

Fixes the issue when Lato font does not have glyphs (e.g. with Cyrillic symbols on the screenshot). In this case a serif font is used, while a sans-serif was definitely meant to be.

Fix invalid font used when Lato does not have glyphs available

---

lib/engine/game/base.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb
lib/engine/game/g_1822_mx/game.rb
lib/engine/round/draft.rb
lib/engine/round/stock.rb
lib/engine/step/program.rb
spec/fixtures/1822/hs_lxemeslq_30797.json

Convert 1822 shenanigans checking to use action_is_shenanigan? only.
This fixes the problem where being outbid and then setting an auto action still results in the auto action being cancelled.
Fixes #6626
Has two associated clean-up commits. The first one makes setup get called properly on the initial round of a game, the second cleans up 1822 a bit to make the main change (the third commit) more focused.

Better 1822 shenanigans

---

routes/game.rb

Use a fixed 'unstarted' value for round name when creating (unpopulated) games.
Trying to init the game before anyone joins breaks due to https://github.com/tobymao/18xx/commit/069b5b9952ad458a4af4d1ed79fe0efe241f71e9 adding a call to round.setup and the stock round setup logic calling code that eventually tries to operate based on the number of players (which is zero).
The round name is only rendered once the game is started, and the value is replaced at start time, so any dummy value should do fine here.
Improvements to round.setup are also possible (e.g. pass in an arg saying it's the initial round, so it avoids running unnecessary skipping logic), but this seems like the simplest fix.
Fixes #6657

Fix being unable to create games that start with a stock around.

---

lib/engine/step/buy_sell_par_shares.rb
spec/fixtures/1889/hs_lhglbbiz_17502.json

Auto-buy programs would not mark themselves as complete if buy_shares was not an available action (a common scenario when spending all your money to float). Formerly only a nuisance, but with the option to transition to auto-pass it actually breaks that functionality. Easy fix, just check for completion before checking if buying is allowed.
This *will* change behavior for buy X shares programs in buy-sell titles. They would previously generate a pass action after the last buy and terminate on the next turn. Now they will terminate after the last buy and not generate a pass (unless conversion to auto-pass is enabled). This seems like an improvement since the option to auto-pass exists, and the default behavior has been aligned with buy until float.
I've fixed the one fixture that was …

Check for auto-buy completion before checking available actions.

---

lib/engine/game/base.rb

I think I found an error. The way on_phase checking was handled resulted in such ability:
```
{
type: 'revenue_change',
revenue: 0,
on_phase: 'Brown',
owner_type: 'corporation',
},
```
triggering upon the sale of the company. Indeed the whole line was skipped since `on_phase` was `nil`.

Fix ability_right_time? (on_phase check)

---

.rspec_parallel
Gemfile
Gemfile.lock
Rakefile

Also set as the default rake action instead of regular spec.
Runtime on my machine (quad core) is reduced by 25-50%, depending on overall system load.
50% is the maximum possible speedup as there's a single spec that takes half the overall time, and parallel_tests won't split up individual specs. Splitting up the large specs (assets_spec and game_spec) is one option, investigating e.g. parallel_split_tests is another.

Add rake action spec_parallel for running rspec in parallel.

---

lib/engine/game/base.rb
lib/engine/game/g_1862/step/track.rb

Fixes #6515 (not just 1862-specific)
Add sanity check to tile lay actions for 1862.
This will likely require some 1862 games to be pinned.

Fix end game message

---

lib/engine/game/g_1822/round/stock.rb

The stock around setup method will skip players who have no legal actions. A skip translates into a pass action, and in 1822 that updates the winning bids, but the winning bids hash was not created before calling super.
Fix is creating the hash before calling super.

Don't crash if stock.setup skips a player.

---

lib/engine/game/g_1893/game.rb
lib/engine/game/g_1893/round/operating.rb
lib/engine/game/g_1893/step/potential_discard_trains_after_merge.rb

1. Do not show any abilities in UI during ORs
2. Fix bug when passing prematurely during discard of trains
(Pass was previously an option even though train limit exceeded)
3. Correct UI handling of merge (fixes #6624)

1893: Fixes for abilities and merge UI

---

lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_sj/step/route.rb
lib/engine/game/g_18_sj/step/token.rb

Contains two fixes:
- Making SJ tokens passable is now done after the token step
so that current entity cannot affect track or token through
a blocked city, even if SJ token is there.
- If current entity makes a non-E route it cannot pass through
a blocked city, even if SJ token is there.
Fixes #6676

18SJ: Fix side effects for E trains

---

lib/engine/game/base.rb

Minor was excluded from crowded corps check, which meant that a title
like 1893, which have decreasing train limit for minors, would not
discard trains in a correct way.
Fixes #6509

Train limit change should affect minors as well

---

assets/app/view/game/par.rb
lib/engine/game/g_18_new_england/entities.rb
lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/map.rb
lib/engine/game/g_18_new_england/round/first_stock.rb
lib/engine/game/g_18_new_england/step/buy_sell_par_shares.rb
lib/engine/game/g_18_new_england/step/buy_train.rb
lib/engine/game/g_18_new_england/step/dividend.rb
lib/engine/game/g_18_new_england/step/issue_shares.rb
lib/engine/game/g_18_new_england/step/redeem_shares.rb
lib/engine/game/g_18_new_england/step/reserve_par_shares.rb
lib/engine/game/g_18_new_england/step/track.rb
lib/engine/game/g_18_new_england_north/entities.rb
lib/engine/game/g_18_new_england_north/game.rb
public/logos/18_new_england/CLOSED.svg

* Fix issues with ISR (consecutive passing and snake order)
* Make market 2D to allow choice of top or bottom minor share value
* Tile upgrade rules for pre-printed track
* Tile 63 vs 611 rule
* 1/2 dividends
* minor train buying rules
* minor liquidation
* share redemption and issuing (not tested)
Common file change:
* UI:par - don't print parenthetical info on par values for companies that have 100% president shares

18NewEngland - ISR, SR fixes. First pass OR steps

---

assets/app/view/game/actionable.rb
assets/app/view/game/round/auction.rb

Automatically show the draft / player info in non-hotseat games when the logged-in user is the active player.
Not automatically displayed to logged-out users in case they're a player with expired cookies, not automatically showing in hotseat since it'd reveal too much in actual hotseat play.
Also fix hotseat games where one of the players has the same name as the logged-in user. The old code would detect this as it being someone else's turn and require master mode.
Also factors out a hotseat? method in actionable for reuse.

1846 show draft to active player

---

assets/app/view/game/pass.rb
assets/app/view/game/round/auction.rb
assets/app/view/game_page.rb

PassButton and Auction both use the same stored need, so there's no need to pass it explicitly from GamePage and Pass.

Remove redundant explicit passing of needs.

---

lib/engine/game/g_18_new_england/entities.rb
lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/meta.rb
lib/engine/game/g_18_new_england/step/bankrupt.rb
lib/engine/game/g_18_new_england/step/buy_train.rb
lib/engine/game/g_18_new_england/step/issue_shares.rb
lib/engine/game/g_18_new_england/step/merge.rb
lib/engine/game/g_18_new_england_north/entities.rb
lib/engine/game/g_18_new_england_north/map.rb
lib/engine/game/g_18_new_england_north/meta.rb

* Add express train rules
* Player bankruptcy rules
* Add merger auto pass
* Make "18NewEngland 2" an option on 18NewEngland
* Add reservation highlighting for available minors on first stock round
* Fix ordering of par values for minors
* Numerous playthrough fixes
* Server-sourced bug fixes

18NewEngland: Express trains; Merger auto actions; playthrough fixes

---

lib/engine/game/g_1817_de/meta.rb
lib/engine/game/g_1877/meta.rb
lib/engine/game/g_18_texas/meta.rb

1877
18DE
18Texas
Rules may change for these, but the prototype warning is sufficient, no need for extra warnings for alpha.

Move prototypes to prototype-production

---

lib/engine/game/g_18_new_england/game.rb

Allow IPO and Treasury shares to be displayed in spreadsheet.

18NewEngland: Show separate IPO+Treasury shares in spreadsheet

---

lib/engine/game/g_18_new_england/game.rb

Fixes #6736 
This doesn't add player colors, but does distinguish between unavailable, available, reserved, and formed.

18NewEngland: reservation UI improvement

---

assets/app/view/game/dividend.rb

Fixes #6752 
This actually changes UI::Dividend, but only 18Mag and 1840 use the method with the fix

18Mag: fix dividend input size

---

assets/app/view/game/buy_company_from_other_player.rb
assets/app/view/game/buy_power.rb
assets/app/view/game/buy_trains.rb
assets/app/view/game/buy_value_input.rb
assets/app/view/game/round/auction.rb

Completing what I started with #6752 
Also, the size field for BuyCompanyFromOtherPlayer was just plain wrong
As far as I can tell, these changes don't affect Chrome's rendering.

UI: adjust size for number input forms for Firefox

---

lib/engine/route.rb

[1822] Extra route check
- Added an extra check to see that a local train have a valid route of 1 hex.
fixes #6753
This shouldnt break any games.

[1822] Extra route check

---

lib/engine/game/g_18_new_england/game.rb

Fixes #6800 
This will break nearly all existing NewEngland and NewEngland2 games. Can we please pin these instead of archiving them?

18NewEngland: fix player reordering after first stock round

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/track.rb
lib/engine/game/g_1848/step/tracker.rb

Normal yellow city tiles are used in 1848 for K tiles (with a K token in
the physical copy) which then upgrade to tiles labelled with a K.

1848 Enable K Yellow Tiles

---

assets/app/lib/whats_this.rb
assets/app/view/create_game.rb
assets/app/view/form.rb
assets/app/view/game_card.rb

This is intended to reduce unwarranted hesitancy towards Auto Route. People in chat have said they avoid joining / creating Auto Route games because they think it is mandatory, or doesn't allow manual routing.
Create game page:
Game card:
Could be combined with (or replaced by) linking to a wiki page.
I was originally going to change the string "Auto Route" to something more descriptive, but I couldn't come up with a clear *and* concise replacement.

Add "what's this?" tooltips for Auto Route in game card and create game views

---

lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/map.rb
lib/engine/game/g_1866/step/dividend.rb
lib/engine/game/g_1866/step/first_turn_housekeeping.rb
lib/engine/game/g_1866/step/token.rb
lib/engine/game/g_1866/step/track.rb

- Token must check operating rights
- Export L/2 trains after OR2
- Obsolete trains only runs for half
- You can run on the same double town hex, but you cant run to the same hex on London or Paris
- Implemented port bonus, and it should only work one time on each port per corporation

[1866] Port Bonus

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/operating.rb
lib/engine/game/g_1848/step/tracker.rb
lib/engine/round/operating.rb

Includes a bug fix which could potentially (but probably hasn't) effected other games when the first company in an OR is skipped, or when all companies in an OR is skipped. See c2cae9a.

1848 Enable COM Start and Home Rules

---

assets/app/view/game_card.rb

The invite link should use window.location.host so that the appended invite_url is not continuously added to the end of the url.
https://github.com/tobymao/18xx/issues/6640

invite link should use window location host

---

assets/app/view/game/auto.rb
lib/engine/action/program_harzbahn_draft_pass.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/draft.rb
lib/engine/round/auction.rb
lib/engine/round/base.rb
lib/engine/step/program.rb

Adds auto pass for the 1873 initial draft (the part where you buy a company or wait for the premium to drop).
Two related CLs attached:
* Add auction? method to round.
* Add prefixes to form fields in auto page to avoid collisions.

1873 draft auto pass

---

assets/app/view/game/buy_sell_shares.rb
assets/app/view/game/corporation.rb
lib/engine/corporation.rb
lib/engine/game/g_21_moon/entities.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/round/corporate.rb
lib/engine/game/g_21_moon/step/buy_sell_par_shares.rb
lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb
lib/engine/game/g_21_moon/step/trade_stock.rb
lib/engine/step/buy_sell_par_shares.rb
public/logos/21Moon/DSE.svg
public/logos/21Moon/IC.svg
public/logos/21Moon/LP.svg
public/logos/21Moon/MA.svg
public/logos/21Moon/ME.svg
public/logos/21Moon/MV.svg
public/logos/21Moon/SM.svg

* UI::BuySellShares - allow custom button names when selling corporate shares
* UI::Corporation - handle treasury_as_holding
* Engine::Corporation - add treasury_as_holding option to treat all corporate-held shares the same
* Engine::Step::BuySellParShares - allow overriding of can_dump? method

21Moon: SRs and CRs

---

import_game.rb

The new method sets the password for all users to 'password', to make it possible to interact with imported games when the user already exists (likely from a database dump).
Also changes the password used for imported users to 'password'.

Add fix_existing_users to import_game.

---

assets/app/view/game/round/stock.rb

This fixes a bug with my previous PR for issue #6650 which broke the layout in mobile.

display bank, train_schedule inline-block

---

assets/app/view/game_row_filters.rb

The rename from 1889 to Shikoku: 1889 made it the first (and only) title to have a display title different from the title stored in the database.
Fixes #6871

Fix main page filtering for 1889.

---

lib/engine/game/g_18_eu/game.rb

A train beginning and ending its route in different red hexes gains a bonus based on how many of the corporation's tokens it has run through, limited to a maximum by the phase.
On route selector:
Resulting log:

18EU Red to Red Bonus

---

lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb
lib/engine/train.rb

This need is shared between 1825 and 18EU, so I wanted to make the implementation more generic. The original implementation was tied to the train being an MN type, which did not apply to 18EU.
1825 Tested:

1825/18EU Allow for a train that does not require a token.

---

lib/engine/game/g_18_eu/step/track.rb

"These additional station tokens may be retained as long as they are in non-contiguous City circles: that is, until these cities are upgraded using the brown tiles designated for the purpose. When this occurs, any tokens beyond one in either Berlin or Vienna are removed from the map and returned to the Corporation for reuse: any tokens beyond one in each of “northern” and “southern” Paris are likewise removed from the map and returned to the Corporation for reuse."

18EU Remove redundant tokens after upgrade

---

lib/engine/game/g_18_eu/game.rb

From https://github.com/tobymao/18xx/issues/792
A train may not run more than once to the same City, Town, Port, or Off-Map Location, including separate City Circles in Paris, Berlin and Vienna.
Note: Default implementation already prevents "City, Town, Port, or Off-Map Location", it is only the separate circles that needs special handling.

18EU Cannot stop at Paris/Vienna/Berlin twice

---

lib/engine/game/g_18_eu/step/track.rb

"These additional station tokens may be retained as long as they are in non-contiguous City circles: that is, until these cities are upgraded using the brown tiles designated for the purpose. When this occurs, any tokens beyond one in either Berlin or Vienna are removed from the map and returned to the Corporation for reuse: any tokens beyond one in each of “northern” and “southern” Paris are likewise removed from the map and returned to the Corporation for reuse."

18EU Remove redundant tokens after upgrade (Take two)

---

lib/engine/game/g_18_eu/game.rb

If a Corporation is started, but does not float, prior to Phase 5, and subsequently floats in Phase 5, the five unsold shares are monetized in accordance with the rules below: the last five shares in the Treasury are placed in the Pool and the Corporation receives an additional five times its Starting Value. In effect the Corporation will start with full capitalization, as if it had started in Phase 5, except for the monies received for exchange shares.

18EU New corporations fund all shares in Phase 5+

---

assets/app/view/game/round/stock.rb

The `undefined` element is no longer rendered if the bank is infinite, as in CZ
Games with a bank such as 46 still have it rendered

only show bank when relevant

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_train.rb

See issue #2548 (@benjaminxscott - if you want to update some of those tasks)
- Can buy current Train or Plus-Train now, rather than all train, then all plus-trains, then the next train.
- 2E available when you buy first 5, doesn't count against train limit, doesn't count for compulsory purchase, can only buy 1. Transfers are not yet prevented.
Trains are formatted that takes up more space, but copied the 1846 styling with its variants (and then changed remaining lines for consistency). I hope that's OK.

1848 Trains as variants and 2E Buy Rules

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/step/track_and_token.rb
spec/fixtures/1825/69820.json

Fixes issue raised by @volker18xxdev 
Required minor refactoring of '25 code to handle multiple "blocks_hexes" abilities
Also adds fixture for '25
This should not require pins

1825: add 2nd Midland reservation when using units 1 and 2

---

lib/engine/game/g_18_rhl/entities.rb
lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/map.rb
lib/engine/game/g_18_rhl/step/special_token.rb
lib/engine/game/g_18_rhl/step/special_track.rb
lib/engine/game/g_18_rhl/step/track.rb

P1 (Ratingen): Set attribute that using this does not consume regular
tile lay. Also, restrict so this P1 cannot be used during yellow phase.
P2: Bug fixes: Make tile lay free. Also fixed a crash.
And updated description.
P3: Set attribute that using this does not consume regular
tile lay.
P4: Bug fixes: Make tile lay free, and token cost is not free.
Also fixed a crash. And updated description. This fixes https://github.com/tobymao/18xx/issues/6948
P6: Correct description.
Finally, also do not allow any tile laying of any kind after
a tokening has taken place.
Also have transformed some unused red hexes to gray.

18Rhl: Corrections of privates and map

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/bankrupt.rb
lib/engine/game/g_18_eu/step/minor_exchange.rb
lib/engine/step/bankrupt.rb

From https://github.com/tobymao/18xx/issues/792
If, after selling all the stock he is legally permitted to sell, the President cannot raise sufficient cash to buy a train, he is bankrupt. His remaining holdings are placed in the Pool (for the purposes of this rule only, the Pool may contain more than fifty percent of a Corporation, and the stock price remains unchanged) and he is eliminated from the game. The Presidency of any of his controlled Corporations is transferred to the next eligible player. If no such player exists (i.e., if no player holds two shares of one of the affected Corporations), the Corporation is closed and all its shares are removed without compensation. Its station tokens are removed from the map and any trains it owns are placed in the Pool and become available for …

18EU Bankruptcy

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/buy_train.rb

_If company is broke (0), may use president cash to buy up to face value, but not sell shares_
In addition, I found the Pullman was triggering the cheapest depot train for ebuying, which cannot be bought as the only train, shown here:
----------
Presedential Contribution during Ebuy without shares sold.
----------
If the president sells shares, the corporation must buy the cheapest non-pullman.

18EU Emergency Buy

---

lib/engine/game/g_1860/step/route.rb

In the nationalization N+m trains run as N train only. This displays a hint for this in the nationalisation phase.
Fixes https://github.com/tobymao/18xx/issues/6961

1860: Displays the shortened trains in nationalization

---

lib/engine/game/g_1817/step/buy_sell_par_shares.rb

must_sell? appears to correctly check for possible sales using can_sell_any?
so the IPO share case seems to be covered.
NB: This change will break games where people have illegally passed. The example game in the bug actually has an earlier illegal pass as wel. 
Fixes https://github.com/tobymao/18xx/issues/6842

Added a check disabling pass when selling is required in 1817.

---

lib/engine/game/g_18_rhl/game.rb

Make ability descriptions better to reflect how it works after RhE
has floated. And remove the ability when the KDA link has been
created. So it will be more dynamic and improve user experience.

18Rhl: Improve RhE ability

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/special_track.rb
lib/engine/game/g_1870/step/track.rb

This deliberately doesn't use multiple labels because the pointy
weights don't currently render multiple labels for cities like a 14.
Fixes https://github.com/tobymao/18xx/issues/6704

1870: Fixes all the multi-label punches for tile lays

---

lib/engine/game/base.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1862/game.rb
lib/engine/step/dividend.rb

Ads a specific fix for 1860 and 1862 which have folded flat markets, all other games don't need a fix.
multi-step share price increases now look like this:  IOW's share price changes from £68 to £100 (4 steps)
single steps are unchanged.

Adds an announcement of multi-jumps,

---

lib/engine/game/g_1862/step/track.rb

1862: ignore normal track restrictions when adding a dit to a tile

---

lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1866/game.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1888/step/special_track.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_zoo/game.rb
lib/engine/part/node.rb
lib/engine/part/path.rb
lib/engine/route.rb
lib/engine/step/special_track.rb

Fixes #6157 
Completely removes Node::select and Path::select methods
Removes "on" parameter from Node::walk and Path::walk
Refactors Step::SpecialTrack to avoid Path::select

refactor check_connected to not use node.select

---

assets/app/view/game/buy_trains.rb

In assets/app/view/game/buy_trains.rb,
the line:
`if @game.class:EBUY_SELL_MORE_THAN_NEEDED_LIMITS_DEPOT_TRAIN`
was changed to:
`if @game.class :EBUY_SELL_MORE_THAN_NEEDED_LIMITS_DEPOT_TRAIN`
but this needs to be:
`if @game.class::EBUY_SELL_MORE_THAN_NEEDED_LIMITS_DEPOT_TRAIN`

Fix earlier rubocop fix

---

lib/engine/game/g_18_rhl/game.rb

[18Rhl] 6 trains should be available on 5 train

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/meta.rb

closes #6993
without optional 2train added:

[18Rhl] should be one fewer 2 train

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/map.rb

Found that the tile in the config was set to terminal. It should be an open city.
I've updated it with an implementation like 18GA.
Unfortunately, placing the city centered causes the name/values to overlap.

18EU Hamburg is Neutral

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/round/final_exchange.rb
lib/engine/game/g_18_eu/step/final_exchange.rb
lib/engine/game/g_18_eu/step/minor_exchange.rb
lib/engine/game/g_18_eu/step/replace_token.rb
lib/engine/game/g_18_eu/step/track.rb

Occurs once per game immediately before the first SR after Phase 5
Begins with the president that bought the train that started Phase 5, then round the table, PD doesn’t move
On their turn, player choose minor to dispose, If connected (or colocated) must merge, including merging into a corporation with no stock available, which is the same result as discarding
Pres decides to accept or decline token. It is allowed to have stations in same hex, but not the same city.
May go over 60% but then must sell at first selling opportunity
These mergers may cause a corp to float (uncommon), and then it is capitalized as in post-phase 5 floatation.
---
General view
Going over 60%, selling down in SR

18EU Final Exchange

---

assets/app/view/welcome.rb
lib/engine/game/g_18_eu/meta.rb
lib/engine/game/g_18_eu/trains.rb
spec/fixtures/18EU/hs_uflpdrek_1613000790.json

Put 18EU to alpha!
Found that the trains had additional offboards which must have been a relic of them being configured 18 months ago.
Closes https://github.com/tobymao/18xx/issues/792

18EU to Alpha

---

lib/engine/step/emergency_money.rb

I also refactored the math to make it more clear what the method is really checking, but the change in logic is effectively just replacing `bundle.price_per_share` to `bundle.shares.map(&:price).min`.

1849: treat double share atomically for EMR legality (fixes #5163)

---

lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/game/trainless_shares_half_value.rb

- Make the base game's `init_share_pool` method use the `PRESIDENT_SALES_TO_MARKET` constant - therefore games no longer need to override both the constant and the method to enable presidencies to be sellable
- Move the shared behaviour of trainless corporation shares being worth 50% in 1860, 1862, and 18GB into a single module for improved maintainabillity

Simplify receivership and trainless-company-shares behaviour to make it easier to use in multiple games

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/final_exchange.rb

Fix https://github.com/tobymao/18xx/issues/7021
Connected minors are detected using pathing, which we avoid during loading. Instead of assuming no connected, we can safely assume the action was valid during original submission.

18EU Fix Merging during Loading

---

lib/engine/game/g_1836_jr30/game.rb
lib/engine/game/g_1836_jr30/meta.rb
spec/fixtures/1836Jr30/2851.json

Adds an optional rule to get the old behavior, as 1830 does. I had to change one fixture to give it the optional rule retroactively.

1836Jr30: follow 1830 rules for brown shares (fixes #5260)

---

lib/engine/game/g_18_ireland/game.rb

I tested the new code on the six most recent 18Ireland games to finish and three of them broke the rule that is now enforced, so this will probably cause lots of pins if games are loaded in strict mode.

18Ireland: fix laying rules for tiles with broad gauge (fixes #5576)

---

lib/engine/game/g_1870/game.rb

Some of the normal upgrade checks are suppressed for labelled tiles as they can have odd rules. 
Add a check for yellow lays in 70. 
Fixes https://github.com/tobymao/18xx/issues/7059

1870 Add check for city count matching on yellow lay for labelled hexes.

---

lib/engine/game/g_18_gb/step/waterfall_auction.rb

- It is now always possible to pass once the auction has been restaged by a full round of passes
- This makes it possible to reach the state where companies cost 0, at which point players are mandated to bid for them at £0

18GB Private company auction

---

lib/engine/game/g_18_gb/map.rb

Allow both offboards to be in the same hex by reapplying from 1862

18GB Hull & Grimsby map fix

---

assets/app/view/game/map_controls.rb
assets/app/view/game/route_selector.rb
lib/engine/action/run_routes.rb
lib/engine/operating_info.rb
lib/engine/part/base.rb
lib/engine/route.rb

When serializing a route, save off its nodes (both the hex and the spot on the tile).
When deserializing a route, if the saved nodes are present and there's a choice of nodes to use for some tile, use the one that matches the saved nodes.
Tiles that can fail to deserialize routes correctly without this code include IR7, IR8, and 457-464.
If saved nodes are not present then the deserialization is the same as before, so it's backward compatible.
This code is fine with respect to the comment at https://github.com/tobymao/18xx/issues/5279#issuecomment-1034000192, since if the deserialization code can't find a chain that hits the saved nodes, it just returns the first possibility, as before.

Run routes through correct nodes when deserializing (fixes #5279)

---

lib/engine/game/g_18_gb/entities.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_gb/step/special_token.rb
lib/engine/game/g_18_gb/step/track_and_token.rb

- Second-edition private company price and revenue changes
- Private companies can't be closed in SR1
- From blue phase onwards, companies can be force-closed by building in their hex
- When using the GC or MC token abilities, a 10-share Caledonian Railway can keep back its free token and use a more expensive available token instead

18GB Private Companies

---

lib/engine/game/g_18_los_angeles/meta.rb
lib/engine/game/g_18_los_angeles1.rb
lib/engine/game/g_18_los_angeles1/game.rb
lib/engine/game/g_18_los_angeles1/meta.rb
spec/lib/engine_spec.rb

* `g_18_los_angeles1/` and `G18LosAngeles1` will now contain code for the 1st
Edition
* `g_18_los_angeles/` and `G18LosAngeles` will now contain code for the 2nd
Edition
* `G18LosAngeles` has `GAME_TITLE = '18 Los Angeles 2'` while `G18LosAngeles1`
has `GAME_TITLE = '18 Los Angeles'`; this means no DB migrations will be needed
for the 1st Edition to continue to work
* `G18LosAngeles1` inherits from `G18LosAngeles` so that when the 2nd Edition is
production ready, we can easily combine the two editions back into a single
game entry, with the first edition being turned into a checkmark option. When
that happens, the currently commented out lines in the two `meta.rb` files will
be uncommented.
* as I make the actual changes necessary for the 2nd Edition, code that is
specific to the 1st …

getting started on 18 Los Angeles 2nd Edition

---

lib/engine/game/g_18_rhl/game.rb

Single towns is only upgradable to green.
Correct choices has been implemented.

18Rhl: Fix upgrade paths for single towns (Fixes #7029)

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/bankrupt.rb
lib/engine/game/g_18_rhl/step/special_token.rb
lib/engine/game/g_18_rhl/step/special_track.rb
lib/engine/game/g_18_rhl/step/token.rb
lib/engine/game/g_18_rhl/step/track.rb

- Correct calculation of remaining treasury in receivership,
improving the log message.
- Do not let receivership do track or token actions

18Rhl: Fixes for receivership (Fixes #7064)

---

lib/engine/game/g_18_rhl/game.rb

Add information about the two capitalizations that are used
for corporations floated pre and post phase 5 phase change.

18Rhl: Enhance info regarding capitalization

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/round/operating.rb
lib/engine/game/g_18_gb/step/buy_train.rb
lib/engine/game/g_18_gb/step/route.rb

- If a corporation does not own a train, does not buy one from another company, and does not have sufficient money to buy the cheapest available new train, it enters emergency money raising
- A five-share corporation in emergency money raising may convert to a ten-share company, dropping three steps instead of two
- After converting during EMR, the corporation must buy a new train if it can afford one
- Corporations in receivership buy the most expensive available train if there is more than one available
- Corporations in receivership which are 5-share corporations will convert if they cannot afford the cheapest train in the depot

18GB Train buying

---

lib/engine/ability/teleport.rb
lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/special_track.rb

1. Make general ability teleport attribute hexes read/write (used by fix)
2. Correct 18Rhl teleport abilities so that tokening can only use
the teleports upgrade hex as teleport token.
3. Correct 18Rhl teleport abilities so that no tokening can take place
if the ability is used to upgrade an already tokened city
4. CCE first token appeared (in GUI) as E6/I10, and the second as I10.
By changing start coordinates to just [E6] (from [E6, I10]) during
placement of home tokens the presentation does now look OK.
As far as I can tell the coordinates does not have any other
effect after the corporation has started.

18Rhl: Improve token handling (Fixes #7053)

---

lib/engine/step/special_token.rb

In case a player owned private gives a teleport token ability
this means that entity is a corporation, and not a company.
This caused the code to crash as sym is not defined for corporations.
By using 'id' instead the crash is avoided, and it gives the
same result as before for when company is owned by a corporation.
This will print, for example:
[15:27] CCE (Tjt) lays tile #925 with rotation 0 on D9 (Duisburg)
[15:39] Krongar (CCE) declines to place token
I think this is good enough, as it is a player declining to use
the special token / teleport ability.

Fix crashing log message (Fixes #7058)

---

assets/app/view/game/corporation.rb
assets/app/view/game/map.rb
assets/app/view/game/pass.rb
lib/engine/game/base.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/map.rb
lib/engine/game/g_21_moon/round/corporate.rb
lib/engine/game/g_21_moon/step/buy_sell_par_shares.rb
lib/engine/game/g_21_moon/step/trade_stock.rb
lib/engine/round/base.rb
lib/engine/round/stock.rb
public/icons/21Moon/RL.svg

- Remove "Auto pass" button for CRs
- Show which shares have been traded
- Prioritize traded shares for selling and untraded shares for buying
- Add a legend to the map for the mineral value progression
- UI::Pass - make auto-pass button optional
- Engine::Round::Base - support for above
- Engine::Round::Stock - support for above
- UI::Corporation - allow adding additional flags to stock holdings
- UI::Map - support for map legends
- Engine::Game::Base - support for map legends

21Moon: UI support; select traded shares for selling; avoid for buying

---

assets/app/view/game/part/city_slot.rb
assets/app/view/game/round/auction.rb
lib/engine/game/base.rb
lib/engine/game/g_18_eu/entities.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/map.rb
lib/engine/game/g_18_eu/step/buy_sell_par_shares.rb
lib/engine/game/g_18_eu/step/final_exchange.rb
lib/engine/game/g_18_eu/step/minor_exchange.rb
lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
lib/engine/minor.rb
lib/engine/step/share_buying.rb
lib/engine/step/tracker.rb

Submitting a batch fix since these almost all invalidate games. Might as well hit them in one fell swoop.
Fixes [7047](https://github.com/tobymao/18xx/issues/7047)
Fixes [7068](https://github.com/tobymao/18xx/issues/7068)
Fixes [7069](https://github.com/tobymao/18xx/issues/7069)
Fixes [7071](https://github.com/tobymao/18xx/issues/7071)
Fixes [7089](https://github.com/tobymao/18xx/issues/7089)
Fixes [7109](https://github.com/tobymao/18xx/issues/7109)
Closes [7080](https://github.com/tobymao/18xx/issues/7080)
Share buying change does not change functionality, just allows for more specific overrides with less duplication of code.
Auction bid_str change already existed in some parts of the file, but not others.
Changes to **base, minor, tracker** and **city slot** allow for coloring the minor …

18EU Alpha Fixes

---

lib/engine/auto_router.rb
lib/engine/graph.rb

Engine::Graph - Expose the no_blocking option.
Engine::AutoRouter - Use the @game.graph_for_entity(corporation) to get the correct graph. If you have initialized the graph with no_blocking option on, make sure the auto router method work the same way as computes node.walk in the graph class.
I dont know if this will sabotage the auto router in any games?

Auto router fix with games that have multiple graphs

---

lib/engine/game/base.rb
lib/engine/game/g_1870/game.rb

Refactor out the special case to avoid a labelled city upgrading to plain yellow tiles now it's needed outside 1870

Refactor out the special case label city upgrade check

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/check_connection.rb

When multiple companies become eligible at the same time, the currently operating company goes first, followed by the other companies in stock price order (p. 22).
Fixes #7145

correct the 1870 connection order for multiple corporations

---

lib/engine/game/g_18_eu/step/modified_dutch_auction.rb

Fix https://github.com/tobymao/18xx/issues/7160
Minors that went down in price were missing the call to place their home token.
Before
After

18EU Fix 7160 Purchased Minor should place token

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_gb/step/buy_train.rb
lib/engine/game/g_18_gb/step/emr_share_buying.rb

Bring 18GB up to pre-alpha test game readiness by completing the final item on the implementation checklist and fixing a few small snags
- North-South and East-West bonuses can now be achieved by chaining together multiple trains - closes #6982
- Certificate limit includes all certificates, even those for corporations in the "no share buying limit" section of the market
- Emergency fund raising changed from a `choose` to a `convert` action - both more accurate, and also enables conversion when train buying is also possible (for the case when the president wants to reject buying from other corporations)
- Corporations are only obligated to buy a train if they can afford the most expensive one currently available and could otherwise choose to skip and keep raising funds

18GB Pre-alpha rules completeness

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/round/operating.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_gb/step/buy_train.rb

Correct server errors caused by Ruby/Opal differences:
- Add missing `require_relative` statements
- Add attribute readers/accessors
- Refer to corporation symbols and types using symbols rather than strings

18GB Server Play bug fixes

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/step/track_and_token.rb

Fix two issues from a pre-alpha test game:
- Tile-laying bug in non-hotseat games when building toward a hill hexside
- Game should end immediately when an OR ends with the export of the final train, rather than another OR being played

18GB Pre-alpha fixes

---

lib/engine/game/g_18_gb/entities.rb

- Correct some typos in the private company descriptions
- Also add the missing green-home-hex ability to the Midland Railway

18GB Company descriptions (fix typos, improve consistency)

---

lib/engine/action/run_routes.rb
lib/engine/operating_info.rb
lib/engine/part/base.rb
lib/engine/route.rb

Fixes #7205 
This changes node.full_id -> node.partial_id so that Engine::Route can use @saved_nodes even across tile upgrades.

Allow find_pairwise_chain to use saved_nodes even with tile upgrade

---

lib/engine/game/g_18_gb/entities.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/map.rb
lib/engine/game/g_18_gb/scenarios.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_gb/step/buy_train.rb
lib/engine/game/g_18_gb/step/special_token.rb

Fix bugs:
- CR teleporting with MC generating a "token already used" error
- Missing W flag on Plymouth preventing EW bonus from being paid
- MC token ability was teleporting to York instead of Carlisle
- MSLR charter listed an ability it doesn't have (green normal home city, but it lives on Sheffield, an OO tile)
Usability improvements:
- Empty tile in the Severn estuary made blue to make it clearer it is out of play when it is surrounded by tiles
- Conversion capital in £ displayed on the Convert button in the SR (consistent with when emergency converting in an OR)

18GB Fixes from pre-alpha test games

---

assets/app/view/game/game_info.rb

closes #7232 
Covers 2P for 46 and 52

[1846 2P] add "end after final train purchased" to end game list

---

lib/engine/game/g_1873/game.rb

1873: allow routes with un-owned trains

---

lib/engine/action/run_routes.rb
lib/engine/game/g_1873/game.rb
lib/engine/operating_info.rb
lib/engine/route.rb

Fixes performance issue when serializing routes by caching node signatures. The cache is cleared whenever connection_data is rebuilt so that it doesn't go stale.
Also addresses issue with Harzbahn performance due to having to rebuild route connection_data to determine if a token should be flipped.

used cached node_signatures for serializing

---

lib/engine/game/g_21_moon/game.rb

I noticed that this shows up under whatever player bought the OLS private:
This is an artifact of creating a dummy minor that holds the OLS token until it is replaced. It should never show up as an entity in play. I had taken care of this for the bank, but not for players.
This PR takes care of it for players.
Also takes care of the erroneous **`-- Operating Round 5.1 (of 2) --`** being displayed.

21Moon: fix erroneous listing of OLS

---

lib/engine/auto_router.rb

Fixes #7258
1822's game.revenue_for(route) requires a route collection to properly check for home-to-destination bonus

auto-router 1822 revenue needs a routes collection

---

lib/engine/game/g_18_ny/game.rb

fixes bug #7275
2H should not receive $30 per token bonus, only the diesel

fixes 2H train receiving Diesel bonus

---

lib/engine/game/g_18_usa/game.rb

Currently it shows the 1817 legend which is not correct for 18USA

18USA: Fix stock market legend

---

lib/engine/game/g_18_usa/step/resource_track.rb

- Only consume resource ability for yellow resource tiles
- Ore20 should count as an upgrade.

[18USA] Resource tile fixes

---

assets/app/view/create_game.rb

Closes https://github.com/tobymao/18xx/issues/5491
I'm not sure why multiplayer was calling params directly again instead of using game_params?
I did not add the seed directly to the hotseat hash as I did not want it included when nil.
---
Multiplayer
Hotseat

5491 Specify seed in game setup

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles/map.rb
lib/engine/game/g_18_los_angeles/meta.rb
lib/engine/game/g_18_los_angeles1/entities.rb
lib/engine/game/g_18_los_angeles1/game.rb
lib/engine/game/g_18_los_angeles1/map.rb
lib/engine/game/g_18_los_angeles1/meta.rb
spec/lib/engine_spec.rb

* new map
* entity changes that can be handled in config (e.g., changing homes/reservations etc)
* new private companies are stubbed out (will implement their new abilities later)
* some minor miscellaneous things: meta.rb changes, make `/map/18LA1` and `/map/18LA2` URLs work as expected, fix imports, when logging companies/corporations in the game for 1846-family games, log them in sorted order
The most substantial code changes are in `lib/engine/game/g_18_los_angeles1/game.rb`, which adds logic so that 18LA1 can use the entities from 18LA2 and only override them when different values are set via the constants `COMPANIES_1E` and `CORPORATIONS_1E`
Local validation has been done to confirm this doesn't break any existing 18LA games.
#7110

18LA2 - map and entity config changes

---

lib/engine/step/tracker.rb

This ensures that only valid tile lays and rotations are shown for e.g. OO tiles with only one connected city upgrading to have both cities connected and is a big UI upgrade for 18GB in particular but also any other current and future titles with these sort of tiles.
- Closes #7333
- Closes #7336

Correctly identify multi-city upgrades even when there are disconnected cities

---

lib/engine/ability/token.rb
lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/map.rb
lib/engine/game/g_18_usa/step/special_token.rb

- Update DFW Brown tile to correct value of 60 (wrong in 1.4 rulebook)
- Change Free station subsidy from extra_token to token ability and allow it to be placed in a tokened out city

[18USA] Rulebook has the incorrect value for DFW's brown tile. 

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/special_track.rb
lib/engine/game/g_1822/step/track.rb

This change adds temporary labels to the plain yellow tiles laid on T and S hexes in 1822. They upgrade to named label tiles in green. 
Include hex match logic rather than operating on all plain tile lays over labels so that this can be incorporated selectively into 1822 derivative games. 
FIxes #7132

[1822] punch labels through plain yellow tiles for C and T hexes

---

lib/engine/game/g_21_moon/game.rb

Add token info to bonus hexes:

21Moon: add bonus token info to bonus locations

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/discard_train.rb

and frozen actions need to be dup'd before modifying.

[18USA] Obsolete trains don't count against train limit 

---

lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles/step/buy_sell_par_shares.rb
lib/engine/game/g_18_los_angeles/step/draft_distribution.rb
lib/engine/game/g_18_los_angeles1/game.rb

instead of removing companies/corporations during setup, 18LA2 does the
following:
* end company draft when limit is reached
* close unstarted corporations when max have been started
This also adds `help` to the draft and stock round steps to inform users how many more companies can be drafted or corporations started.
#7110

18LA2: company and corporation limits

---

lib/engine/game/g_18_ny/game.rb

This adds a check to prevent any special tile being laid if it is availabls, as 18NY has special tiles appear in different phases.
Fixes #7374

Fix for 18NY having both plain and symbol upgrades in some phases.

---

lib/engine/game/g_1846/game.rb

In the Ruby, the tile color is `:green`, not `'green'`, but in the JS `:green` gets translated to `'green'`. This means that in the backend engine, the token didn't actually get placed, leading to the backend and browser disagreeing on what the current step should be.
[Fixes #7361]

1846 2p: fix string/symbol issue for tokens on upgrade

---

lib/engine/game/g_18_gb/entities.rb
lib/engine/game/g_18_gb/meta.rb

- Update the Info page's rules link to point to 2nd edition rules rather than 1st edition (consistent with wiki)
- The MC private should cost £50, not £60 (2nd edition rules change)

18GB Alpha changes

---

lib/engine/game/g_1822/game.rb

This will make it easier to re-use the plain tile lay logic when implementing other 1822 variants.

[1822] Switch to using symbol-based logic for plain tile upgrades

---

assets/app/view/game/route_selector.rb
lib/engine/game/base.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_18_carolinas/game.rb

Fixes #5854 
Common code edits:
- UI::RouteSelector - generalize variable train calls to include entity, select route for newly added train
- Engine::Game::Base - support for above
New UI:

1873: add +/- train controls

---

lib/engine/game/g_18_tokaido/game.rb

18Tokaido uses 18LA's draft, which was modified in PR #7372 to support stopping
the draft once a specified number of companies had been selected; that mechanism
requires a couple more methods in the game class

18Tokaido: fix problems introduced by #7372

---

lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles/step/special_token.rb
lib/engine/token.rb
public/logos/18_los_angeles/ELA_RJ.svg
public/logos/18_los_angeles/LAIR_RJ.svg
public/logos/18_los_angeles/LA_RJ.svg
public/logos/18_los_angeles/PER_RJ.svg
public/logos/18_los_angeles/SF_RJ.svg
public/logos/18_los_angeles/SP_RJ.svg
public/logos/18_los_angeles/UP_RJ.svg

Redondo Junction lets the owning corporation place a token it can use as an
extra station token, until Phase IV, when the token is removed (it persists
after the company closes in Phase III)
To make it obvious which corporation owns the RJ token, each corporation has a
simple RJ "logo"--just the letters "RJ" and the corporation's color--and when
the RJ token is placed, that token's `logo` and `simple_logo` are replaced by
the corporation's RJ logo
Here's how it looks when LA uses the RJ token; LA's home is Pasadena, it has placed
another normal token in Alhambra to the southeast, and the extra token from Redondo
Junction to the west in Burbank.
#7110

18LA2: private company Redondo Junction

---

lib/engine/game/g_18_mex/step/buy_sell_par_shares.rb
lib/engine/game/g_18_mex/step/swap_buy_sell.rb

When at cert limit, you are allowed to by yet another 5% share in NdM
as they do not count towards cert limit. But you are not allowed to
buy swap a 5% for a 10%.

18MEX: Handle NdM 5% corner case (fixes #7360)

---

lib/engine/game/g_18_jpt/game.rb

Typos preventing normal game flow. The `.freeze` one was not an error in hotseat

[18JP-T] Fix game breaking typos

---

lib/engine/game/g_18_mex/step/buy_sell_par_shares.rb

When a corporation is in "yellow" on stock market, it is allowed
to be bought regardless of cert limit, even if buying from IPO.
I do not know if this will break any game but it potentially might make some player having a buy action that they have not had before.

18MEX: Allow buying from IPO for "yellow" corps (fixes #7446)

---

lib/engine/game/g_1866/game.rb

Fixes some punctuation in the Info block's event text

[1866] fix event text

---

lib/engine/game/g_18_gb/game.rb

Show which tier a corporation is in on its charter during the initial auction and SR1 (rather than this only being visible in the log and by which corporations are visible to purchase shares).
After SR1 the information is no longer relevant (since any corporation can be IPOed), so no longer needs to be displayed.

18GB: Show tier information on corp charters during auction and SR1

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/round/operating.rb
lib/engine/round/operating.rb

Games that were already affected by this will need to be pinned.

18NewEngland: keep minors first when resorting (fixes #7502)

---

assets/app/view/game/buy_sell_shares.rb
lib/engine/game/g_1871/game.rb
lib/engine/game/g_1871/step/buy_sell_par_split_shares.rb
lib/engine/game/g_1871/step/exchange.rb
lib/engine/game/g_1871/tiles.rb

This allows games to have unbuyable treasury shares in a corporation without blocking buyable treasury shares from showing up properly. Later on in the process we first call `can_buy` on these shares anyway so filtering for buyable ones when getting the list should be 100% the same except in games like 1871 that has reserved shares sitting around.
I also reorder the "but for other player" buttons to match the order of the normal buttons and fix the same bug as above in a 1871 log line.
Also relabel the C tile to CX as intended and made sure the logic works.

fix: 1871 exchange shares blocking buyable treasury shares

---

lib/engine/game/g_1832/map.rb
lib/engine/game/g_18_fl/game.rb

Changing the name of the private didn't seem to break existing 18FL games when I tried it locally.

Fix spelling of Tallahassee

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/map.rb

Show the North-South and East-West bonuses on the map (so that they are visible during routing), rather than hidden away in the Info tab. This also cleans up the cluttered-looking phase table.

18GB Show NS and EW bonuses on map

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/map.rb

Move the newly added NS/EW bonus display on the map to column C. This will better suit the 2-player North-South scenario map which doesn't include columns Z, A and B.

18GB Move NS/EW bonuses to column C to better suit 2-player NS scenario map

---

lib/engine/game/g_1866/game.rb

- Fixed the minor bug. If you run a train from a double town hex, you could run through both cities on the C-tile "C4"
A very special case, but it could affect games if people have done it.

[1866] Same hex twice

---

assets/app/view/game/alternate_corporations.rb
assets/app/view/game/game_info.rb
assets/app/view/game/round/stock.rb
assets/app/view/game_page.rb
lib/engine/game/base.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/step/buy_sell_shares_bid_companies.rb
lib/engine/game/g_rolling_stock/step/close_companies.rb
lib/engine/game/g_rolling_stock/step/dividend.rb

* Info tab
* Remove standard notion of phase
* Finish receiver auto-actions
* Bug fixes from hot-seat play through
* UI::AlternateCorporations - add "ability" income to table
* UI::GameInfo - support for RS info, no trains
* UI::Round::Stock - option to show private companies before corporations
* UI::GamePage - generalize menu bar color and "phase" string
* Engine::Base - support for above
Portion of RS-specific Info tab:

Rolling Stock: implement info tab, remove phases, fix bugs

---

lib/engine/game/g_1866/game.rb

- If a company closes push the back into the loan market. Have no impact in the game, only so it shows the correct amount of loans in the market tab.
Does not affect the currect games.

[1866] Minor corporation close bug

---

lib/engine/game/g_1889/game.rb

I figured the icon was the canonical color
Before:
After:

[1889] adjust UR card background to match icon

---

lib/engine/graph.rb

I ran this change against the entire database with strict=true. No games that use home_as_token failed.

Add support for cities in graph's home_as_token option

---

lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/round/investment.rb
lib/engine/game/g_rolling_stock/step/ipo_company.rb

* Stock auto-pass conflicts with Close auto-pass, so removed Stock auto-pass
* Found and fixed a bug with finding legal par prices

Rolling Stock: remove auto stock pass; fix par bug

---

assets/app/view/create_game.rb
assets/app/view/game/game_info.rb
assets/app/view/game/player.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/meta.rb
lib/engine/game/g_rolling_stock_stars/game.rb
lib/engine/game/meta.rb

Fixes #7600 
Fixes #7601 
* Fix bug where showing player colors would cause it to crash
* Rolling Stock Stars is now the default even on the Rolling Stock new game page
* Rolling Stock now defaults to using the "always include the best company of each color" rule (i.e. same as Stars)
* Rolling Stock now supports 2-6 players (i.e. same as Stars)
* Text color tweak for game_info to make it work with dark-mode
Because of the RS changes, any active Rolling Stock games (not Stars) should be archived.

Rolling Stock: fix player color bug; change defaults; new RS options

---

lib/engine/game/g_1860/step/home_track.rb

Fixes #7610 
No pins or archives needed.

1860: allow multiple home tile lays in the same SR

---

lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock_stars/meta.rb

Fixes #7616 
This will invalidate any Rolling Stock or Rolling Stock Stars game past turn 1

Rolling Stock (Stars): fix egregious order of IPO bug

---

lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1825/step/track_and_token.rb

Unfortunately Dave Barry's kit DB1 is itself full of optional rules.
This implements the rule he "uses in practice", giving the 887/888
tiles to Units 1 and 3 but not 2 where they are primarily for the
more complex variant which he doesn't use in practice.
As with DB2 I have hence only implemented what I think is the most
popular version since 1825 has many options already.

Implement variant DB1: additional upgrade paths for double dits

---

lib/engine/game/g_1825/map.rb

There was a semicolon missing in the definition of hex F8.

1825: Correct typo making F8 into a single dit not a double dit

---

lib/engine/game/g_1828/step/merger.rb

Currently the player who needs to choose someone to swap shares with just gets a "Choose player:" dialog with no indication of what they are choosing for.

1828: Clarify why player needs to be chosen during merger

---

assets/app/view/game/auto_action/close_pass.rb
assets/app/view/game/game_info.rb
assets/app/view/game/player.rb
lib/engine/game/base.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock_stars/game.rb

Fixes #7624 
Fixes #7627 
Fixes #7632 
* Programmed auto-pass for Closing rounds is now defaulted on
* The "conditional" auto-pass now disables when the player has a company with negative income (as opposed to the operation costs just increasing)
New table:

Rolling Stock: Fix share price bug; Auto-pass now defaults to on; UI enhancements

---

lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/step/propose_and_purchase.rb
lib/engine/game/g_rolling_stock/step/receiver_propose_and_purchase.rb

Fixes #7635 
* Makes offers for Foreign Investor companies, especially by receivership corps, more robust
* Adds sanity checks for the offer responder_list

Rolling Stock: Receivership acquisition of Foreign Inv company bug fixes and checks

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb

Francis Tresham never got around to selling this but he distributed
various copies either as envelope stiffeners or at conventions, so
the layout is known.
Fortunately it does not introduce any more companies, trains, money etc
so there's no need to add three options (units 3+4, 2+3+4, 1+2+3+4).
It is intentional that this implementation doesn't add a @units[4];
there's a lot of 'case units.keys.sort.map(&:to_s).join' which would
break.

1825: implement Francis Tresham's unpublished Unit 4 map

---

lib/engine/game/g_rolling_stock/game.rb

Fixes #7650 
Fixes #7651 
Because player order is affected, nearly all multiplayer games will be invalidated. I would like to see these pinned instead of archived.

Rolling Stock: Fix player order; fix Junkyard Scrappers power

---

lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/step/bankrupt.rb
lib/engine/game/g_21_moon/step/buy_train.rb
lib/engine/game/g_21_moon/step/route.rb
lib/engine/game/g_21_moon/step/token.rb
lib/engine/game/g_21_moon/step/track.rb

* Fixed needless Graph calls during loading
* Added clarified receivership functionality
* OLS no longer removes its token if player owner bankrupts
There is a chance that some games will need to be pinned.

21Moon: Speed fix; receivership fixes to match rules; OLS ruling on bankruptcy

---

assets/app/view/game/part/city.rb
assets/app/view/game/part/single_revenue.rb
lib/engine/part/base.rb
lib/engine/part/pass.rb
lib/engine/tile.rb

Engine::Part::Pass is a new class that inherits from Engine::Part::City
1841 needs a separate object for a pass because:
* It needs to render differently from a normal city
* It is treated differently for routing and train limits

Pass: new revenue center for 1841

---

lib/engine/game/g_1861/step/buy_sell_par_shares.rb

Check for a closed Nikolaev when checking if a player should be prevented from starting an auction for a different minor in the stock round.
Closes #7558
Closes #7567

1861: Fix bug where nationalised Nikolaev blocked starting minors

---

assets/app/view/game/part/future_label.rb
assets/app/view/game/part/large_icons.rb
assets/app/view/game/part/large_item.rb
assets/app/view/game/tile.rb
lib/engine/game/base.rb
lib/engine/game/g_18_dixie/map.rb
lib/engine/game/g_18_dixie/tiles.rb
lib/engine/hex.rb
lib/engine/part/base.rb
lib/engine/part/future_label.rb
lib/engine/tile.rb

Implement 18Dixies special city upgrades using punch-through tile labels implemented as a part called "FutureLabel" to indicate that it's a label for a future tile, but not the current one
Here is a example of them being used on the Memphis city in 18Dixie - 
In yellow Memphis gets a plain yellow city tile
In green Memphis gets the Memphis green tile
In brown Memphis gets a P brown city tile
Care is taken to make sure that when tiles are "returned" that the FutureLabels put on the tiles are restored so that the FutureLabels don't pollute the supply of yellow city tiles.
The benefits of using a part over icons & game code are:
- Easier to apply to pre-existing and new games
- The tile image colors match the user's tile color preferences correctly
- There don't need to be `.svg`s created …

18dixie special city upgrades

---

lib/engine/game/g_18_rhl/step/bankrupt.rb
lib/engine/game/g_18_rhl/step/buy_train.rb

The train buy for receivership after player bankruptcy is
handled automatically so no need to render Buy Trains.
Also fixed bug in case remaining cash in corporation is 0.
Fixes #7674

18Rhl: Correct bankruptcy for corporation in receivership

---

lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1825/step/track_and_token.rb

As with the other DB variants, I have implemented only what I think
is the most commonly used set of changes, since 1825 has many options
already.
This implementation does (purely cosmetically) add town names to hex
I13 even in non-DB3 games since that seems harmless.

Add variant DB3

---

lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_gb/step/track_and_token.rb

- Don't show Sell buttons in the stock round once selling shares is no longer possible due to end-game restrictions
- Update the step descriptions (and the Pass button) for stock trading and track-and-token steps so that these are more accurate in cases where end-game restrictions are active

18GB - small UI updates for 2E playtest variant

---

lib/engine/game/base.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/map.rb
lib/engine/game/g_1822_mrs/game.rb

I updated 1822 to use FutureLabels instead of special upgrade logic. The yellow S tile upgrade logic is still needed because the town is removed in yellow.
I also found and fixed a JS v Ruby bug when testing this which is now fixed

1822: Use FutureLabels for S & T tiles

---

lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles/step/special_track.rb
lib/engine/game/g_18_los_angeles/step/track_and_token.rb
lib/engine/game/g_18_los_angeles/step/tracker.rb
lib/engine/game/g_18_los_angeles1/entities.rb
lib/engine/game/g_18_los_angeles1/game.rb

1E: $20 discount to all mountain costs, can apply to more than mountain in a
single tile lay, e.g., two separate borders, or a border and the main tile
upgrade cost
2E: $20 discount for all terrain costs, but limited to one discount per tile lay
The existing `tile_discount` ability has no configurable mechanism for being
limited to a single use, so a tile's `borders` and `upgrades` are checked and raise
the flag if any terrain is found, in which case the CHE discount can be used.
In entities files, treat 1E/2E versions as completely different companies, instead of one
where the 1E definition overrides the 2E definition, so that the different IDs
can be used in the game logic to apply the different "ability" separately
#7110

18LA2: changes for private company Chino Hills Excavation

---

lib/engine/game/g_18_usa/meta.rb

It looks like AAG has an updated rules link

[18USA] update rules link to 2022 version

---

lib/engine/game/g_18_rhl/map.rb

Promotion tiles variant:
Fixed town rendering on tile 949, 950 and Essen.
Ratingen variant:
Change Ratingen-label to R for tile 1910 and 1911.
Also add R label to Ratingen hex.
The Promotion tiles fix will fix #7503.

18Rhl: Fix some tiles

---

lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_sj/step/route.rb

This bug was not handling GKB nil properly in games where GKB
private is not present.

18SJ: Correct bug with GKB (fixes #7768)

---

lib/engine/route.rb

Fixes #7115 .  Remove the internals from the print.

Remove internal structure when printing warning for using same hex twice

---

assets/app/view/welcome.rb
lib/engine/ability/README.md
lib/engine/ability/token.rb
lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles/meta.rb
lib/engine/game/g_18_los_angeles/step/special_token.rb
lib/engine/step/special_token.rb
public/logos/18_los_angeles/dump.svg

The Dump places a -$20 station token which blocks everyone--including the
corporation that placed it--and reduces the city's revenue by $20 for all routes
Westminster is the only $10 target for the Dump, and if the Dump is placed there
the net revenue is $0 instead of -$10. Westminster is also a target for the
Steamship (adding $40), and if both are placed there, then the Dump's full
penalty applies for a net revenue of $30.
In order to allow a corporation owning Angeles Public Dump to place the Dump
token in a city where they have a regular token, token abilities have a new
attribute, `check_tokenable`, which can be set to `false` to bypass the usual
tokening requirements; at the time the check is made, the token still belongs to
the owning corporation, rather than the dummy DUMP …

18LA2: private company Angeles Public Dump, move to alpha

---

lib/engine/game/g_18_gb/step/special_token.rb

Fix an issue where a token-placing private company ability could not be used if the active corporation was out of existing tokens.
Closes #7779

18GB 2E: Fix issue with using a token-placing ability when out of tokens

---

lib/engine/game/g_18_gb/entities.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb

Updates as per designer Dave Berry:
- The LM private company should give a £20 bonus to Liverpool, not £10.
- The second-edition playtest end-game variant is being updated to trigger with 2 or fewer (instead of 3 or fewer) trains remaining at the end of an OR, and to only block token placement and not also share sales as per the previous version of this rule.

18GB 2E Updates

---

docker-compose.prod.yml
docker-compose.yml
scripts/data_dir.sh

These are changes needed to build using podman on Fedora 35.
If some parts of the build omit the `context` subfield, then podman fails to merge the two yml files correctly.  I could not find any existing podman issues regarding this.
```
rm -f docker-compose.override.yml
ln -s docker-compose.dev.yml docker-compose.override.yml
./scripts/data_dir.sh podman
podman-compose up --build
['podman', '--version', '']
using podman version: 3.4.7
Traceback (most recent call last):
[TRACEBACK OMITTED FOR SPACE]
ValueError: can't merge value of build of type <class 'str'> and <class 'dict'>
make: *** [Makefile:33: dev_up_b] Error 1
```
Per the docs at : https://docs.docker.com/compose/compose-file/compose-file-v3/
This should be equivalent.
>  build can be specified either as a string containing a …

podman updates to allow building on Fedora 35

---

assets/app/view/game/company.rb
assets/app/view/game/round/auction.rb
lib/engine/company.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1817/step/selection_auction.rb
lib/engine/step/auctioner.rb
public/assets/main.css

[1817] Implement Volatility expansion initial auction

---

lib/engine/game/g_18_gb/entities.rb

A new change to be play-tested in the 18GB 2nd-edition variant: increasing the revenue bonus for the Liverpool & Manchester private company from £20 to £30

18GB: Increase LM revenue bonus to £30 in 2E playtest variant

---

lib/engine/game/g_18_rhl/game.rb

18Rhl: Essen tile only allowed in brown Essen hex

---

lib/engine/game/g_1893/step/buy_sell_par_shares.rb

It is Sell&Buy so selling shares and then buying a bond is allowed.
Fixes #7819

1893: Allow bond buy after sell

---

lib/engine/game/g_1849/map.rb

Fixes #7772 
The issue says the name should be "Alcano", but all the references I saw used "Alcamo"

Add Alcamo name to C3 hex

---

lib/engine/game/base.rb
lib/engine/game/g_18_mex/game.rb
lib/engine/hex.rb
spec/fixtures/18MEX/80226.json

This one took me a while to figure out, I'm surprised I didn't catch onto hex.rb being the problem for me sooner.
Adds FutureLabels for 18Mex. 18Mex has the odd situation of a future label where a label goes away:
#480 shows the future label in the tile manifest

18MEX: Tidy up FutureLabel logic and make it so that blank future labels can be used (18Mex Guadalajara -> gray tile)

---

lib/engine/step/train.rb

Fixes #6707
After the change, loading the affected game from the ticket shows a "game cannot be continued error". The error is hard to trigger manually by its nature

Prohibit entities from buying trains from themselves

---

lib/engine/game/g_18_ms/game.rb
lib/engine/game/g_18_ms/map.rb

I left `all_potential_upgrades` in so that the tile manifest still shows the upgrade paths

18MS future labels

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/pending_token.rb
lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_scan/entities.rb
lib/engine/game/g_18_usa/entities.rb
lib/engine/part/city.rb

When a game specifies a slot for a cheater token, that slot can cause extra slots to appear when the tile is upgraded or when the cheater disappears.
A small change was needed for 1822 to make sure Minor 14 (which has a bit different behavior than a cheater) still worked.
The following games will have to be pinned/archived after this change because of the extra slot either allowing an invalid token placement or
allowing a company to pass through a city that should otherwise be tokened:
40005
63892
65571
71413
82164
83068
39042

Modified cheater to always be boolean instead of specifying a slot

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1832/game.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_18_co/game.rb
lib/engine/game/g_18_mt/game.rb
lib/engine/game/g_18_zoo/game.rb
lib/engine/stock_market.rb

In 1868 Wyoming, shares can be sold from SR1, but if shares are sold before the corporation has operated, the seller receives cash from the bank based on the price of the shares _after_ they are sold.
Also, fix `StockMarket#find_relative_share_price` so that `:up` and `:down` are actually correct, and fix values passed in from other games. Finally, refactor `find_relative_share_price` so it doesn't create and use an unnecessary `Array` (turns out that array was originally my own doing, the leetcode training is paying off :wink: ).

sell pre-operational shares at new price (1868WY), fix up/down for find_relative_share_price (1868WY, 1822, 1832, 1870, 18CO, 18MT, 18ZOO)

---

lib/engine/game/g_1849/step/buy_sell_par_shares.rb

1849: Parring counts as moving stock token into market (fixes #7937)

---

lib/engine/game/g_1861/game.rb
lib/engine/game/g_1867/game.rb

Use the FutureLabels functionality for the Ottawa (1867) and Kharkov (1861) upgrades, instead of game-specific logic.
This also makes the O/Kh label visible on yellow, green and brown tiles in this hex, which closes #7133

1861/1867: Use FutureLabels for O/Kh tiles

---

assets/app/view/game/spreadsheet.rb
lib/engine/game/base.rb
lib/engine/game/g_18_co/round/presidents_choice.rb
lib/engine/game/g_18_ny/round/capitalization.rb
lib/engine/round/base.rb
lib/engine/round/choices.rb

* Show rounds in the spreadsheet player history table even if there is no change in values - this is less confusing and works well with the Delta view where a change of £0 is shown for these rounds rather than excluding them altogether. Closes #7961 
* Rather than excluding based on the lack of value changes, we then deliberately exclude rounds which exist for programmatic reasons or weren't shown in the previous display to keep consistent behaviour: all choices "rounds" (especially relevant for 1822 games), 18CO president's choice, and 18NY capitalization rounds.

Spreadsheet player history: include rounds even if no value change

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/dividend.rb
lib/engine/game/g_1868_wy/step/waterfall_auction.rb
lib/engine/game/g_1868_wy/stock_market.rb
lib/engine/step/waterfall_auction.rb

* one small refactor to common engine code: extract function `increase_discount!` in `Engine::Step::WaterfallAuction`
* in the common code, this function is called just once, but in the 1868WY code it is called consecutively in `G1868WY::Step::WaterfallAuction#all_passed!`
1868 Wyoming changes:
* fix initial auction
* no more paying revenues
* P9 and P10 become cheaper if P9 is not bought
* help text for step when winner of P3/P4 chooses Developer/Surveyor
* private company certs don't count toward end game value
* if sold out at end of SR and at top of market, move down and right, as in 1822
* priority order (by cash after auction, then by passing order for SRs)
* double and triple jumps for paying out double/triple

[1868WY] auction / stock market changes

---

lib/engine/game/g_1868_wy/entities.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/buy_sell_par_shares.rb
lib/engine/game/g_1868_wy/step/company_pending_par.rb
lib/engine/game/g_1868_wy/trains.rb

* in phase 3, the green par prices become usable; in phase 5, the brown ones become usable
* the home tokens for LNP and OSL start in cities that are not connected until green, so if the green tile has not already been laid when they start, they get the tile for free

[1868WY] par: add green/brown sections, LNP and OSL get free home green tile

---

lib/engine/game/g_1871/game.rb
lib/engine/game/g_1871/step/dividend.rb

I think the fix is simpler than I feared over in my most recent #7847 comment. Judging from all the `ceil`s and such in the code, it looks like the codebase is used to working around this general issue, so I think this change is sufficient to get 1871 into a state where the rest of the hacks can take over.
I still think that the real fix is to do all share math with fractions instead of percentages, but that ship sailed a couple of years ago.
This PR also fixes what turned out to be a separate rounding issue in implementing the rules (this is the actual bug noticed in #7847 before I turned it into a catchall for 1871 floating-point problems).

[1871] Fix floating-point issues (fixes #7847 et al)

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_1871/game.rb
lib/engine/game/g_1871/step/buy_train.rb
lib/engine/step/bankrupt.rb
lib/engine/step/train.rb

New behavior:
1) UB needs to buy a train and will not have enough funds on its own.
2) UB sells one of its two shares.
3) UB sells its last share.
4) UB owner watshisname sells two shares.
5) Finally there are enough funds to buy a train. Resulting log display:

[1871] UB doesn't go bankrupt, owner must pitch in (fixes #7526)

---

lib/engine/game/g_18_ny/game.rb

- Change diesel bonus to +$10 per stop
- Discarded trains go to the market instead of being removed
Breaks most 2E games

[18NY] 2E balance changes

---

lib/engine/game/g_18_sj/map.rb

This will break 18SJ games as some tiles have changed names. Can be good to pin them to let alpha play test continue - and finished games can be archived.
Here is how tile set looked like before this change:
And after the change:

18SJ: Align tiles to AAG standard (fixes #8020)

---

lib/hooks.rb
queue.rb

Google Chat requires the format <users/123> to notify users rather than the more common <@123>.

Add support for Google Chat webhook.

---

assets/app/view/game_card.rb

This reverts commit 384e8a05cf047dce50bd280ec1887f1c8944f2b3.
This commit incorrectly modified the button to display "View" for the logged in player's games. @benjaminxscott elected to not fix that, so reverting instead.

Revert "refactor game opening button text "Enter" => 'View'"

---

lib/engine/game/g_18_mag/game.rb

As far as I can tell there's nothing about 18Mag that prevents these from working normally. I tested it out locally and it seems to work fine. Based on commit history it ended up this way because of a big 18Mag refactor landing almost at the same time as the initial auto actions commits.

Enable the default auto actions (SR pass, SR buy) in 18Mag.

---

assets/app/view/user.rb
queue.rb
routes/user.rb

If checked, a notification is triggered immediately on saving the settings. Only works for webhooks, never sends email.
An alternative would be a "send test notification" button, but then the flow would be edit settings -> save -> click button, which I don't see a good way to do. It would be too easy to press the button after editing settings, but before saving.

Add a "send test notification" checkbox to webhook settings.

---

lib/engine/tile.rb

Add reserve_city parameter to add_reservation method in tile.rb 
In my prototype a city can get disjoint into 2 cities. Without this change, the reservation was automatically assigned to one of them rather than leaving the choice to the president when the corporation operates for the first time.

Add reserve_city param to tile.add_reservation

---

lib/engine/game/g_1828/step/merger.rb

A few choices had no explanation of what choice you were making. Also made punctuation more consistent.

[1828] Explain choices during merge

---

lib/engine/game/g_1877_stockholm_tramways/game.rb

Closes #8028. Breaks all games in which the run trains step has been skipped due to not being allowed to run acquired trains. Currently, there is only one known game in which the issue has occurred.

1877: Stockholm Tramways fixed not allowed to run acquired trains

---

lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/buy_sell_par_shares.rb

The "you must buy up to the full presidency" warning is no longer spammed 5-20 times
The issue where a player can steal the presidency on a tie is fixed (fixes #6649)
A typo is fixed
@share_pool.buy_shares sets national.ipoed so no longer manually setting it
- this also lets core game code log the IPO price

1856: Fix issues with false national presidency in 1856

---

assets/app/view/game/stock_market.rb
lib/engine/game/g_1849/stock_market.rb
lib/engine/game/g_1870/stock_market.rb
lib/engine/stock_market.rb

The methods `move_down` and `move_up` on `lib/engine/game/g_1849/stock_market.rb` now are only there to write stuff to the log. Can we remove them?

Refactor 1870 soft ledge move. Use same logic for 1849

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_18_ireland/step/merge.rb

added bank of england stock row, and a custom method to find boe share price.
added some cosmetic changes such as game trigger text.
fixed a minor bug in setup where the boe owner and starting cash was defined inside the share selling for loop.
fixed boe double share

[1848] add boe stock row and initial price

---

lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_sj/step/dividend.rb

After this fix redeemed shares appear in Treasury, and shares there
pay to treasury.

18SJ: Correct handling of full cap (fixes #8038)

---

lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/step/waterfall_auction.rb

Fixes #8050 
This needs to pin any games where all players pass in the initial auction before it completes. I don't have a feel for how often this happens.

21Moon: fix auction when all players pass

---

assets/app/view/game/auto.rb
assets/app/view/game/auto_action/base.rb
assets/app/view/game/auto_action/share_pass.rb
assets/app/view/game_page.rb
lib/engine/action/program_disable.rb
lib/engine/game/base.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/step/program.rb
lib/engine/step/programmer.rb

Fixes #7934 
This required refactoring @programmed_actions code to allow multiple outstanding programmed actions for the same player.
I've run a few 1830 and Harzbahn cases to make sure I didn't break things, however, since this involves UI code changes in server mode, I couldn't check that as completely as I'd like. I did spot check a few games.
Does not require pinning/archiving.

Rolling Stock - add investment round programmed auto-pass

---

lib/engine/game/g_18_carolinas/step/dividend.rb

Fixes #8072 
I don't think this will require any pins. There are only two active games. Although the finished game that found this will fail.

18Carolinas: fix payout of exactly half share price

---

lib/engine/action/use_graph.rb
lib/engine/game/g_21_moon/step/track.rb

Fixes #8010 
No pinning necessary. This should be backwards compatible.
It also addresses a weak spot in my previous code that didn't look at newly-added paths to see which base was being used for the track lay

21Moon: More robust tile-to-base checking

---

assets/app/view/game/route_selector.rb

Fixes #7843 
Originally reported as an 1860 bug, this can affect any game after the autorouter is run

Fix autoroute in RouteSelector to update selected_route

---

lib/engine/game/base.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/loan.rb
lib/engine/game/g_1848/step/special_track.rb
lib/engine/route.rb

more 1848 impl:
1- add routing logic. Map has boundaries, each crossing is a gauge change that adds 0 cost city to route. + train adds one free change to the route
2- privates with abilities retain the ability after company closes if unused. Can be used be either player or  corp until end of game. I made the privates 0 revenue, and can't buy at that point. 
3- added loans logic, boe price goes up, corp goes left twice, can only take one loan per round

[1848] Implement privates, loans and routing

---

lib/engine/game/g_1817/step/acquire.rb

fixing #8103 
The rules are that the starting bid is "the bid may be any multiple of $10 that is at least the minimum bid
and above the previous bid." and minimum bid is share value * stock price.
if a company has 2 shares at 46 (2*46=92), round method will round it down to 90. Rules require it to be 100. 
ceil is the correct method, always rounding up.
This will probably break some games (games where someone took the starting bid on companies with stock value * shares in the 0-5 last digit values.

fix use of round instead of ceil for 1817 bids

---

assets/app/view/game/player.rb
assets/app/view/game/round/stock.rb
lib/engine/game/base.rb
lib/engine/game/g_1848/depot.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/round/operating.rb
lib/engine/game/g_1848/step/cash_crisis.rb
lib/engine/game/g_1848/step/special_track.rb

cert limit goes down based on number of companies in receivership and player count
president has further reduction for causing a company to go bankrupt
company pays compensation, if not enough president is liable. 
No personal bankruptcy, player has negative money, and must make it back by earning it elsewhere.

[1848] implement receivership 

---

lib/engine/game/g_1822_mx/step/track.rb

[1822MX] Builder cubes need to call "pass!" if no additional tiles can be placed.

---

lib/engine/game/g_18_co/game.rb
lib/engine/step/emergency_money.rb

fix #4386
The code change was made in the base package, but the code path is only for games that allow corp ownership of shares,
and not allow president switch during ebuy. I don't think any games with this ruleset would want to ignore corp ownership.
If otherwise, i can create a copy of emergency_money.rb in 18co folder and make the change there. LMK

fix 18co where corps owned shared are ignored to determine pres swap

---

lib/engine/game/g_18_sj/game.rb

fix #8120:
#8020 updated the tile names. Stockholm gray was changed from 131 to X5.
The local method of upgrades_to?, returns non existent tile 131 when trying to upgrade to gray. The super method handles the upgrade fine, no need to override it.

Remove unneeded local method upgrades_to in 18sj 

---

lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb

This fixes a bug that occur late in the game. If any games is broken by this fix this is probably bad as the game cannot be completed OR my fix is not correct. So if this do break any games I think I need to get this back for a revisit.
(The issue is that no shares can be bought from IPO, and occurs when game enters brown phase - and some corporations are changes from Incremental to Full cap. So it should have no effect on games that have not reached that phase.)

18SJ: Fix bug after corporations made IPO (fixes #8128)

---

lib/engine/game/g_18_rhl/game.rb

18Rhl uses this to handle receivership, in case a corporation is
not owned by any player, but method can also be called by player
entity, in which case default implementation is used.

18Rhl: Correct acting_for_entity for method (fixes #8147)

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_1848/depot.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_train.rb
lib/engine/train.rb

- discount on variant D not showing
- kwargs failure when ebuying
- 2E failing when running across borders
- When ebuying showing discard trains when it shouldn't
- lower amount of "unlimited" trains. 999 trains causes major slowdown (duh!)
- don't show shares to sell when ebuying and can_ebuy_sell_shares is false
- can buy more expensive trains in 1848

[1848] Fix issues

---

lib/engine/game/g_1848/step/dividend.rb

[1848] use phase color instead of tile color for boe revenue calc

---

assets/app/view/game/spreadsheet.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/map.rb
lib/engine/game/g_1848/step/blocking_loan.rb
lib/engine/game/g_1848/step/buy_sell_par_shares.rb

add blocking loan step for cases where a company has 0 trains, one step away from receivership. Should able to put down token and get a loan
add k bonus string revenue
fix perth, fix #8186 
check for player cert limit not game cert limit in must_sell?
fixed #8197 
hide show interest in spreadsheet

[1848] minor improvements + perth bug fix

---

assets/app/view/game/game_log.rb
lib/engine/game/base.rb
models/game.rb

Since recently, the messages were being show only to the users in the game, but not to the user that created the game (this is important for the tournaments).
Since a long time ago, when the owner (not in the game) sent a message, the id would show up as the sender and the Master Mode warning would appear. Changed this behaviour.

Show game messages to owner. Make them nicer

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/map.rb
spec/fixtures/18NY/91810.json
spec/fixtures/18NY/README.md

1st edition:
2nd edition:
I think the special logic for fixing the New York tile orientation could be removed by adding stubs to the yellow, green, and brown NY tiles and having the base "track must be preserved" rules, but not only does that change the tiles to differ from the print game, it also might not be easier for players to use - it might look something like this
(I could see players mistakingly thinking the stubs connect to NY for running trains when no such connection exists yet)

18ny future labels

---

lib/engine/game/g_18_sj/game.rb

Base code does not support reuse of base discount for
variant trains. The discount information need to be
repeated.

18SJ: Add discount for E trains (fixes #8232)

---

assets/app/view/game/game_info.rb

This removes spacing around arrows on the Info page
Impetus was to make the 1848 rusting schedule a bit more readable
IMO this change improves readability in general, as the arrows have "natural whitespace" around them, so the add'l whitespace is un-necessary
Old 1830:
New 1830
The 1848 Info page in question (in-progress, not currently live on the site)

make arrows more compact

---

assets/app/view/welcome.rb
lib/engine/game/g_18_rhl/entities.rb
lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/map.rb
lib/engine/game/g_18_rhl/round/operating.rb
lib/engine/game/g_18_rhl/step/lay_tile_checks.rb
lib/engine/game/g_18_rhl/step/special_token.rb
lib/engine/game/g_18_rhl/step/token.rb
lib/engine/game/g_18_rhl/step/track.rb

Redesigned the three green Rhine Metropole hexes to be 2+1/1+2
cities in appearance, but work as one city with 3 slots in
practice. This means that a green such hex that has one or
more slots untokened are passable by everyone. And that such
green hex that are fully tokened are passable for the 3
corporations that have a token in any slot on the hex.
To accomplish this there is a special "make neutral/blocked"
procedure at suitable times during the operation round.
I.e. at start/end of OR, and then any of these 3 hexes
are tokened/upgraded.
Also, fixed upgrade of green Rhine Metropolis hexes.
The methods for route handling, bonuses, distance, revenues
has been rewritten to handle these cases.
Also corrected some minor bugs.

18Rhl: Fix Trajekt handling in Rhine Metropoles (fix #7834)

---

assets/app/view/game/buy_trains.rb
lib/engine/game/g_18_jpt/game.rb
lib/engine/game/g_18_jpt/step/buy_train.rb

Train discount wasn't being applied, as the '`include?`' in line 305 was evaluating true with no `selected_company`.  Checking that there is a `selected_company` allows the elsif at 312/313 to evaluate, and use the TC company discount.
This still left emergency fund-raising triggered, as the default `depot.min_depot_price` doesn't take discounts into account.  I've created `G18JPT::Step::BuyTrain`, which implements a `cheapest_train_price` that understands the TC's discount ability.
Works on the exported version of the game I hit the bug in, and passes rubocop.

[18JP-T] Fix train discount for TC once ability is available.  Fixes #8243

---

assets/app/view/welcome.rb
lib/engine/game/g_1848/meta.rb
lib/engine/game/g_1848/step/buy_train.rb
lib/engine/step/train.rb

revert of a previous fix that added depot trains to buyable_trains. This fixed upgrading, but broke buying trains at limit.
The fix here is to not use buyable trains when exchanging.
This was 'working' in other games that have exchanges because buyable returned trains, but room? was false. The view doesn't show trains if room? is false . In 1848 this breaks because of the 2E, corps can have room to buy 2e, and not other depot trains. 
Change was tested on 1889 to make sure other games aren't broken.
fixes #8303

[1848] fix 8303 and move to 48 to beta

---

assets/app/view/welcome.rb

Alpha and beta should be lowercase in this context, so I adjusted them.
I also fixed a verb that was missing an "s" and removed an incorrect comma.

Fixed typos on welcome page

---

assets/app/view/game/map.rb
lib/engine/game/g_18_sj/map.rb
lib/engine/game/g_21_moon/game.rb

I initially noticed this while playing 21Moon, where Magnetite was showing black background instead of white background.  In light theme, this happens naturally because the background is white.  This PR changes the following:
1. For table cells which explicitly set text color, now explicitly set border color to `font_color` from settings.  Most cells don't need this because the color of the text is already set to this color. [18SJ and 21Moon]
2. Explicitly set background color and text color for the lower three row headers. [21Moon]
3. Take phase colors (yellow, green, etc.) from settings for column headers. [21Moon]
| ![image](https://user-images.githubusercontent.com/5263073/190324122-c2e5dacc-1fff-4235-94c2-d4829a23902d.png) | …

Map legend table improvements for darker themes

---

lib/engine/game/base.rb
lib/engine/game/g_18_dixie/companies.rb
lib/engine/game/g_18_dixie/game.rb
lib/engine/game/g_18_dixie/phases.rb
lib/engine/game/g_18_dixie/step/dividend.rb
lib/engine/game/g_18_dixie/trains.rb

This is using a system similar to 1862 because there is a private that lets a player add additional spare parts which lets a train last longer - the key difference between spare parts in 18Dixie and warranties in 1862 is spare parts are only used after the train /could/ rust, not every time

18Dixie: 5 trains come with delayed obsolesence

---

lib/engine/game/g_1848/step/buy_train.rb

fixes #8343
Default is to pass train buy if can't buy train. However during forced buy train when corp buys the 2e, this caused to skip train buying, despite the must_buy_train returning true.

[1848] fix 8343

---

lib/engine/game/g_1848/step/buy_train.rb

closes #8357 
When a company has enough money
When a company has enough for a 2E but not a real train

[1848] Fix when 'must take loan' messages appear

---

assets/app/view/game/part/borders.rb

The default color is the same as the brown tiles, making it difficult to see all of the borders easily.  This uses the less-often used sepia color setting for those borders.  As far as I can see, 1825 is the only game with sepia tiles, and it has no map borders to cause conflicts.
Unfortunately, with the default colors, this inverts the text color on borders which have a cost (see below).  How big of an issue is this?  There are other solutions as well, like manually setting the colors in the map files.

Change border mountain color to sepia to distinguish between brown tiles

---

assets/app/view/game/buy_trains.rb

Adds in a missing space from the text when players can buy trains from other players.

Add missing space to train buying text

---

lib/engine/game/g_1873/step/draft.rb

The winner of the premium auction must buy something and cannot pass. If a player set autopass in draft before winning the auction, this would trigger an illegal move and break the game.
fixes #8345

[1873] Disable autopass in draft if passing is not a valid action.

---

lib/engine/game/g_18_gb/round/stock.rb

18GB: Fix an issue where the 'presidencies' variable on the stock round (used to record presidencies the player possessed at the start of their stock round turn, to check eligibility for double-buys) was being set on player change in the stock round but not at the beginning of a new stock round.
Closes #8402

18GB: Fix issue with check for existing presidencies at start of SR

---

lib/engine/game/base.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_21_moon/game.rb

Fixes #7823
Rules citations showing that result will be the same because either minor companies operate according to the face value, or they are specifically accounted for in the operating order.
| Game    | Description |
| 1873     | 4. - In each OR, first the still independent private mining companies operate in ascending order of their face values (see 4.2). _Same result_ |
| 18EU   |  4.4 - Each Operating Round begins with the Minor Companies operating in numerical order from 1 though 15.   _Same result_  |
| 18MAG   | VI.1 - First the minor companies operate in ascending order of number. _Same result_ |
| 18 New England |  The minor companies operate first in descending share price order.  _Because minors are covered by operating order, no need to …

Sort entities by operating order

---

lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb

Fix a bug where the `G18GB::Round::Operating` instance was checked for a `presidencies` instance variable which doesn't exist on Operating rounds, only in Stock rounds. This check is not needed when buying after converting to 10-share in emergency money raising and was causing games to become inaccessible if they reached featured a corporation converting to 10-share in EMR whilst in the green area of the market.
Closes #8408

18GB: Don't check non-existent presidencies variable during an OR

---

lib/engine/game/g_18_gb/entities.rb
lib/engine/game/g_18_gb/map.rb

- Add an extra piece of track to the blue Severn Tunnel tile G33 to match 2E physical copies being produced and enable an edge case where track is laid in Merthyr Tydfil (C20) pointing in to the Severn estuary (C22). In practice this is an extremely rare case and the track is entirely additional so should not impact existing games.
- Update the MC and GN private company descriptions to be clear that the station token provided is additional rather than an existing token of the corporation. Furthermore, update the language to refer to tokens as 'tokens' throughout rather than 'markers'. Closes #8411

18GB 2E tweaks: G33 tile extra track & private company descriptions

---

assets/app/view/game/part/city.rb
assets/app/view/game/part/city_slot.rb
assets/app/view/game/part/partitions.rb
lib/engine/game/g_18_rhl/map.rb

Fixes #7387
1. Tile in RHL had two of the same label on it.
2. In the map view, `@game` is nil, so CitySlot needs to handle a nil game (18Rhl map view was previously throwing an undefined method error)
3. In the map view, `@game` is nil, so partitions should render if that's the case, so they appear on the map view.

Fix river partitions rendering on map URL

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/step/track_and_token.rb

UI improvements for 18GB:
- The placement of home tokens during game setup is no longer printed in the game log for every single corporation. Alongside this change, code for placing a corporation's home token when the tile was already yellow or green was also removed now this is no longer applicable.
- The bank-owned/unstarted corporations in the Entities tab are now sorted by tier first and then by name during the initial auction round and SR1. (And then only by name from then on, as this information is no longer applicable.)
- When SR2 begins, a log message now reminds players that Tier 2 corporations can be started.
- A Timeline section is added to the Info tab reminding key time-based info, i.e. Tier 2 corp availability in SR2, the train export, and the trigger for end-game …

18GB UI improvements

---

assets/app/view/game/game_info.rb

Fixes #6987
While I was fixing this, I noticed that the obsolete schedule wasn't properly being hidden.  Even if there no obsolete in a game, that dictionary still has `nil` as a key.
| | 1846    |
| Old | ![image](https://user-images.githubusercontent.com/5263073/194175833-0050b3c8-62b1-4179-9c9c-c0495771b6e3.png)  |   
| New | ![image](https://user-images.githubusercontent.com/5263073/194175923-74eb70ad-736f-4239-b9b0-fbe34a28b87d.png) |
| | 1822 PNW |   
| Old | ![image](https://user-images.githubusercontent.com/5263073/194176031-bfe80882-8407-4eb3-92e3-a84e39effb0c.png)  |   
| New | ![image](https://user-images.githubusercontent.com/5263073/194176061-929c4f73-be7b-4cd8-a00d-4402b0fdeb95.png) |
| | 18Scan |   
| ----------- | …

Show variants in rust schedule / properly hide obsolete schedule

---

lib/engine/game/g_18_sj/step/dividend.rb

In Oscarian age, bank shares pay to corporation, not IPO shares.
In base game, full cap corporations do not get any pay for shares, while incremental cap corporations only get paid for shares in treasury.

18SJ: Correct pay out to corporations [fixes #8381]

---

lib/engine/game/g_18_rhl/game.rb

Include the entity defaults in the `WithNameAdapter` returned by `acting_for_entity?` in 18Rhl, so that when other parts of the code check if this entity is a player etc. it responds appropriately. Closes #8466

18Rhl: custom adapter returned by acting_for_entity? for receivership situations should include entity defaults

---

lib/engine/game/g_18_ny/game.rb

Check for and avoid dividing by a share price of zero when trying to calculate possible share bundles that could be emergency issued. Closes #8470

18NY: Don't divide by zero in emergency share issue calculations

---

lib/engine/game/g_1840/entities.rb

1840: Update the descriptions for the private companies Karlskirche, Hofburg, and Stephansdom so they do not suggest a route can run through the relevant tile (since it will be a red tile which does not allow a through route). Closes #8487

[1840] Correct private company descriptions

---

lib/engine/game/g_18_sj/step/dividend.rb

Corrected full cap corporations that has redeemed shares.
This might break games. Pin/Archive as appropriate.
It is possible that no games break, after previous correction.

[18SJ] Make another attempt to fix revenue problem (fixes #8381)

---

lib/engine/game/base.rb
lib/engine/tile.rb

Update the `upgrades_to?` check in the base game definition to account not just for the quantities of city/towns on the two tiles being compared, but also that each city/town on the old tile is present (in terms of a city/town with the same combination of edge connections) on the new tile.
- This avoids the issue of illegal multi-city tile upgrades being visible in the tile manifest when clicking on a tile to check valid upgrades - which closes #8488 
- To avoid adding an overhead to every upgrade check in all games, this check is only performed for multi-city tiles (e.g. OO tiles) - single-city tiles are already well-covered by the existing check that all edge connections are preserved
- This also means fewer illegal-to-place tiles are passed into the `legal_tile_rotations` check in …

Tiles tab: don't show potential upgrades with non-matching cities

---

assets/app/view/game/spreadsheet.rb
lib/engine/game/g_1856/corporation.rb
lib/engine/game/g_1856/game.rb

show corporation type and escrow in 1856 spreadsheet - this makes it very easy to see the amount of capital each company will get when you buy a share

show corporation type and escrow in 1856 spreadsheet

---

DEVELOPMENT.md

This informs new devs how to use [Github Codespaces](https://github.com/features/codespaces)
Should reduce the startup friction and allow dev across OS environments, etc
Also allows for repeatable builds and less "works for me"

update dev docs to reflect new GH codespaces tool

---

lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb

Use the safe navigation operator during the check of the stock round's `presidencies` variable in `already_president?`  in `buy_sell_par_shares`.
This avoids any errors where this property is examined during round/step setup. By the time the first player in the stock round is actually able to act, `record_current_presidencies` on the stock buying step will have run and populated the variable.
Closes #8526

18GB: Use safe navigation when accessing presidencies variable on SR

---

lib/engine/game/g_18_gb/game.rb

When allowing multiple trains to connect to satisfy the NS or EW bonuses in 18GB, don't allow this connection to take place through an offboard location. Closes #8532

18GB: Don't allow routes to connect at offboards (for NS/EW bonus)

---

assets/app/view/game/part/town_dot.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/track.rb
lib/engine/game/g_1868_wy/step/waterfall_auction.rb
lib/engine/part/town.rb
lib/engine/tile.rb

* new/renamed functions with descriptive names instead of IDs for private company and related minor getters
*  remove unused "double" towns (previous iterations of 1868 Wyoming used two down dots next to each other for "double boomtowns", those have been removed from the design)
*  remove unused `setup_event_methods`

[1868WY] cleanup: better function names, remove dead code

---

assets/app/app.rb
assets/app/view/create_game.rb
assets/app/view/game/game_meta.rb
lib/engine/game/g_1830/meta.rb
lib/engine/game/g_1867/meta.rb
lib/engine/game/g_1868_wy/meta.rb
lib/engine/game/g_18_chesapeake/meta.rb
lib/engine/game/g_18_fl/meta.rb
lib/engine/game/g_18_los_angeles/meta.rb
lib/engine/game/g_18_new_england/meta.rb
lib/engine/game/g_18_va/meta.rb
lib/engine/game/g_rolling_stock/meta.rb
lib/engine/game/meta.rb
public/assets/main.css

* no title is selected by default
* fixes #6900; when taking the steps to reproduce that issue, the new
behavior is the last title that was selected is still selected, instead of
1817 being selected but showing the wrong game variants / optional rules
* game setting inputs (async/live, player count, etc) are not shown until a
title is selected
* the long dropdown is replaced with a table showing game titles, location, and
status (prod/beta/alpha, and prototype)
* keyword search allows users to narrow games shown in table not just by title,
but by publisher, designer, etc.
* group all prototype games at the end, fixes #7493
* when a game is selected, scroll to top to start picking game settings
Search by "1817" to find 1817 and games inheriting from it:
Search by designer:
Search by …

Create New Game page: replace dropdown with a table, add input to filter by keyword

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/map.rb
lib/engine/game/swap_color_and_stripes.rb
lib/engine/part/stripes.rb

In 1868 Wyoming, Wind River Canyon (WRC) is a yellow-grey tile, which can be laid from phase 2 (yellow), but can never be upgraded (gray).
Since the new function swaps the color and stripes values, the colors/stripes will visually swap on the tile after it has been laid.
[#5011]
This may also be useful for striped tiles in 1825, 1829, and 1898 [#6083] [#6359] (cc @ventusignis @roseundy)
----
WRC tile before lay -- yellow with gray stripes:
After lay -- gray with yellow stripes:

[1868WY] helper function for swapping tile colors and stripes, WRC

---

lib/engine/game/g_1871/step/buy_train.rb

The constant is set correctly in the game class; in the [base Train EMR module the constant is referenced](https://github.com/tobymao/18xx/blob/a6cb05dc3c2df2bb9f8b31eeba257989aeab4cb3/lib/engine/step/train.rb#L120), but in this override that reference to the constant was missed
[Fixes #8519]

[TOP 1871] enforce MUST_SELL_IN_BLOCKS in BuyTrain#can_sell? override

---

lib/engine/game/g_1822/step/discard_train.rb
lib/engine/game/g_1868_wy/step/buy_train.rb
lib/engine/train.rb

also use new helper function in 1822 when discarding a train (cannot be used on purchase there, as an L can be flipped to a 2 after purchase)
[#5011]

[1868WY] prevent trains from being flipped once purchased

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/stock_round_action.rb

* placing DPR's home or exchanging the private for the UP double share takes up the full stock round action, preventing any selling then buying to happen
* placing DPR's home or exchanging the private for the UP double share are implemented in later PRs
* available par prices vary by phase
[#5011]

[1868WY] Stock Round Action

---

assets/app/view/game/double_head_trains.rb
assets/app/view/game/round/operating.rb
lib/engine/action/double_head_trains.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/dividend.rb
lib/engine/game/g_1868_wy/step/double_head_trains.rb
lib/engine/step/dividend.rb

* in this game, 2 or more trains can be combined and run as if their city and town numbers added up (respectively), allowing much greater reach to hit east-west runs and the Golden/Northern spikes earlier
* trains are combined and a new virtual train is created; its ID is based on the train IDs used to make it, so if the same trains are combined in a future OR, the new train's ID will match, and its previous route will be highlighted to run again
[#5011]

[1868WY] Double Heading trains

---

assets/app/view/game/issue_shares.rb
assets/app/view/game/sell_shares.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/share_pool.rb
lib/engine/game/g_1868_wy/step/double_share_protection.rb
lib/engine/game/g_1868_wy/step/stock_round_action.rb
lib/engine/game/g_18_chesapeake/share_pool.rb
lib/engine/game/g_18_tn/share_pool.rb
lib/engine/share.rb
lib/engine/step/share_buying.rb

* in the Issue Shares view, add flags to the bundle; this affects 1849
* exchanging the private for the double share counts as a stock round action (ie, the owner cannot sell/buy other shares on the same turn as making the exchange)
Rules Notes:
In 1868 Wyoming, the final private can be exchanged for the "Ames Brothers double share", a 20% certificate for the Union Pacific Railroad, like the last 20% cert that the railroads in 1849 have.
The Ames Brothers share has some additional rules to protect the owner from losing it involuntarily:
* as in 1849, they can exchange two 10% shares for the president's cert to continue holding the double cert
* unlike 1849, if they don't have two 10% shares when the presidency is dumped on them, they may immediately buy 10% shares until they have two, …

[1868WY] Ames Double Share

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles1/game.rb

* don't defer Erie's second token [Fixes #7612] 
* clear the graph after the deferred token is placed [Fixes #7183]

[1846 2p] deferred token fixes

---

lib/engine/game/g_1846/step/buy_train.rb

[Fixes #7713]
Added `pins` label since pins are possible, but I don't know for certain yet that there is a game where someone took advantage of buying a train from a presidentless corporation

[1846] prevent cross-buying train from presidentless corporation

---

lib/engine/part/node.rb

Before this change the track gauge was not being checked when track sections between nodes were walked. This meant was possible to walk between two nodes that had intervening narrow gauge track when skip_track had been set to :narrow.
This is needed for 1858, it might not be possible to trigger this bug in other games. In 1858 you're allowed to build broad gauge and narrow gauge track so that they meet at a hex edge, but it's not possible to trace a route or run any trains down a link like this. So you can have something like node, broad gauge track, narrow gauge track, node. As the skip_track setting was not being passed down it was possible for this route to be walked without objecting to the gauge change.

Propogate skip_track parameter from node.walk to path.walk

---

lib/engine/game/g_1861/game.rb

It wasn't possible to view the previous routes run by the RSR as the default implementation of `operated_operators` only includes the `@corporations` and `@minors` arrays. Override this to also include the RSR.
Fixes issue #5620.

[1861] Add RSR to the route history list

---

assets/app/view/game/part/borders.rb

A new type of hex border, to show provincial boundaries. Styled as a dashed orange line.
Some existing games (1848 for example) are using the 'mountain' border type for provincial boundaries, but I think it makes sense to have a dedicated type for these borders.
This change has been extracted from pull request #8578. 1858 which has token costs that are calculated by looking at provincial boundaries.

Add a border type of 'province'

---

lib/engine/game/g_1861/game.rb

Issue #5528 is for the game end description for 1861 on the info tab. It does not correctly describe the game end timing. The game behaviour is correct, it is just the text that needs to be changed.
The game does not always finish after the next set of operating rounds. If the first 8-train is purchased in the first round of an operating round set then the game finishes at the end of the current set (which is extended to three operating rounds). This PR attempts to give a more accurate description of when the game ends. It is far more verbose than the previous description, but I couldn't come up with anything more concise.
This is the relevant paragraph from section 13 of the AAG (second edition) rules:
> The game end is signalled by the purchase of the first 8-train. If this purchase is …

[1861] Corrected description of the game end timing

---

lib/engine/game/g_18_usa/entities.rb

They were commented out for development purposes and not added back in. Unfortunately, this will break every 18USA game.

[18USA] Add-in additional no subsidy subsidies

---

lib/engine/depot.rb
lib/engine/game/base.rb
lib/engine/train.rb

1858 has wounded trains that run for half revenue and can be discarded during the train buying step. You are allowed to buy these wounded trains across between corporations. That isn't possible with the current implementation of obsolete trains: there's a check in `Engine::Train.buyable` that blocks this for an obsolete train.
This patch adds a flag to the game class, `ALLOW_OBSOLETE_TRAIN_BUY`, that can be set to allow obsolete trains to be bought across. It has a default value of `false` and so does not change any behaviour for other games.
This commit has been extracted from pull request #8578.

Add a flag to allow obsolete trains to be bought between corporations

---

lib/engine/config/tile.rb

Add a couple of standard tile definitions:
- Tile 71 is a gently curved section of narrow gauge track, with two towns on it.
- Tiles 108 dual gauge plain track tile, in a K-arrangement (Lawson-type track).
These are both needed for 1858. This has been extracted from pull request #8578.

Add definitions for tiles 71 and 108

---

lib/engine/game/base.rb
lib/engine/game/g_1880/entities.rb
lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/minor.rb
lib/engine/game/g_1880/round/stock.rb
lib/engine/game/g_1880/share_pool.rb
lib/engine/game/g_1880/step/dividend.rb
lib/engine/game/g_1880/step/route.rb
lib/engine/share_pool.rb
lib/engine/step/minor_withold.rb

always market price & no limit on ownership
add float precent change events 
add partial cap during float
add foreign investor share when floating a corp 
foreign leases train
auto withold dividends for foreign investors 
add broker fee on selling shares
remove set SR (in this game SR happen in the middle of an OR when a train type is bought our or removed, will be implemented later)
sold share go to ipo, never to market
Note: Foreign investor owning share doesn't show up in the UI, will need to fix the view files to fix this bug.

[1880] shares, foreign investors, broker fees

---

lib/engine/game/stubs_are_restricted.rb
lib/engine/part/stub.rb

Stubs are used to enforce track connections when a tile is laid in a hex. This check is done by `Engine::Game::StubsAreRestricted.legal_if_stubbed?`. This method is currently written to only handle a single stub in a hex, if there are multiple stubs then only the first one is checked against the track exits of the placed tile.
This pull request is to enhance this check to ensure that all stubs are connected by the new tile.
Most games that use stubs only ever have a single stub in a hex, so will not be affected by this change. I could only find two games that have multiple stubs in a hex:
- 18Rhl has two stubs in hex E10 in the Ratingen variant. It has custom code in `legal_tile_rotation?` to check the tile placement is valid. This change would allow that code to be removed. (cc …

Handle multiple stubs in a hex

---

assets/app/view/game/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_1880/corporation.rb
lib/engine/game/g_1880/entities.rb
lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/minor.rb
lib/engine/game/g_1880/step/buy_sell_par_shares.rb
lib/engine/game/g_1880/step/buy_train.rb
lib/engine/game/g_1880/step/check_fi_connection.rb

show FI shares in corp view
add b3 event  -> corporations getting more capital if 5 shares are sold, ongoing effect after
FI connection check and merger of FI and corp.
Train marker to round description
FI stops operating event

[1880] More Foreign Investor logic and capitalization event

---

assets/app/view/welcome.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/meta.rb

- Allow player-count-specific variants to be selected in 18GB without limiting the player count of the game. (Variants which match the player count when the game is launched will be used and others ignored.) This allows e.g. a 3-4 player game to be created that will use the 4p alternate setup if it launches with 4 players and the (only) 3p setup if launched with 3 players. This is consistent with the implementations in 18FL and 18VA and closes #8579
- Move 18GB to Production. (No new game/rules-related issues have been raised since #8550 was merged on 30th Nov; the only remaining cosmetic/UI issue is closed by this PR as per the previous point.)

18GB: Increase player-count variant flexibility & move to Production

---

lib/engine/step/share_buying.rb

If exchanging a company for a share bundle the share price paid might need to be adjusted. Accept an `exchange_price` parameter and pass this on to `Engine::SharePool.buy_shares`.
This is another commit extracted from pull request #8578. This is needed for 1858 where exchanging a private company for a president's share means you only pay for half of the president's share.

Add exchange_price parameter to Engine::Step::ShareBuying.buy_shares

---

lib/engine/game/base.rb
lib/engine/step/tokener.rb
lib/engine/step/tracker.rb

This pull request originated as part of PR #8578 for 1858 Iberia and needs an explanation that's far longer than the patch. It's marked as draft, as I'm far from certain as to whether this is the correct approach.
The problem being addressed is 1858's particular routing requirements. 1858 has multiple gauges of track: broad, narrow and dual gauge. To be able to lay track or place a token a corporation much be able to trace a route from one its tokens that only has broad and dual gauge track, or narrow and dual gauge track. If the only route would include both broad and narrow gauge track then this is invalid.
The Graph class cannot currently handle these requirements. It can ignore gauge entirely, or be instructed (through the `skip_paths` setting) to exclude one gauge of track.
Other …

Add clear_graph methods to Game class

---

assets/app/view/game/abilities.rb
lib/engine/ability/README.md
lib/engine/ability/purchase_train.rb
lib/engine/depot.rb
lib/engine/game/base.rb
lib/engine/game/g_1880/entities.rb
lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/map.rb
lib/engine/game/g_1880/step/buy_sell_par_shares.rb
lib/engine/game/g_1880/step/buy_train.rb
lib/engine/game/g_1880/step/company_pending_par.rb
lib/engine/game/g_1880/step/rocket_purchase_train.rb
lib/engine/game/g_1880/step/selection_auction.rb
lib/engine/game/g_1880/step/simple_draft.rb
lib/engine/phase.rb
lib/engine/step/selection_auction.rb

more 1880 implementation:
Rocket of china private ability
saved SR triggered in the middle of an OR, then come back to SR when done
implement par order
add par location to corp status array
assign bcr share to FI.
Notes:
- At this point, parred companies are auto allocated to the top available position in each par price, this will change, We're in the middle of implementing a UI for picking exact par choice. 
- The logic to discard all trains is simplified and doesn't include cross buying, or buying trains that do not discard all trains (20, 8e, 10) this is implemented in my local branch and will be added to the next pr, once this is approved & merged

[1880] rocket of china, implement SR trigger, par order, bcr auto par

---

lib/engine/game/g_1822_pnw/entities.rb

In 1822PNW, the word "associated" has become a keyword in defining different types of minors: Associated Minor and Unassociated Minor (per [rules 3.2.2](https://www.dropbox.com/s/aae7vxds0tjdo9u/1822PNW%20Rules%20R4.pdf?dl=0)).  
It looks like the Concession certificates in prior 1822 variants used the description of "50% Director's Certificate in the **associated** Minor Company."  This mix of terminology now causes confusion, so this PR removes the term when not specifically referencing a capital-A Associated Minor Company.

Remove "associated" term from non-associated minors descriptions

---

lib/engine/game/g_1867/game.rb
spec/fixtures/1861/167259.json
spec/game_state_spec.rb

Ian Wilson noted in issue #8572 that minor companies are being nationalised in the wrong order. Where multiple minors are nationalised at the start of phase 4, 6 or 8 this should be done in stock market order. The order can make a difference if the national railway runs out of tokens whilst these minors are being nationalised, it should get the tokens of the first ones to be nationalised.
This pull request fixes this order. It also changes the order of major company nationalisation – this is suppose to happen in stock market order, but it was in reverse stock market order.
There are also tests added for both the minor and major company nationalisation order.
This change has the potential to break a few games as it might change the location of the national railway's tokens, so 1861 and …

[1861/1867] Fix nationalisation order

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/golden_spike.rb
lib/engine/game/g_1868_wy/map.rb
lib/engine/game/g_1868_wy/step/route.rb

The spikes can each be only run once, by completing particular E-W routes, and then extending the route one additional town stop west to the spike location.
* Golden Spike: Omaha to Promontory Summit
* Northern Spike: any E to Billings to Independence Creek
* completing the spike gives a one-time revenue bonus, and then removes the Spike revenue location and upgrades the corresponding offboard tile(s) for Ogden or Billings (which has two separate locations on the map which both count as Billings)
In the unlikely event that a Railroad completes a Spike and has an additional E-W route to Omaha/Bililngs, the Spike route is run first, and then the tile are upgraded, and then the other route is run with the new revenue. Since we have routes submitted all at once, the method …

[1868WY] Golden/Northern Spike: 1-time bonuses for certain E-W runs

---

lib/engine/game/g_1867/step/merge.rb
lib/engine/game/g_1867/step/reduce_tokens.rb

Issue #8589 has reported three issues with removing tokens when minor companies merge and there is a hex with more than one of the merging companies' tokens.
1. The help message is misleading.
2. If three or more minors merging it is possible to remove all but one of the tokens.
3. If two tokens are in the same city (not just the same hex) then one gets put back on the minor's charter, and then moved across to the new public company as a zero-cost token.
This pull request fixes all of these.
The changes to `help` fixes the first of these.
The changes to `process_remove_token` fix the second. It makes sure that you can't remove tokens from all but one hex, unless there was already tokens in just one hex.
And the deleted line from `finish_merge_to_major` fixes the last one. This one was …

[1861/1867] Fix merger token bugs (issue #8589)

---

lib/engine/game/g_1867/game.rb

This method is only called from code that is determining the end of the game, and it will never end after a merger round, so use the base class version of this method which always returns `Round::Operating`.
This fixes tobymao/18xx#8660 which reported that 1861 would not finish if the bank breaks in phase 2, as a merger round never happens.

[1861/1867] Delete `round_end`, use version from base class

---

models/user.rb

not totally sure if this is the right fix, but we encountered a bug where the custom webhook url wasn't working because somebody accidentally put a trailing space in the Webhook URL input. I also saw a similar, older issue that this should solve https://github.com/tobymao/18xx/issues/8142

strip param values in User#update_settings

---

lib/engine/game/g_1880/step/selection_auction.rb
lib/engine/step/selection_auction.rb

when all passing win occurs in 1880 the next auction breaks.
This is a fix for the issue

[1880] fix auction

---

lib/engine/game/g_1822_pnw/map.rb

This was breaking the 1822PNW tiles page.

[1822PNW] Change spelling 'grey' to 'gray' on tile 455
