lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/round/stock.rb
lib/engine/game/g_18_usa/step/dividend.rb
lib/engine/game/g_18_usa/step/loan.rb

First-round off commits for 18USA. This one adds the SV Movement, Metropolis Randomization and fixes the offboards that were broken by the move to the new structure.

18 usa stock value movement, metropolitian cities, offboards

---

assets/app/view/game/stock_market.rb

zigzag stock market: fix box_height

---

lib/engine/game/base.rb
lib/engine/game/g_1870/game.rb

It turns out the special actually skips other important stuff, so here's another try...

1870: Don't use special for tiles lays

---

lib/engine/game/g_1856/corporation.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/loan.rb
lib/engine/game/g_1856/step/token.rb
spec/fixtures/1856/README.md
spec/fixtures/1856/hotseat001.json

I had some trouble with the relatively bigger CGR train borrow PR with
getting everything working in the unit test there so I decided
that making some shorter PRs to clean up the small edge cases
so that I can get some rules-correct unit tests in would make my
life less painful

1856 odd fixes

---

lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_fl/step/buy_sell_par_shares.rb
spec/fixtures/18FL/README.md
spec/fixtures/18FL/hotseat01.json

Create a unit test for 18FL and fix assorted opal v ruby bugs

18fl unit test

---

lib/engine/abilities.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/round/operating.rb
lib/engine/game/g_1870/step/check_connection.rb
lib/engine/game/g_1870/step/connection.rb
lib/engine/game/g_1870/step/connection_dividend.rb
lib/engine/game/g_1870/step/connection_route.rb
lib/engine/game/g_1870/step/connection_token.rb
lib/engine/game/g_1870/step/dividend.rb

This includes a few lines from #4284 (834 - 841 of `game.rb`), but they should merge well with or without each other

1870: Connection runs (last big commit until 1870 is ready)

---

assets/app/view/game/spreadsheet.rb

fixes #4357
regression due to https://github.com/tobymao/18xx/commit/27cd6b97d8497c9805a30aa7ea760bc4dd9f8b39
@daniel-sousa-me

fix regression

---

assets/app/view/game/hex.rb
assets/app/view/game/map.rb
assets/app/view/game/map_controls.rb
assets/app/view/game/tile.rb

Unless I totally overlooked something there’s actually no need to store vars if the values are saved in LocalStorage anyway.
Show/Hide are removed in favor of symbols => Slimmer buttons, that don’t wiggle and are less prone to need 2 lines.
(From a semantics pov these should be checkboxes instead of buttons, though …)

refactoring map controls

---

lib/engine/game/g_1849_boot/game.rb

Resolve issue #4106

---

lib/engine/game/g_1860/game.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/step/dividend.rb

Added correct route information for trains.
- Default for small trains
- x+x for medium trains
- just cities/offboard for large trains
Also changed the dividend step size

18cz Added Route Information

---

lib/engine/game/g_1817/round/stock.rb

Only look at positive shares for short squeeze check [#4363]

---

lib/engine/game/g_1828/game.rb
lib/engine/game/g_1828/step/track.rb
lib/engine/step/tracker.rb

- OO tile layer decides token placement
- For 1828, make it the token owner instead and skip if OO is filled with blocking tokens

OO tile layer decides token placement

---

lib/engine/game/g_1828/step/merger.rb

General clean-up to the 1828 merger step and more logging.

1828: Refactor merger step

---

lib/engine/game/g_1849_boot/game.rb
public/logos/1849_boot/AL.svg
public/logos/1849_boot/FCU.svg
public/logos/1849_boot/IFP.svg
public/logos/1849_boot/MC.svg
public/logos/1849_boot/PL.svg
public/logos/1849_boot/SFCS.svg
public/logos/1849_boot/SFM.svg
public/logos/1849_boot/SFR.svg

This didn’t quite work out as expected … It’s worth merging after Scott’s PR is merged, because of the optimized logos commit anyway.

Scottredracecar boot merge

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/special_track.rb

Cleaned up the game conf a bit.

1870: Reworked privates to fix regressions.

---

assets/app/view/create_game.rb
assets/app/view/form.rb
assets/app/view/game/auto.rb
lib/engine/action/program_buy_shares.rb
lib/engine/step/buy_sell_par_shares.rb
public/assets/main.css
spec/assets_spec.rb
spec/fixtures/1889/hs_jmmljkbw_17502.json
spec/fixtures/1889/hs_lhglbbiz_17502.json
spec/lib/engine/games/game_spec.rb

Auto buy till number

---

lib/engine/game/g_1861/meta.rb
lib/engine/game/g_1861/step/buy_train.rb

fixes #3832
Also, make 1861 production

1861: RSR if trainless must buy cheapest, otherwise must buy from depot.

---

assets/app/view/game/companies.rb
assets/app/view/game/company.rb
lib/engine/game/base.rb
lib/engine/game/g_1867/game.rb

1861/67: Show company value when owned by a corporation

---

lib/engine/game/g_1822/round/stock.rb

- If you bid more then 100 in phase 1, and not par price * 2 in phase 2 that money goes to the bank. Make a log message about this.
fixes #4398
This change shouldnt affect any current games.

[1822] Overpayment on minors

---

assets/app/view/game_card.rb

game card: archived styling

---

lib/engine/game/g_1822/step/buy_sell_par_shares.rb

- You should be able to buy a share with tax haven even if you at cert limit.
fixes #4402
This change shouldnt affect any current games.

[1822] Tax haven

---

lib/engine/game/g_18_neb/game.rb

- simple change to fix tile upgrade in Omaha

[18Neb] fixes Omaha hex so that it can be upgraded to green and beyond

---

lib/engine/graph.rb
lib/engine/part/node.rb
lib/engine/part/path.rb

Revert "[1822] Refactor graph walk"

---

lib/engine/game/base.rb
lib/engine/game/g_1861/game.rb
lib/engine/game/g_1861/meta.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_1867/meta.rb

Implement 1861/1867 2 player rules

---

assets/app/view/user.rb

profile: fix input width

---

lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb

Makes it more clear that an ability was used
Resolves #4334

18CZ Added log for ability used

---

lib/engine/game/g_18_new_england.rb
lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/meta.rb
lib/engine/game/g_18_new_england/step/draft_minors.rb

* adds game.rb, meta.rb
* adds initial draft minors step

[18NewEngland] 18NewEngland initial implementation

---

lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb
spec/fixtures/1822/hs_lxemeslq_30797.json
spec/lib/engine/games/game_spec.rb

1822: Auto-bid should only stop if player goes from winning to losing a bid

---

assets/app/view/game/company.rb
assets/app/view/game/round/auction.rb
assets/app/view/game/round/stock.rb
assets/app/view/game_page.rb

Fix problem with 1817 subsideries not in game

---

assets/app/view/game/player.rb
lib/engine/game/base.rb
lib/engine/game/g_18_cz/game.rb

Made it a little bit more generic. Maybe other games can use the default implementation more
CHanged the display of prioty buttons for most_cash orderings to the 1828 style
closes #3959

Added Option to log all players after reorder

---

assets/app/view/game/part/location_name.rb

Choose center location in three edge cities tile

---

assets/app/view/game/player.rb
assets/app/view/user.rb

Also add that Track 1 = Your color
fixes #2207

Add player colors on entity page

---

assets/app/view/game/loans.rb
lib/engine/game/g_1817/step/acquire.rb
lib/engine/game/g_1817/step/bankrupt.rb

Move payoff loan left (fixes #4372)
Don't repeat log about liquidation if corp is already in liquidation (fixes #4026)
Improve pass button phrase (fixes #3724)

1817: Minor ui tweaks and log improvements

---

lib/engine/game/g_18_ireland.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/meta.rb

Initial boiler plate for 18Ireland no actual code.

Initial boilerplate 18Ireland config files

---

lib/engine/game/g_1822/meta.rb
lib/engine/game/g_1824/meta.rb
lib/engine/game/g_1830/meta.rb
lib/engine/game/g_1849/meta.rb
lib/engine/game/g_1860/meta.rb
lib/engine/game/g_1861/meta.rb
lib/engine/game/g_1867/meta.rb
lib/engine/game/g_1882/meta.rb
lib/engine/game/g_1893/meta.rb
lib/engine/game/g_18_chesapeake/meta.rb
lib/engine/game/g_18_co/meta.rb
lib/engine/game/g_18_cz/meta.rb
lib/engine/game/g_18_fl/meta.rb
lib/engine/game/g_18_mag/meta.rb
lib/engine/game/g_18_ms/meta.rb
lib/engine/game/g_18_tn/meta.rb

I just noticed #4474, so to save any duplicated work I’ve extracted this commit from a larger pull request I’m preparing for #4271.

Populate subtitles

---

lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_neb/game.rb
lib/engine/graph.rb
lib/engine/part/node.rb
lib/engine/part/path.rb

- A new try on the nodewalk, this time only for lawson tiles.
- An optimization from dfan not to dup the visited

Lawson node walk

---

assets/app/view/create_game.rb
assets/app/view/game/game_meta.rb
lib/engine/game/g_2038/game.rb

Show game info on Create New Game page.

---

lib/engine/game/g_1822/step/buy_sell_par_shares.rb

[1822] use default log msg for passing ("declines to")

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/dividend.rb

- Pay of debt as soon as a player gets money.
fixes #4462
This change might affect games.

[1822] Player debts

---

lib/engine/game/g_1870/meta.rb
spec/fixtures/1870/README.md
spec/fixtures/1870/hs_ufqpdrvi_1615279805.json

Everything seems to be working correctly and I think this is ready for alpha after #4528 is merged.

1870: add fixture from mock game and move to alpha

---

assets/app/view/game/game_meta.rb
public/assets/main.css
spec/assets_spec.rb

Include game title in game info

---

lib/engine/game/g_1822/game.rb

- Made the LUR ability shows itself during the track lay and token step as well.
fixes #4522
This change does not affect any of the currect games.

[1822] Lur

---

lib/engine/game/g_1870/game.rb

closes #4545 
Checked game map: https://boardgamegeek.com/image/343004/1870-railroading-across-trans-mississippi-1870

[1870] fix terrain cost of M14

---

assets/app/view/welcome.rb
lib/engine/game/g_18_neb.rb
lib/engine/game/g_18_neb/game.rb
lib/engine/game/g_18_neb/meta.rb
lib/engine/game/g_18_neb/step/price_finding_auction.rb

- fixes 5/7 train
- changes module name to 18Neb
- adds track cost for second tile lay

[18Neb] fixes train, changes module name to 18Neb

---

assets/app/lib/color.rb
assets/app/lib/settings.rb
assets/app/view/game/player.rb

up to 16 player_colors

---

lib/engine/game/g_1870/round/stock.rb

I fixed a bug in the middle of a game and added this line so that we could continue the game at the time. This should never have seen the light of the day

1870: Remove short circuit that should have never made it to commit

---

lib/engine/game/g_18_cz/step/upgrade_or_discard_train.rb

closes #4535
Could break a game, but unlikely

[18CZ] Fix Upgrading trains of bought corporation

---

lib/engine/game/g_18_cz/game.rb

closes #4568 
Could break a game

[18CZ] "Can par" not possible when a player has a debt

---

assets/app/view/welcome.rb
lib/engine/game/g_1873/meta.rb

1873: take to alpha

---

api.rb
assets/app/app.rb
assets/app/view/create_game.rb

=> `?all` is gone for create_game on all dev-envs.
[Fixes #4612]

show prealpha games on dev-env by default, hide on prod completely

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb

Fixes #4606 
Fixes #4608 
Fixes #4607

1873: add par value; prohibit selling last train; show player order

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/meta.rb
lib/engine/game/g_1822_nrs.rb
lib/engine/game/g_1822_nrs/game.rb
lib/engine/game/g_1822_nrs/meta.rb

This is the 1822 North Regional Scenario
- Inherited the 1822 base class, and added as a variant
- Changes cert limit, starting cash, map, tile and train constants.
- Changes the cost for upgrade L -> 2, first one to do it costs £80. After we entered phase 2 it costs £70.
- No special minor in bid box 1

[1822NRS] North Regional Scenario

---

assets/app/view/game/company.rb
assets/app/view/game/round/auction.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/draft.rb

Fixes #4630 
Fixes #4631 
Fixes #4641 
This touches UI:Company (handle non-numeric revenues) and UI:Round/Auction (add price to Buy button)

1873: fix switcher buy from corp; fix tiles; fix cards and button on draft

---

lib/engine/game/g_1822/game.rb

User Eludyan noticed and was bugged by this.

Fixed LNWR description in 1822

---

assets/app/view/game/history_and_undo.rb
assets/app/view/welcome.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/step/acquire.rb
lib/engine/game/g_18_co/round/presidents_choice.rb
lib/engine/round/base.rb

Reenable Restart Turn button. Fixed bugs found last time it was available.

Restart turn feature

---

lib/engine/game/g_1873/step/premium.rb

1873: allow zero premium bid

---

lib/engine/game/g_1893/game.rb

The possibility to buy/sell EVA between players are not
yet implemented.

1893: Close private EVA when first 6 train bought

---

lib/engine/game/g_1822/game.rb

- Another go at the destination token. This time a little more correct :)
fixes #4650

[1822] Destination token

---

lib/engine/game/g_18_cz/game.rb

add "Praha" group to cities on starting Praha hex

---

lib/engine/game/g_1822/game.rb

1822 Change wording for when player increases loan

---

lib/engine/game/g_1873/game.rb

1873: add more info to Info

---

assets/app/view/game/round/merger.rb
lib/engine/game/g_18_ireland/entities.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/round/merger.rb
lib/engine/game/g_18_ireland/step/merge.rb
lib/engine/game/g_18_ireland/step/merger_vote.rb

This is a first pass at implementing the mergers for 18Ireland
which using a voting system.
@todo's label what needs to be improved later.

18Ireland: Initial implementation of the merger voting

---

lib/engine/game/g_18_al/game.rb

18AL: Add detailed descriptions for historical objective

---

assets/app/view/game/entity_order.rb
assets/app/view/welcome.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/meta.rb
lib/engine/game/g_18_cz/round/draft.rb
lib/engine/game/g_18_cz/round/operating.rb
lib/engine/game/g_18_cz/round/stock.rb
lib/engine/game/g_18_cz/step/buy_corporation.rb
lib/engine/game/g_18_cz/step/buy_sell_par_shares.rb
lib/engine/game/g_18_cz/step/buy_train.rb
lib/engine/game/g_18_cz/step/draft.rb
lib/engine/game/g_18_cz/step/track.rb
lib/engine/step/buy_company.rb
lib/engine/step/tracker.rb
spec/fixtures/18CZ/2_player_hostseat.json

Adds the 2 player variant. The variant is activated automatically when 2 player are selected

[18CZ] Added 2 player variant

---

assets/app/view/game/par.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb

- When exchanging the concession of LNWR take into account in the possible shares, the share price since you only get 10% and this is you all get.
fixes #4669
This shouldnt break any of the current games since this is only a UI thing.

[1822] Possible shares of LNWR

---

lib/engine/game/g_1822_nrs/game.rb

- Added the london cities to a group.
fixes #4661
This shouldnt break any of the current games.

[1822NRS] London to London

---

lib/engine/game/g_18_ireland/entities.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/step/merge.rb
lib/engine/game/g_18_ireland/step/merger_common.rb
lib/engine/game/g_18_ireland/step/merger_vote.rb

* Market shares should vote
* Convert market shares
* Ensure legality of merge (apart from connectivity requirement)
* Make 10 shares 70% corps
* Correct train prices

18ireland merger part 2

---

lib/engine/game/g_1822/step/destination_token.rb

- Added missing method.
fixes #4716

[1822] Cant place destination token

---

lib/engine/game/g_1873/game.rb

1873: fix buying from submines

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/form.rb

Fixes #4704 
For some unknown reason, @players.include?(nil) was returning true.

Fix include?(nil) problem for mergeable_entities

---

lib/engine/game/g_18_cz/game.rb

Fixes issue where the wrong player is active

[18CZ] Fix Active Player in Multiplayer games

---

assets/app/view/game/auto.rb

Allow auto-actions to be viewed if programmed when a corp has no shares in IPO/treasury

---

lib/engine/game/g_1867/game.rb

1867: Hide the majors until they can be ipoed

---

assets/app/view/game/bid.rb
assets/app/view/game/round/stock.rb

Next step in being able to break-out some of the complexity of buy_sell_par_shares step. Allows for minor bidding to take place in the separate step.
Ran against today's db and no failures.

Allow other steps to have actions during the stock round.

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/track.rb

1873: change symbol to string; fix another delete bug

---

assets/app/view/game/game_info.rb

https://18xxgames.slack.com/archives/C012K0CNY5C/p1616571381269500?thread_ts=1616530942.263200&cid=C012K0CNY5C

game info: dim previous phases and depleted trains

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb

1873: fix pres change on floation

---

assets/app/view/game_page.rb

indicate note in game menu

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb

1873: check buy_train prices; adjust map for upgrades

---

lib/engine/game/g_18_fl/step/token.rb

18FL: Only one hotel per hex

---

lib/engine/game/g_1870/step/price_protection.rb

1870: Fix pd after price protection

---

assets/app/view/game_page.rb

no note icon if user_settings == nil

---

assets/app/view/game/route_selector.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1846/game.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_18_los_angeles/game.rb

Can easily be missed that you haven't used the private to add the bridge
fixes #2196

1817: Highlight if the player has a bridge they haven't used

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/route.rb

1873: fix QLB bonus for server

---

lib/engine/game/g_1873/game.rb

1873: fix terrain on G6

---

assets/app/view/game/part/partitions.rb
lib/engine/game/g_1862/entities.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/map.rb
lib/engine/tile.rb
spec/lib/engine/games/config_spec.rb

Improved map and also fixed issue with first edition-based map.
Needed minor changes to UI::Part::Partition and Engine::Tile

1862: map update

---

models/user.rb
routes/user.rb

validate username & email

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/dividend.rb
lib/engine/game/g_1873/step/route.rb

1873: fix QLB token cost and handle no routes for QLB

---

models/user.rb

fix account creation vs. validation (#4837)

---

lib/engine/game/g_18_ireland/entities.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares_via_bid.rb

Since 18Ireland stock round is 90% the same as 1867, separate
the reusable code and reuse.
Also add
Tile laying definitions
Company & Corporation setup
Add events
Fix timing of the merger round
Add end game triggers

18ireland stock round

---

assets/app/view/user.rb
models/user.rb

profile: option to update email address

---

assets/app/game_manager.rb

fixes #4801
middle click + right click / context menu should work – ctrl + left click still doesn’t due to https://github.com/tobymao/18xx/blob/2ee85febc97349b03293df734b23f153c3260077/assets/app/view/game_page.rb#L343

open game tabs in new tab (#4801)

---

assets/app/lib/settings.rb
assets/app/view/game/company.rb
assets/app/view/game/corporation.rb
assets/app/view/game/dividend.rb
assets/app/view/game/game_info.rb
assets/app/view/game/hex.rb
assets/app/view/game/part/borders.rb
assets/app/view/game/part/city_slot.rb
assets/app/view/game/part/multi_revenue.rb
assets/app/view/game/part/partitions.rb
assets/app/view/game/player.rb
assets/app/view/game/route_selector.rb
assets/app/view/game/spreadsheet.rb
assets/app/view/game/stock_market.rb
assets/app/view/game_card.rb
assets/app/view/game_page.rb

closes #3808
No change if player colors are off – except for a slight move to the left to center tokens horizontally.

stock market tokens: show player colors

---

lib/engine/game/g_1873/game.rb
public/logos/1873/WBE.alt.svg
public/logos/1873/WBE.svg

Harzbahn 1873: WBE color

---

assets/app/lib/settings.rb
lib/engine/game/g_1873/game.rb

Touches assets/app/lib/settings.rb
Fixes #4865 
Fixes #4867 
Before:
After:

1873: Diesel fixes; More colors

---

lib/engine/game/g_18_cz/game.rb

Adds information who controls Vaclav
closes #4805

[18CZ] Show who controls vaclav in OR

---

lib/engine/game/base.rb
lib/engine/game/g_18_ireland/entities.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/map.rb
lib/engine/game/g_18_ireland/step/special_track.rb
lib/engine/hex.rb
lib/engine/stock_market.rb

18Ireland: Implement offboard private, narrowgauge track private and PAR privates

---

lib/engine/game/g_18_cz/game.rb

Closes #4896
booleans are hard =(

[18CZ] Fixed display of vaclav operator

---

assets/app/view/game/abilities.rb

Now looks like that
@yzemaze is there something I'm missing. In the function I changed is a "truncate" of the name and I'm not sure if I break something

[18CZ] Added company size to ability button

---

lib/engine/game/g_1873/step/buy_train.rb

1873: fix machine scrapping for indie mines

---

lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb

closes #4820
Could break a game, since a player could gain a new action.

[18CZ] Fixed float track lay and ability

---

lib/engine/game/g_18_fl/game.rb

Remove hotels in Key West Hurricane (18FL)

---

lib/engine/game/g_1828/step/merger.rb

Substring check was backwards.

[1828.Games] Fix odd share player choice

---

assets/app/view/game/auto.rb
lib/engine/step/program.rb

fixes #4892
I noticed that the width on the input was a bit small making it unreadable on my machine.

Auto-actions: Validate that the until condition is set

---

assets/app/view/welcome.rb

@tobymao is it ok if we announce the 1846 league once again on the site for a couple of days?
I've seen more people than usual asking about it and wouldn't like if they missed the small-ish registration window.

Add announcement for Season 5 of the 1846 League to the page

---

assets/app/view/game_card.rb

game card: limit username width

---

lib/engine/game/g_1846/game.rb

Based on [rules errata clarified by designer](https://boardgamegeek.com/thread/2015186/article/30647909#30647909) if the steamboat private is in player hands when phase 3 is triggered and privates are removed, its assignment and markers go away (so the assigned corp no longer gets a bonus)
closes #4884
Likely requires pinning since steamboats would have been erroneously paying a bonus to assigned corps, after the markers should have been removed

[1846] remove steamboat markers if not bought in by brown

---

lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/step/special_track.rb
lib/engine/game/g_18_ireland/step/track.rb

Add a narrow 'graph' which has a list of hexes which are connected by narrow gauge.

18Ireland: Track lay restrictions for broad and narrow gauge

---

assets/app/view/game/corporation.rb

visualize dividend.kind/status of last run on corporation card

---

models/user.rb

allow usernames with non-leading whitespace

---

lib/engine/step/buy_sell_par_shares.rb

Auto-actions: Don't auto-pass when corporation is floated

---

lib/engine/game/g_1822/game.rb

fixes #4973
This shouldnt break any of the current games since its a ui change.

[1822] Tax haven should be able to buy unfloated ipo shares

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/dividend.rb

- If you have a pullman you should now be able to payout 2P and LP separately.
fixes #4956
This shouldnt break any of the current games.

[1822] Unable to payout 2P, LP separately

---

lib/engine/game/g_1822/game.rb

- If any of the phase revenue privates still in the bidbox when it closes at phase 7. Do an extra check to make sure it only to pay the bank if its money is positive.
fixes #4930
This doesnt break any of the current games. Atleast one game can continue because of the fix.

[1822] Phase revenue

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb

Fixes #4969 
Fixes #4970 
Fixes #4978 
This will require some pins.

1873: player order w/ties; x-corp diesels; price drop in insolvency

---

lib/engine/game/g_1873/step/buy_train.rb

1873: prohibit all illegal compulsory train buys

---

lib/engine/game/g_1873/game.rb

1873: sanity check on share forfeit

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb

- If your above cert limit you must sell shares if you can down to cert limit.
fixes #5034
This will probably break a few games where this rule wasnt enforced.

[1822] Certificate limit not enforced

---

lib/engine/game/g_18_ireland/game.rb
lib/engine/step/tracker.rb

which allows multiple tile upgrades for a cost

18Ireland: Implement the Dargan private

---

lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_fl/step/dividend.rb
lib/engine/game/g_18_fl/stock_market.rb

18FL Stock market enforces 5 share price cap

---

lib/engine/game/g_1822/step/dividend.rb

- Added an extra check when choosing dividend.
fixes #5029
This shouldnt break any games.

[1822] Wierd Dividend Choice

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/route.rb

1873: step::route::setup - clear round.routes

---

lib/engine/game/g_1866.rb
lib/engine/game/g_1866/entities.rb
lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/map.rb
lib/engine/game/g_1866/meta.rb

- Initial commit of map, tiles and privates for 1866.

[1866] Initial

---

lib/engine/game/g_18_fl/step/dividend.rb

Fixes 5049

---

lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/borrow_train.rb
lib/engine/game/g_1856/step/buy_sell_par_shares.rb

Implements the nationalization scenario where there is a 1-share presidency
Also fixes nationalization (it was broken by other changes at some point)
Also fixes national being able to borrow a train if it has a 4T

1856 false presidency

---

lib/engine/game/g_18_ireland/game.rb

Dargon private
Route selection if private isn't in game

Fix minor issues in 18ireland

---

lib/engine/game/g_18_cz/game.rb

Did not track the rusted trains, when no train was actually rusted.
Closes #5077
Pins at least 1 game

[18CZ] Fixed tracking of rusting information

---

assets/app/view/game/corporation.rb
lib/engine/game/g_18_fl/step/token.rb
lib/engine/token.rb

Changes to Corporation view because hex tokens don't have a city
Fixes 5003

18FL: Show hex tokens on charter

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/token.rb

Finish up tile laying and tokens.
Add building rail link to London as an alternative to track building and normal tokening.

1862: token

---

assets/app/view/game/auto.rb
lib/engine/game/g_1817/step/buy_sell_par_shares.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares.rb

Auto-actions and 1828, fix case where private closes

---

lib/engine/game/g_1822/step/destination_token.rb

1822: Automatically determine destination connectivity

---

lib/engine/game/g_1830/game.rb

1830: Tile reservations on Erie should block others placing token

---

lib/engine/game/g_1889/meta.rb
lib/engine/game/g_18_neb/meta.rb
lib/engine/game/g_18_tn/meta.rb

update some rule links

---

lib/engine/game/g_1873/game.rb

1873: move price correctly after insolvency grant

---

lib/engine/game/g_18_cz/step/sell_company_and_special_track.rb

Fixes a bug introduced with #5016
closes #5128

[18CZ] Fixes array ability bug

---

lib/engine/game/g_1822/step/minor_acquisition.rb

fixes #4489
1) Only show mergers in the UI that are legal and connected
2) Auto pass if no legal mergers are possible

1822: Only show legal mergers

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/dividend.rb
lib/engine/game/g_1862/step/redeem_share.rb

Finish most of buy_train:
- handle mandatory train buy: selling shares, refinancing, bankruptcy (latter two not completed), follow-up purchase
- share redemption

1862: redeeming and selling shares in OR

---

lib/engine/game/g_1873/step/buy_train.rb

Fixes #5130
No pins/archiving needed.

1873: make PMC pay maintenance correctly

---

assets/app/view/game/game_log.rb

add option buttons to show/hide log and chat

---

assets/app/view/game/game_log.rb
assets/app/view/game_page.rb

- camelCase
- margins reduced, flexible => fixed (vmin => rem)
- buttons moved to the right (symmetrical to undo/redo, less visual interference with description)
- description html simplified

game log toggle buttons: styling

---

lib/engine/game/g_18_ireland/game.rb

Add help messages about trains
Fix bug with unconnected narrow gauge

18Ireland: Implement Shannon private

---

lib/engine/game/g_18_ireland/step/merge.rb

18Ireland: Ensure corporations are connected via broad-gauge

---

lib/engine/game/g_18_ireland/game.rb
spec/fixtures/18Ireland/hs_ljvktyhv_38235.json

18Ireland: Fix DKRs starting cash, add log for train purchase.

---

lib/engine/game/base.rb
lib/engine/game/g_1860/game.rb

1860: Disable auto actions if the SR restarts

---

lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/round/stock.rb
lib/engine/game/g_18_ireland/step/buy_sell_par_shares.rb

Also hide majors until phase 6

18Ireland: If no minor is started in SR, close a minor

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/part/town.rb
lib/engine/tile.rb

progress on #5011, fixes #5174

make all 1868WY towns dots; fix rect towns on 1860 tiles

---

assets/app/view/tiles_page.rb

Before/after for [/tiles/1860/787+788+789](https://18xx.games/tiles/1860/787+788+789):

tiles page: fix rendering multiple specific tiles from one game

---

assets/app/view/game/part/town_dot.rb
lib/engine/part/town.rb
lib/engine/tile.rb

[1868WY] render double towns on tiles B5bb and 5bb

---

assets/app/view/game/part/town_location.rb

while working on 1868WY, found that some tiles broke the tile selector when
trying to lay a new tile, this fixes those cases

some fixes for towns with loc:center

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/stock_market.rb

[18ny] End of SR stock price movement

---

assets/app/view/welcome.rb
lib/engine/game/g_18_mag/meta.rb
spec/fixtures/18MAG/32695.json

Also adding fixture for 18Mag.

18Mag: move to production

---

lib/engine/game/g_1860/step/dividend.rb

1860: check for bankruptcy in process_dividend

---

lib/engine/game/g_18_ireland/step/buy_sell_par_shares.rb

18Ireland: fix corps floating in D

---

lib/engine/ability/tile_lay.rb
lib/engine/step/special_track.rb

18Ireland: Donegal shouldn't force connectivity to normally laid tiles

---

lib/engine/game/g_18_ireland/round/merger.rb
lib/engine/game/g_18_ireland/step/merge.rb
migrate_game.rb

Merger code ignored corporations where player didn't own shares (fixes #5196)
Merger should allow multiple rounds until all players pass (fixes #5220)
I'm gonna migrate the existing games for the 5220 fix

18Ireland merger fixes:

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_train.rb
lib/engine/game/g_1873/step/convert.rb
lib/engine/game/g_1873/step/dividend.rb

Fixes #5015 
Fixes #5148
Fixes #5214 
Pretty sure this will require archiving a few (but far from all) games.

1873: increase cert limit; skips steps after closing mine; better diesel UI

---

lib/engine/game/g_1870/step/buy_sell_par_shares.rb

1870: Any share price is a valid par price for reissuing (fixes #5060)

---

lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/meta.rb
lib/engine/game/g_1856/step/discard_train.rb

Also adds optional rules and some assorted fixes

1856 nationalization train discard

---

models/game.rb
routes/game.rb

Same as #5233, but without any UI, just the API calls.

Add API call to manually set player order

---

lib/engine/game/g_18_ireland/step/merge.rb

18Ireland: Merger connectivity isn't blocked by tokens

---

lib/engine/game/g_18_ireland/entities.rb

[18Ireland] P6 should correspond to H4

---

lib/engine/game/g_1822/step/tracker.rb
lib/engine/step/tracker.rb

- Fixed so you can upgrade and lay yellow tile if you use P21.
fixes #5241
This shouldnt break any games.

[1822] P21-HSBC is not working as described

---

lib/engine/game/base.rb
lib/engine/game/g_18_ireland/step/buy_train.rb

18ireland bugs

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/round/stock.rb
lib/engine/game/g_1862/step/buy_tokens.rb
lib/engine/game/g_1862/step/buy_train.rb
lib/engine/game/g_1862/step/charter_auction.rb
lib/engine/game/g_1862/step/forced_sales.rb
lib/engine/game/g_1862/step/merge.rb
lib/engine/game/g_1862/step/option_share.rb
lib/engine/game/g_1862/step/redeem_share.rb

Add player penalty (with possible user interaction) for missed Obligations.
Also includes several bug fixes found with a multiplayer full test game.

1862: handle missed obligations

---

assets/app/view/welcome.rb
lib/engine/game/g_1873/meta.rb

1873: take to beta

---

lib/engine/game/g_1822/entities.rb

[1822] add "can't have permanent L and 2P in same corp" to P2, P3

---

lib/engine/game/g_18_ireland/step/merge.rb

18Ireland: Disallow repeating the same merger proposal

---

lib/engine/game/g_18_cz/step/buy_train.rb

closes #5342 
when buying from another corporation the price is not relevant at that point

[18CZ] Fixed buying from other player when not enough cash for variant

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/step/charter_auction.rb
lib/engine/game/g_1862/step/dividend.rb

Also fix to dividend amount going to treasury (UI issue only).

1862: route revenue fixes; corporate share fixes

---

lib/engine/game/g_1862/game.rb

1862: fix stupid typo

---

lib/engine/game/g_18_zoo.rb
lib/engine/game/g_18_zoo/entities.rb
lib/engine/game/g_18_zoo/game.rb
lib/engine/game/g_18_zoo/map.rb
lib/engine/game/g_18_zoo/meta.rb
spec/lib/engine/games/g_18_zoo_spec.rb

related to https://github.com/tobymao/18xx/issues/5340

18ZOO - move maps from optional rules to variants

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/map.rb
lib/engine/game/g_1862/step/token.rb
lib/engine/game/g_1862/step/track.rb

Fixes #5369 
Fixes #5371 
Fixes #5372 
Fixes #5373

1862 fixes: merges, map, London highlighting

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/charter_auction.rb

Fixes #5382 
Fixes #5383 
Fixes #5370

1862: Fix refinance bug; Fix charter auction bug; Always show par

---

lib/engine/game/g_1862/game.rb

Fixes #5380 
Shouldn't require archiving as we don't post-validate revenue

1862: Fix degenerate case freight run

---

lib/engine/game/g_1862/game.rb

Fixes #5395 
Fixes #5396 
By inspection, found another issue with bankruptcy: need to restore starting permit to company.

1862: clear chartered on bankruptcy; clear graph on merger

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb

1862: remove ebuy from buy_trains; only add a marker once

---

assets/app/view/game/abilities.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/round/player_order_choices.rb
lib/engine/game/g_1840/step/buy_sell_par_shares.rb
lib/engine/game/g_1840/step/choose_player_order.rb
lib/engine/game/g_1840/step/sell_company.rb

Also Adds selling of companies.
This is applied with the choice since it needs to be possible at any time and that is a real simple solution

[1840] Added Train count per Player and Player Order choosing for first SR

---

lib/hooks.rb

Fix webhooks from discordapp.com

---

lib/engine/game/g_1862/map.rb

1862: Fix tile 797

---

lib/engine/game/g_18_ms/step/special_token.rb
lib/engine/game/g_18_ms/step/token.rb
lib/engine/game/g_18_ms/step/tokened_city_must_be_connected.rb

Added check that city is connected to current corporation.
If this breaks any game it should be that an illegal tokening
have taken place. Not possible to fix, so pin/archive the game.

18MS: Fix special token bug (fixes #5414)

---

lib/engine/game/g_1862/step/home_upgrade.rb

1862: relax track restrictions on mandatory home upgrade

---

lib/engine/game/g_18_cz/game.rb

closes #5344
does that pin any games? the one in the issue is not affected I think

[18CZ] Clear auto actions after draft

---

lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/round/acquisition.rb
lib/engine/game/g_1840/round/company.rb
lib/engine/game/g_1840/round/line.rb
lib/engine/game/g_1840/step/route.rb
lib/engine/game/g_1840/step/track_and_token.rb

Added custom end after CR 6, Multiplier for dividend of city corps and check that city corps contain home hexes in its track
also some smaller bugfixes

[1840] Added end game, Revenue multiplier for city, check for city home hexes

---

lib/engine/game/g_1862/step/merge.rb

1862: prevent merging with receivership corps

---

lib/engine/game/g_18_mex/game.rb

Corrects typo mentioned in issue #5472

Corrected spelling of Tucson

---

assets/app/view/game/player.rb
assets/app/view/game_page.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/map.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_1840/step/special_track.rb
lib/engine/game/g_1840/step/track_and_token.rb

Played a "live" game and fixed alot of symbol/string bugs
1840 would be alpha ready, but I'm on vacation next week, so we will probably start with alpha around 5th of june

[1840] Fixed alot of bugs

---

lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/discard_train.rb
lib/engine/game/g_1856/step/remove_tokens.rb
spec/fixtures/1856/hotseat003.json

This also fixes a few bugs I found while testing

1856 CGR operates immediately* if none of the forming corporations operated

---

assets/app/view/game/buy_trains.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_ireland/step/buy_train.rb
lib/engine/step/buy_train.rb
lib/engine/step/train.rb

Also, disallow selling shares then buying trains across
fixes #5187

18Ireland: Disallow selling shares if corp can afford cheapest train

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/game.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/interest_on_loans.rb

1861 67 disable acquisition warning

---

lib/engine/game/g_1862/game.rb

Fixes #5514 
No archiving needed.

1862: add check to pass on merge

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/forced_sales.rb

Fixes #5508 
No archiving needed.

1862: fix issues with enforcing obligations

---

lib/engine/game/g_1870/game.rb

1870: Allow president swap during emr (fixes #5492)

---

lib/engine/game/g_18_zoo/game.rb
spec/fixtures/18ZOO/or_power.rabbits.home_to_gray_li.json
spec/lib/engine/games/g_18_zoo_spec.rb

fixes https://github.com/tobymao/18xx/issues/5495

18ZOO: fixes 5495

---

lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/round/company.rb
lib/engine/game/g_1840/step/route.rb

City Corporations run alawys on a fixed track and start at a fixed position. 
It is really easy to find the optimal route (since we only have a possibility of 2 and no junction)

[1840] Adds city auto tracking

---

lib/engine/game/g_1856/game.rb

Fix home token timing in 1856

---

lib/engine/game/g_18_cz/game.rb

Removed hacky end game and added "default behaviour"

[18CZ] Added endgame info to last round

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_train.rb

1862: deal with trainless corp after merge

---

lib/engine/game/g_1856/meta.rb

Fix alternate destinations in 1856

---

lib/engine/game/g_1836_jr56/game.rb

Fix super port in 1836jr56

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb

Fix 1856 & 1836jr56 destination bug by making offboards terminal

---

lib/engine/game/g_1856/game.rb

Fixes 'Corporation has destinated' spam

---

lib/engine/game/g_1856/game.rb

Clarified 1856 port private text

---

lib/engine/game/g_1840/map.rb

[1840] Fixed oo tile

---

lib/engine/game/g_1856/game.rb

Remove destination ability from corporation when it destinates in 1856

---

lib/engine/game/g_1817_de/game.rb

closes #5582
I think the rounding is explicitly wanted. The $ is of course wrong

[1817DE] Added format_currency override

---

assets/app/view/game/corporation.rb

See below
Tagging @crericha as they are working on loans currently
Fixes #5568

Highlight loans in corporation view if loans > max loans (affects 1856, 18NY)

---

lib/engine/game/g_1856/game.rb

Fixes #5571
I think this doesn't archive any games because the broken actions are just that token actions were skipped and there's a default migration for that?

1856: Fix CGR losing tokens in the case of duplicate tokens in city (toronto, OO)

---

lib/engine/corporation.rb
lib/engine/game/g_18_cz/entities.rb

[18CZ] Made fraction share settable

---

lib/engine/game/g_1840/step/reassign_trains.rb

[1840] Adds error when multiple trains were assigned

---

lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/map.rb
lib/engine/game/g_1840/step/acquisition_auction.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_1840/step/dividend.rb
lib/engine/game/g_1840/step/special_track.rb
lib/engine/game/g_1840/step/track_and_token.rb
lib/engine/step/dividend.rb

closes #5587 
closes #5567
This does pretty sure break alot of games
Also adds closing of minor corporations when everyone has enough and a small map fix.
Removed revenue from non-tokened cities
Adds functionality to submit negative revenue
This could break some games, but I think not alot

[1840] Fixed Laying of orange framed tiles + fixed dividend

---

lib/engine/action/reassign_trains.rb

[1840] Fixes Reassign Train Action

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb

A
B
C
D (multi permit)
@roseundy Does this look reasonable?

1862: highlight in yellow trains a corporation doesn't have permits for at train buy

---

lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/track_and_token.rb

closes #5615
closes #5617
closes #5606
closes #5642

[1840] Fixed some bugs, typos and added some infos

---

lib/engine/game/g_1856/step/bankrupt.rb
spec/fixtures/1836jr56/hotseat003.json
spec/fixtures/1856/README.md
spec/fixtures/1856/hotseat005.json

Fix players unable to go bankrupt in 1856 on train buy

---

lib/engine/game/g_1888/step/dividend.rb

1888: fix MP argument issue in dividend_types

---

assets/app/view/welcome.rb
lib/engine/game/g_1862/meta.rb
lib/engine/game/g_1888/meta.rb

Move 1888 to alpha
Move 1862 to beta

1888 alpha; 1862 beta

---

lib/engine/game/g_1870/meta.rb

The only bug reported on the past month was a rule misread, no coding errors. 22 games have finished since

Move 1870 to production

---

lib/engine/game/g_18_zoo/entities.rb
lib/engine/game/g_18_zoo/step/home_track.rb
spec/fixtures/18ZOO/17.json
spec/fixtures/18ZOO/18.json
spec/fixtures/18ZOO/2.json
spec/fixtures/18ZOO/4.json
spec/fixtures/18ZOO/5.json
spec/fixtures/18ZOO/bankrupt.player_debt.json
spec/fixtures/18ZOO/dividend_as_president.json
spec/fixtures/18ZOO/home_tile_mandatory.json
spec/fixtures/18ZOO/or_power.moles.json
spec/fixtures/18ZOO/or_power.on_a_diet.json
spec/fixtures/18ZOO/sell_ticket_zoo_in_any_phase.json
spec/fixtures/18ZOO/sell_ticket_zoo_in_any_step.json
spec/fixtures/18ZOO/sr_power.days_off.json
spec/lib/engine/games/g_18_zoo_spec.rb

home track is mandatory
fix company price for three companies
fixes https://github.com/tobymao/18xx/issues/5494
most of the games will break

18ZOO: home track is mandatory; fix company price for three companies

---

lib/engine/game/g_1822/step/buy_sell_par_shares.rb

1822: Auto actions should ignore offshore

---

lib/engine/game/g_18_zoo/game.rb
spec/fixtures/18ZOO/or_power.hole.no_reuse.json
spec/lib/engine/games/g_18_zoo_spec.rb

fixes https://github.com/tobymao/18xx/issues/5632
breaking changes

18ZOO: fixes two bugs on Hole

---

lib/engine/game/g_1888/game.rb

1888: add export

---

assets/app/view/game/game_info.rb
lib/engine/game/base.rb
lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_1840/step/dividend.rb
lib/engine/game/g_1840/step/reassign_trains.rb
lib/engine/game/g_1840/step/selection_auction.rb

closes #5654
closes #5586 
this does pretty sure archive nearly all games since the player order is changed.
all games are playable so pinning would be nice, if you have the time for it.

[1840] More fixes

---

lib/engine/game/g_1862/map.rb
lib/engine/game/g_1862/step/buy_train.rb

1862: fix x-corp train buy; add missing hidden tile

---

lib/engine/game/g_18_zoo/game.rb
lib/engine/game/g_18_zoo/round/operating.rb
lib/engine/game/g_18_zoo/round/stock.rb
lib/engine/game/g_18_zoo/step/choose_ability_on_or.rb
lib/engine/game/g_18_zoo/step/home_track.rb

fixes https://github.com/tobymao/18xx/issues/5631
fixes https://github.com/tobymao/18xx/issues/5635
add a suggestion for HomeTrack step
no breaking changes, just cosmetic

18ZOO: fixes https://github.com/tobymao/18xx/issues/5631

---

lib/engine/game/g_1888/game.rb

1888: Fix Terracotta Army power

---

lib/engine/game/g_1856/game.rb

Remove destination icons of nationalized corporations in **56

---

lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_fl/meta.rb
lib/engine/game/g_18_fl/step/token.rb

Fixed a very minor bug I found (erroneous browser console logging) and added the 70% ownership optional rule for 2p

18fl final touches

---

assets/app/view/welcome.rb
lib/engine/game/g_1893/meta.rb

Revert "Set 1893 in Alpha"

---

lib/engine/game/g_1888/game.rb

1888: add destination to corp status

---

lib/engine/game/base.rb
lib/engine/step/tracker.rb

Reverts tobymao/18xx#5691
It turns out that this was not needed after all, so I revert back to before.

Revert "Make it possible to override orientation check"

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/meta.rb

Add optional rules for 1862.
Fixes #5669

1862: optional rules

---

lib/engine/game/g_1862/game.rb

1862: Count subsidy hexes correctly

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/step/buy_sell_par_shares.rb
lib/engine/game/g_18_ka/game.rb

Fixes #5574 and a small bug I found (it turns out in some cases you could take a loan during nationalization (it doesn't help the player at all, they're only digging a hole deeper))
I don't have time to run the full tests here but I was able to run rubocop, if the tests fail I'll be able to check in on this later today

1856 buy from cgr ipo if market violate limit

---

lib/engine/game/g_1856/game.rb
lib/engine/game/g_1856/round/operating.rb

Fix a string and post-nationalization total loans in 1856

---

lib/engine/game/g_1856/step/buy_sell_par_shares.rb

1856: Can't gain full cert if only half cert space

---

assets/app/view/game/player.rb
lib/engine/game/g_18_zoo/game.rb
lib/engine/game/g_18_zoo/step/buy_train.rb

Before the modification:
After the modification:

18ZOO: show debt inside Entity view

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_18_ka/game.rb

This is based off of what 1888 is doing with destinations

1856 Destinations use status_array

---

lib/engine/game/g_1893/game.rb

This is the actual correction.

Correct #5722

---

lib/engine/game/g_1862/game.rb

Fixes #5730 
Will require pins.

1862: fix PD after enforcing obligations

---

lib/engine/game/g_1888/entities.rb
lib/engine/game/g_1888/step/special_track.rb

Updated rule from Lonny.
Should not require archiving.

1888: Rule change - Great Wall can place non-plain track

---

lib/engine/company.rb
lib/engine/game/g_18_ireland/game.rb
validate.rb

fixes #5683: actually close corporations owned by bankrupt player
fixes #5705: ensure server and client both round up min price of company

18Ireland fixes:

---

lib/engine/game/g_1893/step/starting_package_forced_auction.rb

[1893] Fix undefined player error (fixes #5750)

---

assets/app/view/game_page.rb
assets/app/view/welcome.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/meta.rb
lib/engine/game/g_1840/step/buy_train.rb
lib/engine/game/g_1840/step/interrupting_buy_train.rb
lib/engine/game/g_1840/step/interrupting_reassign_train.rb
lib/engine/game/g_1840/step/track_and_token.rb

closes #5735 
This does break nearly all games =(

[1840] Adds lower player options (2, 3) and fixes some smaller bugs

---

lib/engine/game/g_1893/step/starting_package_forced_auction.rb

In case a player cannot afford to buy what is auctioned, skip
that player.
Also, in case player cannot afford the forced buy (all passes
all the time), try the next player. If noone can afford, let
first player (auctioner) buy it for whatever they have got.

[1893] Improved passing in forced auction (fixes #5746)

---

lib/engine/game/g_1893/step/buy_sell_par_shares.rb

Extra checks added to ensure no actions are possible when player passed in SR1.

[1893] Previous commit did not solve all cases

---

assets/app/view/welcome.rb
lib/engine/game/g_18_cz/meta.rb

[18cz] Moved to prod

---

lib/engine/game/g_18_ireland/game.rb

18Ireland: Show price of xH' trains

---

lib/engine/game/g_18_zoo/game.rb
spec/fixtures/18ZOO/5774.json

could break some alpha games
please archive_alpha_games

18ZOO: fix https://github.com/tobymao/18xx/issues/5774

---

assets/app/view/game/part/track.rb

Dechunk track

---

lib/engine/game/g_18_ka/game.rb
lib/engine/game/g_18_ka/step/route.rb
spec/fixtures/1856/hotseat006.json

18ka pullman

---

assets/app/view/game/buy_sell_shares.rb
lib/engine/game/g_1856/step/buy_sell_par_shares.rb

Fix being unable to buy a 5% share of CGR to reach cert limit in 1856

---

lib/engine/game/g_1893/game.rb

This might break some alpha games. If so archive or delete those that
break.

[1893] Fix two bugs with variant tiles (fixes #5819, #5834)

---

lib/engine/game/g_1856/game.rb

Fix typo in text of GLSC private in 1856

---

lib/engine/game/g_1860/step/buy_train.rb

1860: remove valid route check from must_buy

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/track.rb

Fixes #5849 
Fixes #5855 
Fixes #5856

1873: add color check for non-concession laying concession tile

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/round/operating.rb
lib/engine/game/g_18_va/round/stock.rb
lib/engine/game/g_18_va/step/assign.rb
lib/engine/game/g_18_va/step/buy_sell_par_shares.rb
lib/engine/game/g_18_va/step/buy_train.rb
lib/engine/game/g_18_va/step/convert.rb
lib/engine/game/g_18_va/step/dividend.rb
lib/engine/game/g_18_va/step/special_token.rb
lib/engine/game/g_18_va/step/token.rb

This is a big chunk of logic because this is the rounds and steps copied from 18FL after everything unneeded was removed and the needed things were tweaked or fixed to make the game run or more rules accurate
~~The change in `lib/engine/game/base.rb` is an alternative to https://github.com/tobymao/18xx/pull/5827 that doesn't live in view code~~ PR 5868 made that unnecessary so it's removed now

18VA first pass at game logic

---

lib/engine/game/g_1856/step/discard_train.rb

1856: CGR discards 4Ts, not scraps

---

assets/app/view/welcome.rb
lib/engine/game/g_1856/meta.rb

1856 has been on the site for a month now and it's been smooth. The rules are clarified and complete and I got the visual enhancements in to aid players while playing

Put 1856 into beta

---

lib/engine/game/g_1873/step/dividend.rb

Fixes #5876 
This seemingly minor change (+/- 1M to players/corps) killed two of my hotseat tests.

1873: rounding issue on half dividend withholds

---

lib/engine/game/g_1840/step/track_and_token.rb

[1840] Fixes city track problem

---

lib/engine/game/g_1840/step/buy_sell_par_shares.rb

[1840] Fixed selling city shares

---

lib/engine/game/g_1830_plus.rb
lib/engine/game/g_1830_plus/game.rb
lib/engine/game/g_1830_plus/meta.rb

The map otherwise is implemented

1830 plus prealpha - doesn't implement PRR home properly

---

lib/engine/game/g_1846/game.rb

[1846] remove_from_group! - don't mutate the passed in group

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/meta.rb

* Say `Treasury` not `IPO` in UI for corporation
* provide URL for rules in info tab

18VA: Say treasury not IPO

---

lib/engine/game/g_1840/step/acquisition_auction.rb
lib/engine/game/g_1840/step/buy_train.rb

closes #5839 
closes #5917 
I think the auction order change could archive some games, but I'm not sure, since the tests all still pass and the games I Checked also pass

[1840] Fixes forced buy and auction order

---

lib/engine/game/g_18_cz/game.rb

[18CZ] Fixes rusting bug

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/step/bankrupt.rb

Implements 18VA's 1846-ish chain-reaction bankruptcy

18VA bankruptcy

---

lib/engine/game/g_1836_jr56/step/buy_train.rb

This might break some games, is there a way for me to verify this?

1836jr56: Prevent buying a 3 then a 3'

---

lib/engine/game/g_1828/step/merger.rb
lib/engine/game/g_1828/system.rb

Provided that one of the merging corporations hasn't yet floated. Fixes #5911

[1828.Games] Systems get 10x share price in their treasury

---

lib/engine/game/g_1840/step/route.rb

[1840] Fix auto city track

---

lib/engine/game/g_18_va/step/waterfall_auction.rb

[18VA] minimum bid for a private is face value

---

lib/engine/game/g_1856/game.rb

This will require pinning some, but not all games
Fixes #5955

Fix 1856 waterloon & saugeen creating tokens

---

lib/engine/game/g_1817/step/buy_sell_par_shares.rb

[1817] apply sort and uniq to purchase options

---

lib/engine/game/g_18_va/game.rb

Apply freight bonus in 18VA to port CITY as well

---

lib/engine/game/g_1873/step/dividend.rb
spec/fixtures/1873/hs_gwlftpex_33770.json

1873: fix another half-dividend rounding issue

---

assets/app/view/game/buy_power.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/step/bankrupt.rb
lib/engine/game/g_18_carolinas/step/buy_power.rb
lib/engine/game/g_18_carolinas/step/dividend.rb
lib/engine/game/g_18_carolinas/step/route.rb
lib/engine/game/g_18_carolinas/step/token.rb
lib/engine/game/g_18_carolinas/step/track.rb

Tested/fixed emergency fund raising
Personal and corporate bankruptcy
Receivership rules - including automatic power buy
End of game rules
18Carolinas should be feature complete at this point.

18Carolinas: bankruptcy and receivership

---

lib/engine/game/g_1862/game.rb

Fixes #6004 
UI only, no pins required.

1862: fix display of PD in Parliament rounds

---

lib/engine/game/g_1867/game.rb

fixes #5997
Needs pins for 61/67

1861/1867: Nationalization should repay loans if exact amount is left

---

lib/engine/game/g_18_va/game.rb

[18VA] fix philly typo

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/step/token.rb

Fixes #6005 
It may kill off some alpha games unfortunately

18VA: Allow token company to use power if it cannot normally lay a token

---

lib/engine/game/g_18_va/step/dividend.rb

Fixes the confusion behind #6021

Fix 18VA subsidy logging

---

lib/engine/game/g_18_rhl/game.rb

- Implement privates
- Implement capitalization
- Implement tile upgrades
- Added ability descriptions to CCE, KKK, RhE corporations
Some map corrections.
Note: The Aachen link bonus is not yet implemented.

[18Rhl] Add more functionality

---

lib/engine/game/base.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/part/path.rb
lib/engine/route.rb

18Ireland: Restrict trains to only running on broad game

---

lib/engine/step/buy_sell_par_shares_via_bid.rb
migrate_game.rb
spec/fixtures/18Ireland/39547.json

fixes #5808
(18Ireland is still alpha, but probably good enough to soft-beta/pin)

18Ireland/61/67: Skip player for bidding if they are at cert limit

---

lib/engine/game/g_18_va/game.rb

This most definitely will archive games :(

Fix 3Ts lasting longer in 18VA than it should

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/meta.rb

There are 30 privates in the game so I'm going to do a few big batches then do the last few as smaller individual PRs as they get more and more esoteric

18 usa privates batch1

---

assets/app/view/game/player.rb
assets/app/view/game/spreadsheet.rb
assets/app/view/share_calculation.rb

Add Shares to the player card based off the spreadsheet calculation

---

assets/app/view/game/buy_power.rb
assets/app/view/game/emergency_money.rb
lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/map.rb
lib/engine/game/g_18_carolinas/meta.rb
lib/engine/game/g_18_carolinas/step/buy_power.rb
lib/engine/game/g_18_carolinas/step/track.rb

- View::EmergencyMoney - add ability to sell private companies to the bank
- View::BuyPower - fix must_buy_train to be must_buy_power

18Carolinas: bug fixes; EMR sales of companies

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/round/stock.rb

1. Next SR order is based on cash (and LOLA if more than one share)
2. 100% ownership allowed in corporation
3. Corporations floated in brown (or later) is 100% cap.
Also, unsold IPO shares are moved to Market.
4. Corporations floated before brown, gets their market price
upped one step at the end of the SR (it floated)
5. IPO and Market price are the same

[18Rhl] Some special handling for stocks

---

lib/engine/game/g_18_rhl/game.rb

Some bug fixes.
Towns cannot be start/stop of a route.

[18Rhl] Minor fixes

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb

Fix tile manifest in 1856 showing tiles with tokens on them

---

lib/engine/game/g_18_rhl/game.rb

The player order in next SR is that the player with most cash is
priority dealer, and then it is seating order.
If several players share the most cash, then it is normal LOLA.

[18Rhl] Correct player order

---

lib/engine/game/g_18_rhl/game.rb

When Duisburg, Düsseldorf and Köln are yellow hexes, they have three
separate city slots. Two of these are on one side of Rhine, and the
third is on the other. It is not allowed to include the two city
slots on one side of Rhine in the same route (as it is the same city).
Having a route from one side of Rhine to the other side of Rhine
and visiting the different sides of the same hex, is allowed though.
When the Rhine Metropolis hex is upgraded to green (or later) the
hex will be a normal "one city - three slots" and then the normal
game logic will stop the hex being visited twice in one route.
Here is how it looks like in the GUI (when trying to visit Köln twice):

[18Rhl] Forbid route to same Rhine Metropolis city

---

lib/engine/game/g_18_rhl/game.rb

When Duisburg, Düsseldorf and Köln are yellow hexes, they have three
separate city slots. Two of these are on one side of Rhine, and the
third is on the other. It is not allowed to include the two city
slots on one side of Rhine in the same route (as it is the same city).
Having a route from one side of Rhine to the other side of Rhine
and visiting the different sides of the same hex, is allowed though.
When the Rhine Metropolis hex is upgraded to green (or later) the
hex will be a normal "one city - three slots" and then the normal
game logic will stop the hex being visited twice in one route.
This is a 2nd attempt to implement this feature - the 1st attempt
was reverted, as it need to be reviewed, and the 1st attempt also
did not work as it made routes through green Rhine metropolis …

[18Rhl] Disallow double visit to Rhine Metropolis

---

lib/engine/game/g_18_va/game.rb
lib/engine/game/g_18_va/step/buy_train.rb
lib/engine/game/g_18_va/step/special_buy_train.rb

18VA: Don't allow using the train private to buy two depot trains

---

lib/engine/depot.rb
lib/engine/step/train.rb
lib/engine/train.rb

If an entity has a train_discount ability, factor that in for train min_price

---

lib/engine/game/g_1888/game.rb

Typo for ZDR bonus
Setting EBUY_OTHER_VALUE false

1888: bug fixes

---

lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_mag/meta.rb
lib/engine/game/g_18_mag/step/dividend.rb

Add option for "all or nothing" corporate dividends.

18Mag: add option at request of Lonny

---

lib/engine/game/g_1862/game.rb

Fixes #6038 
Fixes #6047 
This will require some games to be pinned.

1862: cert change at LNER formation; freight-train UI fix

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1873/step/track.rb

Fixes #6050 
Fixes #6063 
This _shouldn't_ require pins.

1873: potential_tiles fix; liquidity fix

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/rhe_bonus_check.rb
spec/fixtures/18Rhl/reference_game.json

[18Rhl] Implement RhE bonus when link exists Aachen-Duren-Cologne

---

lib/engine/game/g_18_va/game.rb

Fix B&O bankruptcy behavior in 18VA

---

lib/engine/game/g_1860/step/buy_sell_par_shares_companies.rb

1860: fix issue with pass during special case

---

lib/engine/game/g_18_carolinas/map.rb

Scott wants to move Knoxville.
Fixes #6114 
If this gets merged and deployed fast enough, there shouldn't be a need for any archives.

18Carolinas: map tweak from Scott; fix spurs

---

lib/engine/game/g_1822/entities.rb

[1822+] fix minor name

---

lib/engine/game/g_1846/entities.rb
lib/engine/game/g_1846/game.rb

[1846] cleanup reservation descriptions in phase IV

---

lib/engine/game/g_18_zoo/step/assign.rb

Do not break any game in the tournament

Fixes https://github.com/tobymao/18xx/issues/6118

---

lib/engine/game/g_1846/entities.rb

Implements something that @michaeljb added re: https://github.com/tobymao/18xx/issues/2021, which I forgot to merge into my commit

[1846] clarify IC free tiles

---

lib/engine/game/g_18_va/game.rb

18VA: Offmap cities are cities; they are doubled by 4Ds if untokened

---

lib/engine/game/g_18_rhl/game.rb

1. Correct spelling error for Eastern Ruhr hexes
2. Improve presentation of steel icon and city in Siegerland (J15)

[1893] Some map corrections

---

lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_sj/step/buy_company.rb
lib/engine/game/g_18_sj/step/buy_train.rb
lib/engine/game/g_18_sj/step/dividend.rb
lib/engine/game/g_18_sj/step/token.rb
spec/fixtures/18SJ/hs_aaqpquno_1627552247.json

A serious bug in 18SJ. If this correction breaks any games those games are not salvable, and will have to be deleted.

[18SJ] Correct bot check (fixes #6137)

---

assets/app/view/welcome.rb
lib/engine/game/g_1830/game.rb
lib/engine/game/g_1830/meta.rb

Adds 2-player functionality described in Lookout rules (no special rules needed).

1830 2player

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/assign.rb
lib/engine/game/g_18_usa/step/special_track.rb
lib/engine/game/g_18_usa/step/track.rb
lib/engine/part/city.rb
lib/engine/step/reduce_tokens.rb
lib/engine/token.rb
public/logos/minus_ten.svg

Company Town
Regional Headquarters
Rural Junction

18usa privates batch3

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/bankrupt.rb
lib/engine/game/g_18_rhl/step/buy_train.rb
lib/engine/game/g_18_rhl/step/dividend.rb
spec/fixtures/18Rhl/reference_game_bankruptcy.json

Add reference game that includes no variants, but a bankruptcy.

[18Rhl] Handle receivership after bankruptcy

---

lib/engine/game/g_1840/entities.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1840/step/track_and_token.rb

closes #6135 
closes #6123
closes #6102 
the removing of the reservation could lead to some broken games.

1840  fixed some smaller issues

---

lib/engine/game/g_1862/game.rb

1862: Correct freight calculations with offboards

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/round/operating.rb
lib/engine/game/g_18_usa/step/buy_train.rb
lib/engine/game/g_18_usa/step/reduce_tokens.rb
lib/engine/game/g_18_usa/step/route.rb
lib/engine/game/g_18_usa/step/token.rb
lib/engine/game/g_18_usa/step/track.rb
lib/engine/graph.rb

Adds the two train running shenanigans privates to the game.
This will make it 18/30 done
This also adds the pullman train and the ability to add it to a train as an ability (like the two new privates)

18usa privates batch4

---

lib/engine/game/g_18_cz/game.rb

18cz fix tile_manifest upgrade

---

lib/engine/game/g_18_carolinas/game.rb

18Carolinas: fix interaction between conversions and double-sided tiles

---

lib/engine/distance_graph.rb
lib/engine/game/g_1860/game.rb
lib/engine/game/g_1860/step/track.rb
lib/engine/game/g_1860/step/tracker.rb

Move game-specific distance_graph out of 1860 and into its own class.

1860: Make DistanceGraph class

---

lib/engine/game/g_1860/game.rb

In a continuing effort to remove custom code from 1860, this removes the last custom node walk from 1860. I had used a custom walk so I could use a custom block? method for cities that were visited so that "flipped" tokens were ignored for running routes. I have replaced this custom code with a standard node select/walk and change flipped tokens to neutral token before the walk, and change them back after the walk.

1860: remove custom node walk

---

lib/engine/game/g_1893/game.rb

Let 1893 implement move share method.

[1893] Correct call to private method (fixes #6185)

---

lib/engine/game/g_18_fl/game.rb
lib/engine/game/g_18_fl/step/buy_sell_par_shares.rb
lib/engine/game/g_18_fl/step/dividend.rb
lib/engine/game/g_18_fl/stock_market.rb

Same idea as https://github.com/tobymao/18xx/pull/6183

[18FL] medium, large corps => 5share, 10share

---

lib/engine/game/g_1860/game.rb

1860: fix typo on tokens

---

assets/app/view/create_game.rb
assets/app/view/game_page.rb
lib/engine/config/tile.rb
lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb
lib/engine/option_error.rb

* split map and entities out from game.rb
* add options for all Unit combinations
* add checking for inconsistent options and raise OptionError
* add Unit 1 and Unit 2 maps, tiles, and entities.
* combine tiles based on options
* combine maps based on options
* combine entities based on options

1825: unit 1 & 2 maps, entities; option parsing

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1825/step/buy_sell_par_shares_companies.rb
lib/engine/step/buy_sell_par_shares_companies.rb

Changes for stock rounds
Option-based configuration of trains and phases
Common file change: lib/engine/step/buy_sell_par_shares_companies.rb - change to use SELL_BUY_ORDER

1825: ISR and SR; phase and train configuration

---

lib/engine/game/g_18_rhl/game.rb
lib/engine/game/g_18_rhl/step/lay_tile_checks.rb

All privates closed when first 5 train is bought.

[18Rhl] Correct when privates closed

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb

Fixes #6234 and another bug that was never filed.
It's possible the the cert limit fix may require a very few games to be pinned

1862: Fix freight revenue calc; LNER cert limit bug

---

lib/engine/game/g_18_carolinas/game.rb
lib/engine/game/g_18_carolinas/map.rb

Fixes #6231 
UI change only. No archiving needed.

18Carolinas: have tile manifest show future upgrades

---

lib/engine/game/g_18_ireland/entities.rb

18Ireland fix typo

---

lib/engine/game/g_18_rhl/game.rb

Previously the player was allowed to do the route. But this means
that a player might not notice that a previously OK route now
pays 0 for the off-board hex. It could be argued that you want to
do the route anyway (to collect towns in between) but in almost
all cases you would prefer to re-route. So the choice was to go
for the normal case, and not cater for the rare special case.

[18Rhl] Give error for Route to/from out-tokened off-board hex

---

lib/engine/game/g_1840/map.rb
lib/engine/game/g_1840/meta.rb

closes #6226 
and game is now really in beta...don't know why the meta was not changed 🤷

1840 - Added town

---

lib/engine/game/g_1860/game.rb
lib/engine/game/g_1860/round/operating.rb
lib/engine/game/g_1860/step/discard_train.rb

Fixes #6267 
There is a small chance this will require pins on some games.

1860: fix train discard step

---

assets/app/view/game/history_controls.rb
assets/app/view/game_page.rb
lib/engine/game/base.rb

Store all game actions, even future ones, in the game class. Add helper methods to determine previous and next game actions. Add a helper method to process actions from the current state to the specified action.

Skip undone actions when navigating history and don't reload entire game when navigating forward

---

lib/engine/game/g_1862/step/buy_train.rb

Fixes #6284 
Fixes #6301 
This may require pins.

1862: fix ebuy bugs

---

assets/app/view/game_card.rb

We often want to share games that others have created. This change makes it possible to share games that you have joined. 
Not sure if this approach is better than just making it possible to share all listed games...

Make it easier share games you join

---

lib/engine/game/g_1873/game.rb

Fixes #6317 
This may require some pins.

1873: enforce bids are multiples of 10

---

lib/engine/game/g_1860/game.rb
lib/engine/game/g_1860/step/buy_sell_par_shares_companies.rb

Fixes #5055 
Fixes #6294 
Fixes #6314 
Fixes #6315 
This will require pinning some games.

1860: four fixes

---

lib/engine/game/g_1849_boot/game.rb
lib/engine/game/g_1849_boot/meta.rb

1849:K2S Remove 2x trains from 4p game, remove 3p option

---

assets/app/view/game_page.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/step/buy_train.rb
lib/engine/game/g_1825/step/dividend.rb
lib/engine/game/g_1825/step/route.rb
lib/engine/game/g_1825/step/track_and_token.rb
lib/engine/step/route.rb

Various fixes for issues found during playthrough
I anticipate this being the last PR before moving to Alpha.
Fixes #6332 
Common code edits: 
* UI::GamePage (for above bug)
* Step::Route - use game method train_owner rather than train.owner attribute

1825: playthrough bug fixes

---

lib/engine/game/g_1825/step/track_and_token.rb

Fixes #6339 
Any game that does this will be archived.

1825: fix inappropriate loan for track lay

---

assets/app/view/welcome.rb
lib/engine/game/g_18_va/meta.rb

18VA's been stable while I've been away during a move so I'm comfortable with promoting 18VA from alpha to beta

Move 18VA to beta

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb

Fixes #6349 
Fixes #6352 
Fixes #6353 
This shouldn't invalidate games.

1825: fix OO tiles, 3 rusting, another constant mutation

---

lib/engine/game/g_1825/map.rb

[1825] Add BGM label to Glasgow

---

lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb

Fixes #6359 
Fixes #6361 
May require archiving.

1825: fix tile upgrade bugs

---

lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/step/buy_sell_par_shares_companies.rb
lib/engine/game/g_1825/step/track_and_token.rb

Fixes #6368 
Fixes #6369 
Fixes #6386 
Archiving should not be needed.

1825: More bug fixes

---

lib/engine/game/g_1846/game.rb

[1846] Also output location name when removing companies during setup

---

lib/engine/game/g_1825/map.rb

1825: Define tile 37 correctly

---

lib/engine/game/g_18_carolinas/game.rb

Fixes #6360 
No archiving/pinning required.

18Carolinas: show bankrupt option

---

lib/engine/game/g_1873/game.rb

Fixes #6370 
No pins required.

1873: remove L on MHE market

---

lib/engine/game/g_1870/game.rb

This adds a K label to Kansas City, and L to St. Louis
closes #6400

[1870] add K and L labels to cities

---

assets/app/lib/params.rb
assets/app/view/game_row.rb
assets/app/view/game_row_filters.rb
assets/app/view/home.rb
models/game.rb

This addresses part of issue #782, and can be extended to support more filters as needed.
Screenshot:

Add UI to filter games by title to home page

---

lib/engine/game/g_18_ny/ability/connection_bonus.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/map.rb
lib/engine/game/g_18_ny/step/route.rb
lib/engine/game/g_18_ny/step/token.rb

- Implement connection bonus tokens
- Place coal tokens with assignment
- Implement hex trains
- Implement tokens ($20 * shortest legal path from another station)

[18NY] More operation round functionality

---

lib/engine/game/g_1822/meta.rb
lib/engine/game/g_1822_mrs/meta.rb
lib/engine/game/g_1822_nrs/meta.rb

[1822] Production

---

assets/app/view/game/actionable.rb
lib/engine/action/claim_hex_token.rb
lib/engine/game/g_18_ny/ability/coal_revenue.rb
lib/engine/game/g_18_ny/entities.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/check_coal_connection.rb
lib/engine/game/g_18_ny/step/dividend.rb
lib/engine/game/g_18_ny/step/route.rb
lib/engine/round/base.rb

- Claim coal tokens (auto actions)
- Enhance auto actions to use the active step after processing the last action, not before processing
- Minor fix-ups to connection bonuses
- Implement dividend step

[18NY] Coal tokens and a bit more

---

lib/engine/round/base.rb

So that's what missing the blocking? call was for...
I reverted my changes to base round for now and will figure out what's up with company assignment later.

Fix for company assignments to the map to work again.

---

lib/engine/game/g_1856/game.rb
spec/fixtures/1856/51745.json
spec/fixtures/1856/README.md

1856: Fix CGR paying for kitchener token when it shouldn't need to

---

lib/engine/game/g_18_tokaido/step/buy_company.rb

Fix for token price not being set when buying in the private after all tokens have already been placed.

[18 Tokaido] fix bug with stationmaster tama

---

lib/engine/distance_graph.rb
lib/engine/game/g_1825/map.rb
lib/engine/step/tracker.rb

Fixes #6468 
Fixes #6501 
Fixes #6504

1825: fix stale UI hexes; remove over aggressive distance graph pruning; fix 114 upgrade

---

lib/engine/game/g_18_ireland/step/buy_sell_par_shares.rb

Adds / modifies the first two lines
closes #6523

[18Ireland] add log msg when floating minor company

---

lib/engine/game/base.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/meta.rb
lib/engine/game/g_18_ny/round/capitalization.rb
lib/engine/game/g_18_ny/step/buy_sell_par_shares.rb
lib/engine/game/g_18_ny/step/buy_train.rb
lib/engine/game/g_18_ny/step/issue_shares.rb
lib/engine/game/g_18_ny/step/merge_with_nyc.rb
lib/engine/share_pool.rb

Ran against the whole db of games with strict: true. No new failures were seen.

[18NY] Implement capitalization round and bug fixes

---

assets/app/view/welcome.rb
lib/engine/game/g_18_ny/entities.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/meta.rb
lib/engine/game/g_18_ny/step/special_token.rb
lib/engine/game/g_18_ny/step/stagecoach_exchange.rb

[18NY] Stagecoach token exchange rework and transition to alpha

---

lib/engine/game/g_18_texas/game.rb

I am trying to make this update via a website code change -- apologies if this fails and I will remove it and redo it later.

18Texas - Rule change, always allow two yellow tiles

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/loan_repayment.rb

@tobymao There will be a number of broken games that need to be deleted.

[18NY] bug fixes

---

lib/engine/game/g_1870/game.rb

[1870] make port icons sticky

---

lib/engine/game/g_1830/meta.rb

[1830] add wiki link

---

lib/engine/game/g_1830/meta.rb

Noticed this while working on another issue

[1830] fix typo in variant desc

---

lib/engine/step/buy_sell_par_shares.rb

Fixes #6169
This definitely seems like it has potential to break games.

Disable auto actions after company share redemption.

---

lib/engine/game/g_1822/entities.rb
lib/engine/game/g_1822_mx/entities.rb

[1822] copyedit for concessions

---

lib/engine/game/g_18_fl/meta.rb

[18FL] add publisher

---

lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/step/lease_train.rb
lib/engine/game/g_1825/step/route.rb
lib/engine/game/g_1825/step/track_and_token.rb

Fixes #6518 
Fixes #6519 
Fixes #6629 
Leasing trains now allowed in track/token step. Leasing now allows choice of available trains.

1825: 4+4 fix, leasing fixes

---

lib/engine/game/g_18_texas/entities.rb
lib/engine/game/g_18_texas/game.rb

18Texas: remove use of on_phase in abilities

---

spec/fixtures/18Texas/hs_hqrmcntr_1641188459.json

This fixture uses all the 18Texas tile laying private company special powers.

Add 18Texas fixture 

---

lib/engine/game/g_18_christmas_eve.rb
lib/engine/game/g_18_christmas_eve/game.rb
lib/engine/game/g_18_christmas_eve/meta.rb
lib/engine/game/g_18_christmas_eve/step/track.rb
lib/engine/game/g_18_christmas_eve/step/tracker.rb
lib/engine/tile.rb
nogtest.json

Implementation includes:
- Map.
- Code to copy frames to new tiles. Frames are used to show rooms - happy for feedback if there was a more preferred way.
- Implementation of new private powers.
Implementation is presently missing the 'gift' rules.

Partial implementation of 18ChristmasEve

---

assets/app/view/welcome.rb
lib/engine/game/g_18_new_england/meta.rb
lib/engine/game/g_18_new_england_north/meta.rb

Move 18NewEngland and 18NewEngland 2 to alpha

18NewEngland: to alpha

---

lib/engine/game/g_18_new_england/map.rb

18NewEngland - Fix tiles

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/step/post_merger_shares.rb

18NewEngland: capitalize on post-merger share purchase; fix Quincy-like runs

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/step/buy_sell_par_shares.rb
lib/engine/game/g_18_new_england/step/issue_shares.rb
lib/engine/game/g_18_new_england/step/post_merger_shares.rb

Fixes #6726 
Fixes display of IPO price
Changes sort of corporations in stock round

18NewEngland: fix display/pricing of IPO shares; fix entity ordering

---

lib/engine/game/g_1825/game.rb

1825: move optional trains to end of train list

---

spec/fixtures/18NewEngland/67847.json
spec/fixtures/18Texas/65394.json

18NewEngland/18Texas - add fixtures

---

lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb

1825: tile 200 fix

---

lib/engine/game/g_18_ms/step/token.rb
spec/fixtures/18MS/67889.json

Also adds relevant fixture from https://18xx.games/game/67889
closes #6743

[18MS] route bonus should not be given on/after phase 6

---

lib/engine/game/g_18_new_england/step/buy_train.rb

18NewEngland: fix selling shares on EMR

---

lib/engine/game/g_1825/step/track_and_token.rb

Fixes #6737 
This will break some existing 1825 games. Please pin these instead of archiving them.

1825: lays on green/brown hexes are upgrades

---

lib/engine/game/g_18_new_england/step/bankrupt.rb

Fixes typo found while looking at #6756

18NewEngland: fix typo on declaring bankruptcy

---

lib/engine/game/g_1825/step/buy_train.rb

1825 receivership purchase

---

assets/app/view/welcome.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1873/meta.rb
lib/engine/game/g_1888/meta.rb

Take Harzbahn and 1888 to production
Take 1825 to beta

1873, 1888 to production; 1825 to beta

---

lib/engine/game/g_18_new_england/step/redeem_shares.rb

18NewEngland: prevent redeeming after issuing

---

assets/app/view/game/choose.rb
assets/app/view/game/round/stock.rb
lib/engine/game/g_18_christmas_eve/game.rb
lib/engine/game/g_18_christmas_eve/meta.rb
lib/engine/game/g_18_christmas_eve/step/buy_sell_par_gift_shares.rb

I'm keen to know if there's another UI way I should have addressed the gift share buttons - they show all the time (as opposed to when you have selected that share). Happy for feedback. I also wasn't sure if the gift should have been something I added in 'action' rather than addressing the logic in the step.
I wasn't certain if there was anything else you needed before being comfortable going into alpha. I've run through a couple of games from start to end. I have a full JSON of one of those - but I didn't include as a spec (yet) as the game is still a prototype which will likely have future (hopefully minor) map/rule changes that will break those tests.

18ChristmasEve Gift Shares and move to alpha

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/step/route.rb

18NewEngland: make express multiplier more obvious

---

lib/engine/game/g_18_christmas_eve/meta.rb

Misunderstood the purpose, and the game wasn't being shown in the
list in prod (unlike in dev)

18ChEv Remove 'Variant Of'

---

lib/engine/game/g_18_new_england/game.rb

18NewEngland: Prohibit pres contribution to crossbuy of train

---

lib/engine/game/g_18_new_england/step/issue_shares.rb
lib/engine/game/g_18_new_england/step/redeem_shares.rb

18NewEngland: treat all issues as a single block

---

lib/engine/game/g_18_new_england/game.rb

18NewEngland: fix sort of majors/minors on entities page

---

lib/engine/game/g_18_new_england/step/merge.rb

Fixes #6793 
This will make games fail. If it's a lot, probably should pin.

18NewEngland: fix mergers when minors are "out of order"

---

lib/engine/game/base.rb
lib/engine/game/g_18_ny/game.rb

If you can deploy tonight, that would be appreciated. Right now, no one can start a second edition game.

[18NY] More Second Edition changes and bug fix

---

assets/app/view/chat.rb

Linkify game references in chat.

---

assets/app/view/game/part/city.rb
lib/engine/game/g_21_moon.rb
lib/engine/game/g_21_moon/entities.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/map.rb
lib/engine/game/g_21_moon/meta.rb

Initial PR for 21Moon
Common code change:
* Support 7-slot cities (UI::Part/City)

21Moon: structure, map, tiles, entities, trains phases + support for 7 slot cities

---

lib/engine/game/g_18_new_england/step/merge.rb

Fixes #6811 
This could potentially break games. @tobymao Can you pin these?

18NewEngland: allow merge with colocated minor

---

lib/engine/game/g_18_fl/game.rb

18FL: Phase3 new corps must be 5 share, not 10

---

lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/map.rb
lib/engine/game/g_1866/step/buy_sell_par_shares.rb
lib/engine/game/g_1866/step/discard_train.rb
lib/engine/game/g_1866/step/track.rb

- E trains can run on the same track as normal trains
- Dont show obsolete trains when you are forced to discard
- Ferries becomes available in green and brown phase
- Upgrade London and Paris, and get the offboard in london to work
- Stock bound should change value when phase is changing
- Phase 3-4 4T / 1U, phase 5-6 4T / 2U, phase 8 4T / 3U, phase 10 4T / 4U

[1866] Ferries

---

lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb

More robust fix for #6699 
No pins/archives required.

1825: robust skipping of tile 200

---

assets/app/view/chat.rb
assets/app/view/game/game_log.rb
assets/app/view/log.rb

resolves: #3469
Adds a copy transcript button which copies game log to clipboard.

add copy transcript button

---

lib/engine/game/g_1822/map.rb

[1822] Prevent London from being hit multiple times

---

assets/app/view/game/game_log.rb

fix log message formatting

---

lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/step/buy_train.rb
lib/engine/game/g_1866/step/loan_interest_payment.rb
lib/engine/game/g_1866/step/loan_repayment.rb
lib/engine/game/g_1866/step/track.rb
lib/engine/game/g_1866/stock_market.rb

- Fixed C and B tiles
- Loans, both personal and corporation
- If a company holds any loans it cannot sell trains for less than face value and cannot buy trains for more than face value.
- Some more code cleanup
- Some rules changes

[1866] Loans

---

assets/app/view/game/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/round/operating.rb
lib/engine/game/g_1866/round/stock.rb
lib/engine/game/g_1866/step/buy_sell_par_shares.rb
lib/engine/game/g_1866/step/buy_train.rb
lib/engine/game/g_1866/step/issue_shares.rb
lib/engine/game/g_1866/step/single_item_auction.rb
lib/engine/game/g_1866/step/stock_turn_token.rb
lib/engine/game/g_1866/stock_market.rb

- Auction take the the first randomized private and auction out. Hide rest.
- If passed in ISR, you are out from the ISR
- Selling shares, goes left if president otherwise it goes down
- Issue and redeem shares
- Payback player loans.
- Engine::Game, added a new method "corporation_show_loans?". 
- View::Game::Corporation. Make a call to corporation_show_loans? to see if we want to show the loans.

[1866] ISR

---

assets/app/view/game/route_selector.rb
lib/engine/auto_router.rb

display message if auto-router times out

---

lib/engine/game/g_1866/entities.rb
lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/step/buy_infrastructure.rb
lib/engine/game/g_1866/step/buy_sell_par_shares.rb
lib/engine/game/g_1866/step/buy_train.rb
lib/engine/game/g_1866/step/discard_train.rb
lib/engine/game/g_1866/step/dividend.rb
lib/engine/game/g_1866/step/stock_turn_token.rb

- Austro-Hungary, Lombardy-Venetia and formation of Italy
- If company changes president, check tokens and operating rights. Take back all tokens the company doesnt hade rights for.
- Sell stock token. If any left they will become premium cubes.
- Premium stock tokens. Export train and pay money to other players
- Port bonus now is payed into the treasury of the corporation.
- Buy infrastructure

[1866] Stock Turn Token

---

assets/app/view/game/game_log.rb

add placeholder for ping user

---

assets/app/view/game/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_18_cz/game.rb

show share ownership percentage

---

assets/app/view/game/buy_trains.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/step/buy_train.rb
lib/engine/game/g_21_moon/step/route.rb

UI::BuyTrain - add ability to specify slot via dropdown (select) input rather than via checkbox.

21Moon: add BC/SP train support

---

lib/engine/game/g_18_ireland/game.rb

Scott and fwtwr confirmed there's seven (plus one optional using the variant, which we don't implement):
http://www.fwtwr.com/18xx/rules_difference_list/single_list.htm

[18Ireland] there should be seven 2H to start

---

assets/app/view/game/game_info.rb
assets/app/view/game/round/stock.rb
assets/app/view/game/stock_market.rb
assets/app/view/game/train_schedule.rb

Issue#6650 show upcoming trains

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb

1873: override can_buy? to check for illegal auto action

---

lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/round/operating.rb
lib/engine/game/g_1866/step/buy_sell_par_shares.rb
lib/engine/game/g_1866/step/convert.rb
lib/engine/game/g_1866/step/issue_shares.rb
lib/engine/game/g_1866/step/stock_turn_token.rb
lib/engine/game/g_1866/step/token.rb
lib/engine/game/g_1866/step/track.rb

- Make sure the KPS and FNR home tiles work.
- Endgame

[1866] Endgame

---

lib/engine/game/g_1873/step/buy_sell_par_shares.rb

1873: reorder operations in process_buy_shares

---

lib/engine/game/g_18_eu/game.rb

From https://github.com/tobymao/18xx/issues/792
During the SR a company forms, a player may choose to exchange a minor instead of a buy action. Must be connected or must be colocated
In the following screenshot, 9 is merged into RPR, colocated in Berlin

18EU Allow Merge of colocated minor

---

lib/engine/game/g_18_mo/game.rb
lib/engine/game/g_18_mo/round/draft.rb
lib/engine/game/g_18_mo/step/draft_purchase.rb

18MO - custom draft

---

lib/engine/game/g_18_eu/step/track.rb

This reverts commit d551d4370099b7b682356a956d97a22ef3201d5a.

Revert "18EU Remove redundant tokens after upgrade (#6903)"

---

lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/route.rb
lib/engine/route.rb
lib/engine/step/auctioner.rb

[18USA] Enforce that no more than two trains can run to Mexico

---

lib/engine/game/g_1866/entities.rb
lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/meta.rb
lib/engine/game/g_1866/step/buy_infrastructure.rb
lib/engine/game/g_1866/step/buy_train.rb
lib/engine/game/g_1866/step/dividend.rb
lib/engine/game/g_1866/step/route.rb
lib/engine/game/g_1866/step/track.rb

- Correct rounds on main page gamecard
- Fixed highlightning when selected route
- Can jump 3 steps
- Can not cross buy infrastructure

[1866] Playtest fixes

---

lib/engine/game/g_18_rhl/step/special_track.rb

18Rhl: Make private 2 and 4 usable in green phase

---

lib/engine/game/g_1822_mrs/game.rb

- Fixed missing ignore on the MRS map.
fixes #5375
fixes #6271
Can break games.

[1822MRS] Fixed the MT&P problem

---

lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_tokens.rb

1862: fix receivership flotation

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england_north/game.rb

18NewEngland2: rules change - lay tokes for inactive minors

---

lib/engine/game/g_1862/step/charter_auction.rb

Fixes #6958 
This will require pinning games.

1862: Prevent bidding when at cert limit

---

lib/engine/game/g_18_rhl/game.rb

A train visiting 2 cities and 1 Town will be shown as 2+1.

18Rhl: Use X+Y notation for Used stops in Route

---

lib/engine/game/g_18_ms/game.rb
lib/engine/game/g_18_ms/step/token.rb

18MS: Add route string for New Orleans bonus

---

assets/app/view/game/buy_trains.rb

See comments https://github.com/tobymao/18xx/issues/6655#issuecomment-1030657858 and https://github.com/tobymao/18xx/issues/6655#issuecomment-1030698842.

Note special 18Ireland EMR rules (addresses #6655)

---

lib/engine/game/g_18_cz/step/draft.rb

18CZ Draft no longer ends when one player cannot afford more companies

---

lib/engine/game/base.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_mex/game.rb
lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/round/operating.rb
lib/engine/game/g_18_usa/round/stock.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/dividend.rb
lib/engine/game/g_18_usa/step/loan.rb
lib/engine/game/g_18_usa/step/obsolete_train.rb
lib/engine/game/g_18_zoo/game.rb
lib/engine/game/g_18_zoo/step/dividend.rb

- Implement P13
- Minor bug fixes/clean-up
Common code changes: Encapsulate rust? logic
Tested against the entire DB. No issues.

[18USA] Implement P13

---

lib/engine/game/g_18_sj/game.rb

18SJ: Improve info description for full cap event/status

---

lib/engine/route.rb

Route: make ordered_paths robust with local trains

---

lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/home_token.rb
lib/engine/game/g_18_usa/step/loan.rb

Includes minor refactoring of subsidies.

[18USA] Implement free station and resource subsidies. 

---

lib/engine/game/g_1840/entities.rb
spec/fixtures/1840/3player.json

[1840] make private symbols shorter to fit in spreadsheet

---

lib/engine/game/g_18_rhl/entities.rb

Seems like ATB needs these flags set, based on the description

[18Rhl] update ATB private

---

lib/engine/game/g_18_gb/step/special_token.rb

- If teleporting, the cost is £50
- If connected, the cost is as usual for laying the next token available on the corporation charter

18GB: Costs for tokens placed with company special abilities

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_18_fl/step/token.rb
lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/assign.rb
lib/engine/game/g_18_usa/step/reduce_tokens.rb
lib/engine/game/g_18_usa/step/special_token.rb
lib/engine/hex.rb
lib/engine/part/icon.rb
lib/engine/step/reduce_tokens.rb
lib/engine/step/token_merger.rb
lib/engine/token.rb

A few games were already adding tokens to hexes, so I created a more general approach.
Ran against the entire DB and no games failed.

[18USA] Implement P8. Adds ability to place tokens on hexes.

---

lib/engine/game/g_1828/step/merger.rb
lib/engine/game/g_18_ny/game.rb

Probably fixes a couple auto buy issues. Someone needs to confirm.
Fixes #7055

[1828.Games] Close merged corporations more thoroughly, [18NY] Minors can own one train from phase 12H and on

---

lib/engine/game/g_18_gb/game.rb

- After the start of the grey phase, the price of shares only drops when the president sells
- As the grey phase begins, remove all unstarted corporations along with one 6X train for each of them

18GB Grey phase rules

---

lib/engine/part/base.rb

Addresses https://github.com/tobymao/18xx/pull/7094#discussion_r805117287.

full_id check for null hex

---

lib/engine/game/g_18_rhl/game.rb

Doubling of Rhine metropolis should only be done if there is a
north-south route.

18Rhl: Correct Rheingold bonus (Fixes #7041)

---

lib/engine/game/g_18_new_england/game.rb
lib/engine/game/g_18_new_england/step/bankrupt.rb
lib/engine/game/g_18_new_england/step/merge.rb

18NewEngland: fix token cost on merge; call close!

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_18_gb/round/operating.rb
lib/engine/game/g_18_gb/step/buy_train.rb
lib/engine/game/g_18_gb/step/emr_share_buying.rb

President may buy a share of the corporation after converting to 10-share for emergency train buying

18GB President purchase during EMR

---

lib/engine/game/g_1870/game.rb

1870 close_corporation during OR needs to also call close! or the ghost corp will still get to operate
Fixes #7103

1870 close corporation needs to call close!

---

lib/engine/game/g_1846/game.rb

Fix 1846 event_close_companies to work with 18MO

---

lib/engine/game/g_1888/game.rb
lib/engine/game/g_1888/meta.rb
spec/fixtures/1888/63897.json

1888: new optional rule; add fixture

---

lib/engine/game/g_18_mo/entities.rb
lib/engine/game/g_18_mo/game.rb
lib/engine/game/g_18_mo/map.rb

fixes #7170
fixes #7172
fixes #7180

18MO - fix train discount, fix remove markers

---

lib/engine/game/g_18_ny/game.rb

[18NY] Fix 4DE train definition for 4DE optional rule

---

lib/engine/game/g_18_eu/step/buy_sell_par_shares.rb

Fix https://github.com/tobymao/18xx/issues/7187
Needed to create an auto action for passing when a player had a minor that was not connected on the graph so as to avoid using the graph during loading.
Though checks for @game.loading are removed here, connected_corporations itself still checks for @game.loading.

18EU Fix 7187 Auto pass on unconnected minors

---

lib/engine/game/g_21_moon/game.rb

21Moon: fix error message and end game bonus message

---

lib/engine/game/g_18_mo/entities.rb
lib/engine/game/g_18_mo/game.rb
lib/engine/game/g_18_mo/step/buy_train.rb

18MO: show all variants if ability can buy them

---

lib/engine/game/g_18_eu/step/modified_dutch_auction.rb

Fixes https://github.com/tobymao/18xx/issues/7224

18EU Fix 7224 - Forced free minor didn't place token

---

lib/engine/game/g_18_eu/step/minor_exchange.rb
lib/engine/game/g_18_eu/step/replace_token.rb

Fix https://github.com/tobymao/18xx/issues/7235
Fix https://github.com/tobymao/18xx/issues/7234

18EU Fix 7235 - Check placed tokens

---

lib/engine/game/g_18_rhl/map.rb

[18Rhl] Improve map to remove cosmetic water borders

---

lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/minor_exchange.rb

Fix https://github.com/tobymao/18xx/issues/7236

18EU Fix 7236 Force Discard Pullman on Merge

---

lib/engine/game/g_1861/meta.rb
lib/engine/game/g_1867/game.rb

[1861] fix wiki link and "ipoed" language

---

lib/engine/game/g_1866/map.rb
lib/engine/game/g_1866/round/operating.rb
lib/engine/game/g_1866/step/buy_train.rb

[1866] Bug fixes

---

lib/engine/game/g_18_eu/game.rb

Fix https://github.com/tobymao/18xx/issues/7261

18EU Fix 7261 Shared owner can lay blocked minor tile

---

lib/engine/game/g_18_usa/map.rb

The existing checks (such as route cannot start or end on a rural junction) still apply

18USA: Rural Junctions don't count toward city limit

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/route.rb

18USA: Fix train upgrades so they work on server as well as hotseat

---

lib/engine/game/g_18_eu/game.rb

Fix https://github.com/tobymao/18xx/issues/7245

18EU Fix 7245 Unable to buy optional trains

---

lib/engine/game/g_21_moon/game.rb

21Moon: add step to allow choosing city for OLS on OO tiles

---

lib/engine/game/g_1866/game.rb
lib/engine/game/g_1866/meta.rb
lib/engine/game/g_1866/step/track.rb

[1866] Scenarios

---

lib/engine/game/g_18_eu/step/bankrupt.rb

Fix https://github.com/tobymao/18xx/issues/7266

18EU Fix 7266 Remove restarted corps from OR

---

lib/engine/game/g_18_gb/game.rb
lib/engine/game/g_21_moon/game.rb
spec/fixtures/21Moon/73613.json

Fixes #7285 
Adds spec for 21Moon

add parameters to upgrades_to_correct_color for 21Moon and 18GB

---

lib/engine/game/g_1840/game.rb

This was missed in the 18USA pullman PR

Fixes #7289

---

lib/engine/game/g_18_mo/game.rb

18MO: fix blank turn number for 2P

---

spec/fixtures/1840/3player.json

this would not have helped to prevent the issues but maybe it will prevent other problems ;)

[1840] Added new fixture

---

assets/app/view/form.rb
assets/app/view/game/auto.rb
assets/app/view/game/auto_action/auction_bid.rb
assets/app/view/game/auto_action/base.rb
lib/engine/action/program_auction_bid.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
lib/engine/game/g_18_mt/game.rb
lib/engine/step/program.rb
lib/engine/step/programmer_auction_bid.rb
lib/engine/step/waterfall_auction.rb

Closes https://github.com/tobymao/18xx/issues/7194
Partial implementation of https://github.com/tobymao/18xx/issues/5336
This provides functionality for automatic bidding on 18EU and Waterfall style auctions. I added to 18MT as a "safer" testing ground for this functionality, since that title is still in alpha. It should work for all waterfalls, though.
Changes to **form.rb**
I moved the render_checkbox method here as it mirrors other functionality within the form class. This allows it to be used by more than just the auto class.
Changes to **auto.rb**, and addition of **auto_action/base.rb and auto_action/auction_bid.rb**
I wanted to separate my functionality so defined a new class to hold specific auto action views. I propose refactoring the current auto actions into these specific …

18EU and Waterfall Auto Auction

---

lib/engine/game/g_18_mo/game.rb
lib/engine/game/g_18_mo/step/special_token.rb
lib/engine/game/g_18_mo/step/track_and_token.rb

18MO: add teleport destinations to location names

---

assets/app/view/welcome.rb
lib/engine/game/g_18_new_england/meta.rb
lib/engine/game/g_18_new_england_north/meta.rb
spec/fixtures/18NewEngland/73885.json
spec/fixtures/18NewEngland2/72500.json

Move 18NewEngland and 18NewEngland2 to beta

---

lib/engine/game/g_18_mo/game.rb

18MO Train balance changes

---

lib/engine/game/g_18_dixie.rb
lib/engine/game/g_18_dixie/companies.rb
lib/engine/game/g_18_dixie/corporations.rb
lib/engine/game/g_18_dixie/game.rb
lib/engine/game/g_18_dixie/map.rb
lib/engine/game/g_18_dixie/market.rb
lib/engine/game/g_18_dixie/meta.rb
lib/engine/game/g_18_dixie/minors.rb
lib/engine/game/g_18_dixie/phases.rb
lib/engine/game/g_18_dixie/tiles.rb
lib/engine/game/g_18_dixie/trains.rb

I'm reusing tokens from other games, at least for now

18Dixie: Initial commit

---

lib/engine/game/g_21_moon/game.rb

21Moon: Fix insert to beginning of trains

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/acquire.rb
lib/engine/game/g_18_usa/step/conversion.rb
lib/engine/game/g_18_usa/step/loan.rb
lib/engine/game/g_18_usa/step/post_conversion_loans.rb
lib/engine/game/g_18_usa/step/scrap_train_module.rb

[18USA] Bug fixes

---

lib/engine/game/g_1850/game.rb
lib/engine/game/g_18_eu/game.rb
lib/engine/game/g_18_ga/game.rb

Fix https://github.com/tobymao/18xx/issues/5359

Fix alt open city logos

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/route.rb

Fixes #7378 
This may require pinning games.

1873: more stringent concession route checks

---

assets/app/view/welcome.rb
lib/engine/game/g_18_eu/meta.rb
spec/fixtures/18EU/74045.json

No bugs reported in over a week ... to beta!

18EU to Beta

---

assets/app/view/game/auto.rb
assets/app/view/game/auto_action/buy_shares.rb

Refactoring of the Buy Shares auto action to the more encapsulated structure.
Also adjusted the wiki to be part of the header so it isn't duplicated anymore.

Refactor Autoaction Buy Shares

---

lib/engine/game/g_1871/game.rb

I replaced `filter` with `reject` a couple of times. Lucas found another one.

fix: wrong filter fix

---

lib/engine/game/g_18_jpt/map.rb

[18JP-T] add cost to J5 tile

---

lib/engine/game/g_18_eu/step/modified_dutch_auction.rb

Fix https://github.com/tobymao/18xx/issues/7432

18EU Fix 7432 Able to spend all money in auction

---

lib/engine/game/g_18_eu/game.rb

Fix https://github.com/tobymao/18xx/issues/7437

18EU Fix 7437 Only apply reservations for minors on empty tile

---

lib/engine/game/base.rb

Per recent discussion on #18xxgamesdev.

Make GAME_END_REASONS_TIMING_TEXT consistent

---

assets/app/view/game/dividend.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/round/dividends.rb
lib/engine/game/g_rolling_stock/step/dividend.rb

Dividends Round
common code edits:
- UI::Dividend - More generic dividend chart

Rolling Stock: Dividends Round

---

assets/app/view/welcome.rb
lib/engine/game/g_1866/meta.rb

[1866] To alpha

---

assets/app/view/game/auto.rb
assets/app/view/game/auto_action/share_pass.rb

Following similar refactors for other Auto Actions to reduce to size and scope of the auto.rb file.

Auto Pass Refactor

---

lib/engine/game/g_1871/meta.rb

Small meta changes for 1871... sorry :)

1871 small meta changes

---

lib/engine/game/g_18_ireland/meta.rb

The only remaining issues are enhancements.

Move 18Ireland into production

---

lib/engine/game/g_18_mt/meta.rb

18MT to Beta

---

lib/engine/game/g_1866/entities.rb
lib/engine/game/g_1866/game.rb

- Minor UI fixes
This does not affect any games.

[1866] Minor UI fixes

---

spec/fixtures/18Mag/76622.json

Add fixture after removing old one due to map change

18Mag: add fixture back
