lib/engine/game/g_1866/game.rb

- Fixed the price of the palace cars
Might be games that needs to be archived.

[1866] Wrong palace car price

---

lib/engine/game/g_18_dixie/map.rb

The picture of the 18Dixie map on BGG is incorrect (old?) and I got to look at a friend's copy to verify what the map looks like

18Dixie: Fix map

---

lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/round/issue.rb
lib/engine/game/g_rolling_stock/step/ipo_company.rb
lib/engine/game/g_rolling_stock/step/issue_shares.rb

* Add Issue Round and step
* Fix IPO when par price is less than company value
* Implement operating costs

Rolling Stock: Issue Shares

---

lib/engine/game/g_1871/game.rb
lib/engine/game/g_1871/round/stock.rb

Fixes for 1871
* Allow transferring of the Hunslet when splitting
* Don't issue reserved shares during EMR

1871 fixes

---

lib/engine/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1840/game.rb
lib/engine/game/g_1846/step/bankrupt.rb
lib/engine/game/g_1849/game.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_18_co/game.rb
lib/engine/game/g_18_co/step/acquisition_auction.rb
lib/engine/game/g_18_co/step/moving_bid_auction.rb
lib/engine/game/g_18_co/step/takeover.rb
lib/engine/game/g_18_cz/step/buy_corporation.rb
lib/engine/game/g_18_cz/step/reduce_tokens.rb
lib/engine/game/g_18_eu/step/bankrupt.rb
lib/engine/game/g_18_eu/step/replace_token.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/game/g_18_mt/step/takeover.rb
lib/engine/game/g_18_new_england/step/bankrupt.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/bankrupt.rb
lib/engine/game/g_18_va/game.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/step/bankrupt.rb
lib/engine/minor.rb

Fixes #7527 
There is a chance this will invalidate a few games.

close_corporation now closes corporations

---

lib/engine/game/g_1867/step/merge.rb

Fixes failures created with change to close_corporation

Fix 61/67 reference to owner after closing minor

---

lib/engine/game/g_1866/game.rb

- Minor bug fix when determining who is the president
It shouldnt affect any games.

[1866] Major formation

---

lib/engine/game/g_18_jpt/meta.rb

I consider implementation to be pretty stable and want to move it to beta.

18JP-T: Move to beta

---

lib/engine/game/g_1862/game.rb

Fixes #7562 
This shouldn't invalidate any games.

1862: Allow swap of directors cert with other players after merge

---

lib/engine/game/g_1846/game.rb

[1846] add price change chart

---

lib/engine/game/g_18_jpt/game.rb

[18JPT] fix train costs

---

assets/app/view/game/alternate_companies.rb
assets/app/view/game/alternate_corporations.rb
assets/app/view/game/auto.rb
assets/app/view/game/auto_action/close_pass.rb
assets/app/view/game/button/buy_share.rb
assets/app/view/game/corporation.rb
assets/app/view/game/master_pass.rb
assets/app/view/game/par.rb
assets/app/view/game/pass_button.rb
assets/app/view/game/players.rb
assets/app/view/game/round/stock.rb
assets/app/view/game/round/unordered.rb
assets/app/view/game_page.rb
lib/engine/action/program_close_pass.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock/step/buy_sell_shares_bid_companies.rb
lib/engine/game/g_rolling_stock/step/close_companies.rb
lib/engine/game/g_rolling_stock/step/dividend.rb
lib/engine/game/g_rolling_stock/step/ipo_company.rb
lib/engine/game/g_rolling_stock/step/propose_and_purchase.rb
lib/engine/game/g_rolling_stock/step/receiver_propose_and_purchase.rb
lib/engine/game/g_rolling_stock_stars/game.rb
lib/engine/step/program.rb

- A few bug fixes
- Many UI tweaks
- Add Master-Mode support and improve hotseat mode

Rolling Stock: play test fixes and tweaks

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_1825/map.rb
lib/engine/game/g_1825/meta.rb

I have not implemented this as two separate options since AFAIK anyone
who uses them uses them together, and '25 has _quite a lot_ of options
already.

Implement variant DB2 improving the SECR

---

assets/app/view/create_game.rb
lib/engine/game/g_1888/entities.rb
lib/engine/game/g_1888/game.rb
lib/engine/game/g_1888/meta.rb

* Add ability to have game options selected by default
* Add a default option to 1888 to support 1888-N
This should be completely backward compatible with existing 1888 games

1888: Add support for 1888-N

---

lib/engine/game/g_1825/entities.rb
lib/engine/game/g_1825/game.rb

1825: Fix access to frozen hash for DB2

---

lib/engine/game/g_rolling_stock/game.rb

I noticed that a tie was broken incorrectly.

Rolling Stock: fix ties

---

lib/engine/game/g_18_ireland/meta.rb

[18Ireland] fix rules link

---

assets/app/view/welcome.rb
lib/engine/game/g_18_eu/meta.rb
lib/engine/game/g_18_mt/meta.rb

No open bug reports for over a month.

18EU and 18MT to production

---

lib/engine/game/g_21_moon/game.rb

21Moon: recover stock from bankrupting corporation

---

lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/round/stock.rb
lib/engine/game/g_18_usa/step/resource_track.rb

Fixes #7304 
Fixes #7350 
Fixes #7538 
Fixes #7568 
Fixes #7590
Fixes #7648
No 18USA games failed when I ran the entire database of 18USA games

18USA bug fixes

---

lib/engine/route.rb

Cool! A latent route bug in find_pairwise_chain
Fixes #7663

Disallow circular routes

---

lib/engine/game/g_18_usa/game.rb

[18USA] Only show GNR bonus in route it applies to

---

lib/engine/game/g_1888/game.rb

Fixes #7676 
This may require pins.

1888: fix MUST_BUY_TRAIN

---

assets/app/view/game/alternate_corporations.rb
assets/app/view/game/companies.rb
assets/app/view/game/round/unordered.rb
lib/engine/game/base.rb
lib/engine/game/g_rolling_stock/game.rb
lib/engine/game/g_rolling_stock_stars/game.rb

* Fixes #7680 
* Adds movement info to corporate cards (rollingstock.net feature)

Rolling Stock: UI improvements

---

lib/engine/game/g_18_usa/entities.rb
lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/step/acquire.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb

[18USA] Offer pullman scrapping even if its the only post acquisition action

---

assets/app/view/game/map.rb
lib/engine/game/base.rb
lib/engine/game/g_1825/game.rb
lib/engine/game/g_18_ny/entities.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/dividend.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/step/special_buy_train.rb
lib/engine/step/special_track.rb
lib/engine/step/tracker.rb
lib/engine/step/train.rb

Fixes #7584 
Fixes #7539 
Fixes #7075

[18NY] Bug fixes and enhancements

---

lib/engine/game/g_1822_mx/game.rb

[1822MX] Fixed problem where M18 is sometimes put in the bid boxes

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/token.rb

[18NY] Next wave of 2nd edition changes requested by Pierre

---

lib/engine/game/g_18_zoo/game.rb
spec/fixtures/18ZOO/81965.json

fix https://github.com/tobymao/18xx/issues/7699

Error when a player has "A tip of sugar" and 1S

---

lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1822_mx/step/dividend.rb

Fixes: #7729
Fixes: #7728
Fixes: #7731

[1822MX] bug fixes

---

lib/engine/game/g_1828/game.rb
lib/engine/game/g_1828/step/merger.rb
lib/engine/game/g_1828/step/route.rb
lib/engine/game/g_1840/game.rb
lib/engine/graph.rb
lib/engine/step/tracker.rb
spec/lib/engine/round/operating_spec.rb

Fixes #5409
Fixes #6380
Fixes #6395
Fixes #6664 
Fixes #6665

[1828.Games] Bug fixes

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_18_ka/game.rb

1856, 1836jr56 futurelabels

---

lib/engine/game/g_18_va/game.rb

18va futurelabels

---

lib/engine/game/g_18_sj/meta.rb
lib/engine/game/g_18_sj/step/buy_company.rb
spec/fixtures/18SJ/hs_gswmvkvs_5.json

Contains a spec file for the latest version (0.92).
Also, includes a few minor fixes:
* Correct a minor error in a log message
* Change name to the new official
* Add clear of graph after KHJ merge (fixes #7727)

18SJ: Add spec file and some minor fixes

---

lib/engine/game/g_1822_mx/round/stock.rb

Last fix for this was not correct.  Minor needs to be ipoed.

[1822MX] Fix M18 value correctly

---

assets/app/view/game/button/buy_share.rb
lib/engine/share_bundle.rb

Fix buy_share to handle preferred shares with bundles correctly

---

lib/engine/game/g_18_zoo/game.rb

18ZOO - Add "Next SR" to Players inside Entities page

---

lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1822_mx/step/issue_shares.rb

[1822MX] Fix stock issuing

---

lib/engine/game/g_1822_mx/step/auction_ndem_tokens.rb

[1822MX] Fix orange banner during NdeM auction step

---

assets/app/view/game/stock_market.rb

Fixes #7078 .
Currently not working for 2D markets that slope downward (see pictures).  I am checking to see that I'm even remotely in the right area of code, or if this should go in the individual market specifications or somewhere else.

Draft version of 2D market arrows.

---

lib/engine/game/g_1866/step/single_item_auction.rb

- Fixed a bug whan a player passed and is the only one left with money.
fixes #7830

[1866] IAR Passing

---

lib/engine/game/g_18_usa/map.rb

References:
https://boardgamegeek.com/image/3477275/18usa
https://boardgamegeek.com/image/6718800/18usa

18usa - fix toronto gray value

---

assets/app/view/game/axis.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/minor_acquisition.rb
lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/map.rb

- Minor 13 is the same as 1822's minor 14.
- Fixed the correct currency
- Fixed some hexes on the map
- Used the new feature future_labels for a few tiles.
**Changes to 1822**
- Changes so the minor 14 home hex have its own constant, and cleaned up the method names associated with it
- View::Game::Axis - Added so it could handle AA - AZ letters.

[1822CA] Map changes

---

lib/engine/game/g_1822_mx/step/special_choose.rb
lib/engine/step/special_choose.rb

This bug was introduced with the fix for issue 7759
Fixes: #7808

[1822MX] Fix inability for a company to close P16.

---

lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/map.rb
lib/engine/game/g_18_ny/step/buy_train.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb

Fixes #7821 
Fixes #7801 
Fixes #7800 
Fixes #7777
Fixes #7850
18NY will need pins. 18USA does not.

[18NY, 18USA] Bug fixes

---

lib/engine/game/g_1822_mx/step/special_track.rb
lib/engine/game/g_1822_mx/step/track.rb
lib/engine/game/g_1822_mx/step/tracker.rb
spec/fixtures/1822_mx/85808.json

Fixes: #7812
Fixes: #7804
This PR will break at least games 83794 and 84499

[1822MX] Fixed P9 not being able to place cubes and M22 tile restrictions

---

lib/engine/game/g_1856/game.rb

Fixes 7840

---

lib/engine/game/g_1822_mx/map.rb

[1822MX] Prevent Mexico City from being hit twice with a single train

---

lib/engine/game/g_1822_mx/step/special_track.rb

[1822MX] Don't allow a port to be played on top of another port

---

lib/engine/game/g_1817/step/selection_auction.rb

[1817] Volatility: Can only bid on companies in the last row

---

lib/engine/game/g_rolling_stock/step/propose_and_purchase.rb
spec/fixtures/RollingStock/83092.json

RollingStock: filter offers for last company in corporation; add fixture

---

lib/engine/game/base.rb
lib/engine/game/g_1822_mx/step/buy_sell_par_shares.rb
lib/engine/game/g_1822_pnw/step/buy_sell_par_shares.rb
lib/engine/game/g_1840/step/buy_sell_par_shares.rb
lib/engine/game/g_1862/game.rb
lib/engine/game/g_1862/step/buy_sell_par_shares.rb
lib/engine/game/g_1867/game.rb
lib/engine/game/g_1871/step/buy_train.rb
lib/engine/game/g_1873/step/buy_sell_par_shares.rb
lib/engine/game/g_1877_stockholm_tramways/entities.rb
lib/engine/game/g_1877_stockholm_tramways/game.rb
lib/engine/game/g_1877_stockholm_tramways/step/buy_sell_par_shares.rb
lib/engine/game/g_1877_stockholm_tramways/step/buy_train.rb
lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
lib/engine/game/g_18_ny/game.rb
lib/engine/game/g_18_ny/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares_companies.rb
lib/engine/step/buy_sell_par_shares_via_bid.rb
lib/engine/step/emergency_money.rb

I had to fix a bug in `buy_sell_par_shares_via_bid.rb` to make it also work with games with a `HOME_TOKEN_TIMING` other than `:par`. This required changing the `HOME_TOKEN_TIMING` of 1861/1867 to `:par`, as it was incorrectly set to `:float` and it only worked correctly due to the bug I fixed.

1877: Stockholm Tramways implemented auctioning of corporations and starting phases of corporations.

---

lib/engine/game/g_1856/game.rb

1856: Make cert limit static

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/step/track.rb

Use future_labels for 1870

---

assets/app/view/welcome.rb
lib/engine/game/g_18_va/meta.rb

18VA is overdue to go into production at this point

put 18VA into production

---

lib/engine/game/g_1817/entities.rb
lib/engine/game/g_1817/game.rb

[1817] Fix train scrapper private server side implementation

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/meta.rb
lib/engine/game/g_1868_wy/step/track.rb
lib/engine/game/g_1868_wy/step/waterfall_auction.rb
lib/engine/game/g_1868_wy/trains.rb

* new stock market
* update numbers for private companies
* update train costs
* delete references to removed corporations
* update player count
Like #7925, no real code changes here; just some functions renamed to match the renumbered privates, and a bunch of config changes to various constants.
#5011

[1868WY] config updates, rename functions for private company number changes

---

lib/engine/game/g_1873/step/track.rb

1873: don't allow out of phase tile colors if not concession route building

---

assets/app/view/welcome.rb
lib/engine/game/g_18_los_angeles/entities.rb
lib/engine/game/g_18_los_angeles/meta.rb

Fixes #7894, fortunately it was just an issue with the private text, not with the map or functionality

[18LA2] update private descriptions, move to beta

---

lib/engine/game/g_rolling_stock/game.rb

Fixes #7933 
Amazingly, no pins required!

Rolling Stock: fix cost of ownership in log

---

lib/engine/game/g_21_moon/round/corporate.rb

Fixes #7941 
No pins required.

21Moon: handle corporation closing in corporate round

---

lib/engine/game/g_1877_stockholm_tramways/game.rb
lib/engine/game/g_1877_stockholm_tramways/step/buy_sell_par_shares.rb
lib/engine/game/g_1877_stockholm_tramways/step/buy_train.rb

1877: Stockholm Tramways made starting phases of companies easier to see

---

lib/engine/game/g_1849/round/stock.rb

Fixes issue caused by promotion of fix for #7937

[1849] Fixed re-ordering of corporations happening too frequently

---

lib/engine/game/g_1822_mx/game.rb

[1822MX] Cleanup bidding boxes and info

---

lib/engine/game/g_1877_stockholm_tramways/game.rb

[1877] update pronoun in logs

---

lib/engine/game/g_1871/game.rb

Might cause archiving for some games.

[1871] Require Mainline Concession for ML presidency (fixes #7552)

---

assets/app/view/game/par.rb
lib/engine/action/par.rb
lib/engine/game/g_1871/step/buy_sell_par_split_shares.rb
lib/engine/step/buy_sell_par_shares.rb

Based on the analogous existing code for buying stock on behalf of others.

[1871] Par on behalf of others (fixes #7596)

---

assets/app/view/game/spreadsheet.rb

Display reserved shares in spreadsheet (fixes #4389)

---

assets/app/view/chat.rb
assets/app/view/form.rb
assets/app/view/game/game_log.rb
assets/app/view/game_card.rb

refactor game opening button text "Enter" => 'View'

---

lib/engine/game/g_1871/game.rb

I didn't realize that I'd have to truncate by hand.

[1871] Kill floats for real (may fix #8004)

---

DEVELOPMENT.md

Was pleased to find this functionality. I thought it was worth having in the development notes.

Notes on importing game states.

---

lib/engine/game/base.rb
routes/game.rb

Validate correct auto actions on the server

---

lib/engine/game/g_1817/step/buy_sell_par_shares.rb
lib/engine/game/g_1856/game.rb
lib/engine/game/g_18_ny/step/claim_coal_token.rb

Fixes #8046 
Fixes #8044 
Fixes #8047

[1856, 1817] Bug fixes

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_sell_par_shares.rb

BOE is a corporation of type bank that has no president share, all the shares start in the pool, doesn't have a president but pays dividends to shareholders.
Implemented no president, starting shares in pool, 2000 starting capital

[1848] implement some boe features

---

assets/app/view/welcome.rb
lib/engine/game/g_1822_mx/entities.rb
lib/engine/game/g_1822_mx/meta.rb

Also fix P3/2 description
Fixes: #8022

[1822MX] Move 1822MX to beta

---

lib/engine/game/g_1817/step/acquire.rb

[18USA] Golden parachute doesn't pay out if corp owned by market

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/stock_market.rb

Implement privates, BoE market row, extra tile lay, and loans

[1848] Implement privates, BoE market row, extra tile lay on phase 3

---

lib/engine/game/g_rolling_stock/game.rb

Fixes #7935
Fixes #8057 
This will likely require pinning failing games.

Rolling Stock: fix Foreign income; fix liquidity

---

lib/engine/game/g_1856/meta.rb
lib/engine/game/g_1856/step/loan.rb
spec/fixtures/1836jr56/hotseat002.json
spec/fixtures/1836jr56/hotseat003.json
spec/fixtures/1836jr56/hotseat004.json
spec/fixtures/1856/51745.json
spec/fixtures/1856/89363.json
spec/fixtures/1856/hotseat001.json
spec/fixtures/1856/hotseat005.json
spec/fixtures/1856/hotseat006.json
spec/fixtures/1856/hotseat007.json

Fixes 5639, providing a migration, and moving 1856 to production

---

lib/engine/game/g_18_jpt/game.rb
lib/engine/game/g_18_jpt/map.rb
lib/engine/game/g_18_jpt/step/track.rb

18JPT: use future labels instead of custom code for KU hexes

---

lib/engine/game/g_18_al/game.rb

18AL: Use future label for Montgomery

---

lib/engine/game/g_18_tn/game.rb

18TN: Use future labels to simply custom tile upgrade logic

---

lib/engine/game/g_18_carolinas/step/buy_power.rb
spec/fixtures/18Carolinas/86397.json

A missing unused parameter was found on president_may_contribute
Also adding spec.

18Carolinas: add missing unused parameter

---

lib/engine/game/g_1862/step/charter_auction.rb

Fixes #7521 
Just a cosmetic change - no pinning/archiving needed

1862: fix liquidity in parliament rounds

---

lib/engine/game/g_1877_stockholm_tramways/step/buy_train.rb

1877: Stockholm Tramways fixed not able to continue game when current company has 0kr

---

lib/engine/game/g_18_sj/map.rb

Without the label an illegal upgrade on regaular cities might occur.

18SJ: Put A label on Stockholm hex/tiles (fixes #8100)

---

lib/engine/game/g_18_rhl/game.rb

Readability improvement that should have no effect on
existing games.

18Rhl: Refactoring of 8 train checks

---

lib/engine/game/g_21_moon/step/track.rb

Fixes #8111 
No archiving/pinning needed.

21Moon: fix tile lays

---

lib/engine/game/g_1861/game.rb
lib/engine/game/g_1867/game.rb

move add_neutral_tokens to init_hexes. correcting starting map

---

api.rb
assets/app/app.rb
assets/app/lib/profile_link.rb
assets/app/user_manager.rb
assets/app/view/game/entity_list.rb
assets/app/view/game/player.rb
assets/app/view/game_card.rb
assets/app/view/log.rb
assets/app/view/navigation.rb
assets/app/view/user.rb
models/user.rb

- Public profiles that show active and finished/archived games.
- Links to the public profiles in game cards, front page chat, in-game entity list, and in-game player card.

Implement public profiles

---

lib/engine/game/g_1817/game.rb
lib/engine/game/g_1817/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/interest_on_loans.rb

Bug fixes for 1817, 1817 Volatility, and 18USA

---

assets/app/view/create_game.rb
assets/app/view/game_card.rb
lib/engine/game/g_1825/meta.rb
lib/engine/game/g_1888/meta.rb
migrate/0006_add_min_players_to_games.rb
models/game.rb
routes/game.rb

Implement minimum player counts

---

lib/engine/game/g_1822/step/minor_acquisition.rb
lib/engine/game/g_1822_mx/step/minor_acquisition.rb

[1822MX] Don't do special code for acquiring M14 from bank

---

lib/engine/game/base.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_train.rb
lib/engine/game/g_1848/step/special_buy_train.rb
spec/fixtures/1848/1848_game.json

- can't upgrade 4+ to D  
- add minor description price range for buying
- fix issue where ghan can't be bought in last step

[1848] fix minor bugs

---

assets/app/view/game/buy_trains.rb

fix broken game 1877

---

api.rb
assets/app/lib/settings.rb
assets/app/view/user.rb
models/user.rb
public/assets/main.css

Also added a few headers to make the profile page look cleaner

Configure and display user stats

---

lib/engine/game/g_1848/game.rb

[1848] Fix P1 desc

---

lib/engine/game/g_1848/map.rb

Related to #8228 , does not close it

[1848] add label to Tasmania tile

---

lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_train.rb

fixes #8235
fixed #8256
fix typos (guage vs gauge)

[1848] fix ghan visit logic and 8256

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_mx/game.rb

[1822MX] Fix problem with P16 counting as a share

---

lib/engine/game/g_1817/entities.rb
lib/engine/game/g_1817/map.rb

This changes the text copy for "place a B Tile" privates, and sets count = 1 for that special tile
Closes #8264

[1817] Refactor text copy in privates

---

lib/engine/game/g_1822_mx/step/auction_ndem_tokens.rb

[1822MX] Don't allow under bidding

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_18_ka/game.rb
lib/engine/game/g_18_mex/game.rb
lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_tokaido/game.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/buy_sell_par_shares_companies.rb
lib/engine/step/share_buying.rb

[1848] fix cert limit bug

---

lib/engine/game/g_18_los_angeles/entities.rb

[18LA2] fix ELA teleport price

---

assets/app/view/game/buy_trains.rb
lib/engine/game/base.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/step/buy_train.rb

[1848] fix EMR text

---

assets/app/view/welcome.rb
lib/engine/game/g_1848/game.rb
lib/engine/game/g_1848/meta.rb
lib/engine/game/g_1848/step/buy_train.rb
lib/engine/step/train.rb

MERGE https://github.com/tobymao/18xx/pull/8324 first
(this PR is off the tip of that PR)
Remove un-used code

1848 cleanup

---

lib/engine/game/g_1822_pnw/game.rb
lib/engine/game/g_1822_pnw/step/minor_acquisition.rb
lib/engine/game/g_1822_pnw/step/special_track.rb

[1822PNW] Bug fixes

---

lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb
lib/engine/publisher.rb

Fixes #8360 
Also, fixed Lonny Games URL at Lonny's request.

21Moon: Force pass during Corporate Round for receivership corps

---

assets/app/view/game/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/minor_acquisition.rb
lib/engine/game/g_1822_pnw/entities.rb
lib/engine/game/g_1822_pnw/game.rb
lib/engine/game/g_1822_pnw/step/acquire_company.rb
lib/engine/game/g_1822_pnw/step/connections.rb
lib/engine/game/g_1822_pnw/step/merge.rb
lib/engine/game/g_1822_pnw/step/minor_acquisition.rb
lib/engine/game/g_1822_pnw/step/route.rb
lib/engine/game/g_1822_pnw/step/special_track.rb
spec/fixtures/1822_PNW/p19_merge_coal_company_1.json
spec/fixtures/1822_PNW/p19_merge_coal_company_2.json
spec/fixtures/1822_PNW/p19_merge_coal_company_3.json
spec/fixtures/1822_PNW/p19_merge_coal_company_4.json

1822PNW Fix coal token

---

lib/engine/game/g_21_moon/step/dividend.rb

21Moon: fix dividends with revenue between 0 and half share price

---

assets/app/view/game/part/track.rb
lib/engine/game/g_1822_mx/map.rb
lib/engine/game/g_1822_pnw/map.rb

[1822PNW and 1822MX] Add in dashed lines to represent ferry connections

---

lib/engine/game/g_18_rhl/game.rb

The redesign of Rhine Metropolis green hexes caused home token placement to break for CCE. Have improved the code so that it should work fine for any corporation that starts in a Rhine Metropolis hex.

18Rhl: Correct home token placement (fixes #8337)

---

lib/engine/game/g_1848/game.rb

add payout chart 1848, partial fix of #8417

add payout chart 1848

---

lib/engine/game/g_1862/step/charter_auction.rb

1862: Fix max_bid in Parliament Round

---

lib/engine/game/g_1822_pnw/game.rb
lib/engine/game/g_1822_pnw/step/buy_sell_par_shares.rb

[1822PNW] Fix converting to a major

---

lib/engine/game/g_1822_pnw/game.rb
lib/engine/game/g_1822_pnw/step/buy_sell_par_shares.rb

[1822PNW] Fix merging round titles in log

---

lib/engine/distance_graph.rb

Fixes #8444 
No pins/archives required

Fix distance graph pruning

---

lib/engine/game/g_1822_mx/entities.rb

* Replace pound sign in C7 description

[1822MX] Fix pound sign in C7 description

---

import_game.rb

Update `import_game.rb` script to handle cases where the creator/owner of the game is not one of the players (e.g. tournament games)

Update import_game.rb script to handle games where the owning user is not a player

---

lib/engine/game/g_1822_pnw/entities.rb

fixes #8469
There was a similar issue with Minor 1, just due to a typo

[1822PNW] fix minor colors

---

lib/engine/game/g_1822_mx/map.rb

[1822MX] fix tilecount

---

lib/engine/game/g_1822_pnw/entities.rb

1822PNW: Add H21 and J5 to paper mill hexes

---

assets/app/view/game/train_schedule.rb

Show 'no upcoming trains' if there are no upcoming trains

---

lib/engine/game/g_1825/game.rb

[1825] fix stock price movement chart

---

lib/engine/game/g_18_rhl/entities.rb

[18RHL] fix typo in P1

---

lib/engine/game/g_1822/step/destination_token.rb
lib/engine/game/g_1822_mx/step/minor_acquisition.rb

[1822MX] Fix minor acquisition over ports

---

lib/engine/game/g_21_moon/entities.rb

[21Moon] Adding max price notes to private cards.

---

lib/engine/game/g_18_dixie/corporations.rb
lib/engine/game/g_18_dixie/game.rb
lib/engine/game/g_18_dixie/trains.rb
public/logos/18_dixie/ICG.alt.svg
public/logos/18_dixie/SCL.alt.svg

In the physical game, there is one charter and set of shares for both corporations together since only one of the two can exist at any time but since we can do so here, we may as well split them up into separate corporations for clarity

18Dixie ICG/SCL Merger 1st part: Add ICG&SCL

---

lib/engine/game/g_1840/step/route.rb
lib/engine/route.rb

fixed no token oncity  route issue

---

lib/engine/game/g_18_ireland/game.rb

[18Ireland] Shares s.b. labeled 'Treasury' rather than IPO (default)

---

lib/engine/game/g_1871/game.rb
lib/engine/game/g_1871/market.rb
lib/engine/game/g_1871/phases.rb
lib/engine/game/g_1871/trains.rb

closes #8530
s/par/start/g
Also fixes minor typo in private "Hunslet" desc

[1871] Replace "pars" with "starts"

---

DEVELOPMENT.md
assets/app/view/game/spreadsheet.rb
lib/engine/corporation.rb
lib/engine/operator.rb

makes it easier to see who is going to buy which trains

show order of unfloated companies

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1822_pnw/game.rb

Fixes #8479; see issue for rules discussion

[1822MX,1822PNW] allow LP train to use Mail Contract privates

---

assets/app/view/game/abilities.rb
lib/engine/ability/manual_close_company.rb
lib/engine/action/manual_close_company.rb
lib/engine/game/g_1868_wy/entities.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/manual_close_company.rb

[1868WY] private companies can be closed at any time

---

.github/workflows/ruby.yml
lib/engine/game/g_21_moon/step/waterfall_auction.rb

[21Moon] Unpass all entities after an all pass in an auction

---

lib/engine/game/g_21_moon/game.rb
migrate_game.rb

[21Moon] Allow shares to be sold in SR1

---

lib/engine/game/g_1867/step/loan_operations.rb

[1861/1867] log when a railroad cannot pay loan interest

---

assets/app/view/create_game.rb

fix imported games requiring a selected game

---

lib/engine/graph.rb

Extract two new methods: `home_hexes` and `home_hex_nodes`. These are for when `home_is_token` is set and are for setting up the locations that will be used for starting the graphs.
Extracting these methods allow these to be overridden in subclasses if different behaviour is needed. The default implementation matches the existing behaviour.
This change has been extracted from pull request #8578. 1858 needs to override `home_hex_nodes` as the existing behaviour needs to be changed in two ways:
1. The interaction between a corporation's `coordinates` and `city` attributes needs to be changed, so it possible to specify different city indexes in different hexes.
2. Dummy nodes need to be created for plain track hexes, so it is possible to start node walks from these hexes.

Refactor Engine::Graph.compute, extracting two methods

---

lib/engine/game/g_1873/game.rb
lib/engine/game/g_1873/step/route.rb

Fixes #8586 
This shouldn't invalidate any games.

1873: handle doubly-tokened concession route

---

lib/engine/game/g_1862/step/buy_train.rb

1862: add missing comma to GameError call

---

lib/engine/part/city.rb

Fix city tokens and reservations getting out of sync

---

lib/engine/game/g_18_we.rb
lib/engine/game/g_18_we/entities.rb
lib/engine/game/g_18_we/game.rb
lib/engine/game/g_18_we/map.rb
lib/engine/game/g_18_we/meta.rb

Began the implementation of [18WE: Western Europe](https://boardgamegeek.com/boardgame/317048) by Karl Ernst.
- Map implemented
- Tileset implemented
- Other rules currently inherited from the game's predecessor, 1862

18WE: Initial commit with map and tileset

---

assets/app/view/game_page.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/buy_company.rb
lib/engine/game/g_1868_wy/step/home_token.rb
lib/engine/game/g_1868_wy/step/stock_round_action.rb
lib/engine/game/g_1868_wy/step/track.rb

* if it chooses a Boom City as a home which later BUSTs, it cannot take OR actions until choosing a home again in a later SR
[#5011]

[1868WY] DPR, no fixed home

---

lib/engine/game/g_1868_wy/step/track.rb
lib/engine/game/g_1868_wy/step/tracker.rb

* each corporation gets 6 track points per OR
* yellow tiles cost 2 points
* upgrades cost 3 points
[#5011]

[1868WY] track laying points

---

lib/engine/step/tracker.rb

Log discounts from track laying abilities 

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/track.rb
lib/engine/game/g_1868_wy/step/waterfall_auction.rb

* fix bug with full capitalization       
* fix P5a Casement
* fix bug in auction where removed company stayed open
* fix bug that allowed building track pointing to gray hex

[1868WY] small bug fixes

---

lib/engine/game/base.rb

Corrects pinned game log message. 

---

lib/engine/game/g_1822_pnw/map.rb

Corrects 1822PNW grey city tiles

---

lib/engine/game/g_18_mt/map.rb

Fixes #8459
Will require existing games to be pinned.

[18MT] Correct B2/B4 border to impassable

---

lib/engine/depot.rb
lib/engine/game/base.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/buy_train.rb
lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1824/depot.rb
lib/engine/game/g_1848/depot.rb
lib/engine/game/g_1871/step/hunslet_purchase_train.rb
lib/engine/game/g_1873/game.rb
lib/engine/game/g_1877/step/buy_sell_par_shares.rb
lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/step/rocket_purchase_train.rb
lib/engine/game/g_18_cz/game.rb
lib/engine/game/g_18_rhl/step/bankrupt.rb
lib/engine/game/g_18_sj/game.rb
lib/engine/game/g_18_zoo/step/choose_ability_on_sr.rb
lib/engine/game/g_21_moon/step/buy_train.rb
lib/engine/phase.rb
lib/engine/step/train.rb
spec/lib/engine/games/g_1828_spec.rb
spec/lib/engine/games/g_18_zoo_spec.rb
spec/lib/engine/round/operating_spec.rb

for 1880 I need to be able to determine the source of the train purchased.
I added source to @game.phase.buying_train! as a param.
updated all places where this method is used

[1880] train source

---

assets/app/view/welcome.rb
lib/engine/game/base.rb
lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/meta.rb

move 1880 to alpha
fix end game text

[1880] move 1880 to alpha

---

models/user.rb

Reverts tobymao/18xx#8707
fixes #8717

Revert "strip param values in User#update_settings"

---

lib/engine/game/g_1880/game.rb

[1880] fix SCR, QSR error on place_home_token

---

lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/round/operating.rb

[1880] fix SCR, QSR error on place_home_token 

---

lib/engine/share_pool.rb

[1880] fix disappearing shares when prez changes

---

assets/app/view/game/stock_market.rb

The old code sorted by rows, starting at the bottom row. The updated code also considers columns.
Also removed an unused variable.

[1880] Sort stock market legend starting at bottom row, left column

---

assets/app/view/welcome.rb
lib/engine/game/g_rolling_stock/meta.rb
lib/engine/game/g_rolling_stock/step/ipo_company.rb
lib/engine/game/g_rolling_stock_stars/meta.rb

Fixes #8747 
Move to production

RS: fix log message on IPO, move RS and RSS to production

---

lib/engine/game/g_1888/meta.rb

Fix 1888 rules link

---

spec/fixtures/RollingStock/108770.json

Added spec fixture for Rolling Stock (Rolling Stock Stars already had one).

add fixture for Rolling Stock

---

assets/app/view/game/par_chart.rb
lib/engine/game/g_1880/round/operating.rb
lib/engine/round/operating.rb

[1880] fix end game code

---

lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/step/assign.rb
lib/engine/game/g_1880/step/buy_train.rb

[1880] fix 2p not showing up

---

lib/engine/game/g_1880/minor.rb

[1880] fix minors not getting owner abilities

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_pnw/map.rb
lib/engine/game/g_1822_pnw/step/special_track.rb
lib/engine/game/g_1822_pnw/step/track.rb

[1822PNW] Don't allow portage tiles on top of port tiles

---

lib/engine/game/g_1822/step/minor_acquisition.rb

[1822MX] Fix interaction of P16 and Minor Acquisition

---

lib/engine/game/g_18_usa/entities.rb

[18USA] GNR private text should say one train

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/route.rb
lib/engine/game/g_1868_wy/step/special_track.rb
lib/engine/game/g_1868_wy/step/tracker.rb

* highlight both Billings hexes when one is reachable
* purple tiles can only be run by the home railroad (FEMV and RCL)
* set up Walden, neutral city
[#5011]

[1868WY] various small map features

---

lib/engine/action/credit_mobilier.rb
lib/engine/game/g_1868_wy/credit_mobilier.rb
lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/round/operating.rb
lib/engine/game/g_1868_wy/step/track.rb
lib/engine/hex.rb

* until phase 5 or the Golden Spike is complete, the "Credit Mobilier" pays UP shareholders any terrain costs spent to extend a route from Omaha towards the Golden Spike hex, or vice versa
[#5011]

[1868WY] Credit Mobilier

---

lib/engine/game/g_18_texas/game.rb
lib/engine/game/g_18_texas/meta.rb
lib/engine/game/g_18_texas/step/discard_train.rb

Fixes #8825 
Remove prototype flag

18Texas: remove discarded trains, remove prototype flag

---

lib/engine/game/g_1880/game.rb

1880 - fix ending game when minors have 0 in treasury

---

lib/engine/game/g_1850/corporation.rb
lib/engine/game/g_1850/entities.rb
lib/engine/game/g_1850/game.rb
lib/engine/game/g_1850/map.rb
lib/engine/game/g_1850/meta.rb
lib/engine/game/g_1850/step/buy_company.rb
lib/engine/game/g_1850/step/token.rb
lib/engine/game/g_1850/step/track.rb
public/logos/1850/CBQ.svg
public/logos/1850/GN.svg
public/logos/1850/KATY.svg
public/logos/1850/MILW.svg
public/logos/1850/MP.svg
public/logos/1850/NP.svg
public/logos/1850/RI.svg
public/logos/1850/SOO.svg
public/logos/1850/UP.svg

- clean map 
- add mesabi token logic
- add tile lay definition similar to 18cz (2 lays for first OR of a corp, 1 lay/upgrade after)
- add icons

[1850] mesabi tokens

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/route.rb

$10 to private owner for every route run by anyone to Casper.
[#5011]

[1868WY] P2c Midwest Oil

---

lib/engine/game/g_1870/entities.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/map.rb
lib/engine/game/g_1870/meta.rb

This implements the "1830 Diesels" variant from the official rulebook. 
I also used the opportunity to create a map.rb and entities.rb file for the game.

[1870] Adds Diesel variant to 1870

---

lib/engine/game/base.rb
lib/engine/game/g_1880/game.rb
lib/engine/tile.rb

[1880] fix scr qsr placement blocking

---

assets/app/view/welcome.rb
lib/engine/game/g_1850/entities.rb
lib/engine/game/g_1850/meta.rb
spec/fixtures/1850/1.json

add hex blocking ability for privates
move to alpha

[1850] add hex blocking ability, move to alpha

---

lib/engine/game/g_1850/game.rb
spec/fixtures/1850/114102.json

fix #8883  -> no gray on train 6
fix #8884  -> multiple buy is only from market, not ipo
fix #8885 -> mesabi token logic

[1850] fix minor bugs

---

lib/engine/game/g_1850/game.rb
lib/engine/game/g_1850/step/track.rb
spec/fixtures/1850/114102.json

[1850] fix mesabi token buying when not connected

---

lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_mag/meta.rb
lib/engine/game/g_18_mag/step/simple_draft.rb
public/logos/18_mag/14.svg
public/logos/18_mag/15.svg
public/logos/18_mag/16.svg

Add module 2 of the new 18mag expansion. 
3 new minors with two variants:
simple -> add new minors, remove 3 at random 
challenging -> play with 16 minors, players start with more minors depending on player count

[18mag expansion] add module 2 - extra minors simple and challenging

---

lib/engine/game/g_1866/meta.rb

[1866] Remove some scenarios

---

lib/engine/game/g_1862/game.rb

[1862] fix presidency check when selling shares

---

lib/engine/game/g_1862/game.rb

Revert "[1862] fix presidency check when selling shares"

---

lib/engine/game/g_1862/game.rb

1862: Fix code to detect president sales

---

TILES.md
assets/app/view/game/part/towns.rb
lib/engine/game/g_1880/map.rb
lib/engine/part/town.rb

Add `hidden` style for towns, use for 1880 ports

---

lib/engine/game/g_1817/entities.rb

[1817] make coal mine desc more verbose / clear

---

lib/engine/game/g_18_mag/step/simple_draft.rb

[18mag variant] fix 6 player extra minors variant

---

lib/engine/game/g_1860/game.rb
lib/engine/game/g_1862/game.rb

[1860/2] Update stock movement to reflect new zigzag market behavior

---

lib/engine/game/g_1822/stock_market.rb
lib/engine/game/g_1828/stock_market.rb
lib/engine/game/g_1848/stock_market.rb
lib/engine/game/g_1849/stock_market.rb
lib/engine/game/g_1866/stock_market.rb
lib/engine/game/g_1867/stock_market.rb
lib/engine/game/g_1868_wy/stock_market.rb
lib/engine/game/g_1870/stock_market.rb
lib/engine/game/g_18_co/stock_market.rb
lib/engine/game/g_18_fl/stock_market.rb
lib/engine/game/g_18_ny/stock_market.rb
lib/engine/stock_market.rb
lib/engine/stock_movement.rb

The game overrides of stock movement weren't being called when on a ledge. I now call back into stock_market when on a ledge, so that the overrides are executed.
I ran the entire database. No unexpected failures.

Integrate stock_market and stock_movement more closely

---

lib/engine/game/g_18_mag/game.rb

train discount supporter didn't work due to wrong time param

[18mag] fix train discount supporter

---

lib/engine/game/g_1836_jr56/game.rb
lib/engine/game/g_1836_jr56/meta.rb

Adds diesel variant to 1836jr56

Adds diesel variant to 1836jr56

---

lib/engine/game/g_1846/meta.rb

[1846] Update rules link on Info page

---

lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_mag/step/pay_tile.rb
lib/engine/game/g_18_mag/step/special_track.rb
lib/engine/game/g_18_mag/step/track.rb

minor fix to existing supporter. Change tiles, add that special is false
Tile payment was wrong, and didn't pay SIK company if supporter was used. 
I extracted the method into a PayTile module, that is used by both track (regular lay) and special_track (lay via supporter)

[18mag] fix new supporter

---

lib/engine/game/g_1848/step/dutch_auction.rb

[1848] add unpass after buying a private

---

lib/engine/game/g_18_los_angeles/entities.rb

[18 Los Angeles] - LA Citrus can’t be placed in LAX

---

lib/engine/game/g_1880/step/buy_train.rb

[1880] allow cross buy of 2p

---

lib/engine/game/g_1880/game.rb

replace par price to president share density in corp card
Fixes #9014

[1880] replace par with share density

---

lib/engine/game/g_1822_mx/step/discard_train.rb

Fixes #8567
Checked during discard if the entity is NdeM, remove train from game if so.

[1822_MX] NdeM discarded trains should be removed from the game

---

lib/engine/game/g_1868_wy/game.rb
lib/engine/game/g_1868_wy/step/buy_company.rb
lib/engine/game/g_1868_wy/trains.rb

[1868WY] allow "buying" companies in phase 2 for $0

---

lib/engine/game/g_1868_wy/game.rb

#5011 
P2-P6 each have three different possible companies, P3c is already implemented.
* P3a - Union Pacific Coal Company
* P3b - Bonanza Oil
* P3c - Frémont Expedition - $20 discount on DTs, already implemented; now show the discount on the coal/oil company cards
P3a and P3b each give an extra DT to the owning player, which can be placed ignoring normal DT limits.

[1868WY] Implement P3 privates - UPC, BZ, Frémont 

---

lib/engine/ability/README.md
lib/engine/game/base.rb

* Add `when: 'token'` possibility for abilities
* Necessary for 1847 AE

Add when: 'token' possibility

---

lib/engine/game/base.rb

Log obsolete trains removed from the Depot separately from rusted trains

---

lib/engine/game/g_1817/game.rb

[1817] Verify loans valid

---

lib/engine/game/g_1817/game.rb

[1817] Handle loans internally, ignoring loan provided from view

---

lib/engine/game/g_1880/round/operating.rb
lib/engine/round/operating.rb

[1880] fix 9081 - no end trigger if corp has no actions

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb

[1822 family] end the game if nothing sold in SR1

---

lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/meta.rb

[1880] fix minor issue, move to prod

---

lib/engine/game/base.rb
lib/engine/game/g_18_mag/game.rb
lib/engine/game/g_18_mag/step/buy_train.rb

[18mag optional rules] fix 18mag supporter train discount

---

lib/engine/game/g_18_usa/game.rb
lib/engine/game/g_18_usa/map.rb
lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/special_track.rb
lib/engine/tile.rb

[18USA] Hide unused metropolis tiles

---

lib/engine/game/g_1828/game.rb

[1828] place blocking token in correct city on hex

---

lib/engine/game/base.rb

fix `ability_combo_entities` to allow for multiple abilities

---

assets/app/view/game/button/buy_share.rb
assets/app/view/game/buy_sell_shares.rb
lib/engine/game/base.rb
lib/engine/game/g_1817/step/share_buying_with_shorts.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb
lib/engine/game/g_1856/step/buy_sell_par_shares.rb
lib/engine/game/g_18_mex/step/buy_sell_par_shares.rb
lib/engine/game/g_21_moon/step/exchange.rb
lib/engine/share_pool.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/step/share_buying.rb
lib/engine/step/special_token.rb

- Add functionality to allow buying shares from another player.
- If a token ability has a hexes value of nil, match all hexes.

Buying shares from other players, support token abilities with nil hexes

---

assets/app/view/create_game.rb

Fixes issue importing hotseat games

fix issue importing hotseat games

---

assets/app/view/game/loan_chart.rb
assets/app/view/game/player.rb
assets/app/view/game/round/stock.rb
assets/app/view/game/stock_market.rb
lib/engine/action/take_loan.rb
lib/engine/game/base.rb
lib/engine/game/g_1877_stockholm_tramways/step/acquire.rb
lib/engine/share_pool.rb
lib/engine/share_price.rb
lib/engine/step/buy_sell_par_shares.rb
lib/engine/stock_market.rb
public/icons/red_cube.svg

- UI loan chart
- Player loan support
- Misc loan refactoring
cc @outsidePasser

UI loan chart and player loan support

---

lib/engine/game/g_18_usa/step/buy_sell_par_shares.rb
lib/engine/game/g_18_usa/step/home_token.rb
migrate_game.rb
public/fixtures/18USA/109372.json
public/fixtures/18USA/110327.json

Fixes #9205
@michaeljb added another case to migrate_game. If the broken action entity is different from the current entity, try to pass.

[18USA] Corporations can exceed bid amount when acquiring companies.

---

assets/app/view/game/corporate_buy_sell_shares.rb
lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/round/operating.rb
lib/engine/game/g_1841/step/buy_new_tokens.rb
lib/engine/game/g_1841/step/buy_sell_par_shares.rb
lib/engine/game/g_1841/step/choose_option.rb
lib/engine/game/g_1841/step/corp_start.rb
lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb
lib/engine/game/g_1841/step/merge.rb
lib/engine/game/g_1841/step/transform.rb

This adds the "transformation" OR step (aka "convert").
It also adds a proper "must_sell" to the corporate_buy_sell_shares step
The only common-code change was a bug fix to UI:CorporateBuySellShares (which only 1841 uses at this point).

1841: add transforming step

---

assets/app/view/game/round/operating.rb
lib/engine/game/g_18_dixie/corporations.rb
lib/engine/game/g_18_dixie/game.rb
lib/engine/game/g_18_dixie/minors.rb
lib/engine/game/g_18_dixie/phases.rb
lib/engine/game/g_18_dixie/step/bankrupt.rb
lib/engine/game/g_18_dixie/step/home_token.rb
lib/engine/game/g_18_dixie/step/icgscl_merge_consent.rb
lib/engine/game/g_18_dixie/step/icgscl_option_share.rb
lib/engine/game/g_18_dixie/step/icgscl_presidency_exchange.rb
lib/engine/game/g_18_dixie/step/remove_tokens.rb
lib/engine/game/g_18_dixie/step/selection_auction.rb
lib/engine/game/g_18_dixie/trains.rb
lib/engine/train.rb

I left this unfinished last November and picked this back up this week, my Ruby is a little rusty
Implement 18Dixie's ICG/SCL merger 
No hacks for this

[18Dixie] ICG/SCL mergers

---

lib/engine/game/g_1841/entities.rb
lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/map.rb
lib/engine/game/g_1841/step/buy_new_tokens.rb
lib/engine/game/g_1841/step/buy_train.rb
lib/engine/game/g_1841/step/choose_option.rb
lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb
lib/engine/game/g_1841/step/home_token.rb
lib/engine/game/g_1841/step/remove_tokens.rb
lib/engine/game/g_1841/step/transform.rb
public/logos/1841/H.svg

This implements the Phase 4 events the Ferdinandea Secession and Tuscan Merge.
No common files needed to be changed.

1841: Ferdinandea Secession and Tuscan Merge

---

assets/app/view/welcome.rb
lib/engine/game/g_1841/meta.rb

1841: take to alpha

---

lib/engine/game/g_1841/map.rb

1841: fix lite map

---

assets/app/view/game/round/auction.rb
lib/engine/game/g_1841/entities.rb
lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/map.rb

Fixes #9332
Fixes #9334
Fixes #9333 
Fixes #9330

1841: More alpha bug fixes

---

lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/step/buy_train.rb
lib/engine/share_pool.rb

Fixes #9340 
Fixes #9338 
This changes share_pool.rb, but it just takes care of a special case that crashed the code anyway.

1841: fix EMR bug; make share_pool more robust

---

assets/app/view/game/buy_token.rb
lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/step/blind_auction.rb
lib/engine/game/g_1841/step/choose_option.rb

Fixes #9342 
Fixes #9343 
common code change: UI::BuyToken - fixed missing '@' on variable name (pretty sure only 41 uses this UI)

1841: fix version 1 player order, rust 5 trains, UI improvments

---

assets/app/view/game/buy_token.rb
assets/app/view/game/part/city_slot.rb

The last UI change (for buy_token) was incomplete. This fixes that.
This also allows "show user colors" to work correctly for subsidiary corporations.

1841: UI fixes

---

lib/engine/game/g_1841/game.rb

Fixes #9362 
Simple fix to roster

1841: add 5 train to non-lite games

---

lib/engine/game/g_1848/step/buy_train.rb

Fixes #9331
I don't think this breaks / requires pinning games since it's a relaxed rules change
Removes logic that constrained cross-buys

[1848] fix cross-buy issue

---

lib/engine/game/g_1841/game.rb

1841: fix problem with starting non-historical minor with Lite map

---

lib/engine/game/g_1841/step/buy_sell_par_shares.rb

1841: fix criteria for buying concessions from the bank

---

lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/step/buy_new_tokens.rb
lib/engine/game/g_1841/step/track.rb

My daily bug fixes for 1841.
Fixes #9373 
Fixes #9372

1841: fix track laying and tuscan merge bugs

---

lib/engine/game/g_1841/game.rb

1841: fix Secession when no single shares of IRSFF

---

lib/engine/game/g_1841/game.rb

1841: Fix EMR liquidity

---

lib/engine/game/g_1841/game.rb
lib/engine/share_pool.rb

1841: deal with pres cert xfer during merger

---

lib/engine/game/g_1841/game.rb

Fixes #9397 
Fixes #9395 
Fixes #9396 
This will most likely require archiving games.

1841: fix issues with post-merger stock prices

---

lib/engine/game/g_1846/game.rb

Fixes #9383
s/value/price since IMO it aligns better w/ the column name referencing "Price"
Some other happy to glad changes

[1846] modify market movements description

---

lib/engine/game/g_1841/game.rb
public/fixtures/1841/132002.json

1841: 2 fixes + fixture

---

lib/engine/game/g_1841/game.rb

1841: handle frozen SFLi during Tuscan Merge

---

lib/engine/game/g_1841/game.rb

Fixes #9427 
Some games will need to be archived.

1841: fix share offer on minor xform

---

lib/engine/game/g_1841/game.rb
lib/engine/game/g_1841/step/remove_tokens.rb

I was reviewing code and found a couple of issues. One was dead code, the other was broken code (but apparently never found live yet).

1841: code cleanup

---

lib/engine/game/g_1841/entities.rb
lib/engine/game/g_1841/game.rb
lib/engine/step/concession_auction.rb

Fixes #9432 
Fixes #9365 
Fixes #9430

1841: fix arithmetic order of operations; fix some cosmetic issues

---

lib/engine/game/g_1841/entities.rb
lib/engine/game/g_1841/map.rb

1841: Fix some name typos

---

lib/engine/game/g_1822/step/minor_acquisition.rb
lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/step/acquisition_track.rb
lib/engine/game/g_1822_ca/step/minor_acquisition.rb
lib/engine/step/tracker.rb

[1822CA] bonus track action after acquiring a minor

---

lib/engine/game/g_1841/game.rb

1841: fix exchange of pres share on transform

---

lib/engine/game/g_1841/game.rb

1841: override priority_deal_player in ORs

---

lib/engine/game/g_1822_africa/meta.rb

1822Africa rules/wiki links

---

lib/engine/game/g_1848/meta.rb

Fixes #9464
Rules linked on the site currently are a pre-final version, which apparently has mistakes. Updated link to the FINAL RULES on GMT's website.

[1848] updates rulebook link to the latest version

---

lib/engine/game/g_1850/game.rb
lib/engine/game/g_1850/step/price_protection.rb

change price when prez sells
Fixes #9041

[1850] fix for price protect

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/round/stock.rb
lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/scenario.rb

* scenarios don't add an extra OR and just have the same conditions as 1822, except they won't end immediately if nothing is sold in SR1
#9376

[1822CA] endgame: like 1822, but in full 1822CA extra OR is possible

---

lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/step/issue_shares.rb

[1822CA] fix issuing shares

---

lib/engine/game/g_18_nl.rb
lib/engine/game/g_18_nl/entities.rb
lib/engine/game/g_18_nl/game.rb
lib/engine/game/g_18_nl/map.rb
lib/engine/game/g_18_nl/meta.rb
lib/engine/game/g_18_nl/step/company_pending_par.rb
lib/engine/game/g_18_nl/step/special_token.rb
lib/engine/game/g_18_nl/step/token.rb
lib/engine/game/g_18_nl/step/waterfall_auction.rb
public/logos/18_nl/AS.svg
public/logos/18_nl/DV.svg
public/logos/18_nl/HIS.svg
public/logos/18_nl/MES.svg
public/logos/18_nl/NCS.svg
public/logos/18_nl/NFL.svg
public/logos/18_nl/NRS.svg
public/logos/18_nl/NZO.svg
public/logos/18_nl/ZHE.svg

Initial commit for 18NL (still pre-alpha)
To do:

[18NL] initial commit

---

lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/step/assign_sawmill.rb

* bonus was not actually adding to revenue
* model after destination bonus code
* fix doubling the bonus with the destination
* display sawmill bonus in string
#9376

[1822CA] fix sawmill bonus

---

lib/engine/game/g_1841/game.rb

Fixes #9462 
Fixes #9474 
Fixes #9471 
Also added some informational messages to the log around token placement during a merger.

1841: Various fixes

---

lib/engine/game/g_1822_africa/game.rb

Playtest change, requires pins, at least for this game that has made it to SR4. https://18xx.games/game/132597

1822Africa - change bidding tokens for 3p/4p

---

lib/engine/game/g_1822_ca/entities.rb
lib/engine/game/g_1822_ca/step/tracker.rb

[1822CA] don't show `consume_tile_lay` abilities after 1 yellow has been laid

---

lib/engine/game/g_1841/game.rb

Fixes #9501 
This will require some archiving

1841: remove rounding on minor merger price

---

lib/engine/game/g_1849_boot/map.rb

1849K2S - Remove hex N18

---

lib/engine/game/g_1822_africa/round/stock.rb

[1822Africa] Only increase loans after SR x.2

---

lib/engine/game/g_1822_africa/game.rb

[1822Africa] Fix game end by max stock value

---

assets/app/view/game/round/merger.rb

Fix kwarg name typo

---

assets/app/view/game/scrap_trains.rb
assets/app/view/game/spreadsheet.rb
lib/engine/game/base.rb

- Only check for bank breaking if its a game end condition
- Add player loans to spreadsheet view
- Allow customization of scrap header text

Framework bug fixes and enhancements

---

assets/app/view/game/buy_trains.rb
lib/engine/game/g_1846/step/buy_train.rb

[1846] Don't allow president contributions when a cheaper Discarded train is available

---

lib/engine/game/g_1822_africa/game.rb

[1822Africa] Don't move sold out corps right

---

lib/engine/game/g_1822_africa/game.rb
lib/engine/game/g_1822_africa/step/minor_acquisition.rb

[1822Africa] Fix acquiring minors from bidboxes

---

assets/app/view/welcome.rb
lib/engine/game/g_1840/meta.rb
lib/engine/game/g_1840/step/selection_auction.rb

1840 fix initial round and 1840 production

---

lib/engine/game/g_1822_africa/entities.rb
lib/engine/game/g_1822_africa/game.rb
lib/engine/game/g_1822_africa/step/buy_train.rb
lib/engine/game/g_1822_africa/step/minor_acquisition.rb

These are bundled in one PR because they introduce conflicts when merged separately.

[1822Africa] Add P6 (Recycled Train) and P17 (Bank Share Buy)

---

lib/engine/game/g_1822_africa/game.rb

1822Africa - Playtest Change - Change market

---

lib/engine/game/g_1822_africa/map.rb

Water tile location adjusted by request of @scottredracecar

[1822Africa] Adjust water tile

---

lib/engine/game/g_1822_africa/game.rb

Fixes the game hanging on routing step

[1822Africa] Fix Gold Mine bonus crashing routing

---

lib/engine/game/g_1868_wy/game.rb

[1868 Wyoming] purple hexes only connect to the corporation stationed there

---

lib/engine/game/g_1868_wy/step/development_token.rb

[1868 Wyoming] allow Bonanza token to be moved

---

lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb

1841: fix for auto actions fix

---

assets/app/view/welcome.rb
lib/engine/game/g_1847_ae/meta.rb

All implementation points are done and I've played it multiplayer twice with no issues.

[1847 AE] Move to alpha

---

lib/engine/game/g_1822_africa/game.rb

Fixes #9599
Switched to using trains initialized on game start to prevent game load breaks

[1822Africa] Fix recycled trains

---

lib/engine/game/g_1841/game.rb

1841: fix emr_can_sell

---

lib/engine/game/g_1822_africa/game.rb
lib/engine/game/g_1822_africa/step/special_choose.rb

[1822Africa] Fix exchange token pricing

---

lib/engine/game/g_1841/game.rb

1841: Fix player_distance_for_president

---

lib/engine/game/g_1868_wy/step/waterfall_auction.rb

[1868WY] close choice companies when the main company is removed in auction

---

assets/app/view/welcome.rb

Very minimal update, just added mention of 1858 being in alpha to the welcome page.

Adds 1858 alpha announcement to the welcome page

---

lib/engine/game/g_1841/step/buy_token.rb
lib/engine/game/g_1841/step/token.rb

1841: Deal with loss of route for train buying

---

lib/engine/game/base.rb
lib/engine/game/g_1844/entities.rb
lib/engine/game/g_1844/game.rb
lib/engine/game/g_1844/map.rb
lib/engine/game/g_1844/step/buy_train.rb
lib/engine/game/g_1844/step/mountain_railway_track.rb
lib/engine/game/g_1844/step/route.rb
lib/engine/game/g_1844/step/special_track.rb
public/icons/1844/T1.svg
public/icons/1844/T2.svg
public/icons/1844/T3.svg
public/icons/1844/T4.svg
public/icons/1844/T5.svg

Also replaced an `any?` with `!empty?` in common code

[1844] More OR functionality

---

lib/engine/game/g_1822_africa/game.rb
lib/engine/game/g_1822_africa/step/special_token.rb
lib/engine/game/g_1822_africa/step/token.rb

[1822Africa] Allow placing Gold Mine if corporation is out of tokens

---

lib/engine/game/g_1822_africa/step/choose_express_train.rb
lib/engine/game/g_1822_africa/step/choose_safari_train.rb
lib/engine/game/g_1822_africa/step/route.rb

[1822Africa] Correctly detach Safari and Express bonuses

---

lib/engine/game/g_18_nl/meta.rb

Somehow I put the wrong rulebook link. Fixed.

Corrects rulebook link

---

lib/engine/game/g_1858/meta.rb

Fixes #9730 
Added new link to bgg for rulebook.

[1858] Update rules link

---

lib/engine/game/g_1841/game.rb

1841: fix typo

---

lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1822_mx/meta.rb

Added for testing optional rule (cert. limits from 1822MRS) that is sometimes played. 
Sanctioned by the designer (@scottredracecar )

[1822MX] Add increased cert. limit optional rule

---

lib/engine/game/g_1822_africa/entities.rb
lib/engine/game/g_1822_africa/game.rb
lib/engine/game/g_1822_africa/step/assign.rb

Fixes #9729
Fixes #9717 
Fixes #9725

[1822Africa] Fix bugs

---

lib/engine/game/g_1841/game.rb

1841: no president shift if merging corp already is president

---

assets/app/view/game/stock_market.rb
lib/engine/game/g_18_zoo/game.rb

Revert "18ZOO - Update StockMarket to show bigger cells when there is any user info in any cell"

---

lib/engine/game/g_1822_ca/game.rb

[1822CA] remove big city upgrade abilities after the city is gray

---

lib/engine/game/g_1844/game.rb

- Make sure SBB shares being transferred are unique
- Do not construct the auction round every time `next_round!` is called.

[1844] Bug fixes

---

lib/engine/game/g_1841/game.rb

1841: avoid closing holding corp

---

assets/app/view/game/stock_market.rb
lib/engine/game/g_18_zoo/game.rb

Revert "18ZOO - Update 2D StockMarket to show bigger cells when there is any user_info in any cell"

---

lib/engine/game/g_1825/game.rb

1825: handle acting_for for closed company correctly

---

lib/engine/game/g_1840/step/dividend.rb

Fixes #9825
Make sure the user has chosen a valid dividend payout amount
I also took the liberty of tweaking the explanation language to hopefully be a bit more clear
before:
after:

[1840] add validity check for chosen dividend

---

lib/engine/game/g_1822_ca/entities.rb
lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca_wrs/game.rb

[1822CA] bugfixes: P16 using tile M8, running trains to sawmill, GNWR home in WRS

---

lib/engine/game/g_1822_mrs/game.rb
lib/engine/game/g_1822_mrs/map.rb

[1822MRS] fix running two trains to English Channel

---

DEVELOPMENT.md

add example for running specific test fixtures

---

lib/engine/game/g_1826.rb
lib/engine/game/g_1826/entities.rb
lib/engine/game/g_1826/game.rb
lib/engine/game/g_1826/map.rb
lib/engine/game/g_1826/meta.rb
public/logos/1826/Al.svg
public/logos/1826/B.svg
public/logos/1826/Est.svg
public/logos/1826/Etat.svg
public/logos/1826/GC.svg
public/logos/1826/Midi.svg
public/logos/1826/N.svg
public/logos/1826/PLM.svg
public/logos/1826/PO.svg
public/logos/1826/Paris.svg
public/logos/1826/SNCF.svg
public/logos/1846/O.svg

Just the base structure, not remotely functional yet. Map, trains, phases, cert limits, starting cash, corps and companies, though some abilities are not fully implemented yet.

[1826] initial commit

---

lib/engine/game/g_1832/meta.rb
lib/engine/game/g_1841/meta.rb
lib/engine/game/g_1850/meta.rb
lib/engine/game/g_18_eu/meta.rb
lib/engine/game/g_18_fl/meta.rb
lib/engine/game/g_18_neb/meta.rb
lib/engine/game/g_18_scan/meta.rb
lib/engine/game/g_18_va/meta.rb

Added Golden Spike Games as the publisher to a handful of games where they weren't credited.

added Golden Spike as publisher for these games.

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/buy_train.rb
lib/engine/game/g_18_mag/step/special_choose.rb

fixed some spelling mistakes in log messages.

spelling corrections in log messages.

---

lib/engine/game/g_1850/game.rb

Removes an unnecessary comment I left in the code as a reminder to myself early in the coding process.

removes an irrelevant comment I left in there

---

.github/ISSUE_TEMPLATE/feature_request.md
README.md
assets/app/view/welcome.rb
lib/engine/game/g_18_mt/meta.rb

update slack link to non-expiring one

---

lib/engine/game/g_1848/step/dividend.rb

Revert "[1848] output BoE revenue history"

---

lib/engine/game/g_1822_ca/entities.rb
lib/engine/game/g_1822_ca/game.rb

#9376
* fix getting partially stuck on track step when a major owns one of the "big city" privates and the corresponding big city is upgraded to gray
* fix infinite loop when computing sawmill bonus
* allow P21 to lay in Y cities

[1822CA] a few small bug fixes

---

lib/engine/game/g_1822_ca/scenario.rb
lib/engine/game/g_1822_mrs/game.rb
lib/engine/game/g_1822_nrs/game.rb

Fix phases init in 1822 scenarios

---

lib/engine/game/base.rb

Fixes #9894, where, in 1846 two consecutive corporations were closed after all of their operating steps were automatically skipped due to insufficient cash to take any actions.
The first corporation (ERIE) was closed correctly, but the second (PRR) was not. In the `action_processed()` logic [[1][1]] to close companies at $0, PRR happens to be checked before ERIE; as part of the process for closing ERIE, PRR starts operating and also has its steps skipped [[2][2]] [[3][3]] and needs to be closed, but since it was already checked for closure it remains open after the step that should have closed it.
The iteration in `action_processed()` could be changed to use operating order, but in cases like this one, since ERIE's price drops before PRR operates, the operating order check would still …

Create a queue of corporations to close to fix consecutive closures

---

lib/engine/game/base.rb
lib/engine/game/g_18_esp/corporation.rb
lib/engine/game/g_18_esp/entities.rb
lib/engine/game/g_18_esp/game.rb
lib/engine/game/g_18_esp/round/operating.rb
lib/engine/game/g_18_esp/step/buy_carriage_or_company.rb
lib/engine/game/g_18_esp/step/buy_sell_par_shares.rb
lib/engine/game/g_18_esp/step/buy_train.rb
lib/engine/game/g_18_esp/step/dividend.rb
lib/engine/game/g_18_esp/step/selection_auction.rb
lib/engine/game/g_18_esp/step/track.rb
lib/engine/game/g_18_esp/step/tracker.rb
lib/engine/game/g_18_ireland/game.rb
lib/engine/route.rb
lib/engine/step/passable_auction.rb
lib/engine/step/tracker.rb
lib/engine/tile.rb

[18ESP] part 1 - privates, tile laying, track, buying tenders

---

lib/engine/game/g_1822_pnw/entities.rb

Fixes #9969
Corrects the spelling of Camas Prairie Railroad

[1822pnw] fix typo

---

lib/engine/game/g_1873/meta.rb

Fixes #9966
Point to BGG page, which seems to be the official AAG post

[1873] fix rules link

---

lib/engine/game/g_1822_ca/game.rb
lib/engine/game/g_1822_ca/step/destination_token.rb
lib/engine/game/g_1822_ca/step/pending_token.rb

[1822CA] fix dest token step, use helper methods over string ids

---

lib/engine/game/g_18_tokaido/game.rb

Update train costs for limited express variant.

[18Tokaido] update train costs for limited express variant

---

lib/engine/game/g_18_esp/game.rb
lib/engine/game/g_18_esp/step/acquire.rb
lib/engine/game/g_18_esp/step/home_token.rb
lib/engine/game/g_18_esp/step/route.rb
lib/engine/game/g_18_esp/step/special_choose.rb
lib/engine/game/g_18_esp/step/track.rb
lib/engine/game/g_18_esp/step/tracker.rb
lib/engine/game/g_18_mag/step/token.rb
lib/engine/step/tokener.rb

[18ESP] mountain passes, mza/mz, major-minor mergers, attaching tenders

---

lib/engine/game/base.rb

I modified `rake stackprof` to run the game 100 times instead of 10 times, and checked these changes against game 143129.
Output from `stackprof stackprof.dump` after `rake stackprof` before and after this change:
Before:
```
TOTAL    (pct)     SAMPLES    (pct)     FRAME
812  (11.9%)         140   (2.0%)     Engine::Game::Base#all_bundles_for_corporation
```
After:
```
TOTAL    (pct)     SAMPLES    (pct)     FRAME
529   (8.6%)         116   (1.9%)     Engine::Game::Base#all_bundles_for_corporation
```

Improve performance of `all_bundles_for_corporation()`

---

lib/engine/game/base.rb

I had added a new case for SELL_AFTER, but I forgot to add a definition for it. Corrected.

added definition for a new function

---

lib/engine/game/g_21_moon/meta.rb

Fixes #9982 
* updates rules link for 21moon
* removes superfluous info from meta.rb file.

update rules link for 21Moon

---

lib/engine/game/g_18_mag/meta.rb

related to #9996
Adds a link to the expansion rules
Clarifies how the 'supporters' work

[18Mag] clarify expansion rules

---

lib/engine/game/g_1825/step/track_and_token.rb

1825: add nil parameter to pay_token_cost call

---

lib/engine/game/g_1868_wy/game.rb

[1868WY] fix $20 charges for overpass tiles

---

lib/engine/game/g_1822_ca/entities.rb
lib/engine/game/g_1822_ca/step/special_track.rb

[1822CA] fix currency symbol in entities config, fix available_hexes for big city upgraders

---

assets/app/view/game/buy_token.rb

1841: clear selected_token after purchase

---

lib/engine/game/g_1832/corporation.rb
lib/engine/game/g_1832/entities.rb
lib/engine/game/g_1832/game.rb
lib/engine/game/g_1832/map.rb
lib/engine/game/g_1832/step/buy_company.rb
lib/engine/game/g_1832/step/track.rb

Corrects several errors in the map and entities pages.
implements code for West Virginia Coal Fields, which is essentially identical to 1850's Mesabi range.
still nowhere near alpha

[1832] corrects several bits of the code and adds some

---

assets/app/view/game/buy_value_input.rb

Harzbahn 1873: fix cross-player mine purchase UI bug

---

assets/app/view/welcome.rb
lib/engine/game/g_1847_ae/meta.rb
lib/engine/game/g_1894/meta.rb

Move 1847 AE and 1894 to beta as there weren't any new issues for several weeks.

Move 1847AE and 1894 to beta

---

lib/engine/game/g_18_eu/step/final_exchange.rb
lib/engine/game/g_18_eu/step/minor_exchange.rb
public/fixtures/18EU/74045.json
public/fixtures/18EU/auto_pass_already_tokened.json

Fixes #8053
* restricts purchase of market shares until all treasury shares are gone
* removes the option to replace the token when exchanged for a market share.
_log text may not match example render_
| Render | Example Log |
| ------ | --------- |
| ![image](https://github.com/tobymao/18xx/assets/5263073/9d9983f9-5f05-4edd-9249-7c85b447b70d)    | treasury share and replace token<br><pre lang="text">[21:58] zieskep exchanges 1 for a 10% share of RBSR&#13;[21:58] RBSR takes £1 from 1 remaining cash&#13;[21:58] RBSR takes 4 train from 1&#13;[21:58] RBSR replaces 1 token on A10&#13;[21:58] 1 closes&#13;</pre>|
| ![image](https://github.com/tobymao/18xx/assets/5263073/06b42f2b-2a3d-46b0-b6a7-787381a24434)   | treasury share and discard …

[18EU] Properly restrict stock exchange to match rules

---

lib/engine/game/g_1866/meta.rb
lib/engine/route.rb

- Added a check to find_matching_chains in lib/engine/route.rb to remove the nil error
- Moved 1866 to Beta
Fixes #10141
Fixes #10144

[1866] Split error and move to beta

---

lib/engine/game/g_1822_ca/entities.rb

Fixes #10179
Clarified descriptions
Added appropriate diacritics

[1822CA] tweak private desc

---

lib/engine/game/g_1866/step/single_item_auction.rb

- Fixed a small bug introduced in last PR
Fixes #10162

[1866] Fixed small par bug

---

assets/app/view/game/combined_trains.rb
assets/app/view/game/round/operating.rb
lib/engine/action/combined_trains.rb
lib/engine/game/g_18_esp/entities.rb
lib/engine/game/g_18_esp/game.rb
lib/engine/game/g_18_esp/map.rb
lib/engine/game/g_18_esp/meta.rb
lib/engine/game/g_18_esp/step/combined_trains.rb
lib/engine/game/g_18_esp/step/home_token.rb
lib/engine/game/g_18_esp/step/track.rb
lib/engine/game/g_18_esp/step/tracker.rb
public/logos/18_esp/AVT.svg
public/logos/18_esp/CA.svg
public/logos/18_esp/CSE.svg
public/logos/18_esp/FDC.svg
public/logos/18_esp/GSSR.svg
public/logos/18_esp/MH.svg
public/logos/18_esp/SFVA.svg

adding more 18esp implementation:
combining trains
more corporations and variable setup

[18esp] variable setup, combined trains

---

lib/engine/game/g_21_moon/entities.rb
lib/engine/game/g_21_moon/game.rb
lib/engine/game/g_21_moon/meta.rb
lib/engine/game/g_21_moon/step/train_mod.rb
public/fixtures/21Moon/148096.json

Fixes #10189 
Fixes #10190 
Removes "prototype" attribute
Adds a fixture

21Moon: fix UN contract; X2,X3 upgrades; add fixture; no longer prototype

---

lib/engine/game/g_18_sj/game.rb

This will require pinning all 18SJ games.
Fixes #10202

[18SJ] fix setup randomization: shuffle each collection

---

lib/engine/game/g_1822_ca/step/assign_sawmill.rb

Fixes #10242
Explain what sawmill does

[1822CA] update sawmill desc

---

lib/engine/game/g_18_ms/entities.rb

Following the lead from #10098
Fixes #9192

[18MS] fix Mobile & Ohio's train discount ability

---

lib/engine/game/g_1846/game.rb
lib/engine/game/g_18_los_angeles/game.rb
lib/engine/game/g_18_los_angeles1/game.rb

Harmonize the language with descriptions from:
https://github.com/tobymao/18xx/pull/10170

[1846] use "bonus" terminology

---

lib/engine/game/g_21_moon/map.rb

21Moon: fix terrain types to place nice with Tunnel Company

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/step/discard_train.rb

Update Discard train. No ships shall end up in bankpool

[18Uruguay] Update Discard train. Only trains shall end up in the bankpool

---

lib/engine/game/g_1822/entities.rb

Add terrain explanation to P8 (Hill Discount) of 1822

---

lib/engine/game/g_system18/game.rb
lib/engine/game/g_system18/map_base_customization.rb
lib/engine/game/g_system18/map_france_customization.rb
lib/engine/game/g_system18/map_neus_customization.rb
lib/engine/game/g_system18/step/buy_train.rb

Scott wanted a "base" map that shows what bits will come in the box - separate from any map packs
This also has playtest fixes and tweaks, including server-based testing.
This is hopefully the last PR before moving to alpha.

System18: add base map, fix playtest bugs

---

lib/engine/round/base.rb
lib/engine/round/stock.rb
lib/engine/token.rb

This was useful while debugging and fixing #10226

Implement `inspect` for some base engine classes

---

lib/engine/game/g_21_moon/game.rb

21Moon: allow TC exchange to occur during presidents SR turn

---

assets/app/view/welcome.rb
lib/engine/game/g_1841/meta.rb
lib/engine/game/g_system18/meta.rb

Takes 1841 to beta and System18 to alpha

1841: To beta; System18: to alpha

---

lib/engine/game/g_18_uruguay/corporations.rb
lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/goods.rb
lib/engine/game/g_18_uruguay/loans.rb
lib/engine/game/g_18_uruguay/nationalization.rb
lib/engine/game/g_18_uruguay/round/nationalization.rb
lib/engine/game/g_18_uruguay/round/operating.rb
lib/engine/game/g_18_uruguay/step/buy_train.rb
lib/engine/game/g_18_uruguay/step/nationalize_corporation.rb
lib/engine/game/g_18_uruguay/step/payoff_loans.rb
lib/engine/game/g_18_uruguay/step/remove_tokens.rb
lib/engine/game/g_18_uruguay/trains.rb

[18Uruguay] Triggering Nationalization
When the second 6 train is bought the nationalization is triggered
The nationalization event is divided into two steps
Step 1
Final Export
RPTLA closes
Private closes
First each corporation will payoff loans as much as they can
Then the president may contribute and payoff loans
Then all corporations that still have loans but not more than limit will get the offer to also be nationalize
Then the two most valuable corporations that still have loans but not more than limit will be merge into FCE
Then all corporations that still have loans but not more than limit will get the offer to also be nationalize
Step 2
FCE will need to choose which tokens and trains to keep

[18Uruguay] Triggering Nationalization

---

lib/engine/game/g_18_uruguay/map.rb

[18Uruguay] Added England group to blue

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/step/track.rb

Adding support to take loan while laying track

[18Uruguay] Adding support to take loan while laying track

---

lib/engine/game/g_18_uruguay/step/dividend.rb

Automatically repay loans after nationalization

[18Uruguay] Automatically repay loans after nationalization

---

lib/engine/game/g_18_uruguay/step/payoff_loans.rb

[18Uruguay] Don not show pay off if you do not have the cash

---

lib/engine/game/g_18_uruguay/corporations.rb

[18Uruguay] FCE token value should be 100

[18Uruguay] FCE token value should be 100

---

lib/engine/game/g_18_uruguay/loans.rb

[18Uruguay] Interest rate should be 0 after nationalization
Interest rate should be 0 after nationalization

[18Uruguay] Interest rate should be 0 after nationalization

---

lib/engine/game/g_18_uruguay/step/token.rb
lib/engine/game/g_18_uruguay/step/track.rb

[18Uruguay] Corrected addtional loan action in token and track
The base action needs to be copied since it is frozen

[18Uruguay] Corrected addtional loan action in token and track

---

lib/engine/game/g_18_uruguay/step/dividend.rb

[18Uruguay] New RPTLA share price handling
The share price of RPTLA shall not move until phase 3

[18Uruguay] New RPTLA share price handling

---

lib/engine/game/g_1822_ca/game.rb

[1822CA] fix sawmill bonus with E-trains

---

lib/engine/game/g_18_mt/companies.rb

Fixes #10317 (and other games w/ train discount)
ref: https://github.com/tobymao/18xx/pull/10098#issuecomment-1880205008
`s/buying_trains/buy_trains`
May need pins, would want to run against the DB to check

[18MT] fix train discount ability timing

---

lib/engine/game/g_18_gb/game.rb

Fixes #9869 
Instead of aggressively combining all of a corporation's train routes into as few "route sets" (connected networks) as possible and then checking this for compass-direction route bonuses, instead:
- Calculate all the possible sets of overlapping routes (in practice, this is not much extra work: we iterate just once through the routes and get just 1-6 combos in most cases [corporations with 3 or fewer trains])
- Select the one of these that pays the maximum possible NS/EW bonus
- Where multiple possibilities produce the same total amount of 'compass point bonuses', we prefer the combination which keeps trains as separate as possible. (This will help avoid some unclear situations from before where a corporation which had all of its trains in a single connected network sometimes …

18GB: Better handle different route combos for NS/EW bonus

---

.github/PULL_REQUEST_TEMPLATE.md

having the subheaders of "Implementation Notes" be a bulleted list makes it awkard to put a bulleted list in any of the subsections IMO

change section headers on PR template

---

lib/engine/game/g_system18/map_france_customization.rb
lib/engine/game/g_system18/map_neus_customization.rb

Fixes #10385 
Some games will require archiving.

System18: NEUS map and playtest fixes; Franch map tile renumbering

---

lib/engine/game/g_18_sj/entities.rb

[18SJ] fix P7 (Nydqvist och Holm AB) power

---

lib/engine/game/g_18_royal_gorge/entities.rb
lib/engine/game/g_18_royal_gorge/game.rb
lib/engine/game/g_18_royal_gorge/step/bridge_lease.rb
lib/engine/game/g_18_royal_gorge/step/route.rb

Can run a train through the Royal Gorge, if 10% of the company's total dividend is paid to RG.
#10110

[18RoyalGorge] implement private G3 Hanging Bridge Lease

---

public/fixtures/21Moon/151934.json

Adding fixture back for 21Moon

21Moon: add new fixture

---

lib/engine/game/g_system18/map_twisting_tracks_customization.rb

No active games currently, thus nothing to archive.

System18 Twisting Tracks - Fix starting cash

---

lib/engine/game/g_18_royal_gorge/entities.rb
lib/engine/game/g_18_royal_gorge/step/track.rb

[18RoyalGorge] more info about gold and steel companies via abilities

---

lib/engine/game/g_18_royal_gorge/game.rb

[18RoyalGorge] route_distance_str: show visited towns after `+`

---

lib/engine/corporation.rb
lib/engine/game/base.rb
lib/engine/game/g_1870/game.rb
lib/engine/game/g_18_neb/game.rb
lib/engine/game/g_18_neb/step/buy_sell_par_shares.rb
lib/engine/share_pool.rb
lib/engine/step/share_buying.rb

Includes core code changes to:
1. Update logic used with corporation share buying constants to match what the constants are called
2. DRY'd up use of those constants
Ran against the DB and all looked good.

[18Neb] Redeem shares from players

---

assets/app/view/game/track_conversion.rb

18Carolinas: Fix rendering issue with track conversion

---

assets/app/mail/turn.rb

Reverts tobymao/18xx#10479
Testing to see if this fixes mail sending / rendering on prod

Revert "Removing last backtick warning"

---

lib/engine/game/g_21_moon/entities.rb
lib/engine/game/g_21_moon/game.rb

Temporarily reverting so 21Moon breaking changes can all come in together.

Revert "[21Moon] fix terminal tile placement"

---

lib/engine/game/g_1841/game.rb

1841: use proper distance method for deferred president changes

---

lib/engine/game/g_18_nl/step/track.rb
public/fixtures/18NL/18NL_NZO_hex.json

Fixes #10614
Fixes constant reference
Added test case
AFAIK shouldn't require pins since games would have errored at that step before continuing
The linked issue was triggered due to OR beginning and track step erroring out

[18NL] fix constant reference bug

---

assets/app/view/game/auto.rb
assets/app/view/game/auto_action/buy_shares.rb
assets/app/view/game/auto_action/share_pass.rb

modify text on Auto page to make it a bit more clear / less verbose

tweak copy on auto page

---

assets/app/view/welcome.rb
lib/engine/game/g_18_hiawatha/meta.rb

[18Hiawatha] to alpha

---

lib/engine/game/g_steam_over_holland/game.rb
lib/engine/game/g_steam_over_holland/step/buy_sell_par_shares.rb

- Added code to track the required shares to float based on phase to /game.rb
- Added code to force bundle purchase of all shares needed to float simultaneously to /step/BuySellParShares

[SteamOverHolland] bundle buy shares when parring

---

lib/engine/game/g_steam_over_holland/entities.rb
lib/engine/game/g_steam_over_holland/game.rb

First commit fixes p5 ability
second commit adds second tile lay, trains don't count towns against distance, can't end run on a town, can't visit different cities on the same hex.

[SteamOverHolland] updates

---

.github/CODEOWNERS
assets/app/view/about.rb

Added myself to the CODEOWNERS page for the games I've done, and added my name to the list of contributors.

[info] adding myself to CODEOWNERS and the about page

---

lib/engine/game/g_21_moon/entities.rb

Fixes #10551
recreation so can redeploy all at once
https://github.com/tobymao/18xx/pull/10559

[21Moon] Terminal private revenue s.b. 15 space bucks

---

lib/engine/game/g_21_moon/entities.rb
lib/engine/game/g_21_moon/game.rb

fixes #10547
recreation so can redeploy all at once
https://github.com/tobymao/18xx/pull/10558

[21Moon] fix terminal hex placement

---

lib/engine/game/g_21_moon/game.rb

21Moon: fix space port upgrade broken by tile renumbering

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/phases.rb
lib/engine/game/g_18_uruguay/step/buy_sell_par_shares.rb

[18Uruguay] No RLPTA stock before phase 3

[18Uruguay] No RLPTA stock before phase 3

---

lib/engine/game/g_18_esp/entities.rb

[18ESP] update face value of P1 and P2

---

assets/app/view/welcome.rb
lib/engine/game/g_18_royal_gorge/meta.rb

18RoyalGorge to alpha

---

lib/engine/game/g_18_uruguay/companies.rb
lib/engine/game/g_18_uruguay/corporations.rb

[18Uruguay] Updated the president share to 30% for RPTLA
This change can break existing games

[18Uruguay] Updated the president share to 30% for RPTLA

---

lib/engine/game/g_18_nl/entities.rb

Fixes #10701 
Fixes description of P6 company.

[18NL] fixes P6 company description

---

lib/engine/game/g_18_royal_gorge/game.rb
lib/engine/game/g_18_royal_gorge/share_pool.rb

Fixes #10698
Also fixes issue where the steel and gold companies have messages logged about receivership and presidents

[18RoyalGorge] fix string/sym and logging issues

---

lib/engine/game/g_18_norway/meta.rb

[18Norway] Adding link to rules

[18Norway] Adding link to rules

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/dividend.rb

[18Norway] Update dividend rules

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/build_tunnel.rb
lib/engine/game/g_18_norway/steps/track.rb

[18Norway] Adding support for tunnel building and maintainance cost for trains running over mountains

[18Norway] Adding support for tunnel building

---

lib/engine/game/g_18_royal_gorge/entities.rb
lib/engine/game/g_18_royal_gorge/game.rb
lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
lib/engine/game/g_18_royal_gorge/step/buy_train.rb
lib/engine/game/g_18_royal_gorge/trains.rb

* fix mint worker passing nil to share bundle, fixes #10745
* fix nil error after all trains have been bought, fixes #10757
* close most private companies on 5+ train, fixes #10756

[18RoyalGorge] more fixes

---

lib/engine/game/g_18_norway/corporations.rb

[18Norway] D has 10% train discount

---

lib/engine/game/g_18_hiawatha/step/loan.rb

Fixes #10774
changed `paid all off all loans' to 'has paid off all loans'

[18Hiawatha] fixes typo in loan log message

---

lib/engine/game/g_18_hiawatha/meta.rb

[18 Hiawatha] adds official rules link

---

lib/engine/game/g_18_gb/game.rb

Add usual price movement chart to Market page

[18GB] Add share price movement chart

---

lib/engine/game/g_18_uruguay/map.rb

[18Uruguay] Corrected maps and tiles

[18Uruguay] Corrected maps and tiles

---

lib/engine/game/g_18_uruguay/trains.rb

[18Uruguay] 7 trains shall be able to run to 7 destinations

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/nationalization.rb
lib/engine/game/g_18_uruguay/round/stock.rb

[18Uruguay] Updated Stock movement

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/step/token.rb
lib/engine/game/g_18_uruguay/step/track.rb

[18Uruguay] No action on last run

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/build_tunnel.rb
lib/engine/game/g_18_norway/steps/track.rb

[18Norway] S may lay two yellow tracks

---

lib/engine/ability/blocks_hexes.rb
lib/engine/ability/blocks_hexes_consent.rb
lib/engine/game/base.rb
lib/engine/game/g_1822/step/pending_token.rb
lib/engine/game/g_18_gb/game.rb
lib/engine/tile.rb
spec/game_state_spec.rb

`blocks_hexes` and `blocks_hexes_consent` hex block automatically removed when ability is torn down.

[18Neb, Core] Remove hex blockers when ability torn down

---

lib/engine/game/g_1880/game.rb
lib/engine/game/g_1880/step/check_fi_connection.rb
public/fixtures/1880/1.json
scripts/migrate_1880.rb

[1880] Corp chooses FI token replacement and factor communism into player value

---

lib/engine/game/g_18_usa/step/buy_train.rb

[18USA] Do not auto pass train buying step if in the middle of a rusting event

---

lib/engine/game/g_18_uruguay/step/nationalize_corporation.rb
lib/engine/game/g_18_uruguay/step/payoff_loans.rb
lib/engine/game/g_18_uruguay/step/remove_tokens.rb
lib/engine/game/g_18_uruguay/step/take_loan_buy_company.rb

[18Uruguay] Updated skip log messages

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/route.rb

[18Norway] Ø may pass tokened out city

---

lib/engine/game/g_18_norway/game.rb

[18Norway] Set par price for H

---

assets/app/view/game/company.rb
lib/engine/game/base.rb
lib/engine/game/g_1846/game.rb

[1846] don't show company owner during draft

---

lib/engine/game/g_1822_pnw/step/merge.rb

[1822PNW] show total value of merging minors when selecting par price

---

lib/engine/game/g_18_royal_gorge/game.rb

[18RoyalGorge] Fix B2 Sulphur Springs's revenue increasing before brown

---

lib/engine/game/g_18_norway/game.rb

[18Norway] Add mail contract

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/trains.rb

[18Norway] Add support to drive through Mjøsa

---

lib/engine/game/g_1850/game.rb
lib/engine/game/g_1850/meta.rb

Implements reduced tokens variant from rulebook. 
rulebook text:

[1850] Implements reduced tokens variant

---

lib/engine/game/g_1822_ca_ers/entities.rb

[1822CA ERS] fix NTR and CPR concession descriptions

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_pnw/game.rb
lib/engine/game/g_1822_pnw/meta.rb
lib/engine/game/g_1822_pnw_short.rb
lib/engine/game/g_1822_pnw_short/game.rb
lib/engine/game/g_1822_pnw_short/meta.rb
lib/engine/game/g_1822_pnw_short/trains.rb
lib/engine/game/g_1822_pnw_srs.rb
lib/engine/game/g_1822_pnw_srs/game.rb
lib/engine/game/g_1822_pnw_srs/meta.rb
lib/engine/game/g_1822_pnw_srs/trains.rb

* Short Scenario
* Southern Regional Scenario
* Starting Packet Variant

[1822PNW] scenarios and starting packet variant

---

scripts/import_game.rb

[import_game.rb] remove @ from user names, fix nil/integer comparison

---

lib/engine/game/base.rb
lib/engine/game/g_1822_mx/step/buy_sell_par_shares.rb

[1822MX] include NdeM shares in liquidity calculation

---

lib/engine/game/g_1822_mx/game.rb

[1822MX] set priority player as NdeM's acting entity on other turns

---

lib/engine/game/g_1822_pnw/step/buy_sell_par_shares.rb
lib/engine/game/g_1822_pnw/step/conversion.rb

[1822PNW] stop requiring cash on hand to convert an associated minor to a major

---

lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_mx/game.rb
lib/engine/game/g_1822_pnw/game.rb

[1822,1822CA] always include tax haven value in player value

---

lib/engine/game/g_1822/entities.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822_africa/entities.rb
lib/engine/game/g_1822_ca/entities.rb
lib/engine/game/g_1822_ca/scenario.rb
lib/engine/game/g_1822_mx/entities.rb
lib/engine/game/g_1822_nrs/game.rb
lib/engine/game/g_1822_pnw/entities.rb

As suggested at https://github.com/tobymao/18xx/pull/10904#issuecomment-2159731880

[1822 family] generalize setting the 1822 company colors

---

lib/engine/game/g_1822/game.rb

[1822] require two tokened cities to submit an E-train route

---

assets/app/view/game/round/stock.rb
lib/engine/action/payoff_player_debt_partial.rb
lib/engine/game/g_1822/game.rb
lib/engine/game/g_1822/step/buy_sell_par_shares.rb

[1822] allow player loans to be partially paid off

---

lib/engine/game/g_system18/game.rb
lib/engine/game/g_system18/map_twisting_tracks_customization.rb

Add 2P 70% stock limit
Fix prices for Twisting Tracks trains

System18: more rule changes

---

assets/app/view/create_game.rb

Fixes #10937
- [nah] Add the `pins` or `archive_alpha_games` label if this change will break existing games
I didn't reset max_players correctly 
https://github.com/tobymao/18xx/pull/9250

set an upper bound on max players input box

---

lib/engine/game/g_1822_ca/step/destination_token.rb

Closes #10956, but a lot of that issue is caused by #10331.

[1822CA] don't recompute `destination_node_check?`

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/dividend.rb
lib/engine/game/g_18_norway/steps/issue_shares.rb

[18Norway] Issue/redeem shares

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/buy_train.rb

[18Norway] Ignore mandatory trains for B

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/buy_train.rb

[18Norway] Adding free ship to V

---

lib/engine/game/g_18_norway/steps/route.rb

[18Norway] Pay the fee

---

lib/engine/game/g_1822_pnw_short/game.rb
lib/engine/game/g_1822_pnw_short/meta.rb
lib/engine/game/g_1822_pnw_short/round/stock.rb
lib/engine/game/g_1822_pnw_srs/meta.rb

Fixes #10983
archives needed if anyone started a game and kept playing after the paired minor didn't float

[1822PNW Short] fix floating the paired minor in bidbox 1

---

lib/engine/game/g_1822_ca/step/destination_token.rb

Redoes #10957
Partially fixes #10956

[1822CA] don't recompute `destination_node_check?`, fix cached return

---

lib/engine/game/g_1841/step/buy_train.rb

Fixes #10949 
One or two games may require pinning.

1841: deal with discard in bank on forced purchase

---

lib/engine/game/g_18_norway/map.rb
lib/engine/game/g_18_norway/trains.rb

[18Norway] New updates from the designers

---

lib/engine/game/g_18_norway/game.rb

[18Norway] Add ability for H

---

lib/engine/game/g_18_norway/steps/buy_train.rb

[18Norway] allow for owner sell_shares

---

lib/engine/game/g_18_norway/corporations.rb

[18Norway] Corporations shall always have market values

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/map.rb
lib/engine/game/g_18_norway/phases.rb
lib/engine/game/g_18_norway/trains.rb

[18Norway] Update nationalization phase

---

lib/engine/game/g_18_norway/steps/build_tunnel.rb

[18Norway] Handle when P3 is closed

---

lib/engine/game/g_18_norway/game.rb

[18Norway] No sales during first SR, then p_any_operational

---

lib/engine/game/g_18_uruguay/game.rb
lib/engine/game/g_18_uruguay/meta.rb

Change status to Alpha
Also updated
Corrected port it should be J14 and not J4
RPTLA should operate last

[18Uruguay] Change to Alpha

---

lib/engine/game/g_18_norway/game.rb

[18Norway] Companies should be restartable after close

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/nationalize_corporation.rb

[18Norway] Update cert limit

---

lib/engine/game/g_1822_pnw_short/game.rb
lib/engine/game/g_1822_pnw_short/trains.rb
lib/engine/game/g_1822_pnw_srs/game.rb
lib/engine/game/g_1822_pnw_srs/trains.rb

Fixes #10994
Fixes #10999
Fixes #11003

[1822PNW scenarios] fix M21 in SRS, fix P+ trains

---

lib/engine/game/g_1822/game.rb

The problem is the company's `@value` is modified in `company_status_str` ([here](https://github.com/tobymao/18xx/blob/3abd348/lib/engine/game/g_1822/game.rb#L693)), which is only called in certain cases for the UI.
This change doesn't fix that issue, but works around it, by subtracting the company's `@value`, whatever it may be, before adding in the true value.
Fixes #11007
Originally reported in #5200, which was closed by #10912

[1822/CA] fix tax haven value

---

lib/engine/game/g_1822/game.rb

[1822/MX] track rights around London/Mexico City only apply for yellow tiles

---

lib/engine/game/g_system18/game.rb
lib/engine/game/g_system18/map_poland_customization.rb

Fixes #11034 
Fixes #10992 
Display issues only. No games need to be archived.

s18: fix display issues

---

assets/app/view/create_game.rb

show number of titles matching keyword search on create game page

---

lib/engine/game/g_1870/game.rb
lib/engine/game/g_1870/meta.rb
lib/engine/game/g_1870/step/buy_sell_par_shares.rb
lib/engine/game/g_1870/step/price_protection.rb

Fixes #11006 
This pull request is implementing a few changes at once, all based on Bill Dixon's original rules for the game. A summary of the differences can be found [here](https://web.archive.org/web/20110409211332/http://www3.telus.net/wrdixon/1870html/1870dif.html), and the full rules are available [here](https://web.archive.org/web/20201111210240/http://www3.telus.net/wrdixon/1870html/1870toc.html).
The first change is the game originally supported 7 players. Since this doesn't really impact anything, I simply changed the main code to allow for 7 players. The cert limits and player money for 7 players is detailed in the rules. 
The next few changes are all configured as optional rules and are as follows:
- Original price protection: Dixon originally always intended for the president …

1870 original rules (as optional rules)

---

lib/engine/game/g_18_india/meta.rb

[18India] add wiki link

---

lib/engine/game/g_22_mars/company.rb
lib/engine/game/g_22_mars/entities.rb
lib/engine/game/g_22_mars/game.rb
lib/engine/game/g_22_mars/map.rb
lib/engine/game/g_22_mars/step/dividend.rb
public/logos/22Mars/IG.svg
public/logos/22Mars/MS.svg
public/logos/22Mars/NWC.svg
public/logos/22Mars/PL.svg
public/logos/22Mars/REX.svg
public/logos/22Mars/SMC.svg
public/logos/22Mars/SRC.svg
public/logos/22Mars/TRE.svg

This is part of 22Mars implementation (checklist #11021). 
Added game entities and basic configuration

[22Mars] Add entities and basic game rules 

---

lib/engine/game/g_18_india/entities.rb

Fixes #11153
Corrects spelling of Bengal Nagpur Railway (misspelled as Nagur)

[18 India] corrects spelling of Bengal Nagpur Railway

---

lib/engine/game/g_18_esp/step/company_pending_par.rb

very minor fix, method is missing ? causing failures after auction

[18esp] very minor fix, method is missing ?

---

lib/engine/game/g_1849/step/bond.rb

removed an unnecessary condition that I copied from 1856 code. 
This may resolve the refreshing loop issue, but I've been unable to reproduce the issue locally to confirm.

[1849] correction to Bond variant code

---

lib/engine/game/g_18_esp/game.rb

[18esp] fix hex_by_id bug

---

lib/engine/game/g_18_uruguay/step/dividend.rb

[18Uruguay] Attempt to solve the dividend_types bug

---

lib/engine/game/g_18_hiawatha/meta.rb

Looks like the prior link was deprecated and this is the canonical one
Fixes #11211

[18Hiawatha] Fix rules link

---

lib/engine/game/g_18_uruguay/step/buy_sell_par_shares.rb

[18Uruguay] Allow more than 60% to cover for loans

---

lib/engine/game/g_1850_jr/meta.rb

[1850jr] move to beta

---

lib/engine/game/g_18_carolinas/game.rb

Fixes #11292 
There is a chance that some games would need to be pinned.

18Carolinas: fix power on corp restart

---

lib/engine/game/g_18_uruguay/map.rb

New updated tile sheet from the Designer
I cannot add pins but this change might break existing games

[18Uruguay] New updated tile sheet from designer

---

lib/engine/game/g_1871/meta.rb

Fixes #11298 
Updated wikilink for TOP 1871 to https://github.com/tobymao/18xx/wiki/The-Old-Prince-1871

[1871] fixes wiki link for game

---

assets/app/view/welcome.rb
lib/engine/game/g_18_royal_gorge/game.rb
lib/engine/game/g_18_royal_gorge/meta.rb
lib/engine/publisher.rb

[18RoyalGorge] fix gold miner paying for CF&I, add kickstarter and publisher, move to beta

---

assets/app/view/welcome.rb
lib/engine/game/g_1858_switzerland/meta.rb

Move 1858 Switzerland to alpha release status.

[1858 Switzerland] Move to alpha release status

---

lib/engine/game/g_1822_africa/game.rb

1822Africa: Route express trains separately

---

lib/engine/game/g_18_texas/map.rb

Fixes #11351
Updates game map to match the physical production

[18Texas] update map to match physical game

---

lib/engine/part/city.rb

Very minor update. At some point, the name "Bull tokens" was changed to "extra tokens" but the comment above it still referenced bull tokens. Fixed.

Corrects comment about Extra tokens

---

lib/engine/game/g_1837/game.rb
lib/engine/game/g_1837/map.rb
lib/engine/game/g_1837/step/track.rb

[1837] Treat Vienna as one city, return KK/UG tokens when Vienna/Budapest upgraded to brown

---

lib/engine/game/g_18_norway/trains.rb

[18Norway] S5 shall have 5 stops

---

lib/engine/game/g_18_india/map.rb

Fixes #11395
Corrects tile IF1
Presumably we'll need to pin or archive any games that used that tile.

[18india] Fixes tile IF1

---

lib/engine/game/g_18_norway/game.rb

It shall be allowed to buy privets to up to 1.5X

[18Norway] Setup privates for 1.5X

---

lib/engine/game/g_1807/game.rb
lib/engine/game/g_1807/map.rb

One fix: the underground railway privates were not being made available due to misuse of the `Array.delete` method (it does not take a block, and does not return the deleted item).
Also, use the hex cache and find hexes using the `hex_by_id` method instead of `@hexes.find`.

[1807] Minor fixes and improvements

---

lib/engine/game/g_system18/game.rb

Fixes #11412 
Fixes #11334 
This will require archiving some games.

S18: 1D market fixes

---

lib/engine/game/g_1837/map.rb

[1837] change value of J16 to 30, fixes #11474

---

assets/app/view/welcome.rb

Announce the Kickstarter for 1807: The Big Four.
Fixes #11549.

[1807] Add Kickstarter announcement to front page

---

assets/app/view/welcome.rb
lib/engine/game/g_18_ardennes/meta.rb

18Ardennes was released in alpha status more than five months ago, and there have been over a hundred games completed on the site. There has only been a single of bug found with the code (#11203) and there was one rule that I had missed that needed to be added (#11221). No problems have been found in more than three months, so the code seems to be in good enough shape to move this to beta status.
There are a couple of enhancement request issues open (#11187, #11367), for suggested interface improvements. These might be address later.

[18Ardennes] Move to beta status

---

lib/engine/game/g_1837/game.rb

[1837] Fix plus trains to consume town only distance first

---

lib/engine/game/g_18_norway/game.rb

Corrected the minimum price reqiured for privates

[18Norway] Corrected the minimum price reqiured for privates

---

lib/engine/game/g_18_esp/game.rb

fix mza being placed as cheater when slot is available
fix train discard allowing 2P

[18ESP] Fix more minor 18esp issues

---

assets/app/view/welcome.rb
lib/engine/game/g_18_esp/meta.rb

[18esp] undo beta move

---

lib/engine/game/g_18_norway/depot.rb
lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/buy_train.rb

[18Norway] You are only allowed to buy the cheapest train during emergency

---

lib/engine/game/g_18_norway/game.rb

Also move oslo id after map update

[18Norway] Also update Oslo hex after new map

---

lib/engine/game/g_system18/map_uk_limited_customization.rb

Fixes #11636 
I doubt archiving will be needed.

S18: Fix for UK Limited rusting

---

assets/app/view/welcome.rb

This Kickstarter campaign has finished.

Remove 1807 Kickstarter from the front page

---

lib/engine/game/g_18_norway/map.rb

Correcte minor map issue in Kristiansand

[18Norway] Correcte minor map issue in Kristiansand

---

lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb

Fixes #11660 
This may affect a small number of 21Moon games and require pins.

21Moon: CR issue price drop fix

---

lib/engine/game/g_18_uruguay/meta.rb

[18Uruguay] Dev stage beta

---

assets/app/view/game/bank.rb
lib/engine/game/g_18_esp/game.rb

fix mza bug when brown
add bank info on tenders, fix bug where there one less tender in bank

[18ESP] more bug fixes + add bank card custom info

---

lib/engine/game/g_18_norway/meta.rb

We need before this can be merged
[18Norway] Reimplement that you only are allowed to have one ship per type #11640

[18Norway] Dev stage alpha

---

lib/engine/game/g_18_india/meta.rb

Rulebook link currently links to a draft document. This updates the link to the official GMT rulebook

[18India] updates rulebook link

---

lib/engine/game/g_18_india/game.rb
lib/engine/game/g_18_india/step/certificate_selection.rb
lib/engine/game/g_18_india/step/corporate_buy_shares_company.rb
lib/engine/game/g_18_india/step/dividend.rb
lib/engine/game/g_18_india/step/exchange_token.rb
lib/engine/game/g_18_india/step/gauge_change_border.rb
lib/engine/game/g_18_india/step/home_track.rb
lib/engine/game/g_18_india/step/railhead_tracker.rb
lib/engine/game/g_18_india/step/sell_once_then_buy_certs.rb
lib/engine/game/g_18_india/step/track.rb

There were a lot of debugging lines left in the code for 18 India. This strips it away. 
From what I can tell, nothing breaks by doing this.

[18India] removes leftover debug code

---

lib/engine/game/g_1858_india/entities.rb
lib/engine/game/g_1858_india/game.rb
lib/engine/game/g_1858_india/step/buy_train.rb

This adds locomotive works private companies. These can be bought by a public company during the train-buying step from phase 4 onwards. They give a 10% discount on all future train purchases by the public company.

[1858 India] Locomotive works privates

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/steps/buy_sell_par_shares.rb
spec/lib/engine/games/g_18_norway/g_18_norway_share_selling_spec.rb

[18Norway] Don't allow selling president's share to NSB

---

lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/round/nationalization.rb
lib/engine/game/g_18_norway/steps/nationalize_corporation.rb
public/fixtures/18Norway/18_norway_buy_ship.json

Fixes #11732
Will break existing games

[18Norway] Nationalization rounds should not pay out companies

---

lib/engine/game/g_18_norway/map.rb

[18Norway] Fix typo in Jotunheimen

---

lib/engine/game/g_18_norway/game.rb

Fixes #11746
Part 2
- [X}  Tests pass cleanly with `docker compose exec rack rake`

[18Norway] Updated autoroute

---

lib/engine/game/g_system18/game.rb
lib/engine/game/g_system18/map_britain_customization.rb

Fixes #11840 
Fixes #11842 
No pinning/archiving needed.

[System18] Britain split map fixes

---

Rakefile
scripts/import_game.rb

`docker compose exec rack bundle exec rake fixture_import[<game_id>]`
also, `import_game()` will now throw a useful error if the requested game does not exist

[dev] add Rake task to import fixture from local or prod DB game

---

lib/engine/game/g_system18/map_northern_italy_customization.rb
lib/engine/game/g_system18/map_poland_customization.rb
lib/engine/game/g_system18/map_scotland_customization.rb
lib/engine/game/g_system18/step/charter_auction.rb
lib/engine/game/g_system18/step/order_auction.rb
lib/engine/game/g_system18/step/upwards_auction.rb

Fixes #11947 
Fixes #11950 
Also fix mutation issue with Poland and Northern Italy maps that should have been fixed with my other mutation fix (in NEUS map).
Will require pinning MS and Scotland maps.

[System 18] Scotland rule updates; Upward auction rule updates

---

lib/engine/game/g_18_norway/companies.rb
lib/engine/game/g_18_norway/game.rb
lib/engine/game/g_18_norway/meta.rb
lib/engine/game/g_18_norway/steps/build_tunnel.rb
lib/engine/game/g_18_norway/steps/buy_train.rb
public/fixtures/18Norway/18_norway_buy_ship.json

Added a few new privates from the authors

[18Norway] new privates

---

lib/engine/game/g_1862_solo/game.rb

[1862 Solo] stop mutating parent class's CORPORATIONS

---

scripts/validate.rb

instead of taking a list of families, make it boolean; by default, validate the whole family for every title given to `validate_all()`. This will ensure things like `1824 Cisleithania` are validated when `1824` is given without relying on the memory of the human running the script.

[dev] validate script: change how `families` kwarg works

---

.github/CODEOWNERS

Adding myself to CODEOWNERS for System18

[System18] Add roseundy to CODEOWNERS

---

assets/app/view/create_game.rb

broken by #12037
this review benefits from [hiding whitespace changes](https://github.com/tobymao/18xx/pull/12111/files?diff=split&w=1)

fix importing JSON as hotseat game
