- Gemfile
- Gemfile.lock
- assets/js/view/part/base.rb
- assets/js/view/part/revenue.rb
- assets/js/view/part/town_dot.rb
- assets/js/view/part/town_rect.rb
- assets/js/view/part/towns.rb
- assets/js/view/part/track.rb
- assets/js/view/part/track_curvilinear_half_path.rb
- assets/js/view/part/track_curvilinear_path.rb
- assets/js/view/tile.rb
- lib/engine/tile.rb
- spec/lib/engine/tile_spec.rb
55, 56, and 69 don't look right, but also aren't in 1889. For those we'd need to calculate a different spot on the curve for where to put the town. Right now it's in the exact midpoint, and those three tiles have track crossings at or near the midpoint.
> render yellow town tiles as curvilinear

- assets/js/view/company.rb
- assets/js/view/create_game.rb
- config/1889.json
- lib/engine/game/g_1889.rb
Add a bunch of styles to make the privates look good
Private bidders are now stacked in price order, top to bottom
Make the Player +/- buttons cap at 1889's actual player count
Add proper descriptions for the privates
> Make Privates Prettier

- routes/game.rb
- routes/user.rb
Increasing documentation in the two routes files.
Figured, gotta start somewhere.
> Document routes

- assets/js/view/stock_round.rb
- lib/engine/player.rb
I don't have a lot of faith that this code is idiomatic but it does induce the correct behavior. Improvements welcome.
> Deselect corporation when player changes, fixes #66

- lib/engine/round/stock.rb
> Log when player is autopassed during stock round

- .dockerignore
- .gitignore
- README.md
- db/Dockerfile
- db/postgresql.conf
- docker-compose.yml
- nginx/conf.d/18xx.conf
- postgres data volume is now the host's `./db/data/` (requires that dir to be present when starting the stack, so `mkdir db/data/` to initialize it, or copy the existing data there)
- postgres and nginx containers both write log files to subdirs of `log/` on the host
- after `docker-compose up`, the app is reachable at http://localhost, no need to add a port
I do want to add something more robust to keep `rack` and `nginx` from starting until the `db` is ready (https://docs.docker.com/compose/startup-order/), but perfect is the enemy of the good enough, so that can be delayed instead of holding up the other changes that are ready to go.
> Add nginx, change some postgres config

- assets/js/view/stock_market.rb
Muted colors a bit (especially the red), and reduced font size a little to make more room for tokens and to be less obtrusive.
> Stock market view improvements (colors, font size)

- assets/js/view/stock_round.rb
Add a little space, format as currency
> Improve presentation of par price choice

- assets/js/view/create_game.rb
- assets/js/view/stock_round.rb
- assets/js/view/welcome.rb
- lib/engine/game/g_1889.rb
- Use "IPO" everywhere
- "Hotseat" instead of "Solo"
- Give longer names to default players in hotseat mode
> Wording tweaks

- assets/js/view/game.rb
- assets/js/view/train_roster.rb
- lib/engine/train/depot.rb
Addresses #43.
I would like to add more info, as is found in the per-title data from the JSON file, but we don't appear to read the train data from that file yet, so for now this is pretty bare-bones (both in data and in presentation).
> Train roster tab

- assets/js/view/player.rb
- lib/engine/game/base.rb
- lib/engine/player.rb
- lib/engine/round/stock.rb
- lib/engine/share_price.rb
- lib/engine/stock_market.rb
- spec/lib/engine/player_spec.rb
- spec/lib/engine/share_pool_spec.rb
- spec/lib/engine/stock_market_spec.rb
> Player::cert_limit, counts privates but not yellow/etc shares

- lib/engine/game/g_1889.rb
Fixed a typo and added a couple of currency symbols.
> Fix some privates wording (fixes #146)

- assets/js/view/user.rb
Trying to move the Signup button to after the input fields.  (Not sure if this is the way to do it or not.)
Also not sure what the extra commit is.  I tried to update my fork from the main repo.
> Try to Move the Location of the Signup Button

- routes/game.rb
trivial; found while getting up to speed on the code.
> fix route doc typo

- lib/engine/route.rb
Sent the migration script separately
> Enforce rule 8.2 making routes be at least 2 stops long (fixes #179)

- lib/engine/round/auction.rb
This was the easiest way to implement this given the current auction architecture.
> More informative log during auction (fixes #191)

- lib/engine/game/g_1889.rb
> Add blocks K4 to Takamatsu E-Railroad private description

- lib/engine/round/auction.rb
- lib/engine/round/operating.rb
- lib/engine/round/stock.rb
Toby mentioned the names were a bit too long on mobile devices, shorten them
> Shorten Pass descriptions

- DEVELOPMENT.md
- api.rb
- assets/app/app.rb
- assets/app/view/hex.rb
- assets/app/view/map.rb
- assets/app/view/map_page.rb
> Developer convenience page - /map/<game_title>

- assets/app/view/player.rb
This was intended to be in the original PR for the new player card.
> Center "Priority Deal"

- assets/app/view/corporation.rb
Also keep things cleaner by making cells blank instead of 0.
> Always display market share line if shares are sellable (fixes #318)

- lib/engine/round/operating.rb
WIP because I need to test further, unless someone else does before I get to it.
resolves #330
> WIP Change payout messages to look more like arithmetic

- lib/engine/round/operating.rb
> Change "passes" to "finishes"/"skips" for action logging

- assets/app/view/spreadsheet.rb
- lib/engine/round/base.rb
- lib/engine/round/stock.rb
Solves spreadsheet part of #292.
> Spreadsheet now shows which players have sold shares of which companies.

- assets/app/game_manager.rb
- assets/app/view/home.rb
https://github.com/tobymao/18xx/issues/227
> Issue 227c

- assets/app/view/actionable.rb
- assets/app/view/game.rb
- assets/app/view/tools.rb
- lib/engine/action/end_game.rb
- lib/engine/game/base.rb
- lib/engine/round/auction.rb
- lib/engine/round/base.rb
- lib/engine/round/operating.rb
- routes/game.rb
- spec/assets_spec.rb
* Adds a game end action
* Hotseat games never entered the finish state
* Route wouldn't unapply game end state on pass
fixes #239 
fixes #287
> Allow way of abandoning game early, fix end game on hotseat and when undone

- assets/app/game_manager.rb
- assets/app/view/home.rb
> [issue_375] order finished games after ready/active/unstarted

- assets/app/view/tiles.rb
- lib/engine/round/base.rb
> Prepend # to tile IDs

- lib/engine/config/game/g_1889.rb
> Change most "company" to "corporation" on Mitsubishi

- lib/engine/round/auction.rb
- lib/engine/round/base.rb
- lib/engine/round/operating.rb
- lib/engine/spender.rb
> Disallow non-positive spend amounts

- assets/app/view/game_card.rb
> Add confirmation on game deletion

- assets/app/view/game_log.rb
> disallow empty chat messages in game log

- assets/app/view/buy_trains.rb
Fixes #293
Also makes it clearer who is the owner
> Hide other players trains by default, and list the owner

- assets/app/view/player.rb
- lib/engine/game/base.rb
- lib/engine/player.rb
- lib/engine/round/base.rb
- lib/engine/round/operating.rb
- lib/engine/round/stock.rb
- lib/engine/share_bundle.rb
- lib/engine/share_holder.rb
- lib/engine/share_pool.rb
- Extract logic into functions
- Adjust Margins so token icons don't overlap
> Add Liquidity to Players

- lib/engine/game/base.rb
- Need to filter out bundles that don't fit in the bank before choosing
the max bundle
> Fix Liquidity Calculation

- assets/app/view/corporation.rb
- assets/app/view/route_selector.rb
- assets/app/view/spreadsheet.rb
- lib/engine/action/run_routes.rb
- lib/engine/corporation.rb
- lib/engine/operating_info.rb
- lib/engine/round/operating.rb
- lib/engine/route.rb
fixes #286 
There's no button to reload the route, you can refresh the browser to do that if someone so desires
> Reload trains last routes when entering run routes

- assets/app/view/route_selector.rb
Some people on the chat thought we'd implemented automatic route calculate, make it clearer what it's doing.
> Add description to run routes to avoid people think it's automatic

- lib/engine/config/game/g_1882.rb
- lib/engine/game/base.rb
Also did a pass on privates text.
> Random non-president's share, plus excluded corps (for 1882)

- lib/engine/config/game/g_1817.rb
- lib/engine/config/game/g_1846.rb
- lib/engine/config/game/g_1882.rb
- lib/engine/config/game/g_1889.rb
- lib/engine/config/game/g_18_chesapeake.rb
- lib/engine/game/base.rb
- lib/engine/round/stock.rb
> Per-title rule whether stock must be sold in blocks

- assets/app/view/game_card.rb
- assets/app/view/home.rb
> switch delete text to wastebasket emoji to free up ui, closes #603

- assets/app/view/part/revenue.rb
- assets/app/view/tile.rb
- lib/engine/part/revenue_center.rb
- lib/engine/tile.rb
- spec/lib/engine/tile_spec.rb
> fix rendering revenue for 1882's 30/30 offboard

- assets/app/view/game.rb
- lib/engine/game/base.rb
fixes #158
fixes #320
fixes #577
enables the end game when a stock hits the end of the stock market for 1882 (but it's not coded yet)
> Add warning that the game is ending, add what game it is to the status

- lib/engine/config/game/g_1817.rb
- lib/engine/config/game/g_1846.rb
- lib/engine/config/game/g_18_chesapeake.rb
Related:
* https://github.com/18xx-maker/games/pull/29
* https://github.com/18xx-maker/export-rb/pull/1
https://imgur.com/a/9JWnf15
Changes:
* update config for 1817, 1846, 18Chesapeake from 18xx-maker updates
* remove unused (and incorrect) `axes` config from 1846
> Offboard config

- lib/engine/round/operating.rb
Fixes issue with game https://www.18xx.games/game/1793
> Fix EMR if your bundle contains the president share

- assets/app/view/chat.rb
- public/assets/main.css
+ chatbar: input => textarea
+ placeholder
+ css moved inline
> resizable chatbar; +placeholder

- assets/app/view/game/part/location_name.rb
> Split 5 word strings more sensibly fixing 1882's Pile o'Bones

- assets/app/app.rb
- assets/app/view/game/issue_shares.rb
- assets/app/view/game_card.rb
- models/base.rb
- models/game.rb
- public/assets/main.css
+ player names truncated (max. 19 char), full name on hover
+ Max Players / Created inline
+ Updated right aligned
+ time when today, else date
+ fulldate on hover
+ kick buttons hover text
+ commas separated from name
+ no commas between buttons
+ margins/paddings optimized
+ b => strong, u => em
> game cards revised

- assets/app/view/game_card.rb
- public/assets/main.css
> em = underline; game-card absolute width

- lib/engine/config/game/g_1846.rb
> add tile blocking for 1846 privates (MC, OI)

- lib/engine/game/g_1846.rb
> Proposed change to "Pass card" phrasing

- lib/engine/round/stock.rb
> Changed description text for Stock Round.

- assets/app/app.rb
- assets/app/view/chat.rb
- assets/app/view/game_row.rb
- assets/app/view/home.rb
- assets/app/view/log.rb
- assets/app/view/logo.rb
- assets/app/view/navigation.rb
- assets/app/view/welcome.rb
- public/assets/main.css
+ chat height increase if > 900px width
+ chat resize only vertical
+ h1/h2
+ #/.
+ paddings/margins pruned
+ prev/next fixed position
> homepage (slightly) revised

- assets/app/view/game/part/city.rb
Can't believe I missed that
fixes #771
> Add extra rotation to correct tokens

- lib/engine/corporation.rb
- lib/engine/game/base.rb
- lib/engine/round/stock.rb
- lib/engine/share_price.rb
- lib/engine/stock_market.rb
- spec/lib/engine/round/stock_spec.rb
Implements brown for 1836Jr and 1882.
> Implement the brown

- lib/engine/config/game/g_1846.rb
> 46 sell in blocks

- assets/app/view/game/corporation.rb
https://18xxgames.slack.com/archives/C012K0CNY5C/p1592756702253700
> corporation icons: prevent overlap of border

- assets/app/view/game_row.rb
10rem weren’t enough for "Your Finished Games"
> game_row header: prevent line wrap

- lib/engine/depot.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1882.rb
1882
Trains that companies discard for any reason are removed from the game, not placed in the market.
> Removed trains are discarded

- lib/engine/game/g_1836_jr30.rb
- lib/engine/round/g_1836_jr_30/operating.rb
Implements
A corporation may only buy one of each train type per operating turn
> 1836Jr30: Can only by one of each rank from the depot on a round

- assets/app/view/game/buy_companies.rb
- assets/app/view/game/company.rb
- assets/app/view/game/map.rb
- assets/app/view/game/round/operating.rb
- assets/app/view/game/route_selector.rb
- map inline
- map-size calculation corrected to prevent pagebreaks due to map width set wider than necessary
- buy_companies wrapped & display: flex to avoid setting max-width (which could be a problem later on)
- min. 3 companies will be rendered inline (with rem <= 16px), max. depends on width of map
- route_selection slimmed
> Game page map inline

- assets/app/view/game/route_selector.rb
- lib/engine/config/game/g_1882.rb
- lib/engine/part/base.rb
- lib/engine/part/city.rb
- lib/engine/part/revenue_center.rb
- lib/engine/route.rb
- lib/engine/tile.rb
There is a fishing hex that counts for free onto a route.
> Allow tiles to have a zero 'movement' cost to run for free by a train

- assets/app/view/game/axis.rb
according to browserstack this should work on iOS (Safari/Chrome), but please test locally on hardware
> Fix map top axis on iOS

- assets/app/app.rb
- assets/app/view/game/buy_companies.rb
- assets/app/view/game/company.rb
- assets/app/view/game/corporation.rb
- assets/app/view/game/game_log.rb
- assets/app/view/game/map.rb
- assets/app/view/game/player.rb
- assets/app/view/game/round/operating.rb
- assets/app/view/game_card.rb
- assets/app/view/game_page.rb
- assets/app/view/log.rb
- assets/app/view/logo.rb
- assets/app/view/navigation.rb
- public/assets/main.css
> Revert "margins/paddings revised (header/home/content/game/companies)"

- assets/app/view/welcome.rb
Unsure if this is the ideal wording, but I think it is a nice little thing to mention. Without him, none of this would be possible :)
> Update welcome.rb to mention Francis Tresham

- assets/app/lib/radial_selector.rb
- assets/app/view/game/map.rb
> Fix token selector on right hand side of the map

- assets/app/view/game/corporation.rb
- assets/app/view/game/round/stock.rb
- assets/app/view/game/stock_market.rb
- assets/app/view/game_page.rb
- lib/engine/corporation.rb
- lib/engine/share_pool.rb
fixes #830
fixes #552
fixes #643
> Explain to user when they need to sell stock, add explaination for colors on stock market

- assets/app/app.rb
- assets/app/view/game_row.rb
> Fix paging of hotseat games

- DEVELOPMENT.md
- lib/engine/game/base.rb
Minor spelling issue I noticed.  I couldn't find any other references with this spelling in the code so it's unlikely that there is a string check that this is going to mess up.
> Spelling - Bankruptcy

- lib/engine/round/special.rb
> Restrict potential tiles for special tile lays to valid upgrades

- lib/engine/game/g_1846.rb
avoids executing the removal logic or printing empty 'removal' log lines w/ 5 players
> slight refactor

- assets/app/view/game_card.rb
Try to keep Enter button in a static position to
lessen risk of deleting game by mistake.
> Enter and Delete/Confirm button swapped (#941)

- assets/app/view/game/game_data.rb
It's less confusing to non-engineers if we don't show a bunch of JSON data by default.
fixes #888
> Hide JSON by default, remove pretty print

- assets/app/view/flash.rb
If darker bg colors are / will be relevant, change would be necessary.
> fix flash_opts font color

- lib/engine/round/operating.rb
> Rust all phased out trains, not just the operated trains.

- assets/app/view/game/game_info.rb
> game_info: provide obsoletes and variant names and prices

- lib/engine/game/base.rb
- lib/engine/game/g_1846.rb
- lib/engine/round/operating.rb
> 1846: bankruptcies end game when all but one player goes bankrupt

- assets/app/view/game/buy_trains.rb
- assets/app/view/game/game_info.rb
- lib/engine/train.rb
> Provide variants info on remaining trains when buying trains

- public/assets/main.css
before:
after:
(… on browserstack, ymmv!)
> slightly thinner font on macOS

- assets/app/view/game/stock_market.rb
Par is a word, not an acronym.
> PAR -> Par

- assets/app/view/game/player.rb
> priority deal background: salmon

- assets/app/lib/color.rb
might fix #1016 – if not color_for(:bg|font) will at least work with pcs: dark when not logged in, too.
> prefers_color_scheme: dark => different fallback colors

- assets/app/view/game/bank.rb
- assets/app/view/game/entities.rb
- assets/app/view/game/game_info.rb
> bank card: cash + discarded trains

- lib/engine/config/game/g_1846.rb
> allow MPC to assign hexes any time while owned by corp

- lib/engine/game/g_1846.rb
[Fixes #1029]
screenshots from a clone of game 3559 where I had the GT president sell shares to close it:
> when closing corporations, only "spend" money if more than zero

- assets/app/view/game/part/city_slot.rb
> scale font sizes for reservations based on number of chars in sym

- assets/app/view/game/corporation.rb
- assets/app/view/game/exchange.rb
- assets/app/view/game/round/stock.rb
- assets/app/view/game/spreadsheet.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1846.rb
- lib/engine/share_pool.rb
> add class constant IPO_NAME, set 1846's to "Treasury"

- spec/assets_spec.rb
Hopefully it'll mean we'll break things less
> Add fixtures to check views render for steps

- lib/engine/config/game/g_18_al.rb
Without this 18AL get stuck after OR1.1 and will not
go into SR2.
> 18AL: Specify operating round count per phase

- assets/app/view/game/bank.rb
- assets/app/view/game/game_info.rb
- assets/app/view/game/spreadsheet.rb
- public/assets/main.css
details s. commit comments
tr highlight on hover/tap limited to game_info & spreadsheet for now (only makes sense on larger tables, definitely not on .card)
> Revision game_info & spreadsheet

- lib/engine/graph.rb
> only allow teleportation via token if token has teleport price

- lib/engine/config/game/g_1836_jr30.rb
Example: Change from 'F30' to '30 F'
> 1836Jr30: Update currency format (#1066)

- assets/app/view/create_game.rb
> validate min/max players

- lib/engine/game/g_18_al.rb
Workaround for 18AL to the problem described in #1096
> 18AL: Nashville/Mobile must be terminus if in route

- assets/app/lib/color.rb
- assets/app/lib/settings.rb
- assets/app/view/chat.rb
- assets/app/view/game/bank.rb
- assets/app/view/game/corporation.rb
- assets/app/view/game/game_info.rb
- assets/app/view/game/part/borders.rb
- assets/app/view/game/player.rb
- assets/app/view/game/route_selector.rb
- assets/app/view/game/spreadsheet.rb
- assets/app/view/game/stock_market.rb
- assets/app/view/game_page.rb
- assets/app/view/log.rb
- assets/app/view/logo.rb
- assets/app/view/user.rb
some overdue cleanup, some groundwork for user defined route colors
> separate user settings from lib/color

- assets/app/view/game/company.rb
fixes @jenf ’s [issue](https://github.com/tobymao/18xx/issues/940#issuecomment-660984224)
> fix company name truncation

- assets/app/view/game/spreadsheet.rb
fixes #1119
underline dotted looked a tad better to me than dashed, ymmv
> differentiate half-pay

- lib/engine/game/base.rb
- lib/engine/game/g_1846.rb
- lib/engine/game/g_1882.rb
- lib/engine/step/track.rb
- lib/engine/step/track_and_token.rb
- lib/engine/step/tracker.rb
This generalizes the 1846 approach to track laying allowing a custom list to describe what the rules are.
> 1882 track laying

- assets/app/view/game/part/city_slot.rb
- lib/engine/graph.rb
- lib/engine/step/g_1882/home_token.rb
- lib/engine/step/tracker.rb
* SC couldn't lay neutral token
* CN was offered lay track if SC nicked it's token
* CN was offered run routes if SC nicked it's token and it had a train
> 1882 Misc bugs

- assets/app/view/game/corporation.rb
test case: https://www.18xx.games/game/4641#entities
> fix entities not rendering after game end

- lib/engine/stock_market.rb
> Don't infinitely recurse on 2d stock markets

- lib/engine/share_pool.rb
- lib/engine/step/g_1882/buy_sell_par_shares.rb
Match the change in can_gain?
Fix how much money is spent when using SC setup
> 1882 Minor bugs

- assets/app/view/game/corporation.rb
> operating order on corp cards

- assets/app/view/create_game.rb
- assets/app/view/welcome.rb
With us adding 1836jr and 1882 I think we should suggest good entry games to people.
> Update text to suggest 89 or chesapeake for new players, select 89 by default

- assets/app/view/game/abilities.rb
- assets/app/view/game/part/city_slot.rb
- assets/app/view/game/round/operating.rb
- lib/engine/action/remove_token.rb
- lib/engine/config/game/g_1882.rb
- lib/engine/game/g_1882.rb
- lib/engine/part/city.rb
- lib/engine/step/g_1882/home_token.rb
- lib/engine/step/g_1882/nwr_track_bonus.rb
- lib/engine/step/g_1882/special_nwr.rb
- lib/engine/step/g_1882/track.rb
- lib/engine/step/home_token.rb
- lib/engine/step/tokener.rb
- lib/engine/token.rb
Implements remaining 1882 privates
> NWR Private bonus, and close Canadian Pacific properly

- assets/app/view/game/companies.rb
- assets/app/view/game/company.rb
- assets/app/view/game/corporation.rb
- assets/app/view/game/spreadsheet.rb
- assets/app/view/link.rb
- public/assets/main.css
- spec/assets_spec.rb
I left "Privates" as header, because it’s a tad shorter and a bit easier to grasp instantly than "Companies".
Should resolve: #1061, #872, #473, #1155
> Spreadsheet: some infos added, styling/language consolidated

- lib/engine/game/base.rb
> 1882: NWR should lay without master mode

- lib/engine/step/g_1882/special_nwr.rb
> 1882 Don't show tiles that don't have free token spots

- assets/app/view/game/game_info.rb
> Fix train rusting on info page due to variable aliasing

- assets/app/view/game/part/icons.rb
> Edge borks when height is missing

- assets/app/view/game/discard_trains.rb
- assets/app/view/game/game_end.rb
- assets/app/view/game/round/auction.rb
- assets/app/view/game/round/draft.rb
- assets/app/view/game/round/operating.rb
- assets/app/view/game/round/stock.rb
- assets/app/view/game/undo_and_pass.rb
- assets/app/view/game_page.rb
Moves the undopass code into one spot
> Tidy up the undo/pass code

- lib/engine/game/g_1882.rb
- lib/engine/route.rb
> Remove temporary code relating to 1882 token crash

- lib/engine/step/home_token.rb
> Check home token is being placed on the right tile

- lib/engine/route.rb
> Another form of the problem where the route selector breaks reloading old routes

- lib/engine/config/game/g_1846.rb
- lib/engine/game/g_1846.rb
> Remove private company markers as appropriate

- assets/app/view/game/game_data.rb
- assets/app/view/game/tools.rb
- buttons moved to the left, labels to the right
- data buttons reordered
- obsolete styles removed
> game tools revised

- assets/app/view/game_card.rb
> end date on finished games

- routes/game.rb
> Joining shouldn't be possible after a game has started

- assets/app/view/game/history_controls.rb
Does "latest" work? "most recent" or sth. else better?
(Splitting into latest / game end seems not worth it.)
> history links titles

- lib/engine/share_bundle.rb
> Check to see all shares are owned by the same person

- lib/engine/game/g_1882.rb
- lib/engine/hex.rb
- lib/engine/tile.rb
> 1882: Restore borders on tiles destroyed by NWR event

- assets/app/view/home.rb
- assets/app/view/user.rb
fixes #1113
On a related note: Is the sorting in https://github.com/tobymao/18xx/blob/30b2d4aab3ee1850a040a56dbd152d1fb16c53dc/assets/app/game_manager.rb#L155-L160 necessary? Performance reasons?
> sort games by date DESC

- assets/app/view/tiles_page.rb
fixes #658
doesn't do every parameter, but has a good start.
> Allow custom tile rendering

- lib/engine/step/g_1882/special_nwr.rb
> If there's active routes disable NWR private

- assets/app/view/game/part/icons.rb
- assets/app/view/game/part/revenue.rb
- assets/app/view/game/part/small_item.rb
> Improve 1882 and 18AL icons location

- assets/app/view/game/companies.rb
- assets/app/view/game/player.rb
- assets/app/view/game/round/auction.rb
- lib/engine/step/g_1846/draft_distribution.rb
- lib/engine/step/waterfall_auction.rb
> Show drafted companies and cost when player presses show

- lib/engine/part/city.rb
- lib/engine/step/g_1882/special_nwr.rb
> Remove tile reservation to allow tile lays on NWR special

- lib/engine/game/g_1882.rb
> Remove SC when it cannot be parred

- assets/app/lib/settings.rb
> use "french violet" and "outrageous orange" for routes 5 and 6

- assets/app/view/game/dividend.rb
> fix payout buttons

- assets/app/lib/settings.rb
- models/user.rb
adds config buttons to user profile
> user settings route colors 5 & 6

- assets/app/view/game/par.rb
- assets/app/view/game/round/auction.rb
- lib/engine/step/buy_sell_par_shares.rb
- lib/engine/step/company_pending_par.rb
- lib/engine/step/g_1882/buy_sell_par_shares.rb
> Tidy up PAR code, fix 1882 SC PAR values

- assets/app/view/game/spreadsheet.rb
> Spreadsheet: fix alignment, +letter-spacing

- lib/engine/hex.rb
- lib/engine/part/revenue_center.rb
[Fixes #1369]
This might break some games.
> preserve city groups when laying new tiles

- assets/app/view/game/spreadsheet.rb
maybe to be revised for games where entities would own loads of companies
> no line wrapping

- assets/app/view/game/route_selector.rb
- assets/app/view/tiles_page.rb
> adjust headers

- lib/engine/game/g_1817.rb
- lib/engine/round/base.rb
- lib/engine/step/auctioner.rb
- lib/engine/step/g_1817/selection_auction.rb
- lib/engine/step/waterfall_auction.rb
First pass of the initial auction for 1817
> 1817 initial auction

- assets/app/view/game/buy_trains.rb
> emergency fund raising rendering order + wording

- assets/app/view/game/part/city_slot.rb
> Fix issue where clicking on destination too quickly caused an error

- assets/app/view/game/buy_trains.rb
- lib/engine/depot.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/buy_train.rb
- lib/engine/step/g_1817/dividend.rb
- lib/engine/step/g_1817/track.rb
- lib/engine/step/train.rb
Implement the customization for 1817 for parts that existing actions.
> Add customization for 1817, train export, track, dividend and train purchasing

- assets/app/view/welcome.rb
- lib/engine/game/g_18_al.rb
- lib/engine/game/g_18_tn.rb
Ah, shambles... I managed to overwrite another PR with this one... Therefor the change of title.
So now this is my master branch, and the 18MS thing is on another branch.
> 18AL alpha, 18TN beta

- lib/engine/tile.rb
Fixes #1385 - specifically part 2.
> Fix exception when parsing tile with a town connected to just one edge

- assets/app/view/game/dividend.rb
- lib/engine/step/dividend.rb
Also I finally changed "Payout" to "Pay Out"; "payout" is a noun and the button names should be verbs.
> Show all money corp receives in preview, incl. divs (fixes #1367)

- lib/engine/config/game/g_18_ga.rb
- lib/engine/game/g_18_ga.rb
In 18GA players can buy companies from other players during SR.
> 18GA: Support buy of companies between players during SR

- lib/engine/game/g_18_ga.rb
- lib/engine/step/g_18_ga/buy_company.rb
- lib/engine/train.rb
Buying corporation receives a free non-sellable 2 train if it has
room for it and the 2 trains hasn't rusted.
> 18GA: Implement Ocilla Southern RR company

- assets/app/view/game/part/borders.rb
- assets/app/view/game/tile.rb
> Fix QLL border overlap issue

- lib/engine/ability/README.md
- lib/engine/ability/additional_token.rb
- lib/engine/ability/tile_income.rb
- lib/engine/config/game/g_1817.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817/special_track.rb
- lib/engine/step/g_1817/track.rb
- lib/engine/step/tracker.rb
This implements all 1817 privates except the Coal Mine and Bridge companies.
> 1817 privates

- assets/app/view/game/exchange.rb
- assets/app/view/game/round/stock.rb
- lib/engine/step/exchange.rb
- lib/engine/step/share_buying.rb
> Fix private exchange when at cert limit.

- assets/app/view/welcome.rb
- lib/engine/game/g_18_al.rb
- lib/engine/game/g_18_tn.rb
- spec/assets_spec.rb
- spec/fixtures/18_tn/7818.json
- spec/lib/engine/games/game_spec.rb
18AL set to production.
18TN set to beta. Have added a spec file with a game end.
> 18AL/18TN: Change to production/beta

- lib/engine/step/dividend.rb
> Merge divident payouts onto one line

- lib/engine/config/game/g_1882.rb
fixes #1537
Will need a pinning afterward :(
> 1882: Fix C7/D6, add extra text explaining about extra train for SC

- lib/engine/config/game/g_18_mex.rb
Use swamp and desert terrain.
Added some impassible borders.
> 18MEX: Correct terrain appearance

- assets/app/view/game/corporation.rb
- assets/app/view/game/part/assignments.rb
- assets/app/view/game/tile.rb
- lib/engine/config/game/g_18_al.rb
- lib/engine/game/g_1846.rb
- lib/engine/game/g_18_al.rb
- lib/engine/step/g_18_al/assign.rb
- public/icons/1846/mpc_token.svg
- public/icons/1846/sc_token.svg
- public/icons/18_al/snar_token.svg
> Add tokens for assign_hex and assign_corp and add tokens for 1846 and 18AL

- lib/engine/ability/token.rb
- lib/engine/company.rb
- lib/engine/config/game/g_18_ga.rb
- lib/engine/game/g_18_ga.rb
- lib/engine/step/g_18_ga/token.rb
- lib/engine/step/tokener.rb
Now it should be possible to use Waycross & Southern RR to teleport
the token for free. And when making a normal, connected, tokening
in Waycross the token is paid for.
> 18GA: Implement Waycross & Southern RR (fixes #1496, #1516)

- assets/app/view/game/loans.rb
- lib/engine/config/game/g_1817.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/assign.rb
- public/icons/1817/bridge_token.svg
Icon from https://github.com/18xx-maker/18xx-maker/blob/master/src/data/icons/bridge.svg
> 1817: Bridge privates

- assets/app/view/game/company.rb
(fixes #1450) The issue has been fixed. A new price: value has been added to show the current price of the company. I would like to request assistance for fixing the issue for 1846 as the discount includes the debt of companies like the big four.
> (fixes #1450) Fixes the issue where the price on the cards would not go down if there was an discount. 

- lib/engine/config/game/g_18_mex.rb
- lib/engine/step/minor_half_pay.rb
- Correct text for the minors
- The share received from MIR is now a CHI
- Make it possible to make payout with minors
> 18MEX: Some corrections

- assets/app/view/welcome.rb
- spec/assets_spec.rb
- spec/fixtures/18_ga/8643.json
- spec/lib/engine/games/game_spec.rb
Updated Welcome message.
Added spec fixture test for 18GA. 18TN already has this.
> Elevate 18GA and 18TN to production

- lib/engine/game/g_18_ga.rb
- lib/engine/game/g_18_tn.rb
> 18GA/18TN: Ops, forgot to update DEV_STAGE to production

- assets/app/view/game/round/auction.rb
- lib/engine/step/auctioner.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817/passable_auction.rb
- lib/engine/step/g_1817/selection_auction.rb
- lib/engine/step/waterfall_auction.rb
Fixes
Currently a bug, once you've passed on the IPO bid you can rejoin
Currently a bug, if all other players pass, you still need to up the bid
> Move 1817 IPO auction to use auctioner and fix bugs relating to IPO auction

- assets/app/view/game/part/city.rb
- assets/app/view/game/part/city_slot.rb
- spec/assets/app/view/game/part/slot_spec.rb
> Fix tokening on pointy maps for tiles with both city and town

- lib/engine/game/g_18_ms.rb
- lib/engine/step/g_18_ms/track.rb
In case P1/P2 still has use left we do not finish the tile lay
phase, unless 'Done (Track)' is pressed.
> 18MS: Wait Pass on tile lay if tile lay ability remains

- lib/engine/abilities.rb
- lib/engine/config/game/g_1846.rb
- lib/engine/game/g_1846.rb
> 1846 - add note about IC subsidy to its charter

- assets/app/view/game/part/track_node_path.rb
- lib/engine/part/path.rb
- lib/engine/route.rb
- lib/engine/tile.rb
These changes are needed for the Mexico City tile in 18MEX
> Add parallel path support (lanes) to rendering and routing

- lib/engine/route.rb
> Fix for parallel path concat bug

- assets/app/view/welcome.rb
- lib/engine/game/g_18_ms.rb
Updated welcome page to include 18MS.
Sorted the mentioned 18xx in alphabetical order.
> 18MS: Set to alpha

- lib/engine/step/g_18_ms/buy_train.rb
- spec/assets_spec.rb
- spec/fixtures/18_ms/9882.json
- spec/lib/engine/games/game_spec.rb
Corrected train name if buying variant during assisted train buy.
Add spec fixture for 18MS.
> 18MS: bug fix and fixture

- lib/engine/game/g_18_ms.rb
- lib/engine/step/g_18_ms/lay_tile_with_chattanooga_check.rb
- lib/engine/step/g_18_ms/special_track.rb
- lib/engine/step/g_18_ms/track.rb
- spec/fixtures/18_ms/9882.json
- spec/lib/engine/games/game_spec.rb
Fix so that abilities does not appear during stock round.
Fix bug with Chattanooga bonus if reached via ability.
> Fix/18 ms/abilities

- lib/engine/config/game/g_18_tn.rb
- lib/engine/game/g_18_tn.rb
- lib/engine/step/g_18_tn/special_track.rb
- lib/engine/step/g_18_tn/track.rb
- spec/fixtures/18_tn/7818.json
Abilities should not appear during stock round.
Tile lay ability only allowed during tile laying phase. Require pass on track done if ability not yet used.
> Fix/18 tn/abilities

- lib/engine/config/game/g_18_mex.rb
- lib/engine/game/g_18_mex.rb
- lib/engine/step/g_18_mex/buy_sell_par_shares.rb
- lib/engine/step/g_18_mex/special_track.rb
- lib/engine/step/g_18_mex/track.rb
Do not show Buy/Sell for NdM before phase 3½.
Correct starting location for TexMex.
Various fixes for Copper Canyon private (P2).
Allow two yellow tile lays if major corporation. Minors still only do one tile lay/upgrade.
> 18MEX: Miscellaneous fixes

- assets/app/view/game/round/merger.rb
- lib/engine/game/g_1817.rb
- lib/engine/round/g_1817/acquisition.rb
- lib/engine/round/g_1817/operating.rb
- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/cash_crisis.rb
This implements everything but
* Taking loans/repaying loans
* Reducing station markers to 8
* Paying shorts and cash crisis from them
> 1817 more acquisitions

- lib/engine/config/game/g_18_mex.rb
- lib/engine/game/g_18_mex.rb
- lib/engine/share.rb
- lib/engine/share_bundle.rb
- lib/engine/step/buy_sell_par_shares.rb
Introduce 5% shares for NdM.
Reserve shares used for mergers.
Implement phase 3½ merge of minors.
General: Add buyable attribute for shares and bundles. For a bundle, it is buyable if all shares within it is buyable.
> 18MEX: Implement needed stuff for phase 3½

- assets/app/view/game/part/track_node_path.rb
To go with the earlier bug fix in track_node_path.rb
> Change @width to @width.to_i in two more places

- lib/engine/game/g_18_mex.rb
- lib/engine/round/g_18_mex/operating.rb
If a major corporation has trains at start of its OR, add revenue
for the home city to the treasury.
> 18MEX: Add mail feature

- assets/app/view/game/round/merger.rb
- lib/engine/step/g_1817/acquire.rb
This just leaves
* reducing tokens to 8
* short payoffs
> 1817: Take and payoff loans

- assets/app/view/game/entity_order.rb
- assets/app/view/game/stock_market.rb
Show active entity if the entity is missing as part of an interrupt action.
Fix Belt's logo not showing in the stock market (Checked on Edge, Chrome and Firefox)
> 1817: Two minor bug fixes

- assets/app/view/game/round/merger.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/conversion.rb
- lib/engine/step/g_1817/reduce_tokens.rb
- lib/engine/step/g_1817/token_merger.rb
This just leaves shorts left to sort out
> Add reduction in number of tokens after 1817 merge/acquisition

- lib/engine/step/g_1817/buy_train.rb
from list of trains available to buy
> 1817 Remove trains belong to companies from liquidation

- lib/engine/step/g_1846/buy_train.rb
[Fixes #1780]
Super edgy case, should break very few games if any. I'll be able to check that later.
> prevent selling shares that will close the corporation currently in EMR

- lib/engine/game/g_1846.rb
> 1846 2p - place Erie's second token during setup

- lib/engine/config/game/g_18_mex.rb
- lib/engine/game/g_18_mex.rb
Update description text for minor related privates to make their use clearer.
Add the same interplay functionality to 18MEX that exists in 18AL and 18GA.
> 18MEX: Add some minor things

- lib/engine/step/g_1889/special_track.rb
Addresses a minor issue reported in #1704
> 1889 - fix logging for Ehime Railway's tile lay

- assets/app/view/game/choose.rb
- assets/app/view/game/round/stock.rb
- lib/engine/action/choose.rb
- lib/engine/config/game/g_1817.rb
- lib/engine/game/g_1817.rb
- lib/engine/phase.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
Also make it so you can't sell shares when a corp is in the grey aquisition zone
> Add option to size corporation after winning bid

- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/conversion.rb
- lib/engine/step/g_1817/token_merger.rb
* Make corps that can afford tokens pay for tokens automatically
* Don't allow taking out of loans if you pay loans off
* Fix offering for sale
* Make tokens not disappear after acquisition
> 1817 Bug fixes

- assets/app/view/game/entities.rb
> 18MS: Bank does not have to be visible #1810

- lib/engine/game/base.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
Allow passes when the only option is buy short
Companies should close if bought by the bank
> 1817 Bug Sweep:

- assets/app/view/welcome.rb
- lib/engine/game/g_18_ms.rb
- Updated status to production
- Updated welcome page to reflect this
- Updated rules link to the official v2 release
- Added 18MS as a recommended 18xx for people new to 18xx
> 18MS: Set to production

- assets/app/view/game/bank.rb
- assets/app/view/game/entities.rb
- assets/app/view/game/player.rb
- assets/app/view/game/players.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817/selection_auction.rb
Show bank and seed money on initial auction
Private companies don't count towards cert limit (fixes #1845)
Show loan information (fixes #1844)
Show bid power (fixes #1835)
> 1817 Bugs and improvements:

- lib/engine/game/g_1846.rb
- lib/engine/game/g_18_los_angeles.rb
- lib/engine/game/g_18_ms.rb
- lib/engine/round/draft.rb
- lib/engine/step/g_18_los_angeles/draft_distribution.rb
also a couple of small fixes:
- allowed to pass on first turn of draft
- log removed private companies
> 18 Los Angeles - snake order for draft, priority order for stock rounds

- assets/app/view/game/round/merger.rb
- lib/engine/game/g_18_mex.rb
Fixes #1931 
Plus select first corporation during merge so that Merge button appear without having to select the only corporation.
> 18MEX: Fix two bugs

- lib/engine/game/g_1817.rb
- lib/engine/share.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
Limit shorts to 10
Add share and shorts into share list (fixes #1872)
Fix ownership of new share to corp (fixes #1860)
Correct indexing of shares to cope with 5->10 share conversion
> 1817 Short fixes:

- assets/app/view/welcome.rb
Added prefix to sentence. Replaced misused period with comma.
> Publisher update

- lib/engine/corporation.rb
- lib/engine/game/g_18_co.rb
- lib/engine/step/g_18_co/buy_sell_par_shares.rb
Alright, starting to get into the slightly more complicated stuffs.
Par values are grouped into three zones. Each zone has a different number of shares required to float ( 4 / 5 / 6 ).
Corporations have different classifications that determine the par value zones where they are allowed to launch ( X / A / B / C ).
X is always 75 and 20% to float. This is the DSNG, which floats immediately upon the President's share being awarded.
**Par Groups**
C group corps can be parred in C / B / A
B group corps can be parred in B / A
A group corps can only be parred in A
**Float amounts**
Regardless of corporation group:
C par zone requires 40% to float
B par zone requires 50% to float
A par zone requires 60% to float
Showing X group at par time
Showing …
> [18CO] Par groups and float percent adjustment

- lib/engine/step/g_1817/post_conversion.rb
> 1817 Purchase of treasury share would end when one player could not afford.

- lib/engine/step/dividend.rb
- lib/engine/step/g_1817/dividend.rb
- validate.rb
2 share half pay pays out partial cash.
fixes #1989
> 1817 2 share half pay rounding

- lib/engine/game/g_1817.rb
- lib/engine/round/g_1817/merger.rb
- lib/engine/step/g_1817/conversion.rb
- lib/engine/step/g_1817/post_conversion_loans.rb
* Allow taking more loans than necessary
* Move taking loans after the treasury shares (fixes #1984)
* Buy tokens and liquidate in one place
> 1817: Convert Token purchase bug fixes

- lib/engine/step/g_1817/buy_sell_par_shares.rb
Allow take loan and redeem on same turn (fixes #1986)
Block taking actions as two different corps (fixes #1988)
> 1817: Corporate action fixes

- lib/engine/game/g_18_co.rb
When​ ​a​ ​Corporation​ ​starts​ ​its​ ​run​ ​at​ ​an​ ​East​ ​Off-Board​ ​location​ ​(Lincoln​ ​NE,​ ​Kansas​ ​City​ ​KS,​ ​Wichita​ ​KS)​ ​and ends​ ​its​ ​run​ ​in​ ​Salt​ ​Lake​ ​City,​ ​it​ ​receives​ ​a​ ​bonus​ ​revenue​ ​of​ ​$100.
I based most of this code off the implementation in 1846. It seems pretty straightforward.
> [18CO] East / West Bonus Run

- assets/app/view/game/corporation.rb
Minor correction of previous 5% fix.
> 18MEX: Fix for presentation of 5% share on corporation charter

- lib/engine/step/g_1817/buy_sell_par_shares.rb
- spec/fixtures/1817/13707.json
- spec/lib/engine/games/game_spec.rb
Also add a temporary spec
fixes #2004
> 1817: Make corporations purchase of shares check shares properly

- lib/engine/step/g_1817/conversion.rb
Disallow merging with corps that have already merged (fixes #1996)
Remove from mergable corps that cannot be merged as the player cannot afford the share (fixes #1990)
> 1817: Add extra checks to mergable

- lib/engine/step/g_1817/special_track.rb
- lib/engine/step/tracker.rb
> 1817: Fix using coal mine and mountain engineers together

- lib/engine/game/base.rb
- lib/engine/step/g_1817/special_track.rb
- lib/engine/step/special_track.rb
Because the entity is now the corp and not the private as previous available_hex was exploding fixes #2057
Clarify the text about alpha and beta games
> 1817: Fix coal mines (fixes #2057)

- lib/engine/round/g_1817/stock.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
> 1817: Warn players if their corporations do not have tokens

- assets/app/view/create_game.rb
[Fixes #2058] (this problem wasn't actually exclusive to mobile devices)
> allow deleting in the "Max Players" input

- assets/app/view/game/spreadsheet.rb
> spreadsheet: sort by IPO/par-price

- lib/engine/step/g_1817/conversion.rb
> 1817: prevent companies in acquisition from merging

- lib/engine/game/base.rb
- Add SELL_MOVEMENT where the market price falls once for every 10% sold (for example drops twice when 25% sold)
> Stock drop per 10% sold

- lib/engine/corporation.rb
> fix definition of Engine::Corporation#floated? to prevent re-floating

- assets/app/view/game/bank.rb
- assets/app/view/game/game_info.rb
- assets/app/view/game/round/merger.rb
- lib/engine/config/game/g_1817.rb
- lib/engine/game/g_1817.rb
See player information when buying stocks during MR (fixes #1856)
Show future interest (fixes #2083)
Show corporation sizes (fixes #2073)
> 1817 UI improvements

- lib/engine/game/g_18_mex.rb
Correction of typo indicated in issue #2158
also corrected a typo in a comment on line 234 just for completion's sake.
> corrected typo of Handle on line 234 and of Treasury on line 494

- assets/app/view/game/buy_sell_shares.rb
This is currently only for 18MEX but it is general code that will
be used as soon as there are different percentage shares in the
share pool.
In case there is just one type of shares the behavior will not be changed.
In case there are more the one type of percentage in the share pool
the percentage of the market share will be shown on the Buy/Exchange button.
This is also presented even if only one of the types are buyable.
So, using 18MEX, and Buy, as an example:
* If 5% and 10% are in market pool, and player can buy both
Show: "Buy 5% Market Share" "Buy 10% Market Share"
* If 5% and 10% are in market pool, but player can only buy 5%
Show: "Buy 5% Market Share"
* If just 5% or 10% shares are in market pool
Show "Buy Market Share"
* And this means - if not 18MEX, but still Buy
Show "Buy …
> In case different percentages is in market, separate buttons (#2128)

- lib/engine/game/g_1817.rb
> 1817: Starting corp at size 5 or 10 should set the share sizes correctly

- assets/app/view/welcome.rb
I asked Toby for permission.
The announcement will disappear automatically and then I'll do another PR to remove that code.
> Add temporary announcement of the 1846 tournament

- lib/engine/step/g_1817/buy_sell_par_shares.rb
Reflect the acquisitions that corps make when IPOing dynamically (fixes #1832)
> 1817: Make corporation starting more clear and dynamic

- lib/engine/step/g_1817/buy_sell_par_shares.rb
> 1817: Disallow using subsideries that cannot be legally combined

- assets/app/view/welcome.rb
Registration will close tomorrow morning. Feel free to pull and deploy tonight whenever you feel it's most appropriate (I'm pretty sure that you'd feel pretty constrained if I didn't write this sentence :P )
> Remove the announcement of the 1846 tournament

- assets/app/view/game/buy_sell_shares.rb
- lib/engine/step/g_18_mex/buy_sell_par_shares.rb
1. (18MEX specific) If at cert limit, 5% NdM share should still be possible to buy
2. (General) If buying non-10% for Market is an option, percentage is always shown on Buy button.
> Fixes for NdM 5% in market pool

- lib/engine/step/g_1817/conversion.rb
- migrate_game.rb
- spec/fixtures/1817/15528.json
- spec/lib/engine/games/game_spec.rb
fixes #2252
Adds another spec for 1817
> 1817: Fix lack of share purchasing after conversion

- lib/engine/game/g_1817.rb
> 1817 - fix initial "interest if X loans taken" line, fix plurals

- lib/engine/step/g_1817/acquire.rb
> 1817 Game crashes if player goes bankrupt and players corp is being auctioned

- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817/share_buying_with_shorts.rb
> 1817: Disallow selling, buying and shorting of shares in liquidation

- lib/engine/step/g_1817/track.rb
> 1817: Fix upgrades of Toledo from green to brown

- assets/app/view/game/corporation.rb
- assets/app/view/game/entity_list.rb
- assets/app/view/game/stock_market.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
Also add a field to say how big the corporation is
fixes #2088
> 1817: Make corp logos bigger on 5 & 10 share corps

- lib/engine/game/g_1817.rb
- lib/engine/round/g_1817/merger.rb
- lib/engine/step/g_1817/bankrupt.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
Priority deal should change when acting as corporation (fixes #2338)
Companies with 8 tokens converting shouldn't go into liquidation
(fixes #2335)
> 1817 misc bugs

- lib/engine/share_pool.rb
- lib/engine/step/g_1817/bankrupt.rb
fixes issue with game reported on slack
https://18xx.games/game/16148?action=951
> 1817: Correct share count being invalid after bankrupcy

- assets/app/view/user.rb
- migrate_names.rb
- models/game.rb
- models/user.rb
- routes/game.rb
Modify user settings to use id (needed converting to string)
Update migrate script to modify user settings
fixes #1135
> Allow users to change their name

- assets/app/view/game/stock_market.rb
- assets/app/view/welcome.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/discard_train.rb
- lib/engine/step/train.rb
- spec/fixtures/1817/15528.json
fixes #2385
1817: Fix stock market display issues (fixes #2382)
> 1817: 2+ trains should count towards train limit

- lib/engine/game/g_1828.rb
It is not active in multiplayer games until the game starts.
> 1828: Get the waterfall auction step explicitly. 

- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/buy_train.rb
- lib/engine/step/g_1867/dividend.rb
- lib/engine/step/g_1867/loan.rb
- lib/engine/step/g_1867/redeem_shares.rb
- lib/engine/step/g_1867/track.rb
- validate.rb
This puts together the rough parts of 1867 OR
* Redeem shares
* Track lays
* Dividend
* Train buy
* Nationalizational (needs more owkr)
> 1867: Rough cut of OR

- assets/app/app.rb
- assets/app/view/game/actionable.rb
- assets/app/view/game/game_log.rb
- assets/app/view/home.rb
- assets/app/view/log.rb
- assets/app/view/user.rb
- lib/engine/action/base.rb
- models/game.rb
- routes/game.rb
While doing this I took the chance to review the permission check that
got a little less strict on the other commit related to this (57860854)
I thought the previous commit dealt with all actions, but it turns out I had just peeled the first layer.
> Allow the owner of a game to act even if they aren't playing.

- lib/engine/game/base.rb
- lib/engine/step/train.rb
> add Game#log_later method, log phase change after train purchase

- assets/app/view/game_page.rb
> clear the TileSelector whenever changing tabs

- lib/engine/round/operating.rb
- lib/engine/step/emergency_money.rb
- lib/engine/step/g_1817/bankrupt.rb
- lib/engine/step/train.rb
It now also removes corporations in liquidation
> recalculate_order was not being called in 1817 some times

- lib/engine/config/game/g_1867.rb
- lib/engine/game/g_1867.rb
Initial import of 1867 config
There's a few mistakes, but i'd rather fix as a delta
> Import 1867 from 18xx-maker

- assets/app/view/user.rb
One PR was done while the other was being reviewed and there was a line that went missing in the process
> Fix change username

- lib/engine/step/g_1817/loan.rb
Unsure how the mis-ownership of a loan occured, but enforce it
Causes game 16711 to be pinned (fixes #2429)
> 1817: Enforce repaying loans that belong to corporations

- assets/app/view/game/round/stock.rb
- lib/engine/config/game/g_1867.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1867.rb
- lib/engine/share_price.rb
- lib/engine/step/buy_sell_par_shares.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1867/buy_sell_par_shares.rb
- lib/engine/step/g_1867/dividend.rb
Adds two extra 'par' zones
Adds and corrects the train/phase roster
> 1867: Allow minors (2 share corps) to be auctioned and started

- assets/app/view/game/map.rb
addresses https://github.com/tobymao/18xx/pull/2409#discussion_r528455233
> move the localStorage lookup out of the needs declaration

- lib/engine/game/g_1817_na.rb
1817NA is rules complete. This patch will make 1817NA enter alpha
> 1817NA - Enter Alpha

- assets/app/view/game_page.rb
- lib/engine/game/base.rb
- routes/game.rb
This has *not* been tested. Please make sure it works before merging
> Fix active_players on pinned games

- assets/app/view/game/round/merger.rb
- lib/engine/step/g_1817/acquire.rb
> 1817: Show acquiring corp in acquisitions

- assets/app/view/game/actionable.rb
Made some happy-to-glad changes in the wording on some messages to make it a bit clearer
> change wording in error message flashes

- lib/engine/step/tokener.rb
- lib/engine/step/tracker.rb
e.g., "ELA (DC&H) places a token" instead of "ELA places a token" to indicate
that ELA used the ability from the company Dewey, Cheatham, and Howe to place
that token
> Enhancement: log company sym when its ability is used for tokens/tiles

- lib/engine/game/g_1817_na.rb
I updated the wiki link in the game as per
fixes https://github.com/tobymao/18xx/issues/2466
> Updated wiki link for 1817NA

- assets/app/view/game/abilities.rb
- public/assets/main.css
Most new users get confused with the links. This should help
> Use buttons instead of links for the activated abilities

- assets/app/view/game/round/merger.rb
- lib/engine/config/game/g_1867.rb
- lib/engine/game/g_1867.rb
- lib/engine/round/g_1867/merger.rb
- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/conversion.rb
- lib/engine/step/g_1867/buy_train.rb
- lib/engine/step/g_1867/merge.rb
- lib/engine/step/g_18_mex/merge.rb
Implement 1867's minor, buying shares is still to be done.
Minors become majors via converting, so one step to convert, then choose which major to 'convert' (action is actually 'merge')
> 1867: Basic implemention of minors converting to majors

- Rakefile
- assets/app/view/game/hex.rb
- assets/app/view/game/map.rb
- assets/app/view/game/map_controls.rb
- assets/app/view/game/tile.rb
- lib/engine/game/base.rb
* not during run routes/dividends
fixes #1611 & #563
> Add ability to see last run on map at nearly any time*

- assets/app/view/game/spreadsheet.rb
- lib/engine/game/base.rb
- lib/engine/player.rb
- lib/engine/player_info.rb
- lib/engine/round/auction.rb
- lib/engine/round/draft.rb
- lib/engine/round/g_1817/merger.rb
- lib/engine/round/stock.rb
> Add player value over rounds to the spreadsheet

- lib/engine/ability/README.md
The def changed at some point https://github.com/benjaminxscott/18xx/blob/master/lib/engine/ability/shares.rb
> [docs] private ability s.b. `shares`

- assets/app/view/game/round/auction.rb
- lib/engine/step/auctioner.rb
Fixes auction issues in non-1848 games caused by a bug introduced in [my prior patch](https://github.com/tobymao/18xx/pull/2535/files/472e68df8ba3bb36fea95e5ec73413a59ae3c24e#r536492916)
> revert de25ac2df with more generic fix

- lib/engine/game/base.rb
- spec/assets_spec.rb
- spec/fixtures/18_mex/17849.json
- spec/lib/engine/games/game_spec.rb
Also added the game that had this problem as a fixture.
> 18MEX: Fix argument number error (fixes #2547)

- public/logos/1856/BBG.svg
- public/logos/1856/CA.svg
- public/logos/1856/CGR.svg
- public/logos/1856/CPR.svg
- public/logos/1856/CV.svg
- public/logos/1856/GT.svg
- public/logos/1856/GW.svg
- public/logos/1856/LPS.svg
- public/logos/1856/TGB.svg
- public/logos/1856/THB.svg
- public/logos/1856/WGB.svg
- public/logos/1856/WR.svg
They actually have the corporations color and logos on them now so that's better
> Added (ugly) tokens for the 1856 corporations

- assets/app/view/game/round/stock.rb
- assets/app/view/welcome.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817/post_conversion.rb
- migrate_game.rb
- spec/fixtures/1817/15528.json
- spec/fixtures/1817_na/17386.json
Corps in acquisition cause a crash if no other corps can buy (fixes #2549)
Disallow bidding when player is at cert limit (fixes #2537)
Don't count shorts as shares that can be sold in acquisition (fixes #2536)
> 1817 Bug Fixes, and make production

- assets/app/view/game/rename_hotseat.rb
- assets/app/view/game/tools.rb
this is quite useful for development, since i can never rememeber which hotseat i'm testing with
fixes #1009
> Add ability to rename games from within the hotseat

- assets/app/view/game/stock_market.rb
- lib/engine/config/game/g_1867.rb
- lib/engine/corporation.rb
- lib/engine/game/g_1867.rb
- lib/engine/share_price.rb
- lib/engine/step/g_1867/merge.rb
- lib/engine/stock_market.rb
Add support for conversion prices for minors
Add maximum stock price on minors
Add unlimited 7,8 9 track
Tidy up A17 & D2 tiles
> 1867: Add support for multiple types on stock price at same time

- assets/app/view/game/map_controls.rb
> Fix infinite screen redraw

- lib/engine/step/corporate_buy_shares.rb
It was possible for a corporation or player to be displayed and have no possible inputs ( due to not being able to afford any shares, for example ). This change ensures that if there are no actions possible, that entity is not displayed.
Before Change:
DSL only had $134, and thus could not afford DPAC or KPAC shares
After Change
> Corporate Share Buying: Fix Undefined Buttons and Useless Displays

- lib/engine/step/corporate_buy_shares.rb
Not sure how this disappeared but here it is again :D
> Fix Corporate Share Buy Missing Param ( very simple! )

- lib/engine/game/base.rb
- lib/engine/game/g_18_co.rb
- lib/engine/step/g_18_co/moving_bid_auction.rb
- lib/engine/step/g_18_co/return_token.rb
- lib/engine/step/g_18_co/special_track.rb
From https://github.com/tobymao/18xx/issues/2609
GJGR should close when the ability is used ( town upgraded )
DNPR should close when the ability is used ( token returned )
LNPW should close when the ability is used ( tile laid )
DSNG should be removed if DRGR is not purchased in the auction
> 18CO Company Closings ( with bonus base corporation_close fix! )

- lib/engine/config/game/g_1817_wo.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1817_wo.rb
- lib/engine/step/g_1817_wo/buy_sell_par_shares.rb
This is a re-implementation of https://github.com/tobymao/18xx/pull/2618
>... This is the last of the 1817WO rules needed to be implemented
> 1817WO - Corporation starting in Nieuw Zeeland places second token when buying tokens

- assets/app/view/game/part/track.rb
- assets/app/view/game/part/track_node_path.rb
- lib/engine/config/game/g_1849.rb
- lib/engine/game/g_1849.rb
- lib/engine/part/path.rb
- lib/engine/share_price.rb
- lib/engine/tile.rb
- spec/lib/engine/tile_spec.rb
Adds a barebones 1849 configuration as a PoC for the Tile/Path/Track updates
to support other gauges.
> Preliminary work for 1849

- assets/app/view/welcome.rb
- lib/engine/game/g_1860.rb
- lib/engine/step/g_1860/buy_sell_par_shares.rb
- lib/engine/step/g_1860/home_track.rb
Moves 1860 to alpha dev stage
Fixes issue with wrong player laying tile for corporation when it floats
Fixes #1791
> 1860 moves to alpha

- lib/engine/game/g_18_co.rb
- lib/engine/step/g_18_co/buy_train.rb
From https://github.com/tobymao/18xx/issues/2609
This commit includes only the 18CO specific Emergency Buy implementation, split out from https://github.com/tobymao/18xx/pull/2634
> 18CO Emergency Buy Details

- assets/app/view/game/actionable.rb
- assets/app/view/game_card.rb
> Show hotseat game state on front page

- lib/engine/step/g_1817/conversion.rb
Implementation of the change suggested in https://github.com/tobymao/18xx/issues/2665
> Allow mergers in 1817 that end in the president holding 20%

- lib/engine/config/game/g_1817.rb
- lib/engine/config/game/g_1817_na.rb
- lib/engine/config/game/g_1817_wo.rb
> [1817, 1817WO] Ohio Bridge Company should only be usable once

- lib/engine/game/g_1817_wo.rb
This small fix got lost in code cleanup yesterday
> Fix interest discount in 1817WO being applied to every corp

- lib/engine/game/g_1889.rb
- lib/engine/game/g_18_tn.rb
- lib/engine/step/buy_company.rb
- lib/engine/step/g_1889/special_track.rb
> Bug Fix - 1889: fix active_players when Ehime Railway is sold

- lib/engine/part/city.rb
- lib/engine/share_pool.rb
- lib/engine/step/g_1867/merge.rb
- lib/engine/step/g_1867/post_merger_shares.rb
Mostly working, needs token reduction and share purchasing
> 1867: First pass on merger

- lib/engine/config/game/g_1817_wo.rb
Fixes https://github.com/tobymao/18xx/issues/2692
> Fix 1817wo ny name

- lib/engine/step/corporate_buy_shares.rb
- lib/engine/step/corporate_sell_shares.rb
Quality of life update for corporate share steps. It helps set the context of the action faster since your eyes are generally below the log.
From https://github.com/tobymao/18xx/issues/2671
> Corporate Shares - Button Text Update ... (simple PR)

- assets/app/view/game/buy_companies.rb
- spec/assets_spec.rb
Implementation of https://github.com/tobymao/18xx/issues/1153
> Hide other player's privates

- lib/engine/game/g_1817_wo.rb
Fixes https://github.com/tobymao/18xx/issues/2715
> Add wiki link for 1817WO

- lib/engine/config/game/g_18_co.rb
- lib/engine/step/g_18_co/dividend.rb
The DSNG closes when the company runs its first train, not buys, as it comes with a train, but starts on a yellow hex with no track.
Sorry @michaeljb another usage of company.abilities https://github.com/tobymao/18xx/pull/2545
> 18CO - Fix when the DSNG closes

- lib/engine/game/base.rb
Context: The DNSG has 20% presidency, two 20% shares and four 10% shares.
The assumption was made that the President's certificate would always have a higher percentage and thus price than any other share. However, in a game where there are shares with the same percentage, the President's cert could wind up anywhere in the shares list. This could cause any or all bundles to contain the President's certificate.
The sorting at the end handles out of order partial bundles, because the partialing occurs as the last bundle added but could be a lower percentage.
---
Before
After
> Fix all_bundles_for_corporation sorting when same % share exists

- assets/app/view/game/corporation.rb
- lib/engine/corporation.rb
- lib/engine/g_1856/corporation.rb
- lib/engine/g_1856/share_pool.rb
- lib/engine/game/g_1856.rb
- lib/engine/round/g_1856/operating.rb
- lib/engine/step/g_1856/buy_sell_par_shares.rb
1856 corporations are full cap, incremental cap, or escrow based on the facing train at presidency purchase
> 1856 variable cap

- lib/engine/config/game/g_1856.rb
- lib/engine/game/g_1856.rb
- lib/engine/step/g_1856/assign.rb
This implements the functionality for the 4 "small" (not bridge, not tunnel) privates
> 1856 small privates

- lib/engine/config/game/g_1867.rb
- lib/engine/game/g_1867.rb
Nationalization should replace with CN tokens while available or reserved.
Cannot start corporations on cities with other corporations
> 1867: Nationalization tokens

- lib/engine/g_1856/corporation.rb
- lib/engine/game/g_1856.rb
- lib/engine/step/g_1856/buy_sell_par_shares.rb
The CGR will (might not!) be floated during nationalization. Until then, cannot par it
> CGR cannot be parred normally

- lib/engine/config/game/g_1856.rb
Goederich can be run through
Group Canadian West, Buffalo, and Lower Canada
> Fix offboards in 1856:

- lib/engine/config/game/g_18_co.rb
Two wording clarifications on company abilities to match the current rulebook.
Removal of a duplicated border.
> 18CO Config Updates ( Ability text, Duplicate Border Removal )

- assets/app/view/welcome.rb
- lib/engine/game/g_1817_na.rb
This PR will mark 1817NA as in production
> Mark 1817NA as production

- lib/engine/config/game/g_1817_wo.rb
I'm shocked this hasn't been reported yet; as-is the game cannot end
> 1817WO can actually end now

- assets/app/view/welcome.rb
- lib/engine/game/g_18_co.rb
- spec/assets_spec.rb
- spec/fixtures/18_co/0.json
- spec/fixtures/18_co/hs_ghyigehv_1608562373.json
- spec/lib/engine/games/game_spec.rb
Take 18CO: Rock & Stock to alpha!
> 18CO: Rock & Stock to Alpha

- lib/engine/config/game/g_1849.rb
- lib/engine/g_1849/stock_market.rb
- lib/engine/game/g_1849.rb
- lib/engine/step/g_1849/dividend.rb
- Par values become available with phases
- Blue zone on market blocked until 16H
- Share price moves right only if dividend >= price
- Also, fewer trains in 3p game
> 1849 share price behavior

- lib/engine/game/base.rb
- lib/engine/step/g_1867/single_item_auction.rb
Fix halt caused by home tokening twice
> Stop inability to create 1867 games

- lib/engine/step/g_1860/route.rb
Simple logging-only change.
Fixes #2786
> 1860: fix for logging leased trains

- spec/assets_spec.rb
- spec/fixtures/1860/19_354.json
- spec/lib/engine/games/game_spec.rb
Adding one test case for 1860.
> 1860 spec test case

- lib/engine/game/g_1849.rb
- Ports aren't sufficient to make a route.
- You can lay track that connects different track types, but not from the exit through which you gain access to the hex:
> Route requirements for track, ports

- lib/engine/game/g_18_mex.rb
- lib/engine/step/g_18_mex/assign.rb
See comment on the issue for how it looks like.
> 18MEX: Add help text for token removal (fixes #2706)

- lib/engine/game/g_1846.rb
- lib/engine/game/g_18_los_angeles.rb
https://boardgamegeek.com/thread/2565191/article/36583576#36583576
> 1846: Update text for company token removal event

- lib/engine/game/g_18_co.rb
Fix https://github.com/tobymao/18xx/issues/2819
> 18CO - Set DRGR to not contribute to player value

- lib/engine/game/g_1817.rb
- lib/engine/round/g_1817/stock.rb
- lib/engine/round/stock.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
fixes #2040 
Note these also apply to 1817NA and 1817WO
> 1817 optional rules

- assets/app/view/game/corporation.rb
- lib/engine/game/g_1860.rb
> 1860 show layer and par prices on corp cards

- lib/engine/step/g_18_co/takeover.rb
Fix https://github.com/tobymao/18xx/issues/2845
May break games in progress.
> Fix 2845 - 18CO DRGR private Should close on DSNG Takeover

- lib/engine/config/game/g_1824.rb
- lib/engine/g_1824/corporation.rb
- lib/engine/game/g_1824.rb
- lib/engine/round/g_1824/first_stock.rb
- lib/engine/step/g_1824/buy_pre_staatsbahnen.rb
- lib/engine/step/g_1824/buy_sell_par_shares.rb
- public/logos/1824/BH.svg
- public/logos/1824/BK.svg
- public/logos/1824/C1.svg
- public/logos/1824/C2.svg
- public/logos/1824/C3.svg
- public/logos/1824/C4.svg
- public/logos/1824/CL.svg
- public/logos/1824/K1.svg
- public/logos/1824/K2.svg
- public/logos/1824/KK.svg
- public/logos/1824/MS.svg
- public/logos/1824/S1.svg
- public/logos/1824/S2.svg
- public/logos/1824/S3.svg
- public/logos/1824/SB.svg
- public/logos/1824/SD.svg
- public/logos/1824/U1.svg
- public/logos/1824/U2.svg
- public/logos/1824/UG.svg
With the general commits pushed up at the same time it should be
possible to buy privates, buy mining corporations with initial
1g train.
Trains types and count, event info, tiles, map, corporations, minors
is there but much still remains.
> Initial commit for 1824

- assets/app/view/game/buy_companies_at_face_value.rb
- assets/app/view/game/round/stock.rb
- lib/engine/step/buy_sell_par_shares.rb
This is a preparation for 1824 which does not have an initial auction,
but instead the privates are sold together with shares during SR 1.
> Make it possible to sell unsold privates during SR.

- lib/engine/config/game/g_1867.rb
- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/merge.rb
- lib/engine/step/g_1867/post_merger_shares.rb
Ensure lock on Granby tile works (fixes #2887)
also tidys up the error message
> 1867 Bug Fixes part 2

- lib/engine/ability/README.md
- lib/engine/ability/train_discount.rb
- lib/engine/step/special_buy_train.rb
Add missing documentation.
Add new attribute that will control if the private with this ability
is closed or not when used up.
> Ability train_discount improvement

- Rakefile
- assets/app/mail/turn.rb
- assets/app/view/game_page.rb
- lib/engine/game/base.rb
- migrate_game.rb
- routes/game.rb
- spec/game_state_spec.rb
- spec/lib/engine/games/game_spec.rb
- validate.rb
> add new Game method to load game from JSON or DB

- assets/app/view/game/round/auction.rb
This is the first step towards some new functionality, but I didn't want to layer that in at the same.
1.) Fix the tiny bid increment bug. ( you had to manually type the true minimum )
2.) Rename step variable to increment so as not to confuse with @step
3.) Move the giant if statement for company actions into a fail first function
4.) Move bid-action lambdas into encapsulated functions
> Refactor view/Auction.rb

- assets/app/lib/settings.rb
- assets/app/view/game_page.rb
- assets/app/view/user.rb
- models/user.rb
> Make navbar purple (configurable) when in hotseat game and add [HOTSEAT] to round description

- lib/engine/config/game/g_18_co.rb
- lib/engine/game/g_18_co.rb
- lib/engine/step/g_18_co/takeover.rb
Both from https://github.com/tobymao/18xx/issues/2671
Do not show distribute log if there were no payouts
Add corporates shares open status
> 18CO - Two QoL Updates

- lib/engine/step/buy_sell_par_shares.rb
- lib/engine/step/g_1860/buy_sell_par_shares.rb
Fixes #2920 
Fixes #2928 
Add purchasable_unsold_companies to base and 1860
> 1860: Fix private companies offered for sale in SR

- lib/engine/step/buy_sell_par_shares.rb
- lib/engine/step/g_1817/special_track.rb
- lib/engine/step/g_1846/draft_2p_distribution.rb
- lib/engine/step/g_18_co/takeover.rb
see comments added at https://github.com/tobymao/18xx/pull/2918/files
> fix bad merge changes from #2918

- lib/engine/step/g_1860/buy_train.rb
> 1860: define president_may_contribute?

- lib/engine/step/g_1817/acquire.rb
> 1817: After merge on loan show the buyer (fixes #2965)

- lib/engine/step/g_1867/merge.rb
- lib/engine/step/g_1867/redeem_shares.rb
- lib/engine/step/g_1867/token.rb
Fix token log after merge
fixes #2791
> 1867: Don't log minors for skipping redeem and tokens.

- lib/engine/step/g_1867/buy_train.rb
> 1867: Players cannot contribute on EMR

- lib/engine/game/base.rb
Fixes bug introduced in a0ab6377b5399a45a7b32d5dc3aec0c01fa6554c.
> Priority deal marker at start of SR (fixes #2956)

- lib/engine/config/game/g_1882.rb
Change copy on private descriptions
Goal is to make them less of a "wall of text" while keeping the important bits
> [1882] make private descriptions a bit shorter and hopefully clearer

- lib/engine/config/game/g_18_mag.rb
- lib/engine/game/base.rb
- lib/engine/game/g_18_mag.rb
- lib/engine/publisher.rb
- public/logos/18_mag/1.svg
- public/logos/18_mag/10.svg
- public/logos/18_mag/11.svg
- public/logos/18_mag/12.svg
- public/logos/18_mag/13.svg
- public/logos/18_mag/2.svg
- public/logos/18_mag/3.svg
- public/logos/18_mag/4.svg
- public/logos/18_mag/5.svg
- public/logos/18_mag/6.svg
- public/logos/18_mag/7.svg
- public/logos/18_mag/8.svg
- public/logos/18_mag/9.svg
- public/logos/18_mag/mine.svg
First commits for 18Mag
game/base: allow empty privates
publisher: add Lonny
> 18Mag map and tiles

- lib/engine/config/game/g_18_co.rb
chatted with @ryandriskel via slack and got confirmation that these look good
> [18CO] tweak some colors and names

- lib/engine/step/g_1867/merge.rb
> 1867: Disallow convert while a merge is in progress

- lib/engine/g_1849/share_pool.rb
- lib/engine/game/g_1849.rb
- lib/engine/step/g_1849/swap_choice.rb
When the presidency changes and the incoming president has both the
double cert and two single certs, the outgoing president has the option
of exchanging the presidency cert for either.
> Last cert exchange

- lib/engine/step/g_1867/merge.rb
> 1867: Fix maximum merger price

- lib/engine/game/g_1849.rb
- lib/engine/part/path.rb
Also a couple bug fixes for track laying and corp removal.
> Messina earthquake

- lib/engine/config/game/g_18_sj.rb
- lib/engine/game/g_18_sj.rb
- lib/engine/publisher.rb
- lib/engine/round/g_18_sj/operating.rb
- lib/engine/step/g_18_sj/assign.rb
- lib/engine/step/g_18_sj/buy_company.rb
- lib/engine/step/g_18_sj/buy_sell_par_shares.rb
- lib/engine/step/g_18_sj/buy_special.rb
- lib/engine/step/g_18_sj/buy_train.rb
- lib/engine/step/g_18_sj/buy_train_action.rb
- lib/engine/step/g_18_sj/buy_train_before_run_route.rb
- lib/engine/step/g_18_sj/choose_priority.rb
- lib/engine/step/g_18_sj/dividend.rb
- lib/engine/step/g_18_sj/issue_shares.rb
- lib/engine/step/g_18_sj/route.rb
- lib/engine/step/g_18_sj/special_track.rb
- lib/engine/step/g_18_sj/waterfall_auction.rb
This more or less completes the implementation of 18SJ. There are
two things that are on draft, and which affect the common code but
I need to work more on those. (One is nationalization triggered by
phase change, and the other is discount for E train variant.)
The only common code change in this commit are addition of self
publisher as a publisher.
> Make 18SJ (almost) feature complete

- assets/app/view/welcome.rb
- lib/engine/game/g_18_sj.rb
- lib/engine/step/g_18_sj/buy_special.rb
- spec/fixtures/18SJ/shambolica_19.json
Added 18SJ as alpha.
Fixed one bug.
Added spec file.
> 18SJ: Alpha introduction

- lib/engine/game/base.rb
- lib/engine/game/g_1849.rb
- lib/engine/step/g_1849/bankrupt.rb
- lib/engine/step/g_1849/loan_choice.rb
Players either leave the game or take a loan if left with no assets
after corporation closure.
> Bankruptcy for 1849

- DEVELOPMENT.md
- lib/engine/step/g_18_co/moving_bid_auction.rb
- migrate_game.rb
Closes https://github.com/tobymao/18xx/issues/2864
If the player has all their cash committed, they cannot participate in the auction any more, so skip them.
This will probably break any active 18CO game where a player committed all their cash. Not sure how likely that is.
> 18CO Force Pass Player out of Cash

- lib/engine/step/g_1867/loan_operations.rb
- lib/engine/step/g_1867/major_trainless.rb
Add extra methods for stock round nationalization (fixes #3116)
Fix nationalization if cannot pay interest (fixes #3088)
> 1867 fixes not requiring migration/deletion

- lib/engine/config/game/g_1849.rb
- lib/engine/g_1849/stock_market.rb
- lib/engine/game/g_1849.rb
- lib/engine/share_price.rb
- lib/engine/step/g_1849/bankrupt.rb
- lib/engine/step/g_1849/buy_sell_par_shares.rb
- lib/engine/step/g_1849/buy_train.rb
Corporations that end up on the same stock market space after a series
of sales by the same player should retain the relative operating order
they had before the sales.
> Share value ordering

- lib/engine/step/g_18_mex/swap_buy_sell.rb
> Allow swap for 10% cert when at 55%

- lib/engine/config/game/g_1867.rb
- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/track.rb
- migrate_game.rb
- spec/fixtures/1867/21268.json
- spec/fixtures/1867/hs_ahjzadkh_19792.json
Add stubs to tiles (fixes #2884, needs migration on tile ids)
Hex L10 doesn't enforce tile rotation (fixes #3086)
Game doesn't end at correct point due to train export (fixes #3092)
> 1867: Fix bugs that might need migration/deletions

- lib/engine/game/g_1817.rb
> Avoid liquidating corporations already in the stock pool

- assets/app/view/game/game_log.rb
- assets/app/view/game/history_and_undo.rb
- assets/app/view/game/history_controls.rb
- assets/app/view/game/spreadsheet.rb
- assets/app/view/log.rb
- public/assets/main.css
@crericha is fine with undo instead of rewind
> chat maxwidth; review/undo buttons margins + positioning

- public/assets/main.css
> resizable chat/log

- assets/app/view/game_card.rb
> Show fallback game card on error

- lib/engine/game/g_18_mex.rb
- lib/engine/game/g_18_sj.rb
Bug was attempt to add minor's treasury of 0.
Fixed for 18SJ as well for KHJ merge.
> 18MEX: Fix bug with minor merge (fixes #3185)

- lib/engine/game/g_1817.rb
- lib/engine/game/g_1867.rb
- lib/engine/game/interest_on_loans.rb
- lib/engine/step/g_1867/buy_train.rb
- lib/engine/step/g_1867/post_merger_shares.rb
- migrate_game.rb
fixes #3145
Will probably need a migration
Allow ebuy of non-cheapest train #3113
> 1867: Don't pay interest on loans already taken since it's already paid

- assets/app/view/game/part/track.rb
> Render narrow gauge routes dashed

- lib/engine/config/game/g_1849.rb
> Fix Palermo yellow value

- lib/engine/g_1849/share_pool.rb
Fixes bug found in this game: https://18xx.games/game/22104
> Fix presidency swap

- lib/engine/round/g_1849/stock.rb
Previous change broke all other corps to fix AFG 🤦 🤦 🤦
> Fix RSA to work with all corps

- assets/app/view/game/game_log.rb
- assets/app/view/game/history_and_undo.rb
- public/assets/main.css
> revert chat/log maxwidth

- lib/engine/step/g_1817/acquire.rb
- migrate_game.rb
> 1817: Repeated log occurs if the buyer enters acquisition

- models/action.rb
- routes/game.rb
> Fix pinned games causing errors on second action

- assets/app/view/game/corporation.rb
- assets/app/view/game/spreadsheet.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1846.rb
- lib/engine/game/g_1856.rb
- lib/engine/game/g_1860.rb
- lib/engine/game/g_1867.rb
- lib/engine/game/g_18_los_angeles.rb
- lib/engine/round/g_1817/operating.rb
- lib/engine/round/g_1846/operating.rb
- lib/engine/round/g_1856/operating.rb
- lib/engine/round/g_1860/operating.rb
- lib/engine/round/g_1867/operating.rb
- lib/engine/round/operating.rb
Move operating order customization into the base class
(fixes #883)
> Display operating order when in stock round

- lib/engine/g_1849/corporation.rb
- lib/engine/game/g_1849.rb
> Move corp init to initialize

- lib/engine/g_1849/share_pool.rb
- lib/engine/game/g_1849.rb
Fixes selling down to 10% from >20% when incoming pres has only double
cert. Also fixes buying double cert from market.
Fixes #3231
> Double cert bug fixes

- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/loan_operations.rb
- lib/engine/step/g_1867/post_merger_shares.rb
- migrate_game.rb
Correct loan amount after loan payment (fixes #3227)
Don't make a player pass twice consequtively buying shares post merger (fixes #3156)
> 1867 bugs + move to beta

- lib/engine/config/game/g_1817.rb
- lib/engine/config/game/g_1817_na.rb
- lib/engine/config/game/g_1817_wo.rb
- lib/engine/game/g_1817.rb
- lib/engine/step/g_1817/acquire.rb
- lib/engine/step/g_1817/buy_sell_par_shares.rb
- migrate_game.rb
- spec/fixtures/1817/15528.json
- spec/fixtures/1817WO/19926.json
Don't close bank shorts if in acq or liq (fixes #3240)
Correct corporation abilities timing (fixes #2570)
Allow short followed by sell (fixes #3105)
Will need quite a few pins since quite a few people cheated :)
> 1817(+NA/WO) bugs needing migration/pins

- assets/app/view/game/spreadsheet.rb
- lib/engine/game/g_1817.rb
Add buying power to spreadsheet (fixes #2663)
Add shorts to spreadsheet (fixes #2371)
Add sortation of buying power, shorts and loans (fixes #2152)
> 1817: Spreadsheet improvements

- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/dividend.rb
large go 4 steps, all others 2 steps
> 18CZ Added Basic Dividend Implementation

- lib/engine/game/g_1867.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/game/g_18_los_angeles.rb
- lib/engine/game/stubs_are_restricted.rb
@jenf Is that all thats needed? It was all I found in 1867
> 18CZ Added Restrictions for stubs

- lib/engine/step/g_1849/buy_sell_par_shares.rb
> Sort before checking buyability

- lib/engine/game/g_1849.rb
> Reset @afg after closure

- lib/engine/game/g_1849.rb
- lib/engine/part/path.rb
Fixes #3282 
Also fixes the same problem for track laying.
> path.walk checks track

- lib/engine/config/game/g_1849.rb
- lib/engine/game/g_1849.rb
> Change gray revenue colors

- lib/engine/game/g_1849.rb
- lib/engine/step/g_1849/home_token.rb
> Fix AFG-RSA token placement

- TILES.md
- lib/engine/config/game/g_18_cz.rb
Impassable is not the correct type. So for now I added some 'random' border type.
> 18CZ Fixed tile Type and typo in tile.md

- lib/engine/config/game/g_1882.rb
fixes #3274
needs migrations & pins
> 1882 NWR Ability timing

- lib/engine/game/g_1849.rb
> Remove closed AFG from round after quake

- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/buy_train.rb
Fixed Buying of trains.
Corporations can buy other trains but have to buy at least one runnable train
> 18CZ Fixed Buying of trains

- lib/engine/game/g_1828.rb
- lib/engine/round/g_1828/stock.rb
- lib/engine/step/g_1828/merger.rb
- lib/engine/step/g_1828/waterfall_auction.rb
- spec/lib/engine/games/g_1828_spec.rb
See commit descriptions for a list of fixes
> 1828: Round of bug fixes [fixes #3343, fixes #3346]

- lib/engine/config/game/g_1828.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1828.rb
- lib/engine/step/tracker.rb
Move the ability blocking logic to game class to make it possible.
Tested with 1846 O&I and 1828 with other corporations/locations.
> 1828: Allow C&P to lay on its blocked hex. 

- lib/engine/config/game/g_18_co.rb
The hex had a double mountain edge
fixes #3334
> [18CO] fix I15 hex

- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/reduce_tokens.rb
Fix CN not placing token in Montreal (fixes #3349)
Add help text on merger for token removal (fixes #3287)
> 1867 bugs/improvements

- lib/engine/game/g_1849.rb
> Prevent RSA double fund

- lib/engine/config/game/g_1835.rb
- lib/engine/game/g_1835.rb
I'm working through the abandoned 1835 data file which didn't actually work out of the box and which was padded with a bunch of placeholder data. 
I've stripped it right back to something which works well enough to display a trivial map/market and am committing this  ahead of slowly working through checking all the data against my copy and I'll submit them as a series of small merges which will be easier to review.
> First commit for 1835

- assets/app/view/user.rb
- models/user.rb
- routes/user.rb
Caveats as discussed earlier.
fixes #3319
> login with username

- assets/app/view/flash.rb
> prevent flash from being cut off on mobile

- lib/engine/config/game/g_1835.rb
Needs a pass for names, missing some terrain and rivers, and needs a
full check for correctness and rendering bugs.
> Adding all the basic 1835 map hexes.

- lib/engine/step/g_1817/acquire.rb
> 1817: Fix cash crisis when corp is in market

- assets/app/view/welcome.rb
- lib/engine/game/g_18_mag.rb
Take 18Mag to alpha
Fixed pointer to rules
> 18Mag: alpha release

- lib/engine/config/game/g_18_mag.rb
2T should cost 80, not 480!
Fixed #3414
> 18Mag: fix 2T price

- lib/engine/config/game/g_18_mag.rb
> 18Mag: fix label on tile L35

- lib/engine/config/game/g_18_co.rb
Fix https://github.com/tobymao/18xx/issues/3396
> 18CO DNP Private Text (Trivial)

- lib/engine/game/g_1817_wo.rb
This is overdue at this point, there is a fixture already for 1817WO as well
> Make 1817WO beta

- lib/engine/game/g_1867.rb
- lib/engine/game/g_1882.rb
> 1867/1882: Fix simplified view of neutral tokens

- lib/engine/game/base.rb
- lib/engine/game/g_1828.rb
- lib/engine/phase.rb
- lib/engine/step/g_1828/buy_train.rb
- lib/engine/step/g_1828/merger.rb
Tested moving private close on train buy with 18Chesapeake and 1849.
> 1828: Bug fixes

- lib/engine/config/game/g_18_cz.rb
- lib/engine/game/base.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/phase.rb
- lib/engine/step/g_18_cz/token.rb
Added Rusting of trains (fixed from last PR)
city for ATE home token can be chosen
B9 can only be tokened when ATE has home token
Added revenue for E trains  and offboard bonus
> 18CZ - More Implementation

- lib/engine/step/g_18_mag/simple_draft.rb
> 18Mag: fix 6p minor count

- assets/app/view/game/bank.rb
- assets/app/view/game/corporation.rb
- assets/app/view/game/entities.rb
- lib/engine/config/game/g_1867.rb
- lib/engine/corporation.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1861.rb
- lib/engine/game/g_1867.rb
Using the 1867 config until most of the national corporation stuff is done
Show the CN 'national' in the UI
Set the PD to be the operator of the CN
> Initial work on 1861

- lib/engine/step/g_18_mag/route.rb
Use slightly more flexible item parsing for special buys
> 18Mag: fix rail-car special buy parsing

- lib/engine/step/track.rb
> 1846: Fix second tile lay to allow upgrades on the same tile

- lib/engine/step/g_1849/track.rb
> Fix SMS after it was broken

- assets/app/view/game/convert.rb
- assets/app/view/game/round/operating.rb
- lib/engine/config/game/g_18_fl.rb
- lib/engine/game/g_18_fl.rb
- lib/engine/step/g_18_fl/buy_sell_par_shares.rb
- lib/engine/step/g_18_fl/convert.rb
- lib/engine/step/g_18_fl/dividend.rb
- public/logos/18_fl/ACL.svg
- public/logos/18_fl/FECR.svg
- public/logos/18_fl/LN.svg
- public/logos/18_fl/Plant.svg
- public/logos/18_fl/SAL.svg
- public/logos/18_fl/SR.svg
There's not too much to 18FL outside of the hotels and initial auction. I included the 5 -> 10 share conversions in this PR because it was pretty simple once it was implemented and working
> 18FL Initial commit

- lib/engine/game/g_18_fl.rb
- lib/engine/step/g_1836jr30/buy_train.rb
- lib/engine/step/g_18_fl/buy_sell_par_shares.rb
- lib/engine/step/g_18_fl/buy_train.rb
3E must hit at least 2 paying revenue centers
One train of a type / OR like 36, except 6/3E are exempt from this
A few bug fixes
> 18FL train buy updates

- lib/engine/game/g_1856.rb
Steve U warned me about this issue in 1856
> Fix server-side-only issue with 1856

- lib/engine/config/game/g_1861.rb
- lib/engine/game/g_1861.rb
There's no changes from 1867 at this point, it's identical
> Add 1861 config

- lib/engine/step/g_1849/track.rb
> 1849 - Remove cost from tiles after upgrade

- assets/app/view/game/player.rb
Fix https://github.com/tobymao/18xx/issues/3520
> 18CO - Fix 3520 - Priority Pass Order Display

- lib/engine/config/game/g_1861.rb
- lib/engine/game/g_1861.rb
- lib/engine/game/g_1867.rb
Change the tile manifest
Add the 2d market
Change the phase and train limits
> 1861 tiles market

- lib/engine/config/game/g_1849_boot.rb
Move ATA to Cantazaro
Move P1 from Salerno to Caserta
> 1849K2S Balance Changes

- lib/engine/game/g_1860.rb
Addresses #3374 
Changed text for SR endgame trigger to be less ambiguous.
> 1860: event_southern_forms text change

- lib/engine/game/g_1860.rb
- lib/engine/round/g_1860/operating.rb
Fixes #3576 
Fixes #3578
It is possible that pins will be required.
> 1860: fix bankruptcy bugs

- lib/engine/corporation.rb
- lib/engine/g_1867/stock_market.rb
- lib/engine/game/g_1867.rb
- lib/engine/step/g_1867/buy_sell_par_shares.rb
- lib/engine/step/g_1867/merge.rb
- lib/engine/stock_market.rb
Also tidy up how 1867 did the max stock market price
> 1861: Implement moves, mergers for 2d market.

- lib/engine/config/game/g_1861.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1861.rb
- lib/engine/game/g_1867.rb
- public/logos/1861/E.svg
- public/logos/1861/GR.svg
- public/logos/1861/KB.svg
- public/logos/1861/KK.svg
- public/logos/1861/KP.svg
- public/logos/1861/KR.svg
- public/logos/1861/MK.svg
- public/logos/1861/MKN.svg
- public/logos/1861/MKR.svg
- public/logos/1861/MKu.svg
- public/logos/1861/MNN.svg
- public/logos/1861/MV.svg
- public/logos/1861/MVR.svg
- public/logos/1861/N.svg
- public/logos/1861/NW.svg
- public/logos/1861/OK.svg
- public/logos/1861/RO.svg
- public/logos/1861/RSR.svg
- public/logos/1861/SE.svg
- public/logos/1861/SPW.svg
- public/logos/1861/SV.svg
- public/logos/1861/SW.svg
- public/logos/1861/TR.svg
- public/logos/1861/V.svg
- public/logos/1861/Y.svg
- scripts/generate_logos.rb
Add 1861 corporations
Add 'simple' logos for 1861
Add script to generate simple logos
Fix ruby sym lookup
> 1861 corporations

- lib/engine/config/game/g_1822.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1822.rb
- lib/engine/route.rb
- lib/engine/step/g_1822/dividend.rb
- lib/engine/train.rb
**The problem:**
The rules states the following description of a Local train.
5.5.3 L (local) trains run in a city which has a station token of the owning (minor or major) company. They can additionally run to a single small station, but are not required to do so. They can thus be considered 1 (+1) trains. Only one L train may operate on each station token.
**The solution:**
I really tried to see as many solutions as possible to touch the base code as little as possible. But In the end i had to include some, there was no support for a route when pressing the first city or method in base game class  i could override to get it to work.
First there is a new method the train, local?. Here i try to do it in the most generic way. I look at the distance of the train, is it 1 then its a local. If …
> [1822] Half dividend and local trains

- lib/engine/game/g_18_mag.rb
- lib/engine/step/g_18_mag/dividend.rb
- lib/engine/step/g_18_mag/route.rb
- lib/engine/step/g_18_mag/simple_draft.rb
- Tiles, hexes, minors, corps, trains, market and phases are all a function of multiplayer or not.
- RABA and LdStEG corps behave slightly differently.
- Snake order for draft round
Drastically smaller map:
> 18Mag: implement 2P

- lib/engine/game/g_18_mag.rb
> 18Mag: fix 2P train power descriptions

- lib/engine/game/g_18_cz.rb
There's no "50% limit of shares in the pool", you can sell everything but the presidency into the pool
> [18cz] unlimited number of shares can be in the pool

- lib/engine/config/game/g_1861.rb
- lib/engine/game/g_1861.rb
- lib/engine/game/g_1867.rb
concludes implementation and closes #3229
> 1861: Finish end game, fix a few dollars to rubles and move to alpha

- lib/engine/step/g_1861/buy_train.rb
> 1861: Disallow buying trains from RSR

- assets/app/view/game/map.rb
- assets/app/view/game/map_controls.rb
- assets/app/view/game/map_zoom.rb
Follow-up to #3489
100 % zoom (default):
62 % zoom:
> zoom controls on map

- lib/engine/step/g_1867/merge.rb
- lib/engine/step/g_1867/reduce_tokens.rb
- lib/engine/step/token_merger.rb
> 1867: Enforce the one token per hex rule after a merger

- assets/app/app.rb
- assets/app/view/chat.rb
- assets/app/view/form.rb
- assets/app/view/game_page.rb
- assets/app/view/navigation.rb
- assets/app/view/welcome.rb
- public/assets/main.css
removal of some hacks, still ensuring 1rem margin between elements
> harmonize header/content margins

- lib/engine/config/game/g_1861.rb
- lib/engine/game/g_1867.rb
- public/logos/1861/RSR.svg
- scripts/generate_logos.rb
Remove reservations from minors after they cannot be started (fixes #3669)
Change RSR from 1867 color to 1861 color (fixes #3661)
> 1861 bugs:

- lib/engine/config/game/g_1877.rb
> Revert "1877 Move city from c6 to c4, rename cities"

- assets/app/view/user.rb
- public/assets/main.css
some structural simplifications, some pixel pushing
> profile review

- lib/engine/game/g_1861.rb
- lib/engine/game/g_1867.rb
Game doesn't end at right point (fixes #3674)
Nationalized privates should go to RSR (fixes #3675)
Add RSR to the spreadsheet (fixes #3660)
> 1861 bug fixes:

- lib/engine/game/base.rb
> Store player history at end of game

- lib/engine/step/g_1817/buy_sell_par_shares.rb
- lib/engine/step/g_1817_wo/buy_sell_par_shares.rb
fixes #3526
@ventusignis https://github.com/tobymao/18xx/blob/01ffdc3cd4b9d54ad8e741d1927535f5c8b45ebf/lib/engine/game/g_1856.rb#L884 affected, too?
> 1817: token(s) (fixes #3526)

- assets/app/view/game/stock_market.rb
- lib/engine/game/g_18_mag.rb
- lib/engine/step/g_18_mag/dividend.rb
- lib/engine/step/g_18_mag/route.rb
1. Check to see if all purchased rail-car benefits are actually used when routes are submitted
2. Replace the word "Moscow" on the map. Apparently it's offensive to Hungarians.
3. Add the price movement chart to the stock market tab
> 18Mag: Rule tweaks from Lonny

- lib/engine/config/game/g_1893.rb
- lib/engine/game/g_1893.rb
This commit contains the following:
- Map and tiles, including variations for 2 optional rules
- 3 optional rules
- Private companies
- Minors
- Corporations
- Buy blocked for corporations in the beginning
- Info
- Stock market
- Certificate limits 2-4 players
- Bank limit
- Starting money 2-4 players
Crucial things missing:
- Logos for minors and corporations
- Bonds
- Drafting not auction
- Starting package
- Formation and merge of AGV and HGK
- End game
- ....
> 1893: Initial commit

- assets/app/view/game/hex.rb
- lib/engine/action/hex_token.rb
- lib/engine/config/game/g_18_fl.rb
- lib/engine/game/g_18_fl.rb
- lib/engine/step/g_18_fl/token.rb
- lib/engine/step/tokener.rb
> 18 fl hotels

- assets/app/view/game/game_log.rb
- assets/app/view/game_page.rb
> store scroll position on tab change

- lib/engine/game/g_18_mex.rb
- lib/engine/step/g_18_mex/merge.rb
Set cost to free when putting out NdM tokens.
> 18MEX: Fix merge bug (fixes #3175)

- lib/engine/step/g_1867/token.rb
> 1867: Token step gets skipped if corp has exact cash for token

- assets/app/view/welcome.rb
- lib/engine/game/g_1860.rb
- lib/engine/game/g_18_mag.rb
I left the 1860 kickstarter notice up. It should probably be removed tonight.
> Move 1860 to production; 18Mag to beta

- lib/engine/config/game/g_1830.rb
- lib/engine/game/g_1830.rb
- lib/engine/publisher.rb
- public/logos/1830/BM.svg
- public/logos/1830/BO.svg
- public/logos/1830/CO.svg
- public/logos/1830/CPR.svg
- public/logos/1830/ERIE.svg
- public/logos/1830/NYC.svg
- public/logos/1830/NYNH.svg
- public/logos/1830/PRR.svg
Initial config. In theory all the privates are correct but I need to test them.
> Initial 1830 config

- lib/engine/game/g_1830.rb
> [1830] small typo in location

- assets/app/view/game/abilities.rb
- lib/engine/ability/README.md
- lib/engine/ability/sell_company.rb
- lib/engine/config/game/g_18_cz.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/sell_company.rb
In 18CZ a company can be sold from the corporation to the bank for face value
> 18CZ added Selling ability to companies

- lib/engine/config/game/g_1849.rb
- lib/engine/config/game/g_1849_boot.rb
- public/logos/1849/AFG.alt.svg
- public/logos/1849/ATA.alt.svg
- public/logos/1849/CTL.alt.svg
- public/logos/1849/IFT.alt.svg
- public/logos/1849/RCS.alt.svg
- public/logos/1849/SFA.alt.svg
- public/logos/1849_boot/BTR.alt.svg
- public/logos/1849_boot/TSR.alt.svg
Fixes https://github.com/tobymao/18xx/issues/3745
> Add simple logos for 1849 and 1849K2S

- assets/app/view/game/bank.rb
- lib/engine/game/g_1817.rb
- lib/engine/game/g_1817_na.rb
- lib/engine/game/g_1817_wo.rb
fixes #3186
Also change 1817NA and 1817WO to use common code for loan calculations
> 1817: Add expandable full loan table

- lib/engine/game/g_18_fl.rb
EBUY_OTHER_VALUE was defined twice
> Fix build warning in 18FL

- assets/app/view/game/round/auction.rb
- lib/engine/game/g_18_fl.rb
- lib/engine/step/g_18_fl/buy_cert.rb
It's a thing now.
I created an option for a game to use choos-ey buttons instead of a number box. Having to use the number box to choose between only 3 valid choices was annoying
> 18fl private auction

- lib/engine/game/g_18_chesapeake_off_the_rails.rb
> [18ChesOTR] update info page since trains are not exported

- lib/engine/player_info.rb
> Output SR# instead of SR#.X

- lib/engine/config/game/g_18_cz.rb
This didn't get included in https://github.com/tobymao/18xx/pull/3801
> [18cz] fix terrain discount

- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/buy_corporation.rb
- lib/engine/step/g_18_cz/home_track.rb
- lib/engine/step/g_18_cz/sell_company_and_special_track.rb
- lib/engine/step/g_18_cz/upgrade_or_discard_train.rb
- lib/engine/step/tracker.rb
Fixed some issues that came through teleport refactoring, and some general issues.
Should now be alpha stable.
I will make a test game tomorrow (if merged)  or you can just "release" it.
> 18CZ Fixed issues

- lib/engine/config/game/g_18_eu.rb
Towns do not count against length.
> 18EU - Fix train definition

- lib/engine/config/game/g_1860.rb
- lib/engine/game/g_1860.rb
> 1860: fix redefinition of MUST_SELL_IN_BLOCKS error

- assets/app/view/welcome.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/sell_company_and_special_track.rb
I know there is a bug in a game, but I think it is still good enough for alpha
> 18CZ Alpha ready

- lib/engine/config/game/g_1828.rb
Based on the [live rules link](https://kanga.nu/~claw/1828/1828-Rules.pdf)
> [1828] fix place name Copper county/country

- assets/app/view/game/stock_market.rb
- lib/engine/game/g_1867.rb
Generalize the approach taken for 18CZ
fixes #3635
> Switch 1861/67 to use Crosshatch for the convert range

- lib/engine/config/game/g_18_cz.rb
It's a green city, so s.b. `30` (green dits are `20`)
closes #3881
> [18CZ] fix revenue for 14p

- assets/app/view/game/upgrade_or_discard_trains.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/buy_corporation.rb
- lib/engine/step/g_18_cz/dividend.rb
- lib/engine/step/g_18_cz/reduce_tokens.rb
- lib/engine/step/g_18_cz/sell_company_and_special_track.rb
- lib/engine/step/g_18_cz/upgrade_or_discard_train.rb
- lib/engine/step/token_merger.rb
closes #3871, #3877, #3880, #3887, #3879, #387, #3870
This will break nearly all games left OR1.
> 18CZ Fix some issues

- assets/app/view/game/spreadsheet.rb
> spreadsheet: fix sort when same stock price

- assets/app/view/game/tools.rb
> add wiki-link hotkeys/shortcuts to tools

- assets/app/view/game/spreadsheet.rb
> add legend to OR history

- assets/app/view/game/spreadsheet.rb
- lib/engine/game/g_1860.rb
- lib/engine/step/dividend.rb
- lib/engine/step/g_1860/dividend.rb
> Revert "Operating info fix"

- lib/engine/config/game/g_18_cz.rb
> [18CZ] fix 888p tile

- assets/app/view/game/spreadsheet.rb
> spreadsheet sort all columns

- public/logos/18_co/UP.alt.svg
Fix https://github.com/tobymao/18xx/issues/3931
> 18CO Fix 3931 UP More Distinct Token Color

- lib/engine/step/g_18_cz/home_track.rb
> [18CZ] large companies can lay a token on their first turn

- lib/engine/step/g_18_cz/buy_corporation.rb
Cleans up certs, etc fixes #3916
> [18CZ] fully close corps when bought in

- lib/engine/step/g_18_cz/buy_corporation.rb
- lib/engine/step/g_18_cz/upgrade_or_discard_train.rb
> 18CZ Fixed Upgrade And Discard Step

- lib/engine/game/g_18_cz.rb
> 18CZ Fixed Runnable Trains

- lib/engine/game/g_18_cz.rb
> [18CZ] allow purple upgrade from double-dit to green dit

- lib/engine/step/g_18_cz/buy_corporation.rb
> [18CZ] after acquisition, buyer must pay 100 for future tokens

- assets/app/view/game/spreadsheet.rb
- lib/engine/game/g_1860.rb
- lib/engine/step/dividend.rb
- lib/engine/step/g_1860/dividend.rb
Third time's a charm (I hope...)
> Operating info fix

- public/assets/main.css
> improve rendering of color inputs on Chrome/Safari

- assets/app/view/game/map.rb
- assets/app/view/game/tile_confirmation.rb
> fix tile confirmation dialog being cut off on top row

- lib/engine/step/g_18_cz/buy_corporation.rb
- lib/engine/step/g_18_cz/buy_train.rb
- lib/engine/step/g_18_cz/reduce_tokens.rb
> 18CZ Fixed more bugs

- lib/engine/config/game/g_18_cz.rb
> [18CZ] fix train rust schedule

- assets/app/view/welcome.rb
- lib/engine/game/g_1830/meta.rb
- lib/engine/game/g_18_co/meta.rb
> 18CO to prod, 1830 to beta

- assets/app/view/game/abilities.rb
- lib/engine/game/g_1846/game.rb
- lib/engine/game/g_1846/step/special_track.rb
- lib/engine/step/track_and_token.rb
- lib/engine/step/tracker.rb
> Restore "[1846] Fix LSL invalid tile lay"

- lib/engine/game/g_1828/game.rb
- lib/engine/game/g_1828/step/buy_sell_par_shares.rb
- lib/engine/game/g_1828/step/company_pending_par.rb
- lib/engine/game/g_1828/step/exchange.rb
- lib/engine/game/g_1828/stock_market.rb
- lib/engine/game/g_1849/game.rb
- lib/engine/game/g_1849/step/buy_sell_par_shares.rb
- lib/engine/game/g_1849/step/company_pending_par.rb
- lib/engine/game/g_1849/stock_market.rb
- spec/lib/engine/games/g_1828_spec.rb
> Restore "Convert 1828.Games and 1849 to use par groups for phased par values""

- lib/engine/config/game/g_18_cz.rb
- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/buy_train.rb
- lib/engine/step/g_18_cz/upgrade_or_discard_train.rb
- lib/engine/step/train.rb
Phew...
I bet there are still problems left. But that is a big step into fixing.
The problem is that trains can rust at completly different times, so I have to add all following trains to the rusting.
Also it is possible to buy a variant of a train which one variant is rusted but the other variant is not rusted.
Upgrading the train also triggers rusting https://boardgamegeek.com/thread/1890183/article/27537048#27537048
The game_page rusting info is now completely empty =/ But I will fix that another time
> 18CZ Fixed rusting

- lib/engine/game/g_18_cz.rb
- lib/engine/step/g_18_cz/dividend.rb
Closes #4015
Now the correct float value is calculated, displayed and then the sum is rounded correctly
> 18CZ Fixed Dividend rounding

- lib/engine/config/game/g_18_cz.rb
You can upgrade towns as well as cities
> [18cz] clarify private descriptions

- assets/app/view/game_page.rb
scroll to top & game_menu when loading a game or switching tabs
> scroll to game menu

- assets/app/view/game_page.rb
> Revert "scroll to game menu"

- assets/app/view/game/game_info.rb
- public/assets/main.css
- spec/fixtures/18CZ/hs_gwurdqhs_1613616655.json
The old info looks exactly the same.
18CZ looks like that
Also addes a basic fixture
> Updated rusting game info for 18CZ

- lib/engine/game/g_1828/game.rb
- lib/engine/game/g_1828/meta.rb
As suggested in section "4 Setup" of the rules.
Hopefully this is trivial enough to sneak through code freeze.
> 1828: Ensure Good Privates option

- lib/engine/game/g_18_cz.rb
> [18CZ] Fix Purple Upgrade ability for Town Tiles

- lib/engine/step/g_18_cz/buy_train.rb
> [18CZ] Fix buying of wrong variants with too less cash

- lib/engine/config/game/g_18_cz.rb
> [18CZ] tweak private text

- assets/app/view/game/spreadsheet.rb
fixes #4112
… hm, need to check edge cases. I’ll merge it myself when done.
> spreadsheet: sort trains alphanumeric

- assets/app/view/game_page.rb
> fix private notes / chat enter regression

- lib/engine/step/g_18_cz/draft.rb
Small one are always one top etc.
closes #4132
> [18CZ] Fixed Sorting of privates

- assets/app/view/form.rb
- assets/app/view/game/async.rb
- lib/engine/action/program_merger_pass.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817/game.rb
- lib/engine/game/g_1817/round/acquisition.rb
- lib/engine/game/g_1817/round/merger.rb
- lib/engine/game/g_1817/step/acquire.rb
- lib/engine/game/g_1817/step/conversion.rb
- lib/engine/game/g_1867/game.rb
- lib/engine/game/g_1867/round/merger.rb
- lib/engine/game/g_1867/step/merge.rb
- lib/engine/round/base.rb
- lib/engine/round/merger.rb
- lib/engine/step/program.rb
- lib/engine/step/programmer_merger_pass.rb
Also loads the settings from stock round programmed action and slightly tidy the UI
> Add programmable action to pass 1817 MA and 1867 MA rounds

- assets/app/view/game/dividend.rb
- assets/app/view/game/route_selector.rb
- assets/app/view/game/stock_market.rb
- lib/engine/game/g_1849/game.rb
- lib/engine/game/g_1860/step/route.rb
- lib/engine/game/g_1873/game.rb
- lib/engine/game/g_18_mag/game.rb
- lib/engine/game/g_18_mag/step/dividend.rb
Discussion: https://18xxgames.slack.com/archives/G017LJQ2DSA/p1614114302161200
ante:post
> dividend and revenue charts: styling, position, wording

- assets/app/view/game/auto.rb
- assets/app/view/game_page.rb
- spec/assets_spec.rb
Add asset specs to ensure the auto page gets displayed correctly
> Rename async to auto for the UI and add asset specs

- lib/engine/game/g_1817/game.rb
fixes #4148
I've run all 1817 games, no games break because of it (which makes sense)
> 1817 Close shorts after sale

- lib/engine/game/g_1846/step/buy_company.rb
- lib/engine/step/tokener.rb
> Revert "1846: Show tokens gained from privates on corporation charter. #3327"

- lib/engine/step/buy_sell_par_shares.rb
- spec/lib/engine/round/stock_spec.rb
the game gets stuck
fixes #4138
> Players only must sell if they can actually sell anything, otherwise

- lib/engine/game/g_1846/step/buy_company.rb
- lib/engine/step/tokener.rb
> Restore "1846: Show tokens gained from privates on corporation charter. #3327""

- lib/engine/game/g_1822/game.rb
> [1822] London and bids

- lib/engine/game/g_1822/game.rb
- Added a check to only check exchange tokens for a corporation.
> [1822] Added an exchange token check

- lib/engine/game/g_1822/game.rb
- Improved the names of the companies in the timeline info. Separated the company name from timeline to get more flexibility what short names we want to use in this view.
fixes #4207
> [1822] Improved the timeline

- lib/engine/game/g_18_cz/game.rb
> [18CZ] can only run each distinct city of praha once

- lib/engine/game/g_1822/game.rb
- lib/engine/game/g_1822/step/minor_acquisition.rb
- Fixed a very small issue with a text did show correctly in the log.
fixes #4219
fixes #4224
> [1822] English channel

- assets/app/view/game/player.rb
- lib/engine/game/g_18_cz/game.rb
Adjusted 18CZ for the 1822 player dept display and added player_interest
Closes #3917
> [18CZ ] Adjusted for debt and added interest

- lib/engine/game/g_1822/game.rb
- lib/engine/game/g_1822/round/operating.rb
- lib/engine/game/g_1822/step/buy_sell_par_shares.rb
> [1822] Cert limit and corporation reorder

- lib/engine/game/g_18_cz/step/buy_corporation.rb
closes #4209
This could break games
> [18CZ] Added validation for buying a corporation

- assets/app/view/game/game_info.rb
> game info: progress bar moved to timeline

- assets/app/view/game/buy_trains.rb
- lib/engine/game/g_1822/round/operating.rb
- Remove a check and didnt test all possilties I could think of in my last reorder PR. Im usually not this sloppy, will test better.
> [1822] Corporation reorder

- lib/engine/game/g_1822/game.rb
- You should be able to hit both towns on a double town hex.
fixes #4246
> [1822] Run twice on hex

- lib/engine/game/g_18_cz/game.rb
The rules provide 2 ways of currency display, but the new one is on all the cards and trains etc.
> [18CZ] Fixed Currency Display

- assets/app/view/game/game_log.rb
- assets/app/view/game_page.rb
> store chat input on tab change

- lib/engine/game/g_1817/step/buy_sell_par_shares.rb
> 1817: Try to buy tokens when a share is purchased

- lib/engine/game/g_18_cz/game.rb
- lib/engine/game/g_18_cz/step/upgrade_or_discard_train.rb
Needed to nil the owner
closes #4211
could break games, but probably very unlikely
> [18CZ] Fixed scrapping of trains

- assets/app/view/game/part/city_slot.rb
> extra_token: simpler shadow

- lib/engine/game/g_1822/step/buy_sell_par_shares.rb
> [1822] Strange behaviour in stock round

- lib/engine/game/g_1822/game.rb
- lib/engine/game/g_1822/step/track.rb
- If no tokens is available, you wont be able to use the token swap ability. I made so it also shows up during track lay step. This way you can make a token and you will then it will stop at the tokenstep
fixes #4297
> [1822] Show P18 on trackstep

- assets/app/view/create_game.rb
I'm sorry for the excessive amount of PRs. I'm not sure if it was worth withholding small stuff like this.
Before:
After:
> Group the game list on CreateGame by stage

- assets/app/view/game/auto.rb
- lib/engine/action/program_share_pass.rb
- lib/engine/game/base.rb
- lib/engine/game/g_1817/game.rb
- lib/engine/game/g_1817/step/buy_sell_par_shares.rb
- lib/engine/step/buy_sell_par_shares.rb
- lib/engine/step/program.rb
- spec/fixtures/1882/hs_fxmfdndg_26178.json
- spec/fixtures/1882/hs_iopxwxht_26178.json
- spec/fixtures/1882/hs_kufujwkw_26178.json
- spec/fixtures/1882/hs_vaxptumi_26178.json
- spec/lib/engine/games/game_spec.rb
> Add protection for shenanigans on auto-buys and add auto-pass

- lib/engine/game/base.rb
- lib/engine/game/g_1867/game.rb
> 1861/67: Fix share price movement down rather than left

- lib/engine/game/g_1822/step/buy_sell_par_shares.rb
> [1822] Track actions

- lib/engine/game/g_1822/game.rb
- Somewhere along my testing back and forth I must have entered the wrong number of 5 trains :(
fixes #4336
> [1822] Wrong number of 5 trains

- lib/engine/part/node.rb
- lib/engine/part/path.rb
> Walk refactor
