tobymao/18xx

lib/engine/step/buy_sell_par_shares_via_bid.rb
`Engine::Step::BuySellParSharesViaBid` implements the style of auction where an available entity is selected for auction, then players get asked to bid or pass until only one person is left. This is used by 1861 and similar games for auctioning corporations (minor companies).
The same style of auction is used in other of of Ian D Wilson's games to auction privates: 1858 only has auctions of privates, and 18BF has auctions of both privates and minors.
This change extends BuySellParSharesViaBid to be able to auction companies as well as corporations. Most of the changes are renaming variables so that they are more general. It also adds an `auctioning_company` method to be called from `View::Game::Round::Stock.render`.
This change has been extracted from pull request #8578.
=> Extend Engine::Step::BuySellParSharesViaBid to handle company auctions

lib/engine/game/g_1880/entities.rb
Text change to use more inclusive wording.
NOTE: The official rulebook uses "his".
=> [1880] Remove gendered phrasing on privates

spec/lib/engine/games/config_spec.rb
1822PNW was broken by issue #tobymao/18xx#8732. This was caused by a typo in the colour name part of a tile definition. This adds a rspec test to catch mistakes like this, which are easily made by those of us who think that 'grey' is the correct spelling. It checks that all colour names are part of the Engine::Config::Tile.COLORS list.
=> Add test to check for typos in tile colours

assets/app/view/game/choose.rb, assets/app/view/game/round/operating.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/buy_train.rb, lib/engine/game/g_1868_wy/step/choose.rb, lib/engine/game/g_1868_wy/step/choose_big_boy.rb
this private provides a `+1 +1` token which boosts a train's city and town values by one
* represent the token as `[+1 +1]`, and when assigned to a train, represent the new number in square brackets to distinguish it; e.g., a `2` train becomes `[3+1]`
* wrap choice buttons in a div so that in the train-buying step, all choices are rendered on the same line
* before, with first choice on one line and the rest on another line: ![](https://i.imgur.com/wJFayNh.png)
* after, all on one line: ![](https://i.imgur.com/WaSOLlE.png)
* the token can first be assigned when the private is bought (`Choose` step), or during the `BuyTrain` step; `ChooseBigBoy` is implemented as a module so to easily provide the functionality to both possible steps
* the token can be re-assigned to a different train …
=> [1868WY] P7 "Big Boy" private

lib/engine/game/base.rb, spec/lib/engine/games/g_18_zoo_spec.rb
In `validate.rb`'s `run_game()` function, the game engine is loaded outside of the `begin`/`rescue` block, before calling `maybe_raise!` inside the block, so that an error in the game state can be caught without crashing the whole program.
The changes in the recent PRs #8735, #8756, and #8787 all changed/removed certain game objects like trains and tiles. This caused the game engine to error out when in `process_action` when converting the action to a hash (for example, the 1852: Missouri change removed some trains from the roster, so actions using the removed trains tried calling `@train.id` where `@train` was `nil`) before `process_single_action` was called.
That made the `validate.rb` functions impossible to use to identify which games to archive; the `NoMethodError` on the `nil` train …
=> validation: Catch all errors in `process_action`

lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/graph.rb, lib/engine/game/g_1858/path_node.rb, lib/engine/game/g_1858/step/track.rb
This adds the overall structure of the operating round for 1858, and the code for laying track. 1858 has several differences from other games which have had to be implemented here.
Routes for laying track (and placing tokens and running trains) start at a token (or a home hex for a minor) and are traced on either broad/dual gauge track or narrow/dual gauge track. Routes cannot include both narrow and broad gauge track. This is implemented by having two graph objects created, with `skip_track: :narrow` and `skip_track: :broad`. Various methods in the track step check both of these graphs to see if a tile placement is valid on either of them.
Terrain costs are halved for yellow narrow gauge tiles. Also the Pt20 cost of a second tile is halved if either the first or the second tile is only …
=> [1858] Operating round structure and track laying

lib/engine/game/g_18_mo/entities.rb, lib/engine/game/g_18_mo/game.rb, lib/engine/game/g_18_mo/map.rb
Fixes #8786 
This will require archives/pins.
Given that it's been out for almost a year pending games should probably be pinned even if it's still in alpha.
=> 18MO: Playtest changes

lib/engine/game/g_1880/game.rb, lib/engine/game/g_1880/step/assign.rb, lib/engine/game/g_1880/step/buy_train.rb
fixes #8781
Edge case where rocket of china hasn't been used AND a full operating order passes on the 4 trains.
see here: 
https://boardgamegeek.com/thread/1042314/forced-exchange-p7-rocket-and-removal-unpurchased
"If no one buys a 4T, as you pick them up to get rid of them, when you pick the first one up, the second one zips off to the P7 owner and then all the rest go away. I'll admit this isn't clear." and "The discarding of the 4-trains is one after the other, so the Rocket of China will be exchanged into the second 4-train in case of all 4-trains are discarded.
Lonny"
fixes #8803 as well. @game.phase.buying_train! has 3 params but the code was only passing 2.
=> [1880] fix edge case 4t rocket

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/assign.rb, lib/engine/game/g_1868_wy/step/buy_train.rb
* provides a permanent 2+1 train to the owning railroad
* train does not count against limit or for train-owning requirement
* if still player owned when closing, it may be assigned to a corporation
[#5011]
=> [1868WY] P9 LHP private

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/buy_train.rb, lib/engine/game/g_1868_wy/step/issue_shares.rb
* railroads can issue xor redeem shares any time during the OR turn
* can issue up to the phase number (ie issue only 2 shares in phase 2)
* can only redeem if owns a train
* during EMR, must first issue shares, ignoring phase limit; president may go for more expensive train variant
=> [1868WY] Issuing/Redeeming Shares and EMR

lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/step/token.rb
In 1858 the cost of tokens are determined by the number of provincial borders crossed from another token, measured as the crow flies. The bulk of this pull request is a hardcoded list of distances between cities. It might be possible to calculate these distances by looking at the map and hex borders, but this approach seemed far easier.
There are also base class methods overridden to ensure that there is a legal route to the new token, using either narrow gauge or broad gauge track.
=> [1858] Token step in the operating round

lib/engine/game/g_18_mo/entities.rb, lib/engine/game/g_18_mo/game.rb, lib/engine/game/g_18_mo/map.rb
Fixes #8820 
Playtest updates (from Scott):
- Aurora (J2) should have the same definition as Joliet (K3).
- Change the private company Mountain Construction Company to $40 rebate instead of $20.
- Change description to
- Owner receives $40 whenever a yellow tile is laid on a mountain hex by any entity. Never closes.
- Remove hard rust of yellow trains
- This is not really important, it just never is a factor in this game
- Change the Tunnel Blasting Company to "Missouri River Bridge Company". 
- Change tile_discount from mountain to water
- New text is "Reduces, for the owning corporation, the cost of laying or upgrading a tile that incurs river terrain cost by $20 (hexside or printed hex cost).
- All destination costs are 80. Change teleport_price and descriptions for ATSF, MKT, MP.
- …
=> 1852:MO E-train bug fix + more playtest updates

lib/engine/game/g_1848/game.rb, lib/engine/game/g_1848/step/tasmania_tile.rb
fix #8827 - only add tile lay ability if doesn't exist 
fix #8604 - when reseting company value, also reset discount
=> fix 1848 bugs

lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/step/buy_sell_par_shares.rb
This is the start of the stock round implementation for 1858. Buying and selling shares is fairly normal, the main difference being that you can't directly par a corporation before phase 5. Before that point corporations can only be started by exchanging a private railway company, this is to be added in a later commit.
In a stock round you can also put up a private company for auction. Everyone gets a chance to bid on this company, until only one person is left. This is implemented using the Engine::Step::BuySellParSharesViaBid code from 1861/1867.
=> [1858] Stock round: auctions, buying and selling shares

lib/engine/game/g_18_va/game.rb
Fixes #8845
This will have the 5-share corps display "40% to float", switching to "20% to float" after the first 5 train is purchased.
Edited to add: 
Fixes #8418
MUST_BUY_TRAIN set to :always, as per rule 4.6 of the 18VA rulebook
=> [18VA] show 40% to float, Must buy set to always

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/meta.rb, lib/engine/game/g_1868_wy/step/waterfall_auction.rb
There are three P2 companies: P2a, P2b, and P2c. The same is true for P3-P6. The default way to play is randomly choose one of each to be in the auction; the rules also include a variant where the auction winner has a choice of which private to take.
[#5011]
=> [1868WY] variant: winner of P2-P6 chooses which company to take

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/stock_round_action.rb, lib/engine/game/g_1868_wy/step/waterfall_auction.rb
Previous rule was certain companies could not be started before phase 5; now there is no phase restriction, but there are two stacks/decks of president certificates determining the order in which corporations may be started.
* during setup, all presidencies but UP and DPR are shuffled and split into two piles, with DPR at the bottom of one of them (randomly chosen)
* only top corporation of each pile may be started until phase 5, when all become available
* also, fix small bugs for companies with free green tile; do on float, not start, and don't lay green if gray tile is already there
* list the stacks during auction and stock rounds
[#5011]
=> [1868WY] before phase 5, 2 shuffled stacks of presidencies

lib/engine/game/base.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/meta.rb, lib/engine/game/g_1868_wy/round/bust.rb, lib/engine/game/g_1868_wy/round/development.rb, lib/engine/game/g_1868_wy/step/assign.rb
* separate DEV rounds from ORs; DEV rounds derive from ORs, so add a new method in the base `Game`, `final_or_in_set?()`, so that DEV rounds don't incorrectly trigger the end in 1868 Wyoming * in DEV rounds the "minors" (coal and oil companies) operate by placing their development tokens * normally all coal companies go and then oil; there is an async-friendly variant where each player does their coal and oil at once, so you just go through the priority turn order one time instead of twice
* log "privates pay" rounds
* BUST rounds are mostly automatic, but the NO BUST private can lay its token to protect a city that is just about to BUST in the current round
* endgame is triggered by 7-train purchase, and at that point the round structure changes up
* rule changes for player value at the …
=> [1868WY] Endgame, new round structure, and P6c NO BUST private

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/buy_train.rb, lib/engine/game/g_1868_wy/step/discard_train.rb
- fixes info page issue where after the first train of a type is bought, its row only shows that variant
- hopefully fixes hard-to-reproduce hotseat issue where sometimes buying the plus variant would not actually rust all the other trains
[#5011]
=> [1868WY] remove train variants at discard (like in 1822) instead of on buy

api.rb, assets/app/view/game/game_meta.rb, assets/app/view/game_page.rb, lib/engine.rb, lib/engine/game/g_1822_mrs/meta.rb, lib/engine/game/g_1822_nrs/meta.rb, lib/engine/game/g_1846_two_player_variant/meta.rb, lib/engine/game/g_1849_boot/meta.rb, lib/engine/game/g_1868_wy/meta.rb, lib/engine/game/g_1871/meta.rb, lib/engine/game/g_1873/meta.rb, lib/engine/game/g_1877/meta.rb, lib/engine/game/g_18_chesapeake_off_the_rails/meta.rb, lib/engine/game/g_18_christmas_eve/meta.rb, lib/engine/game/g_18_los_angeles/meta.rb, lib/engine/game/g_18_los_angeles1/meta.rb, lib/engine/game/g_18_mt/meta.rb, lib/engine/game/g_18_ny_1e/meta.rb, lib/engine/game/g_18_tokaido/meta.rb, lib/engine/game/g_18_zoo/meta.rb, lib/engine/game/g_rolling_stock/meta.rb, lib/engine/game/g_rolling_stock_stars/meta.rb, lib/engine/game/meta.rb
* add "Known Issues" link to info page for each game, which will open GitHub
with the appropriate label selected
* games with a different label tag than their `title` must set
`GAME_ISSUE_LABEL` in their `Meta`, e.g., "The Old Prince 1871" simply uses
"1871" for its issues
* update the 'raise a bug report' link on broken games to go to the issues page
and search for two labels: the active game, and "needs triage", maximizing the
chances of the user seeing if their bug has already been reported
* add new routes, `/issues/<dev_stage>`, to redirect to the GitHub issues page
with labels for all games matching the entered dev stage, so it's easy to find
a production isssue to work on
=> Links for known issues

lib/engine/game/g_18_cz/game.rb
If the currently active corporation has no cash, they can still gain cash from a company by simply selling it, so move the check for positive cash into the loop on the condition looking at player-owned companies.
[Fixes #8409]
=> [18CZ] fix `potential_company_cash`

lib/engine/game/base.rb, lib/engine/game/g_1880/game.rb, lib/engine/tile.rb
The current fix in #8871 assumes all tiles with more than one city is an OO. This is not a valid way to identify an OO city. There are many games with more than one extra city on a tile that is not an OO tile and thus the name of the feature is incorrect.
This fix attempts to provide a clearer blocking mechanism that can be reused without providing unexpected behavior.
Also removed yellow_only as it was added for 1880 and not used by any other game.
=> [1880] Fix OO hex tile reservations

lib/engine/game/g_1817_de/game.rb
Fixes #8903
Removes "no new shorts" status from phase 8, since 18DE doesn't have shorts.
=> removes "No shorts" comment from phase 8 info

assets/app/view/game/hex.rb, assets/app/view/game/part/city_slot.rb, lib/engine/action/remove_hex_token.rb, lib/engine/game/g_1868_wy/entities.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/oil_companies.rb, lib/engine/game/g_1868_wy/step/assign.rb, lib/engine/game/g_1868_wy/step/manual_close_company.rb, lib/engine/hex.rb, lib/engine/step/tokener.rb
* oil companies are minors like coal companies, placing development tokens; oil companies can also remove their hex tokens as an action
* P8 adds a Boomtown to a chosen hex 
* if the hex booms, the Boomtown becomes a Boom City that is reserved for the owner of P8
* update rendering so the boomed dashed line renders outside of the city circle
[#5011]
=> [1868WY] oil companies and P8 pure oil camp

lib/engine/game/g_18_ireland/game.rb, lib/engine/game/g_18_ireland/meta.rb
Implements the official larger bank variant from the AAG rulebook (5k bank instead of 4k)
=> [18Ireland] Implements the official larger bank variant

lib/engine/game/g_18_co/meta.rb
Fixes #8918 
Updates the rules link to point to a direct PDF which is accessible anonymously
We assume that this is the latest version of the rules, this PDF seems to be the only file in the gdrive folder that covers the rules
https://drive.google.com/drive/folders/0B3lRHMrbLMG_eEp4elBZZ0toYnM?resourcekey=0-GDuc0xyk8bJoY8xanSNSCg
=> [18CO] fix rules link

lib/engine/game/g_1856/game.rb, lib/engine/game/g_1856/meta.rb
Adds 8-train variant from the official rules for 1856
=> Adds 8-train variant from the official rules for 1856

lib/engine/game/g_21_moon/game.rb
Fixes #8956 
Fixes the old "deallocating elements of a list while iterating through the list" bug.
No pinning nor archiving required.
=> 21Moon: fix disposal of shares owned by a closing corp

lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/market.rb, lib/engine/game/g_1858/step/buy_sell_par_shares.rb, lib/engine/game/g_1858/step/dividend.rb, lib/engine/game/g_1858/step/exchange.rb, lib/engine/game/g_1858/step/home_token.rb, lib/engine/game/g_1858/step/private_exchange.rb, lib/engine/part/city.rb
This is the next batch of code for 1858. This is the penultimate chuck of game logic, after this there is just the private closure round to be implemented.
This is the implementation of the stock round exchange and tokening steps.
Private railway companies in 1858 can be exchanged for shares in two different ways:
1. A private with a city in one of its home hexes can be used to start a    new corporation. The par price is taken from the private's face value, with the player paying for half of the president's certificate. The corporation starts with a token in the privates home city (if there are two cities in the private's home hexes then the player gets to choose which one to start in). The corporation becomes the owner of the private company.
2. A private can be exchanged for a treasury …
=> [1858] Stock round: exchange and tokening steps

assets/app/view/game/stock_market.rb, lib/engine/game/g_1817/game.rb, lib/engine/game/g_1817/step/conversion.rb, lib/engine/game/g_1822/stock_market.rb, lib/engine/game/g_1848/game.rb, lib/engine/game/g_1848/stock_market.rb, lib/engine/game/g_1849/stock_market.rb, lib/engine/game/g_1856/stock_market.rb, lib/engine/game/g_1860/game.rb, lib/engine/game/g_1860/step/dividend.rb, lib/engine/game/g_1862/game.rb, lib/engine/game/g_1862/step/dividend.rb, lib/engine/game/g_1866/step/single_item_auction.rb, lib/engine/game/g_1866/stock_market.rb, lib/engine/game/g_1867/stock_market.rb, lib/engine/game/g_1868_wy/step/double_share_protection.rb, lib/engine/game/g_1868_wy/stock_market.rb, lib/engine/game/g_1870/stock_market.rb, lib/engine/game/g_1871/game.rb, lib/engine/game/g_18_co/stock_market.rb, lib/engine/game/g_18_cz/game.rb, lib/engine/game/g_18_cz/step/dividend.rb, lib/engine/game/g_18_ireland/step/merge.rb, lib/engine/game/g_18_new_england/game.rb, lib/engine/game/g_rolling_stock/game.rb, lib/engine/game/g_rolling_stock_stars/game.rb, lib/engine/stock_market.rb, lib/engine/stock_movement.rb, spec/lib/engine/round/stock_spec.rb
- Introduce stock movement class for each type of stock market
- Remove zigzag market workarounds from being based on a 1d market, in 1860, 1862, and 18CZ
- Some methods took coordinates ([r, c]) and others r, c. Standardize on coordinates
=> Refactor stock movement into separate classes per market type

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/game.rb
Fixes #8965 
Override a base 1822 function that handles the way that P16 `Tax Haven` in the base game does not count against certificate limit
This s.b. generalized in 1822 base code so future games don't have to know about this hack-around
=> [1822PNW,MX,CA] fix P16 not counting as a cert

lib/engine/game/g_1880/game.rb, lib/engine/game/g_1880/step/home_token.rb, lib/engine/step/home_token.rb
Fixes #8952.
The changes introduced by commit 4c65c1f to `lib/engine/step/home_token.rb` had changed game behaviour in 1867. The home token for a minor needs to be placed before the minor has a president (at the start of its auction), previously the player was the active entity during the home token step, this had changed it to be the presidentless minor.
This removes this change and instead puts it in a G1880 subclass.
I don't believe that this change will break any existing 1867 games. The recent behaviour is that anyone can place the token for the minor that is being auctioned, but the action produced is the same regardless of who chooses where the token goes.
@bentziaxl Can you check that this is OK for 1880? I can't …
=> Partially revert 4c65c1f, move changes to 1880 code

Rakefile, assets/app/view/about.rb
Adds date that `precompile` was run to /about
=> add build date to /about

lib/engine/game/g_1860/game.rb, lib/engine/game/g_1862/game.rb, lib/engine/stock_market.rb, lib/engine/stock_movement.rb
Fixes #8979 
Have to touch stock_market and stock_movement
- [*] Branch is derived from the latest `master`
- [*] Add the `pins` label if this change will break existing games
- [*] Code passes linter with `docker compose exec rack rubocop -a`
- [*] Tests pass cleanly with `docker compose exec rack rake`
1860 and 1862 have different rules than 18CZ and EUS when reaching either end of the "ZigZag" row.
=> Fix ZigZig end movement for 60 and 62

lib/engine/game/double_sided_tiles.rb
Fixes some problems from #8951:
* the new tile returned from `add_extra_tile` was not being captured, so
`new_tile` was actually not defined on the subsequent `if` check
* the method was named `update_tile_lists!` but the base method it overrides
does not have an exclamation point; originally the 18Carolinas code and 18Mag
code did call it with the exclamation point but that call was removed in #8951
I think 18Carolinas and 18Mag didn't break since their double-sided tiles are
all limited in count.
=> Fix `update_tile_lists` for double-sided tiles

assets/app/view/game/par_chart.rb, lib/engine/game/g_1880/game.rb
fixes #9038: 
removes the extra float_40 event on 4+4.
sets min of shares purchasable and 10
fixes #9034
=> [1880] fix 6e route issue

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/golden_spike.rb, lib/engine/game/g_1868_wy/map.rb, lib/engine/game/g_1868_wy/step/track.rb, lib/engine/game/g_1868_wy/step/waterfall_auction.rb
* map/tile tweaks:
* embiggen spike icons
* new track on A23
* get rid of `dotify`, just use `style:dot` now
* used for boomtowns to always use dots and appear in center of tile, as
opposed to regular towns with the classic rectangle
* fix `legal_tile_rotation?` for green $20 tiles and L/G tiles; the "L" and
"G" tiles have only one legal rotation in yellow and green, but the logic
that was using `TILE_UPGRADES` was leaking into the green tiles that cost
$20 to lay, allowing upgrades that actually rerouted track;
`TILE_UPGRADES` also is no longer needed for boom tiles, so it can be
removed entirely
* routes:
* remove boom city calculation from `revenue_for`, that is now done directly
on the city's revenue
* string for uranium bonus; actual value is done directly on the city's
revenue
* …
=> [1868WY] various small fixes

lib/engine/game/base.rb, lib/engine/game/g_1817/game.rb
Fixes #8988
- Sets the `rusted` flag on trains before `remove_train()` is called, as within that function it was not possible to check the `rusted` state otherwise. This behavior was causing a bug as described here https://github.com/tobymao/18xx/issues/8988#issuecomment-1467477512
-  Also Removes an un-necessary "2+ trains provide zero revenue" definition from the lookup hash, since the calling function returns zero anyway if the train type is not in the hash
We assume that `remove_train` will operate correctly if the train is already marked as rusted
=> [1817] Volatility-variant private "Inventor" pays too much on 6 train purchase

lib/engine/game/base.rb, lib/engine/game/double_sided_tiles.rb
This bug was introduced by #8951, and fixed by #8996, but in between those two, games could be broken and not found when validating #8996 since the tile mismatch could not have any real impact on the game for many actions--in the case of game 115149, the game first misused tiles at action 630 but was not visibly broken until action 1766.
Closes #9026
----
10 of 11 active 18Mag games are impacted; pinning would prevent them from hitting this new exception but cannot prevent encountering the broken behavior seen in #9026.  
Here are the affected games:
`[111821, 113092, 113389, 114853, 115023, 115024, 115139, 115149, 115319, 116143]`
I've pinned them all. Many have triggered the end and may be able to finish, but could still encounter the issues caused by #8951.
=> Raise an error if the tile being laid is already on the board

Rakefile, assets/app/view/about.rb
Fixes #8987
Refactors the `rake precompile` code to generate an epoch rather than a DateTime object
Stores that epoch in `version.json` that is generated from above
Refactors `about.rb` to pull that new epoch and format it in JS on the client-side
[Time.at()](https://ruby-doc.org/core-2.6.3/Time.html#method-c-at) returns the local time at that epoch with timezone offset
`If a numeric argument is given, the result is in local time.`
=> [feat] Localize deploy date in /about

lib/engine/ability/token.rb, lib/engine/step/special_token.rb
* Add an option to the `token` ability that closes the associated company when the ability is used
* Necessary for 1847 AE
* Based on how it is implemented for the `tile_lay` ability
=> Add option to close company when Token ability used

lib/engine/game/g_1849/stock_market.rb
fix #9078
The fix of stock price movement a month ago introduced an issue where find_relative_share_price calls
right (nil, coordinates). 1849 uses the corp name to log movement, causing a nil exception
=> fix 1849 dividend view

lib/engine/game/g_1849/stock_market.rb
Fixes #8253
First time using CodeSpaces, not sure why it made an empty commit!
=> [1849] Fix 8253 - Allow up movement when blocked from blue zone

lib/engine/game/g_18_al/meta.rb
Linked to version 1.7 of the rules (more current). The file is also much easier to read - the 1.64 version was paginated for booklet printing.
=> [18AL] Update rules URL in meta.rb

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/dividend.rb, lib/engine/game/g_1868_wy/step/waterfall_auction.rb, lib/engine/step/dividend.rb
#5011
P2-P6 each have three different possible companies this finishes the implementation for two of the P6 privates:
- P6a James E Shepperson's Coal Strikebreakers - owning player gets one more coal DT for each color/phase, and gets an extra coal DT placement in the first dev round of each phase
- P6b Teapot Dome Oil Leases - owning player's oil DTs each add $5 total revenue ($0.5 per share) to Boom Cities on its hex or an adjacent hex for that player's corporations
=> [1868WY] Implement P6 privates - strikebreakers, teapot dome oil

lib/engine/game/g_1858/step/track.rb
The call to `can_lay_tile?` in the actions method meant that the graph had to be evaluated whilst a game's history is loaded, increasing the amount of work to be done.
This call has been removed from actions and instead `auto_actions` is used to generate a pass if it is not possible for a minor to lay any track.
=> [1858] Remove graph call from Step::Track.actions

lib/engine/game/base.rb, lib/engine/game/g_18_cz/game.rb
* change `Game::Base#valid_actors` to account for `acting_for_player` returning `nil`
* in 18CZ, implement `acting_for_players` and stop overriding `active_players` and `valid_actors`
* show which players will take track and token actions on corp cards in ORs
Fixes #4806
=> [18CZ] fix Vaclav logging, always show on corp cards

lib/engine/step/buy_sell_par_shares.rb
Fixes #7142
While #7142 only references 18CZ, this can affect all games.
I repro'd the behavior locally and created a game where illegal passes were happening automatically. With this change applied, the validation script did not break on the game with the illegal actions, since they are "snuck" in with auto_actions, so no pins/etc will be needed.
=> Don't let players over the cert limit autopass

lib/engine/game/g_1868_wy/entities.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/assign.rb, lib/engine/game/g_1868_wy/step/stock_round_action.rb
#5011
Some parts of DPR's home are already done, such as its operations being skipped automatically if it has no home token.
Implemented here:
* if DPR started during full cap part of game (phase 5+), their home token is reserved instead of immediately placed
* if all their tokens are in Boom Cities which end up BUSTing, they can place a new home token in the stock round
* add note about home token to status array for corp card
Recent rule change: the token can only be used on blank (white) or yellow hexes/tiles
Recent change: the rulebook and components will now refer to the special share as a "20% share" instead of "double share".
-----
The implementation is now alpha-ready, but the designer and publisher want to hold off on making it available. Last target I heard was matching it up …
=> [1868WY] Finish implementing DPR home, fix Pure Oil, update Ames Bros wording

lib/engine/game/g_18_mag/game.rb, lib/engine/game/g_18_mag/step/special_choose.rb
fixes #9045
one of the supporters converts a train into +1, for example 2+1.
this can combine with the major ability that converts into plus train. (gc major)
Need special logic to handle
2+1 (supporter only)
2+2 (plus train conversion only)
2+3 (supporter and plus train)
added
1- train conversion and train distance use a city_distance_value  in case it's a gc train
2- compute stops needs to use the updated distance, previously used distance without GC. instead of copying the entire content of compute stops i pass a dummy duplicate train with the correct distance (open to other suggestions such as adding a param or copying the entire method)
3- modified route_distance to also work if just supporter is used without gc
=> [18mag] fix +1 train supporter

lib/engine/game/g_18_rhl/game.rb
Fixes #8774 
Raise an error when a route consists of only a Rhine metropolis city.
This may break existing games, so `pins` is needed.
=> [18Rhl] Fix illegal route

assets/app/view/game/map.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1850/game.rb, lib/engine/game/g_1861/game.rb, lib/engine/game/g_1867/game.rb, lib/engine/game/g_1870/game.rb, lib/engine/game/g_1894/game.rb, lib/engine/game/g_18_fl/game.rb, lib/engine/game/g_18_jpt/game.rb, lib/engine/game/g_18_los_angeles/game.rb
* fixes an issue where the map view with "Starting Map" selected can change throughout the game, e.g., [/game/116364?action=0#map](https://18xx.games/game/116364?action=0#map) vs [/game/116364?action=481#map](https://18xx.games/game/116364?action=481#map)
* fixes an issue where toggling "Starting Map" can change the map view at the start of the game, e.g., [/game/116364?action=0#map](https://18xx.games/game/116364?action=0#map)
* moves implementation of `init_hexes` into `setup` for a number of games (all validated, this change doesn't break anything)
* 1822
* 1850
* 1861
* 1867
* 1870
* 1894
* 18FL
* 18JPT
* 18 Los Angeles
Fixes #9001
Other closed issues/PRs which are relevant:
* #3204
* #5274
* #6704
* #8294
* reverts PR #8118 for #3080
* reverts PR #4252 for #4233
* reverts PR #4877 …
=> "Starting Map" view: clone full game instead of calling `init_hexes`

lib/engine/game/g_1822_mx/step/track.rb
Fixes #8096
This lets the track step be properly skipped, which stops logging "NDEM skips lay/upgrade track" after it runs trains and during the auction for its station tokens, as described in #8096.
Validated against all 1822MX games, this change caused no breakages.
=> [1822MX] fix `active?` for NdeM in track step to stop excessive logging

lib/engine/game/g_1882/game.rb, lib/engine/game/g_1882/step/buy_train.rb
Fixes #7775
In the base code, `president_may_contribute?` points to the Game class's `must_buy_train?`; the 1882 override takes just what it needs from that and adds the exception to allow, but not require, EMR with a route to the fishing exit: https://github.com/tobymao/18xx/blob/a77c96dd939b0d8ce999933b40664e9f03171e0d/lib/engine/game/base.rb#L1214-L1219
Validated all 1882 games and got no breakages, as expected, since this only adds a possible action to a step where `pass` was already possible.
=> [1882] make EMR optional if only route is to fishing exit

lib/engine/game/base.rb, lib/engine/game/double_sided_tiles.rb
It's #9029 again, but the error is only raised if the tile's hex is the hex from the game. Tiles need to be assigned an `A1` hex belonging to the TileSelector (this is why #9029 broke everyone's games), so it's not enough to check whether a tile has a hex, we need to check if that hex is the game's hex.
=> Raise an error if the tile being laid (or its opposite) is already on the board

assets/app/view/game/dividend.rb
No step actually implements `movement_str`, so I removed the check for it when defining `direction`.
Fixes #8536, which is actually applicable to more games than just 1817.
=> Fix displayed stock price movement at end of market

lib/engine/game/g_1867/game.rb, lib/engine/game/g_1867/step/buy_sell_par_shares.rb
Fixes https://github.com/tobymao/18xx/issues/8980
Prior to this fix, 1867 games could select a Major to start with no valid home,
and then be unable to place its home token. They were forced to undo the actions
instead of the game preventing the illegal move, e.g.,
http://18xx.games/game/115992?action=486
This PR changes the UI so that an option to start a Major is not presented, but
it does not change any action validation, so no previous games will break.
1861 already has its own override of `ipo_type`, so those games won't be affected.
From the designer in the comments on https://github.com/tobymao/18xx/issues/8980:
> In 1867, minors may start in unconnected revenue centres in the same hex, but
> majors may not (if one such centre is occupied). Therefore, it should be
> impossible to …
=>   [1867] don't allow a Major with no valid home to start; fix Toronto/Montreal starts

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/game.rb
Fixes #8828
Pins needed for 1822MX and 1822PNW games where shares were not sold in blocks:
```
[83532, 85341, 90838, 94484, 96028, 96507, 100292, 101527, 103539, 103853,
104314, 105097, 106495, 106814, 107499, 108159, 108528, 109165, 112879, 113007,
113207, 117068, 118921]
```
=> [1822 family] Fix MUST_SELL_IN_BLOCKS for 1D market games

lib/engine/game/g_1822_mx/step/auction_ndem_tokens.rb
Fixes #8574
Not all games violating the rule are caught by the validation script because of how auto actions work, e.g., in game 106013, the player who shouldn't have been allowed to bid passed on their turn, so no breaking action occurred. 
Pins:
```
[88732, 92280, 92703, 92821, 93434, 94482, 94484, 98864, 99158, 100237, 100302,
101009, 101954, 102436, 105374, 105993, 106814, 107617, 111006, 111383, 114266,
115540]
```
=> [1822MX] don't allow bidding on NdeM token for a Major with token on same hex

assets/app/view/game/discard_trains.rb, lib/engine/game/g_18_ny/game.rb, lib/engine/game/g_18_ny/step/discard_train.rb
Fixes #9128
Generalizes the 'verb' that is used during a forced "discard train" step
Adds the `salvage` property to 18NY trains, as this is used to determine whether the verb will be "Salvage" or not
Before:
After:
=> [18NY] Change Text for Forced Salvage of Trains Over Limit on Phase Change

assets/app/view/game/alternate_corporations.rb, lib/engine/game/g_1858/game.rb
The default view for a minor shows:
1. Its name.
2. The trains it owns.
3. The cash in its treasury.
4. Its position in the operating order.
5. The value of its last run.
Most of these are irrelevant for 1858, as the minor parts of the private railway companies can't own trains, don't have a treasury, and don't run routes.
This alternate view makes minors look like companies. This shows more relevant information:
- Revenue.
- Home hexes.
- Whether it can be used to start a corporation (public company).
- Face value.
Making the minors look like companies also helps hide the internal split of private railways into a company and a minor, this does not need to be visible to the player.
This introduces new code into the shared `assets/app/view/game` directory, but it will be ignored by all …
=> [1858] Alternate view for minors

lib/engine/game/g_1846/entities.rb
Two private company descriptions had errors in the way they used single and double quotations.
Corrected indentation on those entries too. 
Before: 
None.
=> [1846] fixes single/double quote in two company descriptions

lib/engine/ability/reservation.rb, spec/lib/engine/round/operating_spec.rb
In `Ability::Reservation.teardown` the reservation was being removed by calling `City.reservations.delete`. This could trigger a bug if there were other reservations and also tokens in a city with multiple slots.
The bug appears if:
- The city has two slots, which are reserved by companies P1 and P2.
- A corporation has used P1's ability to place a token in slot 0.
- The city's reservations will be `[P1, P2]`, so P2 has a reservation on the open slot.
- If P1 closes, `Ability::Reservation.teardown` will call `City.reservations.delete(P1)`, changing the reservations array to be [P2], so P2's reservation is now for slot 0, which already has a token, and slot 1 is no longer reserved.
- By calling `City.remove_reservation!(P1)` instead, the reservations array will become `[nil, P2]`, so P2's …
=> Call City.remove_reservation from Ability::Reservation.teardown

lib/engine/game/g_1848/step/buy_train.rb
Fixes #9145
It's possible this could pin games, seems unlikely to be too widespread
After buying across a train from another corp, cannot buy from the depot. Implements the rule where buying across from a corp must be the last action of the corp's turn
Before buying across a train:
After buying across a train (cannot buy from depot anymore):
=> [1848] Shouldn't be able to buy a train from supply after buying from corporation

lib/engine/game/g_1858/step/buy_sell_par_shares.rb, lib/engine/game/g_1858/step/private_exchange.rb
The call to `can_exchange_any?` in `Step::BuySellParShares.actions` was leading to a call to `@game.corporation_private_connected?` which uses the game graph. This will be slowing down loading the game history, so this commit adds a simplified check which is just checking that shares are available for the exchange.
When the game is being run interactively, `auto_actions` will check the game graph to see if any exchanges are actually possible, and pass if not.
=> [1858] Don't check graph in Step::BuySellParShares.actions

lib/engine/game/g_1858/map.rb, lib/engine/game/g_1858/step/track.rb
Remove the custom code for keeping icons on upgraded tiles, and instead define the icons as being sticky, as there is already code to preserve the icons.
=> [1858] Use sticky icons for private railway home hexes

lib/engine/game/g_18_mex/game.rb, lib/engine/step/buy_train.rb
4.3.4.2, pages 10-11 in rulebook
Fixes #9162
Also update error message for the case where the buying company has no money; in
some 18MEX games, presidents contributed $1 for an EMR cross-buy resulting in
messages like "TM may not spend $1 on MC's 6' train; may only spend between $1
and $0."
=> [18MEX] set EBUY_OTHER_VALUE to false

lib/engine/player_info.rb
[#5011]
- N/A Add the `pins` label if this change will break existing games
Adds "DEV" as another round short name where there can be multiple rounds. Fixes a bug where one of the DEV rounds' delta values would be the opposite of the preceding OR's value.
Before:
After:
=> [1868WY] Fix DEV rounds being displayed incorrectly on spreadsheet

assets/app/view/game/tile.rb, lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_mx/map.rb, lib/engine/hex.rb
* [1822 family] make destinations more clear/accessible, fixes #9135 and fixes #5248
* make destination ability more concise
* add home token ability 
* add new ability for corporations like LNWR that get their destination for free, instead of including it in the too-long destination ability description
* in 1822MX, on the N23 hex, "Mexico City" is currently not rendered on the map, presumably to avoid excess clutter; add mechanism to have the location name saved but not rendered, so that it will remain off the rendered map, but will be visible for corporations with a home there
Before:
After:
=> Improve 1822 family destination information, allow hiding location name

lib/engine/game/base.rb
if update_cache is called on shares it doesn't wipe out shares currently in players hands
=> update game.shares to utilize both corporation and player shares 

TILES.md, assets/app/view/game/part/base.rb, assets/app/view/game/part/icons.rb, assets/app/view/game/part/small_item.rb, assets/app/view/game/part/upgrade.rb, assets/app/view/game/part/upgrades.rb, assets/app/view/game/tile.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/map.rb, lib/engine/hex.rb, lib/engine/part/base.rb, lib/engine/part/icon.rb, lib/engine/part/upgrade.rb, lib/engine/tile.rb
* use new method `preferred_render_locations_by_loc` to render icons and upgrades near the specified corner * only works in `:pointy` layout for now, since 1868WY is only game using it
* put rendered revenue on top of other elements
* [1868WY] specify locs for coal, oil, and uranium development tokens (DTs) to manage crowded hexes; specify some locs for upgrades on starting uranium hexes
* fix transform/translate for upgrades and pointy layouts 
* this necessitated defining some more part positioning constants in `View::Game::Part::SmallItem` and `View::Game::Part::Upgrade` to avoid changing rendering of terrain upgrade costs in existing pointy-layout games too much
#5011 
----
1868 Wyoming, Jeffrey City (J12) with one coal token, one oil token, two uranium tokens, and two corporation …
=> [core] allow icons and upgrades to have a `loc` set to specify rendering location, use for DTs in 1868WY

lib/engine/game/g_1822/entities.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/special_track.rb
Also:
* move ability definitions to config file; when the choice between the one-time or persistent abilities is made, remove the other abilities instead of adding them at the choice time
* list out all valid hill/mountain hexes (list of hexes also valid for 1822MRS and 1822NRS)
* update code comment to say "P8" for easier reference
Fixes #9180
=> [1822] stop P8 ability from working with swamps

lib/engine/game/g_18_ny/map.rb, lib/engine/game/g_18_ny_1e/map.rb
Fixes #9189 
added `border=edge:5,type:impassable` to hex I21 in both editions of 18NY map files
=> fixes impassable edge 5 border on hex I21

assets/app/view/game/stock_market.rb, lib/engine/game/base.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/stock_market.rb, lib/engine/share_price.rb
This finishes implementing the 1841 stock market. It required adding a 2nd 'max_price' stock attribute. One is if minors (as in 1861/1867), the other is for pre-phase 8.
Borrowed the approach 1861/1867 took with redefining the stock market "right" method. 1841 needs to pass in the game to it's stock market in order to check the current phase.
**Common code:**
Engine::SharePrice: added :max_price_1
UI::StockMarket: added max_price_1, added flexible border colors for :max_price and :max_price_1
Engine::Game::Base: added default color for :max_price
=> 1841: Stock Market

migrate_game.rb
* better stdout logging
* add param to trigger interactive debugging
* `repair` block updates 
* better support for `auto_actions`, e.g., in certain cases, deleting a `pass` action and moving its `auto_actions` to the previous one 
* add check to change the entity on the `pass` action before trying to delete it, useful for private companies which lay two tiles and cause a blocking step for the second one
* add `require_pin` param, and stop require passing a `pin` when `require_pin` is not `true`
=> migrate_game.rb changes

assets/app/view/create_game.rb, assets/app/view/form.rb, lib/engine/game/g_1825/meta.rb, lib/engine/game/g_1888/meta.rb, lib/engine/game/g_18_gb/meta.rb, lib/engine/game/meta.rb
Old behavior with bad set of optional rules selected:
* multiplayer: can create a game table, no error until starting the game
* hotseat: taken to error page
* JSON: taken to error page
New behavior with bad set:
* multiplayer and hotseat: 'Create' button is disabled
* JSON: error message flashes and user stays on the page
=> Disable create game button when incompatible optional rules are selected

lib/engine/game/g_rolling_stock/step/ipo_company.rb
Fixes #9212 
Fix to allow purchase of 4 shares during an IPO. The failing case represents the worst difference between max company value and min par price.
I thought about using a ceiling function and making the code cleaner, but I remembered there have been rounding issues with Opal/JS.
No pins needed.
=> Rolling Stock: one more ipo fix

assets/app/view/game/part/track.rb, assets/app/view/game/tile.rb, lib/engine/game/g_1840/map.rb, lib/engine/game/g_1873/game.rb, lib/engine/game/g_18_sj/map.rb, lib/engine/tile.rb
Several games have pre-determined routes on the map where track will be built later in the game:
- Harzbahn 1873 has concession routes for the railway companies.
- 1840 has the route for the Stadtbahn companies.
- 18SJ has three mainline routes.
On the physical game boards for these games these are indicated by lines on the map. 18xx.games currently indicates these routes by having icons in the hexes that form the route, but this is less clear as it does not show the edges that the route enters and exits each hex.
This pull adds a :future track type for path tile parts. This gives a dotted line on the game map, allowing the route to be drawn.
Any path tile parts with a track type of :future are not added to the tile's `paths` array, instead they are stored in a separated `future_paths` …
=> Add a :future track type for paths

lib/engine/game/base.rb, lib/engine/game/g_1822_pnw/game.rb, lib/engine/game/g_1822_pnw/meta.rb
The current variants for reducing the number of L/2 trains are not functional. This PR replaces the four non-functional variants with two new ones that match the variants in the latest version of the rulebook.
* four variants were implemented in #8380, merged on 2022-09-26
* the variants were announced [on BGG][0] on 2022-10-03
* the implementation for the variants was deleted in #8443, merged on 2022-10-15, but the `OPTIONAL_RULES` remained in `G1822PNW::Meta`; since this was deployed, 1822PNW games could be created with a variant for fewer L/2 trains selected, but the setup was not actually changed
* the latest (dated 2023-02-22) [draft rules][1] show variants for removing two or three L/2 trains (Chapter 11, page 28)
* since this implementation uses different names for the optional …
=> [1822PNW] fix L/2 train roster variants

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md
Use hidden comments to convey hints to the issue/PR creator, rather than having the hints be visible in the ticket by default
=> [issue /PR templates] use hidden comments

lib/engine/game/g_18_mex/game.rb, lib/engine/game/g_18_mex/map.rb
Fixes #7765
Before:
After:
----
=> [18MEX] Change Copper Canyon's town style to `:rect`, make it orange

lib/engine/game/g_1860/game.rb, lib/engine/game/g_1860/meta.rb
Implements the Re-use Of Hexes variant from the official rules, allowing trains to reenter a hex as long as no track is reused.
=> 1860: Implements Re-use Of Hexes variant

lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/step/dividend.rb, lib/engine/game/g_1841/step/track.rb
* Adds 1841-specific train routing rules and revenue calculation
** Need to have at least 2 cities/offboards/non-port towns
** Offboard revenue changes on phases 4 and 6
* Adds 1841-specific dividend rules
** Need to exceed market value to move right
=> 1841: train routing and dividend rules

lib/engine/game/g_18_rhl/step/track.rb
Duisburg title, when using optional promotion tiles, need special handling as it adds a town.
Right now this tile can only be placed in one orientation; attempts to make is possible to rotate were not successful.
Fixes #8654
=> [18RHL] Correct lay of special tile 949

assets/app/view/create_game.rb
Fixes #9233
Attempting to set a bogus `max_players` (i.e. less than the game supports, or zero/negative) will now result in a game where `max_players` is set to the maximum that the game supports
I had to (possibly redundantly) check and correct `max_players` at submit-time, since it didn't seem like the `max_players` set in `update_inputs()` would be correctly modified, otherwise
=> Only allow valid playercounts

lib/engine/game/g_18_sj/step/buy_sell_par_shares.rb
Fixes #9155
This is unlikely to affect any 18SJ games as it gives the option of buying shares that previous implementation did not allow. So it should be backwards compatible.
If not it is likely broken games can be archived (or contact me to look into this issue).
=> [18SJ] Make it possible to buy multiple "brown" shares from treasury

lib/engine/game/base.rb, lib/engine/game/g_1817/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1832/game.rb, lib/engine/game/g_1848/game.rb, lib/engine/game/g_1850/game.rb, lib/engine/game/g_1860/game.rb, lib/engine/game/g_1862/game.rb, lib/engine/game/g_1866/game.rb, lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1870/game.rb, lib/engine/game/g_1873/game.rb, lib/engine/game/g_1877_stockholm_tramways/game.rb, lib/engine/game/g_18_co/game.rb, lib/engine/game/g_18_gb/game.rb, lib/engine/game/g_18_mt/game.rb, lib/engine/game/g_21_moon/game.rb
- Add movement kwarg to sell_shares_and_change_price() to allow caller to override default stock movement
- Add  CLOSED_CORP_TOKENS_REMOVED constant
=> Add override for default stock movement when shares sold and make removing closed corp tokens configurable

lib/engine/game/g_18_tn/game.rb, lib/engine/game/g_18_tn/meta.rb
Implements the official rules variant to allow a third yellow track lay on a corporation's first operating turn.
=> [18TN Implements triple yellow variant

assets/app/view/create_game.rb, assets/app/view/game/buy_trains.rb, lib/engine/ability/train_discount.rb, lib/engine/graph.rb, lib/engine/share_pool.rb, lib/engine/step/route.rb, lib/engine/step/special_buy_train.rb, lib/engine/step/special_choose.rb
- Train discounts should specify rounding to avoid JS/ruby rounding issue
- Train discounts should apply to all variants
- Train discounts should apply during EMR
- Add graph support to check if city is tokenable with a cheater token
- Use game class to determine runnable trains
- Bug fix: When buying a different corporation's share from a corporation, pay the owning corporation
- Add support for corporations having multiple privates with choice_ability
=> Misc common code changes

assets/app/view/game/buy_trains.rb, assets/app/view/game/emergency_money.rb, lib/engine/action/bankrupt.rb, lib/engine/game/base.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/step/bankrupt.rb, lib/engine/game/g_1841/step/buy_new_tokens.rb, lib/engine/game/g_1841/step/buy_sell_par_shares.rb, lib/engine/game/g_1841/step/buy_train.rb, lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb, lib/engine/game/g_1841/step/merge.rb, lib/engine/game/g_1841/step/remove_tokens.rb, lib/engine/game/g_1841/step/track.rb, lib/engine/game/g_1841/step/transform.rb
This implements the EMR and Bankruptcy rules for 1841.
EMR is complicated because of the possibility of corporations selling treasury shares as well as IPO shares as part of EMR and also because multiple corporations can be involved before a player, given the fact that corporations may own corporations.
Bankruptcy is a little more complicated than usual because 1841 specifies two ways a player may bankrupt.
**Common Code Changes**
* lib/engine/game/base - add support for multiple bankruptcy options
* UI::emergency_money - add support for multiple bankruptcy options
* UI::buy_trains - generalized corporation ownership, corporate funds available and corporation owning the shares to be sold
* lib/action/action/bankrupt - add an optional, um, option.
* …
=> 1841: EMR and Bankruptcy

lib/engine/game/g_18_dixie/game.rb
Set the flag so that shares can only be sold once a corporation has operated
=> 18Dixie: Cannot sell shares until a corporation has operated

lib/engine/action/program_buy_shares.rb, lib/engine/game/g_1871/step/buy_sell_par_split_shares.rb
Fixes #9282
1 - Changes `from_market` to also be writable
2 - Add an override in 1871 to float via a purchase from market
On local, it's `testman3` turn, who sets an auto-action which is immediately executed as it's his turn
Setting auto-action
Execution of auto-action
=> [1871]  autobuy from market to float

assets/app/view/game/cash_crisis.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/step/bankrupt.rb, lib/engine/game/g_1841/step/buy_new_tokens.rb, lib/engine/game/g_1841/step/buy_train.rb, lib/engine/game/g_1841/step/emergency_assist.rb, lib/engine/game/g_1841/step/token_emergency_money.rb
* Finishes the last case of EMR: a token purchase after transforming a minor into a major. Unlike other token purchases (when forming a corp), this is the only one that potentially requires more than just issuing IPO shares to cover it.
**Common Code Changes**
* UI::CashCrisis - much like the changes to UI::BuyTrains, I had to customize somewhat for the whole corps owning corps deal. I did test this on 18NY and I don't appear to have broken anything
=> 1841: EMR for tokens

assets/app/view/game/buy_sell_shares.rb, assets/app/view/game/flexible_buy.rb, assets/app/view/game/round/stock.rb, lib/engine/action/buy_shares.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/map.rb, lib/engine/game/g_1841/meta.rb, lib/engine/game/g_1841/round/stock.rb, lib/engine/game/g_1841/step/base_buy_sell_par_shares.rb, lib/engine/game/g_1841/step/buy_sell_par_shares.rb, lib/engine/game/g_1841/step/corporate_buy_sell_par_shares.rb, lib/engine/game/g_1841/step/token.rb, lib/engine/share_pool.rb
This adds player to player stock purchases, as well as player to player and bank owned concession purchases. Concessions always come with the president's share of the corresponding corporation.
It also fixes a few bugs found during live testing.
This adds/changes the following common elements:
Engine::SharePool - add code to handle president changes for certain player to player purchases
Engine::Action::BuyShares - add new optional parameter - total_price, because there was no way to set a total bundle price except by setting the share_price for individual shares - which because of rounding may not add up to the correct value
UI::Round::Stock - support for new FlexibleBuy element
UI::BuySellShares - support for new FlexibleBuy element. Adds buttons that when …
=> 1841: Add player to player share and concession purchases

assets/app/view/game/blind_bid.rb, assets/app/view/game/round/auction.rb, lib/engine/action/blind_bid.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/round/operating.rb, lib/engine/game/g_1841/step/blind_auction.rb
This adds a new auction type: Blind Bidding, for the version 1 rules of 1841
It also finishes the automatic selling of stock for corporations that were frozen due to a circular chain of ownership
This finishes all planned functionality for 1841
UI::BlindBid - new auction type and action
UI::Round::Auction - use BlindBid, and hide bids for companies when blind bidding
Engine::Action::BlindBid - new action for blind bids 
A blind bid:
=> 41: Blind Bidding

assets/app/view/game/emergency_money.rb, assets/app/view/game/sell_shares.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/step/buy_train.rb
Fixes #9348 
UI::SellStock - allow step to override bundle creation. I've tested this w/o the override to make sure I didn't break anything.
UI:EmergencyMoney - fix broken option to Bankrupt action. Only affects 1841.
=> 1841: Fix EMR player sales, fix bankruptcy

lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/step/choose_option.rb
Fixes #9351 
This also fixes an additional problem with mergers I discovered while testing this fix. This is an edge case where corp A owns corp B owns corp C, and A and C merge. Since I didn't construct the list of shareholders until after I moved A and C's stock into the new corp, corp B was left out since it was owned by the new corp and no entities owned the new corp yet. The solution is to generate the list of shareholders before transferring any stock.
While I was at it, I made the UI for mergers, secessions and transformations more user friendly - it was pretty terse before.
=> 1841: Merger fixes

lib/engine/game/g_1888/game.rb
Fixes #9357
Diesels are only buyable after all the 6's
=> [1888] fix diesel buy-on

lib/engine/game/g_1856/entities.rb
- [x ] Branch is derived from the latest `master`
For some reason the train limit increase for the CGR was set to 99 instead of 1. Given how CGR can only buy trains at face value, this is likely unimportant, but regardless, it should be fixed.
=> [1856] fixes train limit increase for CGR

lib/engine/game/g_1822_ca/map.rb, lib/engine/game/g_1822_ca/meta.rb, lib/engine/game/g_1822_ca/scenario.rb, lib/engine/game/g_1822_ca_ers.rb, lib/engine/game/g_1822_ca_ers/entities.rb, lib/engine/game/g_1822_ca_ers/game.rb, lib/engine/game/g_1822_ca_ers/map.rb, lib/engine/game/g_1822_ca_ers/meta.rb, lib/engine/game/g_1822_ca_wrs.rb, lib/engine/game/g_1822_ca_wrs/entities.rb, lib/engine/game/g_1822_ca_wrs/game.rb, lib/engine/game/g_1822_ca_wrs/map.rb, lib/engine/game/g_1822_ca_wrs/meta.rb
* split `HEXES` constant into different parts for easy reuse on scenario maps
* add config for scenarios (trains, different companies used, etc)
#9376
=> [1822CA] Scenario scaffolding

assets/app/view/game/buy_sell_shares.rb, lib/engine/game/base.rb, lib/engine/game/g_1841/game.rb, lib/engine/game/g_18_ny/game.rb, lib/engine/share_pool.rb
Fixes #9379 
Engine::SharePool - add parameter to avoid re-bundling when pres cert is bought
Engine::Game::Base - add parameter to can_buy_presidents_share_directly_from_market? method
UI::BuySellShares - use parameter for can_buy_presidents_share_directly_from_market?
Also, modified 18NY to add parameter to can_buy_presidents_share_directly_from_market? method
=> 1841: allow purchase of president cert directly from share pool

lib/engine/game/g_18_dixie/step/buy_sell_par_shares.rb
Prevent a player from buying a share and a minor in the same stock turn. 
The approach here (`if bought?...`) might not be the best way to do this
=> 18Dixie: Only allow "buying" one thing during a SR turn

assets/app/view/game/choose.rb, lib/engine/game/base.rb, lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/step/private_closure.rb
The 1858 private closure round is implemented using choose actions: for each private railway company, the player is shown a set of buttons with the shares that the private can be exchanged for. If a treasury share is chosen, for a corporation whose president is another player, then we need to check that consent has been received for this exchange.
This pull request adds a `Game::Base::consenter_for_choice` method. If that method returns a player then a consent check will occur. The default implementation of this method is to return nil, which means that no consent checks are needed.
This PR also tidies up 1858's use of choose actions, so that structured information is stored as the choice, instead of storing the button label text.
- ~~[ ] Add the `pins` label if this change will break …
=> Allow consent checks to be required for choose actions

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/route.rb, lib/engine/game/g_1822_ca/step/special_track.rb, lib/engine/game/g_1822_ca/step/track.rb, lib/engine/game/g_1822_ca/step/tracker.rb, lib/engine/step/tracker.rb
- set override constants from 1822 to correct values for 1822CA's privates
- implement the Pullman, which can hit 2xN towns instead of unlimited towns
- fix laying plain yellow city tiles on the city+town hex (M6's home)
- extracted a function from `Engine::Step#legal_tile_rotation?` for a more precise override in `G1822CA::Tracker`
#9376
=> [1822CA] Fix M6's home and implement some basic privates

lib/engine/game/g_1822/step/special_track.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/special_track.rb, lib/engine/hex.rb, lib/engine/step/tracker.rb
* Refactor `Step::Tracker#legal_tile_rotation?` for readability and deubgger-friendliness
* Don't allow a 2-slot city to "upgrade" to a 1-slot city * Extract function to create the old->new city map in Engine::Hex
* Prevent some nil reference errors in `G1822::Step::SpecialTrack`
#9376
Assumption: no implemented games need to upgrade a city to one with fewer token slots
=> [1822CA] Implement P14-P18, "big city" upgrades and a few more config-only privates

lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb
Small Mail Contracts pay the owning Major a subsidy which increases with the phase color, if the Major runs at least one train.
#9376
=> [1822CA] Small Mail Contracts, fix initialization of M13 and Tax Haven

lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/meta.rb, lib/engine/game/g_1822_ca_ers/meta.rb, lib/engine/game/g_1822_ca_wrs/meta.rb
* add setup for full 1822CA from the [2p thread on BGG](https://boardgamegeek.com/thread/2591186/1822ca-2-player-scenarios)
* implement the sell_movement being different for 2p than other player counts * update comments for `SELL_MOVEMENT` in the base game class to include all implemented options, in the same order in which they appear in the `case` block
* fix meta links
#9376
(holding as a draft until rake passes)
=> [1822CA] fix some meta info, finish 2p-specific implementation

lib/engine/game/g_1822_africa/map.rb
Checked all running games and none of them are in brown yet
Y tiles in brown incorrectly had 40 instead of 50 revenue, preventing the upgrade
=> [1822Africa] Fix brown Y tile revenue

lib/engine/game/g_1858/step/buy_sell_par_shares.rb, lib/engine/game/g_1858/step/token.rb, lib/engine/game/g_1858/step/track.rb, public/logos/1858/AS.svg, public/logos/1858/BCR.svg, public/logos/1858/BM.svg, public/logos/1858/CB.svg, public/logos/1858/CM.svg, public/logos/1858/CMP.svg, public/logos/1858/CS.svg, public/logos/1858/HG.svg, public/logos/1858/LC.svg, public/logos/1858/LG.svg, public/logos/1858/MA.svg, public/logos/1858/MC.svg, public/logos/1858/MS.svg, public/logos/1858/MV.svg, public/logos/1858/MZ.svg, public/logos/1858/OV.svg, public/logos/1858/PL.svg, public/logos/1858/RT.svg, public/logos/1858/SC.svg, public/logos/1858/SJC.svg, public/logos/1858/VJ.svg, public/logos/1858/ZP.svg
A few more fixes for 1858. Nothing is touched in shared code.
- Improve loading speed by stopping the game graph from being computed during the game load process. I'd already got rid of most of the calls into the game graph, but missed a couple of places where this was happening:
- When checking if there is a route to an available token slot, and the token could be afforded. Neither of these are checked in `Step::Token.actions` any more, instead `auto_actions` are used to pass the token-laying step if there is no legal token placement option.
- When checking whether another tile lay action is possible after a tile had been laid. Now we just check whether there is another tile lay action allowed, if there is then a new track step will occur, and `auto_actions` will pass if a minor (private …
=> [1858] performance improvements and fixes

lib/engine/game/g_1848/game.rb
Fixes #9452
Override the built-in endgame descriptions
1848 uses a `stock_market` price trigger at 260 to determine whether BoE has hit 16 loans, since it only moves up when a loan is taken. This avoids having to make a custom check, but also means we have to override the base description for that endgame check
Note that the base hash is immutable so we have to redeclare it here
=> [1848] make end text more clear

lib/engine/game/g_1847_ae/entities.rb, lib/engine/game/g_1847_ae/game.rb, lib/engine/game/g_1847_ae/step/buy_sell_par_shares.rb
- Nationalization allows a player that owns at least 70% of a corporation to buy a share from another player, for 150% of the current market value, without asking them for permission. 
- Investor companies are purchasable by players but not by corporations.
=> [1847 AE] Nationalization

lib/engine/game/g_1817/game.rb, lib/engine/game/g_1817/step/reduce_tokens.rb
Fixes #9371 
Clarifies text for reduce_tokens step to explain that you need to remove duplicate tokens from hexes, even if you're below the 8 token limit.
=> [1817] clarifies reduce_tokens message

lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/special_track.rb, lib/engine/game/g_1822_ca/step/tracker.rb
* P19-P20 can lay a yellow in their respective mountain pass hex for free
* uses up the owning Major's full normal tile laying action, i.e., another lay yellow may not be laid before or after, unless with another private ability like the 3-Tile Grant
* if another Major pays for the mountain pass, the private cannot be used, but continues to make its revenue
* fix laying in labeled mountain pass hexes with normal track actions by overriding `upgrades_to_correct_label?`
https://github.com/tobymao/18xx/issues/9376
=> [1822CA] P19-P20 free Mountain Pass privates

lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/step/issue_shares.rb
When issuing shares stock price only moved left one step regardless of the number of shares issues.
Correct behavior is to move one step per share issues.
This change **may** break existing games if they had share issuing
=> [1822Africa] Fix share movement on issue

lib/engine/game/g_1822_africa/game.rb
5/E and 6/E trains in this game can either run normally, or as Express (infinite distance, only count tokened locations, but double the revenue).
- The implementation counts the revenue from running these trains normally and as Express on submitted route, compares the revenue and selects running mode based on which revenue is higher. 
- If selected route exceeds the distance of the train, Express mode is used
- If a Pullman car is attached to */E train, it runs as a normal train
- */E train running in Express mode can use same track as any other normal train (even other */E train running in normal mode)
Note that "6/E" train in this image runs as Express:
The `check_overlap` function is copied from 1822 implementation mostly without changes because my function for determining train type …
=> [1822Africa] Add 5/E and 6/E trains

lib/engine/game/g_18_texas/game.rb, lib/engine/game/g_18_texas/step/discard_train.rb
Fixes #9467 
The game code was not actually removing discarded trains from the company. This corrects that, ensures that they're removed from the game, and displays the message that was initially displayed. 
=> [18Texas] Fixes train discard

lib/engine/game/g_1822_africa/game.rb
Fixes #9476
- Fix Express mode being available if only one token is included in the route
- Fix destination bonus only counting once instead of twice for trains in Express mode
=> [1822Africa] */E train fixes

lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/route.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/discard_train.rb, lib/engine/game/g_1822_ca/step/route.rb, lib/engine/game/g_1822_ca_wrs/game.rb, lib/engine/train.rb
Grain trains can attach to regular trains in order to earn revenue at grain elevators without counting the town as a stop. All standard trains except E-trains can earn bonuses at grain elevators, and an extra bonus if the route includes a grain elevator and a port.
Any train except an E-train can attach a grain train. This is done in the Route step. If a Major owns both a pullman and a grain train, the pullman is attached (or skipped) first.
Details on the revenue bonus rules can be found on page 21 in the [rulebook](https://boardgamegeek.com/filepage/238950/1822ca-rules):
* the table in rule 5.11.27 covers most of it
* 5.11.25 shows the port limit 
Very small, semi-related changes also included here:
* reorder pullman's distance to fix it counting stops; this was broken when enough towns …
=> [1822CA] P26-P27 Grain Trains, grain elevators, and ports

lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/pending_token.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/special_token.rb, lib/engine/game/g_1822_ca/step/special_track.rb, lib/engine/game/g_1822_ca/step/track.rb
* P10 can teleport an Exchange token into Winnipeg, creating an extra slot
* P21 can close to lay 3 additional yellow tiles, which may be interleaved with the corporation's normal tile lays; if only some if its lays are used it closes at the end of the track step
* fix QMOO's home on the Quebec hex so it is not fixed on a particular city until it first operates
#9376
=> [1822CA] Implement P10 Winnipeg Station and P21 3-Tile Grant, fix QMOO's home

lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/map.rb
Implemented functionality of following privates: 
- **P11**: The owning company may close this company when it lays a yellow tile in a mountain hex to earn A50 into its treasury.
- **P12**: The owning company may place any amount of yellow tiles in the hexes marked with desert terrain as their normal tile laying step at normal cost. Using this ability closes the private company.
=> [1822Africa] Implement P11 and P12

lib/engine/game/g_1822_africa/game.rb
=> [1822Africa] Fix auto-pass not disabling in SR x.2

lib/engine/game/g_1841/game.rb
This is a better fix for #9474 
It took me a while, but I root-caused why the above bug only failed on the server and not with validate_json - even with strict:true.
The prior fix works, but this is potentially more robust.
=> 1841: always clear both graphs

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/meta.rb, lib/engine/game/g_1822/step/buy_sell_par_shares.rb, lib/engine/game/g_1822_ca/game.rb
This is a base rule in 1822CA, and an official variant in 1822 (page 28, rule 11.1.2).
This allows the Tax Haven private to use the cash it has accumulated to buy one share per stock round, but it can never buy a second share of a corporation.
#9376
=> [1822CA, 1822] allow Tax Haven to buy additional shares

lib/engine/game/base.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/token.rb, lib/engine/graph.rb, lib/engine/part/city.rb, lib/engine/step/tokener.rb, lib/engine/step/tracker.rb
* let `TILE_UPGRADES_MUST_USE_MAX_EXITS` consider unlabled cities; in 1822CA, upgrading M1 to M3 joins cities up but does not increase value or add new track paths, but is legal * core code modification required to enable this check
* set `TRACK_RESTRICTION`
* allow placing a token in the normal token step in a different city on the same hex where a token is already present * core code modification to plumb `same_hex_allowed` through
https://github.com/tobymao/18xx/issues/9376
=> [1822CA] fix some track and token restrictions

lib/engine/game/g_1822/step/tracker.rb, lib/engine/game/g_1822_mx/step/track.rb
* in previous 1822MX implementation, the extra token was simply destroyed instead of being returned
Fixes #9494
#9376
=> [1822CA, 1822MX] if a city has multiple tokens from one corp, return extra to charter

lib/engine/game/g_1847_ae/game.rb
- In two first phases corporations may lay two yellow tracks
- On its very first operation, a corporation may perform two track actions
=> [1847 AE] Two track actions on first operation

lib/engine/game/g_18_eu/entities.rb
Fixes #8508
No pins should be required, since hexes were previously blocked.
changed 'blocks_hexes' to 'blocks_hexes_consent', as rule 4.6 says you can ignore hex reservations with the consent of the owner of that minor.
Issue #8508 originally was reporting that a minor was able to lay a tile on a reserved hex. This was not actually a bug, since  both minors were held by the same player so consent was implied. The code already made an exception to disregard the reservation if the owners were the same. I left that code in place so that players will not be asked to confirm consent from themselves.
=> [18EU] Checks consent for reserved hexes

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/map.rb, lib/engine/part/path.rb
* fixes Windsor-Detroit and Hamilton-Buffalo in 1822CA
* change France in 1822 to always have 2 lanes, now that 1 lane can run into the two; remove code around "upgrading" France
#9376
=> [1822, 1822CA] match up lanes of different width, simplify France hex

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/destination_token.rb, lib/engine/game/g_1822/step/tracker.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/destination_token.rb, lib/engine/game/g_1822_pnw/game.rb, lib/engine/operator.rb
* GNWR and NTR destinate in specific cities on the Winnipeg hex, which can have as many as 4 different cities
* GT destinates in a specific city on the Montreal hex
* ICR destinates in any city that it connects to on the Quebec hex; if it is connected to multiple cities when placing its destination token, it gets to choose 
* in the DestinationToken step, ICR needs to use the `place_token` action so that the chosen city can be tracked without being recomputed by the engine
* `destination_exits` defines which exits are connected to the destination city by a track path; when checking for a destination connection, these exits are used to identify the destination city (or cities, in ICR's case)
* list the cardinal direction for the locations of the destination city/cities on the corporation …
=> [1822CA] Destinate on a hex with multiple cities

lib/engine/game/g_1846/game.rb
`routes/game.rb` does halt with a 400 error if the player count is wrong when a multiplayer game is starting, and no other games have this logic, so maybe it could be deleted instead? OTOH this should prevent #9222 from occurring again.
Close #9222
=> [1846] bad player count: raise error instead of returning early out of setup

assets/app/view/game_page.rb
In #5604, when an 1846 player makes their Steamboat Company assignments and the OR begins, their opponents won't see hexes available for the active corporation, because the Steamboat is still in their UI state as the `selected_company`.
Fixes #5604
=> Clear `selected_company` when processing an action received from server

assets/app/view/game/buy_trains.rb, assets/app/view/game/train_schedule.rb, lib/engine/game/base.rb, lib/engine/graph.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/dividend.rb
- Hide reserved trains from buyable trains
- Add `round` to `SELL_AFTER` list and add support for issuing shares
- Fix Graph `can_token?` to work when the corporation has no tokens (only private token abilities)
- Add `available_cash` method to `buy_sell_par_shares` step
- Fix dividend log method to handle when their are no dividend receivers
=> Framework bug fixes and enhancements

lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/map.rb
- Fixes the number of private companies in the deck setup (should be 12, not 10)
- Revises map tiles to test for use in the physical game (will change back to unlimited plain yellow tiles after playtest period)
- Removes two (now) unnecessary off-map spikes
This will archive almost all existing games due to the deck setup and tile changes and that is okay.
=> 1822Africa - Update Tiles, Fix setup private company count

lib/engine/game/g_18_eu/step/minor_exchange.rb
Fixes #9283
I don't think this will require pins, since previously players wouldn't have had the choice to exchange at this point. 
Allows players to exchange a minor for a share of a corp they already own 60% of. Player will still have to sell down to 60% at next legal opportunity, as per the last paragraph of rule 4.2.
=> [18EU] Allows minor exchange above 60%

lib/engine/game/g_1822_africa/game.rb
Fixes #9550
*/E train running over the distance were using express mode, but still calculating the best possible revenue. So it could be that such a train runs for 10-20 stops, treats itself as express, but gets revenue as a diesel)
**This will definitely archive some games**
=> [1822Africa] Fix express trains running over the distance

assets/app/view/game/part/town_dot.rb
`render_revenue` can return `nil` early, and if that's left in the `children` array it dumps `undefined` into the DOM.
Pulling this out of #9544
=> Keep `undefined` out of the DOM when rendering town dots

lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_africa/game.rb
This is implemented already in 1822 but I forgot it for some reason.
Also fixed a private selection bug where only first 12 privates of 18 were always in the game.
=> [1822Africa] Implement P13 (Station Swap)

.github/workflows/ruby.yml, Gemfile.lock, docker-compose.dev.yml, docker-compose.prod.yml
* see [opal/opal #2505](https://www.github.com/opal/opal/issues/2505) for note on `OPAL_PREFORK_DISABLE`
=> Upgrade to Opal 1.6.1 (longer stacktraces!); disable opal builder prefork

assets/app/view/game/spreadsheet.rb
this is needed to not break w/ Opal 1.6, also good to not throw `undefined` on the DOM in general anyway (basically another case like #9556)
=> don't return nil during spreadsheet rendering

lib/engine/game/g_1822/game.rb
Adds an `route_distance_str` implementation to the 1822 base which gives a M+N display for pullman trains (to more easily see if the 5+ can keep on running cities) and a M/N display for E trains (where N is the number of laid tokens for the corporation) to more easily see if the company is running the E train as best as they can
Assumes pullmans and only pullmans end in "+" in 22-ish games
=> 1822: Add custom route distance strings for Pullman trains and E trains

lib/engine/game/g_1841/game.rb
Since towns are friendly in the game
Small visual improvement to 1841
Since towns are friendly in 1841 I am adding the CitiesPlusTownsDistanceStr that several other games with friendly towns (like 18Mex) use to get a "M+N" route distance display
!Warning!
I didn't run `rack rake` locally before sending this out, I'm running it now though
--update--
I ran `rack rake` locally and all tests passed
=> Add CitiesPlusTOwnsRouteDistanceStr module to 1841 

lib/engine/game/g_1822_africa/round/stock.rb
I've found a bug which caused minors in bid box 2 or 3 to be removed from the game. This made the game faster if such a minor was left not purchased. The bug was because I partitioned bidbox contents on them being a minor so minor in any bid box could have index 0 and be removed from the game.
This might archive some games.
=> [1822Africa] Fix unnecessary removal of unpurchased minors

assets/app/view/game/corporation.rb, assets/app/view/game/round/operating.rb, assets/app/view/game_page.rb
* the approach in #9527 caused #9563; this reverts that PR
* changing the hex view to match the corporation view, where selected_company is cleared when the action is processed, would work for the current player but would reintroduce #5604
* `View::Game::Round::Operating` sets the selected_company if the step has assignable_corporations, but before this change did not clear the stored state if the step doesn't have any assignable corporations
* fixes #9563
=> clear `selected_company` at the start of rendering for every action

assets/app/view/game/choose.rb, lib/engine/game/base.rb, lib/engine/game/g_1858/step/private_closure.rb
This is two unrelated changes to messages shown to players:
For a game with a game end timing of `:current_or`, if the bank breaks during a stock round you finish the stock round and play one operating round. But the game end message is a bit confusing during the stock round, it says something like:
> Stock Round 7 - Sell then Buy Shares - Bank Broken : Game Ends at conclusion of this OR (7.1)
This changes the message to say 'the next OR' if we are not already in an operating round.
This allows extra text to be shown underneath a group of Choice buttons. If the step has `choice_explanation` method that returns an array of strings then these will be added, with a `<p>` element for each string.
git
=> Changed interface messages: end of game description and choice explanations

assets/app/view/game/bank.rb, assets/app/view/game/buy_trains.rb, assets/app/view/game/corporate_buy_shares.rb, assets/app/view/game/flexible_buy.rb, assets/app/view/game/game_info.rb, assets/app/view/game/hex.rb, assets/app/view/game/issue_shares.rb, assets/app/view/game/map_controls.rb, assets/app/view/game/par_chart.rb, assets/app/view/game/round/unordered.rb, assets/app/view/game/scrap_trains.rb, assets/app/view/game/tranches.rb, assets/app/view/game_card.rb, assets/app/view/game_row_filters.rb
Trying to get ahead of more potential render problems for Opal 1.6 like #9556 and #9560
Methods to fix were identified by temporarily enabling `Style/ReturnNil` and checking with both possible `EnforcedStyle` settings. See [Style/ReturnNil docs](https://docs.rubocop.org/rubocop/cops_style.html#stylereturnnil).
In some cases the caller adds the return value to an Array and then calls `compact`, so the nil/undefined value doesn't end up being sent to the DOM, so not every `return` or `return nil` case is changed here.
=> Don't return `nil` in methods returning rendered items

assets/app/view/game/hex.rb, assets/app/view/game/round/operating.rb, assets/app/view/game_page.rb, lib/engine/game/g_1846/game.rb
Previous attempts:
* take 1: #9527 - cleared `selected_company` when processing action made by another player, regardless of the action type
* take 2: #9573 - intended to clear `selected_company` when rendering after every action, but also did it on other UI interactions, most notably attempting to select a company; so a company would be selected and immediately cleared, breaking a lot of things (#9574, #9576), so this was reverted in ddcfd9f
Manually tested here:
* 1822 bidding no longer disrupted by chat messages from opponents (fixes #9563)
* 1846 steamboat assignment working (verifies #5604 still ok)
* companies can still be bought (verifies #9574 still ok)
* company blocking/track laying works as expected (verifies #9576 still ok)
* tested the different views that update the …
=> selected_company fixes, take 3

assets/app/view/game/part/upgrade.rb, assets/app/view/game/part/upgrades.rb, assets/app/view/game/tile.rb, assets/app/view/tiles.rb, assets/app/view/tiles_page.rb, lib/engine/game/base.rb, lib/engine/game/g_1822_ca/game.rb
Robert Lecuyer gave me some feedback on the 1822CA map, he pointed out the lack of currency symbol on the upgrades. That is standard across 18xx.games, but in the physical games it is standard to show the currency symbol for the upgrade costs.
Sometimes we show minor/corporation names on the hexes to show they'll eventually have a home on that tile; in 1822CA, those minors just have numbers for names, so it's good to have some distinction between the minor and the upgrade cost; here's Toronto, home to Minor 13 and costs $20 to upgrade:
This PR adds a flag to show the currency symbol on the hex. I defaulted to false, only setting it true for 1822CA. I imagine adding another character will cause a lot of new overlap problems, so I'm leaving it as "opt-in" for now.
=> add new constant to show currency symbol for upgrade costs on tiles

lib/engine/game/g_1868_wy/step/waterfall_auction.rb
=> [1868 Wyoming] fix auction sometimes blocking the company choice

lib/engine/game/g_1858/entities.rb, lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/meta.rb, lib/engine/game/g_1858/step/exchange.rb, lib/engine/game/g_1858/step/exchange_approval.rb, lib/engine/game/g_1858/step/home_token.rb, lib/engine/game/g_1858/step/private_closure.rb, lib/engine/game/g_1858/step/private_exchange.rb
This moves 1858 from pre-alpha to alpha status.
There is one new feature added in this pull request: a clearer process for exchanging private railway companies for shares in public companies.
When you get to the private closure round (which occurs at the end of the operating round in which the first 5E/4M train is bought), all remaining private railway companies must be exchanged for shares in public companies, or sold back to the bank. The rules for exchanging privates for shares in public companies run by other players are fairly subtle:
- If the only available shares in a public company are in the bank pool, then the private can be swapped for a share without the consent of the public company's director.
- If the only available shares in a public company are in the company's treasury, …
=> [1858] Private railway exchange approval. Move to public alpha status.

lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_africa/game.rb
After P8 is purchased by minor/major, it allows to reserve three tiles from a choices menu containing all unplaced tiles. These tiles are removed from available and are only added during the turn of the associated major/minor. It can only lay these three tiles if all other rules permit.
Tile selection menu is made using generic choices component so player will have to either know tile ids or reference the Tiles tab to understand what they are reserving
=> [1822Africa] Add P8 (Reserve Three Tiles)

lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/step/route.rb
Safari Bonus acts like a Pullman car, but simply adds bonus revenue if visiting Game Reserve hexes so it was implemented similarly.
A multi-step choose was implemented to handle cases when company has both Pullman and Safari Bonus
=> [1822Africa] Add P18 (Safari Train)

lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/map.rb, lib/engine/game/g_1822_ca/scenario.rb, lib/engine/game/g_1822_ca/trains.rb, lib/engine/game/g_1822_ca_wrs/entities.rb
Various config-only changes that don't really need review which I've been saving up for a while. 
* company names
* company colors
* fix price movement chart
* fix company acquisition phases
* set locs on some of the big city tiles so they look a bit nicer
* rename pullmans from "P+" to "P"
* clean up duplicate hex definition (Y29)
* fix some tile revenues and homes
* better port icon placement (though icon loc for flat is not fully supported yet)
* fix some private and minor company text
* remove some commented code
#9376
=> [1822CA] miscellaneous config changes

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/pending_token.rb
M13 is roughly equivalent to 1822's M14, but in 1822, M14 can have a say in track laid adjacent to the London hex, which is not the case for M13 in Toronto
#9376
=> [1822CA] fix placing M13's home token in Toronto

lib/engine/game/g_1822_ca/game.rb
bug caused by avoiding var name shadowing with a simple appended underscore--one spot in the loop was missed; this changes the outer var to be named `dest_cities` so the inner one can just be `cities` instead of `cities_`
#9376
=> [1822CA] fix destinating

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/scenario.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/scenario.rb, lib/engine/game/g_1822_mrs/game.rb, lib/engine/game/g_1822_nrs/game.rb
In standard 1822, it is always $80 to upgrade an L to a 2; in 1822MRS, 1822NRS, 1822CA ERS, and 1822CA WRS, it is only $70 after Phase 2.
#9376
=> [1822/CA scenarios] show change of L-train upgrade cost on info page

lib/engine/ability/README.md, lib/engine/game/g_1825/step/track_and_token.rb, lib/engine/game/g_1860/step/tracker.rb, lib/engine/game/g_1882/game.rb, lib/engine/step/tracker.rb
The word is spelled "laid", not "layed". This is one of those internet spelling mistakes that have caught on, but are incorrect.
https://brians.wsu.edu/2016/05/19/layed-laid/#:~:text=Although%20%E2%80%9Clayed%E2%80%9D%20is%20an%20extremely,You%20laid%20down%20the%20law.
=> Corrects spelling of 'layed' to 'laid' throughout site.

assets/app/view/welcome.rb, lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/meta.rb, lib/engine/game/g_1822_africa/step/choose_express_train.rb, lib/engine/game/g_1822_africa/step/choose_safari_train.rb, lib/engine/game/g_1822_africa/step/route.rb, lib/engine/train.rb
Fixes #9550
As per discussion with designer in #9550 only one */E train can run as Express so it was decided to implement a selector to choose which train should be the E train. It was done using Choices action during Run Routes step.
This also allowed to remove all custom routing and revenue calculation code and simply reuse it from 1822.
I had to make train `multiplier` field writable to avoid complicated shenanigans with train substitution
=> [1822Africa] Refactor E trains

lib/engine/game/g_1858/entities.rb
M&A, V&J and M&C all had mistakes in their descriptions, giving the wrong home hex coordinates.
Fixes #9641.
=> [1858] Fix incorrect home hex descriptions on privates

lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
Fixes #9662 
By adding the @auctioning && check, The code checks that min_bid is only called when @auctioning is not nil, which prevents the "undefined method `zero?' for nil" error and allows the proper next steps to follow.
=> [18EU] fixes auction when players have zero cash. 

lib/engine/game/g_1822/step/special_track.rb
someone put the `!` in the wrong spot in #9196
Fixes #9231
=> [1822,1822MX,1822CA] fix advanced tile lay with minors

lib/engine/game/g_1868_wy/game.rb
The new city/town was not added to the tile's `city_towns`, which is what is checked for determining if boomtown/boom city tiles should be used.
Fixes #9651
=> [1868 Wyoming] fix pure oil placement

assets/app/view/game/map.rb
Fixes #9605 for Opal 1.6 (progress for #9608); the issue is not present with Opal 1.5.
**Explanation of Change**
The `selector` variable is set here with an `if` block, like this:
```
selector =
if ...
...
end
```
In Opal, this is compiled as `selector = (function() { ... })();`.
The problematic line is:
```
return h(:div) if select_tiles.empty?
```
In Opal 1.5, this `return` is incorrectly applied to the function wrapping the
`if` block for defining `selector`:
```
if ($truthy(select_tiles['$empty?']())) {
return self.$h("div")
};
```
That bug is fixed in Opal 1.6, and the line is compiled so that the `render`
function is the one that returns, causing the whole map to be rendered as an
empty `<div>`, instead of only the `TileSelector` being rendered as an empty
`<div>`:
```
if …
```
=> Fix map rendering with TileSelector for Opal 1.6

lib/engine/game/g_18_nl/step/token.rb
Fixes #9677
Game was locking up because of an invalid past blocking step if a corp with no tokens had the P2 token ability still available, due to the way I introduced a blocking step. 
Added condition to check if corp has any remaining tokens before blocking
=> [18NL] adds check that corp has remaining tokens before blocking on token step.

assets/app/view/game/flexible_buy.rb, lib/engine/game/g_1822/round/stock.rb, lib/engine/game/g_1822_africa/round/stock.rb
[opal/opal #2357](https://www.github.com/opal/opal/pull/2357) revamped how closures are tracked. As described in #9673, this is better behavior and unveiled some problems in our code, but Opal itself has a bug here (at least in 1.6.1), where a `return` inside of a lambda causes the enclosing function, instead of the lambda itself, to return. Fortunately, in a lambda, `next` behaves the same as `return`, so we can work around this issue by using `next` in our lambdas.
Fixes #9603, #9604, #9606 for Opal 1.6--progress on #9608
=> [Opal 1.6] don't use return inside of a lambda

lib/engine/game/g_1868_wy/entities.rb, lib/engine/game/g_1868_wy/game.rb
- remove the `close` ability, the closure is instead handled by `event_close_privates!`
- change how the owning corporation's hex token is handled so that it can easily be cleaned up when the Pure Oil Camp hex becomes a ghost town
Fixes #9699
=> [1868 Wyoming] fix closing Pure Oil Camp at phase 7

migrate_game.rb, validate.rb
Small changes made while I looked at #9697.
Previously, if `nil` was passed in for `pin` when calling `migrate_all()`, the game's `settings` in the DB would be updated with `pin: nil`, which is undesirable for certain calls which check whether the `pin` key exists at all, instead of checking if its value is a real pin.
=> migrate_game: skip pinninng if `pin` is `nil`; validate.rb: make filename kwarg on validate_all()

lib/engine/game/g_1861/game.rb, lib/engine/game/g_1867/game.rb
In the section underneath the bank on the entities page, 1867 was only showing the national railway. This commits adds unstarted minor and major railways to this section. 1861 was already showing minors, majors are now added. The number of unstarted minors is added to the bank box in 1861.
Fixes #9524.
=> [1861/1867] Show unstarted corporations on entities page

lib/engine/game/g_1858/map.rb
Icons are used to mark the private railway companies' home hexes. A couple of these were missing: for L&G in F1 and for M&C in L19.
Fixes #9667.
=> [1858] Add missing home hex markers

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_ca/game.rb, spec/lib/engine/tile_spec.rb
- add constant specifying illegal tile upgrades which the game code would otherwise allow
- add unit tests to verify the possible upgrade paths for the big city tiles 
- in the test, check for a tile with the given name before checking the hex; 1822CA has some overlap there, e.g., M5 and M7
- when `upgrades_to?` is called in the test, there is no hex, so `G1822CA::Game#upgrades_to_correct_label?` and `G1822::Game#upgrades_to?` have to make sure the hex is non-nil before calling `.name` on it
#9376
=> [1822CA] fix big city upgrades

assets/app/game_class_loader.rb
While debugging performance with different Opal versions, I found via console output that the sample game of 1822MRS I was using was frequently being loaded twice on page load or refresh. This problem affects all games which depend on another one, such as 1861, 18USA, and of course all of the 1822 variants.
This doesn't directly fix anything related to Opal performance, though while Opal 1.6 was deployed, the performance decrease would have been roughly twice as noticeable to anyone playing one of those dependent titles.
=> Stop processing games multiple times

lib/engine/game/g_18_dixie/companies.rb
Fixes minor typo in 18dixie companies
- [] Tests pass cleanly with `docker compose exec rack rake`
Fixes a typo
n/a
n/a
=> Fix typo in 18Dixie companies

lib/engine/ability/README.md, lib/engine/ability/base.rb, lib/engine/game/base.rb, lib/engine/phase.rb
If an ability uses `on_phase`, `ability_right_time?` will return before checking `when` conditions. This change will first check if it is the right phase and if it is, proceed to check the `when` condition.
The PR also includes a new attribute called `after_phase` which `ability_right_time?` will make sure the game has moved past the specified phase.
=> Allow abilities to use on_phase and when together. Add after_phase attribute

lib/engine/game/g_18_tokaido/entities.rb, lib/engine/game/g_18_tokaido/tiles.rb, public/logos/18_tokaido/ARC.alt.svg, public/logos/18_tokaido/ARC.svg, public/logos/18_tokaido/KRC.alt.svg, public/logos/18_tokaido/KRC.svg, public/logos/18_tokaido/NAN.alt.svg, public/logos/18_tokaido/NAN.svg, public/logos/18_tokaido/SHI.alt.svg, public/logos/18_tokaido/SHI.svg, public/logos/18_tokaido/SRC.alt.svg, public/logos/18_tokaido/SRC.svg, public/logos/18_tokaido/YSL.alt.svg, public/logos/18_tokaido/YSL.svg
Changes to get in sync with current version of in-progress print prototype.  A couple company (three-letter) code changes to match the prototype map, some tile number changes to match prototype tile sheet, and colors now match 18Chesapeake.
All the code changes are basically cosmetic, but pretty sure the private/company three-letter code changes require a pin.
=> [18Tokaido] color plus name changes to match print version

lib/engine/game/g_1870/step/price_protection.rb
Fixes #9321
the price_protection.rb file for 1870 defined can_buy? but didn't include arguments, while the call passes two arguments. This fixes it. 
edit: not sure if pins will be required, since affected games would bounce back to a previous step when the error occurred.
=> [1870] adds missing arguments for can_sell?

lib/engine/game/g_1847_ae/entities.rb, lib/engine/game/g_18_nl/entities.rb
Fixes #9726 
Fixes the text of the Rammelsbach private to say the revenue increases when E9 is laid, rather than the current D9. The code in the game.rb file applies the bonus properly, it was just the description text that was wrong.
I also took the opportunity to correct a missing space on a private company in 18NL.
=> [1847AE] fixes text of Rammelsbach private

lib/engine/game/g_1844/game.rb
Fixes #9750 
Code was set to rust the 4 trains on '7', but they rust on the 8E, which is technically phase 7 in the rules.
No pins should be needed, games on site are all still in the opening auction.
=> [1844] fixes 4 train rust

public/fixtures/18NL/135853.json, public/fixtures/18NL/135870.json
Adds two fixture files for 18NL
=> [18NL] adds fixture files

assets/app/view/game/round/stock.rb, lib/engine/game/g_18_dixie/game.rb, lib/engine/game/g_18_dixie/step/buy_sell_par_shares.rb, lib/engine/game/g_18_dixie/step/selection_auction.rb
Fixes P6/P10 (B&O like privates that can be bought in the stockround) for 18Dixie
I meant to work on the obsolete trains train limit here but I got side-quested with this, which I thought worked before but might not have ever worked. 
- [x ] Tests pass cleanly with `docker compose exec rack rake`
Updates the stock page to allow handing `companies_pending_par` in stock rounds and uses that in 18Dixie to get P6/P10 working
=> 18dixie fix b&o-like privates

migrate_game.rb
Remove the section of the `migrate_game.rb` script for issue #9655 as this migration has been completed.
=> Remove completed migration script for 1861/1867 issue #9655

assets/app/view/welcome.rb, lib/engine/game/g_1858/meta.rb
1858 has been in alpha for three weeks with no game play bugs reported, so move to beta status.
=> [1858] Move to beta

assets/app/view/game/player.rb
Fixes #9753
Uses the minor's simple_logo preference 
Likely affects other games besides '80 which have similar mechanics
=> [1880] show simple logos for FIs on player cards

assets/app/view/game/stock_market.rb, lib/engine/game/g_18_zoo/game.rb
Fixes #9693
As requested inside the issue, the stock market was updated to support the info, but only for the 2d grid
=> 18ZOO - Update StockMarket to show bigger cells when there is any user info in any cell

lib/engine/game/g_1868_wy/round/bust.rb
Adds LHP to BUST round entities; train export happens after an OR set but before a BUST round.
Much nicer than the attempt to handle this in the SR (#9785)
Fixes #9714
=> [1868WY] fix LHP assignment when phase 5 is triggered by export

lib/engine/game/g_1822/step/special_track.rb
Fixes issue in 1822CA with the "major city upgrade" privates being usable by minors to upgrade Montreal/etc. to brown and gray. #9376
Now includes actual validation, so pins will be needed for #9196 and #9669
=> [1822 family] never let minors use a private to lay brown or gray tiles

lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/step/special_track.rb
P5 (Pullman) is replaced with P5 (Add Town) which works like P9 (Remove Town), but in reverse.
=> [1822Africa] Change P5 from Pullman to Add Town

lib/engine/game/g_1822/step/route.rb
Fixes #9724
Fixed in base 1822 because it may affect other versions too.
=> [1822Africa] Allow Pullman trains to visit stops with 0 visit cost

assets/app/view/game/stock_market.rb, lib/engine/game/g_18_zoo/game.rb
Fixes #9693 
In https://github.com/tobymao/18xx/pull/9731 I changed a style shared, in this case I renamed it to be specific to own flow, and created a new property, specific for 2D with user info (and the only market with that configuration is 18ZOO)
As requested inside the issue, the stock market was updated to support the info, but only for the 2d grid
Right now no game is using the user info inside the market; maybe in the future the size of the market could be related to the specific game, instead of just 2 values (with user info / without user info)
=> 18ZOO - Update 2D StockMarket to show bigger cells when there is any user_info in any cell

lib/engine/game/g_1841/step/buy_token.rb, lib/engine/game/g_1841/step/buy_train.rb
Fixes #9832 
Fixes #9834 
The first fix will need to archive '41 games that broke the rules.
=> 1841: prohibit x-corp EMR buy; prohibit selling last non-pass placed token

lib/engine/game/g_1830/entities.rb, lib/engine/game/g_1836_jr30/entities.rb, lib/engine/game/g_1836_jr56/entities.rb
Fixes #[9818]
Added a sentence explaining that the teleport ability in 1830 and both variants of 1836jr require that the teleport hex be empty in order to use the private ability, as I've seen the question come up more than once.
=> [multiple] clarifies text for teleport abilities

lib/engine/game/g_1844/map.rb
"appelzell was labelling an empty hex instead of the correct city location (neighbouring hex)
=> [1844] fixes placement of Appelzell name on map

lib/engine/game/g_1847_ae/game.rb
Add the missing "MUST_SELL_IN_BLOCKS" setting.
=> [1847 AE] Must sell shares in blocks

lib/engine/game/g_1840/step/dividend.rb, lib/engine/game/g_18_mag/step/dividend.rb, lib/engine/game/g_rolling_stock/step/dividend.rb, lib/engine/step/dividend.rb
Currently, if one creates a game with a "variable" dividend payout method and a custom 'dividend step', one must also define a specific set of methods in the custom step or the custom step will error out.
This attempts to shave off those rough edges by adding default methods in `step/dividend base`, which are called [from view/dividend](https://github.com/tobymao/18xx/blob/master/assets/app/view/game/dividend.rb#L147) to render the variable payout UI. 
I tried to set sane defaults here, LMK if these need tweaked
This also removes the relevant custom method definitions in 1840 and Rolling Stock which can just use those defaults
=> generalize values used for variable dividends

lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_africa/round/stock.rb
Fixes #9837
1822Africa has a custom `finish_round` function for stock round and sold out increase was called unconditionally.
=> 1822Africa - Remove sold out increase

assets/app/lib/radial_selector.rb
Fixes #9855
Add a new z-index value to the radial selector.  This issue was introduced in https://github.com/tobymao/18xx/commit/9c0e13167f619f6c699e2e80a5a02ebb4b3d1204, specifically with adding `position: relative` in [this line](https://github.com/tobymao/18xx/blame/bb32b0318896fd2e63e72529ee47159b6484c47a/assets/app/view/tiles.rb#L62).  I don't know why this causes this problem specifically.  Alternatively, this `position:relative` could be reverted, but that causes issues in the tiles/test page that was added in that commit.  This seemed like the easier option.
I could not recreate the second portion of that issue for upgrades not appearing.
| Old | New |
| :---:        |   :---: |
| …
=> Add z-index to radial selector to ensure that all tiles appear on top.

lib/engine/game/g_1850/entities.rb, lib/engine/game/g_1850/game.rb, lib/engine/game/g_1850/step/track.rb
Fixes #9863
Private was closing if any of the 3 tile lays had been used. Should only close if all 3 have been used. I updated the text on the private to match the text on the physical card, which also meant updating the abilities of the private to close immediately once all 3 tile lays have been used, which also allowed the method in game.rb to be simplified for WLG, since it only needs to check that it is still open. 
Also fixed several instances in the code where "company" was misspelled as "compnay"
=> [1850] fixes Western Land Grant closing, and typos

lib/engine/game/g_18_ny/round/capitalization.rb
18NY Operating Round class has special handling for auto actions. Don't inherit from it for the Capitalization Round.
=> [18NY] Use Operating Round base class for Capitalization Round.

lib/engine/game/g_18_eu/meta.rb
Fixes #9862 
Moves 18EU back to beta. From the Issue report: 
"There are currently 16 open bugs for 18EU. 11 of them are to do with the final exchange round. Several of these prevent the game from proceeding. The oldest of these reports is over a year old."
=> [18EU] moved back to beta

lib/engine/game/g_rolling_stock/step/dividend.rb, public/fixtures/RollingStockStars/dividend.json
Fixes #9888
Rolling stock's dividend step used to inherit from base.rb instead of base/dividend.rb, for some reason
Also adds a test file
=> [rolling stock] fix broken dividend step

lib/engine/game/g_18_tokaido/game.rb
Any private companies remaining after the initial round should be closed via init_round_finished.  I verified the fix by taking the [given game](https://18xx.games/game/138956), undo all the way to the beginning, then redo all the way and I was able to proceed.
Fixes #9839
I added a big description in the issue, but the basic issue is that a private company ended up in the Bank by accident, and when private companies were paid out at the beginning of the operating round, there was sorting code that tried to compare a corporation to the bank.
=> [18Tokaido] Make sure initial round is finished properly

lib/engine/game/g_1848/step/check_com_formation.rb
Fixes #9847
This issue was introduced in 6e628bec64f5bf0d6e5742a294b63ec40f3f1c53.  This commit reversed the order that `actions` and `blocking?` are evaluated in.  In the existing code for 1848, this order mattered, because `actions` had a side-effect to set `@connected` to true, which was then used in `blocks?`.
When this order was reversed, `blocks?` will always return false, and `actions` will be short-circuited out of that check, never being evaluated.
This change removes `@connected` and calls the actual connection check at each point to remove any ordering problems when things are called.  This change also deactivates the step once the connection is made.
=> [1848] Fix timing issue with calling actions and blocks?

lib/engine/step/dividend.rb
Fixes #9882
The base dividend `skip!` function was overriding corp operating history to insert a zero payout 'withhold'
I wanted to double-check that in such cases we were still outputting corp operation history, so I checked and every game that overrides `process_dividend()` will still output corp operating history - either implementing a game-specific operating history (i.e. games with "psuedo-corps" like Bank of England) or calling `super`
=> don't override dividend history when skipping dividend step

assets/app/view/game_card.rb
Fixes #9913
Adds the dev_stage of games in the game card on the main page, unless the game is already in production.
You can ignore the first commit, I was initially also including prototype status, and the game location. Toby requested not to include location, and it was decided that prototype was also unnecessary.
=> [improvement] Adds the development status to game cards on homepage

lib/engine/game/g_1844/game.rb
Fixes #9916
In the current implementation, when selling shares of an unoperated corp, the payout was determined by checking the find_share_price method and then going :down a number of spaces equal to the amount of shares sold. However, in 1844, the price only drops once per bundle sold. 
I corrected the calculation.
=> [1844] Fixes payout on sales of unoperated corps

lib/engine/game/g_1880/step/assign.rb
Fixes #9791
I believe this will require pins, since players could have inserted a 'pass' action for an "Assignment" step which is now skipped
Skips the 'P5 assignment step' when the active corp already has a D permit
Adds an error case if the player tries to assign P5 to a corp that already has a D permit
Also made some "happy to glad" changes to the verbiage
The below cases assume that a corp is operating whose president owns the P5
To address the specific case in the issue: in D phase, the Assign step will NOT block (be skipped) if active corp already has a D permit
in D phase, an Assign step will block if P5 can be used if active corp does not have a D permit
P5 cannot be used if corp already has a D permit
P5 can still be used earlier in …
=> [1880] skip P5 assignment if corp already has D

lib/engine/game/g_1848/step/dividend.rb
Output revenue history for BoE
before:
after:
=> [1848] output BoE revenue history

lib/engine/game/g_18_tokaido/game.rb
Fixes #9902, backs out the breaking change for #9839 and fixes that underlying issue.
There's a sort in `payout_companies` that breaks when both the bank and corporations own anything (works fine if it's only one or the other).  @andrewzwicky tracked that down, but his change both broke a bunch of existing games where the corporations weren't already removed, and also...  They're not supposed to be removed.  So I backed out that change and fixed the actual sort issue.
TBH, I think the version of `payout_companies` I put in my game object could go in the main engine (whether you filter out the bank owned companies or short-circuit the payout loop, the result is the same), but in the interests of not potentially breaking anything else, I just did the minimal thing.
=> 18 tokaido fix sort key issue

lib/engine/game/g_1849/step/buy_sell_par_shares.rb
Fixes #8384
Currently, autopass always disables if the 20% final cert is available for purchase and you can afford it. 
This update first checks if the share is in the treasury, and then verifies if the active player has sold shares this round. If yes, autopass remains enabled. It then checks if the share is available from the bank pool. In that case, autopass is disabled even if the player has previously sold shares, in the event that the active player wants to sell a share to block the purchase of the double share. 
=> [1849] autopass tweak

lib/engine/game/g_1846/step/track_and_token.rb
=> [1846] highlight "teleport" token hexes for PRR and B&O

assets/app/view/welcome.rb, lib/engine/game/g_1868_wy/meta.rb, lib/engine/game/g_1868_wy_simple_2p.rb, lib/engine/game/g_1868_wy_simple_2p/game.rb, lib/engine/game/g_1868_wy_simple_2p/meta.rb
Uses same rules as normal game with scaled cert limit and starting cash. Does not implement 2p rules in rulebook.
This was suggested in discussion with John Harres at TraXX, a few friends of his are interested in playing 2p even without the full rules implementing the "Doc" player (a bit like "Vaclav" from 2p 18CZ).
=> [1868WY] move to beta; also add "simple" 2p variant

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/destination_token.rb, lib/engine/game/g_1822_ca_wrs/game.rb, lib/engine/part/city.rb
In the full game, M18's home is on the eastern half
Similar to QMOO/Quebec issues, so some of the logic in #9936 is generalized here.
Core change: allow a "cheater" token to create its (temporary) extra slot if other slots are occupied by reservations, not just tokens; this allows GNWR's home token to appear next to Minor 18's home reservation
#9376
=> [1822CA WRS] fix GNWR sharing home with M18

lib/engine/game/g_1822/step/buy_sell_par_shares.rb
A lot of bid-related rendering depends on `bid` appearing as one of the step's current actions, e.g.,
https://github.com/tobymao/18xx/blob/0bad615d8eda50db7bb2885ebdb9f94da2863fea/assets/app/view/game/round/stock.rb#L356
This causes a bug where if one player has debt (and therefore does not have the `bid` action available), previous bids and bid tokens can fail to render.
Screenshot 1 - JFParadis has made bids on 3 privates, no bid is visible on P6 (Pullman) -- the other privates are rendered below the screen:
Screenshot 2 - no bids shown on the other two privates, bid token count is not listed for any of the players; note that jonathan has a loan
This change makes `bid` always included in the possible actions, and raises a `GameError` to prevent indebted players from actually making …
=> [1822 family] don't break rendering on bidding due to player debt

lib/engine/game/g_1822/step/buy_sell_par_shares.rb
This reverts commit 788f62c9a95677d81b0f6407add057036c864526, reversing changes made to 21263d8ea6db948a831fa6f269315bdd9ab78f59.
This probably fixes #9946 and #9947
=> Revert "Merge pull request #9938 from michaeljb/1822-debt-rendering"

assets/app/view/home.rb
Games without `updated_at` are put at the front, alpha-sorted by id.
=> Home page: sort hotseat games by last updated time

lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/step/special_track.rb, lib/engine/game/g_1822_ca/step/tracker.rb
* Fix P19,P20,P29,P30 correctly using up full track action 
* slight refactor to simplify P19 and P20 -- remove mountain pass abilities when mountain pass built, instead of checking if they're built in the `abilities` call
#9376
=> [1822CA] private track actions

lib/engine/game/g_1850/game.rb, lib/engine/game/g_1850/step/price_protection.rb, public/fixtures/1850/115810.json
**Explanation of Change**
Per 1850 rules a president can use price protection even if he already sold shares in the company. 
This is different from 1870 rules, so this fix is needed. 
**Any Assumptions / Hacks**
* I've decided to not allow president to use price protection to buy the shares he sold himself, otherwise it leads to possible infinite SRs.
* Migrate script was able to repair the fixture, so most possibly pins won't be needed, only migration of existing games as they are easily fixable by adding a pass.
=> [1850] Fix price protection

lib/engine/game/g_18_eu/game.rb
Fixes #9805
- N/A Add the `pins` label if this change will break existing games
I don't think this needs pins because the case where it makes a difference was previously an exception, so there should be no actions broken by this.
This bug comes from the code trying to decide if the Depot needs to discard its Pullman trains.  This code is called during the final exchange round when you both: exchange for a market share AND your minor has trains.  If either of those conditions is not met, the game will progress.  i.e. if your minor doesn't have any trains, the market exchange works fine.
=> [18EU] Fix problem exchanging minor for market shares when it has trains

lib/engine/game/base.rb, public/fixtures/18Mag/plus_train_power.json
Fixes #9996
Explicitely convert the number of paying stops to an int 
This seems to be an issue w/ Opal, as there have been other patches (including in the line below this one) that fix similar issues
Includes a fixture to test this fix
=> [18Mag] fix int conversion issue w/ Opal

assets/app/view/game/company.rb, lib/engine/game/g_1817/game.rb, public/assets/main.css
In fbcd3ed `min-height:100px` was added to the `.card` css to ensure that the empty slots in the 1817 auction were not too short (my assumption).  In other games, this adds tiny bars to some of the minor corp cards that don't have much info.  This change reverts the `min-height` and replaces it with a description of a few newlines for those empty slot companies.  To allow this to work, the description style now has the `whiteSpace: 'pre-line',` property, which is identical to `normal` except that it preserves newlines.  I didn't see any newlines in any other company descriptions.
| ![image](https://github.com/tobymao/18xx/assets/5263073/3182d8ff-e05c-4581-b7aa-ef7938023a44) | …
=> [multiple] Adjust CSS to not add extra bar under minor companies.

assets/app/view/welcome.rb, lib/engine/game/g_1850_jr.rb, lib/engine/game/g_1850_jr/entities.rb, lib/engine/game/g_1850_jr/game.rb, lib/engine/game/g_1850_jr/map.rb, lib/engine/game/g_1850_jr/meta.rb, public/fixtures/1850Jr/hotseat.json
Implements 1850jr, a small 1830 clone from 1995 that was originally published in an Italian fanzine. [BGG link](https://boardgamegeek.com/boardgameexpansion/154473/1850jr). I reached out to the designer via BGG and got his permission. Screenshot of geekmail below. 
Maybe just a curiosity of a game, but I played a couple of hotseat games and there were at least a few interesting moments.
=> 1850jr init commit and to alpha

assets/app/view/game/corporation.rb, assets/app/view/game/round/auction.rb, lib/engine/game/g_18_eu/step/modified_dutch_auction.rb
Noticed while looking at #9945, because that minor does have bids on it, but they're not shown, so it's tough to tell.
In an `Auction` round, if minors are being displayed, show bids if there are any for that minor.  Most applicable for 18EU.  I couldn't find another game with the right set of criteria to benefit from this.  Some don't use actual minors, just corporations with the type "minor", and some use other rounds that don't inherit from Auction.
| ![image](https://github.com/tobymao/18xx/assets/5263073/7675cf9d-073a-4473-bd22-c9cb982884e2) | ![image](https://github.com/tobymao/18xx/assets/5263073/01c38ae0-1918-4e36-bff8-49a6c5640601) |
=> [18EU] show bidders on corporation cards

lib/engine/game/base.rb
Fixes #10026 
The code previously didn't take into account that it would prevent you from selling stock in another corp which had operated only once if you were also the president of that corp. This should fix that by also checking if the bundle.corporation is the @round.current_operator.
I ran a couple of tests, but given its failure the first time, I'd appreciate it if someone else can't take a look and make sure I got it right this time.
=> [1822] fix for full_or_turn SELL_AFTER case.

lib/engine/game/g_18_eu/corporation.rb, lib/engine/game/g_18_eu/game.rb, public/fixtures/18EU/can_hold_70_percent_before_operates.json
Fixes #9987 
This is a mismatch between `must_sell?`, `can_sell_anything?` and `holding_ok?`.  The game processes that you can sell something (FS), and you must sell something (over 60% cert limit in AIRS), but it doesn't know that you can't sell the thing you're over the limit in, so it keeps telling you to sell until you can't sell anything any longer.
This change adds a `holding_ok?` to the 18EU corp so that holding is ok if the corp hasn't operated yet.
| ![image](https://github.com/tobymao/18xx/assets/5263073/6908a49b-fe94-4471-a060-b4fb91ae3261) | ![image](https://github.com/tobymao/18xx/assets/5263073/1b83407a-31ac-4b1b-9a70-2ba967c3fdd9) |
=> [18EU] Allow holdings above limit when corporation hasn't operated yet.

lib/engine/game/g_1871/step/buy_sell_par_split_shares.rb
The player's pass flag was not being cleared on a split action. This could result in a stock round ending early: if a player had passed, then split a corporation on their next action, and all others then passed, the stock round will end without the splitter getting another action.
Fixes #10038 and #8568.
This might break a few games. It's a fairly weird set of actions that could trigger this bug, but there might be some games that are broken by this fix and will need pinning or archiving.
@kelsin: can you please review this fix? Github isn't letting me add you as a reviewer.
=> [1871] Call player.unpass! in process_split

lib/engine/game/g_1830/game.rb, lib/engine/game/g_1830/meta.rb
Fixes #10046
The Avalon Hill rules did include an option to add a 3rd 6-train. This is also referenced in the Mayfair rules:
=> [1830] adds 3rd 6-train option

lib/engine/game/g_1866/game.rb
Fixes #10050 
Updates the description text when buying Stock tokens to be a little more precise. 
=> [1866] updates description text for buying stock tokens

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/double_share_protection.rb
* don't increase price past original sale price when new president buys shares to protect their Ames double share
* fix error when logging price change
Fixes #10028
=> [1868WY] fix Ames double share protection

lib/engine/game/g_1868_wy/game.rb, lib/engine/game/g_1868_wy/step/dividend.rb, lib/engine/game/g_1868_wy/step/double_head_trains.rb
When double-heading trains, first detach the token, and re-attach it to the double-headed train, re-attaching it to the original train when the double-headed train is "rusted" in the divdend step for being obsolete.
Fixes #10040
=> [1868WY] fix Big Boy [+1 +1] token with double-headed trains

assets/app/view/game/part/city_slot.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca_ers/entities.rb, lib/engine/operator.rb, lib/engine/part/city.rb
1822CA introduces destination tokens that are specific to cities and slots, rather than just the hexes, as seen in other 1822 games.
This will make it clear which city needs to be hit for the destination to be complete. Icons in city slots also count as reservations, meaning other corporations may not token there.
[#9376]
=> [1822CA] Allow icons to be rendered in city slots; use for destinations

lib/engine/game/g_1822_ca/game.rb
Fixes issue where a company could have only one train but collect bonuses from both the small and large mail contracts.
#9376
=> [1822CA] compute small mail contracts with large, limit one contract per train

Makefile, queue.rb
* rsync `public/pinned` on deployment so the current release always shows up in pins directory, simplifying the process to pin games
* clean up unused pin files daily in `queue.rb` * keep the newest few around so that just-deployed pins aren't cleaned up before they can be used
=> rysnc the pinned directory on deploy, clean unused pins in queue

lib/engine/game/g_18_mt/companies.rb
Correct spelling of “White Sulphur Springs”
=> correct typo 'Sulpur'

assets/app/view/welcome.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/meta.rb, lib/engine/game/g_1822_ca/scenario.rb, lib/engine/game/g_1822_ca_ers/entities.rb, lib/engine/game/g_1822_ca_wrs/entities.rb, lib/engine/game/g_1822_ca_wrs/game.rb
Move `init_companies` from `g_1822_ca_wrs/game.rb` into `g_1822_ca/scenario.rb` so ERS can use it as well, so the corporations with a different home/dest in the scenarios can have their concession description updated as well.
Closes #9376
=> [1822CA] move to alpha (update welcome page), add home+dest info to concessions

lib/engine/game/g_18_gb/step/special_token.rb
Fixes #9262
* Private company powers in 18GB can only be used once the company has been closed (by using the `choice` ability on the company) by its owner. Therefore in the `abilities` function in `game.rb` for 18GB, abilities are filtered based on whether or not the company has been closed
* However, the standard `special_token` step (from which 18GB's `special_token` step inherits) was bypassing this check with its own `ability` function, allowing a token to still be placed at some times when it should not
* Therefore, this change updates 18GB's `special_token` step to filter out the abilities based on company status and avoid a token ability being used illegally
=> 18GB: Prevent special token powers being used illegally

lib/engine/game/g_18_va/entities.rb
Fixes #9686 
- [ x] Branch is derived from the latest `master`
- [ x] Add the `pins` label if this change will break existing games
- [ x] Code passes linter with `docker compose exec rack rubocop -a`
- [ x] Tests pass cleanly with `docker compose exec rack rake`
Changing the timing from `buying_train` to `buy_train` fixes Tredgar; looking at the `ability_right_time?` implementation it looks like `buying_train` isn't the name of a step or explicitly stated so it doesn't get past this
https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L3082
Are other games that use `when: 'buying_train'` broken?
Looking at this and the blame for game::base, I'm not sure how Tredgar ever worked
=> Fix Tredgar in 18VA

lib/engine/game/g_18_gb/game.rb, public/fixtures/18GB/18gb-leased_train.json
Fixes #9877
If a corp in receivership would have to lease a train but there are none, it doesn't get to lease one at all
This should be a no-op in practice, as the game ends soon after the final train is purchased - and receivership corps just withhold to buy a train anyway (which never happens as there are none)
Shouldn't require pins as this PR handles an edge case that would have broken existing games
See linked older PR for more details
=> [18GB] receivership corps can't lease a train if there are none

lib/engine/game/g_18_usa/entities.rb
Fixes #10105
Updates description of P18 and P28 to say "in a coal hex" instead of "in a mountain hex".
Also removed some double-spaces after periods.
=> [18USA] corrects description of P18 and removes double spaces

lib/engine/game/g_1870/game.rb, lib/engine/game/g_1870/meta.rb
Adds the $400 Finish variant to 1870, page 24 of rulebook (screenshot below) 
=> [1870] adds $400 finish variant

lib/engine/game/g_18_al/entities.rb, public/fixtures/18AL/hs_pzujrnou_144868.json
Fixes #10023
Similar to #10098
This is slightly different though, because there is only a single train buy allowed, the appropriate step here isn't 'buy_train' but instead is 'single_depot_train_buy'.  Same logic applies though, 'buying_trains' does not pass the "right time" check.
=> [18AL] Fix ability timing for train_discount.

lib/engine/game/g_1822_ca/game.rb
Before, rendering https://18xx.games/game/147861?action=1276 takes nearly a minute. After this change, it's down to about 6 seconds.
In game 147861 at action 1276, it is PGE's route step in OR 9.2. The route they ran in OR 9.1 combined a G-train with their 7-train to visit 19 (!) stops. The G-train is not automatically re-attached to the same train they used last time, so that 19-stop route is invalid for the 7-train. The grain bonus calculation was using `stops` instead of `visited_stops`, leading to a bad loop of trying to compute the revenue-generating stops on an invalid route.
Fixes #10123
=> Fix 1822CA's grain bonus computation

lib/engine/game/g_1822/step/minor_acquisition.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_ca/round/stock.rb, lib/engine/game/g_1822_ca/step/minor_acquisition.rb, lib/engine/game/g_1822_ca/step/special_track.rb
Fixes #10137 
Fixes #10115
Fixes #10148
Fixes #10151
* fix sold out movement at end of SR
* fix minors being able to acquire P10
* fix some track-laying abilities appearing as available during the bonus track action from acquiring a minor
* clear graph when acquiring a minor if the exchange token is moved to available instead of replacing the minor's token on the map; the token may have opened up a city for the acquisition track step, which is unique to 1822CA
=> [1822CA] fix a few small bugs

lib/engine/game/g_18_ga/game.rb, lib/engine/game/g_18_ga/meta.rb
Implements a variant rule from the rulebook where Central of Georgia has one token fewer than usual.
=> [18GA] Adds a reduced token variant from the rules

lib/engine/game/g_1822_ca/game.rb
Fixes #10176
My reading of the rules is that minors are allowed to get the sawmill bonus, it says "all companies" get the bonus if sawmill is `Open` and doesn't state minors don't get that bonus
It does say that only Majors may acquire the P13
Game is alpha so pins not needed. This would result in more money being paid out so unlikely to break games
=> [1822CA] minors also get the sawmill bonus

lib/engine/game/g_1846/entities.rb, spec/assets_spec.rb
I got a wild hair to rewrite the private descriptions for clarity
The physical game has features where the stock descriptions make sense, but in our digital implementation they are less relevant (e.g. "bonus markers")
I also wanted to address common issues, like 
"why doesn't my 2 train run?" 
"oops I have to assign the MPC bonus"
=> [1846] modify private language copy

lib/engine/step/programmer_auction_bid.rb, spec/lib/engine/games/g_18eu_spec.rb, spec/lib/engine/games/g_18mt_spec.rb
Fixes #9615 
Two games allow expanded auto action options during the initial private/minor auction (18EU & 18MT).  In 18EU, in certain cases, a player can be next to "act", have auto actions programmed, actually be unable to pass (not enough money to spend in auction, thus already eliminated OR must select a minor to auction), but the default auto action is Pass.  This triggers an infinite loop of Pass actions which do not change the game state (player cannot Pass), thus freezing the game.
This change returns an empty array if pass is not a valid action, otherwise it returns Pass.  This accommodates the "Pass after max bid reached / buy price impossible" functionality.
=> [18EU][18MT] Change default Pass optional to conditional in programmed auction bid, was causing infinite loops

lib/engine/game/g_1846/step/buy_train.rb
Fixes #10185
In EMR when a corp has enough money for a "weaker" variant but not enough for a pricer variant, the president is allowed to sell shares to afford the pricier one.
In this case, we should only show trains that can be purchased at those times
=> [1846] only show buyable trains in EMR

assets/app/view/game/round/auction.rb, assets/app/view/game/round/stock.rb, lib/engine/game/g_18_ardennes/entities.rb, lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/map.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/major_auction.rb, lib/engine/game/g_18_ardennes/step/minor_auction.rb, lib/engine/game/g_18_ardennes/step/minor_exchange.rb
In 18Ardennes major companies are started by converting minors. There is an auction at the start of each stock round for the rights to start a major, with the players bidding amounts for the rights to start the major, and saying which minor will be converted. The players’ first action(s) in the stock round must be converting the minors into majors.
This is done by first having an auction round to buy (hidden) concession private companies linked to the major corporations. The majors are started in the `BuySellParSharesCompanies` step, in the `process_par` method. A `pledged_minors` hash is added to the game state, to track which minors are going to be used to start the majors.
There are a couple of places where this touches the core rendering code:
1. When placing a bid for the right to …
=> [18Ardennes] Starting major corporations

lib/engine/game/g_18_nl/map.rb
Tweaked the map code of E6 so elements aren't overlapping. 
Before: 
After:
=> [18nl] esthetic update to hex E6

lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
* company groups: 2 from yellow, 2 green, 1 brown
* corporations: SF, RG, and 3 randos; par order determined by "established" year
* 2 can par in yellow
* 2 can par in green
* 1 can par in brown
* available par prices depends on phase
* log available corporations during setup
* 2p: 70% ownership max
#10110
=> [18RoyalGorge] setup corporations and companies, implement phase-based parring

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/map.rb, lib/engine/game/g_18_royal_gorge/meta.rb, lib/engine/game/g_18_royal_gorge/trains.rb
=> [18RoyalGorge] config updates

lib/engine/game/g_1841/game.rb, lib/engine/share_pool.rb
Fixes #10158 
This adds a parameter to SharePool::transfer_shares to handle moving a president certificate between corporations correctly. It is needed for mergers in 1841.
=> 1841: add and use new parameter for SharePool.transfer_shares

lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/single_item_auction.rb
priority deal is usually left-of-last-to-act, but after the auction it goes to the player with the most cash, *without* reordering everyone at the table
#10110
=> [18RoyalGorge] 1861-style auction, priority deal

lib/engine/game/g_1822_pnw/entities.rb
Fixes #10191
Add the 75 and 100 cost mountain hexes to P19
Selecting the P19 at this step shows the "build cost" mountain hex (N13) as buildable
https://gist.github.com/benjaminxscott/bc798e0f0a1393d3e476be453b6b4989
=> [1822PNW] P19 may be used on mountain hexes w/ a cost

lib/engine/game/g_1822_ca/game.rb, spec/game_state_spec.rb
some illegal cases are slipping through the logic in `upgrades_to?`
Fixes #10164
=> [1822CA] hard code legal rotations for big city tiles

lib/engine/game/g_rolling_stock/game.rb
Fixes #10215
Override the default 50% limit
Should also cover RSS since it imports the RS config
=> [rollingstock] market can have more than 5 shares

lib/engine/game/g_21_moon/game.rb
Fixes #10218 
Fixes #10211 
This may require pins.
=> 21Moon: must sell in blocks; fix terminal bonus

lib/engine/game/g_21_moon/game.rb
Fixes #10229
This fix will require pins, though I think every 21Moon game prior to a couple days ago was pinned already.
E-W bonus appears to have changed in late playtesting from $50 per off board to $40 per offboard, dropping the total from $100 to $80.
=> [21Moon] fixes E-W bonus

lib/engine/game/g_1894/game.rb
In the last OR set, track and token steps are skipped. If a company floats just before that, it does place its home station but the graph is not recalculated, so for the engine it doesn't have any route.
Technically this requires pinning but it's unlikely to occur... If pinning is problematic, then we can risk not doing it.
=> [1894] Fix bug stopping company floated in last SR from running trains

assets/app/view/game/part/label.rb, lib/engine/test_tiles.rb
Fixes #8178
Add a new location that labels can use.  This will give the OO in the 1830 tile a better place to land.
Here are the two tiles I could find that were affected by this, and the changes look better in both cases (imo).
**1830**
(old on left, new on right)
**1880**
(old on left, new on right)
(ignore the color change here)
=> [1830][1880] Add new bottom center location to pointy tile labels

lib/engine/game/g_1856/round/stock.rb, public/fixtures/1856/README.md, public/fixtures/1856/hotseat001.json, public/fixtures/1856/hotseat004.json, public/fixtures/1856/move_up_price_sr1.json
Fixes #9940
* Add override of `corporations_to_move_price` to 1856 to also include `sold_out?` corporations.
* Add new test case to ensure stock price moves up
* Modify two existing test cases that were affected by this change (one for final game values, the other was affected by corp operating order).
* I added the pins label, but I don't think I saw any live games that this would affect.  None had any sold out corps after SR1.
=> [1856] Move stock marker up if sold out in SR1

assets/app/view/game/part/small_item.rb, assets/app/view/game/part/upgrade.rb
Found when I was looking around at other tile-related rendering issues.
These 3 locations are repetitions of existing locations, some have incorrect region weights.
*  _unused_: `PP_TOP_LEFT_CORNER` is an x/y duplicate of `PP_UPPER_LEFT_CORNER`, but `UPPER` has the correct region weights (`LEFT_CORNER = [5, 12].freeze`, from the flat tiles before rotated.) 
* `PP_TOP_RIGHT_CORNER` is an exact duplicate of `PP_UPPER_RIGHT_CORNER`.  This one did have a single usage which I fixed.
* `PP_BOTTOM_RIGHT_CORNER` is overwriting the variable of the same name at line 87.  This is an x/y duplicate, but the region_weights point to `BOTTOM_LEFT_CORNER` which is a different area of the tile, so I just deleted so the one at line 87 will be the one that's used.  This should …
=> Remove duplicated pointy location layout locations

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/loans.rb, lib/engine/game/g_18_uruguay/step/take_loan_buy_company.rb, lib/engine/game/g_18_uruguay/step/token.rb
All corperations will take a loan from RTPLA when floating It is then optional for the corperation to take one addtional loan per OR The interest is payed end of OR
It is not possible to repay until Nationalization started
This commit will only add the basic support additional possibilities to take loan and the Nationalization will be handled later
=> [18Uruguay] Adding basic support for loans

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/step/dividend.rb
Adding support for RPTLA dividens which have dependency on how many loans that have been taken
=> [18Uruguay] Adding support for RPTLA dividens

lib/engine/game/g_1858/map.rb
Fixes #10275
Likely requires pins
Put Madrid cities in a group so they can't be reused (same logic as chicago in 46)
Madrid doesn't expand to any more cities so this should cover it
=> [1858] madrid can't be used twice in same route

lib/engine.rb, lib/engine/deep_freeze.rb, lib/engine/game/g_1825/map.rb
While running a full db validation I found some failing 1825 games, and upon further investigation, found there were certain cases where I could validate a game and it would pass, I'd validate another game and it would pass, and then validating the first one again would fail.
It turned out that 1825's hex set up was actually mutating some of the constants, so when the first game was validated again, it didn't have the same starting data.
The constants have a `freeze` call applied to them, but for arrays and hashes that only shallowly freezes references. With 3c80bf7 checked out (includes `deep_freeze` changes but excludes the fix in `append_game_hexes`), the tests for 1825 fail when the code attempts to modify the constants.
It would be useful to apply `deep_freeze` to other constants …
=> Add deep_freeze method, apply to 1825 map constants

lib/engine/game/g_18_uruguay/ability_ship.rb, lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/step/buy_train.rb
[18Uruguay] Adding support for RPTLA to buy ships
Updating logic in Buy Train to support emergency finance
Adding possibility to take loan before buy train
=> [18Uruguay] Adding support for RPTLA to buy ships

lib/engine/game/g_1846/entities.rb
In the prior PR I accidentially made the text too long for the corp cards
https://github.com/tobymao/18xx/pull/10170
I also moved the IC's subsidy to the top, as it seems the most relevant when someone scans the corps
=> [1846] fix text on corp cards

lib/engine/game/base.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_18_royal_gorge/game.rb, public/logos/18_royal_gorge/CF&I.svg, public/logos/18_royal_gorge/VGC.svg
Full implementation coming in step classes later.
Basic idea:
* gold can be shipped from the map to give a route a bonus; the more gold shipped, the more dividends the gold company will pay out
* railroads need to pay the steel company for each track tile laid; that payment turns into the dividends the steel company pays out
Implemented here:
* gold and steel companies only pay out at the end of the OR set, not every OR
* when track is laid on a mine hex, the mine turns into a gold cube
* gold and steel companies in the table top game have no president; here that is approximated by having their share price not be affected when the "president" sells (there never any decisions to be made for the gold and steel companies) 
* now the base `sell_movement` method optionally takes a corporation …
=> [18RoyalGorge] basic setup for gold and steel companies

lib/engine/game/g_18_chesapeake_off_the_rails/meta.rb
This PR links Off the Rails to it's respective wiki page rather than the base game wiki.  From there users can navigate to the base game wiki entry if need be.
It also adds a link to the base 18Chesapeake rules as the current link to the expansion rules does not have a lot of info.  Follows the same pattern used in the 18Mag meta.rb: https://github.com/tobymao/18xx/blob/bc9b3a270f21aab9dd7f8b508da2117061e60116/lib/engine/game/g_18_mag/meta.rb#L21
Fixes #10286
=> [18Chesapeake: Off the Rails] Update links in meta.rb

assets/app/view/game/choose.rb, assets/app/view/game/hex.rb, lib/engine/game/g_18_royal_gorge/step/dividend.rb
#10110
During dividend step, a company may ship a single gold cube from anywhere along their routes, to add $50 to the total dividend. This affects how much the gold company will pay in dividends, and the gold company has a limit on how many gold it will ship in total across the OR set, based on phase.
This changes the `hex` and `choose` views to allow the choice to be made by clicking directly on the hex with the gold, which is much more natural than clicking a button on the side (the default `choose` UI).
Route for $50, option to ship gold:
One gold shipped, total dividend is now $50:
=> [18RoyalGorge] ship gold cube from route for dividend bonus

spec/game_state_spec.rb
* traverse only the subdirectory relevant for the given title (extracted from the string used in the `describe` block via RSPec metadata)
* allows fixtures for different titles to have the same game ID (18ZOO and 1822CA--in an upcoming PR for #10226--both have a fixture `4.json`)
=> refactor how test fixture files are opened in game_state_spec.rb

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_ca_wrs/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/game.rb, public/fixtures/1822CA/README.md
In 1822, M14 in London is always in a city that only has one normal slot. On the Toronto hex and tiles in 1822CA, M13's home city can have 1-4 slots. This is progress on #10226.
A couple other small miscellaneous fixes:
* clean up some dead 1822 code missed in #9519
* add note to fixtures README about 1822CA game 3
* make `MINOR_14_ID` references explicit for PNW and MX
* remove `MINOR_14_ID` from `PENDING_HOME_TOKENERS` for CA WRS as M13 is not present there (probably worth a refactor to give this a more descriptive name at some point, it's weird for the constant named with "14" to refer to the minor company "13" in CA)
=> [1822/CA] fix `upgrade_minor_14_home_hex` to work with Toronto tiles in 1822CA

lib/engine/game/g_steam_over_holland/game.rb, lib/engine/game/g_steam_over_holland/meta.rb
Implements fixed round structure for the game, which runs 5 sets of SR-OR-OR after the initial auction
Still Pre-alpha
Borrows code from 21Moon
=> [SteamOverHolland] - implements fixed round structure

lib/engine/game/g_1822_ca/game.rb
Renaming it to "5" in this way causes a mismatch with the variant that gets created when the train object is initialized. Updating the string in the variant could be done too, but it would be clunky and isn't worth it.
Fixes #10238
=> [1822CA] keep the name "5P" for the special private company 5-train

lib/engine/game/base.rb, lib/engine/game/g_1817/game.rb, lib/engine/game/g_system18/game.rb
Fixes #10255
FWIW @scottredracecar, the 1817 rules have no mention of the word "float". :)
=> rename after_ipo > after_float symbol

lib/engine/game/g_steam_over_holland/game.rb
Implements the price shelves in Steam Over Holland's market, and the price movement rules for it. 
=> [SteamOverHolland] implements price shelves (take 2)

assets/app/view/game/map.rb, assets/app/view/game/map_legend.rb, assets/app/view/game/round/operating.rb, lib/engine/game/base.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/track.rb
#10110
* up to 6 track actions possible
* for each color laid, pick one column of that color from the steel table
* a company can only take cubes from the chosen column 
* a company can use columns that were used by previous companies 
* cubes are refilled at the end of the OR set 
* the cheapest option need not be used; if no explicit choice is made, the cheapest will be used 
* cube/column choices are made by clicking directly on the steel table 
* the currently chosen cube is highlighted in white 
* when a column is committed, its header is higlighted in the column color
* re-uses the "map legend" from 21Moon to render the table, and allows clicking the table to process actions, so that the user can click directly on the cube they want to use
By default, the first, cheapest column is …
=> [18RoyalGorge] implement paying steel company for track tiles

assets/app/view/create_game.rb, assets/app/view/game/game_meta.rb, lib/engine/game/g_1825/meta.rb, lib/engine/game/g_1888/meta.rb, lib/engine/game/g_system18/game.rb, lib/engine/game/g_system18/map_base_customization.rb, lib/engine/game/g_system18/map_neus_customization.rb, lib/engine/game/g_system18/meta.rb
More tweaks to System18
Common code change: CreateGame
-> add display of player count and optional designer for options
Needed because various maps for System18 may have different designers
This won't affect any game option w/o `:players` or `:designer`
Common code change: Game::GameMeta
-> add display of optional designer
CreateGame Before:
CreateGame After:
GameMeta Before:
GameMeta After:
=> System18: more updates; add player count and designer info to CreateGame options

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/goods.rb, lib/engine/game/g_18_uruguay/step/route.rb, lib/engine/game/g_18_uruguay/step/route_rptla.rb
Farms will generate goods once per OR which can be delivered to a near by town of city
The trains can then ship them to a close by port and then RTPLA can ship them to England
This commit covers the delivery both for trains and ships
=> [18Uruguay] Adding support for delivering goods

lib/engine/game/g_21_moon/step/buy_train.rb
Fixes #10302 
Swaps the position of Space Port and Local Base in the drop down menu when buying trains. 
I don't believe this will require pins
=> [21Moon] sets default buying slot to Space Port

lib/engine/corporation.rb
Fixes #10107 
I just added a safe nav operator on the offending line of code. Then I ran the game action on dev and it continued without error and provided the expected results:
* Companies successfully merged
* New merged company had correct Home and Destination token
I am assuming that if object `ability` has no `.owner` method, then `remove_ability()` should continue its work. This didn't negatively impact the test game and all current spec tests passed.
=> [1822PNW] Fix 10107 - add safe navigation operator

lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb, lib/engine/game/g_18_royal_gorge/step/special_choose.rb, lib/engine/game/g_18_royal_gorge/step/track.rb, public/logos/18_royal_gorge/DEBT.svg
#10110
At the Treaty of Boston (second 3-train), the Royal Gorge is upgraded to green, and the Rio Grande corporation becomes indebted to the Santa Fe corporation, and the Santa Fe corporation becomes indebted to the Doc Holliday private company (or bank if that private is not in the game).
Royal Gorge hexes
* a three-hex green tile is laid, and Rio Grande gets tokens on the two cities
* there is also a three-hex brown tile that can upgrade these hexes; following the 18MEX lead, these work by allowing operators to upgrade one of the hexes and then the others are automatically upgraded
Debt
* each indebted party has a debt card with slots for tokens; when paying off debt, they fill one slot with a token; the leftmost open slot shows how many steps there stock price will move left at the …
=> [18RoyalGorge] Treaty of Boston, debt, Royal Gorge hexes

lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb
=> [1822CA] disallow sawmill in Y-cities, fix currency symbol on info page

assets/app/view/game/round/stock.rb, lib/engine/step/buy_sell_par_shares.rb
Fixes #9990 
Split the functionality for checking each individual corp into a new function.  Use that function and check for `empty?` in `must_sell`, but also use the list result when printing out which corps must be sold in the UI.
=> Make must_sell messaging more specific to include the corp names

lib/engine/game/g_18_sj/step/dividend.rb
Fixes #10230 
corrected code. Tested, works as expected now.
Will require pins for any games using the Oscarian Era variant. 
=> [18SJ] Fixes bank pool dividends in Oscarian Era variant

assets/app/view/game/part/debug_region_weights.rb, assets/app/view/game/part/region_coordinates.rb, assets/app/view/game/tile.rb
I found this helpful when debugging, so I thought it might be good to add.  It uses the same `grid` parameter as the region lines for the tiles.  Text needs to be a little small so it can all fit.
=> Add in region weight debugging information when 'grid' URL parameter is used

lib/engine/game/g_1836_jr56/game.rb, spec/lib/engine/games/g_1836jr56_spec.rb
Fixes #9954 
When the auto_actions for the Escrow step are checked, it calls `@game.destination_connected?`, which calls `hexes_connected?(*@destinations[corp.id])`.  When this is called with a corp that has no destinations, it fails for having no arguments instead of the expected 2.
This change mirrors the initialization in 1856, and this causes the capitalization type to be set to `:incremental`, which fails the first condition in `hexes_connected?`, allowing the game to proceed.
https://github.com/tobymao/18xx/blob/f283aaab87172b8c2e3e2177fbb5f534c26a2a0a/lib/engine/game/g_1856/game.rb#L609-L611
=> [1836Jr56] Fix wrong number of arguments into hexes_connected?

assets/app/view/game/part/track_node_path.rb
While working on tiles for System18, I noticed this rendering problem when specifying lanes on a tile:
The bug appeared to be dependent on the ordering of elements.
I took a look at the track rendering code I wrote 3.5 years ago and saw that I was missing dups on lane references.
Fixing it resulted in this:
=> Fix lane rendering bug

lib/engine/game/g_1847_ae/game.rb
- Remove abilities that are only reminders about when a given corporation can be started once the corporation is started.
- It doesn't break games, so pinning isn't needed
=> [1847 AE] Remove unnecessary info ability

lib/engine/game/g_1893/step/merger.rb
Fixes #10311
I believe no games will break due to this fix. The fix now makes it possible to avoid getting stuck. Presumable those that got stuck, did instead do Undo, and then vote No, to get passed this lock. And as they now have worked around this situation nothing will happen.
In case a player owned shares of the corporation to be created by merge, the merge step did not regard this as a voter, so the GUI got stuck. Players had to decline merge to get passed this.
Now merge step considers share owners as well.
Also refactored and added a couple of simple methods to make code more readable.
And updated information to point out that shares in bank pool is regarded as No votes.
Now vote buttons appear for the player that only owned share in …
=> [1893] Fix exclusion of merge voter for share-only owner

assets/app/view/game/round/stock.rb
Seems that wrong value was used here, which caused a crash when trying to use this code.
When trying to use this code (in 1824) it resulted in a crash, with a message about sym and nil.
Location where in the code that was I found this issue, and have replaced @current_entity with entity parameter.
The code now works.
Here is (part of) how the GUI look like in 1824 for initial SR:
My assumption is that no other title use this code, as noone else have encountered this issue it seems.
=> Fix buy with interval buttons

lib/engine/game/g_18_sj/game.rb
Need to handle call to player? to the Adelswärd entity due to GUI issues.
Fixes #9895
To me it looks like 2 player 18SJ does not work at all, so do not think this will affect any game. In case it do, I suppose the game can be pinned or archived. (Quite rare that people play at this player count.)
Adelswärd is a bot that has some automatic actions, and some player controlled.
So it has to mimic a player in some ways. Therefor a Wrapper has been created in the game. This wrapper had only a name method, but it seems the GUI now required a player? method, so this has been added.
No screen shot, but when testing the fix, the critical moment (that is, end of SR2) was passed without any problems.
Adding this player? …
=> [18SJ] Fix issue with Adelswärd selection of corporation

assets/app/view/game/alternate_corporations.rb
Fixes #4913 
* Change borders to use font color instead of black
* Adjust highlight color to adjust based on background instead of just gray (more contrast for both light and dark theme)
| ![image](https://github.com/tobymao/18xx/assets/5263073/4475df74-2167-47db-a262-3a072d3e42e7) | ![image](https://github.com/tobymao/18xx/assets/5263073/0a9cd306-4d3c-465e-94a5-7682798bcdc8) |
| ![image](https://github.com/tobymao/18xx/assets/5263073/5e186442-54ce-49b9-911a-23dfafe72d81) | ![image](https://github.com/tobymao/18xx/assets/5263073/100c1e24-8f09-4b49-bf3b-82634277698e) |
Just for fun
=> [1873] Make colors controlled by settings for mine displays

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/goods.rb, lib/engine/game/g_18_uruguay/nationalization.rb
[18Uruguay] Added some more logic to nationalization
- Decrease stock value on nationalization added
- Remove surplus goods from map when nationalized
- The interest is 0 after nationalization
- Add final payout from RPTLA
=> [18Uruguay] Added some more logic to nationalization

assets/app/view/game/part/location_name.rb, assets/app/view/game/part/multi_revenue.rb, assets/app/view/game/part/revenue.rb, lib/engine/game/g_18_uruguay/map.rb, lib/engine/part/revenue_center.rb, lib/engine/tile.rb
In 18 Uruguay the offboard revenue box gets to big and hiding the rails.
Inspired by https://www.18xx-maker.com/elements/ "Offboard Revenues"
I suggest here to add an extra parameter "rows" to the offboard tile which will allow the revenue to be splitted over multiple rows.
In addition to split the row we also need to move the tile name so it does not collide with the revenue when multiple rows is configured
Example from the 18 Uruguay map
`            ['G1'] => 'offboard=revenue:yellow_30|green_30|brown_40|gray_60,format:+%d,visit_cost:0,route:optional'\
',groups:England,rows:2;path=a:3,b:_0;path=a:4,b:_0',
`
Before
After
=> Suggestion for adding support for multirow revenue

lib/engine/game/g_1824/game.rb, lib/engine/game/g_1824/trains.rb
This is the trains parts extract from a previous abandoned PR (#8640), slightly rewritten after review comments.
1824 is in pre-alpha and is not playable so it should not affect any games.
18xx.games do not handle the g-trains of 1824 correctly, so events are used to handle these trains, and the peculiarities connected to them.
Here is how the train table looks like when first 4 train, and first 3g train, has been bought:
None
=> [1824] Corrections for train handling

assets/app/view/game/map.rb
Stop setting `@cols` and `@rows` to sparse arrays. This allows for a row/col to be unused, which is especially useful when incrementally defining the map for a new game.
=> [core rendering] fix handling gaps in map axes

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/dividend.rb, lib/engine/game/g_18_royal_gorge/step/special_track.rb
* Y5 Territorial Prison - terrain discounts (just config in `entities.rb`)
* Y6 Local Jeweler - earns $5 every time gold is shipped; transfers to player's cash at beginning of SR
* G2 13LB Gold Nugget - one time, may ship gold for $130 instead of $50
* B3 Steel Depot - free steel, up to 2x per OR and 5x total (just config in `entities.rb`)
#10110
=> [18RoyalGorge] implement private companies Y5, Y6, G2, B3

.github/workflows/ruby.yml, .rubocop.yml, Dockerfile, Gemfile.lock, assets/app/view/game/par_chart.rb, assets/app/view/game/triangular_grid.rb, docker-compose.dev.yml, docker-compose.prod.yml, queue.rb
* a few gems, as well as configuration for a couple rubocop cops, needed updating for Ruby 3.2
* Opal 1.6+ gives longer in JS  stacktraces 🎉 
* Opal 1.7+ allows use of `Set` in Ruby 🎉 
Fixes #9608
=> Opal 1.8, Ruby 3.2

assets/app/app.rb, assets/app/game_class_loader.rb, assets/app/game_manager.rb, assets/app/lib/connection.rb, assets/app/lib/params.rb, assets/app/lib/settings.rb, assets/app/lib/storage.rb, assets/app/view/about.rb, assets/app/view/chat.rb, assets/app/view/confirm.rb, assets/app/view/create_game.rb, assets/app/view/flash.rb, assets/app/view/game/actionable.rb, assets/app/view/game/auto.rb, assets/app/view/game/game_data.rb, assets/app/view/game/game_log.rb, assets/app/view/game/tile_manifest.rb, assets/app/view/game_card.rb, assets/app/view/game_card_page.rb, assets/app/view/game_page.rb, assets/app/view/home.rb, assets/app/view/user.rb, assets/deps.rb, lib/engine/auto_router.rb, lib/engine/game/base.rb
suppresses this warning from Opal:
```
warning: Backtick operator usage interpreted as intent to embed JavaScript; this
code will break in Opal 2.0; add a magic comment: `# backtick_javascript: true`
-- (file)
```
Still see one instance of the error when running `rake spec_parallel` but it doesn't include a filename. We can worry about that one when Opal 2.0 is available
Fixes #10381
=> add `backtick_javascript` comments

docker-compose.yml
I don't know why this needs to change now, but lowercase z is defined as the "shared volume" flag in https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options and this fixes my issues building on a fresh reinstall of Fedora 39.  I was coming from Fedora 35 which is really far back, so something must have changed in the meantime.
I did a local test, and a codespace test, which should cover ubunutu/docker.  I didn't see any issues there.
=> Fix shared mount volume designation for podman

assets/app/app.rb, assets/app/game_manager.rb
When the `/fixture` path is used in production, the fixture does not load, but due to the `safe_get` implementation it is retried, triggering a loop:
This also happens in development if path in the URL does not correspond to an actual fixture file.
=> fix looping error for `/fixture` in prod or when fixture doesn't exist

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/special_track.rb, lib/engine/game/g_18_royal_gorge/trains.rb
* Y1 St Cloud Hotel - bonus revenue in one hex, then a different hex in brown phase
* B2 Sulphur Springs - can upgrade Sulphur Springs hex from a town to a city; only pays revenue in brown phase if Sulphur Springs hex has track built to it
#10110
=> [18RoyalGorge] update phase info, implement two more private companies

api.rb, assets/app/app.rb, assets/app/view/game/actionable.rb, assets/app/view/game_page.rb, assets/deps.rb, lib/engine.rb, lib/engine/auto_router.rb, lib/engine/game/base.rb, lib/engine/game/g_18_dixie/step/conversion.rb, lib/engine/game/g_18_neb/step/buy_sell_par_shares.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/graph.rb, lib/engine/logger.rb, queue.rb, scripts/scripts_helper.rb, spec/spec_helper.rb
By default, log level is `INFO` in production and `DEBUG` in development.
In the browser, the URL param `l` can be used to set the level. On the server, the environment variable `ENGINE_LOG_LEVEL` can be used. The level is set to an integer; 0/1/2/3/4 for `DEBUG`/`INFO`/`WARN`/`ERROR`/`FATAL`.
When the URL param or environment variable are not set, the log level will default to `INFO` in production and `DEBUG` in development.
Added logging:
* prealpha games - replace `puts` with `LOGGER.debug`
* auto_router - replace `puts` with `LOGGER.info`
* actionable view - log the rescued error with `LOGGER.error`
* add `LOGGER.debug` for some things I've made temporary local edits for countless times:
* show each action ID as it is processed
* start and end of:
* processing game actions
* rendering …
=> [core] add global LOGGER

lib/engine/game/g_1832/game.rb, lib/engine/game/g_1832/map.rb, lib/engine/game/g_1832/market.rb, lib/engine/game/g_1832/meta.rb, lib/engine/game/g_1832/phases.rb, lib/engine/game/g_1832/round/merger.rb, lib/engine/game/g_1832/step/track.rb, lib/engine/game/g_1832/trains.rb
Works on #10122 
@philcampeau did a ton of work here already to get the basic game setup done. This PR mostly just rearranges the files a little bit so that trains, phases, market are in their own files. There was also an issue in laying track that this fixes (I did not examine whether the behavior is truly correct, just that it was breaking tile laying and now it isn't).
***Screenshots**
N/A
N/A
=> 1832 initial dev work by jemiahlee

lib/engine/ability/README.md
No new information added. I only wanted to organize and standardize the information on this page. 
Previously, some paragraphs had linebreaks at around 80 characters, while others ran well over 100.
Now, linebreaks are added more uniformly.
Previously, some lines ended in periods while others didn't.
Now, all sentences end in a period. I know that this isn't always standard in code comments, but I think for a readme document it makes more sense. 
Previously, it appeared that many attributes were just tacked on to the end of the list as they were added.
Now, all entries within the document are alphabetized, which makes for easier visual searching.
=> Organizes the Ability README page

lib/engine/game/g_1850/entities.rb
Fixes #10033
Fixes #10334 
Western Land Grant was requiring all special lays be contiguous. This isn't required.
=> [1850] Corrects Western Land Grant to not require connected lays

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/dividend.rb
After last gold is shipped from a hex, may place a ghost town marker (from a starting supply of 4) there for +$10 to the owning corporation's routes there.
#10110
=> [18RoyalGorge] implement private Y2 Ghost Town Tours

lib/engine/game/g_18_india/game.rb, lib/engine/game/g_18_india/step/track.rb
Implement upgrade chart differences for Yellow Towns and Yellow Cities to Green Tiles
- n/a Add the `pins` or `archive_alpha_games` label if this change will break existing games
- Yellow towns may upgrade to Single Slot green cities.
- Needed to override legal_tile_rotation in Step:Track / Tracker
- Yellow cites upgrades to Double Slot green cities
=> [18 India] Yellow Town / City Upgrades to Green City Tile

lib/engine/game/g_18_esp/game.rb
Fixes #10404
Currently loan interest rounds down to nearest whole integer, but according to the rules it should round **up** to the nearest whole integer. 
Changed loan calculation from `interest = loan_amount * 0.5` to `interest = (loan_amount * 0.5).ceil`
This change will break any games where interest calculation was wrong, applied `archive_alpha_games` label.
=> [18ESP] Fixes interest calculation to round up.

lib/engine/game/g_1858/step/home_token.rb
An extra slot was being created when Madrid was upgrade to green. The sequence of events that triggered this was:
1. M&A is used to form AVT in stock round 3.
2. AVT places its home token in M&A's slot in the NE Madrid city.
3. In OR 3.1 RP operates before AVT.
4. RP upgrades Madrid to green.
At this point M&A hasn't yet closed and the code for moving tokens and reservations sees both AVT's token and M&A's reservation in the NE Madrid city, and helpfully creates a second slot to accommodate both of these.
The fix is to remove M&A's reservation after AVT places its home token.
Fixes #10442.
I would hope that this doesn't break any existing games, but it's possible that there has been someone who has taken advantage of this extra slot, so I've added the pins label to this pull request. …
=> [1858] Delete private company reservation when token is placed

lib/engine/game/g_1841/game.rb
Fixes #10389 
This will very likely require pins (there are only 24 active games at the moment)
Rewrite best_stock_value method to use operating order sort
=> 1841: Fix tiebreaker for Tuscan Merge decider

lib/engine/game/g_system18/game.rb
maps now _always_ override constants, even ones that should default OK,  in order to allow validate script to work correctly
=> System18: game validation fix

lib/engine/game/g_1880/step/buy_train.rb
Fixes #10455
- [Maybe?] Add the `pins` or `archive_alpha_games` label if this change will break existing games
Disables flag "entity is able to pass if unable to buy train"
This flag appears to be included by default in order to cover cases like nationals where they don't need to own a train
Reading 1880 rules, corps must always own a train at the end of its turn, and they will always have space for a train when purchasing one when otherwise trainless
=> [1880] don't autoskip when corp must buy train

lib/engine/game/g_1848/map.rb
Fixes #10468 
Game was tracing connected K cities through the blue tile 241. I made the paths on that tile as well as the offboards along the top of the map all terminal:1.
=> [1848] Makes terminal paths always terminal

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/route.rb, lib/engine/game/g_18_royal_gorge/trains.rb
https://github.com/tobymao/18xx/issues/10110
* B5 Track Engineer increase one train's length by one each OR
* Y3 Coal Creek Mines and G6 Coal Depot get coal cubes in different ways, but they are spent in the same way: the owning corporation can spend up to 2 coal cubes to increase one train's length by one per cube
* no train can be lengthened by more than one of these companies per OR; the `choose_state` logic in the route step ensures only one of these companies will be chosen at a time
* Depends on #10435 and #10436, but while in prealpha it doesn't matter if this one is merged first.
=> [18RoyalGorge] implement train-lengthening privates (Y3, G6, B5)

lib/engine/train.rb
This will be used in 18RoyalGorge with private companies that can increase a train's number. It could also replace (and simplify) the current implementation of other train attachments, such as the pullman cars in 1822.
Split off from #10428 for #10110
=> [core] allow trains to have variants dynamically added

lib/engine/ability/base.rb
This will be used in 18RoyalGorge for an ability that involves earning and spending cubes; more cubes can still be earned after the corporation hits zero available.
Split off from #10428 for #10110
=> [core] abilities can increase in count, and stay open when count hits 0

assets/app/view/game/map_legend.rb, lib/engine/game/base.rb, lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/dividend.rb, lib/engine/game/g_21_moon/game.rb
#10110 
* when a gold is shipped, it occupies a spot in the market
* gold may only be shipped to spaces with colors up to the current phase
* the smallest uncovered number in the gold market is the amount of total dividends that the gold company will pay
* add capability to render multiple "map legends", so that the gold and steel tables can be rendered separately
The shipped gold cube is placed in the next spot on the gold market:
=> [18RoyalGorge] show table for gold market; [core] allow multiple "map legends"

lib/engine/game/base.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb, lib/engine/share_pool.rb
The gold and steel corporations don't really have presidencies and all their shares can be in the market.
#10110
=> [18RoyalGorge, core] allow president sales to market for only specified corporations

assets/app/view/game/button/buy_share.rb, assets/app/view/game/buy_sell_shares.rb, lib/engine/action/buy_shares.rb, lib/engine/game/g_18_new_england/step/buy_sell_par_shares.rb, lib/engine/game/g_18_va/step/buy_sell_par_shares.rb, lib/engine/game/g_21_moon/step/buy_sell_par_shares.rb, lib/engine/game/g_21_moon/step/corporate_buy_sell_shares.rb, lib/engine/game/g_rolling_stock/step/buy_sell_shares_bid_companies.rb, lib/engine/share_pool.rb, lib/engine/step/buy_sell_par_shares.rb, lib/engine/step/share_buying.rb
18RoyalGorge's share-buying step will implement `company_discounted_bundles`, which will be used for multiple private companies; see #10449 for a screenshot.
=> [core] Allow companies to provide a discount when buying shares

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb, lib/engine/game/g_18_royal_gorge/trains.rb
#10110 
* implement private G5 Metal Investor - buy gold/steel shares at a discount once per SR
* implement private B4 Gold Miner - virtual 20% share of gold company
* implement private B6 US Mint Worker - close to buy 1-2 gold shares for half price
Separate buy button to use the private company and get the one-step discount:
* depends on core changes in #10448, but while in prealpha the order of merging these PRs doesn't matter
=> [18RoyalGorge] gold/steel - implement privates G5, B4, B6

lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/map.rb, lib/engine/game/g_18_ardennes/market.rb, lib/engine/game/g_18_ardennes/step/decline_tokens.rb, lib/engine/game/g_18_ardennes/step/track.rb, lib/engine/game/g_18_ardennes/trains.rb
Various fixes and small new features for the in-progress 18Ardennes implementation:
- Major companies can lay two yellow tiles.
- Minor companies cannot lay brown tiles.
- If you go above 60% ownership of a major (by exchanging minors) you don't have to sell back down.
- Show unsold shares as 'Treasury' instead of 'IPO'.
- Share price of fully sold companies doesn't increase at the end of a stock round.
- Custom rules for rusting 2-trains.
- Fix a bug from the last batch of code, where it was possible for a minor to remain open after it had been exchanged for a share in a major.
The l2-train rusting is the only bit that involves anything unusual. The rule is that when the first 4-train is bought, some 2-trains rust immediately, but others don't.
- 2-trains belonging to companies that have …
=> [18Ardennes] Various small changes and fixes

lib/engine/game/g_18_ny/map.rb, lib/engine/game/g_18_ny_1e/map.rb
Fixes #10223
Terminal offboard track didn't have the terminal:1 tag on it, so the game was reading them as pass-throughs for this purpose. 
Tested on my end, game works as expected now. Please let me know if I'm neglecting anything with this fix.
=> [18NY] makes terminal offboards actually terminal

lib/engine/game/g_1817/game.rb, lib/engine/game/g_1817/step/buy_sell_par_shares.rb
**How to Reproduce the Bug?**
If a 5 or 10 share corp is started using the Train Station private, instead of getting an additional station token, the game simply doesn't charge the corp for the second token. In the image below, we can see the Train Station was used to form the corp. The corp acquires the "extra" token, Train Station closes, and then the corp starts with 5 shares and $60, and isn't forced to buy a third station. 
The reason this happens is because the code that checks for the amount of tokens needed for the corp to start does this by checking if the corporation owns any companies with the id 'TS', but the current code closes Train Station as soon as it's assigned to the corp and the token is granted. 
https://github.com/tobymao/18xx/blob/a351c8169ad84ac9b5fec5aebb8d662971b8 …
=> [1817] fixes edge case bug with Train Station private

assets/app/mail/turn.rb
Remove final backtick warning in test output, adds on to #10382
=> Removing last backtick warning

assets/app/mail/turn.rb
Add comments explaining that suppressing the backtick warning will break the email notifications, hopefully prevent someone else from doing the same thing
=> [Core] Add comment about suppressing backtick warning

assets/app/view/welcome.rb
Add specific links to notif options so ppl don't have to scroll the whole page
Update the links to the wiki
=> update links to webhook notif instructions on home page

lib/engine/game/g_21_moon/entities.rb, lib/engine/game/g_21_moon/game.rb
Fixes #10547
Updates the tile for Terminal that was changed in https://github.com/tobymao/18xx/pull/10527
Likely needs pins since games could have laid the incorrect tile before
=> [21Moon] fix terminal tile placement

lib/engine/game/g_21_moon/entities.rb
The BGG-hosted rules indicate Terminal revenue is 15, Scott confirmed
https://boardgamegeek.com/filepage/263361/21moon-rules
Definitely needs pins
=> [21Moon] Terminal private revenue s.b. 15 space bucks

lib/engine/game/g_21_moon/entities.rb
Temporarily reverting so 21Moon breaking changes can all come in together.
=> Revert "[21Moon] Terminal private revenue s.b. 15 space bucks"

assets/app/view/game/dividend.rb, assets/app/view/game/pass_button.rb, assets/app/view/game/route_selector.rb, assets/app/view/game_page.rb
I've added a few hotkeys that will allow players to quickly speed through the final ORs of a game
[1] - handles all passing (Skip track/skip token/skip trains/skip companies)
[2] - clears all saved runs
[3] - hits the auto route button
[Enter] - Selects 'Pay Out' option, and also 'Submit' for the run
I find this really helpful with everyone agrees the game is over but still want to see a final score. One player enables master mode, goes through one OR where they maximize each route (if desired) and then it's just 1 and Enter for the rest of the game
=> Adds hotkeys for speeding up operations, especially end of game runs.

lib/engine/game/g_18_rhl/map.rb
Remove duplicated E8 definition from the map.rb which resulted in two visible layers in some moments of the Operating Round:
The correct E8 definition is several lines further in the file.
=> [18Rhl] Remove duplicated E8 definition from map.rb

lib/engine/game/g_18_neb/game.rb
Fixes #10576
Rules don't indicate there's a discount
- [no, since alpha] Add the `pins` or `archive_alpha_games` label if this change will break existing games
=> [18Neb] t'aint no train discounts

assets/app/view/game/buy_sell_shares.rb, lib/engine/game/base.rb, lib/engine/game/g_18_ardennes/entities.rb
Bugs tobymao#10537 and tobymao#10563 were reports of spurious exchange buttons appearing in stock rounds, in 1871 and 1858.
These buttons were appearing when the active player owned a private company that could be exchanged for a share in a corporation. As well as the button to exchange the private for a share, one or more extra buttons were appearing, offering to exchange corporations for a share.
This was caused by commit bc6fa7d, which added `@game.corporations` to the entities that are checked for exchange abilities. This was needed for 18Ardennes, which has corporations with exchange abilities.
Neither 1858 or 1871 have corporations with exchange abilities, but `Corporation.all_abilities` will also pick up any abilities owned by the corporation's president which have an …
=> Prevent spurious exchange buttons appearing in stock round

lib/engine/game/g_18_uruguay/step/dividend.rb
[18Uruguay] Only auto withhold when nationalized
Corrected a bug and only withhold when nationalized
=> [18Uruguay] Only auto withhold when nationalized

lib/engine/game/g_1822_pnw/map.rb
=> [1822PNW] Fix typo in tile name

lib/engine/game/g_18_ardennes/trains.rb
The 4D trains in 18Ardennes can run a route of any length, earning revenue for four cities and doubling this revenue and any bonuses earned. They can share track with other trains.
This pull request has the bits of code needed to implement 4D trains correctly:
- They can only be bought be 10-share public companies, and these can only each own a single 4D train.
- Sharing track with normal trains.
- Calculating the ferry and Trans-Europa Express bonuses.
- ~~Add the `pins` or `archive_alpha_games` label if this change will break existing games~~
=> [18Ardennes] 4D trains

lib/engine/game/g_1848/depot.rb, lib/engine/game/g_1848/game.rb, public/fixtures/1848/101.json, spec/game_state_spec.rb
Fixes #10603
- [yes] Add the `pins` or `archive_alpha_games` label if this change will break existing games
Export the next permanent rather than the next upcoming train. Typically happens if 2nd corp is thrown into receivership early
Adds test case
=> [1848] fix train export on 2nd/5th receivership

DEVELOPMENT.md
~~Added details about how to reset passwords in the local dev environment to the section on importing games, since that's most likely when you're going to want that information.~~
Apparently I misunderstood something about the import script, and this is already done automatically. I modified the DEVELOPMENT.rb file instead to just explicitly say that the passwords are scrubbed and reset to "password".
=> Adds instructions for scrubbing passwords to import_game info.

lib/engine/game/g_18_nl/entities.rb
Directly fixes two small typos in 18NL
"De Vuluwe" -> "De Veluwe"
"Hollandsche Ijzeren" -> "Hollandsche IJzeren"
(in Dutch 'IJ' is a single character and thus must be capitalised this way)
=> 18NL Typo fixes

lib/engine/game/g_21_moon/game.rb, lib/engine/game/g_21_moon/step/special_token.rb, lib/engine/game/g_21_moon/step/special_track.rb
Fixes #10552
Adds a SpecialToken step after SpecialTrack (the latter is necessary to allow laying two tiles after the Terminal)
There was a bunch of custom logic in SpecialTrack that is now covered by SpecialToken, but I kept the logic to close the private and regenerate the graph after the player has finished choosing.
This also fixes a related (unticketed) bug where if the corp had no tokens left, the private would not close. I double-checked in the rules that laying the Terminal is what closes the corp, not the choice to token or not
SpecialToken step firing (same as C&OC)
Laying a token
Choosing not to lay a token
=> [21Moon] allow Terminal to optionally place token

lib/engine/game/g_steam_over_holland/game.rb, lib/engine/game/g_steam_over_holland/step/token.rb
Odd rule but confirmed by the designer: https://boardgamegeek.com/thread/1034408/article/13330784#13330784
=> [Steam Over Holland] cannot lay a token in corps first operating turn

lib/engine/game/g_18_hiawatha/meta.rb
Fixed title to include a space.
=> [18 Hiawatha] apparently this title has a space in its name

lib/engine/game/g_18_hiawatha/game.rb
Fixes #10660
Removed the "safe par" notation for this game, since selling and shortselling is allowed on unoperated corps, so the information is irrelevant.
=> [18 Hiawatha] change the description of a couple of market spaces

lib/engine/game/g_18_hiawatha/step/buy_sell_par_shares.rb
Fixes #10664
Corrected the `def use_on_assign_abilities(company)` method.
=> [18 Hiawatha] fixes Union Station

assets/app/view/game/game_info.rb
Just a minor tweak, adding a space after the Event name.
Here's what it used to look like:
and here's how it looks after the change:
=> [info page] added a space between the event name and '(on Xth train)'

assets/app/view/game/game_log.rb, routes/game.rb
Fixes #10674
Implements common slack/discord style keywords for pinging everybody in a game
Also removes yourself from that list, and removes the ability to ping yourself in general
I used the community discord for testing:
https://discord.com/channels/692794539169284186/747222914419523644
I had two users locally, each w/ the same webhook setup pointing to my Discord userID 
Before I added the "don't ping yourself" check under the `@all` handling, it pinged both users
=> support "ping all" keywords and remove self-pings

lib/engine/game/g_1822/meta.rb
Fixes #10560
As pointed out in the report, saying that the privates are sorted into the blue, dark grey, and gold piles doesn't really mean anything for online play, while explaining what unites the cards in each pile does.
=> [1822] improves description of 1822+ variant

assets/app/view/game/part/track_node_path.rb, lib/engine/part/path.rb
Fix rendering of 4 lanes going into specific exits on hex edge and add possibility to render 5.
This is needed to implement 22Mars
Formula to decode lane spec is:
```ruby
[x_lane.to_i, ((x_lane.to_f - x_lane.to_i) * 10).to_i]
```
which is transpiled to this javascript
```js
[x_lane.$to_i(), $rb_times($rb_minus(x_lane.$to_f(), x_lane.$to_i()), 10).$to_i()]
```
so when lane is odd, there are rounding issues in code generated by Opal:
1. `x_lane.to_d` = `4.3`
2. `x_lane.to_i` = `4`
3. `(x_lane.to_f - x_lane.to_i) * 10` = `2.9999999999999982``
4. `((x_lane.to_f - x_lane.to_i) * 10).to_i` = `2` (while it should be 3)
This only starts happening when trying to use 4 lanes on a hex edge.
=> [Core] Fix lane connections with 4 lanes per hex edge

assets/app/view/game/part/assignments.rb, lib/engine/assignable.rb, lib/engine/game/base.rb, lib/engine/game/g_18_uruguay/farm.rb, lib/engine/game/g_18_uruguay/game.rb, public/icons/stack_background.svg
In 18 Uruguay there is a need to assigne multiple assignments to one tile. 
In current framework the tile quickly gets overloaded with the assignments
This is a proposal for a possibility to stack assignments
In this proposal you can tag an assignment with stackable like this
`          target.assign!(good, Engine::Assignable::STACKABLE)
`
When drawing the framework will then stack all stackable assignments and add a counter if the number of elements are 2 or larger
=> Adding support for stackable assignments

lib/engine/game/g_1849/entities.rb, lib/engine/game/g_1849/game.rb
1. After playing a lot of 1822* here I found myself looking for the random corporation order in the Timeline section.
2. Also I played with people new to 1849 and they found it hard to remember where AFG can start so I added a description to the company.
1
2
<details><summary>Rejected</summary>
<p>
3. I also added markers to the map hexes where AFG can start (small red circles with AFG letters).
</p>
</details>
=> 1849 usability improvements (Timeline, AFG start spaces)

lib/engine/game/g_18_royal_gorge/game.rb
DEBT should start at $60, not $35.
In theory this could break games, but so far I don't see any that have gone far enough for DEBT to actually be a factor.
=> [18RoyalGorge] fix starting DEBT value

lib/engine/game/g_1846/entities.rb
Very pedantic, but the description for the Ohio & Indiana private company in 1846 specified that F15 was a reserved tile, which is not on the 1846 board. It should be F16.
I don't think it will break existing games since it's just a description change, but I'm not entirely clear on that...
=> [1846] Correct Ohio & Indiana description in 1846

lib/engine/game/g_18_hiawatha/game.rb, lib/engine/game/g_18_hiawatha/step/loan.rb
Fixes #10687 
Fixes #10689
First commit:
forgot to add the changed signal_end_game to EVENTS_TEXT
Second commit:
improved the text from the first commit.
Third commit:
The far left market space wasn't coded as Liquidation as it should be. This will likely break some games. since we're in alpha, they should just be archived.
=> [18 Hiawatha] signal_end_game text and fixes Liquidation section of the market

lib/engine/game/base.rb
This is a single line change: when an exception is caught processing an action in server mode, print the exception and the backtrace to the server log at debug priority.
This is should make it easier to identify where a error has occurred.
=> [Core] Log backtrace on caught exception

lib/engine/game/g_18_royal_gorge/game.rb, public/fixtures/18RoyalGorge/post_boston.json
Fixes #10695
`remove_when_used_up` is used instead of `closed_when_used_up` in the context of a `choose_ability`
`choose_ability` isn't documented in the Abilities readme, so I assume it's a newer feature that seems used for adding boutique abilities that aren't tied to a private
https://github.com/tobymao/18xx/blob/master/lib/engine/ability/README.md
I don't think this needs pins, as games were stuck on that step anyway (also it's alpha)
adds fixture
fwiw I also tested that the doc holiday debt ability worked as expected, and it seemed fine
https://gist.github.com/benjaminxscott/549b21902bf4da3da52707a4596ca0de
=> [18RG] fix ability keyword

lib/engine/game/g_18_sj/game.rb, lib/engine/game/g_18_sj/step/requisition.rb, public/fixtures/18SJ/bot_chooses_fullcap.json
Fixes #10709
also adds test case
I don't believe this requires pins, as it enables previously broken actions
Obtain a `shares` object based on the corp's IPO shares, no matter who owns them
I believe the issue was that the [fullcap conversion logic](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_sj/game.rb#L758) moves IPO shares to the bank, so when we attempt to obtain those shares later from the corp's context, the corp doesn't actually own any shares so it returns nil which blows up the [share transfer logic](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_sj/game.rb#L851)
Also changed the requisite step to pass an ID instead of a bare name, since we …
=> [18SJ] fix bot corp choice after fullcap hits

lib/engine/game/g_1822_ca/entities.rb
Fixes #10734
I changed the text to match the description of the other privates of this type. Added city name and hex coordinates to the description.
=> [1822CA] adds the city name and hex coordinates to P18 description

lib/engine/game/g_18_ardennes/entities.rb, lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/round/auction.rb, lib/engine/game/g_18_ardennes/round/stock.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/decline_trains.rb, lib/engine/game/g_18_ardennes/step/exchange.rb
An assortment of minor changes to the information shown to players in 18Ardennes. No game logic is changed in this pull request.
- Show the company cards for a player's minor companies during their stock round turns. You can't buy or sell shares in the minor companies, but it useful to be able to see their stock prices and assets without having to switch to the 'entities' tab, in case you are considering exchanging one for a public company share.
- In a stock round, sort public company cards by stock market price.
- Add a description on the company card for the GL minor company.
- Add descriptions to the concession company cards shown when auctioning the rights to start public companies.
- Use the acronym 'PCA' for public company auction rounds on the operating history shown on the game …
=> [18Ardennes] Display improvements

lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/decline_forts.rb, lib/engine/game/g_18_ardennes/step/decline_trains.rb, lib/engine/game/g_18_ardennes/step/minor_auction.rb, lib/engine/game/g_18_ardennes/trains.rb
Fixes for a few issues identified in pre-alpha testing.
- Fix a syntax error (missing parameter) in `G18Ardennes::Step::DeclineTrains` that wasn't being picked up when run in hotseat mode, but was causing the game to break when run in server mode.
- The decline forts steps wasn't getting marked as active, and so wasn't running at the right time.
- The wrong player was getting asked to carry out the decline forts step.
- Allow the GL minor company to be sold at the start of a stock round, as well as public company shares, before a player is obliged to start a new public company.
- Set the priority deal correctly at the end of the initial minor company auction round. Priority goes to the player to the left of the person who bought the last minor.
- Use an auto-action to pass a player's …
=> [18Ardennes] Bug fixes

assets/app/view/game/buy_sell_shares.rb, lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/exchange.rb, lib/engine/game/g_18_ardennes/step/exchange_approval.rb, lib/engine/game/g_18_ardennes/step/minor_exchange.rb
18Ardennes allows minor companies to be exchanged for shares in public companies (majors). If there are shares of the public company both in the bank pool and the company's treasury, then there's a sequence that must be followed: first the minor company's owner may attempt to exchange the minor for a treasury share of the public company. If this is refused by the public company's president, then the minor may be exchanged for a pool share. This is very similar to the process for exchanging private railway companies for public company shares in 1858, so I have copied the approval/denial mechanism from that game.
This pull request also implements the rules for what happens when a minor is exchanged for a pool share – all its assets are discarded.
This touches the core code in one place: in …
=> [18Ardennes] Exchange approvals

assets/app/view/game/company.rb, assets/app/view/game/round/auction.rb, lib/engine/action/select_multiple_companies.rb, lib/engine/game/g_18_india/game.rb, lib/engine/game/g_18_india/step/certificate_selection.rb
- [n/a] Add the `pins` or `archive_alpha_games` label if this change will break existing games
- Created a `SelectMultipleCompanies` action that stores an array of companies as part of a single action.
- Modified `View::Company` and `View::Round::Auction` behavior to support selection of multiple companies.
- Refactor Certificate Selection step to use multiple selection action. 
The old version of the certificate selection step was very "clicky", often needing 20 - 30 clicks to complete and felt "clunky" as a user experience.  This refactor allows the completion of the step with 1/3 of the clicks, and without hiding the screen after individual certificate selection.
- Uses the `click` -> `select_company` event on company card as the "button" to select and unselect the company.
=> [18 India] [Core] Create Multiple Selection Action and Refactor Certificate Selection

lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb, lib/engine/game/g_18_royal_gorge/step/route.rb, lib/engine/game/g_18_royal_gorge/step/single_item_auction.rb, lib/engine/game/g_18_royal_gorge/step/special_choose.rb
* fix interaction with coal depot and mines when depot is out of cubes; fixes https://github.com/tobymao/18xx/issues/10736
* fix run routes step with 0 coal cubes left; fixes https://github.com/tobymao/18xx/issues/10735
* fix metal investor passing nil to share bundle; fixes https://github.com/tobymao/18xx/issues/10733
* fix auction - close company when all pass on it; rmoves some copy-pasted code from 1861, where  the company becomes cheaper instead of being removed from the game; fixes https://github.com/tobymao/18xx/issues/10749
* close Doc Holliday when his DEBT is paid off; fixes https://github.com/tobymao/18xx/issues/10750
=> 18RoyalGorge fixes

lib/engine/game/g_1817/game.rb
Fixes #10746
Fixes an issue where the 1817 export logic would bail if there were no upcoming trains 
Only relevant in cases where games inherit from 1817 code since 1817 has infinite trains, but I wanted to fix it at the source rather than expecting those games to handle this case
Specifically 18Hiawatha
=> [1817] fix check for exporting trains (relevant when other games inherit)

lib/engine/game/g_18_mo/entities.rb
Fixes #10782
Changes `when` for train_discount ability from `buying_train` to `buy_train`, as per fix in #10098
=> [1852] fix train discount ability timing

lib/engine/game/g_18_uruguay/step/destination_bonus.rb
Do not check for destination bonus for closed companies
=> [18Uruguay] Do not check for destination bonus for closed companies

lib/engine/game/g_18_uruguay/corporations.rb
Updated reserved color of FCCU since text color is not possible to update
=> [18Uruguay] Updated reserved color of FCCU

lib/engine/game/g_18_uruguay/step/buy_sell_par_shares.rb
[18Uruguay] Handle nil bundles in can_buy?
=> [18Uruguay] Handle nil bundles in can_buy?

lib/engine/game/g_18_uruguay/nationalization.rb, lib/engine/game/g_18_uruguay/phases.rb, lib/engine/game/g_18_uruguay/step/route.rb
[18Uruguay] Corrected nationalization
- Updated the share bunlde calculation in nationalization
- Updated so that you transition into phase 7 on nationalization
- Minor closes on nationalization
- Removed "Attach good to train" text  after nationalization
=> [18Uruguay] Corrected nationalization

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/goods.rb
[18Uruguay] RTPLA starts with three goods from start
=> [18Uruguay] RTPLA starts with three goods from start

lib/engine/game/g_18_uruguay/game.rb
Only final OR in last round should be doubled
No track and token in last or
=> [18Uruguay] Only final OR in last round should be doubled

lib/engine/game/base.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/single_item_auction.rb, lib/engine/game/g_18_royal_gorge/step/special_choose.rb
* fix salvaging rusted trains for some cash - fixes https://github.com/tobymao/18xx/issues/10761
* fix St Cloud Hotel's brown phase hex - fixes https://github.com/tobymao/18xx/issues/10762
* fix SF paying off Doc Holliday's debt when Doc private is not in the game - fixes https://github.com/tobymao/18xx/issues/10763
* fix everyone passing on last private company in the auction - fixes https://github.com/tobymao/18xx/issues/10771
* fix logging of priority deal player at end of auction - fixes https://github.com/tobymao/18xx/issues/10772
* fix handling local jeweler after it has closed - fixes https://github.com/tobymao/18xx/issues/10789
* one small change to core code - adds a `silent` argument to `reorder_players()` to completely prevent logging
=> [18RoyalGorge] bug fixes

lib/engine/game/g_1868_wy/step/buy_train.rb
Fixes #10783
* the base code determined that both the 4 and 4+3 variants should be available for other corporations to buy (other code made sure the UI only presented the 4+3, which is how the train was bought initially by LNP)
* FE&MV has $325, more than the face value of a 4-train ($300) but less than the 4+3's face value ($360)
* the 1868 Wyoming code assumes that if two variants are available, we're buying from the depot
* when buying from the depot, we can only buy a train we can afford or the cheapest, so the 4+3 gets filtered out
The fix is to simply return the single active variant if the train is in fact owned by a corporation instead of the depot.
=> [1868WY] fix available variants on trains owned by corporations

lib/engine/step/buy_sell_par_shares.rb
Fixes #5698
put in a gate to check if the owner == @game.bank, and added a log entry for that situation, then included the previous code as an else. 
I figured this was desirable if no one had closed the bug report in nearly 3 years.
=> [site] eliminates bold text in log when buying a company from the bank

lib/engine/game/g_1871/game.rb
Fixes #8991 
I was thinking about this, and I agree with the initial report that the liquidity is wrong, but I disagree with the calculation. Liquidity is how much money the player potentially has access to _now_. So actually, liquidity is player cash + the value of maximum 3 sellable shares per corporation.
Additionally, the calculation would need to ignore the value of any shares in corporations that the player has already sold that turn. 
To do this, I took the `def value_for_dumpable` method, which is referenced in `def liquidity`, from base.rb, which is:
```
def value_for_dumpable(player, corporation)
return value_for_sellable(player, corporation) if self.class::PRESIDENT_SALES_TO_MARKET
max_bundle = bundles_for_corporation(player, corporation)
.select { |bundle| …
```
=> [TOP1871] fixes liquidity calculation

lib/engine/game/g_1846/game.rb, lib/engine/game/g_18_los_angeles/game.rb, lib/engine/game/g_18_mo/game.rb
=> [1846] during auction, show private companies under bank in Entities tab

assets/app/view/game/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/round/stock.rb, lib/engine/game/g_1822/step/buy_sell_par_shares.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/game.rb, lib/engine/player.rb
* 1822CA - fix reference to wrong private ID in tax haven's text
* 1822, 1822CA - show tax haven ID and player owner's name on entity card as a shareholder
* 1822CA - allow bidding on tax haven even when at cert limit (this rule does not apply to 1822's tax haven)
Fixes #10654
Fixes #10678
=> [1822, 1822CA] fix Tax Haven cert limit, text, and display in corporation shareholders

lib/engine/game/base.rb, lib/engine/game/g_1846/game.rb, public/fixtures/1846/README.md, public/fixtures/1846/hs_wbpewgex_1715274627.json
Addresses #10743 where minors and private companies have all closed. There is still an outstanding issue when some private companies (but not minors) are still open and should eventually drain the bank, but the engine just hangs.
The game end check is added to the base code, but not to the default conditions. While it is applicable to other games where corporations can be closed, I'm not confident enough that the implementation of `all_closed?` here would be universal, so it's only in 1846 for now.
=> [1846] add game end check for all companies and corporations being closed

lib/engine/game/g_1822/step/tracker.rb
=> [1822 family] when laying to border, remove adjacent border if it has track

scripts/db/dump_prod.sh, scripts/db/env.prod
* the bash command given to ssh was interpreted as multiple arguments, use quotes to treat it as a single argument
* the prod db port from the hostname is 5432, it's only 5433 inside of Docker
=> fix some bugs with creating a scrubbed db

lib/engine/game/g_1850/game.rb
Fixes #9949
Previously, the share price of the corp in EMR wouldn't drop because of potential price protection, which would prevent a player from deliberately closing the corp.
I added a line in `def sell_shares_and_change_price` to return super if the current round entity is the bundle corporation. Since the only time the current entity could be a corp is during ORs, I didn't bother with an OR guard clause.
=> [1850] Selling shares of the corp in EMR immediately affects price

lib/engine/game/g_1860/game.rb, lib/engine/game/g_1860/meta.rb
Fixes #9484
Implements the simplified insolvency rules from the game rules.
=> [1860] implements simplified insolvency variant

lib/engine/game/g_18_mag/game.rb
Fixes #10673 10673
**Edit to add:** this will require pins for games using this expansion (:new_major) 
The CIWL bonus should be added to revenue, not to the minor company's treasury. Confirmed by the designer here: 
https://boardgamegeek.com/thread/3309608/article/44344808#44344808
=> [18Mag] changes CIWL bonus from subsidy to revenue

lib/engine/game/g_18_mag/meta.rb
The expansion content is restricted to 3-6 players, but currently the site allows you to create 2-player games using expansion content. Some of these do not work and throw out errors. 
This update will prevent 2 player games from being started with those options enabled.
=> [18Mag] restricts expansion content to 3+ players

lib/engine/game/g_1866/game.rb
Fixes #10481
**This will absolutely require pins, as it will drastically change the treasury of any corps that were running Palace Cars on E-trains.**
As per section 2.6 of the rules, the Palace Car doesn't apply its bonus to E-Trains
I fixed this by adding the `e_train?(train)` method on lines 1851-1853, and then calling it on line 1810.
I also made some grammatical improvements to the description and events related to infrastructure.
=> [1866] Palace Car shouldn't work with E-trains

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/meta.rb
These are official variants found on page 29, section 12.6 in the 2020 1822 rulebook
Fixes #9808 by way of providing an officially endorsed variant combo that gets the desired outcome
=> [1822] Implement 1822+ variants for no removals and single stack

lib/engine/game/g_1822_pnw/game.rb
Fixes #10758
Pins needed if anyone got away with upgrading to the boom town tile without the private.
=> [1822PNW] prevent brown town tiles from upgrading to the Boom Town tile

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/step/buy_train.rb, lib/engine/game/g_18_uruguay/trains.rb
[18Uruguay] Corrected the forced train purchase after nationalization
- [] Add the `pins` or `archive_alpha_games` label if this change will break existing games
=> [18Uruguay] Corrected the forced train purchase after nationalization

lib/engine/game/g_1822_pnw/game.rb, lib/engine/game/g_1822_pnw/round/stock.rb
When an associated Minor is removed from a bid box because its associated Major is started directly, a placeholder company is used to fill the bidbox, and is cleaned up at the end of the stock round.
Fixes #10525 and #10609, where an associated Minor was removed from bid box 1, and the Minor in bid box 2 received no bids and caused a train to export as if it had been in bid box 1.
=> [1822PNW] create placeholder company to occupy empty bid boxes

lib/engine/game/g_18_royal_gorge/game.rb
Fixes #10846
Pins probably aren't needed, this should be deployed with other open RG PRs that do require pins anyway, adding the label for safety.
=> [18RoyalGorge] mark gold icons as not preprinted

lib/engine/game/g_1822_pnw/game.rb
Fixes #10858
Note: in the prototype, this was not the rule, see #8393 and #8472, which reference Rule 7.1.7:
> Once the game end has been triggered, the game will end at the indicated time,
even if another end condition is triggered after the first.
In the final rulebook, Rule 7.1.8 says this:
> Once the game end has been triggered, the game will end at the indicated
> time. If another end condition is triggered after the first that would make
> the game end sooner, then that end game condition takes precedence in deciding
> when the game ends.
=> [1822PNW] stock market endgame takes precedence over bank breaking

lib/engine/game/g_1822_pnw/game.rb, lib/engine/game/g_1822_pnw/step/acquire_company.rb, lib/engine/operator.rb
* fix showing the Major's new home on the card after P20 Backroom Negotiations changes it, fixes #9751
* P20 Backroom Negotiations changes the Major's destination when its destination is the same as the newly associated Minor's home; the Major's original home becomes the destination; fix this case and show the new destination on the card, fixes #9993
=> [1822PNW] P20 - update home/dest on major's card, fix dest changing cases

lib/engine/game/g_1868_wy/game.rb
=> [1868WY] don't show corp stacks in phase 5, when all corps can be started

lib/engine/game/g_18_mag/meta.rb
Fixes #9668
The two New Minors variants are incompatible with each other. This tweak prevents players from creating a game with both variants selected.
=> [18Mag] Prevent selecting both New Minors variants

assets/app/view/game/button/buy_share.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
* only increase DEBT after Treaty of Boston
* fix US Mint Worker (B6)'s discount when buying 2 shares
* the `modify_purchase_price` method actually affects the per-share price
of the bundle, not the overall bundle price, so it didn't work with B6's
two-share bundle
* change the `buy_share` button to display the `modified_price` times the
number of shares to given the total modified bundle price
Fixes #10838
=> [18RoyalGorge] bug fixes for DEBT and US Mint Worker (B6)

assets/app/view/game/button/buy_share.rb, lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
`modify_purchase_price` modifies the price of the bundle, but it was being passed as an arg that modifies the price of each share in the bundle; some variables have been renamed, the per-share price is computed, and the correct value is now passed into `buy_shares`
Caused by [#10840](https://github.com/tobymao/18xx/pull/10840/files#diff-9b2159472e7490019b81ebc059e863df6e9875c016bad07ae7627ed9322cd024)
Fixes #10870
=> fix buy share button logic with modified share price

lib/engine/game/g_1841/entities.rb
Pretty much everyone I know who plays 1841 refers to the different private companies by their color, not the random jumble of 4-5 letters in its abbreviation or even its name. We have the ability to color code the privates, I think we should do it. 
Here's how it would look:
=> [1841] color-coding the concessions

lib/engine/game/g_18_mag/game.rb
fixes the calculation for ciwl_add with a ternary.
Fixes #10876 
My initial change didn't take into account that sometimes there wouldn't be any ciwl_add value. This corrects the calculation by turning it into a ternary.
=> [18Mag] fixes ciwl_add calculation

lib/engine/game/base.rb
Commit 67572e8 had broken 1858. This commit introduced changes to ability timing, introducing a check that an ability with timing `owning_player_sr_turn` was either owned by a player or a player's company.
1858 includes abilities that are owned by minor entities which were failing this check. This meant that it was not possible to exchange a private railway company (minor+company pair) for a share in a public comany (corporation).
Fix this by changing the check to work for minors too.
Fixes tobymao#10813.
- ~~Add the `pins` or `archive_alpha_games` label if this change will break existing games~~
=> [Core] Minor's abilities can be used in stock round

assets/app/view/game/corporate_buy_companies.rb, assets/app/view/game/ipo_rows.rb, lib/engine/game/g_18_india/game.rb
- [n/a] Add the `pins` or `archive_alpha_games` label if this change will break existing games
Added the IPO Rows view to Corporate Buy Companies View
=> [18 India] [Core] Add IPO Rows to Corporate SR

assets/app/view/game/double_head_trains.rb
Fixes #9737
Dark mode is unchanged.
=> [1868WY] fix double-heading trains selection for light mode

assets/app/view/game/player.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/buy_sell_par_shares.rb, lib/engine/game/g_1822_ca/game.rb
Fixes #10159
See also #10678
* 1822 family: change view to count winning bids as certificates
* 1822CA: revert commit which allowed bidding on P11 Tax Haven when at cert limit; although the private itself does not count, the bidding cube does.
> 4.10.8 A player may not place or move a bid on an item if they are at the certificate limit. Each item on which a player currently has the highest bid counts as a certificate against the certificate limit. (!is applies to P11 Registered Retirement Savings Plan as well.)
=> [1822 family] show winning bids in the player card's cert count; fix 1822CA tax haven

lib/engine/game/g_1822_mx/game.rb
Fixes #9276
Probably doesn't need a pin, the only tile showing was one that had no copies left available to lay.
=> [1822MX] ensure builder cubes are the only potential tiles for builder cube companies

lib/engine/game/g_1870/game.rb, lib/engine/game/g_1870/meta.rb, lib/engine/game/g_1870/step/connection_token.rb
This variant makes the destination tokens on non-offboard spaces `cheater` tokens instead of `extra_slot` tokens. 
from the rulebook:
=> [1870] implements Station Wars rulebook variant

lib/engine/game/g_1822/entities.rb, lib/engine/game/g_1822_africa/entities.rb, lib/engine/game/g_1822_mx/entities.rb, lib/engine/game/g_1822_pnw/entities.rb
match the physical games, where companies which can be acquired by minors are green, and companies which cannot are red; this is already done for 1822CA
=> [1822 family] add private company colors

lib/engine/game/g_1841/game.rb, lib/engine/game/g_1841/meta.rb
Fixes #10832 
Add optional rule for Version 1 games to allow SFLi formation to use Version 2 rules.
=> 1841: add version 1 optional rule for SFLi

lib/engine/game/g_1822_pnw/step/acquire_company.rb, lib/engine/operator.rb
=> [1822PNW] fix updating the minor's simple logo when associated major changes

lib/engine/game/g_1822_mx/step/buy_sell_par_shares.rb
Rule 1.3.1 says the game ends "Immediately, if the first stock round ends with nothing sold", NdeM shares are something
=> [1822MX] buying NdeM shares in first stock round prevents a game end

lib/engine/game/base.rb, lib/engine/game/g_1822_mx/step/buy_sell_par_shares.rb, lib/engine/game/g_1841/game.rb, spec/assets_spec.rb
Fixes #9821 without causing #10900, which #10896 did
* adds an 1841 test that would have caught #10900
=> [1822MX] include NdeM shares in liquidity calculation

lib/engine/game/g_18_royal_gorge/entities.rb, lib/engine/game/g_18_royal_gorge/game.rb, lib/engine/game/g_18_royal_gorge/trains.rb, public/fixtures/18RoyalGorge/post_boston.json
* metal companies should pay at end of final OR set, fixes https://github.com/tobymao/18xx/issues/10922
*  put debt "share price" on corp card as cash so it is visible on the entities tab 
* set colors for the private companies for more clear auction grouping
* sort companies in auction by price, not number (migrated the `post_boston` fixture by hand)
* better description for Steel Depot 
* rename 6-trains to "6x2"
=> [18RoyalGorge] fix endgame, add some small enhancements

lib/engine/auto_router.rb, lib/engine/game/g_1822/game.rb
Move 1822's check for L-trains into a new method so that it can be called during auto routing
Technically applicable to all 1822 games, most applicable to 1822MX as the NdeM is the most likely entity across these titles to be running multiple L-trains
Fixes #7902
=> [1822 family] Allow auto-routing to run L-trains in different cities

assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, assets/app/view/game/player.rb, assets/app/view/game/round/stock.rb
Fixes #10543
1822's auctions are during a Stock round instead of a special Auction round, so it can be a player's turn without `bid` being an available action.
=> [1822 family] render bid info based on step, not just available actions

lib/engine/game/base.rb, lib/engine/game/g_1822_mx/game.rb
The implementation of `Game.can_dump?` introduced by tobymao#10907 broke the (pre-alpha) implementation of 18Ardennes. It caused a 'maximum stack size exceeded' error. This is because there is a step in 18Ardenees where `actions` calls `@game.liquidity`, and so the call to `active_step` in this new `can_dump?` function is causing an infinite loop.
To fix this, and avoid the same error being caused in future, this commit makes the base class implementation of `can_dump?` as simple as possible, just calling `Bundle.can_dump?`. The version of the method which checks `active_step` is moved into the 1822MX game code.
=> [Core/1822MX] Simplify base implementation of Game.can_dump?

lib/engine/auto_router.rb, lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb, lib/engine/game/g_18_los_angeles/game.rb
Trains within a group cannot have overlapping routes, but they can overlap with routes of trains in different groups. Trains not listed in `TRAIN_AUTOROUTE_GROUPS` end up in a default group.
* in 1822, E-trains can overlap with other trains; all others are automatically placed in another group
* in 18 Los Angeles, freight  (e.g., 3/5) trains can have routes overlapping with passenger trains
Fixes #7982
=> [Autorouting] create groups of different trains for autorouting

lib/engine/game/g_1822_pnw/step/special_track.rb
other logic is already in place to prevent the portage from going after other tile lays, this fixes when portage is used first
Fixes #10920
some pins will be needed `[126288, 126312, 142944, 143929, 150567, 157534, 160785]`
=> [1822PNW] prevent other tile lays from being made after portage

lib/engine/game/g_system18/game.rb, lib/engine/game/g_system18/map_poland_customization.rb, lib/engine/game/g_system18/map_uk_limited_customization.rb
System18 - Poland map changes from Ian:
- add rivers to map
- priority deal shouldn't move after a Parliament Round
System18 general changes
- end game early if SR ends with no floated corps
=> System18: Poland - add river symbols; fix PD after Parliament Round

lib/engine/game/g_system18/map_poland_customization.rb, lib/engine/game/g_system18/step/dividend.rb
Fixes #10947 
Adds bonus legend to Poland map.
=> System18: fix inc-cap dividends; add legend to Poland map

Gemfile, Gemfile.lock, Rakefile, api.rb, assets/app/view/create_game.rb, lib/assets.rb, lib/engine.rb
After the issues with #10797 and #10810, I've used this branch for a few weeks to make sure it was stable before opening another PR for this.
Stop waiting for the files for all titles to build in local dev mode; only build for titles as needed. This reduces time for initial development setup, and reduces the pain for every `make clean`.
This changes functions in `lib/assets.rb` to use a `titles` param so that only the given titles are built, and change cached functions to cache things per-title when possible instead of caching the whole function call. In non-production mode, the API will trigger builds for game files that aren't already built.
It's best to view this diff with the "Hide whitespace" setting enabled. If the changes as a whole are confusing / difficult to review, looking at …
=> Dev mode: compile only game files for requested games 

lib/engine/game/g_1822_africa/entities.rb
also update to use Scott's suggested working
Fixes #10886
Pins needed for games where P12 was used and then more tiles were laid on the same turn, at least these games: `[137381, 138358, 139168, 139558, 143179, 143324, 144765, 144839, 145246, 145270, 150797, 158656, 161673]`
=> [1822Africa] fix step and tiles for P12

lib/engine/game/g_1822_ca/step/destination_token.rb, lib/engine/graph.rb, lib/engine/part/node.rb, lib/engine/part/path.rb
Working on #10331. This helps compare performance with the new graph system, and helps better identify where the graph computation is turning out to be very costly.
There are a number of other places where `node.walk` or `path.walk` are called directly, so far I've only adding logging for that to the 1822CA step destination step for #10956, it's probably worth adding logging in more places.
A hash is created in `Graph#compute` and passed into `Node#walk` and `Path#walk` where it is mutated. If the `walk` methods are called outside of `Graph`, the total walk calls will still be computed but are not currently logged.
=> [graph] track and log the number of calls made to `node.walk` and `path.walk`

lib/engine/game/g_1822_pnw_srs/game.rb
this was missed in the rulebook as well, the correct count of 6 was provided at https://boardgamegeek.com/thread/3233220/article/43669844#43669844
=> [1822PNW SRS] add bidding tokens, fix 2p

assets/app/view/game/bid.rb, assets/app/view/game/company.rb, assets/app/view/game/corporation.rb, assets/app/view/game/player.rb, assets/app/view/game/round/stock.rb, spec/assets_spec.rb
Fixes #10543
1822's auctions are during a Stock round instead of a special Auction round, so it can be a player's turn without `bid` being an available action.
#10913 was the first attempt at this, but it broke 18NY and 1817 so it  was reverted. Tests have been added for those titles at actions where they failed to render with the original change.
=>  [1822 family] render bid info based on step, not just available actions

lib/engine/game/g_18_ga/entities.rb
Fixes #10965 
Adds hex coordinate I9 to the description of the Waycross & Southern private company description.
=> [18GA] Adds coordinates to private description

assets/app/view/game/hex.rb
Almost all of the games with striped tiles that have been implemented so far have a `:pointy` layout (1822Africa is the only exception I could find). With a pointy layout the stripes on a tile are rotated 30° degrees from vertical.
If a game with a `:flat` layout has a striped tile then these will currently be rendered with vertical stripes. This, IMHO, doesn’t look great. This pull request rotates these stripes by 60°.
This change has been done by grouping the stripes in a `g` element and applying a `rotate` transformation to it. It would also be possible to have done this by changing the points returned from the `stripe_points` method in `assets/app/lib/hex.rb` but my trigonometry was too rusty to be able to calculate all of the coordinates.
[CC: @vandamm and @scottredracecar for the …
=> [Core] Rotate stripes on tiles for games with a :flat layout

lib/engine/game/g_1850/game.rb
Fixes #10976
- [NA since alpha] Add the `pins` or `archive_alpha_games` label if this change will break existing games
Once a president contributes to a train purchase, it may only be from the depot
no pins since the game is alpha
=> [1850] must buy from depot if pres contributes

lib/engine/step/buy_sell_par_shares.rb
In certain cases/games more than one share may exists which is eligible. max_by function evaluates without an error in this case.
Fixes #10814 
- ~~[] Add the `pins` or `archive_alpha_games` label if this change will break existing games~~
In 1847 a constellation may occur, where this particular loop collects more than one share with equal percent value. 
The Array.max function seems to not work as expected with the shorthand notation, because it is accepting an integer argument.
Enumeration.max_by does not have this issue.
=> fix: mitigate wrong numer of arguments in max.

lib/engine/game/g_18_rhl/entities.rb
- ~~[ ] Add the `pins` or `archive_alpha_games` label if this change will break existing games~~
just a typo.
=> 18Rhl: fix typo in name of company No. 3

assets/app/view/create_game.rb
Fixes #11010
- [na] Add the `pins` or `archive_alpha_games` label if this change will break existing games
This is just to file off the sharp edge of typing zero accidentially
It only covers the case where the frontend generates a bad playercount, not a tamperdata/direct POST
I believe the issue was that we were checking explicitly for .zero? on those fields, and then setting them to nil. That doesn't seem to be necessary and actually creates an issue where the "autocorrect" logic doesn't fire
=> disallow zero as playercount on user input

lib/engine/ability/README.md, lib/engine/ability/token.rb, lib/engine/game/base.rb, lib/engine/game/g_1822_ca/entities.rb, lib/engine/game/g_1822_ca/step/special_token.rb
Fixes #11004
* [core] - adds new param for token abilities, defaults to `false` and should not change previous behavior when it is `false`
=> [1822CA/core] add `same_hex_allowed` to token abilities, use for P10

assets/app/view/game/corporation.rb, lib/engine/game/g_18_ardennes/entities.rb, lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/buy_train.rb, lib/engine/game/g_18_ardennes/step/minor_exchange.rb, lib/engine/game/g_18_ardennes/step/post_conversion_shares.rb, lib/engine/game/g_18_ardennes/step/track.rb
Various fixes for 18Ardennes identified during private alpha testing:
- Allow the GL minor company (which is implemented as a Company object) can be sold during emergency money raising.
- The GL minor company can be sold when over the certificate limit.
- Include the value of the GL minor company in liquidity calculations.
- Share price does not change on sales, apart from president sales.
- Invalidate the game graph after a minor is exchanged for a public company share. There are changes to tokens when this happens, and hexes available for track lays were not being correctly calculated.
- You don't have to buy the cheapest available train when in emergency money raising.
- You can go above 60% ownership of a public company when buying shares from the bank pool.
- After the initial …
=> [18Ardennes] Various fixes

lib/engine/game/g_22_mars.rb, lib/engine/game/g_22_mars/entities.rb, lib/engine/game/g_22_mars/game.rb, lib/engine/game/g_22_mars/map.rb, lib/engine/game/g_22_mars/meta.rb
First part of 22Mars implementation: only the map.
Does not include random map generation now.
=> 22Mars: Add map and tiles

lib/engine/game/g_1849_boot/entities.rb
Fixes #10775 
Adds "L'Aquila" to the description of this private, since even though this city is not a coastal city, it is on the edge of the map and it's the only city that is neither a valid target for the private ability nor mentioned in the exceptions. 
This makes it clearer.
=> [1849 K2S] fix Societa Marittima description

lib/engine/game/g_1830/game.rb, lib/engine/game/g_1830/step/buy_sell_par_shares.rb
Fixes #9735 
Both the Avalon Hill and Mayfair rules for 1830 say that players can buy private companies from each other in any stock round after SR1. This implements the ability. 
I tested with several live games, but it would be a good idea to check for pins, in the case where players who had no possible actions in subsequent SRs were automatically skipped, which wouldn't happen with this code.
=> [1830] implements private company cross-buys

lib/engine/game/g_18_cz/game.rb
changed TILE_RESERVATION_BLOCKS_OTHERS from :always to :single_slot_cities, since this game has a OO hex with a reservation that merges into a 2-slot city in brown.
This shouldn't need pins, since no corp would be able to token before ATE at all with the previous rule.
=> [18CZ] fixes OO reservation issue with hex B9

lib/engine/game/g_18_gb/entities.rb
=> [18GB] Add blocked hexes to private descriptions

lib/engine/game/g_18_india/step/home_track.rb
Fixes #11058 
This is "unlikely" to break existing games that haven't gotten past this point or didn't have two corps in a OO tile. 
Rewrote method that moved a reservation from a hex back to a city after it was moved by laying the first yellow OO tile. 
The default code doesn't handle the case when  yellow OO tile is placed where there is a home token and a reservation to track.   This case is handled by first moving the reservation to the hex and then after the tile and token are placed, moving the reservation back to the other un-tokened city.
=> [18 India] Fix OO reservation relocate bug 

assets/app/view/welcome.rb, lib/engine/game/g_18_sj/meta.rb, public/fixtures/18SJ/166116.json, public/fixtures/18SJ/167041.json
Updated Welcome text.
Added two fixtures for 18SJ. One full standard game, and one full gane for Oscarian variant. Do cover a good selection of all privates. 18SJ only had a previous fixture that tested the fix of an error case for the 2 player variant.
So it does cover a good bit of options, including incremental and full cap.
18SJ has been stable for over a year, with only few issues. No open isses at the moment.
None
None
=> [18SJ] Set in production

lib/engine/game/g_1846/meta.rb
Currently one can create a '46 in which only 1E privates are allowed and also 2E privates are guaranteed.
This implements the 'check options' feature and prevents that at the frontend level. 
Also will throw an error if a game is imported with such options
=> [1846] optional rules are XOR

public/fixtures/18 Hiawatha/164543.json, public/fixtures/18 Hiawatha/164606.json
- [n/a] Add the `pins` or `archive_alpha_games` label if this change will break existing games
Adds a couple of fixture files for 18 Hiawatha
=> [18 Hiawatha] adds fixture files

assets/app/view/create_game.rb
Fixes #11064
After this change, JSON import and game creation all work
In the case of imported games, `selected_game_or_variant` is Nil so the code was bailing when `title` was set.
This was due to where I was checking playercount, as part of a codepath that handled all 3 game types (multi, hotseat, json)
Now it only checks playercount for multiplayer 
I refactored this function to be (hopefully) more readable. 
To confirm that game creation and import works:
[import game.webm](https://github.com/user-attachments/assets/9ee0e72c-4961-4c59-8d4b-eae3a65ee0fd)
[create_multi_and_hotseat.webm](https://github.com/user-attachments/assets/095cf2d8-aad1-46b1-b21e-9977cc94f31c)
=> Fix issue checking playercount 

lib/engine/game/g_18_ardennes/entities.rb, lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/bankrupt.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/buy_train.rb, lib/engine/game/g_18_ardennes/step/convert.rb, lib/engine/game/g_18_ardennes/step/dividend.rb, lib/engine/game/g_18_ardennes/step/route.rb, lib/engine/game/g_18_ardennes/step/token.rb, lib/engine/game/g_18_ardennes/step/track.rb
It is pretty much impossible to go bankrupt in 18Ardennes, unless you‘re actually trying to do so. Nevertheless, there are rules for bankruptcy, so this pull request implements them.
There are two possible ways to go bankrupt: not being able to afford a train after emergency money raising, or not being able to start a public company that you’ve won in an auction. In both cases all your assets get sold to the market.
If the presidencies of any companies end up in the market these companies run on autopilot. They skip all steps in an operating round apart from running trains and paying out dividends.
If a company is on autopilot someone needs to select the routes its trains run. To speed up play the player selected to do this is the player who just operated the preceding company in the …
=> [18Ardennes] Bankruptcy

lib/engine/game/g_1849/game.rb, lib/engine/game/g_1849/meta.rb, lib/engine/game/g_1849/step/bond.rb, lib/engine/game/g_1849/step/buy_token.rb
Fixes #11116
Rules say that games with Electric Dreams also must use the Acquiring Station Tokens and Bonds variants. This automatically includes the other two variants if Electric Dreams is chosen.
Note: This will require pins for any games that are using the Electric Dreams variant without both Bonds and Acquiring Station Tokens.
=> [1849] Forces games with Electric Dreams variant to also use Bonds and Acquiring Tokens

lib/engine/game/g_system18/step/buy_train.rb
Fixes #11161
According to the rules (see below), shares issued during EMR in incremental cap games should only drop the price by a single space. The code had movement: :left_share. Corrected to :left_block.
This will only affect existing incremental cap games where multiple shares were issued during EMR.
=> [System18] corrects price change when emr issuing

lib/engine/game/g_18_uruguay/trains.rb
Fixes #11173
Adds the code for a $200 discount when trading in a 4, 5, 6, or 7 train for a diesel.
=> [18Uruguay] adds diesel discount.

lib/engine/game/g_1861/map.rb
Perm is the city in hex H2. This location name had been showing in the grey plain track hex H0.
Fixes #11175.
=> [1861] Move Perm location name to the correct hex

assets/app/view/game/corporation.rb, lib/engine/game/base.rb, lib/engine/game/g_1841/game.rb
Corporations can be restarted or reformed from mergers, but their shares cannot be sold until they have completed an operating turn.
`Game::Base` changes
* add new method `render_revenue_history?`, so that 1841 can have an override to tell when operating history belongs to a previous version of the corporation
* add explicit `emergency` keyword in `liquidity` recursive call, I found it confusing to read without it
Fixes #9502
Fixes #9525
=> [1841] new corporations: hide "last run" and exclude from liquidity

lib/engine/game/g_steam_over_holland/game.rb
Fixes #11164
Fixes #11155
Fixes #11150 
Fixes #11157 
Code I had for checking route bonuses doesn't seem to work. I replaced it with essentially the exact code from 1867 applying the same bonuses (simplified due to not needing the hexes to be unique).
Archive shouldn't be needed, since these routes would have simply been blocked before.
=> [SteamOverHolland] fixes revenue bugs

lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb, lib/engine/game/g_18_ardennes/step/dividend.rb, lib/engine/game/g_18_ardennes/step/exchange.rb
The last few corner case rules for 18Ardennes. It is unlikely that any of these would come up in actual gameplay, but they've been coded for completeness:
- The share price of a public company (major) cannot fall below 50F.
- If a minor company is in receivership following a bankruptcy, then it cannot be bought if its share price is in the grey zone.
- If a public company is in receivership then it does not have a president who could approve a request to exchange a minor company for a treasury share. Because of this, it is not allowed to attempt to exchange for a treasury share, but a player can exchange a minor for a market share.
- A player who has won the right to start a public company is allowed to sell shares (and/or the GL minor company) before starting the public company. But they …
=> [18Ardennes] Last corner case rules

lib/engine/game/g_18_uruguay/companies.rb, lib/engine/game/g_18_uruguay/corporations.rb, lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/trains.rb
Fixes #11047
Fixes #11051 
Fixes #11080
- Changes sym for Latifundio Agrícola to LO_CORN (and all references to it) to match the other Latifundio private syms.
- Sets float percentage for RPTLA to 30, since it has a 30% presidency.
- Corrects 4D train. It currently runs 4 cities/offboards and infinite towns, it should be max 4 stops with the ability to skip towns.
=> [18uruguay] various fixes

lib/engine/game/g_18_esp/corporation.rb, lib/engine/game/g_18_esp/entities.rb, lib/engine/game/g_18_esp/game.rb, lib/engine/game/g_18_esp/map.rb, lib/engine/game/g_18_esp/round/operating.rb, lib/engine/game/g_18_esp/step/acquire.rb, lib/engine/game/g_18_esp/step/buy_carriage_or_company.rb, lib/engine/game/g_18_esp/step/buy_sell_par_shares.rb, lib/engine/game/g_18_esp/step/buy_train.rb, lib/engine/game/g_18_esp/step/choose.rb, lib/engine/game/g_18_esp/step/company_pending_par.rb, lib/engine/game/g_18_esp/step/discard_train.rb, lib/engine/game/g_18_esp/step/dividend.rb, lib/engine/game/g_18_esp/step/route.rb, lib/engine/game/g_18_esp/step/special_choose.rb, lib/engine/game/g_18_esp/step/track.rb, public/fixtures/18ESP/1.json
in last ORs north corps jump 2 times and not 3
fix private abilities
one mountain pass open per OR turn
can take over multiple minors
minors close instead of stop operating, no auction
remove extra icons after phase 5
p2 can not be sold
tender can be bought from other corporations and also the bank
=> [18ESP] implement minor rule changes

lib/engine/company.rb, lib/engine/game/g_1837/entities.rb, lib/engine/game/g_1837/game.rb, lib/engine/game/g_1837/step/selection_auction.rb, lib/engine/step/selection_auction.rb
Implementation of the start packet auction for 1837.
Also includes minor log bug fix for selection auctions where if the first player passes, the log would state "Player 1 passes" rather than "Player 1 passes on <company name>".
=> [1837] Start packet auction

assets/app/lib/profile_link.rb
Several games have dummy players:
- The Union Bank in 1871.
- Vaclav in the two-player version of 18CZ.
- A W Edelswärd in the two-player version of 18SJ.
These are all represented by player objects with an ID of -1.
These entities are shown on the entity page (and other places) where a link to the player profile pages is included. Clicking on these links gives a 404 error, as these links are not valid.
This pull request suppresses the links to the profile pages for players with negative user IDs.
Fixes tobymao#11124.
The assumption here is that any negative user IDs aren't real people.
=> Suppress profile links for dummy players

lib/engine/game/g_22_mars/game.rb, lib/engine/game/g_22_mars/round/permit_purchase.rb, lib/engine/game/g_22_mars/step/select_or_discard.rb
It's like ISR, but permits (privates) are randomly distributed to players (1 each) and then players can choose whether to buy the assigned permit for listed price or to remove it from the game. And you can view which permits are in player hands on Entities tab.
Also game round tracker on Info tab now has interactive Revolt markers on rounds where revolt can start.
=> [22Mars] Initial Permit distribution round

lib/engine/game/g_1861/map.rb
=> Fix spelling of Yaroslavl in 1861.

lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/bankrupt.rb, lib/engine/game/g_18_ardennes/step/buy_sell_par_shares_companies.rb
An extra parameter had been added to the G18Ardennes implementation of the `Game.declare_bankrupt` method, which was causing an error when the superclass method was called.
This commit renames the 18Ardennes method to `bankrupt!` which calls `declare_bankrupt` with the correct number of parameters.
Fixes tobymao#11203.
=> [18Ardennes] Fix error on bankruptcy

lib/engine/game/g_18_uruguay/game.rb
Company should get full cap but no destination bonus after nationalization 
Fixes #11060
This can break existing games
=> [18Uruguay] Company should get full cap after nationalization and no destination bonus

lib/engine/game/g_1822_nrs/map.rb
Fixes #11223
Shrewsbury was misspelled as Shrewbury
this mistake was only on the NRS map file, spelling is correct in both 1822 and 1822MRS
=> [1822nrs] fixes spelling of shrewsbury

lib/engine/game/g_18_norway/game.rb, lib/engine/game/g_18_norway/steps/token.rb, lib/engine/step/tokener.rb
=> [18Norway] Updated harbor

Makefile, api.rb, lib/assets.rb, queue.rb
I had to rename deps because there was a name collision where the file was written to twice once in compile_lib and another time in combine and thus the corresponding source maps would get mangled. 
This made it much easier to debug some issues. I was able to get ruby source code in the web inspector and see where exceptions where being thrown from.
=> assets: Emit source maps

lib/engine/game/g_1858_switzerland/game.rb, lib/engine/game/g_1858_switzerland/graph.rb, lib/engine/game/g_1858_switzerland/round/closure.rb
This adds code handling the differences between the original 1858 game, and the prototype of the variant set in Switzerland.
These differences include:
- Bonuses for running north-south or east-west routes.
- Three sets of private railway companies instead of two.
- Two private closure rounds instead of one.
- Different timings for wounding and rusting mid-game trains.
- Mountain railway tiles which can be laid on hexes with a 120SF terrain cost. A public company that has laid one of these will then get a 40SF bonus to its revenue whenever it runs trains.
- Special rules for the private railway companies which have Gotthard as a home hex. Normally a public company is allowed to acquire a private railway if there is a connection to anywhere in the private's home hex; for GB you need a …
=> [1858Switzerland] Add game code for 1858 Switzerland variant

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/nationalization.rb, lib/engine/game/g_18_uruguay/step/route_rptla.rb
=> [18Uruguay] Do not ship more than ship capacity for rptla

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/step/destination_bonus.rb
[18Uruguay] Company shall only retreive destination_bonus in their own turn
Fixes #11073
Will break existing games
=> [18Uruguay] Company shall only retreive destination_bonus in their own turn

assets/app/view/game/dividend.rb, lib/engine/action/run_routes.rb, lib/engine/game/base.rb, lib/engine/game/g_1822/step/dividend.rb, lib/engine/game/g_1825/step/dividend.rb, lib/engine/game/g_1840/step/dividend.rb, lib/engine/game/g_1856/step/dividend.rb, lib/engine/game/g_1860/step/dividend.rb, lib/engine/game/g_1862/step/dividend.rb, lib/engine/game/g_1866/step/dividend.rb, lib/engine/game/g_1868_wy/step/dividend.rb, lib/engine/game/g_1870/step/connection_dividend.rb, lib/engine/game/g_1873/step/dividend.rb, lib/engine/game/g_1888/step/dividend.rb, lib/engine/game/g_18_esp/step/dividend.rb, lib/engine/game/g_18_mag/game.rb, lib/engine/game/g_18_mag/step/dividend.rb, lib/engine/game/g_18_tn/step/dividend.rb, lib/engine/game/g_18_uruguay/step/dividend.rb, lib/engine/game/g_18_va/step/dividend.rb, lib/engine/game/g_18_zoo/step/dividend.rb, lib/engine/step/dividend.rb, spec/game_state_spec.rb, spec/lib/engine/games/g_18_zoo_spec.rb, spec/lib/engine/games/g_18eu_spec.rb
Add generic implementation of subsidies in the dividend step.
Previously, games that used subsidies, copy and pasted the subsidy logic into their dividend step. This PR moves that copy and pasted code into the base dividend step. If a game does not have a subsidy, the added logic has no effect.
=> [Core] Add subsidies to dividend step

lib/engine/game/g_system18/game.rb
I added some game methods with my last edit. I forgot to make a call to super if a map didn't provide an override. This broke games that relied on the super method - 'place_home_token' most notably.
=> S18: add super to game overriding methods

lib/engine/game/base.rb, lib/engine/step/dividend.rb
1837's subsidies are called `mining revenue`. This PR allows the subsidy name to be configurable to allow games to customize it to their terminology.
=> [Core] Allow subsidy name to be configurable in the UI

assets/app/view/game/dividend.rb, lib/engine/step/dividend.rb, lib/engine/stock_market.rb, lib/engine/stock_movement.rb, public/assets/main.css
Hex markets can move diagonally up-left, up-right, down-left, and down-right. This PR adds support to the game logic and view logic to support.
=> [Core] Add support for hex market movement to dividends

lib/engine/game/base.rb, lib/engine/game/g_18_royal_gorge/step/special_choose.rb
* fixes debt pay-off and 13LB Gold Nugget bonus interacting and breaking
* possibly also affects Ghost Town Tour Co. (Y2), which is also active during the dividend step
No issue to link, issue was reported by the designer directly to me.
=> [core/18RoyalGorge] add `Dividend` to `ability_blocking_step`, fix debt/company interactions

lib/engine/game/g_system18/map_britain_customization.rb, public/fixtures/System18/182070.json
Fixes #11274 
Fixes #11273 
Adds fixture for System18
Will require archiving any S18 game using the Britain map (currently only one in progress).
=> S18 full Britain map fixes; add S18 fixture

lib/engine/game/g_1822_ca/game.rb
Fixes #11257
Corrects the game end description for when the bank breaks in 1822CA
=> [1822CA] fix game end description

lib/engine/game/g_1860/meta.rb, lib/engine/game/g_18_ireland/meta.rb
Update direct rules links for 1860 and 18Ireland to point to BGG instead of my personal dropbox (reduce bus factor and fragility)
=> Update rules for 1860 and 18Ireland to deprecate my personal dropbox

lib/engine/game/g_1822_pnw/game.rb
Fixes #11339
1822PNW was using base 1822's STATUS_TEXT, which of course uses £ instead of $ as its currency symbol. This corrects that.
=> [1822PNW] replace £ with $ in status info

lib/engine/game/g_1822_ca_ers/map.rb
Fixes #11329 
Makes hex T14 on the 1822CA-ERS map a non-terminal city. Confirmed by both Scott Petersen on the issue report comments, and the designer over discord.
=> [1822CA ERS] Winnipeg should be pass-through, not terminal

lib/engine/game/g_18_royal_gorge/game.rb
Fixes #11359
------
Pins needed: any games where more than one 2+ train remained at the end of the first OR set
=> [18RoyalGorge] export all 2+ trains at end of first OR set

lib/engine/game/g_1849/step/bond.rb
Fixes #11138
(hopefully)
We keep getting blocking step errors when using the Bonds variant, and it's always happening after the game enters phase 8, which is when the bonds are enabled. 
It's difficult to test this fix, as the error doesn't happen in my local test environment, but I think the fix here may help.  I changed the round_state definition, and modified the related code.
=> [1849] fix for the Bonds variant

lib/engine/game/g_1867/game.rb
If a major company is nationalised and then restarted it defaults to a 60% player ownership limit. This is wrong for the two-player variants, which allow a player to own up to 70% of a company.
Fixes tobymao#11246.
From testing, there is just one game that is broken after this patch is applied, game ID 147977 (there's an assumed pass when a player reaches 60% ownership in a merger round, which no long applies). This can be fixed by pinning or migrating.
=> [1861/1867] Restart major companies with 70% ownership limit in two-player games

lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb
Fixes #11363
----
Pins: any games where a player was skipped in the SR due to no valid actions, but they could have used the discount from a private company to afford a gold or steel company share
=> [18RoyalGorge] don't skip player if they can buy shares via private discount

lib/engine/game/g_1822_ca/game.rb
Fixes #11390
------
No pins needed: route values aren't recomputed every time the route is processed
=> [1822CA] only give Sawmill bonus to E-trains with tokens

assets/app/view/game/company.rb, lib/engine/game/base.rb, lib/engine/game/g_1822/game.rb
1822's `company_status_str` (called by views) was mutating the value of the private company entity, and there was a substraction operation in place to try to copmensate for that, but that caused #11040 by subtracting the tax haven's value for other players.
This has been simplified with the following approach:
- when displaying the company value, call a new wrapper method in the `Game::Base` class
- in 1822, override that new method only for the Tax Haven
Now the Tax Haven private company entity will always have a value of $0/£0, but the value of the Tax Haven "player" entity is handed off to display methods.
Fixes #11040
=> [1822/CA and core] fix 1822 tax haven bug

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_mx/entities.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/game.rb
Changed behavior:
* 1822: Mail Contract no longer pays with LP-train running to a city and town
* 1822CA: Large Mail Contract no longer pays with LP-train running to a city and town
* 1822CA: Small Mail Contract now pays with LP-train running to just a city
* Fixes #11147
* 1822MX: Mail Contract no longer pays with LP-train running to a city and town
Errata references:
* https://boardgamegeek.com/thread/2640241/article/40423428#40423428
* https://boardgamegeek.com/thread/2640241/article/43680986#43680986
* https://docs.google.com/document/d/1puHQJV4eLeunOtu_RyqAT-_mBCI93u8dqSBNwWMsAiE/
-----
Pins not needed since route values are not recomputed when processing the game actions.
=> [1822 family] fix Mail Contract interactions with permanent L-trains

assets/app/view/welcome.rb
The 18Royalgorge kickstarter is over. Removing the link to it from the welcome page.
=> Removes RoyalGorge KS link from welcome page

lib/engine/game/g_1871/step/buy_train.rb
Fixes #8260 
This will likely require pins. 
Players should not be able to sell more than 30% of a corp during funding, as per rule:
Corporations may issue above 30%, so I put in an added guard clause to ensure only players are blocked.
=> [1871] Prevents sale of more than 30% during EMR

lib/engine/game/g_1871/step/buy_train.rb
Fixes #10069
According to the rules of the game, a company cannot cross-buy after issuing shares. This prevents that from happening. 
Any games where a cross-buy has occurred after issuing shares would need to be pinned or archived.
=> [1871] Should not be able to crossbuy after issuing shares

lib/engine/game/g_18_ms/entities.rb
Fixes #10025 
The M&M private was usable by any corporation that the president of the owning corporation was running. This was corrected by adding `when: 'token'` to the company in entities.rb, limiting its use to the owning corporation's token laying step.
=> [18MS] Fixes M&M ability to only work for owning corp

lib/engine/game/g_1850/step/buy_train.rb
Fixes #9950 
rules say if you hold more than 60% and are selling shares of that corp, you must sell down to at least 60%. Currently this isn't enforced during EMR. 
1870 had code for this. I modified 1850 to inherit 1870's buy_train class, which I suspect was bentziaxl's intention since he had it in the require_relative at the top.
Pins may be required if there are any games breaking this rule.
=> [1850] require selling down to 60% when force selling

lib/engine/game/g_1858_switzerland/game.rb
Issue #11372 was caused by modifying 1858's train definitions without a making a deep copy. If a game of 1858 is loaded on the server after a game of 1858 Switzerland then it is was seeing the version of the definitions after these modifications, causing errors as 1858 does not have a method for handling the `blue_privates_available` event.
Making a deep copy of the train definitions prevents this error.
This commit also makes a deep copy of the phase definitions. No problems have been observed with this, but making the copy is safer.
Fixes #11372.
=> [1858 Switzerland] Avoid modifying 1858's train definitions

lib/engine/game/base.rb, lib/engine/game/g_1837/game.rb, lib/engine/round/stock.rb
Sold out stock movement is a common difference between games. Move the functionality to the game class, to reduce the amount of games that need to override the stock round class.
=> [Common] Move sold_out_stock_movement to game class

lib/engine/game/g_1837/game.rb, lib/engine/graph.rb, lib/engine/part/node.rb, lib/engine/part/path.rb
1837 allows backtracking along an hex edge when determining potential token locations. This PR adds backtracking support to `walk`.
=> [1837] Allow backtracking when considering token spots

lib/engine/game/g_18_esp/game.rb, lib/engine/game/g_18_esp/step/acquire.rb, lib/engine/game/g_18_esp/step/buy_carriage_or_company.rb
transfer all but one tender to the bank when buying p5.
fix broken game when buying p5
fix having two tokens in the same city when merging major with minor
Fixes #11337
=> [18ESP] fix a few minor bugs

lib/engine/game/g_1888/entities.rb, lib/engine/game/g_1888/game.rb, lib/engine/game/g_1888/step/exchange.rb
Fixes #11400
The Forbidden City private changed between the prototype phase and the final release. The final release version was never implemented. This implements it, but only when playing with the 1888-North variant, since the prototype version is still available for play on the site.
This will require pinning any games using the :north variant.
=> [1888-N] corrects the Forbidden City private ability

lib/engine/train.rb
The `variants` parameter passed to `Engine::Train.init_variants` is (in the default implementations) an array of train variant definitions that is part of the TRAINS constant. The code inside `init_trains` was, for each train, creating a new variant for the normal type of train and prepending it to the variant array. This was modifying the array inside the TRAINS constant, making the list of variants steadily longer.
This wasn't much of a problem in most cases as the extra items in the `variants` array were all duplicates and we only extra a single item for each variant name. But when games are loaded on the server in quick succession the TRAINS constant is shared between a game title and (potentially) any titles that inherit from that title. This was causing bug tobymao#11416, where 1858 …
=> [Core] Don't modify TRAINS definition when creating train variants

lib/engine/game/g_18_norway/game.rb
Only ships are allowed to use harbors
=> [18Norway] Only ships are allowed to use harbors

lib/engine/game/g_1807/entities.rb, lib/engine/game/g_1807/trains.rb
In the 1807/18BF rules the 10-share companies are called 'public companies', so use that terminology in the user interface.
=> [1807] Change terminology: public companies, not majors

lib/engine/game/g_18_uruguay/game.rb
The correction that was made to solve the problem with blocked home tokens accidently broke RTPLA so no home token were placed, this solves that issue
=> [18Uruguay] The correction of home toke timing broke RPTLA

lib/engine/game/g_18_uruguay/game.rb, lib/engine/game/g_18_uruguay/nationalization.rb, lib/engine/game/g_18_uruguay/step/nationalize_corporation.rb
Fixes #11111
Fixes #11074
This can break existing games
=> [18Uruguay] Also add FCE shares to secondary corps

lib/engine/game/g_18_uruguay/loans.rb
Fixes #11447
Can potentially break existing games
=> [18Uruguay] Interest should not be paid for penalty loans

lib/engine/game/g_1822_mx/meta.rb, lib/engine/game/g_1822_pnw/meta.rb, lib/engine/game/g_1825/meta.rb, lib/engine/game/g_1836_jr56/meta.rb, lib/engine/game/g_1841/meta.rb, lib/engine/game/g_1850/meta.rb, lib/engine/game/g_1858/meta.rb, lib/engine/game/g_18_eu/meta.rb, lib/engine/game/g_18_rhl/meta.rb, lib/engine/game/g_21_moon/meta.rb
There are a number of games that haven't updated the dev stage of the game in over a year. This PR moves each of those to the next dev stage.
=> Move to next dev stage if the dev stage has stayed the same for a year or more

lib/engine/step/home_token.rb
See linked issue for the "before" image.
=> [Core] Improve ux for start of OR home token placement

assets/app/view/game/game_info.rb, assets/app/view/game/train_schedule.rb
Fix errors in rusts/obsoletes information in train tables on info and spreadsheet pages
Fixes #11305
=> Fix errors in rusts/obsoletes information in train tables on info and spreadsheet pages

lib/engine/game/g_1860/trainless_shares_half_value.rb
Fixes #11332
With the non_operated_full_value variant, when I modified the `def player_value` code, I forgot to add in the value of shares of corps with trains. Admittedly a big oversight!
I suspect we'll need to pin any finished games on that variant, since their recorded final scores will be incorrect.
=> [1860] fix player value in game variant

lib/engine/game/g_1837/game.rb
When checking for games to pin, 1837 sees the error "Cannot place token on L2 as the hex is not available" on the server only for a subset of the games. I am unable to reproduce in my development environment with the same games that cause the issue in production. This is an attempt to fix it.
=> [1837] Attempt to fix transient 'hex is not available' issue

lib/engine/game/g_1871/step/dividend.rb
`entity.total_shares` doesn't always work correctly for PEIR.  If there are three shares then each is a 33% share, and `total_shares` returns 3.030303...
This can lead to rounding errors in dividend payout, with a revenue of 300 being calculated as 99 per share.
Fixes tobymao#11525.
=> [1871] Fix dividend payout when there are three PEIR shares

lib/engine/game/g_1858_switzerland/step/buy_train.rb
Pull request tobymao#11452 added some checks to the train buying step, to catch cases where too many shares had been issued during emergency money raising.
This was causing an error in the 1858 Switzerland two-player variant, where the robot-controlled SBB company buys a train for zero cash.
This fixes this error by declaring that zero is a valid amount for these train purchases.
Fixes tobymao#11553.
=> [1858 Switzerland] Fix train buying by robot player

lib/engine/game/g_18_uruguay/nationalization.rb
Fixes #11578
Also corrected half share payout so there is a small risk that games that has done the nationalization will brake
=> [18Uruguay] Corrected aquire fce share sequence

lib/engine/game/g_18_uruguay/game.rb
Fixes #11571
Should not break any existing games
=> [18Uruguay] Updated closed corporations after nationalization

lib/engine/game/g_18_norway/game.rb, lib/engine/game/g_18_norway/round/nationalization.rb
Updated the turn calculation in the end so that we do not end the game to early
- [] Add the `pins` or `archive_alpha_games` label if this change will break existing games
=> [18Norway] Corrected turn calculation

lib/engine/step/selection_auction.rb
If a player doesn't have enough cash to start a new auction in a selection auction, automatically pass
=> [Core] Enhance selection auction automatic passes

lib/engine/game/g_18_esp/game.rb, lib/engine/game/g_18_esp/step/acquire.rb, lib/engine/game/g_18_esp/step/buy_train.rb, lib/engine/game/g_18_esp/step/choose.rb
two minor rule changes/bug fixes:
1- when merging, corp doesn't unlock a new token. It either replaces an existing free token with one on map, or nothing (token of non survivor gets removed as usual)
2- minor companies can't own + trains (aka track_type narrow), when buying private that gets train, there's no choice, it gets a regular 2 train. Majors get the regular choice
=> [18ES] fix minor 18esp errors

lib/engine/game/g_18_norway/game.rb, lib/engine/game/g_18_norway/steps/nationalize_corporation.rb
Companies that are floated after end game is automatically nationalized
=> [18Norway] Companies that are floated after end game is automatically nationalized

lib/engine/game/g_1844/game.rb
When the first 6/6H train is bought, the destinations for pre-SBB and large historical companies are removed. This involves removing the destination abilities for these companies, but in tobymao#11591 this was causing an error.
The test for a destination ability is done for looking at the ability's description. BLS has, as well as the destination ability, an assign hexes ability. That does not have a description set, and so an `undefined method 'start_with?' for nil` was being thrown. This is fixed by using the safe navigation operator.
Fixes tobymao#11591.
=> [1844] Fix error from nil ability description

lib/engine/round/operating.rb
tobymao#11586 made some changes to the setup method of operating rounds. This has caused an error in some games of 1868 Wyoming, where P6c is one of the entities in the operating round. P6c is a company and does not have a trains attribute.
This adds a guard cause, to avoid errors like this. Fixes tobymao#11594.
It is possible that the change in #11586 has exposed a bug in the 1868 Wyoming code and P6c should not be an operating entity. So there might be a fix in that code, as well as, or instead of this one.
=> [Core] Don't assume all operating entities have trains

lib/engine/game/g_1867/game.rb, lib/engine/game/g_1867/step/home_token.rb
Commit d8abe5a (from pull request tobymao#11503) had changed the calculation of the active entities in a home token step. This had broken 1867, where the home token is placed by a player (the one who just started an auction), not a corporation.
This commit restores the previous behaviour.
Fixes tobymao#11565.
=> [1867] Fix active entity for home token step

assets/app/view/welcome.rb, lib/engine/game/g_18_esp/game.rb, lib/engine/game/g_18_esp/map.rb, lib/engine/game/g_18_esp/meta.rb
the rand generator doesn't work well when doing modulo even numbers, it is impacting the code in 18esp, as the random corp selected for random_share and random_president is not truly random.
A quick and easy fix is to divide the rand number by a 100, to get a more random distribution.
also moving 18esp to beta. Removed 1837 from welcome.rb as it's been there for over a month.
=> [18ESP] minor 18esp rand fix and move to beta

lib/engine/game/g_1867/game.rb
Looks like this bit was copied over from 1817, but 1861 and 1867 don't have medium sized 5-share corps.
=> [1867] Remove "medium" from corp sizes

lib/engine/game/g_18_norway/steps/token.rb
=> [18Norway] Adding missing extra_slot attribute

lib/engine/game/g_1858/step/buy_sell_par_shares.rb
A player's pass status was not being cleared when a bid for a private railway company was placed. This meant that it was possible for the initial stock round to end prematurely – if a player had passed on an auction earlier in the round but bid on a later one they were still marked as having passed, meaning the round could end if all other players had passed.
Fixes tobymao#11446.
This breaks a few games (seven of 1858, two of 1858 Switzerland, according to my testing) where the stock round had been ended too early. These will require pinning.
=> [1858] Clear pass flag when bidding for a private

lib/engine/game/g_1858/step/buy_sell_par_shares.rb
Players will sometimes click the autopass button to pass during an auction, then get confused when they are not allowed to bid on future auctions in the stock round.
This PR clears these programmed passes when a bid on a private railway is made, unless the player can't afford to bid on any available private railway companies. This exception is for later stock rounds where there are green privates available, but a player has spent all their money and doesn't want to be prompted to sell shares.
Fixes #11620.
This will not require any pins. There are games where players should have been given the option to participate in auctions, but these will not be broken by this change, as the pass actions have been inserted in the game action list.
- ~Add the `pins` or `archive_alpha_games` label if …
=> [1858] Disable autopass on private railway company bids

lib/engine/game/g_1837/game.rb, lib/engine/game/g_1837/step/token.rb
1837 has two graphs: a standard one and one that allows track to backtrack at junctions. The latter is needed for placing station tokens, where this type of route is allowed.
The token step was not using this graph, it was using the standard one. This meant that not all possible token locations were being included, and an auto-pass was being generated for the token step if the only possible token locations involved backtracking.
Fixes tobymao#11600.
This shouldn't break any games. There will be games where the BH should have been able to lay a token on its first turn but wasn't allowed to, but a pass action will have been generated for those turns and that will be in the game actions.
=> [1837] Use backtracking graph in the token step

lib/engine/game/g_1837/step/token.rb
PR tobymao#11602 has introduced an error. `G1837::Step::Token.can_place_token?` doesn't have an entity parameter, so is failing with `an Undefined method 'entity' for <Engine::Game::G1837::Step::Token>` error.
Fixes tobymao#11643.
=> [1837] Fix error in token step.

lib/engine/game/g_18_uruguay/game.rb
Fixes #11638
Did not check for nil before checking for closed
=> [18Uruguay] Check for nil before check for closed

lib/engine/game/g_18_usa/entities.rb
Removed unnecessary asterisks, which aren't present on similar private companies (e.g. P1 and P4)
=> [18USA] Remove asterisks from private P3's description

lib/engine/game/g_21_moon/entities.rb
Fixes #11658 
This will likely require pins for some 21Moon games.
=> 21Moon: Terminal teleport fix

lib/engine/game/g_1858/entities.rb, lib/engine/game/g_1858/game.rb, lib/engine/game/g_1858/graph.rb, lib/engine/game/g_1858/market.rb, lib/engine/game/g_1858/step/buy_train.rb, lib/engine/game/g_1858/step/route.rb, lib/engine/game/g_1858/step/track.rb, lib/engine/game/g_1858/trains.rb, lib/engine/game/g_1858_switzerland/entities.rb, lib/engine/game/g_1858_switzerland/game.rb
Ian D Wilson is working on a prototype of an 1858 based game set in India (the [rules](https://boardgamegeek.com/thread/3433590/article/45592411#45592411) and [map](https://boardgamegeek.com/thread/3433590/article/45482069#45482069) are on BGG).
This pull request refactors some of the 1858 code, to make the 1858 India implementation simpler.
- Remove the hard-coded assumption that broad gauge track is available from phase 2. Instead check the phase statuses to see when it is available.
- Adds `track_type` attributes to all the trains.
- Add a `private_railway?` method that is passed a company object and decides whether the company represents a private railway company, or some other type of private.
- Adds `type` attributes to all the company objects for the private railway companies, and …
=> [1858/1858 Switzerland] Refactoring in preparation for 1858 India implementation

lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/exchange.rb
The implementaion of ``priority_deal_player` in Game::Base can't always cope with players going bankrupt in stock rounds. It errors if the player who was last to act goes bankupt – all players are removed from a copy of the players array, then it fails to find the last to act player in the reduced list.
https://github.com/tobymao/18xx/blob/15ccfbf74b5549cb9f11e1178006aceb97ff857a/lib/engine/game/base.rb#L2897-L2914
This adds a fixed version of this method to the 18Ardennes code.
It would *probably* be safe to add this version of the method to the base class, but I didn't want to risk missing something a breaking lots of other games. It's impossible to bankrupt in stock-type rounds in most games. It is possible to go bankrupt in merger and acquisition rounds in 1817 and derivatives, but it …
=> [18Ardennes] Fix error when priority player bankrupts

scripts/validate.rb
This is a small tweak to the output of the validation scripts. It includes the list of variants/optional rules  selected for a game in the `validate.json` output file.
=> [Scripts] Include optional rules in validation script output

lib/engine/game/g_1858_india/entities.rb, lib/engine/game/g_1858_india/map.rb, public/icons/1858_india/BS+BT.svg
A few map updates from playtesting:
- Bombay [K6] starts as a yellow tile.
- Chittagong [I26] is an off-board area.
- Some tweaks to terrain costs and terrain icons.
Also fix a typo in border types.
=> [1858 India] Map updates

lib/engine/game/g_1858_india/entities.rb, lib/engine/game/g_1858_india/game.rb
PR #11652 added `type` attributes to private railways companies and trains in the 1858 code. This updates the 1858 India code to mirror this change.
This also fixes a mistake in the description text for the MA private railway company.
- ~Code passes linter with `docker compose exec rack rubocop -a`~
=> [1858 India] Add type attributes to companies and trains

lib/engine/auto_router.rb, lib/engine/game/base.rb, lib/engine/game/g_1860/game.rb, lib/engine/game/g_1862/game.rb, lib/engine/game/g_1870/game.rb, lib/engine/game/g_1873/game.rb, lib/engine/game/g_21_moon/game.rb, lib/engine/route.rb
In 1862, the autopather can't find paths which don't include the home token. This is because the check for the home token is in `check_overlap` when it should be in `check_other`. `check_overlap` is intended to be used to make sure trains don't reuse tracks whereas `check_other` is for checks that require the full set of routes to check the validity of. The key is that the autopather doesn't call `check_other` when calculating the set of all possible routes per train.
The main key is the autorouter suppresses `check_other` when looking for valid routes. If we move this code from `check_overlap` into `check_other`, then the autorouter can find routes that don't include the home token. I also moved the other two over because there isn't a reason to check them for single routes so we get a …
=> [1862] Fix autopathing issues

lib/engine/game/g_18_norway/depot.rb, lib/engine/game/g_18_norway/steps/buy_train.rb, public/fixtures/18Norway/18_norway_buy_ship.json, spec/lib/engine/games/g_18_norway/g_18_norway_buy_ship_spec.rb, spec/lib/engine/games/g_18_norway/g_18_norway_hovebanen.rb
Removed a bit to much in latest commit re-adding the filter for only one ship per type
=> [18Norway] Reimplement that you only are allowed to have one ship per  type

assets/app/view/game/hex.rb, lib/engine/game/g_1868_wy/step/development_token.rb
The `remove_hex_token` action is only currently used by 1868WY. I'm working on an implementation for 1858 India (a prototype from Ian D Wilson) that also wants to use this action.
There is a check built into the view class that only allows a hex token to be collected if it is owned by the currently operating entity. 1858 wants to use different checks: the tokens are neutral and can only be collected if the corporation has a route to the token, can afford to pay a fee and the game is in the correct phase.
This moves this check to a `check_hex_token?` method in the step class, and calls it from the view class. This means that 1858 India will just need to implement its own version of this method, with no logic changes to the view class.
- ~Add the `pins` or `archive_alpha_games` label if …
=> [Core/1868WY] Add method for checking if a hex token can be removed

lib/engine/game/g_18_ardennes/game.rb, lib/engine/game/g_18_ardennes/step/minor_auction.rb
The base implementation of `Game.reorder_players` can give an error after bankruptcies in a stock round. An out-of-bounds array access returns nil.
Fixes tobymao#11710.
=> [18Ardennes] Fix error after bankruptcy in stock round

lib/engine/game/g_1822_nrs/map.rb
There was a random hex duplicated in R31 completely outside of the map. This has been there since the game was first implemented 4 years ago, but definitely serves no purpose.
=> [1822NRS] removes erroneous hex from map

lib/engine/game/g_18_esp/meta.rb
The link for the game rules had broken. It looks like the BGG file page for the draft rules has been deleted now that a final version of the rules is available.
This updates the rules link to point to a BGG page for the final version of the Lonny Games rules. It also adds a link to the Playbook file page.
=> [18ESP] Updated rules URLs

lib/engine/game/g_1858_india/game.rb, lib/engine/game/g_1858_india/step/buy_train.rb, lib/engine/game/g_1858_india/step/route.rb
1858 India has mail trains. These are similar to 1822's Pullman trains, in that they are attached to another train and affect its run. They give a £10 revenue bonus for each large city or off-board area they visit.
Mail trains do not count towards the train limit, and a company that only owns a mail train can still use emergency money raising to buy another train.
=> [1858 India] Add mail trains

lib/engine/game/g_1858_switzerland/entities.rb
The VSB private railway company should be spelled "Vereinigtebahn", not "Vereingtebahn".
Fixes tobymao#11737.
=> [1858 Switzerland] Fix spelling of VSB private railway company

lib/engine/game/g_1858/step/buy_sell_par_shares.rb
I wasn't able to reproduce this myself, but someone else was getting errors when starting 1858 and 1858 India games in hotseat mode. The error was occuring when trying to place the first bid on a private railway company: `undefined method 'cash' for nil`.
This was occurring in the loop iterating over `@game.programmed_actions`. It was returning an element where `player` (the key) was nil and the `actions` (values) were an empty array.
This prevents the error by testing for the nil key.
=> [1858] Fix error in hotseat games

lib/engine/game/g_1849/step/bond_interest_payment.rb
Removes the `def blocks?` method from bonds, which was done when I was testing ideas to fix the previous bonds issue. I have come to realize that removing this caused the bonds interest to not be charged.
=> [1849] Variants - remove bonds block

lib/engine/game/g_18_norway/companies.rb
Fixes #11739
P1 was configured for hex I23 but should be J23. I23 doesn't even exist.
corrected ability and description.
=> [18Norway] fixes coordinates for P1 from I23 to J23

lib/engine/game/g_18_esp/game.rb, lib/engine/game/g_18_esp/step/home_token.rb
MZA and MZ share a single slot city in madrid (f24).
When mz is taken over, and MZA was placed as a cheater token, the closing of MZ doesn't remove the extra slot.
added minor code to fix this behaviour.
=> [18esp] fix mz mza cheater token

lib/engine/game/g_1847_ae/step/buy_single_train_of_type.rb
Fixes #11735
The rules say that a dividend is paid to the owner of LFK every time the first train has been bought from the Bank, but as implemented, the code was giving the dividend every time the first train was bought from anywhere other than the discards, which means it was also paying out if the first train was a cross buy.
This will require pins.
=> [1847AE] should LFK only pay on on first new train

lib/engine/game/g_1867/game.rb, lib/engine/game/g_1867/step/merge.rb, lib/engine/game/g_1867/step/reduce_tokens.rb
The fix for tobymao#8589 in PR tobymao#8689 was incomplete. It prevented public companies (majors) being given free tokens when three or more minors merged to form a major, but it did not handle the case of two minor companies with tokens in the same city being merged to form a new major. When this type of merger was being done, one of the two minor companies' tokens was being removed by the player and was returned to the minor's charter. The call  to `move_tokens_to_surviving` from `Step::ReduceTokens.process_reduce_tokens` was then moving this token from the minor to the major, where it was keeping the zero cost it had in the minor company.
This prevents this from happening by clearing all unplaced tokens from minor companies at the start of `move_tokens_to_surviving`. 1861/1867 does …
=> [1861/1867] Don't transfer zero-cost tokens from minors to majors

lib/assets.rb
The way to repro this bug is pretty simple:
- Load up a 1822 game (or substitute the instructions appropriately)
- `rm public/assets/g_1822.js.map`
- Touch a ruby file to cause rake to restart
- Refresh the 1822 game page and see an exception like:
```
"/18xx/lib/assets.rb:34:in `read'",
"/18xx/lib/assets.rb:34:in `extend'",
"/18xx/lib/assets.rb:204:in `block (2 levels) in combine'",
"/18xx/lib/assets.rb:202:in `map'",
"/18xx/lib/assets.rb:202:in `block in combine'",
"/18xx/lib/assets.rb:196:in `each'",
"/18xx/lib/assets.rb:196:in `combine'",
"/18xx/api.rb:74:in `block in <class:Api>'",
"/usr/local/bundle/gems/roda-3.55.0/lib/roda/pl
```
- If you refresh again it works because presumably somewhere the 18xx server is caching that it has built the files, but I don't know where.
This just …
=> assets: Require the source map to exist if it is enabled

assets/app/view/game/route_selector.rb, lib/engine/auto_router.rb, lib/engine/game/g_1822/game.rb
This was caught while rebasing my mass game replay tool and re-running them and while debugging https://github.com/tobymao/18xx/issues/11784. None are particularly fatal, but the inheritance on train_autoroute_group means that all the 1822 games will have subpar auto-routing when they have an E trains until it is merged.
I can split these into separate pull requests if desired, but they are all simple changes.
- Get the autogroup constant in ruby so the inheritance lookup rules are respected
- Delete a log statement that made debugging https://github.com/tobymao/18xx/issues/11784 annoying
- A pedantic detail on not errorring when no valid paths are available. This is caught by the testing harness, but the UI is the same
- Restore reading the settings for route + path timeout and then add …
=> Some minor autorouter bugfixes

lib/engine/game/g_1848/game.rb
Fixes #11764
Currently, players can sell one share of a corp, then another, then another, etc to cause multiple price drops in a single turn.  While the rules as written don't have a specific ruling against this, I know we encountered the same issue with 1844 and Helmut's ruling was that [you must sell all shares as a single block.](https://boardgamegeek.com/thread/3308703/can-players-sell-multiple-shares-in-a-company-one) Given that he's also the designer here, I would assume that holds true. 
I can try reaching out to him if we think a confirmation would be helpful.
=> [1848] must sell in blocks -> confirmed by designer

lib/engine/auto_router.rb
This was intended to be an array/non-nil check but unfortunately https://github.com/tobymao/18xx/commit/75be0ddd65e101037ac5f1d62b529a67fbbeec5d changed the behavior of how ruby's nil appeared in this code path (before it used to be undefined and now it is NilClass.. which seems to also have an length property :/ ). Switch from a truthy check to an explicit array check.
I tested 1858 (this has no train autogroup, so falls into the else),  1822 with a combo with no E train and a combo with both an E train and no Etrain (this falls into the code path for this if statement) as well as 1862 and ~dozen other games for good measure. Hopefully, this finally fixes this finicky codepath.
=> autorouter: Fix invalid array check

lib/engine/game/g_1858/game.rb
It was possible, when manually setting routes for trains in 1858, to route narrow gauge trains over broad gauge track, and to route broad gauge trains over narrow gauge tracks. These routes can never be legal, so it is better to make it impossible to select these routes.
This adds a `skip_route_track_type` method which makes it impossible to select a route with the wrong track type. Both narrow and broad gauge trains can still be routed over dual gauge track.
=> [1858 family] Enforce correct track types in route selector

Makefile, scripts/tag_deployment.sh, scripts/tag_name.rb
This adds `make tag` and executes it during `make prod_deploy`. It creates a git tag on the deployed commit. The tag name is a human-readable UTC timestamp that uses the same source as the timestamp shown on the `/about` page.
=> Create a git tag when deploying

lib/js_context.rb
An attempt to stabilize the test environment.
Try to ensures that the Opal runtime is available in the JavaScript context before any Opal-compiled code is executed.
=> Ensure that opal runtime is loaded

lib/engine/game/g_18_norway/game.rb
Fixes #11731
Can impact existing games
=> [18Norway] Stock movement should be left block if in bank pool and right block if sold out

lib/engine/game/g_18_norway/game.rb, lib/engine/game/g_18_norway/steps/buy_train.rb
Fixes #11799
Can break existing games
=> [18Norway] Include discount when calculating cheapest train price

lib/engine/game/g_18_royal_gorge/step/buy_train.rb
From page 13 of 24 in the [current rulebook PDF][0].
Check for the connection when processing the action--instead of when finding available trains to buy--to minimize the necessary graph checks.
Fixes #11364
[0]: https://boardgamegeek.com/filepage/284918/graphic-rulebook-preliminary
-----
Pins needed: any games where an illegal (unconnected) cross-buy occurred.
=> [18RoyalGorge] Require graph connection for cross-buying trains

DEVELOPMENT.md, Makefile, scripts/data_dir.sh, scripts/db/dump.sh, scripts/db/load_from_backup.sh, scripts/db_upgrade.sh, scripts/generate_logos.README, scripts/tag_deployment.sh, scripts/tag_name.rb, scripts/validate.rb
* DB scripts: get name of db container from `docker ps` output instead of using underscores (switched from underscores to dashes in a few places 63e2b22, but I missed some spots in my haste, and more importantly this new approach is not dependent on Docker version)
* add `-t` to `ssh` command in `make prod_deploy` so that the git tag creation script works during deployment
* use `print` instead of `puts` in `scripts/tag_name.rb` so that the newline does not get added to `$TAG` in `scripts/tag_deployment.sh`
* add more methods to `Validate` class in `scripts/validate.rb` for convenience when inspecting results and pinning/archiving
* explicitly set mode for `db/data/`
* `umask` should have covered this but apparently it did not work for @MatthewDeKoning when he was getting set up for …
=> [core] deployment/validation/getting started DB script fixes and enhancements

lib/engine/share_pool.rb
In games where multiple shares can be exchanged prior to parring the corporation, its possible that the presidents share is already acquired before the corporation is parred. Add additional logic to check for this case and properly mark the corporation as ipoed.
=> [Core] Set corporation as ipoed one first share purchase

assets/app/view/game/round/operating.rb, lib/engine/game/g_1858_india/game.rb, lib/engine/game/g_1858_india/step/buy_train.rb, lib/engine/game/g_1858_india/step/discard_train.rb, lib/engine/game/g_1858_india/step/route.rb
1858 India is almost ready to be moved to alpha status. All features have now been implemented, it is currently undergoing private alpha testing before it is moved to alpha on the main site.
This contains a few changes, mostly cosmetic.
1858 India has a couple of locomotive works private companies. These can be purchased by public companies from the bank during the buy trains step. The current rendering puts the private companies underneath the map in this step – this is reasonable because they usually won't be bought during the step. But 1858 India has a big map, so the privates are likely to be off the bottom of the screen and so forgotten about.
This adds a check for a `show_companies_on_left?` method in the step object, if this method exists and returns true then the buyable privates …
=> [1858 India/Core] Add option to show private companies on the left in the buy trains step

lib/engine/game/g_18_norway/game.rb, lib/engine/game/g_18_norway/round/stock.rb
Fixes #11823
Market adjustments for minors at the end of a stock round which were sold out or that had shares in the market weren't happening. This is because, by default, that operation excludes minors. I added a stock.rb file to 18_Norway that modifies the `corporations_to_move_price` method to include them, and then pointed the game.rb file to G18Norway::Round::Stock.
Likely all active games will need to be pinned or nuked.
=> [18Norway] fix price change after SR

lib/engine/share_pool.rb
Fixes #11790
A user noted that 18USA lists the name of the corp and the player when taking loans in 18USA, but not when the corp issues or redeems shares. 
These later elements appear in the share_pool.rb file. It could be clearer if this information was included in all games where corps can take stock actions, so I made some edits to share_pool.rb to apply this site-wide. 
I borrowed the basic idea from 1817 here:
https://github.com/tobymao/18xx/blob/6c5692516add29893e8e07b95ed9c6eabc1c579e/lib/engine/game/g_1817/game.rb#L694-L695
Please let me know if I've overlooked anything!
=> [base] - updates log to include player name when corp takes SR action

lib/engine/game/g_1822_nrs/map.rb
Fixes #11791
Scott Petersen confirms on [BGG here](https://boardgamegeek.com/thread/3524561/article/46189461#46189461) that there should be stub track in hex M28 to prevent LNWR from being locked into its home.
=> [1822NRS] adds London stub for LNWR

docker-compose.dev.yml, models.rb
replace previous default which spews a ton of output when connecting to the DB
if you still want that verbose db output, now you can set DB_LOG_LEVEL in the Docker Compose configuration
=> [dev] allow all Logger values for DB_LOG_LEVEL in dev, default to fatal

lib/engine/auto_router.rb
Fixes https://github.com/tobymao/18xx/issues/7982 as well as a bug I found while testing the fix.
I left a note on a possible optimization for skip_paths for games that use TRAIN_AUTOROUTE_GROUP (1822 family is the prime example). But I avoided doing it because it's complicated and didn't want to mess it up. So I focused on the bug fix (allow re-using paths with routes that are prefilled) .
The two bugs fixed:
- We still calculated all paths for trains that were prefilled. This is completely wasted work. I can't figure out how this happened, but it's been in the repo for 6+ months and scrolling through history I don't see an obvious spot that caused the bug. I'm not good enough at ruby + our frameworks to know if this is something that used to/should work.
- If the game rules allow routes …
=> Autorouter: Allow overlapping routes with pre-filled trains and don't search for routes for pre-filled trains

lib/engine/game/g_18_india/step/sell_once_then_buy_certs.rb, lib/engine/game/g_18_india/step/track.rb
Fixes #11483.
adds simple check to ensure ipo not purchased SR1, fixes ferry tile placement to only show legit placements vs throwing error on incorrect placement. 
^ the above tests have been run - i am sadly ignorant of how to add the tag "archive_alpha_games" which this needs.
=> [18 India] fixed sr1 buy issues and cleaned up ferry tile fix #11487and #11810

lib/engine/game/g_18_mex/game.rb
Fixes #11462
Simple bug fix.
Bug was caused by an attempt to remove the P2 ability when upgrading F5 to green. This had already been done when yellow non-470 tile was put there, so the ability did not remain.
Fix was just to not remove if ability already lost.
None. Tested manually to do the upgrade of F5, and after bug fix it works.
None
=> [18MEX] Correct bug for upgrading F5 for non-470 tile #11462

lib/engine/game/g_1825/meta.rb
Fixes #11855
Unit 2 should support 2-4 players. It looks like the cert limit and starting cash were all configured to support 4 players, but then the meta page only listed 2-3.
Tiny little fix!
Confirmed here: http://www.fwtwr.com/18xx/info/inv-1825-unit2.asp
=> [1825] Unit 2 should support 4 players

assets/app/lib/settings.rb, assets/app/view/create_game.rb, assets/app/view/user.rb, models/user.rb
* now players that want auto-routing to always be on won't need to remember to check the box when they create a new game (see https://github.com/tobymao/18xx/issues/6598#issuecomment-1009393255); and of course the same applies for the "Live" label and invite-only games
* also fix error in console on create game page when clicking on async/live; `is_async` was undefined, so an error was thrown instead of of the `is_async` param getting updated
=> [User/Create game pages] Add user settings for default game options

lib/engine/game/g_system18/map_ms_customization.rb
Fixes #11913 
May require pins
=> [System18] MS map train roster update

lib/engine/game/g_1873/game.rb
=> [1873] Fix check_intersection with empty trains

lib/engine/game/g_system18/map_ms_customization.rb
Fixes #11925
At least one finished game needs to be archived.
=> [System18] MS map EMR change

.rerun.amd64, DEVELOPMENT.md, Dockerfile.amd64, db/Dockerfile.amd64, docker-compose.dev.yml
As of this writing, these are the instructions for Apple Silicon currently on the wiki:
> ### Developing on Macbooks with Apple M1/M2 chip
>
> Some modules don't fully support Apple Silicon chips yet so you need preparations:
>
> 1. If you use Docker Desktop, enable `Use Rosetta for x86/amd64 emulation on Apple Silicon` in Docker Desktop / Preferences / Features in development
> 2. Edit `Dockerfile`, replacing `FROM` in line 1 with `FROM --platform=linux/amd64`
> 3. Edit `db/Dockerfile`, removing [lines 3 to 9](https://github.com/tobymao/18xx/blob/943f42ef2afc23342fa62b2c5e2be94073dde23f/db/Dockerfile#L3-L9)
> 4. Create a file named `.rerun` with following line in it `--force-polling`
> 5. Follow usual steps on starting the app
With this commit, instead of steps 2-4, the env var …
=> [dev] Apple Silicon setup for local dev via env vars

assets/app/view/game/par.rb, assets/app/view/game/round/auction.rb, assets/app/view/game/round/stock.rb, assets/app/view/game/stock_market.rb
This does not fix any issue, but is a preparation for 1824 mainly.
It should not affect any existing games.
For games not imp,ementing par_chart this change will have no effect at all.
In case a game does implement par_chart by creating information this will cause a slight degradation. But if the game does cache its par chart the effect will be minimal.
The idea is that it should be possible to remove a par chart from a game that inherits from a game that uses it.
By adding the check for non nil, the affected game can implement par_chart and let it return nil.
None. But I have created hotseat games of 1837 and 1880, and checked Market view, and it worked as it should.
N/A
=> Make it possible to disable par_chart in derived games

lib/engine/game/g_1837/game.rb
No issues reported yet, but it probably causes problems in 1837 games
stock_market does not have a hex_market method, it should be hex_market?
Change was done in 1837 to cater for 1824, but a mistake was made. This commit fixes that.
N/A
N/A
=> [1837] Correct method call, adding missing ?

lib/engine/route.rb
When an old route is being loaded, either for route history or to populate the route selector, we attempt to map the route onto upgraded tiles.
Part of this process is done in `Route.find_matching_chains`. If there are multiple candidate routes between tiles A1→B2→C3 it will look for nodes that were on the previous route. If the previous route visited nodes A1-0, B2-1 and C3-1 it will prefer a candidate route that includes all three of those nodes. But if no candidates include all three nodes then the first candidate route is returned.
This algorithm was failing in [game 211985](https://18xx.games/game/211985), resulting in a broken route being loaded.
At [action 541](https://18xx.games/game/211985?action=541) in OR8.3, N runs its 5+5 train through the town on hex F16.
On its next …
=> [Core] Tweak to algorithm for restoring previous routes

.gitignore, DEVELOPMENT.md, Dockerfile.amd64
followup to [#11930](https://github.com/tobymao/18xx/pull/11930)
copying the file in the Docker image doesn't really work due to mounting the
whole directory; macOS users can set up a symlink for `.rerun`
[`direnv`](https://direnv.net/) is a tool that reads `.envrc` files when you enter that directory; now
I have `export DEV_DOCKERFILE=Dockerfile.amd64` saved in my `.envrc` so that it
will always be set correctly in my terminals, and with it gitignored it won't
break anything for non-mac contributors
=> [dev] for macOS: ignore `.rerun`, add recommendations

lib/engine/game/g_18_gb/step/buy_sell_par_shares.rb
In 18GB the president's certificate can be sold to the share pool, and the corporation is placed in receivership. Once this has happened, a player is not allowed to directly buy the president's certificate. They must either buy two single shares (from either the IPO or the pool) or buy a single share and then buy the president's certificate from the pool and place the single share back in the pool.
This check was not in place and a player who did not own any shares in a company was being given the option to buy the president's share from the pool.
Fixes tobymao#11886.
There is at least one game broken by this (at [action 295 of game 208720](https://18xx.games/game/208720?action=295)).
=> [18GB] Restrict buying president's certificate from the pool

lib/engine/game/g_1824/game.rb
Fixes 11988
This should not break any game. And it wont fix the game broken in #11988 - that game can be archived.
Just ensure exchange_entities returns 0 or 1 companies.
If a player owned multiple MRs, when doing forced MR exchange, when player clicked on an exchangeable corporation one button with "Exchange X for 10% share" appeared. If the player does not click on the top one, but one of the ones below, this caused the game to break.
By only showing one button in this situation the user cannot trigger this bug.
N/A
N/A
=> [1824] Avoid showing multi exchange buttons #11988

lib/engine/game/g_1824/game.rb
Corrected this bug by adding a check that upgrade of yellow town tile is only allowed it is a single town (both from and to) and to a green tile.
Fixes #11993 
Fixes #12002 
**Note! The bug led to an illegal upgrade in one game. That game will break and can be archived. Games without illegal upgrades will not be affected.**
Code is a change from 1837 as they have different rules. But the check in 1824 did not check that
it was a single town upgrade to green. Have now added that to ensure only single towns can be upgraded.
The bug made it possible to upgrade yellow single town to yellow double town, which is illegal.
Double towns has now disappeared from chices
None
=> [1824] Disallow upgrade of yellow one town to yellow two town #11993

lib/engine/game/g_1862/meta.rb, lib/engine/game/g_1862_solo.rb, lib/engine/game/g_1862_solo/corporation.rb, lib/engine/game/g_1862_solo/game.rb, lib/engine/game/g_1862_solo/meta.rb, lib/engine/game/g_1862_solo/step/buy_sell_par_shares.rb, lib/engine/step/buy_sell_par_shares.rb
This is a commit that adds the solo variant to 1862 as prealpha. It should not affect existing implementation of 1862.
This is an initial commit that just do some setup, and display IPO rows in SR. It is based on 1862 base game.
It is far from playable, so it is in prealpha.
Have not added permits a la 1862 solo yet (6 permits - 2 of each - are used, and corporation gets the first one when it is parred). Instead the base 1862 mechanism is used.
My idea is to continue with SR work to get that to work, before I make the next PR. But it requires some architectural decisions how to handle the SR actions specific to 1862 Solo before I can continue.
Initial commit.
Stock Market:
Timeline about IPO rows:
Entities view:
None
=> [1862] Initial commit to add solo variant to 1862 (EA)

lib/engine/game/g_1824/game.rb, lib/engine/game/g_1824_cisleithania/game.rb
Could cause initial operating to fail for Staatsbahn that form between ORs.
Fixes #12007
I think this should not cause any game to fail, rather it will fix games that has gotten stuck on the error.
HomeToken step was missing, which ment that pending_tokens was not defined.
Unclear why this works sometimes?
See Implementation notes.
N/A
N/A
=> [1824] Add missing HomeToken step, fixes #12007

lib/engine/game/g_system18/game.rb, lib/engine/game/g_system18/map_ms_customization.rb, lib/engine/game/g_system18/map_russia_customization.rb, lib/engine/game/g_system18/step/buy_sell_par_bid_merge.rb, lib/engine/game/g_system18/step/buy_train.rb
Fixes #12016
Fixes #12023 
Fixes #12025 
Fixes #12028
Fixes #12032 
Will likely require pins.
For Russia map:
1. Fixed game ending too late when 8 train was exported
2. Fixed issue when auto-passing immediately after a minor was auctioned in a SR
3. Fixed problems with nationalizing a corp with shares in market and/or more tokens than SPX could take
For Mississippi map:
1. Fixed player ordering that wasn't happening after a SR
2. Fixed bug with giving "used" trains warranties
=> [System18] Russia and Mississippi fixes

lib/engine/game/g_1822_pnw/game.rb
Starting price should be $50, which is apparently the "last" par price, while $100 is the "first".
Fixes #11959
=> [1822PNW] fix share prices for starting minors in Starting Packet Variant

lib/engine/game/g_1822/game.rb, lib/engine/game/g_1822/step/acquire_company.rb, lib/engine/game/g_1822_africa/game.rb, lib/engine/game/g_1822_ca/game.rb, lib/engine/game/g_1822_mx/game.rb, lib/engine/game/g_1822_pnw/step/acquire_company.rb
As a player, I may have been burned a couple times by forgetting to acquire private companies in the last OR before a SR where cert limit was going to matter.
=> [1822 family] add help text to acquire_company step about cert limit

lib/engine/game/g_1822/step/minor_acquisition.rb
Fixes #12018
Pins are theoretically possible, but I think unlikely to be needed.
=> [1822] allow acquiring for two shares if major is in yellow

scripts/validate.rb
No more need to list all the 1822-related titles, now `families: ['1822']` or even
`families: ['1822PNW SRS']` will find all of the relevant titles.
=> [dev] validate.rb: improve experience for dealing with related titles

scripts/db/create_scrubbed.sh, scripts/db/dump.sh
* copy-pasting the old "scrub the local data" command lead to this error:
> `bash: !": event not found`
* apparently the user on the db container is root and there is no "db" user?
=> [dev] fix quotes in db script, fix scripts/db/dump.sh

lib/engine/game/g_system18/meta.rb
Just a small thing I thought of when I came across System18's `meta.rb` while looking at #11973 and #12000. Seems easier to deal with long-term.
=> [System18] make all optional rules automatically mutex

lib/engine/game/g_1824/game.rb, lib/engine/game/g_1824_cisleithania/game.rb
1824 Cisleithania setup for 2 players did modify 1824 which caused validation to fail.
**Note! When I run activate_all for 1824 family (with this commit applied) it shows that 2 1824 Cisleithania games are broken. But this was caused by the fix for player order during SR1 that was merged last week.**
Uses deep_freeze as well as avoiding modify base when setting up 1824 Cisleithania.
Similar change that 1849 did.
N/A
N/A
=> [1824] Add deep freeze of trains

lib/engine/game/g_18_usa/game.rb
Do not merge this PR directly; see #12086
----
* requires `end_game!()` to be called with the reason for ending it
* expose the reason `.game_end_reason`
* require fixtures to have a `game_end_reason` key
* require alpha games to have at least one fixture with a `game_end_reason` that is not `manually_ended`
* require beta/production games to have at least one fixture for each `game_end_reason`
* exceptions do currently exist in constants at the top of `spec/lib/engine/fixtures_required_spec.rb`; no examples for those title/game end reason combinations were found in the real DB
=> [dropped cash 3/5] add `game_end_reason` to Game object, add tests requiring it for fixtures

lib/engine/game/g_18_ny/step/buy_train.rb
Do not merge this PR directly; see #12086
----
I found some weird behavior and comments--plus a lot of duplicated code--around
player loans while I was working on other parts of #12000. It seemed best to
handle the loan-specific changes separately from the rest.
* `G1844:Player` was added only for tracking `@debt`; move that onto
`Engine::Player`, and add `@penalty` for debt which counts against the
player's score but can never be repaid
* add debt and loan methods to `Spender`
* add `@debt` to the Bank, so that all debt given to players can be tracked; add
test for each fixture to ensure the net debt is 0
* add methods and constants to `Game::Base` to manage player loans
Notable assumptions:
1) loans are not really outside money
Loans weren't always taken from the bank; there was a …
=> [dropped cash 4/5] fix player loans, refactor player loans into base engine objects
